from pathlib import Path
import json,hashlib,sqlite3,importlib.util,time,shutil
from PIL import Image
R=Path.cwd();D=R/'evaluations/T-0817';P=D/'preparation';start=time.monotonic()
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def load(p):return json.load(open(p))
def save(n,v):(P/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
base=load(P/'baseline-v1.json');MAIN=R/base['main']['path'];assert sha(MAIN)==base['main']['sha256'];sp=importlib.util.spec_from_file_location('h',R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py');h=importlib.util.module_from_spec(sp);sp.loader.exec_module(h);c=h.conn(MAIN);assert h.state(c)==base['state']
r=h.native(c,h.current(c,'R-508b3628d54f6430658fa240'));assert r['id']=='R-508b3628d54f6430658fa240@1';save('exact-current-record-v1.json',r)
asset=r['assets'];assert len(asset)==1;path=R/asset[0]['asset_path'];digest=sha(path);assert digest=='04155810d3ffc48a324e060e2a8d2fe30c5da612d8f84a670402ced1fdcaed3f';meta=dict(c.execute('select * from asset where path=?',(asset[0]['asset_path'],)).fetchone());assert meta['sha256']==digest and meta['bytes']==path.stat().st_size
with Image.open(path)as im:dimensions=list(im.size);fmt=im.format;orientation=im.getexif().get(274)
assert dimensions==[6284,4700]
source_id=r['data']['source_id'];source=h.native(c,h.current(c,source_id));save('exact-current-source-v1.json',source)
citation=R/'genealogy/citations/C-0446-hemsjo-AI4-sven-olofsson-familj-sida-98.md';(P/'C-0446-frozen-textual-context.md').write_bytes(citation.read_bytes())
save('single-original-metadata-input-v1.json',{'record_revision':r['id'],'source_revision':source['id'],'citation':'C-0446','image_id':'C0043834_00110','path':str(path.relative_to(R)),'sha256':digest,'bytes':path.stat().st_size,'dimensions':dimensions,'format':fmt,'EXIF_orientation':orientation,'canonical_record_asset':asset[0],'canonical_asset':meta,'provenance_text':'Frozen accepted C0446 citation and exact native record/source/origin metadata; no new access or provider-version assertion','provider_version':'unknown unless exact existing source metadata specifies otherwise','reading_scope':'Brita P0337 complete ownrow including correct headers/dittos/blanks/margins and necessary attribution ONLY; no other family ownfield extraction','crop_status':'No derivative generated; full exact original is supplied. Row/header coordinates to be determined independently by SOURCE readers; no invented row-location metadata.','original_images':1,'new_downloads':0,'mechanical_image_inspection':'Only file hash/header dimensions/EXIF metadata; no content interpretation'})
owner=load(R/'evaluations/T-0813/preparation/all-current-OWNER-scope-v1.json');assert len(owner['OWNER_full_native'])==45;assert all(h.current(c,x['object_id'])==x['id']for x in owner['OWNER_full_native']);save('OWNER45-current-reuse-proof-v1.json',{'all45_current_heads_exact':True,'scope_packet':'evaluations/T-0813/preparation/all-current-OWNER-scope-v1.json','full25bases_and6PCDsections_reused':True,'new_mandate_PCD003':'Latest PROJECT-CONTROL snapshot supplied; this authorizes exact T0817/18/19 run, not new OWNER fact expansion.'})
prior=load(R/'evaluations/T-0815/root-actual-final-verification-v1.json');assert prior['main_sha256']==base['main']['sha256'];save('accepted484-receipt-journal-reuse-v1.json',{'main_identical_to_accepted_actual484':True,'actual_result':'evaluations/T-0815/root-actual-final-verification-v1.json','all50_actual_comparison':'evaluations/T-0815/actual-main-stage-comparison-v1.json','prefix483_reconciliation':'evaluations/T-0815/preparation/actual-accepted-reconciliation-v1.json','accepted484_journal':str(next((R/'genealogy2/journal').glob('000000484-*')).relative_to(R)),'no_accepted_source_reading_repeated':True})
for name in ['AGENTS.md','wotan/README.md','wotan/dev-log/T-0817.md','PROJECT-CONTROL.md','genealogy2/docs/working.md','docs/research/person-contract.md','docs/research/source-strategy.md']:
 q=P/'normative-snapshots'/name;q.parent.mkdir(parents=True,exist_ok=True);q.write_bytes((R/name).read_bytes())
for pid in ['P0269','P0270']:
 p=Path('/private/tmp/slaktforsk-T0817-'+pid+'-start.json');assert p.exists();q=P/(pid+'-baseline-pedigree.json');q.write_bytes(p.read_bytes());assert len(load(q)['paths'])==41
backup=P/'baseline484.sqlite';assert not backup.exists();shutil.copyfile(MAIN,backup);assert sha(backup)==base['main']['sha256'];assert h.state(h.conn(backup))==base['state'];save('baseline-all50-v1.json',h.all50(c))
focal=load(P/'native/P-0337.json');relations=[x for x in focal['current']if x['kind']=='relation'];save('current-semantic-consequence-input-index-v1.json',{'focal':'P-0337','complete_fullnative':'evaluations/T-0817/preparation/native/P-0337.json','fullperson':'evaluations/T-0817/preparation/current-full/P-0337.json','all_body_caveat_data_status_outcomes_structured_fields':'Included exactly in full native packet; no correction/PASS ordering by Sol','source_record':'R-508b3628d54f6430658fa240@1','current_full_relations':relations,'protected_child':'P-0287','direct_bound_and_current_stronger':'evaluations/T-0817/preparation/native-support-versions-v1.json','no_interpretation':True})
assert sha(MAIN)==base['main']['sha256'];save('preparation-result-v1.json',{'state':h.state(c),'main_unchanged':True,'baseline_copy_sha256':sha(backup),'original_hash_dimensions_and_registered_asset_exact':True,'original_scope_count':1,'new_original_acquisition':0,'image_content_interpretation':0,'native_or_queue_changes':0,'OWNER_current':45,'relations_in_focal_native':len(relations),'elapsed_sealing_seconds':time.monotonic()-start,'capture_result':load(P/'capture-result-v1.json')})
reuse=[path,citation,R/'evaluations/T-0813/preparation/all-current-OWNER-scope-v1.json',R/'evaluations/T-0815/root-actual-final-verification-v1.json',R/'evaluations/T-0815/actual-main-stage-comparison-v1.json',R/'evaluations/T-0815/preparation/actual-accepted-reconciliation-v1.json',R/'evaluations/T-0815/root-actual-inventory-full-v2.json',R/'evaluations/T-0814/preparation/PCD-2026-10-08-002-snapshot.md',next((R/'genealogy2/journal').glob('000000484-*')),D/'root-start-baseline-v1.json',D/'collect_usage.py',R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py']
files={p.resolve()for p in P.rglob('*')if p.is_file()};files.update(p.resolve()for p in reuse);pins=[{'path':str(p.relative_to(R)),'sha256':sha(p),'bytes':p.stat().st_size}for p in sorted(files)]
save('locked-input-manifest-v1.json',{'task':'T-0817','state':base['state'],'main_sha256':base['main']['sha256'],'baseline_copy':'evaluations/T-0817/preparation/baseline484.sqlite','focal':'P-0337','protected_child':'P-0287','source_record_revision':r['id'],'original_ceiling':1,'original_scope':'Only C0043834_00110/full Brita ownrow; no extra source/person pass','original_metadata':'evaluations/T-0817/preparation/single-original-metadata-input-v1.json','fullperson_index':'evaluations/T-0817/preparation/current-person-index-v1.json','native_support':'evaluations/T-0817/preparation/native-support-versions-v1.json','pins':pins,'source_interpretation':False,'native_or_queue_writes':0,'reading_release':'ROOT ONLY after exact lockverification; two separate Astra own readings before claims comparison'});print('manifest',sha(P/'locked-input-manifest-v1.json'),'pins',len(pins),'original',digest,dimensions)
