import json,sqlite3,hashlib,datetime,re
from pathlib import Path
p=Path('evaluations/T-0828/independent'); c=sqlite3.connect('file:genealogy2/data/research.sqlite?mode=ro',uri=True);c.row_factory=sqlite3.Row
rows={};groups=[]
def native(oid):
 o=c.execute('select kind from object where id=?',(oid,)).fetchone()
 if not o:return None
 r=dict(c.execute('select * from revision where object_id=? order by version desc limit 1',(oid,)).fetchone());rid=r['id'];d=[dict(x) for x in c.execute('select * from '+o['kind']+' where revision_id=?',(rid,))]
 return {'revision':r,'data':d[0] if len(d)==1 else d,'evidence':[dict(x) for x in c.execute('select * from dependency where revision_id=? order by basis_revision_id,role',(rid,))],'origins':[dict(x) for x in c.execute('select * from origin where revision_id=? order by unit_id',(rid,))]}
def add(g,ids,fields,decision,basis,status='REVISE_SCOPED'):
 item={'group':g,'fields':fields,'decision':decision,'basis':basis,'status':status,'targets':[]}
 for oid in dict.fromkeys(ids):
  n=native(oid)
  if not n:raise Exception('missing '+oid)
  rows[oid]=n;item['targets'].append({'object':oid,'revision':n['revision']['id']})
 groups.append(item)
source='source-concurrence-eight-v1.json; primary C0626 v2/Rotman v1; exact own original-first v2/v3/v4'
add('C626-structured',['O-P-0451-C0626-own','M-P-0451-C0626-own','ID-P-0451-C0626-own','F-P-0451-birth_assessment-three-forms','F-P-0451-source_assessment-own-life-limits','F-P-0463-source_assessment-later-Rundbacken','F-P-0464-source_assessment-later-Rundbacken'],['value_literal','value_json','role_literal','caveat','rationale'], 'Apply exact C626 full-field map, reserved Rundb.[?] instead of Ljust.[?], right-year unextracted false and actual annual map. F451 C626_missing_full_images=[]/right_year_fields_unextracted=false; birth_assessment original_late_place=Rundb.[?]. F463/F464 three flags false/[] only with tested_reserved field maps. Preserve C0678 other missing material, source variants, provider assertions and all unrelated flags.',source)
add('Henrik-hidden-structured-route',['F-P-0338-source_route-precise-open-and-historical'],['value_literal','value_json'],'BI1_1850_day_ditto_and_headers_unresolved=false on accepted T826 1November1850 extraction; remove C0033130_00015 and C0033097_00044/45/46 from missing_full_copies. Preserve AI7s201/AI8s203/childhood1829–50, secondarychildren and all other life/source routes. Do not claim source-time continuity.','T826 accepted C0625 audit + C626 new audit')
add('P451-source-quality',['RESEARCH-P-0451-9d76f0343410','KEY-P-0451-5197d84d6ca2','PATH-P-0451-KP-03','CONTRACT-P-0451-PK-05','CONTRACT-P-0451-PK-11'],['body','outcome','caveat','rationale'],'Close exact C626 full-copy/right-field debt and correct reserved original birthplace. PK05 criterion outcome pending explicit primary narrow judgment; PK11 retains EJ STYRKT because C0678 separate missing originals remain. No person-wide or native gate upgrade. Preserve exact older failed/reading text explicitly historical only for replaced C626 scope.',source)
add('P452-source-quality',['F-P-0452-source_assessment-own-life-limits','RESEARCH-P-0452-9d76f0343410','PATH-P-0452-KP-03','CONTRACT-P-0452-PK-11'],['value_literal','value_json','body','outcome','caveat','rationale'],'C0626_three_full_copies_missing=false. Explicit C626 debt closed; bounded Brita absence1860–70 does not prove death1850 or earlier residence. Preserve laterAI2s30/C1s99 untested. PK11 sole-copy outcome pending primary narrow concurrence; no new side-person native/fullcontract PASS.',source)
# current own-source semantic copies: whole rows already reviewed in full-person/closure sets
seed=json.loads(Path('evaluations/T-0828/preparation/current-relevant-native-v2.json').read_text())
for person,pat in [('P-0336',r'C0?473|Rot[em]man|roteman|sju.{0,15}(kort|post)|fem.{0,20}(kort|post)|septemberavvik'),('P-0338',r'C0?626|C0?625|00044|00045|00046|kopie|fulloriginal')]:
 ids=[]
 for x in seed:
  d=x['data']; r=x['revision']; text=json.dumps(d,ensure_ascii=False)+' '+r.get('caveat','')
  if isinstance(d,dict) and d.get('subject_id')==person and re.search(pat,text,re.I) and r['kind'] in ['assessment','narrative','question','fact']:
   ids.append(r['object_id'])
 add(person+'-current-semantic',ids,['body/markdown','outcome where exact criterion/path scope changes','caveat','structured exact debt flags','rationale'],'Update only actual current own extraction/copy/gate scope. Preserve explicitly superseded historical sections. Olaus: native identity PK11 closes7, legacy PK11 remains exact wider debt; PK05 STYRKT. Native review/tree existing pair revised, tree evidence binds exact new review; adults/descendants positive support required. Henrik: PK11 STYRKT/native passed+supporting with existing adult/downward chain, upward4relations stayLEAD. For Olaus September caveats distinguish resolved C0474 false24 from real1853/1854 sourceyears. New fields cannot silently erase unrelated routes. Retain all original evidence/origins and rationale history; current amendment must acknowledge new source work.',source)
add('Robert-display-period',['RESEARCH-P-0367-9d76f0343410','THEME-P-0367-BO','THEME-P-0367-SYN','CONTRACT-P-0367-PK-03','F-P-0367-life_scope-registration-not-travel-or-lifetime','F-P-0367-residence_context-linked-rote1878-1884'],['body','caveat','value_literal','value_json'],'Replace current total-no-read-post1890–96 with exact displayed Robert1878-06-07 period1891–96 on434840120030. Full_chain_read remains false; own relative card and exact move date not read. Earlier displayed1878–79/1879–84 may qualify precise_child_dates unextracted but cannot claim individual move dates. Preserve birth7June, ownHudiksvall1896-12-29/1898 departure and later unresearched scope.',source)
add('Johanna-post1910',['BIO-P-0397','RESEARCH-P-0397-9d76f0343410','THEME-P-0397-BO','THEME-P-0397-SYN','THEME-P-0397-SAM','CONTRACT-P-0397-PK-03','PATH-P-0397-KP-02','P-0397/Q-02','KEY-P-0397-ca951b802563'],['markdown/body','outcome of path only','caveat'],'Add exact displayed Fredberg /Jansson/,Johanna Ch...1866-10-16,1911–15 on030080030190; no claim everything after1910 unread. Remove blanket prohibition on source surname Fredberg; preserve raw truncation. Olaus Gift is his status, household period not individual marriage/dying boundary. Do not automatically replace marriage end interval1910–25 with1915–25. Path partial relevant registercontext read, owncard/laterhousehold/death/divorce remain unresearched. Preserve own Skånela/1888original stronger support.',source)
add('Oskar-Elvira-post1910',[f'{a}-P-{person}{b}' for person in ['0492','0493'] for a,b in [('BIO',''),('RESEARCH','-9d76f0343410'),('THEME','-BO'),('PATH','-KP-02')]]+['P-0492/Q-02','P-0493/Q-02'],['markdown/body','outcome of path only','caveat'],'Add displayed OskarFredrik1895-10-16 and ElviraFredinaGully1902-11-28 each1911–15 on030080030190. Replace zero-read-source1910→death claim with exact bounded anchor and remaining gaps. No individual moves/civilstate/occupation/continuity/laterlife inferred.',source)
# household surname/birth-source precision explicitly inspected full bodies and structured facts
house=json.loads((p/'semantic-household-targets-v1.json').read_text())
ids=[]
for x in house:
 oid=x['object_id']; subj=x.get('subject_id'); body=str(x.get('body',x.get('markdown',x.get('value_text',''))))+' '+str(x.get('value_json',''))
 if subj in ['P-0489','P-0490','P-0491','P-0492','P-0493'] and (re.search(r'efternamn|Dagen kommer|dagen kommer|exakta dagen|late_name_limit|grave_name_limit',body) or oid.startswith('BIO-')) and not ('/Q-02' in oid or '-KP-02' in oid or '-HAL' in oid):ids.append(oid)
add('Five-known-household-persons-name-date-context',ids,['body/markdown','value_literal/value_json.late_name_limit or grave_name_limit','caveat'],'Exact new displayed lists also attest Fredberg surname and exact birth dates for already-correlated P0489 Augusta1890-09-05 (1891–97/1897–1907), P0490 Esther/Ester1891-12-21 (sameperiods), P0491Edit1894-04-13 (1894–97/1897–1907), P0492Oskar1895-10-16 (1895–97/1897–1907/1911–15), P0493Elvira1902-11-28 (1902–07/1911–15). Amend exclusive late-grave-first/only-date assertions; original census no-surname observation remains true. Independent birthoriginals remain unread; same administrative-chain context not a new birth proof. Edit real1894/1895 conflict remains. Do not add1911–15 presence to Augusta/Ester/Edit absent from displayedcard. Preserve grave-copy unknown metadata and individual grave facts; no native/legacy identity grade auto-upgrade.',source)
# narrow additional reviewed scope retained, no blind rewriting source-specific truths
retains=['BIO-P-0367','PATH-P-0367-KP-02','PATH-P-0395-KP-04','PATH-P-0396-KP-04','CONTRACT-P-0395-PK-05','CONTRACT-P-0396-PK-05','CONTRACT-P-0396-PK-08','THEME-P-0396-BO','RESEARCH-P-0396-9d76f0343410','PATH-P-0489-KP-02','PATH-P-0490-KP-02','PATH-P-0491-KP-02','P-0489/Q-02','P-0490/Q-02','P-0491/Q-02','O-P-0451-C0593-biography','O-P-0338-C0520-Erik']
add('Individually-retained-boundaries',retains,['all current fields'],'RETAIN current scoped statements: T0820 explicit historical continuation closure already sufficient; provider literal facts not rewritten as original. Ruth display1891–95 does not change ownHudiksvall1896arrival, no intervening continuous presence or transfer of father dates. Robert biography not falsely claiming absence1890–96. Augusta/Ester/Edit after1910 gap not closed by their absence from 1911–15 household list. No retrospective new noll or independent-side research.',source,'RETAIN')
# source structures are directly assigned, do not impose inferred household roles
extras={'exact_source_payload_requirements':['Five own mention name_literal must follow own displayed forms:03854/43487 just OlausFredberg; othernew3 OlausFredbergFredriksson. Occupation03008=Stationskarlsförman; absent household-role field stays empty/qualified.','Existing T82604601 settled full extraction spells Fredrikson single-s; align own mention only if current differs, using accepted audit without rereading original. Two existing T826 owncard caveats may close remaining5card debt, no other reread/rewrite.','S0376 current description contains legacy24Sep C0474; if revised individually clarify accepted4Sep1852/current7completeHTML and exact old capture unknown; preserve true1853/1854 and nonindependence. Sourcehead update is optional if audit/currentassessment sufficient and no active false claim remains.','P0451 C0624 READ/record caveat Tyske birth-place wording is not stronger birthplace proof; actual accepted O/ID shows Tyske home only. Preserve or explicitly scope historical mistaken caveat; no new raw birth inference.'],'other_retain_scopes':['P0337 own role/residence not borrowed from Olaus; his1878-05-22 move cannot be her exactmove solely on displayedhouseholdperiod. Accepted T0826 1879–84 householdcontext sufficient reuse; no independent original claim from currentHTML.','P0489/P0490/P0491/P0492/P0493 original ownbirthday/death records remain unread; do not upgrade gates from displayed context. No Gösta biological relation inferred. Existing lifetime child-count overreach should remain explicitly qualified as known-child inventory, not solved by list membership.','P0463/P0464 own verified witness identities and samepage1860localanchors retained; upward candidate siblings stayLEAD.','Current metadata historical no-new-research rationale may be preserved as old exact text, but every changed object needs explicit current T0828 rationale; do not silently claim unchanged workscope.'],'required_final':'Final one baseline→final row perfield with exact old/final values and independent group disposition, including retains. Actual changed closure and pending resolutions individually judged, baseline full native metadata/origins/evidence/dataarray/order/history and45OWNER/T826171 retains preserved. Exact ordered package/hash and stable stage hash still require independent approval.'}
d={'schema':'independent-consolidated-consequence-set/1','task':'T-0828','recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline':503,'source_concurrence':{'path':str(p/'source-concurrence-eight-v1.json'),'sha256':hashlib.sha256((p/'source-concurrence-eight-v1.json').read_bytes()).hexdigest()},'scope':'eight available originalunits plus3existingHH recheck;15accessblocked no source interpretation; no newresearch beyond exact23','groups':groups,'exact_old_native_objects':rows,**extras}
out=p/'consolidated-consequences-eight-v1.json';out.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');print('groups',len(groups),'objects',len(rows),'sha256',hashlib.sha256(out.read_bytes()).hexdigest())
