import json,hashlib,pathlib
base=pathlib.Path('evaluations/T-0828');p=base/'implementation/stage-v6/actual-pending-full-native-v1.json';x=json.loads(p.read_text())
rotids={f'{prefix}-P-0336-C0473-{post}' for prefix in ['O','ID'] for post in ['046010030010','434800120100']}
readid='READ-2229f88b325af6523ee384b0'
rottext='T-0828, 2026-10-09: De fem andra egna korten 038540010180, 045850170100, 434840120030, 434870120010 och 030080030190 är nu fullutvunna och hashbevarade som daterad leverantörs-HTML. Tillsammans med de två accepterade T-0826-korten är exakt sju-kortsskulden sluten. Titel och Status är lästa fält; inget separat uttryckligt hushållsrollsfält visas och inget sådant värde härleds. Fotografiska mantalsblad är fortsatt olästa och samma registreringskedja är inte oberoende födelsebevis. Äldre femkortsskuld nedan beskriver T-0826:s historiska läsläge.'
readtext='T-0828, 2026-10-09: C0626 s.34–36 är nu fullkopierade och relevanta fält prövade. Henric 1796-11-02:s egen födelseort på s.34 läses Rundb.[?], inte äldre Ljust.[?] och inte normaliserad till databasens Lagfors. Egen rad är fullutvunnen, inklusive Förhör/Nattvard 1860–1869 och odaterad högermarginal; ingen 1870-kolumn finns. Testade svårtydda tecken och sido-radernas attributioner behåller sina reservationer. Ingen Henrik född 1829 eller Brita identifierades på de tre sidorna; detta ger ingen ny döds- eller föräldraslutsats och avgör inte 1829–1850. Äldre ordalydelse nedan är historiskt läsläge; tidigare negativa kvitton och deras okända metadata ändras inte.'
rows=[]
for r in x['rows']:
 n=r['affected_full_native'];o=n['revision']['object_id'];decision='retain';reason=''
 if o in rotids:
  decision='revise_current_caveat';reason='Explicit current five-other-cards debt is superseded by the five exact T0828 provider representations. Preserve own T0826 extraction/identity, original_booklet_read=false, raw fields, grades and all history.'
 elif o==readid:
  decision='revise_current_caveat';reason='Current Ljust.[?] and unextracted right-year fields contradict settled C0626 full reading. Preserve bounded historical negative and no parent/death inference.'
 elif o.startswith('READ-') and 'C-0473' in n['data'].get('body',''):
  reason='This legacy_record_boundary assessment locates the seven exact records and states dependence/date boundaries. It does not claim a still-unread field or missing copy; record_located remains true after fuller extraction. Exact older basis is legitimate preserved reading history, not a competing current gate.'
 elif o.startswith(('AUDIT-T0826','TR-T0826')):
  reason='Accepted source-specific T0826 extraction and dated provider-representation receipt remain correct; S0376 description update adds other cards and corrects the shared date summary without invalidating this own card or its historical source-model version.'
 elif o in ['R-e86aa5ec1aa886e5c62475e1','R-304574b60269a9dd2762d376']:
  reason='Full accepted T0826 own-card extraction, HTML asset, raw spelling, period-boundary interpretation and dependence remain adequate. No current remaining-five debt is asserted by this record; historical S0376@1 reference remains preserved.'
 elif o=='F-P-0287-residence-documented-anchors':
  reason='Existing dated family/residence anchors remain valid. New father-card periods do not alter the own after-1900 unread chain or imply Sollentuna residence; protected P0287 identity/tree and stronger own support remain unchanged.'
 elif 'C0651' in o or o=='R-802147d6e2a5240dbba36fdb' or o=='TR-ea836e8e1087954ad51224cf' or o=='READ-096361c7909b83943d8d86d7':
  reason='C0651 is the separately bounded Brita Stina post434800120110 and its preserved 1885–1886 household extraction, not one of the newly opened Olaus cards. Existing family names, accepted identities and address/deathbook dependence remain valid. A statement about a row outside that preserved screenshot is specific to that representation, not a claim that all father-card HTML lacks the person; no new individual-relative card was opened.'
 elif o=='M-P-0336-C0473-434800120100':
  reason='Literal Olaus Fredberg Fredriksson and empty separately-unshown household role remain consistent with accepted T0826 exact own card. S0376 metadata correction does not change this mention; historical @1 record binding is not rewritten in a retain.'
 else:raise Exception(o)
 rows.append({'request':r['request'],'affected_full_native':n,'changed_full_native':r['changed_full_native'],'decision':decision,'reason':reason,'retain_scope':'Whole native payload, metadata, origins, evidence, literal/source uncertainties and grades unchanged unless explicitly revised below.'})
changes=[]
for o in sorted(rotids):
 changes.append({'object_id':o,'expected_version':2,'field':'revision.caveat','required_current_prefix':rottext,'preserve':'Retain complete old caveat verbatim as explicitly superseded historical reading; retain all data, statuses, origins and existing support. Add five exact AUDIT-T0828-unit-4..8@1 supports only for the debt closure. No inferred household role.','evidence_rebinds':[{'basis':'M-P-0336-C0473-046010030010','from':1,'to':2,'reason':'Exact accepted same-post single-s name correction only; own-field/identity assertion unchanged.'}] if o.endswith('046010030010') else []})
changes.append({'object_id':readid,'expected_version':1,'field':'revision.caveat','required_current_prefix':readtext,'preserve':'Keep full old caveat and body as explicit historical reading, existing outcome record_located, metadata/origins/history. Add AUDIT-T0828-unit-1@1 and exact R-43b34a14d2bb3717d56dfd1a@2; individually authorize its old R@1→@2 derived_from reference for same corrected own source, preserving old note/history. No rewrite of historical negative receipts.'})
y={'task':'T-0828','review':'Independent actual stage-v6 pending review; not final package approval','input':str(p),'input_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'source_operation_sha256':x['operation_sha256'],'coverage':{'actual_requests':len(rows),'current_objects':len({r['affected_full_native']['revision']['id'] for r in rows}),'retain_requests':sum(r['decision']=='retain' for r in rows),'revise_requests':sum(r['decision']!='retain' for r in rows),'revised_objects':len(changes)},'method':'Read all35 full native payloads including caveats, bodies, structured fields, exact existing evidence, origins and media; all8 changed bases compared to settled source judgments. No new originals reopened.','rows':rows,'required_object_changes':changes,'v6_delta_review':{'V4-01':'CONCUR five current outcomes with narrow remaining-life source scopes','V4-02':'CONCUR all41 current date caveat corrections retaining true1853/1854 variations and historical text','V4-03':'CONCUR four-source native-vs-legacy PK11 scope boundaries; positive C0476 notice kept positive, obligations preserved','V4-04':'CONCUR merged tree duplicate supports and current Olaus identity@4 boundary with prior notes historic','V4-05':'Scope CONCUR; exact displayed-period arrays must use actual individual list values, no birthdate formula','period_corrections':{'P-0492':['1895–1897','1897–1907','1911–1915'],'P-0493':['1902–1907','1911–1915'],'P-0367':['1878–1879','1879–1884','1891–1896']},'note':'These arrays describe the specific fields being amended, not an exhaustive biography or continuous physical presence.'},'final_gate':'Review exact corrected ordered source op, resulting actual pending requests/resolution payloads, reference dispositions, full native/history/protected-state proof and stable stage hash before canonical apply.'}
out=base/'independent/actual-pending-v6-dispositions-v1.json';out.write_text(json.dumps(y,ensure_ascii=False,indent=2)+'\n');print(out,hashlib.sha256(out.read_bytes()).hexdigest());print(y['coverage'])
