import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {openDB,importBaseline,exportData,restore} from '../lib/store.mjs';
import {applyOperation,inspect} from '../lib/domain.mjs';
import {snapshot,canonical} from '../lib/archive.mjs';
import {migrationReport} from '../lib/migration.mjs';

test('konverteringsbeslut skiljer bevarad text från tolkningsfråga och versioneras utan att ändra underlaget',async t=> {
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'genealogy2-conversion-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  fs.mkdirSync(path.join(dir,'genealogy/citations'),{recursive:true});
  fs.writeFileSync(path.join(dir,'genealogy/citations/C-0001.md'),'# C-0001: Test\n\n## Avskrift\n\n27/28; inget värde väljs.\n');
  const base=path.join(dir,'baseline');await snapshot(dir,base);
  const db=openDB(path.join(dir,'db.sqlite'),{create:true});t.after(()=>db.close());importBaseline(db,base);
  const unit=db.prepare("SELECT id FROM unit WHERE section='Avskrift'").get().id;
  const decision={unit,expectedVersion:null,state:'pending_interpretation',rationale:'Två läsningar bevarade.',question:'Vilken av åldrarna avser modern? Ingen väljs nu.'};
  const request={id:'decide',actor:'test',reason:'Syntetiskt',changes:[],unitDecisions:[decision]};
  applyOperation(db,request);assert.equal(applyOperation(db,request).unchanged,true);
  assert.match(migrationReport(db).units.find(u=>u.id===unit).reason,/Ingen väljs/);
  assert.equal(inspect(db,'C-0001').conversionDecisions[0].question,decision.question);
  const before=canonical(exportData(db));
  assert.throws(()=>applyOperation(db,{...request,id:'invalid',unitDecisions:[{...decision,expectedVersion:1,question:''}]}),/CHECK/);
  assert.equal(canonical(exportData(db)),before);
  applyOperation(db,{...request,id:'preserve',unitDecisions:[{...decision,expectedVersion:1,state:'preserved_text',question:'',rationale:'Alternativen representeras tills vidare fullständigt som ordagrann text.'}]});
  assert.equal(db.prepare('SELECT count(*) n FROM unit_decision').get().n,2);
  assert.equal(migrationReport(db).units.find(u=>u.id===unit).state,'preserved_text');
  assert.throws(()=>db.exec("UPDATE unit_decision SET question='radera historik'"),/oföränderliga/);
  const data=exportData(db);restore(data,path.join(dir,'restored.sqlite'));
  const restored=openDB(path.join(dir,'restored.sqlite'));assert.equal(canonical(exportData(restored)),canonical(data));restored.close();
});

test('en sammansatt rad behåller alla återbrukade mål och senare beslut ersätter hela målgruppen',async t=> {
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'genealogy2-multi-target-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  fs.mkdirSync(path.join(dir,'genealogy/people'),{recursive:true});
  fs.writeFileSync(path.join(dir,'genealogy/people/P-0001.md'),'# P-0001: Test\n\n## Påståenden\n\n| A-0001 | Dop och födelse har skilda datum. | TRANSCRIBED | hög | C-0001 | Förbehåll. |\n');
  const base=path.join(dir,'baseline');await snapshot(dir,base);
  const db=openDB(path.join(dir,'db.sqlite'),{create:true});t.after(()=>db.close());importBaseline(db,base);
  const unit=db.prepare("SELECT id FROM unit WHERE legacy_id='A-0001'").get().id;
  applyOperation(db,{id:'objects',actor:'test',reason:'Tidigare oberoende införda objekt',changes:['S1','S2'].map(id=>({id,kind:'source',expectedVersion:null,disposition:'recorded',rationale:'Syntetiskt återbruksmål',data:{title:id,archive_reference:null,source_class:null,description:'text'}}))});
  const before=db.prepare('SELECT * FROM revision ORDER BY id').all();
  const first={unit,expectedVersion:null,state:'mapped_complete',target:'S1',targets:['S1','S2'],rationale:'Sammansatt rad har två självständiga mål.',question:''};
  const op={id:'map',actor:'test',reason:'Två mål på äldre objekt',changes:[],unitDecisions:[first]};
  applyOperation(db,op);
  assert.deepEqual(inspect(db,'A-0001').representations.map(x=>x.object_id),['S1','S2']);
  assert.deepEqual(inspect(db,'A-0001').conversionDecisions[0].targets,['S1','S2']);
  assert.deepEqual(db.prepare('SELECT * FROM revision ORDER BY id').all(),before);
  assert.equal(applyOperation(db,op).unchanged,true);
  const beforeInvalid=canonical(exportData(db));
  assert.throws(()=>applyOperation(db,{...op,id:'bad',unitDecisions:[{...first,expectedVersion:1,targets:['S1','missing']}]}),/FOREIGN KEY|saknat mål/);
  assert.equal(canonical(exportData(db)),beforeInvalid);
  applyOperation(db,{...op,id:'replace',unitDecisions:[{...first,expectedVersion:1,target:'S2',targets:['S2'],rationale:'Ny granskning begränsar den aktuella representationen.'}]});
  assert.deepEqual(inspect(db,'A-0001').representations.map(x=>x.object_id),['S2']);
  assert.equal(db.prepare('SELECT count(*) n FROM unit_decision_target').get().n,3);
  assert.throws(()=>db.exec('DELETE FROM unit_decision_target'),/oföränderliga/);
  const data=exportData(db);restore(data,path.join(dir,'restored.sqlite'));
  const restored=openDB(path.join(dir,'restored.sqlite'));assert.equal(canonical(exportData(restored)),canonical(data));restored.close();
});
