import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {openDB,importBaseline,exportData,restore,verifyDB} from '../lib/store.mjs';
import {applyOperation,personView} from '../lib/domain.mjs';
import {buildPilot} from '../import/pilot.mjs';
import {canonical,sha} from '../lib/archive.mjs';
import {migrationReport} from '../lib/migration.mjs';
import {renderPerson} from '../lib/render.mjs';
import {pedigree} from '../lib/pedigree.mjs';

test('riktig pilot: familjeroller, provenans, datum, avgränsat noll och identiteter',t=> {
  const dir=fs.mkdtempSync(path.join(os.tmpdir(),'genealogy2-pilot-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));
  const db=openDB(path.join(dir,'pilot.sqlite'),{create:true});t.after(()=>db.close());
  importBaseline(db,new URL('../import/baseline/',import.meta.url).pathname);
  const request=buildPilot(db);applyOperation(db,request,{legacy:true});
  assert.equal(applyOperation(db,request).unchanged,true);
  assert.equal(verifyDB(db).ok,true);
  assert.equal(db.prepare("SELECT count(*) n FROM object WHERE id='P-0295'").get().n,0);
  assert.equal(db.prepare("SELECT target_id FROM legacy_mapping WHERE legacy_id='P-0295'").get().target_id,'P-0027');
  assert.throws(()=>applyOperation(db,{id:'invalid-alias',actor:'test',reason:'Syntetisk konflikt',changes:[],mappings:[{...request.mappings[0],id:'second-alias',target:'P-0028'}]}),/beslutat mål/);
  assert.equal(db.prepare("SELECT decision FROM identity_resolution WHERE person_a='P-0424' AND person_b='P-0028'").get().decision,'different_people');
  assert.equal(personView(db,'P-0424').person.legacy_state,'retired');
  assert.deepEqual(db.prepare("SELECT person_id FROM current_participation WHERE event_id='E-P0016-baptism' AND role='witness' ORDER BY person_id").all().map(r=>r.person_id),['P-0113','P-0114']);
  for(const p of ['P-0016','P-0113','P-0114'])assert.ok(personView(db,p).events.some(e=>e.event_id==='E-P0016-baptism'));
  assert.deepEqual(db.prepare("SELECT from_person FROM current_relation WHERE to_person='P-0016' AND relation_type='parent' ORDER BY from_person").all().map(r=>r.from_person),['P-0110','P-0111']);
  assert.deepEqual(db.prepare("SELECT from_person FROM current_relation WHERE to_person='P-0007' AND relation_type='parent' ORDER BY from_person").all().map(r=>r.from_person),['P-0015','P-0016']);
  assert.equal(db.prepare("SELECT count(*) n FROM current_relation WHERE relation_type='spouse' AND (from_person='P-0015' OR to_person='P-0015')").get().n,0);
  assert.deepEqual(pedigree(db,'P-0007',{mode:'typed'}).paths.map(x=>x.person).sort(),['P-0007','P-0015','P-0016','P-0110','P-0111']);
  assert.equal(db.prepare("SELECT value_literal FROM observation WHERE revision_id='O-C0075-witness-place@1'").get().value_literal,'Hogtorp[?]');
  const age=JSON.parse(db.prepare("SELECT value_json FROM observation WHERE revision_id='O-C0075-age@1'").get().value_json);
  assert.equal(age.selected,null);assert.deepEqual(age.alternatives,[27,28]);
  const birth=db.prepare("SELECT place_id,place_role FROM event WHERE revision_id='E-P0016-birth@1'").get();
  assert.equal(birth.place_id,'PL-Gryt');assert.equal(birth.place_role,'registered_parish');
  assert.equal(personView(db,'P-0016').events.find(e=>e.event_id==='E-P0016-birth').caveat,
    'Djupnäs är föräldrahemvist; fysisk förlossningsplats inte säkert utskriven.');
  assert.match(renderPerson(personView(db,'P-0016')),/Förbehåll:\*\* Djupnäs är föräldrahemvist; fysisk förlossningsplats inte säkert utskriven\./);
  assert.equal(db.prepare("SELECT count(*) n FROM dependency WHERE revision_id='F-C0075-witness-place@1'").get().n,2);
  const negative=db.prepare("SELECT scope_json,outcome FROM search WHERE revision_id='SEARCH-C0978-51-96@1'").get();
  assert.equal(negative.outcome,'negative');assert.deepEqual(JSON.parse(negative.scope_json).bounds.record_from,51);
  assert.equal(JSON.parse(negative.scope_json).bounds.record_to,96);
  assert.equal(db.prepare("SELECT disposition FROM current_revision WHERE object_id='F-P0016-rejected-arrival-hypothesis'").get().disposition,'rejected');
  const move=JSON.parse(db.prepare("SELECT date_json FROM event WHERE revision_id='E-P0016-departure1902@1'").get().date_json);
  assert.deepEqual(move.values,['1902-10-22','1902-10-23']);
  assert.equal(db.prepare("SELECT evidence_status FROM current_revision WHERE object_id='F-P0004-birth-owner'").get().evidence_status,'OWNER_CONFIRMED');
  assert.match(personView(db,'P-0016').assessments[0].outcome,/UNDERKÄND/);
  assert.ok(personView(db,'P-0016').remaining.some(r=>r.kind==='assertion'&&r.n>0));
  assert.ok(personView(db,'P-0016').questions.length>0);
  const report=migrationReport(db);
  assert.equal(report.summary.documents+report.summary.assets,8784);
  assert.equal(report.units.length,new Set(report.units.map(u=>u.id)).size);
  assert.equal(report.summary.units,db.prepare('SELECT count(*) n FROM unit').get().n);
  assert.equal(report.groups.flatMap(g=>g.documents).length,report.documents.length);
  assert.ok(report.units.every(u=>u.group&&u.state&&u.reason));
  assert.equal(report.groups.flatMap(g=>g.persons).length,538);
  assert.equal(report.groups.flatMap(g=>g.citations).length,1111);
  assert.equal(report.groups.flatMap(g=>g.sources).length,805);
  assert.equal(migrationReport(db).reportHash,report.reportHash);
  const data=exportData(db),digest=sha(canonical(data));
  restore(data,path.join(dir,'restored.sqlite'));
  const restored=openDB(path.join(dir,'restored.sqlite'));assert.equal(sha(canonical(exportData(restored))),digest);restored.close();
});
