import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {execFileSync} from 'node:child_process';
import {openDB,exportData} from '../lib/store.mjs';
import {applyOperation} from '../lib/domain.mjs';
import {canonical,sha} from '../lib/archive.mjs';
import {workView,validateNodeLinks,renderWork} from '../lib/work.mjs';
const mapping=JSON.parse(fs.readFileSync('wotan/node-links.json'));
const c=(id,kind,data,extra={})=>({id,kind,data,expectedVersion:null,disposition:'recorded',rationale:'Synthetic work-view fixture',...extra});
function setup(t,{omit}={}){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'work-view-')),file=path.join(dir,'db.sqlite'),db=openDB(file,{create:true});t.after(()=>{db.close();fs.rmSync(dir,{recursive:true,force:true});});const changes=[c('S','source',{title:'Source',description:''})];for(const id of mapping.pilot_people)changes.push(c(id,'person',{display_name:id},{evidence:[{object:'S',version:1,role:'context'}]}));for(const id of new Set(mapping.routes.map(x=>x.question_id).filter(Boolean)))changes.push(c(id,'question',{subject_id:id.split('/')[0],title:'Question',outcome:'ÖPPEN',body:'Exact bounded question'}));for(const r of mapping.routes)if(!changes.some(c=>c.id===r.path_id))changes.push(c(r.path_id,'assessment',{subject_id:r.person_id,criteria:'legacy_source_path',outcome:'EJ UNDERSÖKT.',body:'Exact path body'},{caveat:'Preserved caveat',evidence:[{object:'S',version:1,role:'context'}]}));changes.push(c('OLD-SEARCH','search',{question_id:'P-0241/Q-02',source_id:'S',scope_json:{description:'Exact old index',query:'Axel',bounds:{pages:'12–14'}},outcome:'negative',body:'Target not identified; other rows were positive'},{caveat:'Not whole archive absence',evidence:[{object:'S',version:1,role:'context'}]}));applyOperation(db,{id:'fixture',actor:'test',reason:'Synthetic pilot',changes:changes.filter(x=>x.id!==omit)});const backlog={tasks:[{id:'T-0803',status:'READY',priority:'CORE_LIFE',after:[]},{id:'T-0217',status:'BLOCKED',priority:'DEFERRED',after:['T-OTHER'],blocker:'Original existing dependency'},{id:'T-OTHER',status:'ONGOING',after:[]}]};fs.mkdirSync(path.join(dir,'wotan'));fs.writeFileSync(path.join(dir,'wotan/node-links.json'),JSON.stringify(mapping));fs.writeFileSync(path.join(dir,'wotan/backlog.json'),JSON.stringify(backlog));return {db,dir,file,backlog};}
test('shared task references are identical while own subsets remain separate; live blockers update without a second queue',t=>{
 const {db,backlog}=setup(t),before=canonical(exportData(db));let emma=workView(db,'P-0246',{mapping,backlog}),axel=workView(db,'P-0241',{mapping,backlog});const common=x=>({...x,shared_routes:x.shared_routes.map(({relevant_to_this_person,...r})=>r)});assert.deepEqual(common(emma.routes[0].task),common(axel.routes[0].task));assert.equal(emma.routes.length,1);assert.equal(axel.routes.length,2);assert.equal(emma.routes[0].task.shared_routes.filter(r=>r.relevant_to_this_person).length,1);assert.equal(axel.routes[0].task.dependencies_satisfied,false);assert.equal(axel.routes[0].path.outcome,'EJ UNDERSÖKT.');assert.equal(axel.searches[0].scope.bounds.pages,'12–14');assert.match(axel.searches[0].memory_qualification,/legacy\/unqualified/);assert.match(renderWork(axel),/Target not identified; other rows were positive/);backlog.tasks[2].status='DONE';backlog.tasks[1].status='READY';axel=workView(db,'P-0241',{mapping,backlog});assert.equal(axel.routes[0].task.ready_with_dependencies,true);assert.equal(axel.routes[0].path.outcome,'EJ UNDERSÖKT.');assert.equal(canonical(exportData(db)),before);
});
test('bad associations, unknown refs, duplicated routes, status metadata and outside pilot fail explicitly',t=>{
 const {db,backlog}=setup(t);for(const mutate of [m=>m.routes.push(m.routes[0]),m=>m.routes[0].question_id='missing',m=>m.routes[0].path_id='missing',m=>m.routes[0].status='DONE']){const m=structuredClone(mapping);mutate(m);assert.throws(()=>validateNodeLinks(db,m,backlog));}assert.throws(()=>workView(db,'P-9999',{mapping,backlog}),/omappad betyder inte/);assert.throws(()=>workView(db,'P-0241',{mapping,backlog:{tasks:[]}}),/Task saknas/);const missing=setup(t,{omit:'PATH-P-0240-KP-02'});assert.throws(()=>validateNodeLinks(missing.db,mapping,backlog),/Källvägsreferens saknas/);
});
test('work CLI JSON and default Markdown do not mutate database or journal; unmapped clear failure',t=>{
 const {db,dir,file}=setup(t),before=sha(fs.readFileSync(file)),beforeExport=canonical(exportData(db));const run=(...args)=>execFileSync(process.execPath,['genealogy2/cli.mjs','work',...args,'--db',file,'--source',dir],{encoding:'utf8'});assert.equal(JSON.parse(run('P-0241','--format','json')).routes.length,2);assert.match(run('P-0246'),/# Arbetsvy/);assert.throws(()=>run('P-9999'));assert.equal(sha(fs.readFileSync(file)),before);assert.equal(canonical(exportData(db)),beforeExport);assert.equal(fs.existsSync(path.join(dir,'genealogy2/journal')),false);
});
