import{person,core,all,src,fact,event,exact,year,kin,relRows,assertion,save,reuse,add,record,cs,relation}from './part-c-common.mjs';
const ids=['P-0494','P-0495','P-0496','P-0497','P-0498','P-0499'];
const names={'P-0494':'Carl Johan','P-0495':'Anna Lotta','P-0496':'Lars Petter','P-0497':'Johanna Mathilda','P-0498':'Hedda','P-0499':'Maria Sofia'};
const born={'P-0494':'1843-01-04','P-0495':'1846-01-14','P-0496':'1848-02-27','P-0497':'1854-01-21','P-0498':'1859-10-29','P-0499':'1863-02-27'};
const assertions={'P-0494':['A-3041','A-7982'],'P-0495':['A-3042','A-7983'],'P-0496':['A-3043','A-3044','A-4624'],'P-0497':['A-3045','A-3046','A-4760'],'P-0498':['A-3047','A-3048','A-4761','A-4762','A-4763','A-4764'],'P-0499':['A-3049','A-7984']};
function witness(p,cid,filter,key,name,role,home,bap){const os=[...all(p),cs(cid)],r=record(cid,filter),m=add(p,`M-${p.person}-${key}`,'mention',{record_id:r,name_literal:name,role_literal:role},os,[r],'Eget dopvittne, ingen personfusion eller släktrelation.','TRANSCRIBED','recorded');const o=add(p,`O-${p.person}-${key}`,'observation',{record_id:r,mention_id:m,property:'witness_fields',value_literal:JSON.stringify({home}),value_json:{home}},os,[r],'Reserverad ort återges utan harmonisering.','TRANSCRIBED','recorded');const e=add(p,`EP-${bap}-${key}-witness`,'participation',{event_id:bap,person_id:null,mention_id:m,role:'witness'},os,[m],'Dopvittne vid detta barns dop; ingen känd släktidentitet.');return[m,o,e];}
function ownHouse(p,cid,filter,key,fields){return src(p,cid,filter,key,names[p.person],'',{name:names[p.person],...fields},all(p),'Ingen ordagrann separat roll har utvunnits här. Föräldra-/barnrollen framgår av den bevarade hushållsavskriften; egna outvunna kolumner fylls inte från föräldrarna.');}
for(const id of ids){const p=person(id,'Hela egen akt och profil inklusive historik och sena T0139/T0144/T0202-rättelser lästa. Hela C0702/0718/0721/0729/0732/0749/0750/0763/0771/0775/0794 har kontrollerats för aktuella postgränser. Källrapporter, jämförelser och profilgranskning hålls skilda; inga nya arkivbilder lästa.');const os=all(p),targets=[];
 const independent=['P-0494','P-0495','P-0499'].includes(id);core(p,os,independent?'Den avgränsade identiteten korroboreras av egen födelsepost och senare namngivna familjerader. Varje exakt dag och råfält behåller sin egen källsäkerhet; Maria Sofias hushållsdatum avviker.':'Accepterad identitet inom den uttryckliga familjekedjan. Upprepade husförhör och SCB-utdrag kan bero på samma kyrkobokföring; ingen självständig vitalpost är läst. Därför TRANSCRIBED, utan ändrad identitets-/kontraktsgranskning.',id==='P-0496'?'male':null,independent?'CORROBORATED':'TRANSCRIBED');
 targets.push(...event(p,'birth',exact(born[id]),os,id==='P-0499'?'Födelsepostens27februari ges prioritet genom månadskontext och dopföljd. Senare hushållens27mars bevaras som verklig råavvikelse.':independent?'Egen födelsepost; Bettna, hemort enligt egna råfält.':'Rapporterad födelseuppgift i husförhör, Bettna. Egen födelsenotis oläst; rättade avskrifter är inte nya oberoende källor.'));
 let household=[];
 if(['P-0494','P-0495','P-0496'].includes(id)){
  for(const [filter,key]of [['A I/12a','C0702-AI12-own'],['A I/13a','C0702-AI13-own']])household.push(...ownHouse(p,'C-0702',filter,key,{birth:born[id],birth_parish:'Bettna',home:'Glippsta soldattorp',...(id==='P-0496'?{vaccination:'v',knowledge_columns:'tomma',communion:'tomt',examination:'tomt',marriage:'tomt',death:'tomt',remarks:'tomt'}:{})}));
  if(id==='P-0494')household.push(...ownHouse(p,'C-0718','A I/11a','C0718-own',{birth:'1843-01-04',birth_parish:'Bettna',home:'Glippsta soldattorp'}));
 }
 if(['P-0497','P-0498','P-0499'].includes(id))household.push(...ownHouse(p,'C-0729','A I/16b','C0729-own',{birth:id==='P-0499'?'1863-03-27':born[id],birth_parish:'Bettna',home:'Hagby, Östra Soldattorp N:o38'}));
 if(['P-0498','P-0499'].includes(id))household.push(...ownHouse(p,'C-0732','A I/18a','C0732-AI18-own',{birth:id==='P-0499'?'1863-03-27':born[id],birth_parish:'Bettna',home:'Hagby, Östra Soldattorp N:o38',...(id==='P-0499'?{internal_reference:'190/1'}:{})}));
 if(['P-0495','P-0496','P-0497','P-0498'].includes(id)){
  const initials={'P-0495':'A. L.','P-0496':'L. P.','P-0497':'J. M.','P-0498':'H.'}[id];household.push(...src(p,'C-0749','', 'C0749-own',initials,id==='P-0496'?'Son':'',{name:initials,birth_year:Number(born[id].slice(0,4)),birthplace_column:'blott län eller stad',birthplace_literal:'förkortning ej säkert avskriven',...(id==='P-0496'?{sex:'man',civil_status:'ogift',occupation:'ingen utöver familjeroll',personal_remarks:'inga lytes- eller nationalitetsord'}:{})},os,'Initialrad korrelerad genom föräldrapar, barnordning och födelseår. Utdrag ur kyrkobokföringen, inte oberoende födelsebevis. Ortskolumnen får inte bli Bettna socken.'));
  targets.push(...event(p,'residence',year(1860),os,'SCB1860, Bettna, egen initialrad i familjegruppen. Ingen exakt bostadsort eller obruten vistelse1852–1860 härleds.',null,'TRANSCRIBED',`E-residence-${id}-1860`));
 }
 targets.push(...household);
 const members=ids.filter(x=>x!==id).map(x=>kin(p,x,'sibling',id==='P-0494'||x==='P-0494'?'maternal_sibling':'recorded_sibling'));members.push(kin(p,'P-0133','sibling',id==='P-0494'?'maternal_sibling':'recorded_sibling'));const mother=kin(p,'P-0475','parent');members.push(mother);if(id!=='P-0494')members.push(kin(p,'P-0474','parent'));
 const anders=reuse(p,'F-P-0474-family_context-Anders-Fredric1844',os,'Separat barnrad1844 med dödsnot, ingen ny person eller styrkt biologisk faderskant.');
 const family=fact(p,'family_context','limits',{mother:'P-0475',father:id==='P-0494'?null:'P-0474',carl_johan_paternal_link_unresolved:true,carl_johan_sibling_nature:'Gemensam mor; varken säkra helsyskon eller säkra halvsyskon.',known_children:['P-0494','Anders Fredric1844','P-0495','P-0496','P-0133','P-0497','P-0498','P-0499'],lifetime_children_complete:false,anders_birth_death:1844,anders_exact_day_reserved:true,maria_not_present_1860:true,parents_professions_not_inherited:true,mother_name_forms:['Jansdotter','Jonsdotter'],name_limit:'Båda namnformerna är faktiskt rapporterade. Moderns far Jan gör inte den senare källans Jonsdotter till en ogiltig råform.'},[...os,cs('C-0718'),cs('C-0794')]);
 const limits=fact(p,'identity_limits','own-fields',{own_surname:id==='P-0498'?'Carlsdotter':null,unattested_names:id==='P-0494'?['Karl','Johanson','Jansson','Grill','Drill']:id==='P-0495'?['Anna Charlotta','Carlsdotter','Grillsdotter']:id==='P-0499'?['Maria Sophia','Carlsdotter','Grill']:[],occupation_after_childhood:null,marriage:null,death:null,own_move_date:null,own_columns:id==='P-0496'?'Två egna fulla rader lästa; v och namngivna tomfält bevarade.':id==='P-0497'||id==='P-0498'?'Flera egna kunskaps-, kyrko- och flyttkolumner är outvunna, inte blankt konstaterade.':'Endast uttryckligen utvunna egna fält representerade.',limits:'Föräldrars eller andra barns senare död/närvaro bevisar inte egen överlevnad. Inga egna militära fynd; könskategori bevisar inte att ingen sådan källa kan finnas. Soldattitel, kyrkliga grader och hushållsflytt överförs inte från fadern.'},os);
 targets.push(...members,anders,family,limits);
 const map={'P-0474':[family,...members],'P-0475':[mother,family], 'biologisk far':[family], 'Anders Fredric':[anders,family]};for(const x of [...ids,'P-0133'])if(x!==id)map[x]=[...members,family];
 if(independent){
  const cid=id==='P-0494'?'C-0763':'C-0794',filter=id==='P-0494'?'Carl Johan':id==='P-0495'?'Anna Lotta':'Maria Sofia',bapday=id==='P-0494'?'1843-01-06':id==='P-0495'?'1846-01-18':'1863-03-08';
  const fields=id==='P-0494'?{birth:born[id],baptism:bapday,home:'Glippsta soldattorp',legitimacy:'oäkta',mother:'Johanna Jansdotter',mother_role:'pigan',mother_age:23,father:null,maternal_churching:'blek not prövad men inte säkert läst',officiant:null}:id==='P-0495'?{birth:born[id],baptism:bapday,home:'Glippsta soldattorp',father:'Carl Fr. Drill',father_role:'soldaten',mother:'Johanna Jonsdotter',mother_role:'hustrun',mother_age:26,maternal_churching:'1/2[?]'}:{birth:born[id],baptism:bapday,home:'Hagby soldattorp[?]',home_role:'faderns hemvist',legitimacy:'äkta flicka',father:'Carl Fredric Drill',father_role:'soldaten',mother:'Johanna Jonsdotter',mother_role:'hustrun',mother_age:43,maternal_churching:'11[?]/4',column23:'tom',other_remarks:'tomma'};
  targets.push(...src(p,cid,filter,`${cid.replace('-','')}-birth-own`,names[id],'',fields,os,'Egen födelse- och doppost. Modersålder och kyrktagningsnot gäller modern; ingen sådan händelse läggs på barnet. Prövade bleka reservationer är bevarade.'));
  const baptism=event(p,'baptism',exact(bapday),[...os,cs(cid)],'Eget dop enligt födelse-/dopbok, Bettna. Fyra namngivna dopvittnen hålls åtskilda från släktingar.');targets.push(...baptism);
  const witnesses=id==='P-0494'?[
   ['JonasAndersson','Jonas Andersson','H.[?]',null],['MajaStGustafsdotter','Maja St. Gustafsdotter[?]','',null],['CajsaGretaErsdotter','Cajsa Greta Ersdotter','pigan','Agnatorp[?]'],['PetterErsson','Petter Ersson','drängen','Skresta[?]']
  ]:id==='P-0495'?[
   ['NilsThor','Nils Thor','soldaten','Skrella[?] soldattorp'],['AnnStJansdotter','Ann. St. Jansdotter[?]','hustrun','Skrella[?] soldattorp'],['CarlOttoNilsson','Carl Otto Nilsson','sonen','Skrädd...stugan[?]'],['AnnMSoderberg','Ann. M. Söderberg','pigan','Knuf...n[?]']
  ]:[['AugustWerner','August Werner','drängen','Kofhult[?]'],['EvaLottaOlsdotter','Eva Lotta Olsdotter','hustrun',null],['CarlJohJansson','Carl Joh. Jansson','drängen','Hagby[?]'],['GustafvaOlsdotter','Gustafva Olsdotter','pigan','Sjöstugan']];
  for(const[key,n,r,h]of witnesses)targets.push(...witness(p,cid,filter,key,n,r,h,baptism[0]));
 }
 if(id==='P-0494'||id==='P-0495'||id==='P-0499')targets.push(fact(p,'source_interpretation','parental-chronology',{banns1841:'Överstruket ärende, ingen fullbordad vigsel där.',banns_later:'16april1843[?], årtalets sista siffra reserverad.',muster_date:'1845-07-07',muster_married_status:true,marriage_date:null,mother_status_1843:'pigan',mother_status_1846:'hustrun',assessment:'Civilståndsrapporterna ger riktning för sökning. Oäkta ensam bevisar inte en säker nedre vigselgräns för just detta par; rullans datum gäller mönstring/giftstatus, inte vigsel. Påståendet27månadersdröjsmål saknar därför daterad vigsel att jämföra med.',father_of_carl_johan:null,ages_reported:[23,26,43],derived_ages_from1819May30:['23år7månader5dagar','26år7månader15dagar','43år8månader28dagar'],age_limit:'Beräknade åldrar är inte källans exakta åldersprecision eller tre oberoende bevis för födelsedagen.23/26/43 skiljer inte30april från30maj. C0721T0202tabellens1863-02-26 avviker från barnets27februari.'},[...os,cs('C-0718'),cs('C-0763'),cs('C-0794'),cs('C-0721')],'INFERRED','Äldre analytiska påståenden bevaras via akt/profil men korrigeras här med faktisk källprecision.'));
 if(id==='P-0494')targets.push(fact(p,'source_interpretation','father-and-name',{father:null,mothers_husband:'P-0474',link:'Moderns senare make och hushållsvuxen; inte belagd far till Carl Johan.',baptism_birth_gap_days:2,post_date_correction:'1843-01-04, äldre4juli var felläsning.',later_life_unknown:true,search_names_only:['Karl','Johan(s)son','Jansson','Grill','Drill'],paternal_research:'Samtida uttrycklig uppgift i faderskapsärende, bilaga, attest, domstol eller hushåll kan avgöra; ingen källklass är bevisat den enda möjliga vägen.'},os,'INFERRED'));
 if(id==='P-0495')targets.push(fact(p,'source_interpretation','late-census-and-name',{census1860_own_initials:'A. L.',earlier_last_life_claim:'Enbart1850talet är för snävt: C0749 har egen initialrad1846 i1860familjen.',father_corrected:'Carl Fr. Drill',father_rejected_transcription:'Carl Er. Grill',name_only:'Anna Lotta',anna_charlotta:'Sökform, inte belagt fullständigt namn.',married_name_change:'Ingen egen vigsel eller namnändring belagd; en vigsel skulle inte ensam bevisa namnbyte.',baptism_birth_gap_days:4},[...os,cs('C-0749'),cs('C-0794')],'INFERRED'));
 if(id==='P-0496'){
  targets.push(fact(p,'source_correction','lars-not-lovisa',{accepted_name:'Lars Petter',accepted_birth_report:'1848-02-27',old_name:'Lovisa',old_birth:'1849-02-27',old_reading_rejected:true,new_person_created:false,source_conflict_remaining:false,vaccination:'v i båda egna rader, ingen exakt vaccinationsdag',blank_fields:'Egna kunskaps-, förhörs-, nattvards-, vigsel-, döds- och anmärkningsfält tomma; inte föräldrarnas markeringar.',source_dependency:'SCB Son L.P.1848, man/ogift, korreleras genom familjen; utdraget är beroende, inte egen födelseoriginalpost.'},[...os,cs('C-0702'),cs('C-0749')],'TRANSCRIBED'));
  targets.push(add(p,'SEARCH-P-0496-C0794-corrected-birth','search',{source_id:'S-0116',outcome:'negative',scope_json:{description:'Bettna C5, den redan bevarade februaribilden1848.',query:{name:'Lars Petter',birth:'1848-02-27',parents:['Carl Fredrik Drill/Grill','Johanna Jansdotter']},bounds:{volume:'Bettna C/5',image:'C0005882_00041',sequence:'februari1848 vidare tillmars',date:'1848-02-27'}},body:'Ingen post med rättat namn/paret på27februari1848 i den lästa bildföljden. Inte ett helt års, socknens eller personens noll; husförhörets positiva rapport kvarstår.'},[...os,cs('C-0794')],[],'Den äldre1849Lovisa-kontrollen var felriktad och blir inget giltigt noll för Lars Petter.','TRANSCRIBED','recorded'));
 }
 if(['P-0494','P-0495','P-0496'].includes(id))targets.push(fact(p,'source_interpretation','household-routing',{literal:'52 Östra R.',old_literal:'52 W:a V.',old_reading_rejected:true,scope:'Hela överstrukna hushållets internnot, inte individuellt exakt flyttdatum.',destination:'Östra roten, Bettna',receiving_page:null,year1852_continuity_to1860:false,external_book_limit:'BettnaB2saknad externpost är förväntad vidinternnot, inte flyttnoll. VästraVingåkerBI3bilder30–31 hela1852 utanprofil är snävt avgränsadkontroll, inte visad destination.'},[...os,cs('C-0702'),cs('C-0771')],'INFERRED'));
 if(id==='P-0497'||id==='P-0498')targets.push(fact(p,'source_correction','birth-and-search-scope',{accepted_birth_report:born[id],old_birth:id==='P-0497'?'1854-04-21':'1858-11-22',old_reading_rejected:true,current_source_conflict:false,old_negative:{volume:'Bettna C/5',image:id==='P-0497'?'C0005882_00060':'C0005882_00074',date:id==='P-0497'?'1854-04-21':'1858-11-22',extent:id==='P-0497'?'Riktad aprilbild':'November11–30'},negative_applies_to_corrected_date:false,own_birth_post_found:false,scb_year_only:true,scb_independent_birth_evidence:false},[...os,cs('C-0729'),cs('C-0732'),cs('C-0749'),cs('C-0794')],'TRANSCRIBED'));
 if(id==='P-0497')targets.push(fact(p,'source_interpretation','own-boundaries',{scb1870:'Döttrarna som kollektiv; ingen individuell målrad eller eget exakt1870ankare utvunnet.',ai18:'Endast två systrar nämns i lagrad avskrift, inte en fullständig negativprövning av Johanna Mathilda.',ai17:'Äldre visuella/OCRkandidatkontroller ger inte namn-för-namn-frånvaro.',own_columns:'Kunskap, vaccination, nattvard och flyttnoter outvunna. Moderns eller Eriks marksituation fylls inte i.',carlsdotter:'Belagd hos Hedda, inte därmed hos Johanna Mathilda.',last_life:'Egen rad i volym1866–1870 utan säker precis sista närvarodag.'},os));
 if(id==='P-0498'){
  targets.push(...src(p,'C-0732','äldre Hedda','C0732-AI19-own','Hedda Carlsdotter','',{name:'Hedda Carlsdotter',birth:'1859-10-29',birth_parish:'Bettna',home:'Gatstugan, Backstuga',remarks:'Deflorata',internal_reference:'218/1 81'},os,'Den äldre Heddas egen rad. Ingen exakt kalenderdag läses ur internhänvisningen; den yngre Heddas dödsnot hör inte hit.'));
  targets.push(...src(p,'C-0750','SCB1880','C0750-own','Hedda Carlsdotter','dotter',{name:'Hedda Carlsdotter',birth_year:1859,birth_parish:'Bettna',home:'Gatstugan Backstuga'},os,'Egen rad i den lästa familjegruppen1880; avskrift/index är beroende av kyrkobokföring. Enda här upptagna barnet betyder inte enda levande barnet.'));
  targets.push(...event(p,'residence',year(1880),os,'SCB1880 egen rad, Gatstugan Backstuga, Bettna. Ingen obruten vistelse till moderns död1883 bevisad.',null,'TRANSCRIBED',`E-residence-${id}-1880`));
  const younger=reuse(p,'F-P-0474-family_context-two-Heddas',os,'Den yngre Hedda har egen klamrad barnrad och dödsnot, inte den äldre Heddas död eller ett automatiskt nytt barn till morföräldrarna.');targets.push(younger);map['Yngre Hedda']=[younger];
  targets.push(fact(p,'source_interpretation','two-heddas-and-notes',{own_remark:'Deflorata',remark_limit:'Kyrklig notis utan egen daterad rättslig händelse, medicinsk diagnos eller säkert födelsebevis.',own_internal_reference:'218/1 81',normalized_move_date:null,other_child_reference:'AI18s20 har30/4 och190/1; endast190/1 är uttryckligen knuten tillMariaSofia,30/4 förs inte automatiskt tillHedda.',younger_name:'Hedda Carlsdotter',younger_birth_raw:'79[?] 29/10',younger_death_report:'1883-11-10',younger_person_id:null,biological_maternity:'Sannolikt genom klammer och dotter, inte avgjort; fosterrelation eller skrivfel inte motprövade.',biological_father:null,own_death:null,mother_death_proves_own_survival:false,longest_resident_child_proven:false,place_correction:'C0732senaste: Gatstugan; äldre Götstugan var avskriftsfel. Faderns senareHagbystugan kontraGatstugan är skilda bokföringsfält, inte tre bevisade fysiska boställen för Hedda.',father1890:'Egen ensamrad hos fadern visar varken Heddas död eller hennes utflyttning ur socknen.'},[...os,cs('C-0732'),cs('C-0750')],'INFERRED'));
 }
 if(id==='P-0499')targets.push(fact(p,'source_interpretation','birth-context-and-siblings',{preferred_birth:'1863-02-27',baptism:'1863-03-08',household_raw_birth:'1863-03-27',old_birth_record_reading_rejected:'27mars/8april',record_context:'Februari fortsätter frånpost10till14; mars börjarpost15. Dopmånadens mars följer föregående notering.',argument_limit:'27mars är senare hushållsrapport, inte ett motbevis inom en enda post. Dop8mars och födelse27mars kan inte båda vara riktiga; prioriteringen27feb grundas på egenposts tydliga månadskontext, inte på antagande att varje dopdag är ofelbar. Jämförelsen med P0446 avgör inte den personens identitet.',birth_home:'Hagby soldattorp[?]',birth_home_role:'Faderns rapporterade hemvist, inte belagd exakt fysisk födelseplats.',old_home_omission:'Aktens påstående att ingen soldattorpsort står saknar stöd i sena C0794; Glippsta överförs inte.',closest_known_older_sibling:'P-0498',closest_known_gap:'3år3månader29dagar',twelve_year_gap_is_not_adjacent:true,omitted_known_siblings:['P-0496','P-0497','P-0498'],erik_gap:'1851-01-30–1863-02-27 är12år28dagar, ungefär12år1månad, inte intilliggande barnfödslar.',lifetime_last_child_proven:false,maternal_age:43,internal_reference:'190/1',reference_limit:'Mottagarsida190 rapporteras återfunnen i C0732, men egen fullrad och exakt flyttdag är inte utvunna här.',own_continuous_residence_after_ai18:false,baptism_birth_gap_days:9},[...os,cs('C-0794'),cs('C-0729'),cs('C-0732'),cs('C-0721')],'INFERRED'));
 relRows(p,map);for(const a of assertions[id])assertion(p,a,targets,'Egen källrad, aktuella datum/rättelser, anhörigrelationer och uttryckligt avgränsade jämförelser representerade; äldre analytiska överpåståenden kvalificerade i egna sakobjekt.');save(p);
}
