import {person,core,fact,event,reuse,relation,assertion,relationRow,save,origins,exact,units,section,src,cs,add} from './genealogy2-persons10-combined.mjs';
const all=p=>[origins(p.person,'person',1,Math.max(...units(p.person,'person').map(u=>u.end_line)))];
const birthR='R-a2a8fc78bdeaaae25c917e7f',homeR='R-5785656ae35a013a260b39b3';
const children=[{name:'Anna Maja Andersdotter',birth:'1806-08-02'},{name:'Eric Andersson',birth:'1809-09-27',rejected_older_date:'1809-07-27'},{name:'Anders Andersson',birth:'1812-04-12',rejected_older_date:'1812-04-19'},{name:'Cajsa Lena Jansdotter',birth:'1816-08-13',daughter_marked:true},{person:'P-0475',name:'Johanna',birth:'1819-05-30',daughter_marked:true},{name:'Brita Stina Jansdotter',birth:'1821-10-22',daughter_marked:true}];
for(const [id,isJan]of[['P-0476',true],['P-0477',false]]){
 const p=person(id,'Hela akt/profil och hela C0721/C0731 inklusive senaste följdresonemang lästa. Prövad vuxenfamilj skiljs från Jan1791/Helena1785-kandidater; inga kandidatföräldrar skapas. T0173:s15/18/21år och uteslutetfaderskap är för starka: exakta datum ger14/18/20 och ålder/patronymikon bevisar varken förälder eller vigselintervall. Gamla fullårsnoll och olästa egna fält kvalificeras individuellt.');const os=all(p);
 core(p,[section(p,'Identitet'),cs('C-0721')],'Individuell identifikation genom samma namngivna par, Walla, Johannas egen1819födelse och hennes familjerad. GODKÄND/BÄRANDE gäller vuxenidentitet och relation nedåt; egna kandidatursprung och livsbild UNDERKÄND består.',null,'CORROBORATED');
 const childSource=src(p,'C-0721','','C0721-parent',isJan?'Jan Ericson':'Lena Jonsdotter',isJan?'hemmansbrukaren':'hustrun',{child:'Johanna',child_birth:'1819-05-30',child_baptism:'1819-05-31',home:'Walla',...(isJan?{spouse:'Lena Jonsdotter'}:{spouse:'Jan Ericson',own_age_reported:34})},[isJan?'A-2850':'A-2852'],'Egen namngiven föräldraroll i dotterns avgränsade födelsepost; inga vuxenradens födelsedata i denna observation.','accepted',birthR);
 const homeData=isJan?{birth_literal:'1791 5/9 Björkvik',arrival_year:1815,arrival_phrase:'Laffinge/Läffinge[?] L.M.[?]',smallpox_cell:'tom',reading_signs:'K-liknande markeringar och ett streck',church_signs:{1819:'två bokstavsliknande nattvardstecken och förhörstecken',1820:'små nattvardstecken och förhör',1821:'g-liknande nattvard och förhör'},year_fields1822_1823:'tomma',departure_fields:'tomma',disability_and_life_circumstances:'tomt',own_death_note:null}:{birth_literal:'1783 21/10 Malm'};
 const home=src(p,'C-0721','','C0721-Walla',isJan?'Jan Ericson':'Lena Jonsdotter',isJan?'brukaren':'hustrun',homeData,os,isJan?'Egna fullprövade T0141-fält. Barnensv överförs inte; tomt fält bevisar inte hälsa eller död.':'Senaste lästa namn-/datumrad. Makens fullprövning ger inga egna tomma kunskaps-/års-/kopporfält.','accepted',homeR);
 const child=relation(p,id,'P-0475','parent',os);const spouse=relation(p,'P-0476','P-0477','spouse',os,'recorded_spouse');
 const family=isJan?fact(p,'household_membership','Walla-six-children',{place:'Walla',parish:'Stora Malm',farm:'Uppgården',page:80,children,all_children_birth_parish_literal:'Malm',older_Anders_children_biological_parentage_unknown:true,lower_servants_inmates_not_automatically_related:true,no_lifetime_child_count:true,child_birth_years_not_proof_of_continuous_Walla_residence:true,daughter_Johanna_departure1841_not_parents_life_point:true},os):reuse(p,'F-P-0476-household_membership-Walla-six-children',os);
 const witnessIds=['CarlEricErsson','MajaJonsdotter','PehrLarsson','GretaLenaLarsdotter'].map(k=>reuse(p,`EP-E-baptism-P-0475-${k}-witness`,os));
 const limits=fact(p,'research_limits','own-life',{own_parents_unknown:true,own_death_burial_unknown:true,own_exact_marriage_date_unknown:true,spouse_and_child_are_not_origin_bridge:true,Jans1815arrival_is_only_Jans:true,Johannas1841departure_is_only_Johannas:true,child_years_do_not_prove_continuous_own_residence1816_1821:true,no_personal_or_property_or_military_records_searched:true,...(!isJan?{own_literacy_knowledge_smallpox_annual_church_fields_unextracted:true,act_claims_empty_own_annual_fields_but_citation_full_review_is_Jans:true,own_empty_migration_fields_reported_in_act_not_confirmed_by_separate_citation_extraction:true,husbands_occupation_not_own:true}:{occupation_does_not_prove_ownership:true,blank_smallpox_does_not_mean_no_disease:true,blank_later_years_not_death_or_absence:true})},os);
 let candidate,assessment,ownBirth;
 if(isJan){
  ownBirth=event(p,'birth',exact('1791-09-05'),['A-2851',cs('C-0721')],'Rättad senare Walla-uppgift med Björkvik som rapporterad socken; födelsekandidaten identifieras inte automatiskt.');
  const arrival=event(p,'registered_arrival',{precision:'year',value:'1815',literal:'1815'},['A-4676'],'Eget bokfört år, ingen exakt fysisk flyttdag eller normaliserad ursprungsförsamling.');
  const life=fact(p,'occupation','Walla',{forms:['hemmansbrukaren','brukaren'],home:'Walla',parish:'Stora Malm',birth_parish_reported:'Björkvik',arrival_phrase:'Laffinge/Läffinge[?] L.M.[?]',arrival_parish_chosen:null,reading_signs:'K-liknande',church_signs_years:[1819,1820,1821],no_invented_school_level_or_church_dates:true,ownership_unproven:true},os);
  candidate=src(p,'C-0731','bild190','Jan1791-candidate','Jan','Son',{birth:'1791-09-05',baptism:'1791-09-06',home:'Åtorp[?]',father_literal:'Arb. Eric Anderssons',mother_literal:'dess Hust. Anna Andersdotters',parents_phrase_literal:'Arb. Eric Anderssons och dess Hust. Anna Andersdotters',baptism_place:'St. Malms [kyrka?]',mother_churched:'St. Malm',mother_age_not_stated:true,mother_churching_exact_date_not_stated:true,witnesses:[{name:'Carl Andersson',wife:'Anna Andersdotter',place:'Åbol[?] i St. Malm'},{name:'Eric Ersson',role:'dr.',place:'Åtorp[?] i St. Malm'},{name:'Anna Stina Carlsdr',role:'dottern',place:'ib.'}]},['A-4675'],'Samtida post, men uttrycklig personlig brygga till Walla saknas. Bokföringsförsamling, hemvist och dopplats skiljs.','candidate');
  assessment=fact(p,'identity_assessment','Jan1791-candidate',{adult_date:'1791-09-05',adult_parish:'Björkvik',candidate_record:'R-de8eeb46e6961ce1353920c1',matching:['Jan','5september1791','farEric'],bridge_missing:true,chosen_identity:false,candidate_parents_not_accepted:true,candidate_baptism_not_own_accepted_event:true,source_parish_does_not_prove_birth_parish_of_candidate:true},['A-4675'],'LEAD');p.changes.at(-1).disposition='candidate';
  const search=add(p,'SEARCH-P-0476-historical-May1791','search',{question_id:null,source_id:'S-0564',scope_json:{description:'Tidigare felriktad majkontroll inom fem bevarade bilder.',query:'Jan född1791-05-09',bounds:{book:'BjörkvikC/4',images:'C0005938_00187–00191',May_image:'C0005938_00188',last_image_ends:'november',whole_year:false}},outcome:'negative',body:'Ingen Jan på den då felavlästa9majnyckeln. Utfallet är historiskt felriktat för målpersonen och säger inget om5september. Senare faktisk kontroll av samma bilder gav positiv kandidat på190. December-/helårsgräns inte verifierad.'},['A-2851',cs('C-0731')],[],'Historisk felnyckel, inget aktuellt personnoll.','NEGATIVE','retired');
  const correction=fact(p,'source_assessment','May-correction',{rejected_older_birth:'1791-05-09',corrected_adult_birth:'1791-09-05',old_conflict_rejected:true,old_May_negative_not_September_negative:true,positive_candidate_found:true,five_images_not_full_year:true,no_unique_candidate_in_whole_year_claim:true,Lena_Helena_candidate_not_Jans_birth:true},['A-2851',cs('C-0731')]);
  assertion(p,'A-2850',[...childSource,...home,child,spouse,family,life],'Samtida fadersnamn och korrelerad egen familjerad, inget härkomstbeslut.');
  assertion(p,'A-2851',[...ownBirth,correction,search],'Avvisningen gäller gammal majkonflikt; rätt septembernyckel och gammalt felriktat noll bevaras.');
  assertion(p,'A-4675',[...candidate,assessment],'Hela kandidaten inklusive dop iStoraMalm, råföräldrar och geografiska reservationer, utan identitetsfusion.');
  assertion(p,'A-4676',[...home,...arrival,life],'Egen1815uppgift med osäker fras; ingen make-/dotterflytt härledd.');
  relationRow(p,'P-0477',[spouse,family],'Dokumenterad hustru i vuxenfamiljen.');relationRow(p,'P-0475',[child,...childSource,family],'Johanna född1819-05-30 och uttrycklig dotter.');
  for(const name of ['Cajsa Lena','Brita Stina','Anna Maja','Eric Andersson','Anders Andersson'])relationRow(p,name,[family,limits],'Exakt rättad barnrad, patronymikon och datum bevarade utan nya person-ID eller biologiska slutsatser.');
 }else{
  ownBirth=event(p,'birth',{precision:'unknown',literal:'1783-10-21 i hushåll; ålder34 ger1784-05-31–1785-05-30; separat Helena-kandidat1785-10-31'},['A-2853','A-7671'],'Ingen av de olika kunskapsgrunderna väljs. Kandidatposten är inte en accepterad egen födelse.',null,'CONFLICT');
  candidate=src(p,'C-0731','Helena','Helena1785-candidate','Helena','',{birth:'1785-10-31',baptism:'1785-11-06',home:'Walla',father_reading_reserved:'Jonas Ersson',mother_reading_reserved:'Cajsa Persdotter'},['A-2854'],'Ingen separat råroll utvunnen. Kandidaten är dubbelt försvagad men kvar som LEAD; ingen identitets- eller föräldrapropagation.','candidate');
  assessment=fact(p,'birth_assessment','three-bases',{household_date:'1783-10-21',household_parish_literal:'Malm',rejected_old_household_transcription:'1785-10-31',reported_age_at_child_birth:34,child_birth:'1819-05-30',derived_window_if_completed_years:{from:'1784-05-31',to:'1785-05-30'},household_date_gives_age:35,candidate_date:'1785-10-31',candidate_date_gives_age:33,candidate_identity_unproved:true,age_may_be_rounded_or_running_year:true,chosen:null,no_date_created_from_window:true,Helena_still_LEAD:true,candidate_parents_not_accepted:true,old1785_search_not_negative_for1783_1784_keys:true,possible1784_10_21_is_hypothesis_not_fact:true},['A-2853','A-2854','A-7671',cs('C-0721'),cs('C-0731')],'CONFLICT');
  const hypothesis=fact(p,'family_hypothesis','Anders-children',{children,all_birth_parish_literal:'Malm',Jans_reported_birth:'1791-09-05',older_children_Jans_completed_ages:[14,18,20],old_ages_15_18_21_not_exact:true,age_alone_does_not_exclude_fatherhood:true,patronymic_does_not_identify_mother:true,older_children_are_Lenas_unproven:true,earlier_husband_Anders_unproven:true,no_new_husband_person_or_biological_child_edges:true,possible_marriage_search_window:['1812-04-12','1816-08-13'],window_conditional_on_family_hypothesis:true,no_exact_marriage_event:true,childbearing_does_not_itself_prove_marriage:true},['A-7672',cs('C-0721')],'LEAD','Äldre positivt uteslutande och säker vigseldatering är inte styrkta av räkningen. Hypotes och faktiskt hushåll skiljs.');p.changes.at(-1).disposition='candidate';
  const network=fact(p,'social_network','Johanna-baptism',{child:'P-0475',baptism:'1819-05-31',witnesses:[{name:'Carl Eric Ersson',role:'brukaren',spouse:'Maja Jonsdotter',place:'Hindricstorp[?]'},{name:'Maja Jonsdotter',role:'hustru',place:'Hindricstorp[?]'},{name:'Pehr Larsson',role:'sonen',place:'Maglinge[?]'},{name:'Greta Lena Larsdotter',role:'pigan',place:'Djulvekvarn[?]'}],Maja_sister_hypothesis_name_compatibility_only:true,no_kinship_created:true,shared_patronymic_not_unique_family_identifier:true},['A-7673',cs('C-0721')]);
  assertion(p,'A-2852',[...childSource,...home,child,spouse,family],'Samtida modernamn och samma vuxenfamilj, skild från hennes egna födelsedata.');
  assertion(p,'A-2853',[...home,...ownBirth,assessment],'Rättad senare1783-10-21uppgift med ålderskonflikt; ingen vald egen födelse.');
  assertion(p,'A-2854',[...candidate,assessment],'Separat Helena-post med reserverade föräldrar, fortsattLEAD och spärrad propagation.');
  assertion(p,'A-7671',[...childSource,assessment],'Uppgiven34, villkorligt åldersfönster och35/33jämförelse, med åldersosäkerhet och inget valt datum.');
  assertion(p,'A-7672',[family,hypothesis],'Alla sex barn och rättade datum; åldersräkning korrigerad14/18/20 utan påhittat faderskapsuteslutande eller vigsel.');
  assertion(p,'A-7673',[network,...witnessIds],'Alla fyra verkliga dopvittnen och ortreservationer, ingen syster utsedd.');
  relationRow(p,'P-0475',[child,...childSource,family,limits],'Säker dotter, men hennes1841flytt bevisar inte moderns dåvarande liv/hemvist.');relationRow(p,'P-0476',[spouse,family,limits,hypothesis],'Make och hans1815uppgift, inte moderns inflyttning.');
  p.pending.push({origin:'A-7672',question:'Födelsedatumen1791-09-05 och1806-08-02/1809-09-27/1812-04-12 ger14/18/20fyllda år. Varken dessa åldrar eller patronymika avgör biologiskt faderskap/moderskap eller ett äktenskap1812–1816. Äldre säkert uteslutande förblir historik, hypotesen är villkorlig.'},{origin:section(p,'Hälsa och död'),question:'Lenas profil säger egna årsfält tomma samtidigt som KP04/C0721 säger dem outvunna. T0141 prövade Jans, inte hennes. Ingen egen tomhet/död eller1816–1821obrutenhemvist får härledas från hans fält eller barnens födelseår.'});
 }
 if(isJan)p.pending.push({origin:section(p,'Inkommande följdfynd från T-0173, 2026-09-09'),question:'Följdnoten kallarJan15/18/21vidAndersbarnen och utesluterfaderskap. Datumger14/18/20; räkningen ensam bevisar inte biologiskt uteslutande. Lenas eventuella tidigare gifte1812–1816 är uttryckligen villkorlig hypotes, se hennes särskilda bedömning.'});
 save(p);
}
