import{db,doc,units,origins,exact,unknown,person,add,assertion,relationRow,save,row,section,reuse,known,core,fact,relation,event,src,cs,record}from './genealogy2-persons10-combined.mjs';
const yr=y=>({precision:'year',value:String(y),literal:String(y)}),unc=s=>({precision:'unknown',literal:s});
const os=(p,s)=>[section(p,s)];
function search(p,key,sid,cid,query,bounds,body,orig){return add(p,`SEARCH-${p.person}-${key}`,'search',{source_id:sid,question_id:null,outcome:'negative',scope_json:{description:body,query,bounds},body},[...orig,cs(cid)],[],body,'NEGATIVE','recorded');}
function ev(p,type,date,orig,mention,id=undefined,role='principal',cav=''){const e=event(p,type,date,orig,cav,null,'TRANSCRIBED',id,role);const x=p.changes.find(x=>x.id===e[1]);if(x&&mention)x.data.mention_id=mention;return e;}
function witness(p,cid,filter,key,name,rawRole,data,eventId,orig){const a=src(p,cid,filter,key,name,rawRole,data,orig,'Vittnes-/utfärdarroll, inget automatiskt släktskap.',null);const eid=`EP-${eventId}-${key}-witness`;if(known(eid))reuse(p,eid,orig);else add(p,eid,'participation',{event_id:eventId,person_id:null,mention_id:a[0],role:'witness'},[...orig,cs(cid)],[], 'Namngiven deltagare utan ny person.');return[...a,eid];}
function shared(p){const h=[];const sid=p.person==='P-0474'?'father':'mother';const father=sid==='father';for(const[cid,filter,key,name,role,data]of[
 ['C-0718','A I/11a','AI11',father?'Carl Fr. Drill':'Johanna Jansdotter',father?'Sold.':'',{birth:father?'22 9/4 Halla':'19 30/5 St. Malm',arrival:father?'41 Björkvik':'41 St. Malm',smallpox:'v',knowledge:'grafiska grader',communion:['1844 11/2','1845 19/10'],banns:'Lyst t. äkt. m. hvarandra d. 16 april 1843[?]',marriage_and_death_year_blank:true}],
 ['C-0702','A I/12a','AI12',father?'Carl Fr. Drill':'Joh. Jansd:r',father?'Sold.':'',{birth:father?'22 9/4 Halla':'19 30/5 St. Malm',arrival:father?'tomt':'41 St. Malm',smallpox:'v',knowledge:'läs-/kunskapsstreck, prickar i kristendomsfält',communion:['1848 27/8','1849 1/4'],marriage_death_remarks_blank:true}],
 ['C-0702','A I/13a','AI13',father?'Carl Fr. Drill':'Joh. Jansd:r',father?'Sold.':'',{birth:father?'22 9/4 Halla':'19 30/5 St. Malm',smallpox:'v',knowledge:'läs-/kunskapsstreck, prickar',communion:['1852 18/7'],examination:father?'1851 6/11':'bleka äldre tal',family_crossed:true,departure:father?'52 Östra R.':'streck',marriage_death_own_remarks_blank:true}],
 ['C-0729','A I/16b','AI16',father?'Carl Fredrik Drill':'Johanna Jansdotter','',{birth:father?'1822 9/4 Halla':'1819 30/4 Stora Malm',title:father?'soldat':'hustru',smallpox:'v',knowledge:'grafiska betyg',communion:father?['1868 13/12']:['1867 14/4','1868 13/12'],examination:father?['1866 10/11','1867 21/11[?]']:['1869 10/11','1870 grafiskt tecken'],own_arrival_marriage_death_departure_remarks_blank:true}],
 ['C-0732','A I/18a','AI18',father?'Carl Fredrik':'Johanna Jansdotter','',{birth:father?'1822 9/4 Halla':'1819 30/4 Stora Malm',title:father?'soldat; tillägg avskedad':'hustru',smallpox:'v',knowledge:'grafiska läsbetyg, försv.[?]',communion:['1876 8/10','1877 21/10','1878 6/10'],examination:father?['1877 tecken','1879 tecken']:['1877 tecken'],own_arrival_marriage_death_blank:true,departure:'hårt överstruket, ingen säker destination/dag',remarks:father?'Gratialist':''}],
 ['C-0732','s193 Gatstugan, Carl','AI19',father?'Carl Fredrik':'Johanna Jansdotter','',{birth:father?'1822 9/4 Halla':'1819 30/4 Stora Malm',title:father?'avskedad soldat':'hustru',place:'Gatstugan, Backstuga (ytterligare reserverad parentes)',smallpox:'v',knowledge:'grafiska betyg, försv.[?]',communion:father?['1882 25/6','1884 20/7']:['1882 25/6'],examination:'grafiska tecken',widowed:father?'83 24/2':null,death:father?null:'83 24/2',departure:father?'22[?]/[rad?] 85':'tomt',arrival_blank:true,remarks:father?'Gratialist':'tomt'}],
 ['C-0749','SCB1860','SCB1860',father?'Drill C. F.':'Jansdotter J.',father?'':'Dess Hustru',{birth_year:father?'1822':'1819',title:father?'soldat':'',married:true,birthplace_column:'blott län eller stad; förkortning reserverad',children:['A. L.1846','L. P.1848','E.1851','J. M.1854','H.1859']}],
 ['C-0729','SCB1870','SCB1870',father?'Carl Fredrik Grill':'Johanna Jonsdotter','',{birth_year:father?'1822':'1819',birthplace:father?'Halla':'Stora Malm',title:father?'soldat':'',children:'döttrarna; Erik inte i utdragshushållet'}],
 ['C-0750','SCB1880','SCB1880',father?'Carl Fredrik Grill':'Johanna Jansdotter',father?'':'hustru',{birth_year:father?'1822':'1819',birthplace:father?'Halla':'Stora Malm',place:'Gatstugan Backstuga',occupation:father?'afskedad soldat vid Kungl. Södermanlands regemente':'',daughter:'Hedda Carlsdotter1859Bettna'}]
])h.push(...src(p,cid,filter,key,name,role,data,os(p,'Tidslinje'),'Egna fält; bleka tal förblir reserverade. Tom råroll betyder att separat ordagrann roll inte säkrats. Utdrag och HFL är inte oberoende födelseoriginal.'));
return h;}
function commonFacts(p){const m=fact(p,'marriage_assessment','undated',{spouse:p.person==='P-0474'?'P-0475':'P-0474',banns1841:'överstruket ärende Stora Malm; vigselkolumn tom',banns1843:'16 april 1843[?], årsslutsiffran reserverad',Carl_unmarried_asof:'1842-06-14',Carl_married_asof:'1845-07-07',muster_date_not_wedding_date:true,wife_not_named_in_muster:true,Johanna_wife_in_childbirth:'1846-01-14',CarlJohan_oakta_not_safe_marriage_lower_bound:true,marriage_date:null,late27month_anomaly_proven:false},[section(p,'Militärt, civilt och rättsligt'),cs('C-0718'),cs('C-0763'),cs('C-0794')],'TRANSCRIBED','Senare T0202 resonemang bevaras, men status vid mönstring får inte bli vigseldatum eller bevisat27mån dröjsmål.');
const f=fact(p,'residence','documented-family-chain',{anchors:['Glippsta s33 iAI11/12','Glippsta s37AI13,52 Östra R.','SCB1860Bettna','HagbyÖstraSoldattorp38AI16s201','HagbyAI18s20','GatstuganAI19s193'],continuous_physical_presence:false,family_folios1852_1866_open:true,old52_WaV_rejected:true,exact_next_farm_page_unknown:true,child_lives_not_extended_from_parents:true},[section(p,'Boställen och flyttar'),cs('C-0771')]);
return[m,f];}
{
const p=person('P-0474','Hela426radersakten/profilen och22relevantaC lästa inklusiveT0173/T0202. Ulla/[P]iltbarn rättar äldreElla/gosse. April/juli verklig konflikt endast egna1840attesten motapril; historiskaHFLfel inte extra röster. Rullans giftstatus intevigsel. Kandidater/avvisningar, källnoll och forskningsprofil skilda.');
core(p,[section(p,'Identitet')],'Attester, råcivilnamn, rote, flytt, födelse och vuxenfamilj korrelerar en person. Ingen far av patronymikon. KontraktUNDERKÄND består.',null,'CORROBORATED');
const b=src(p,'C-0798','post 3 Carl','birth','Carl Fredrik','[P]iltbarn',{born:'1822-04-09',baptised:'1822-04-12',place:'Lilla Wättstugan',mother:'Pig. Ulla Ersdotters',mother_age:28,father_not_named:true,illegitimacy:'oäkta',margin:'ab.',no_officiant_or_churching_date:true},['A-3066',section(p,'Inkommande följdfynd från T-0173, 2026-09-09')],'Ulla och[P]iltbarn är senasteT0173läsning; modersålder28, inte23.');
const birth=ev(p,'birth',exact('1822-04-09'),['A-3066','A-2894'],b[0]);const bap=ev(p,'baptism',exact('1822-04-12'),['A-3066'],b[0]);const bp=fact(p,'birth_place','Halla',{locality:'Lilla Wättstugan',parish:'Halla',not_identical_to_Lilla_Linvafvarstugan:true},['A-3066','A-3068']);
const mother=relation(p,'P-0500',p.person,'parent',['A-3066',section(p,'Relationer')]);const father=fact(p,'parentage','unknown-father',{mother:'P-0500',mother_reading:'Ulla Ersdotter',old_Ella_rejected:true,father:null,Pehrsson_Pettersson_not_identification:true,ab_interpretation:'sannolikt absolverad',ab_not_dated_event:true,no_father_or_employer_inferred:true,comparison_posts:[3,4,5],neighbours6_7_not_counted:true},['A-3066',section(p,'Inkommande följdfynd från T-0173, 2026-09-09'),cs('C-0798')]);
const bws=[];for(const[k,n,r]of[['Rihlstadius','H. Rihlstadius[?]','Enkefru'],['Andersson','A. Andersson','Mjölny[?]gesällen'],['Lars','Lars','dr.'],['AnnaLena','Anna Lena','pig.']]){const ids=witness(p,'C-0798','post 3 Carl',k,n,r,{place:'alla i Björklund[?]'},bap[0],os(p,'Relationer'));bws.push(...ids);if(n==='Lars')p.relations.push({unit:units(p.person,'person').find(u=>u.kind==='relation_row'&&JSON.parse(u.parsed_json).cells[0]==='Lars').id,state:'mapped_complete',targets:ids,rationale:'Eget dopvittne, inte släktskap eller säkert gemensamt hushåll.'});else relationRow(p,n,ids,'Eget dopvittne; ortgruppen bevisar inte gemensamt hushåll, tjänst eller släktskap.');}
const hs=shared(p),common=commonFacts(p),sp=relation(p,p.person,'P-0475','spouse',os(p,'Relationer'),'recorded_spouse','CORROBORATED');
const af=fact(p,'family_context','Anders-Fredric1844',{name:'Anders Fredric',role:'S.',birth_year:1844,birthplace:'Bettna',birth_day_month_obscured:true,death_year:1844,death_day_month:'24[?]/12',crossed:true,person_id:null,biological_parentage_not_established:true,lifetime_child_total:null},[section(p,'Relationer'),cs('C-0718')]);
const hh=fact(p,'family_context','two-Heddas',{older:'P-0498',older_birth:'1859-10-29',younger_name:'Hedda Carlsdotter',younger_birth:'1879[?]-10-29',younger_death:'1883-11-10',bracket_starts_on_older:true,younger_is_older_daughter:true,grandchild:'sannolikt',not_another_own_daughter:true,no_new_person:true,no_father_from_patronymic:true},['A-2845',section(p,'Relationer'),cs('C-0732')],'INFERRED');
const younger=src(p,'C-0732','äldre Hedda och hennes dotter','younger-Hedda','Hedda Carlsdotter','dotter',{birth:'79[?] 29/10 Bettna',death:'83 10/11',bracket_starts_at_older_Hedda:true},os(p,'Relationer'),'Ingen ny person; den yngre hör till äldreHeddas familjegrupp.',null);const youngerDeath='E-death-younger-Hedda-Gatstugan1883';add(p,youngerDeath,'event',{event_type:'death',date_json:exact('1883-11-10'),place_id:null,place_role:'place_of_event'},[section(p,'Relationer'),cs('C-0732')],[],'Egen dödnot för yngreHedda, fysisk dödsplats ej angiven.');add(p,`EP-${youngerDeath}-younger-Hedda-principal`,'participation',{event_id:youngerDeath,person_id:null,mention_id:younger[0],role:'principal'},[section(p,'Relationer'),cs('C-0732')]);
const reg=src(p,'C-0732','A I/20a','gratialist-register','Carl Fredr. Drill','',{place:'Gatstugan',birth:'1822 9/4'},['A-2846']);
const late=src(p,'C-0750','s47','AI20','Carl Fredrik Grill/Drill','',{birth:'1822 9/4 Halla',title:'avskedad soldat',place:'Hagbystugan, Backstuga, Hagby ägor',widowed:'83 24/2',smallpox:'v',knowledge:'fyra grafiska betyg',communion:['1888 22/1','1890 31/8'],examination:['1887tecken','1888tecken','1890tecken'],remarks:'gratialist;ytterligarebleknoteringoläst',arrival_death_departure_blank:true},['A-2926']);
const rplace=fact(p,'source_assessment','register-vs-folio',{register:'Gatstugan',ownfolio:'Hagbystugan',physical_conflict_or_move_proven:false,older_Grill_Gotstugan_July_readings_rejected:true},['A-2846','A-2926',cs('C-0732'),cs('C-0750')]);
const s90=src(p,'C-0750','SCB1890','SCB1890','Carl Fredrik Grill','',{birth_year:1822,birthplace:'Halla',title:'före detta/avskedad soldat',widower:true,place:'Hagbystugan'},['A-2925']);
const idx=fact(p,'name_form','census-index',{index1880:'Drill',index1890:'Drill, Karl Fredrik',original1880_1890:'Carl Fredrik Grill',same_correlated_family:true,no_new_person:true},['A-2922','A-2925',cs('C-0750')]);
const dr=src(p,'C-0743','F/4','death','Carl Fredrik Grill','',{death:'1895-01-04',burial:'1895-01-13',birth:'1822 9/4',title:'avskedad soldat',home:'Stora Hesselstugan',reference:'1:27',sex:'man',civil_status:'änkling',blank:['cause','death_place','certificate','remarks']},['A-2893']);
const hr=src(p,'C-0743','A I/21a','AI21','Carl Fredrik Grill','',{birth:'1822 9/4 Halla',title:'avskedad soldat',widowed:'24/2 83',smallpox:'v',knowledge:'fyra grafiska betyg',from:'p.1:47 år94',death:'4/1 95',annual_and_departure_blank:true,remarks:'Fri.[?]'},['A-2893','A-2894']);
const death=ev(p,'death',exact('1895-01-04'),['A-2893'],dr[0]);p.changes.find(x=>x.id===death[0]).evidenceStatus='CORROBORATED';const burial=ev(p,'burial',exact('1895-01-13'),['A-2893'],dr[0]);const arrival=ev(p,'registered_arrival',yr(1894),os(p,'Tidslinje'),hr[0],'E-arrival-P-0474-Hesselstugan1894','principal','Bokförd internöverföring; inte fysisk resdag.');
const limits=fact(p,'life_context','limits',{death_place:null,death_cause:null,death_home_not_death_place:true,birth_conflict_not_person_split:true,childhood_chain_open:true,Jernbol_attests_not_HFL:true,marriage_date_unknown:true,physical_residence_not_continuous:true,military_discharge_date_unknown:true,pension_amount_unknown:true,probate_unread:true,no_own_letter_photo_in_reviewed_material:true,not_full_personal_archive_search:true,signatures_belong_to_issuers:true,knowledge_not_school_grade:true,Fri_not_legal_conclusion:true},[section(p,'Forskningsfrågor och konflikter'),section(p,'Media och personliga källor')]);
const reject=src(p,'C-0732','1885 post2','Carlsson-rejected','Carl Fredrik Carlsson','',{death:'1885-01-18',age:'62år9mån29dagar',widower:true,place:'annan svårläst ort'},['A-2847'],'Annan personprofil/ort; positiv egen död1895. Åldersberäkning ensam avgör inte.','rejected');p.changes.find(x=>x.id===reject[1]).evidenceStatus='REJECTED';
const rec=src(p,'C-0793','rekryteringsrulla','recruit','Carl Fredrik Drill','',{document_date:'1840-12-31',numbers:'36/36',rote:'Glippsta',hired_by:'Lejd af Roten N:o142Bokulla',birth_county:'Sörmland',birth_year:'1822 rättat/överskrivet',height:'5fot10tum',marital_status:'ogift',remark:'Approberas [mellanordejutvunna] den15Febr.1841',exposures:[24,26]},['A-3038']);
const att=[];for(const[cfilter,key,name,role,data,a]of[
 ['tillståndsintyg','permission','Carl Drill','Drängen',{date:'1840-12-20',place:'Jernbol',issuer:'Anders Andersson',mark:'bomärke',permission:'bevista[?] ex-sisen i Sommar',conditions:'sedan överenskomma och enas'},'A-3039'],
 ['kyrkoattest','church-attest','Carl Fredric Pehrsson','Drängen',{date:'1840-12-15',place:'Björkvik',home:'Jernbol',birth:'1822 9/7 Halla',issuer:'[initialer?] Rendgren[?]',issuer_role:'Vice pastor',assessments:['försvarlig kristendomskunskap','ärlig levnad','ordentligt bruk av salighetsmedlen','vaccination']},'A-3062'],
 ['tjänsteintyg','service-attest','Carl Fredric Pehrsson','Drängen',{date:'1840-12-14',place:'Jernbol',service_since:'hösten1837',release:'nästkommande24oktober på egen begäran',issuer:'Anders Andersson',mark:'bomärke',assessment:['nykterhet','trohet','frånvaro av för honom kända felaktigheter'],margin:'C. F. Drill'},'A-3063'],
 ['medicinsk attest','medical-attest','Carl Fredrik Pettersson','drängen',{date:'1840-12-16',place:'Nyköping',home:'Jernbol,Björkvik',issuer:'C. W. Martin[?]',issuer_role:'Provinsialläkaren',assessment:'frisk och färdig till alla lemmar samt duglig till krigsstånd',continuation:'edlig försäkran'},'A-3064']]){att.push(...src(p,'C-0793',cfilter,key,name,role,data,[a]));ev(p,'other',exact(data.date),[a],att.at(-3),`E-${key}-P-0474-1840`);}
const ac=fact(p,'attestation_limits','1840',{exercise_performed_not_proven:true,final_contract_terms_unknown:true,no_own_signature:true,no_parent_named:true,no_epilepsy_diagnosis:true,release_October_not_actual_move:true,health_assessment_dated_not_lifetime:true,recruit_exposures_same_sheet:true,Bokulla_recruitment_rote_not_home:true},['A-3038','A-3039','A-3062','A-3063','A-3064']);
const bf=fact(p,'birth_conflict','April-July',{accepted:'1822-04-09',opposing:'1822-07-09',opposing_source:'C-0793 kyrkoattest1840-12-15',supporting:['C-0798 födelsepost','C-0743 död/AI21','C-0752 GMR1851/55','rättade egna HFL'],old_HFL_July_transcriptions_rejected:true,no_silent_harmonization:true},['A-2894','A-3062',cs('C-0793'),cs('C-0798')],'CONFLICT');
const jr=src(p,'C-0793','Jernbol s. 121','Jernbol-rejected','Anders Petter[?]','',{alternative_name:'Carl[?] Petter[?]',birth_year_alternatives:['1821[?]','1817[?]'],birth_date:'9/8[?]',birthplace:'Halla',arrival:'1837 Läggesta[?]',departure:'38 fol.156',crossed:true},['A-3065'],'Avvisning av tidigare säkerkoppling, inte säker annan identitet. Ingen egenJernbolrad på justuppslaget.','rejected');p.changes.find(x=>x.id===jr[1]).evidenceStatus='REJECTED';
const mr=[];for(const[cid,filter,key,name,role,data,a]of[
 ['C-0763','1842, nr','GMR1842','Carl Fredr. Drill','Recruten',{muster:'1842-06-14',rote:'36Glippsta',county:'Södermanland',age:'20',service:'1 3/12',height:'5fot10tum',marital_status:'ogift',replacement:'1841-02-18',remark:'Recrut approberas'},'A-2966'],
 ['C-0763','1845, nr','GMR1845','Carl Fredric Drill','Soldat',{muster:'1845-07-07',rote:'36Glippsta',county:'Södermanland',age:'23',service:'4 5/12',height:'5fot10tum',marital_status:'gift'},'A-2969'],
 ['C-0752','1848, nr','GMR1848','Carl Fredric Drill','',{rote:'36/36Glippsta',county:'Sörmland',age:'26',service:'7 5/12',height:'5fot10tum',marital_status:'gift',marks:'pr.[?]'},'A-2935'],
 ['C-0752','1851, nr','GMR1851','Carl Fredric Drill','',{rote:'36/36Glippsta',age:'29 2/12[?]',service:'10 3/12[?]',height:'5fot10tum',marital_status:'gift',previous:'Förut Dräng[?] C. F. Pehrsson',birth:'Halla,Nyköpings län9april1822',admitted:'15februari1841'},'A-2936'],
 ['C-0752','1855, nr 36','GMR1855-old','Carl Fredric Grill','',{rote:'36Glippsta',crossed:true,transport:'Den25[?]Juli1851[?] transporterad till ...N:o38...',successor:'Lars Petter Landin'},'A-2937'],
 ['C-0752','1855, nr 38','GMR1855-new','Carl Fredric Grill','',{rote:'38/38Hagby iBettna',from:'nr36Glippsta',previous_name:'C. F. Pehrsson',birth:'Halla9april1822',admitted:'15februari1841',age_service_fractions:'bleka reserverade'},'A-4626']])mr.push(...src(p,cid,filter,key,name,role,data,[a]));
const mf=fact(p,'military_registration','transport-and-admission',{unit:'Livkompaniet,Södermanlandsregemente',from:'36Glippsta',to:'38Hagby',transport_positive:true,transport_date:'25[?]juli1851[?]',admission1841_02_15:true,older_GMR_replacement1841_02_18:true,dates_not_harmonized:true,Landin_admission1854_08_26_not_own_discharge:true,CarlJohanStrid_predecessor38_to61Malby:'25[?]juli1851[?]',own_discharge_date:null,earlier_eight_company_negatives_rejected:true,seven_other_companies_still_other_men:true},['A-2934','A-2936','A-2937','A-2966','A-2987','A-3038','A-4626',cs('C-0752'),cs('C-0771')],'CORROBORATED');
const move=src(p,'C-0763','Bettna B/1','arrival1841','Carl Fr. Drill','Soldaten',{date:'1841-11-11',from:'Björkvik',to:'Glippsta S.T.',men:1,no_accompanying_wife_children_in_own_row:true},['A-2967']);const me=ev(p,'registered_arrival',exact('1841-11-11'),['A-2967'],move[0],'E-arrival-P-0474-Glippsta1841','principal','Bokförd dag, inte säker fysisk resdag.');
const probate=src(p,'C-0760','','probate-index','Drill, Karl Fredrik','',{year:1895,title:'soldat',civil_status:'änkling',home:'Hässelstugan,Bettna',reference:'OppundaFII:69nr557'},['A-2960']);const pr=fact(p,'source_route','probate1895',{archive:'SE/ULA/11151/F II/69',period:'1894–1895',permanent_id:'kSN8qDX9rH6cxG02H087k3',act:557,only_analogue_in_tested_access:true,act_unread:true,heirs_and_assets_unknown:true},['A-2961',cs('C-0760')],'LEAD');
const sn={};sn.got=search(p,'Gotstugan337','S-0572','C-0739','Carl Fredrik Grill',{volume:'BettnaAI21a',period:'1891–1895',page:337,image:'C0005874_00166',headings:['Fiskartorp','Götstugan'],register_image:8},'Ingen målrad på just registerroutade sidan; inte hela volymen eller levnadsnoll.',['A-2878']);sn.death=search(p,'F3-deaths1883-1894','S-0565','C-0739','Carl Fredrik/Carl Fredric/Carl Eric Grill',{volume:'BettnaF3',period:'1883–1894',images:'F0002755_00011–00050;53omtag50;51–52ejposter'},'Samtliga sakliga död-/begravningsposter. Johannas positiva post och avvisadeCarlsson ingår; inget bredare dödsnoll.',['A-2879']);sn.move=search(p,'B5-moves1891-1894','S-0576','C-0743','Carl Fredrik/Carl Fredric/Carl Eric Grill',{volume:'BettnaB5',period:'1891–1894',images:'8–24,26',excluded:'25tom;27–28ingen sakpost'},'Samtliga sakliga in-/utflyttningar, endast angivna namnformer; ingetvistelse/levnadsbelägg.',['A-2895']);sn.bj=search(p,'Bjorkvik-departure1841','S-0592','C-0763','Carl Fredric Drill',{volume:'BjörkvikB1',year:1841,images:'C0005933_00106–00109'},'Kompletta utflyttningsföljden saknar uttrycklig reciprok post; positivaBettnaankaretbestår.',['A-2970']);sn.hag=search(p,'Hagby184','S-0601','C-0775','Carl/Carl Eric/Carl Fredric Grill/Drill; Johanna Jansdotter/Jonsdotter; sammanhållenGrillfamilj',{volume:'BettnaAI14b',period:'1856–1860',page:184,headings:['Kyrko-Roten','Hagby Sold. Torp'],image:'C0005861_00199',register:'Hagby12→D:oSoldattorp184'},'Fullsida utan målprofil, ingetHagby/helvolyms/vistelsenoll eller boställesidentitet.',['A-3005']);sn.reg=search(p,'Hagby-register','S-0616','C-0800','ort/fritext Hagby; socken Bettna',{register:'RiksarkivetIndelningsverket(Grill)',fields:{place:'Hagby',parish:'Bettna'}},'0träffar efter faktiskladdning, enbartexaktformfråga; positivHagby38består.',['A-3061']);
for(const[v,im]of[['AI13b','C0005910_00100'],['AI14b','C0005912_00106']])sn[v]=search(p,'Bokulla-'+v,'S-0610','C-0793','Carl Fredrik Drill eller kändmålprofil',{volume:'Björkvik'+v,page:90,place:'Bokulla',image:im},'Exaktsida utan säkermålrad, ingen bostads-/sockenfrånvaro.',['A-3040']);
for(const[v,page,im]of[['AI4',119,'C0006527_00133'],['AI5',3,'C0006528_00016']])sn[v]=search(p,'Halla-'+v,'S-0614','C-0798','Ella Ersdotter/Carl Fredrik via Lilla Linväfvarstugan',{volume:'Halla'+v,page,image:im,route:'Lilla Linväfvarstugan'},v==='AI4'?'Registermålsidan tom; inte sammaort bevisad somLillaWättstugan.':'Ingen säkermålrad på sidan; gamlaElla-nyckeln rättadUlla, ingen person/vistelsenolla.',['A-3068']);
const nav=fact(p,'source_assessment','bounded-navigation',{AI10a:{pages:[32,34],page33:'tom'},B4_OCR_navigation_not_negative:true,SCB1890_old_ALTCHA_superseded_by_C0750:true,anonymous_max:{B5:'fungerade',F4:'401',AI21a27:'403'},image_viewers_worked:true,Hagby_old_ALTCHA_attempts_not_negative:true,C0800_exactform_now_zero:true,AI14ab_OCR_not_negative:true,AI15b180_other_Werner_household_only:true},['A-2880','A-2881','A-2968','A-3006','A-3037',cs('C-0739'),cs('C-0743'),cs('C-0749'),cs('C-0800')]);
const provenance=fact(p,'source_assessment','preservation-debt',{SCB1880_1890_missing_old_read_images:44,positive_images_preserved:['1880:859/860','1890:146'],all412linked_packagefiles_exist:true,other_exact_missing:['C0005877_00028','C0005858_00179'],S0583_nomination_roster_unresolved:true,S0559_37hits_not37unique_images:true,PK11_not_identity_rejection:true},[origins(p.person,'profile',1,173)]);
const birthOther=src(p,'C-0725','utflyttade1839','CarlEric-candidate','Carl Eric Carlsson','Drängen',{year:1839,from:'Ellesta',to:'Björnlunda'},['A-2894'],'Namnnäraledtråd utan identitetsbrygga.','candidate');const bo=src(p,'C-0725','bild189','Eric-rejected','Eric Carlsson','Dräng',{birth:'1820-08-10'},['A-2894'],'Avvisad som datumangivna kandidaten, intehelvolymsnoll.','rejected');p.changes.find(x=>x.id===bo[1]).evidenceStatus='REJECTED';const navold=fact(p,'source_assessment','old-origin-searches',{HallaC2_full1822negative_rejected:true,July9_exactname_negative_only:true,HallaB1_1836_1842:'Grill ejfunnen, CarlEricCarlsson1839kandidat',Ellesta37_40:'ingenmotsvarandehushållsrad',BjornlundaAI11_382images:'OCR+nominerade visuella; ejhelvolymsnoll',positive_birth_overrides_old_negative:true},['A-2894',cs('C-0725')]);
const ownFather=src(p,'C-0147','','Erik-father','Carl Er. Grill','Soldaten',{child:'Erik efter överstruketGustafOscar',born:'1851-01-30',baptised:'1851-02-02',mother:'Joh. Jonsdr',mother_age:31,home:'Glippsta soldattorp'},['A-2837'],'Denna C0147s senasteT0132råform Er. bevaras; rättelser tillFr.iandraR överförs inte hit.');
const amap={2837:[relation(p,p.person,'P-0133','parent',['A-2837']),...hs,...ownFather],2844:hs,2845:[...hs,hh],2846:[...reg,rplace],2847:reject,2878:[sn.got],2879:[sn.death],2880:[nav,sn.move,...death],2881:[nav],2893:[...dr,...hr,...death,...burial,limits],2894:[bf,...b,...hr,...att,...birthOther,...bo,navold],2895:[sn.move],2922:[...hs,idx],2925:[...s90,idx],2926:[...late,rplace],2934:[mf],2935:mr,2936:[...mr,mf],2937:[...mr,mf],2960:probate,2961:[pr],2966:[...mr,mf],2967:[...move,...me],2968:[nav],2969:[...mr,...common],2970:[sn.bj],2987:[mf],2988:[...hs,...common],3005:[sn.hag],3006:[nav],3037:[nav],3038:[...rec,mf,ac],3039:[...att,ac],3040:[sn.AI13b,sn.AI14b,ac],3061:[sn.reg,mf],3062:[...att,bf,ac],3063:[...att,ac],3064:[...att,ac],3065:jr,3066:[...b,...birth,...bap,bp,mother,father,...bws],3068:[sn.AI4,sn.AI5,bp],4626:[...mr,mf]};for(const[k,t]of Object.entries(amap))assertion(p,'A-'+k,[...new Set(t)],'Individuellt mappad sakuppgift med senaste rättelser, källgränser och osäkerhet i angivna objekt.');
relationRow(p,'P-0500',[mother,father],'Moderns relation består; senasteUlla rättaräldreElla.');relationRow(p,'Okänd man',[father],'Ingen nyfarperson eller patronymikoninferens.');relationRow(p,'P-0475',[sp,...common],'Korreleratpar, faktiskvigsel okänd.');relationRow(p,'Anders Fredric',[af],'Egen sonrad utan nyttP ellerbiologiskutvidgning.');relationRow(p,'Yngre Hedda',[hh,...younger,youngerDeath],'Separat yngre barnrad, sannoliktbarnbarn.');
for(const child of ['0494','0495','0496','0133','0497','0498','0499']){if(child==='0494'){const f=fact(p,'family_context','Carl-Johan',{child:'P-0494',mother:'P-0475',household_son:true,biological_father_unknown:true,later_marriage_not_fatherproof:true},os(p,'Relationer'));relationRow(p,'P-'+child,[f],'Hushållsson, inte accepteradbiologiskfader.');}else relationRow(p,'P-'+child,[relation(p,p.person,'P-'+child,'parent',os(p,'Relationer'))],'Uttrycklig familjerelation, ingen obestämd biologisk art eller överföring av senareliv.');}
const network=fact(p,'social_network','child-witnesses-and-attesters',{child_baptisms:{P0494:[['Jonas Andersson','H.[?]','Agnatorp[?] räckviddreserverad'],['Maja St. Gustafsdotter[?]','hustru',''],['Cajsa Greta Ersdotter','piga','Agnatorp[?]'],['Petter Ersson','dräng','Skresta[?]']],P0495:[['Nils Thor','soldat','Skrella[?]soldattorp'],['Ann. St. Jansdotter[?]','hustru','samma'],['Carl Otto Nilsson','son','Skrädd...stugan[?]'],['Ann. M. Söderberg','piga','Knuf...n[?]']],P0499:[['August Werner','dräng','Kofhult[?]'],['Eva Lotta Olsdotter','hustru',''],['Carl Joh. Jansson','dräng','Hagby[?]'],['Gustafva Olsdotter','piga','Sjöstugan']]},attesters:[['Anders Andersson','tjänste-/tillståndsgivare','Jernbol; bomärke'],['Jacob Jacobsson','tjänsteintygsvittne','Jacobstug[?]'],['Jan Jansson','tjänsteintygsvittne','Hålstugan[?],StoraMalm'],['[initialer?] Rendgren[?]','vicepastor','Björkvik'],['C. W. Martin[?]','provinsialläkare','Nyköping']],military:[['Lars Petter Landin','efterträdare36;inteegen son'],['Carl Johan Strid','föregångare38']],kinship_not_inferred:true},[section(p,'Relationer'),cs('C-0763'),cs('C-0794'),cs('C-0793'),cs('C-0752')]);
for(const name of ['Nils Thor','Ann. St. Jansdotter','Carl Otto Nilsson','Ann. M. Söderberg','August Werner','Eva Lotta Olsdotter','Carl Joh. Jansson','Gustafva Olsdotter','Anders Andersson','Jacob Jacobsson','Jan Jansson','Rendgren','C. W. Martin','Lars Petter Landin','Carl Johan Strid','Jonas Andersson','Maja St. Gustafsdotter','Cajsa Greta Ersdotter','Petter Ersson'])relationRow(p,name,[network],'Namngiven roll med rätt barn/intyg/rote, ortreservation och utan släktinferens.');
for(const[c,keys]of[['0494',['JonasAndersson','MajaStGustafsdotter','CajsaGretaErsdotter','PetterErsson']],['0495',['NilsThor','AnnStJansdotter','CarlOttoNilsson','AnnMSoderberg']],['0499',['AugustWerner','EvaLottaOlsdotter','CarlJohJansson','GustafvaOlsdotter']]])for(const k of keys)reuse(p,`EP-E-baptism-P-${c}-${k}-witness`,os(p,'Relationer'));
p.pending.push({origin:'A-2894',question:'April/juli mellan födelseoriginalet och kyrkoattesten består; äldreHFLjuli/Jernbolkoppling avvisade.'},{origin:section(p,'Militärt, civilt och rättsligt'),question:'Ingen vigselpost; C0718/0763T0202 kallar mönstringsdag1845-07-07giftdatum och föreslår27mån dröjsmål utan sådan dateringsgrund.'},{origin:'A-3066',question:'ModernUlla rättaräldreElla; ab sannoliktabsolverad men inget dateratärende/fadersnamn. Följdväg oläst.'});save(p);
}
