import pathlib,json,hashlib,time,datetime,shutil
R=pathlib.Path.cwd();D=R/'evaluations/T-0809';I=D/'implementation';S=I/'stage473-sequence-v1';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();axes=json.load(open(S/'final-axis-differences-and-nine-relation-proof.json'));assert axes['persons']==536;assert [x['person']for x in axes['all_person_axis_differences']]==['P-0009'];assert axes['all_nine_relation_native_exact'];result=json.load(open(S/'result.json'));assert result['state']=={'journal_head':473,'pending':0};readers=json.load(open(S/'reader-capture-result.json'));first=json.load(open(I/'stage472-v1/failure-preserved.json'));accepted=json.load(open(I/'stage472-v2/initial-result.json'));controls=[]
for pid,oldfile in [('P-0269','root-after-4-v1.json'),('P-0270','root-after-5-v1.json')]:
 b=json.load(open(R/'evaluations/T-0808'/oldfile));a=json.load(open(S/(pid+'-pedigree.json')));key=lambda p:json.dumps(p,sort_keys=True);bs={key(p) for p in b['paths']};as_={key(p) for p in a['paths']};assert bs<=as_;added=[p for p in a['paths']if key(p)not in bs];assert len(b['paths'])==34 and len(a['paths'])==35 and [x['person']for x in added]==['P-0009'];controls.append({'root':pid,'baseline_paths':34,'final_paths':35,'all_old_paths_retained':True,'exact_added_paths':added})
for f in ['verify.json','verify-assets.json']:
 x=json.load(open(S/f));assert x['ok']and not x['errors']
qualified={'state':result['state'],'changed_current_native_objects':87,'individual_dependency_resolutions':96,'retains_initial':200,'retains_dependency':92,'six_original_media':6,'all_nonderived_old_rows_and_five_native_array_orders_exact':True,'total_persons':536,'protected_nonfocal_axes':535,'all_nonfocal_identity_tree_life_and_stop_reasons_exact':True,'focal_identity':'passed/usable','focal_tree':'supporting/usable','focal_legacy_full_contract':{'outcome':'failed','usable':True,'source':'legacy_header','scope':'legacy_full_contract','explicit_backing_revision_change':'ASSESSMENT-P-0009@1→@2','new_native_LIFE_created':False},'all_nine_relation_native_metadata_order_exact':True,'pedigree_controls':controls,'native_and_asset_validators_pass':True,'main_baseline_unchanged':sha(R/'genealogy2/data/research.sqlite')==json.load(open(D/'preparation/baseline-state-v1.json'))['main']['sha256'],'attempts_preserved':['stage472-v1 transactional missing reading_note rejected/all50 rollback','stage472-v2 accepted initial96 dependencies','fresh471→472→473 exact sequential final clone'],'elapsed_seconds':{'rejected_apply_and_check':first['elapsed_seconds'],'accepted_initial_apply_and_check':accepted['elapsed_seconds'],'fresh_two_operation_sequence':result['elapsed_seconds'],'final_readers':readers['elapsed_seconds']},'model_usage':'unknown; root collects actual per-role new-turn usage after final responses','canonical_apply':'Root only, not performed by worker'};assert qualified['main_baseline_unchanged'];(S/'qualified-final-result-v1.json').write_text(json.dumps(qualified,ensure_ascii=False,indent=2)+'\n')
N=D/'preparation/normative-snapshots-final-v1';assert not N.exists();N.mkdir();norms=['AGENTS.md','wotan/README.md','wotan/dev-log/T-0809.md','wotan/dev-log/T-0237.md','genealogy2/README.md','genealogy2/docs/working.md','docs/research/person-contract.md','docs/research/source-strategy.md','docs/research/riksarkivet-access.md'];snap=[]
for p in norms:
 dst=N/(p.replace('/','__'));shutil.copyfile(R/p,dst);snap.append({'source_path':p,'snapshot_path':str(dst.relative_to(R)),'sha256':sha(dst),'qualification':'Snapshot of instructions/current adopted scope before root-only final task-status amendment; live Wotan task closure is not a model mutation.'})
(N/'snapshot-index.json').write_text(json.dumps(snap,ensure_ascii=False,indent=2)+'\n');paths=[p for p in D.rglob('*')if p.is_file()and '__pycache__'not in p.parts and p.suffix not in ['.pyc'] and 'final-source-gate'not in p.name and p.name!='final-manifest-v1.json'];paths += list((R/'genealogy2/journal').glob('*.json'));paths +=[R/u['staging_receipt']['storagePath'] for u in json.load(open(D/'preparation/six-actual-media-input-lock-v1.json'))['units']];paths +=[R/'evaluations/T-0808'/p for p in ['actual-main-stage-comparison-v1.json','root-after-3-v1.json','root-after-4-v1.json','root-after-5-v1.json']];paths +=[R/'evaluations/T-0808/implementation/stage471-sequence-v1/inventory-full.json',R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py'];paths=sorted(set(paths));files=[{'path':str(p.relative_to(R)),'sha256':sha(p)}for p in paths];manifest={'task':'T-0809','baseline_state':{'journal_head':471,'pending':0},'baseline_main_sha256':json.load(open(D/'preparation/baseline-state-v1.json'))['main']['sha256'],'final_state':result['state'],'stage_database':{'path':str((S/'stage.sqlite').relative_to(R)),'sha256':sha(S/'stage.sqlite')},'operations':[{'path':str((I/p).relative_to(R)),'sha256':sha(I/p)}for p in ['operation-v2.json','repair-operation-v1.json']],'consequence_tables':[{'path':str((I/p).relative_to(R)),'sha256':sha(I/p)}for p in ['consequence-table-v2.json','repair-consequence-table-v1.json']],'qualified_result':{'path':str((S/'qualified-final-result-v1.json').relative_to(R)),'sha256':sha(S/'qualified-final-result-v1.json')},'file_count':len(files),'files':files,'canonicalApproval':False};p=D/'final-manifest-v1.json';assert not p.exists();p.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');print(sha(p));print('pins',len(files),'DB',sha(S/'stage.sqlite'))
