import pathlib,json,hashlib,sqlite3,datetime
B=pathlib.Path(__file__).resolve().parent;F=B/'final-review';F.mkdir(exist_ok=True)
def h(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def artifact(n):p=B/n;return {'path':str(p),'sha256':h(p)}
ops=['C-0026-candidate-operation-v2.json','C-0026-resolution-operation-v2.json','C-0027-candidate-operation-v2.json','C-0027-resolution-operation-v2.json','C-0035-candidate-operation-v1.json','C-0035-text-amendment-operation-v2.json','C-0035-resolution-operation-v2.json','independent-copy-amendment-operation-v1.json','independent-copy-amendment-operation-v2.json','independent-copy-amendment-operation-v3.json','independent-copy-amendment-operation-v4.json']
allchanges=[x for n in ops for x in json.loads((B/n).read_text()).get('changes',[])];ids={x['id'] for x in allchanges};newids={x['id'] for x in allchanges if x['expectedVersion'] is None};res=sum(len(json.loads((B/n).read_text()).get('resolve',[])) for n in ops)
source=[]
for cid in ['C-0026','C-0027','C-0035']:
 source.extend(artifact('source-decisions/'+cid+'-'+s+'.json') for s in ['source','decisions','dispositions'])
checks=['final-clone-full-object-match-v2.json','final-clone-verify-v2.json','final-clone-verify-assets-v2.json','final-clone-verify-source-v2.json','final-protected-invariants.json'];assert json.loads((B/checks[0]).read_text())['all_pass'];assert not json.loads((B/checks[0]).read_text())['pending'];assert json.loads((B/checks[-1]).read_text())['post_journal']==248
for n in checks[1:4]:assert json.loads((B/n).read_text())['exit_code']==0
src=B/'clone/research-candidate-v2.sqlite';dst=F/'candidate-frozen-v1.sqlite';assert not dst.exists();a=sqlite3.connect('file:'+str(src)+'?mode=ro',uri=True);o=sqlite3.connect(dst);a.backup(o);o.close();a.close();c=sqlite3.connect('file:'+str(dst)+'?mode=ro',uri=True);head=c.execute('select max(sequence) from operation_payload').fetchone()[0];assert head==248;c.close()
coverage=['selection-before-receipt-augmentation.json','pre-source-lock-v1.json','rubric-v1.md','current-manifest.json','cards-routing-sidecar.json','current-baseline-capture-hashes.json','semantic-copy-search-input.json','C-0035-P0045-current-sidecar.json','C-0035-P0045-surname-name-candidates.json','C-0027-support-rebinding-astra-sidecar.json','C-0035-independent-research-precision-sidecar.json']
coverage.extend(p.relative_to(B).as_posix() for p in sorted((F/'old-followup-captures').glob('*.json')))
freeze={'schema':'T0775-candidate-freeze/1','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'state':'FROZEN_AFTER_EXPLICIT_INDEPENDENT_CORRECTIONS_AWAITING_HASH_BOUND_FINAL_PASS','sources':source,'selected':['C-0026','C-0027','C-0035'],'baseline_journal':237,'candidate_journal':head,'candidate_database':artifact(str(dst.relative_to(B))),'operations_in_exact_apply_order':[artifact(n) for n in ops],'checks':[artifact(n) for n in checks],'coverage_and_search_inputs':[artifact(n) for n in coverage],'counts':{'unique_current_objects':len(ids),'new_objects':len(newids),'revised_preexisting_objects':len(ids-newids),'change_events':len(allchanges),'individual_resolutions':res,'pending':0},'history':{'initial_joint_candidate':'85unique objects PASS technically; independent review found missed current copies before acceptance.','preserved':'Initial C26v1, C27failedv1, C35initialv1 and subsequent correction operations/logs retained.','independent_added_work':'1RESEARCH precision plus14copy/metadata corrections; no new citation scope or identity/gate.'},'canonical_applied':False,'norm':'Original+old canonical+contract; model agreement alone is not correctness.'}
(F/'candidate-freeze-v1.json').write_text(json.dumps(freeze,indent=2)+'\n');print(freeze['counts'],freeze['candidate_database'])
