import fs from 'node:fs';import os from 'node:os';import path from 'node:path';
import {openDB,importBaseline,exportData} from '../../../../genealogy2/lib/store.mjs';
import {applyOperation} from '../../../../genealogy2/lib/domain.mjs';
import {snapshot,sha} from '../../../../genealogy2/lib/archive.mjs';
const here=path.dirname(new URL(import.meta.url).pathname),pub=path.join(here,'../public');
const dir=fs.mkdtempSync(path.join(os.tmpdir(),'z-prepare-'));
fs.mkdirSync(path.join(dir,'genealogy'),{recursive:true});fs.writeFileSync(path.join(dir,'genealogy/README.md'),'# Syntetiskt underlag\n\nRättelseprov. Inga verkliga personer.\n');
await snapshot(dir,path.join(dir,'baseline'));const db=openDB(path.join(dir,'fixture.sqlite'),{create:true});importBaseline(db,path.join(dir,'baseline'));
const doc=db.prepare('SELECT * FROM document ORDER BY path LIMIT 1').get();
const unit=sha(`${doc.path}\0${doc.sha256}\0curated_span\0${0}\0${doc.bytes}`);
const spans=[{id:unit,path:doc.path,sha256:doc.sha256,start:0,end:doc.bytes}];
const origins=[{unit,coverage:'complete',note:'Syntetisk proveniens som ska bevaras.'}];
const evidence=(object,version=1)=>[{object,version,role:'supports'}];
const c=(id,kind,data,extra={})=>({id,kind,data,expectedVersion:null,disposition:'recorded',rationale:'Syntetiskt startläge',origins,...extra});
const media=(name,bytes)=>({id:'MED-'+name,sha256:sha(bytes),storagePath:'genealogy2/media/objects/'+sha(bytes),bytes:Buffer.byteLength(bytes),originalName:name+'.txt',provenance:'Syntetiskt medieinnehåll för test; ingen arkivbild.'});
const old=media('old','old-image'),fresh=media('full','full-image');
const changes=[c('S-A','source',{title:'Provförsammlingen',description:'Syntetisk källa A'}),c('S-B','source',{title:'Provförsamlingen B',description:'Syntetisk källa B'}),c('P-A','person',{display_name:'Testperson A'}),c('R-B','record',{source_id:'S-B',record_type:'departure',locator:'folio 20',dependence_note:'Samma registreringskedja som observationen.'},{media:[{id:old.id,region:'utsnitt'}],evidence:evidence('S-B')}),c('O-B','observation',{record_id:'R-B',mention_id:null,property:'departure_date',value_literal:'22/10 1930',value_json:{precision:'exact',value:'1930-10-22'}},{evidence:evidence('R-B')}),c('F-B','fact',{subject_id:'P-A',property:'departure_date',value_type:'date',value_json:{precision:'exact',value:'1930-10-22',literal:'22/10 1930'}},{evidence:evidence('O-B'),evidenceStatus:'TRANSCRIBED',caveat:'Registrerad utflyttning, inte bevis för faktisk resdag.'}),c('F-OWNER','fact',{subject_id:'P-A',property:'residence',value_type:'text',value_json:'Testbyn'},{evidenceStatus:'OWNER_CONFIRMED',evidence:evidence('S-B'),rationale:'Ägaren har bekräftat bostadsorten.'})];
applyOperation(db,{id:'fixture-seed',actor:'fixture',reason:'Syntetiskt startläge',media:[old],spans,changes});
const record={...changes[3],expectedVersion:1,data:{...changes[3].data,locator:'folio 20, rad 3'}};
applyOperation(db,{id:'fixture-record-correction',actor:'fixture',reason:'Tidigare metadataändring; individuella följdprövningar väntar.',dependencyReviewVersion:2,changes:[record]});
const current=changes.map(x=>x.id==='R-B'?{...record,expectedVersion:2}:{...x,expectedVersion:1});
const pending=db.prepare('SELECT * FROM pending_review ORDER BY affected_revision_id').all();
fs.writeFileSync(path.join(here,'fixture.json'),JSON.stringify(exportData(db),null,2));
fs.writeFileSync(path.join(here,'media-content.json'),JSON.stringify({[old.storagePath]:'old-image',[fresh.storagePath]:'full-image'},null,2));
const input={format:'T-0769-Z-input/1',currentChanges:current,pendingReviews:pending,newMedia:fresh,decision:{simple:'Rätta endast S-A.title till Provförsamlingen.',complex:'R-B.locator ska bli folio 20, rad 3, utflyttning nr 17. Lägg till nytt helbildsmedium med region helbild och behåll utsnittet. O-B och F-B ska ange 1930-10-23, rådatum 23/10 1930. Bevara alla andra uppgifter och F-B-förbehållet. Pröva och stäng båda väntande följdprövningarna individuellt eftersom respektive sakuppgift nu rättas. F-OWNER och personkärnan får inte ändras.'}};
fs.writeFileSync(path.join(pub,'input.json'),JSON.stringify(input,null,2));
const get=id=>structuredClone(current.find(x=>x.id===id));
const s=get('S-A');s.data.title='Provförsamlingen';
const r=get('R-B');r.data.locator='folio 20, rad 3, utflyttning nr 17';r.media.push({id:fresh.id,region:'helbild'});
const o=get('O-B');o.data.value_literal='23/10 1930';o.data.value_json.value='1930-10-23';o.evidence=evidence('R-B',3);
const f=get('F-B');f.data.value_json.value='1930-10-23';f.data.value_json.literal='23/10 1930';f.evidence=evidence('O-B',2);
for(const x of [s,r,o,f])x.rationale='T-0769: fastställt sakbeslut, versionsbunden rättelse och bevarad proveniens.';
const answer={id:'T-0769-Z-answer',actor:'benchmark',reason:'T-0769: rättad titel och fullständig datumrättelse.',dependencyReviewVersion:2,media:[fresh],changes:[s,r,o,f],resolve:pending.map(q=>({request:q.id,rationale:q.affected_revision_id==='O-B@1'?'O-B har rättats till 23/10 1930 och bundits till R-B@3.':'F-B har rättats till 23/10 1930 och bundits till O-B@2; förbehållet om registrerad utflyttning kvarstår.'}))};
fs.writeFileSync(path.join(here,'reference.json'),JSON.stringify(answer,null,2));db.close();fs.rmSync(dir,{recursive:true,force:true});
