import fs from 'node:fs';
import {person,core,full,cs,src,fact,assertion,relationRow,relation,reuse,use,event,participation,search,section,ev,exact,units,db,known,add,origins} from './part-a-utils.mjs';
import {readCurrent} from '../../lib/domain.mjs';
// Independently curated supplemental packet; root merges it into d only after review.
// Shared helpers deliberately do not discover this file, so new cross-person links
// are tracked within this generator and represented only once.
const output=[],created=new Set(),R932='R-86e25c6dd1c2141e8454c02e';
const link=(p,a,b,type,os,nature='recorded_'+type)=>{const ends=type==='parent'?[a,b]:[a,b].sort(),id=`REL-${type}-${ends[0]}-${ends[1]}`;if(created.has(id))return reuse(p,id,os);const out=relation(p,a,b,type,os,nature);created.add(out);return out;};
const finish=p=>{const own=new Map(units(p.person,'person').filter(u=>u.kind==='assertion'&&!u.historical).map(u=>[u.legacy_id,u.id]));for(const m of [...p.changes,...p.reuse])m.origins=m.origins.map(o=>typeof o==='string'&&own.has(o)?own.get(o):o);output.push(p);};
const own=(p,cid,filter,key,name,role,value,os,caveat='',r=null)=>src(p,cid,filter,key,name,role,value,os,caveat,'accepted',r);
const factEv=(p,prop,key,value,os,bases,status='TRANSCRIBED',caveat='')=>ev(p,fact(p,prop,key,value,os,status,caveat),bases);
{
 const p=person('P-0532','Hela akt/profil och C0952/0954/0955/0972/0973/0976 med samtliga rättelser, C0919 och det gemensamma C0033-uppslaget lästa. Native vigsel, änka, familjeobjekt och hela ärvda frågor/bedömning granskade. Säker vuxen make är skild från olöst födelse1878/1881/1887. Fem folier är en överföringskedja; lysningsmånad och betygssubjekt är reserverade. Ingen ny bild eller födelseläsning.');const os=full(p);
 core(p,['A-3650','A-3641',cs('C-0976'),cs('C-0972'),cs('C-0952'),cs('C-0955')],'CORROBORATED gäller individuellt sammanhållen vuxenidentitet: vigselns namn/yrke/maka, rotens samma familj och dödsdag mot namngiven änkenotis. Ingen oberoenderäkning, inget löst födelseår, inga egna föräldrar eller höjt kontraktsutfall.',null,'CORROBORATED');
 const deathOld=use(p,'O-P-0016-husband-death-fields',['A-3578'],{record_id:'R-cbf2e0de37426fcfca82cd15'});
 const death=own(p,'C-0952','','C0952-own','Axel Vilhelm Ekholm','lokomotiveldare',{death_literal:'Mars 11',year:1913,birth_literal:'78 ¹⁷/₂',registered_parish_literal:'fr. Katarina förs. i Stockholm',counted_in_parish_literal:'–',married_column:'1',reference_column:'—',cause_literal:'Lungsot',death_place_literal:'Helgesta',burial_literal:'Mars 17',note_literal:'F. m. f. 77. Attest om begrafn. d. Helgesta ¹⁷/₃ 13'},['A-3578'],'Första förkortningen olöst. Katarina är kyrkobokföring, inte födelse-, döds- eller vigselort. 35år är senare beräkning, inte avläst råålder.');
 const de=event(p,'death',exact('1913-03-11'),['A-3578',cs('C-0952')],'Dödsort Helgesta; notisen är införd i Hyltinge F/1.');ev(p,de[0],[death[2]]);
 const bu=event(p,'burial',exact('1913-03-17'),['A-3578',cs('C-0952')],'Helgesta enligt begravningsattest; egen gravplats okänd.');ev(p,bu[0],[death[2]]);
 const health=factEv(p,'death_context','Helgesta',{death:'1913-03-11',death_place:'Helgesta',burial:'1913-03-17',burial_place:'Helgesta',recording_parish:'Hyltinge',registered_parish:'Katarina, Stockholm',cause_literal:'Lungsot',reported_age_calculated:35,age_conditional_on_reported1878_birth:true,why_in_Helgesta_unknown:true,no_care_or_relatives_proven:true,own_grave_probate_unread:true},['A-3578',cs('C-0952')],[death[2]]);
 const orig=own(p,'C-0954','mantalsutdrag','C0954-original','Ekholm, Axel Vilhelm','Lokomotiveld.',{birth_year_literal:'81',birth_place_literal:'Åsbo Östergötl.',entry:2123,family:1,year:1910,place:'Kungsholm rote23, Kettingen36/37'},['A-3584'],'Originalbladets81 hålls skilt från register1887.');
 const idx=own(p,'C-0954','Folk_126426614','C0954-index','Ekholm, Axel Wilhelm','Lokomotiveldare',{birth_year:1887,birth_place:'Åsbo, Östergötlands län',family:1},['A-3584'],'Registerhushållets mansuppgifter; ingen egen födelsepost.');
 const oldBirth=[use(p,'O-P-0016-husband-birth1910-original',['A-3584'],{record_id:'R-8dbc2cebc0b43d681dbd941d'}),use(p,'O-P-0016-husband-birth1910-index',['A-3584'],{record_id:'R-57d0fb4d38de5d9ddf259ef0'}),use(p,'F-P-0016-research_key-husband1878',['A-3595'])];
 const rote23=own(p,'C-0955','203040290210','C0955-rote23','Axel Wilhelm Ekholm','Lok eldare',{birth_reported:'1878-02-17',birth_parish:'Åsbo, Östergötlands län',status_literal:'Gift, Sammanboende med barn',streets_literal:['Fridhemsgatan,54 56','Fridhemsgatan,24'],properties_literal:['Kettingen,3','Kettingen,36 37','Trossen,4 5'],littera:'D 2',parish:'Kungsholmen (även S:t Göran)',rote:23,volume:20304,book_period:'1904–1926',page_row:'029-21',arrival:'1910-10-07',from_rote:'27',departure:'1911-09-27',to_rote:'04',military_literal:'264-124-1899',floor_literal:'Hyr'},['A-3594','A-4751'],'Adresserna är häftets fält, inte daterade separata lägenheter; bokperioden är inte egen vistelse.');
 const rote14=own(p,'C-0955','149320360160','C0955-rote14','Axel Wilhelm Ekholm','Lokeldare',{birth_reported:'1878-02-17',birth_parish:'Åsbo, Östergötlands län',status_literal:'Gift, Inneboende med familj',streets_literal:['Kocksgatan,42','Nytorgsgatan,30'],property_literal:'Oron,8',littera:'C 20',parish:'Katarina',rote:14,volume:14932,book_period:'1910–1917',page_row:'036-16',arrival:'1912-12-23',from_rote:'10',closed:'1913-03-11',closure_reason_literal:'Död',household_head_literal:'Göth',church_registration_year:1912,military_literal:'264-124-99',note_literal:'Betyget Felutskr från Rote 4 Ti Ll Rote 10'},['A-3594','A-4751'],'Död är registeravslut, ingen utflyttning1913-03-11. Göth är hushållsföreståndare, inte belagd släkting.');
 const bans=own(p,'C-0976','E I/17','C0976-banns','Axel Wilhelm Ekholm','Lokomotiveldaren',{birth_place_literal:'Åsbo — Östergötlands län',birth_literal:'1878 ¹⁷/₂',arrival_literal:'⁷/₁ 97',parish_literal:'A.F.',knowledge_literal:'godkänd',military_literal:'Vpl. 264 ¹²⁴/₁₈₉₉',not_previously_married:true,home_literal:'Vestmg. 72',banns_days_literal:'5, 12, 19 — 03',marriage_reference:'03 N:o96'},['A-3650','A-3651','A-4752'],'Andra militära talet124eller128. Månad står inte utskriven enligt citationens eget förbehåll; betygsfältets subjekt är olöst och läggs inte som egen livshändelse.');
 const mar=own(p,'C-0976','E II/6','C0976-marriage','Ekholm, Axel Vilhelm','M.',{occupation_literal:'eldare',home_literal:'Vestmg. 72',birth_literal:'78 ¹⁷/₂',banns_reference:'86/03',following_column_literal:'1',date_literal:'Maj 1',year:1903,officiant_literal:'Heüman',officiant_reading_reserved:true},['A-3650'],'Västmannagatan72 är bostad; faktisk vigsellokal inte angiven.');
 const marriage=use(p,'E-P0016-marriage1903',['A-3650'],{event_type:'marriage',date_json:'{"literal":"1903-05-01","precision":"exact","value":"1903-05-01"}'}),mep=use(p,'EP-marriage-P-0532',['A-3650'],{event_id:'E-P0016-marriage1903',role:'spouse'}),spouse=use(p,'REL-P0016-P0532',['A-3650','A-3641'],{from_person:'P-0016',to_person:'P-0532',relation_type:'spouse'});
 const widow=use(p,'O-P-0016-widow-Flen',['A-3641'],{record_id:R932}),widowFact=use(p,'F-P-0016-civil_status-widow1913',['A-3641']);
 const wm=own(p,'C-0972','','C0972-late-spouse','Ax. Vilh. Ekholm','lok. eld.',{context_literal:'Änka efter lok. eld. Ax. Vilh. Ekholm',widow_date_literal:'13 ¹¹/₃',widow_row:1},['A-3641'],'Indirekt omnämnande på änkans rad, inte egen levande närvaro1933–1940.',R932);
 const late=[];for(const [key,r,n,role,note]of[
 ['744','R-ab847c1960d02f28801419b3','Ax. Vilhelm Ekholm','lok.eld.','Änk. eft. lok.eld. Ax. Vilhelm Ekholm'],
 ['736','R-ae4ef4e5d88c29871432433d','Ax. Vilh. Ekholm','Lokeldaren','Änka eft. Lokeldaren Ax. Vilh. Ekholm'],
 ['497','R-f39c0fec6478a29ae3e60fb7','Ax. Vilh. Ekholm','lokeld.','Änka eft. lokeld. Ax. Vilh. Ekholm'],
 ['83','R-389c0ed0f64fa269f41b91cd','Ax. Vilh. Ekholm','lokeld.','änka efter lokeld. Ax. Vilh. Ekholm']])late.push(...own(p,'C-0973','',`C0973-late-spouse-${key}`,n,role,{widow_folio:key,note_literal:note,widow_date_reported:'1913-03-11'},['A-3641'],'Makens indirekta namn i samma överföringskedja; bokperioden är änkans, inte hans livstid.',r));
 const bc=factEv(p,'birth_assessment','three-years',{reported_date:'1878-02-17',reported_parish:'Åsbo, Östergötlands län',census_original_year:1881,census_index_year:1887,chosen_birth:null,work_key:'1878-02-17 Åsbo',other_search_years:[1881,1887],own_birth_record_unread:true,no_parents_known:true,registers_may_share_information_source:true,old_resolution_revoked:true,Katarina_not_birthplace:true},['A-3578','A-3584','A-3594','A-3595','A-3650',cs('C-0955')],[death[2],orig[2],idx[2],rote23[2],rote14[2],bans[2]],'CONFLICT');
 const be=event(p,'birth',{precision:'unknown',literal:'1878-02-17 enligt senare poster; 1881 på1910blad och1887 iindex; ingen uppgift vald'},['A-3578','A-3584','A-3595'],'Säker vuxenidentitet, olöst födelseår och oläst egen födelse.');ev(p,be[0],[bc]);
 const mil=factEv(p,'military_registration','civil-records',{rote_literals:['264-124-1899','264-124-99'],banns_literal:'Vpl. 264 ¹²⁴/₁₈₉₉',banns_second_number_alternatives:[124,128],first_number:264,last_number_1899_interpretation:'möjligt inskrivningsår, inte klarlagd systemnyckel',service_not_proven:true,not_professional_soldier:true},['A-3651','A-4751',cs('C-0976')],[bans[2],rote23[2],rote14[2]]);
 const res=factEv(p,'residence','reported-route',{arrival_Adolf_Fredrik:'1897-01-07',address1903:'Västmannagatan72',rote23:{arrival:'1910-10-07',from:'27',departure:'1911-09-27',to:'04'},rote14:{arrival:'1912-12-23',from:'10',closed_by_death:'1913-03-11'},unread_rote_posts:['27','04','10'],certificate_routing_literal:'Betyget Felutskr från Rote 4 Ti Ll Rote 10',Hyr_not_ownership_or_all_assets:true,inlodging_does_not_prove_economic_decline:true,child_Matteus_births_not_own_address:true,no_continuous_1897_1903_or_1903_1910_residence_proven:true},['A-3650','A-4751',cs('C-0955'),cs('C-0976')],[bans[2],rote23[2],rote14[2]]);
 const moves=[];for(const [key,kind,date,bas,detail]of[['AF1897','registered_arrival','1897-01-07',bans[2],'Kyrkobokförd inflyttning till Adolf Fredrik; inte sex års sammanhängande faktisk vistelse.'],['rote23','registered_arrival','1910-10-07',rote23[2],'Till rote23 från27.'],['rote04','registered_departure','1911-09-27',rote23[2],'Från rote23 till04; mottagarpost oläst.'],['rote14','registered_arrival','1912-12-23',rote14[2],'Till rote14 från10; mellanpost oläst.']]){const e=event(p,kind,exact(date),['A-4751','A-3650'],detail,null,'TRANSCRIBED',`E-${kind}-P-0532-${key}`);ev(p,e[0],[bas]);moves.push(...e);}
 const occ=factEv(p,'occupation','locomotive-fireman',{anchors:[{year:1903,literals:['Lokomotiveldaren','eldare']},{year:1910,literal:'Lokomotiveld.'},{period:'1910–1913',literal:'Lokeldare'}],employer_unknown:true,SJ_not_proven:true,continuous_ten_years_work_not_proven:true,own_education_only_knowledge_mark:'godkänd',no_school_degree_proven:true},['A-3578','A-3584','A-3594','A-3650','A-4752'],[mar[2],orig[2],rote23[2],rote14[2],bans[2]]);
 const chain=factEv(p,'source_assessment','widow-chain',{folios:[932,744,736,497,83],one_administrative_chain:true,independent_evidence_count_not_established:true,no_living_presence_in1933_1955:true,husband_named_directly_in_widow_notes:true,C0919_widow_field_reading:'13 ⁴/₃',other_widow_fields:'13 ¹¹/₃',reading_or_record_discrepancy_unresolved:true,own_death_reported:'1913-03-11',C0976_three_documents_same_registration_chain:true,missing_local_images:['C0973 four images','C0976 three images'],browser_hash_not_local_copy:true,contract_review_not_upgraded:true},['A-3641','A-3650',cs('C-0972'),cs('C-0973'),cs('C-0919')],[widow,wm[2],...late.filter(x=>x.startsWith('O-'))]);
 const bn=[];for(const day of ['05','12','19']){bn.push(use(p,`E-banns-P-0016-P-0532-1903-04-${day}`,['A-4752']),use(p,`EP-E-banns-P-0016-P-0532-1903-04-${day}-P-0532-subject`,['A-4752']));}
 const bannsLimit=factEv(p,'source_assessment','banns-month',{days:[5,12,19],year:1903,month_not_explicit:true,April_conditional_on_marriage_chronology:true,Sunday_pattern_alone_not_unique:true,July1903_also_matches_Sundays:true,chosen_raw_month:null,existing_exact_April_events_require_qualification:true},['A-4752',cs('C-0976')],[bans[2]],'CONFLICT');
 p.pending.push({origin:'A-4752',question:'C0976 skriver april i inledningen men anger uttryckligen att månaden inte står utskriven. Söndagar5/12/19 identifierar inte ensamt april (även juli1903). De tre befintliga E-banns-P-0016-P-0532-1903-04-05/12/19@1 har exakt april utan förbehåll. April stöds av vigsel1maj som kontext, inte säker råmånad; root prövar uttrycklig native precisering.'});
 const cert=factEv(p,'source_assessment','certificate1903',{literal:'Uttagit betyg ⁶/₅ 03',date_reported:'1903-05-06',five_days_after_marriage:true,person_column_unresolved:true,transcript_appears_mans_column:true,opposite_column_has_marriage_date:true,no_own_migration_inferred:true},['A-4752',cs('C-0976')],['R-C0976-banns86']);
 p.pending.push({origin:'A-4752',question:'Betyg6maj1903 står som mannens kolumn i tabellen men akt/profil reserverar subjektet eftersom vigseldatum står i motsatt kolumn; ingen säker egen betygs- eller flytthändelse innan kolumnbindningen prövats.'});
 const fam=fact(p,'family_context','spouse-children',{wife:'P-0016',marriage:'1903-05-01',sons:['P-0533'],daughters:['P-0534'],children_reported_births:{'P-0533':'1907-03-09','P-0534':'1910-02-05'},own_parents_siblings_unknown:true,Huldas1920_1921_daughters_not_his:true,Goth_not_proven_relative:true},['A-3584','A-3650',...os]);
 const ps=[];for(const child of ['P-0533','P-0534']){const l=link(p,'P-0532',child,'parent',['A-3584',cs('C-0954'),cs('C-0955')]);ev(p,l,[orig[2],rote23[2],rote14[2]]);ps.push(l);relationRow(p,child,[l,fam],'Barnroll i den identifierade familjen; födelsedatum ur senare roteregister, egen födelsepost oläst.');}
 relationRow(p,'P-0016',[spouse,marriage,mep,widow,widowFact,chain],'Native direkt äktenskap och änkans namngivna make återbrukas; inga fem oberoende röster.');
 assertion(p,'A-3578',[...death,deathOld,...de,...bu,health,bc,...be],'Död/begravning och rapporterad födelse med årskonflikt; orternas olika funktioner.');
 assertion(p,'A-3584',[...orig,...idx,...oldBirth,bc,fam,...ps],'Original1881, index1887 och familjen; inga undanröstade år.');
 assertion(p,'A-3594',[...rote23,...rote14,...moves,res,mil,occ,bc],'Samstämmig vuxenidentitet, råregisterfält med egna datum och upphörande Död.');
 assertion(p,'A-3595',[bc,...oldBirth,...be],'Arbetsnyckel1878 är inte avgjord födelse; senare rättelse överordnad den gamla upplösningen.');
 assertion(p,'A-3641',[widow,widowFact,...wm,...late,spouse,chain],'Namngiven avliden make i fem folier, en administrativ överföringskedja.');
 assertion(p,'A-3650',[...bans,...mar,marriage,mep,spouse,res,...moves,occ,bc],'Direkt vigsel1maj1903, tidigare ogift, egen inflyttning1897och bostad1903; inte obruten sexårig vistelse.');
 assertion(p,'A-3651',[mil,...bans,rote23[2],rote14[2]],'Samma första värnpliktstal, andra reserverat och tjänstgöring ej visad.');
 assertion(p,'A-4751',[...rote23,...rote14,res,mil,...moves],'Hela utvunna egna fälten, rote27/4/10 är läshänvisningar och luckor.');
 assertion(p,'A-4752',[...bans,occ,bannsLimit,...bn,cert],'Kunskapsord och lysningsdagar bevaras, månad och betygssubjekt kvalificeras.');
 p.pending.push({origin:section(p,'Biografisk sammanfattning'),question:'Biografins ekonomiska nedgång och obrutna tioåriga arbete/boende går längre än C0955/C0976: Hyr och inneboende är bokföringsord, yrket är daterade ankare; barnens Matteusuppgifter är inte egen adress. F-residence/occupation bevarar positiva fält och dessa gränser.'});
 finish(p);
}

for(const id of ['P-0533','P-0534']){
 const son=id==='P-0533',other=son?'P-0534':'P-0533',name=son?'Axel Ivar':'Ingrid Amalia',birth=son?'1907-03-09':'1910-02-05',a=son?'A-3585':'A-3586',b=son?'A-3596':'A-3597',ad=son?'A-3643':'A-3644',method=son?'A-7988':'A-7989';
 const p=person(id,'Hela akt/profil, fulla C0954/0955/0957/0972/0973/0919 inklusive rättelser och gemensamma C0033 lästa. Individuell familjekedja och vuxenrad motlästa; egen födelsepost saknas. Native moderns relationer, utflyttning och barnfält återbrukas. Samma fastighetsfolio är inte samma lägenhet. Sonuppgifter minimeras till tidigare år/ort; inga extra personkärnor. Normativ dopveckoinferens och kontinuitetsord kvalificeras.');const os=full(p);
 core(p,[a,b,ad,cs('C-0955'),cs('C-0973')],`CORROBORATED gäller individuellt ${name}s återkommande exakta födelsedatum, namngivna familj och vuxna egenrad. Glesa daterade ankare är inte obruten närvaro; egen födelse/dopnotis oläst. Befintlig GODKÄND identitetsgranskning och EJ BÄRANDE kvarstår, full nivå UNDERKÄND.`,null,'CORROBORATED');
 const c=own(p,'C-0954',son?'mantalsutdrag':'Folk_126426614','C0954-own',name,son?'s.':'',{birth_year:son?1907:1910,birth_place_literal:'Stockholm',family:1,household_surname:'Ekholm',own_surname_not_written:true},[a],'Egen namnrad saknar efternamn. Ingrids roll saknas i återgiven registerrad och fylls inte med redaktionellt dotter.');
 const ro=own(p,'C-0955',son?'149320360180':'149320360190','C0955-own',`${name} Ekholm`,son?'Son':'Dotter',{birth_reported:birth,birth_parish:'Matteus, Stockholms stad',status_literal:'Ogift, Barn inom äktenskapet',page_row:son?'036-18':'036-19',departure:'1913-09-12',destination:'Helgesta'},[b],'Egna datum ur roteregister, inte egen födelse/doppost; faderns inflyttningsdatum lånas inte till barnraden.');
 const hy=own(p,'C-0919','r13–16','C0919-own',name,son?'s.':'d.',{birth_literal:son?'07 ⁹/₃':'10 ⁵/₂',birth_place_literal:son?'S:t Matteus':'d:o',row:son?14:15},os,'Rättelsen lokaliserar egna raden i moderns hushåll; rad16är Maj, inte folio16. Ingen faktisk närvarodag hämtas från bokens1918–1927.');
 const bo=use(p,`O-P-0016-child-birth-${id}`,[b],{record_id:son?'R-f9a2b7cc4c1c0208b7d245bb':'R-1167e7918d6e192f5433555e'}),be=event(p,'birth',exact(birth),[b,cs('C-0955')],'Rapporterad exakt födelsedag ur senare roteregister; egen födelsenotis oläst, dopdag okänd.');ev(p,be[0],[ro[2]]);
 const bf=factEv(p,'birth_report','Matteus',{date:birth,reported_parish:'Matteus, Stockholm',own_birth_record_read:false,baptism_date_unknown:true,birth_parish_not_necessarily_baptism_parish:true},[b],[ro[2]]);
 const dep=use(p,'E-registered_departure-P-0016-Helgesta1913',[b],{event_type:'registered_departure'}),depEP=use(p,`EP-E-registered_departure-P-0016-Helgesta1913-${id}-migrant`,[b],{person_id:id,event_id:dep,role:'migrant'});
 const father=reuse(p,`REL-parent-P-0532-${id}`,[a,b], 'Samma fadersrelation skapad i P0532:s supplementalpacket; ingen dubbel kant.'),mother=use(p,`REL-parent-P-0016-${id}`,[a,b,ad],{from_person:'P-0016',to_person:id}),sibling=link(p,id,other,'sibling',[b,cs('C-0955')]),half=son?use(p,'REL-sibling-P-0007-P-0533',os):link(p,'P-0007',id,'sibling',[...os,cs('C-0919')],'maternal_sibling');
 const half17=use(p,`REL-sibling-P-0017-${id}`,os,{from_person:'P-0017',to_person:id});
 const fam=factEv(p,'family_context','birth-household',{father:'P-0532',mother:'P-0016',sibling:other,maternal_half_sisters:['P-0007','P-0017'],Maj_reported_birth:'1920-05-11',Maj_birth_place:'Hyltinge',Maj_status_literal:'d. u.ä.',Maj_note_literal:'Erkännande inför pastor',Maj_father:'P-0015',father_not_propagated_to_half_sisters:true,father_death:'1913-03-11',father_death_place:'Helgesta',death_not_Stockholm_from_timeline:true,own_parents_spouse_relation_source_report_not_DNA:true},[...os,cs('C-0919'),cs('C-0952')],[ro[2],hy[2],father,mother]);
 const names=fact(p,'name_form','recorded-and-search',{recorded:[name,`${name} Ekholm`,...(son?[]:['Johansson f. Ekholm, Ingrid Amalia','Johansson, Ingrid Amalia f. Ekholm'])],search_only:[`${name} Eckholm`,...(son?[]:['Ingrid Amalia Johansson'])],no_Eckholm_source_attestation:true,own1910_surname_not_written:true,...(!son?{Johansson_surname_explicit_in_C0973:true,canonical_reordered_full_form_not_literal:true}:{})},[...os,cs('C-0954'),cs('C-0973')]);
 const bornSearch=fact(p,'source_assessment','birth-search-bounds',{own_birth_search_performed:son,brothers_negative_only:true,Matteus1907_posts:'129–182',baptism_band:{from:'1907-03-15',to:'1907-04-11'},birth_band:{from:'1907-01-11',to:'1907-04-08'},early_dates_not_covered:['1907-03-09','1907-03-10','1907-03-11','1907-03-12','1907-03-13','1907-03-14'],five_dates_March10_to14_not_six:true,post_number_before129_inference_not_exhaustive_order_proof:true,no_statistical_normal_baptism_interval_proven:true,late_entries_and_other_parish_open:true,sister_has_no_negative_search:true,sister_correct_search_target:'Matteus1910, not Kungsholm',no_claim_post_found_outside_band:true},[method,cs('C-0957'),cs('C-0955')]);
 p.pending.push({origin:method,question:'C0957/A7988/A7989:s giltiga noll gäller bara nr129–182. Datumen10–14mars är fem dagar (9–14 är sex kalenderdagar). Orden mest sannolik/normal dopvecka saknar här redovisat jämförelseunderlag; den lästa dopföljden bevisar inte utan vidare varje tidigare posts läge. Gränsen bevaras, ingen dopdag eller sannolikhetsvärdering införs.'});
 const limits=fact(p,'life_scope','gaps-and-minimization',{dated_anchors_only:true,continuous_life_line_not_proven:true,own_death_health_records_unread:true,last_explicit_life_anchor:son?'1949-01-14':'1950-01-03',folio83_contains_own_row_but_no_exact_life_date:true,folio83_and_nb96_references_not_fixed_transfer_years:true,no1955_survival_from_book_period:true,same_property_folio_not_same_apartment:true,no_shared_economy_or_care_day_proven:true,child_name_and_exact_birth_date_omitted:true,no_new_private_information:true,own_personal_material_unknown:true,local_images0973_missing:true},[ad,...os,cs('C-0973')]);
 p.pending.push({origin:section(p,'Biografisk sammanfattning'),question:'Akt/profil kallar livslinjen sammanhängande och hela kedjan belagd, men C0955/C0972/C0973 har luckor mellan ankare och odaterade fortsättningshänvisningar. Endast dokumenterade orter/datum förs som egna händelser; samma folio ger inte gemensam lägenhet eller omsorgsdag.'});
 let adult,adultObs,early=[],adultEvents=[],adultFamily,marriage;
 if(son){
  const s=own(p,'C-0972','','C0972-own','Axel Ivar Ekholm','rör.arb., f.d. 2 kl. sjöman',{birth_literal:'07 ⁹/₃',birth_parish_literal:'S:t Matteus, Sthlm',vaccination_literal:'v',following_mark_literal:'K',arrival_from_folio:1041,arrival_year:1933,banns_literal:'Lysn. 8/1936',military_literal:'frik.',departure_folio:687,departure:'1936-12-08',row:4},['A-3642'],'8/1936 är lysningsnotens literal, inte automatiskt augusti. K lämnas oexpanderat. Egen värnpliktsanteckning frik. finns trots aktens militära noll.',R932);early=s;
  const late=own(p,'C-0973','497 rader 1–3','C0973-497-own','Ekholm, Axel Ivar','rörarb.',{birth_literal:'07 ⁹/₃',birth_parish_literal:'S:t Matteus, Sthlm',vaccination_literal:'v',marriage_year:1936,arrival_from_folio_reading:'976',arrival_from_folio_reserved:true,arrival:'1949-01-14',military_literal:'Frik.',continuation_literal:'N.B. 83',row:1},[ad],'Hushållets son1943 anonymiserad; son1938 på annat radavsnitt får inte tilldelas honom.');adult=late;adultObs=late[2];
  const next=own(p,'C-0973','83 rader 1–3','C0973-83-own','Ekholm, Axel Ivar','',{rows:'1–3',with_wife_and_son:true,continuation_literal:'nb 96'},[ad],'Ingen separat råroll eller säker egen överföringsdag återgiven; moderns g.b.497·54/årsmärken gäller inte sonen.');adult.push(...next);
  for(const [key,kind,date,bas,note]of[['Flen1933','registered_arrival',{precision:'year',value:'1933',literal:'33'},s[2],'Till Lyckedal från fol1041; moderns24april lånas inte.'],['folio687','registered_departure',exact('1936-12-08'),s[2],'Till fol687; detta anger inte bostad hela1936–1949.'],['folio497','registered_arrival',exact('1949-01-14'),late[2],'Från läsosäkert fol976 till497.']]){const ee=event(p,kind,date,[ad,'A-3642'],note,null,'TRANSCRIBED',`E-${kind}-${id}-${key}`);ev(p,ee[0],[bas]);adultEvents.push(...ee);}
  marriage=event(p,'marriage',{precision:'year',value:'1936',literal:'gift1936; hustruns rad har3/5'},['A-3642',cs('C-0972'),cs('C-0973')],'Vigselnotis oläst;3/5står på hustruns rad och bevaras som komponent, ingen tyst exakt dag.');ev(p,marriage[0],[s[2],late[2]]);
  adultFamily=factEv(p,'family_context','adult',{spouse_name:'Ingegärd Regina Lindblom',spouse_literal:'Ingegärd Regina f. Lindblom',spouse_birth:'1912-06-26',spouse_birth_parish:'Flen',marriage_year:1936,wifes_date_components:['36 ³/₅','³/₅'],chosen_marriage_day:null,spouse_arrival_from_folio:1087,spouse_arrival_year:1936,child:{birth_year:1943,birth_place:'Flen',role_literal:'s.'},child1938_not_assigned_to_this_couple:true,child1938_prefix_d_vs_s_unresolved:true,child1938_transfer860_not_own_departure:true},['A-3642',ad,cs('C-0972'),cs('C-0973')],[s[2],late[2]]);
  const life=factEv(p,'occupation','adult-anchors',{1933:['rör.arb.','f.d. 2 kl. sjöman'],1949:['rörarb.'],seaman_period_unknown:true,no_ship_or_voyage_proven:true,no_continuous_sea_service1926_1933_proven:true,seaman_title_not_itself_military:true,military_marks:['frik.','Frik.'],military_exemption_meaning_not_expanded:true,reason_or_date_unknown:true},['A-3642',ad,cs('C-0972'),cs('C-0973')],[s[2],late[2]]);
  p.pending.push({origin:section(p,'Militärt, civilt och rättsligt'),question:'Akt/profil säger ingen militär uppgift, men C0972 rad4 och C0973 fol497rad1 återger värnpliktsfältet frik./Frik. Det positiva fältet bevaras; tjänst, skäl eller exakt frikallelsedag är inte därmed belagt.'});
  const return24=fact(p,'residence','Stockholm1924-1926',{period:'1924–1926',place:'Stockholm',basis:'C0955 textsökning tbLastname=Ekholm tbFirstname=Axel Ivar',individual_post_id_not_recorded:true,return_as_adult_reported:true,exact_arrival_departure_unknown:true},[b,cs('C-0955')]);
  const neg=search(p,'C0957-Matteus1907','S-0747','Axel Ivar Ekholm, född1907-03-09; far Axel Wilhelm Ekholm, mor Hulda Amalia Ålund',{volume:'Matteus C I/1 (1906–1907)',year:1907,posts:'129–182',pages:'87–93',images:'00050993_00088–00050993_00094',birth_dates:{from:'1907-01-11',to:'1907-04-08'},baptism_dates:{from:'1907-03-15',to:'1907-04-11'},separate_control_pages:[97,99,101,104,179]},'Ingen far/mor Ekholm och ingen gosse född9mars i nr129–182. Kontrolluppslag utanför bandet utvidgar inte till helt volymnoll. Tidiga dop, sena inskrivningar och annan dopförsamling kvarstår. Aina Eugenia nr152 och Karl Axel nr134 är andra barn, inga egna kandidater.', ['A-3602',method,cs('C-0957')]);
  for(const native of ['O-P-0016-Axel-Ivar-family','O-P-0016-Axel-Ivar-earlier'])use(p,native,['A-3642',ad]);
  assertion(p,'A-3642',[...s,...adultEvents,...marriage,adultFamily,life,limits],'Egen rad1933/1936 med yrken, frik., lysningsliteral, exakt8decutflyttning och hustruns åtskilda uppgifter.');
  assertion(p,ad,[...adult,...adultEvents,adultFamily,life,limits],'Egen inflyttning14jan1949, familj och olika fortsättningsfolier utan säkert1955år eller gemensam lägenhet.');
  assertion(p,'A-3602',[neg,bornSearch],'OförändratNEGATIVE för lästa bandet; varken födelseort eller hela volymen avvisas.');
  assertion(p,method,[neg,bornSearch,limits],'Båda kanterna öppna och annan dopförsamling möjlig; fem/sexdagarsräkning och normalitetsord kvalificerade.');
  assertion(p,b,[...ro,bo,...be,bf,dep,depEP,return24],'Exakt senare rapporterad födelse, barn inom äktenskapet, utflyttning med modern och senare periodträff utan uppfunnet post-id.');
 }else{
  const late=own(p,'C-0973','497 rader 14–15','C0973-497-own','Johansson f. Ekholm, Ingrid Amalia','fru',{birth_literal:'10 ⁵/₂',birth_parish_literal:'Matteus, Sth. s.',vaccination_literal:'v',marriage:'1942-03-02',arrival_from:'S:t Göran',arrival:'1950-01-03',note_literal:'Gift m. handlaren Allan Gerald Johansson f. 99 ¹⁰/₂',continuation_literal:'N.B. 83',row:14},[ad],'Handlaren gäller maken. Hennes egen yrkesuppgift saknas på raden; det är inget helt livsnoll.');adult=late;adultObs=late[2];
  const next=own(p,'C-0973','83 rader 13–14','C0973-83-own','Johansson, Ingrid Amalia f. Ekholm','',{rows:'13–14',with_son:true,continuation_literal:'nb 96'},[ad],'Ingen säker egen överföringsdag eller separat råroll; ingen1955överlevnad ur bokperioden.');adult.push(...next);
  marriage=event(p,'marriage',exact('1942-03-02'),[ad,cs('C-0973')],'Datum rapporterat i senare församlingsbok. Vigselförsamling och faktisk vigsellokal okända; Stockholm från tidigare hemvist fylls inte som vigselort.');ev(p,marriage[0],[late[2]]);
  const arr=event(p,'registered_arrival',exact('1950-01-03'),[ad,cs('C-0973')],'Till Flen från S:t Göran, inte automatiskt samma lägenhet som modern.',null,'TRANSCRIBED','E-registered_arrival-P-0534-Flen1950');ev(p,arr[0],[late[2]]);adultEvents=arr;
  adultFamily=factEv(p,'family_context','adult',{spouse_name:'Allan Gerald Johansson',spouse_birth:'1899-02-10',spouse_occupation:'handlande',own_occupation_not_given:true,marriage:'1942-03-02',marriage_place_unknown:true,child:{birth_year:1940,birth_place:'Solna',role_literal:'s.'},child_birth_before_marriage_only_chronology:true,no_paternity_or_civil_status_inferred_from_child_year:true,arrival:'1950-01-03',from:'S:t Göran, Stockholm',destination:'Flen'},[ad,cs('C-0973')],[late[2]]);
  for(const native of ['O-P-0016-Ingrid-nearby1950','O-P-0016-Ingrid-family'])use(p,native,[ad]);
  const chrono=fact(p,'age_calculation','dated-anchors',{at_census1910_12_31:{years:0,months:10,days:26},at_departure1913_09_12:{years:3,months:7,days:7},at_marriage1942_03_02_years:32,at_arrival1950_01_03_years:39,husband_older_approximately_years:11,own_death_unknown:true},[method,cs('C-0955'),cs('C-0973')]);
  const military=fact(p,'research_limits','military-generalization',{no_own_military_record_reported:true,male_conscription_rule_not_exclusion_of_all_military_information:true,own_occupation_not_husbands_trade:true},[section(p,'Militärt, civilt och rättsligt'),cs('C-0973')]);
  p.pending.push({origin:section(p,'Militärt, civilt och rättsligt'),question:'Påståendet ingen militär uppgift kan finnas följer inte av att värnplikten gällde män. Ingen egen uppgift är läst; det är skilt från om militärt relaterad verksamhet eller annan civil militär handling kan finnas.'});
  p.pending.push({origin:section(p,'Namnformer'),question:'Aktens namnlista anger Johansson som ej belagd utskriven form. C0973fol497rad14 skriver Johansson f. Ekholm, Ingrid Amalia och fol83sammanfattningen Johansson, Ingrid Amalia f. Ekholm. Råformerna är belagda; den omordnade sökformen Ingrid Amalia Johansson är en normalisering.'});
  assertion(p,ad,[...adult,...marriage,...adultEvents,adultFamily,limits],'Egen vuxenrad med exakt rapporterad vigsel, makes egen titel och födelse, eget inflyttningsdatum och anonym son.');
  assertion(p,method,[bornSearch,chrono,adultFamily,limits,military],'Förebyggande sökregel, ingen negativ egen sökning, beräknade åldrar med rätt person; statistisk dopnorm reserverad.');
  assertion(p,b,[...ro,bo,...be,bf,dep,depEP],'Exakt senare rapporterad födelse och egen utregistrering12sept1913. Ingen egen dopdag.');
 }
 const res=factEv(p,'residence','recorded-anchors',{census1910:'Kungsholm rote23, Kettingen36/37, familj1',departure1913:{date:'1913-09-12',to:'Helgesta',with_mother_and_sibling:true},Hyltinge_book_context:'Banvaktstugan70, AIIa5 (1918–1927), egna rader i moderns hushåll',adult_first_folio:son?932:497,adult_folio497:'Hjärpen35C, Hagagatan8, Flen',adult_folio83:'Hjärpen2, Hagagatan7, Flen',new_address_not_automatically_physical_move:true,next_reference:'nb96',next_transfer_year_unknown:true,...(son?{Lyckedal1933_from1041:true,departure1936_to687:'1936-12-08',arrival1949_from976_reading_reserved:true}:{} )},[a,b,ad,cs('C-0973'),cs('C-0919')],[c[2],ro[2],hy[2],adultObs]);
 assertion(p,a,[...c,father,mother,sibling,fam,res,names],'År/Stockholm/familj1med egen rånamnsgräns; barnroll från egen rotepost.');
 relationRow(p,'P-0532',[father,fam],'Fader i identifierat hushåll, död1913iHelgesta utan att låna Stockholm som dödsort.');
 relationRow(p,'P-0016',[mother,fam,dep,depEP,res,limits],'Moderns relation och gemensam utregistrering; sena folier är närhet, inte gemensam lägenhet.');
 relationRow(p,other,[sibling,fam,dep,depEP],'Syskon med samma föräldrapar och gemensam utregistrering; bådas egna datum separat.');
 relationRow(p,'Maj Amalia',[half,half17,fam,...hy],'Maternal halvsyster identifierad som befintlig P0007; u.ä. och erkännande hör till hennes rad, inte egen.');
 relationRow(p,son?'Ingegärd Regina':'Allan Gerald',[adultFamily,...marriage,...adult],'Namngiven make/maka bevaras utan extra personkärna; egna födelsedata och yrke på rätt subjekt.');
 relationRow(p,'en son född',[adultFamily,...adult,limits],'Tidigare minimerat födelseår/ort och sonroll består, inga namn/dagar införs.');
 finish(p);
}
const path='genealogy2/migration/persons-11-ekholm.json';
if(fs.existsSync(path))throw Error('Supplementalpacket finns redan; ersätt bara uttryckligen vid reproducering.');
for(const p of output){const ids=new Set(p.changes.map(m=>m.id));if(ids.size!==p.changes.length)throw Error('Dubbel ändring '+p.person);}
const temp=path+'.writing-'+process.pid;fs.writeFileSync(temp,JSON.stringify(output,null,2)+'\n');fs.renameSync(temp,path);
console.log(output.map(p=>({person:p.person,changes:p.changes.length,reuse:p.reuse.length,assertions:p.assertions.length,relations:p.relations.length,pending:p.pending.length})));
