import {db,person,core,add,fact,relation,event,exact,section,origins,cs,reuse,assertion,relationRow,save} from './genealogy2-persons11-combined.mjs';
const cfg=[
{id:'P-0509',child:'P-0329',mate:'P-0510',name:'Anders Åhlund',role:'Klåckaren',home:'Klåckaregården',birth:'1808-09-02',baptism:'1808-09-04',a:'A-3223',network:'A-7300',age:'A-7679',mother:false},
{id:'P-0510',child:'P-0329',mate:'P-0509',name:'Hedda Molander',role:'Dess Hustru',home:'Klåckaregården',birth:'1808-09-02',baptism:'1808-09-04',a:'A-3224',network:'A-7302',age:'A-7681',mother:true},
{id:'P-0511',child:'P-0330',mate:'P-0512',name:'Carl Carlsson',role:'Bonden',home:'Stocktorp',birth:'1808-12-23',baptism:'1808-12-26',a:'A-3225',network:'A-7303',age:'A-7683',mother:false},
{id:'P-0512',child:'P-0330',mate:'P-0511',name:'Anna Anders Dotter',role:'Dess Hustru',home:'Stocktorp',birth:'1808-12-23',baptism:'1808-12-26',a:'A-3226',network:'A-7304',age:'A-7684',mother:true}];
for(const c of cfg){
 const p=person(c.id,'Hela akten och profilen samt hela C0845/C0317 inklusive T0167/T0174/T0193 lästa. Återbrukar egna avgränsade föräldraomnämnanden och barnens händelser/vittnen. En egen föräldrapost ger TRANSCRIBED; barnets senare identitet ger ingen andra källa för förälderns eget liv. Intervallregeln, sociala inferenser, rättade namn/orter och kunskapsgränser bevaras uttryckligt.');
 core(p,[section(p,'Identitet')],'Säker avgränsad förälder i en egen post; OLÖST ursprung och AVVAKTAR trädverkan bevaras separat. C0317 namnger barnet, inte denna förälder.');
 const m=`M-C0845-${c.child}-parent-${c.id}`,oldO=`O-C0845-${c.child}-${c.id}`,oldI=`ID-${m}`;
 const r=db.prepare('select x.* from current_revision v join mention x on x.revision_id=v.id where v.object_id=?').get(m);
 if(r.name_literal!==c.name||r.role_literal!==c.role)throw Error('Eget befintligt omnämnande avviker '+c.id);
 const own=[m,oldO,oldI].map(id=>reuse(p,id,[c.a,cs('C-0845')]));
 const ff=(prop,key,value,os,status='TRANSCRIBED',caveat='')=>{const id=fact(p,prop,key,value,[...os,cs('C-0845')],status,caveat);p.changes.at(-1).evidence=[{object:oldO,role:'supports',note:'Den egna föräldraposten; ingen andra oberoende personkälla.'}];return id;};
 const parent=relation(p,c.id,c.child,'parent',[c.a,section(p,'Relationer')]);
 const spouse=relation(p,c.id,c.mate,'spouse',[c.a,section(p,'Relationer')],'recorded_spouse');
 const ev=[];for(const[k,date]of[['birth',c.birth],['baptism',c.baptism]]){const ids=event(p,k,exact(date),[c.a,cs('C-0845')],'Förälder i barnets egen post, inte eget födelse- eller dopdatum.',null,'TRANSCRIBED',`E-${k}-${c.child}`,'parent');const ep=p.changes.find(x=>x.id===ids[1]);if(ep)ep.data.mention_id=m;ev.push(...ids);}
 const w=db.prepare("select v.object_id,p.mention_id from current_revision v join participation p on p.revision_id=v.id where p.event_id=? and p.role='witness'").all(`E-baptism-${c.child}`);
 if(w.length!==6)throw Error('Sex egna vittnen krävs');
 const wit=w.flatMap(x=>[reuse(p,x.object_id,[c.network]),reuse(p,x.mention_id,[c.network])]);
 const raw=add(p,`O-${c.id}-C0845-number-field`,'observation',{record_id:r.record_id,mention_id:m,property:'number_field',value_literal:c.child==='P-0329'?'30. 35.; senare läsning30- 35.':'30-35.',value_json:{field:c.child==='P-0329'?'30- 35.':'30-35.',position:'efter moderns namn'}},[c.age,cs('C-0845')],[r.record_id],'Endast råfältets form och position i egen post; vem intervallet avser är en separat tolkning.','TRANSCRIBED','recorded');
 const age=ff('source_interpretation','age-interval',{raw:'30–35',one_interval_not_two_ages:true,comparison_posts:21,single_mother_posts:4,intervals:['20–25','25–30','30–35','35–40','40–45'],probable_subject:'modern',rule_proven:false,alternatives:['moderns ålder','hushållsföreståndarens ålder','hushållet som helhet'],own_definite_age:null,own_conditional_birth:c.mother?'omkring1773–1778':null,own_date_selected:false,matching_interval_other_mother_not_rule_confirmation:true,comparison_covers_whole1808:false,parish_annual_total33_not_family_count:true},[c.age,section(p,'Historik och rättelser')],'INFERRED','Fyra enmodersposter motsäger två personers åldrar. De avgör inte säkert modern kontra hushållsföreståndare i tvånamnspost. Ingen ålders-/födelsehändelse konstrueras.');
 p.changes.at(-1).evidence.push({object:raw,role:'supports',note:'Egen råcell.'});
 const oldAge=reuse(p,`F-${c.child}-parent_age-interval1808`,[c.age]);
 const residency=ff('residence','reported1808',{home:c.home,parish:'Ludgo',date:c.birth,only_own_life_anchor1808:true,earlier_later_unknown:true,child_later_Gryt_Helgesta_not_own_migration:true,home_not_own_birthplace:true,own_occupation:c.mother?null:c.role,spouse_title_not_own_occupation:c.mother,only_one_record:true,child_correlation_in_C0317_not_second_parent_record:true},[c.a,c.network,section(p,'Boställen och flyttar')]);
 const social=ff('social_network','own-child-baptism',{event:`E-baptism-${c.child}`,witness_count:6,kinship_proven:false,social_description:c.child==='P-0329'?'ämbets- och kyrkliga rolltitlar i samma doppost':'bönder, torpare, enka, son och dotter i samma doppost',independent_record_corroboration:false,own_upbringing_or_social_origin_not_proven:true,no_contacts_outside_baptism_ruled_out:true,own_surname_match_count:c.id==='P-0512'?3:0,Anders_patronymic_bearers:c.child==='P-0330'?['Pehr Andersson','Lena Anders Dr.','Cathrina Anders dr']:[],two_highlighted_in_A7304:c.child==='P-0330'?['Pehr Andersson','Cathrina Anders dr']:[],two_highlighted_not_exhaustive:c.child==='P-0330',Sattersta_reserved:c.child==='P-0330',external_parish_route_may_belong_to_either_parent:true},[c.network,section(p,'Relationer')],'INFERRED','Faddrarnas titlar är samma handlings kontext. Namnlikhet/namnfrånvaro bevisar varken släktskap, härkomst eller att dopvägen är uttömd. A7304:s två utpekade nycklar behålls; Lena Anders Dr är en tredje faktisk patronymikonbärare.');
 const limits=ff('life_context','unknowns',{own_birth_date:null,own_birth_place:null,own_parents:null,own_death:null,own_marriage_date:null,only_known_child:c.child,additional_children_unknown:true,own_hand_unknown:true,own_letters_photos_unknown:true,death_or_birth_original_unread:true,named_as_parent_not_independent_survival_certificate:true,churching_date_absent:true,patronymic_not_new_parent_identity:true,contract_not_upgraded:true,definite_military_exclusion_not_inferred_from_role:true},[section(p,'Hälsa och död'),section(p,'Militärt, civilt och rättsligt'),section(p,'Media och personliga källor')]);
 const corrected=ff('source_assessment','corrected-forms',{current_name:c.name,current_home:c.home,current_role:c.role,rejected_old_title:c.id==='P-0509'?'mäskaren':null,rejected_old_surname:c.id==='P-0510'?'Morander':null,rejected_old_place:c.child==='P-0330'?'Hökstorp':null,correction_is_same_cell_not_new_source:true,old_wrong_key_negative_not_valid:true,name_alone_not_identity:true,Hedvig_only_search_variant:c.id==='P-0510',file_name_not_source_evidence:true},[c.a,section(p,'Namnformer'),section(p,'Historik och rättelser')]);
 const extras=[];
 if(c.id==='P-0509')extras.push(ff('occupation','clerk1808',{title:'Klåckaren',place:'Ludgo',home:'Klåckaregården',service_home_interpretation:true,private_ownership_proven:false,tenure_contract_unread:true,loss_of_home_on_end_of_office_not_personally_proven:true,appointment_date:null,salary_amount:null,teacher_role_proven:false,own_hand_identified:false,appointment_accounts_unread:true},[c.a,c.network,section(p,'Yrke, utbildning och ekonomi')]));
 if(c.id==='P-0511')extras.push(ff('occupation','farmer1808',{title:'Bonden',place:'Stocktorp,Ludgo',tenure:null,farm_share:null,property_ownership_not_proven:true,roteholder_or_soldier_role_not_proven:true,neighbour_landsvarnist_not_this_man:true,torp_suffix_not_farm_tenure:true},[c.a,section(p,'Yrke, utbildning och ekonomi'),section(p,'Militärt, civilt och rättsligt')]));
 if(c.id==='P-0510')extras.push(ff('name_context','Molander',{source:'Hedda Molander',rejected:'Hedda Morander',search_forms:['Hedda Molander','Hedvig Molander'],family_name_not_patronymic:true,her_social_origin:null,adopted_name_possible:true,no_witness_named_Molander:true,no_kinship_route_from_name_only:true,all_baptism_kinship_routes_exhausted:false},['A-7682',c.a],'INFERRED'));
 assertion(p,c.a,[...own,parent,spouse,...ev,residency,corrected,...extras],'Den namngivna föräldern och barnkorrelationen bevaras; egna uppgifter är från en enda post.');
 assertion(p,c.network,[...wit,social,residency,...extras],'Samtliga sex barnbundna vittnen återbrukas med egna poster/roller; sociala och namnmässiga jämförelser kvalificeras.');
 assertion(p,c.age,[raw,age,oldAge,limits],'Det omprövade intervallet bevaras som villkorlig tolkning; ingen säker egen ålder eller dag fylls i.');
 if(c.id==='P-0509'){
  assertion(p,'A-7301',[raw,age,oldAge],'Den äldre råavskriften består, plural-slutledningen är upphävd av T0174.');
  const compare=reuse(p,'F-P-0329-network_comparison-1808',['A-7680']);
  assertion(p,'A-7680',[compare,social,...wit],'Noll gemensamma vittnesnamn gäller de två dopkretsarnas tolv namn, inte annan kontakt eller oberoende social härkomst.');
 }
 if(c.id==='P-0510')assertion(p,'A-7682',[social,...extras,...wit],'Inget Molander bland sex egna vittnen, tre andra familjenamn; ingen säker släktfrånvaro eller social härkomst sluts.');
 relationRow(p,c.child,[parent,...ev],'Uttrycklig egen föräldraroll; barnets datum överförs inte till förälderns eget liv.');
 relationRow(p,c.mate,[spouse,residency],'Make/maka i egen post; vigseldatum okänt.');
 p.pending.push({origin:c.age,question:'C0845 T0174 visar ett intervall efter moderns namn men modern/hushållsföreståndare/hushåll är inte slutligt avgjort. Mödrarnas cirka1773–1778 är villkorligt, fäderna saknar säker datering.'},{origin:section(p,'Hälsa och död'),question:'Föräldranamn i barnets doppost är inget oberoende bevis för överlevnad till dopdagen; egna födelse-/dödposter och kyrktagningsdatum saknas.'},{origin:c.network,question:'Vittnenas roller och namn beskriver samma post, inte en oberoende bekräftelse av social härkomst eller släktfrånvaro. Ingen familjekontakt utanför dopet utesluts.'});
 if(c.id==='P-0512')p.pending.push({origin:c.network,question:'A7304 pekar ut två Andersson/Andersdotter-vittnen, men C0845 har också Lena Anders Dr. som tredje. Ingen av de tre får släktrelation utan nytt belägg.'});
 save(p);
}
