import pathlib,json,sqlite3,datetime,hashlib,native_payload
B=pathlib.Path(__file__).resolve().parent;native_payload.connection=sqlite3.connect('file:'+str(B/'clone/research-candidate-v7.sqlite')+'?mode=ro',uri=True);native_payload.connection.row_factory=sqlite3.Row
d=json.loads((B/'source-decisions/C-0083-pending-amendment-dispositions-v1.json').read_text());pending=json.loads((B/'C-0083-amended-full-object-match-v1.json').read_text())['pending'];assert {r['id'] for r in pending}=={r['id'] for r in d['rows']}
x=next(r for r in d['rows'] if 'patch' in r);e=x['patch'];obj=native_payload.existing(e['id'],e['expectedVersion']);assert obj['caveat'].count(e['before'])==e['expected_match_count'];obj['caveat']=obj['caveat'].replace(e['before'],e['after'],1);obj['rationale']+=' T-0776 AC3: '+x['reason']
for binding in e['approved_support']:
 oid,ver=binding.rsplit('@',1)
 if not any(z['object']==oid and z['version']==int(ver) for z in obj['evidence']):obj['evidence'].append({'object':oid,'version':int(ver),'role':'supports','note':'T-0776: individuellt Astra-prövad befintlig egen familjerad och bokföringsankare.'})
op={'id':'T-0776/C0083-final-participation-resolutions-v1','actor':'Codex Sol mechanical implementation of individual Astra dispositions','reason':'T-0776 AC3–4: exakt deltagarkopia rättas och fyra beroendeprövningar avgörs individuellt; kontrollerad kanonisk införsel efter självständig slutgranskning.','dependencyReviewVersion':2,'changes':[obj],'resolve':[{'request':r['id'],'rationale':'T-0776 C0083 individuell Astra-disposition för '+r['affected_revision_id']+': '+r['reason']} for r in d['rows']]}
p=B/'C-0083-final-participation-operation-v1.json';p.write_text(json.dumps(op,ensure_ascii=False,indent=2)+'\n');(B/'C-0083-final-participation-freeze-v1.json').write_text(json.dumps({'created_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'files':[{'path':str(q),'sha256':hashlib.sha256(q.read_bytes()).hexdigest()} for q in [p,B/'source-decisions/C-0083-pending-amendment-dispositions-v1.json']]},indent=2)+'\n')
a=sqlite3.connect('file:'+str(B/'clone/research-candidate-v7.sqlite')+'?mode=ro',uri=True);b=sqlite3.connect(B/'clone/research-final-candidate-v1.sqlite');a.backup(b);b.close()
