from pathlib import Path
import re,hashlib,json,datetime
p=Path('PROJECT-CONTROL.md');before=p.read_bytes();s=before.decode();assert 'project-control/v0.1' in s
ids={t:max([int(n) for n in re.findall(t+'-2026-10-02-(\\d+)',s)] or [0])+1 for t in ['PCR','PCD']};review=f"PCR-2026-10-02-{ids['PCR']:03d}";decision=f"PCD-2026-10-02-{ids['PCD']:03d}"
append=f'''\n\n## {review}\n\n- Record type: review\n- Date: 2026-10-02\n- Mode: checkpoint\n- Trigger: T-0775 är slutförd och ägarens slutavläsning är 39 procent mot startens 37. Ägaren begär fortsatt rekommendation.\n- Control judgement: continue, evaluate\n- Current gate: Den initiala kedjans käll- och följdtäckning behöver fortfarande självständig prövning. Underlaget är en liten pilot, inte visad generell kostnad eller felfrihet.\n- Recommendation: Nästa exakt tre nya G001-scopes med samma gräns: Sol för metadata och avgjord implementation, Astra för käll-/evidensbedömning och separat Astra för självständig slutgranskning. Skärp konsekvenstabellen med exakta citat, versioner, fält, stöd och individuella dispositioner även för retain. Dittotecken kan bära egen personuppgift trots ej utskrivet ord; daterade ankare ska nå luckbeskrivningar; oprövat ska ange exakt återstående omfång. Rättningsanvisning med noll exakt ersättningsträff återförs till Astra.\n- Owner decision required: Godkänn denna avgränsade fortsättning; ägarens svar bevaras separat i {decision}.\n- Evidence: `evaluations/T-0775/report.json`, `evaluations/T-0775/budget-amendment-v1.json`, `evaluations/T-0775/final-review/independent-review-agent-v1.md`, `NORTH-STAR.md`, `AGENTS.md`.\n- Uncertainty: Två observerade procentenheter för tre accepterade scopes är lovande men bevisar inte kausal halvering. Oberoende granskning fann två materiella och tre precisionskluster som rättades; förstakandidaten räckte inte. Modellsamstämmighet är inget källstöd.\n- Revisit when: T-0776:s faktiska budget, fynd och rättningsbörda finns. Upprepade materiella följdfel utlöser riktad metodundersökning före vidare skala.\n\n## {decision}\n\n- Record type: decision\n- Date: 2026-10-02\n- Decides review: {review}\n- Owner: Sverker Adam Janson\n- Decision: ”vi fortsätter som du rekommenderar”. Genomför nästa exakt tre nya G001-scopes enligt rekommendationen, med skärpt följdgranskning och oförändrad Sol/Astra-sakgräns.\n- Disposition: approved\n- Resulting Wotan tasks: T-0776; T-0677 uppdateras enbart med faktiskt accepterad programprogress.\n- Portfolio signal: Projektet får fortsatt avgränsad hybridpilotuppmärksamhet. Ingen permanent modellregeländring eller fjärde scope är godkänd genom detta beslut.\n- Related records: `wotan/dev-log/T-0776.md`, `PCD-2026-10-01-001`, `evaluations/T-0775/budget-amendment-v1.json`.\n- Revisit when: T-0776:s budget, fynd och rättningsbörda är redovisade, eller upprepade materiella följdfel motiverar riktad metodundersökning.\n'''
p.write_bytes(before+append.encode());assert p.read_bytes().startswith(before)
b=Path('evaluations/T-0776');(b/'project-control-append-receipt.json').write_text(json.dumps({'review_id':review,'decision_id':decision,'before_sha256':hashlib.sha256(before).hexdigest(),'after_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'previous_bytes_preserved':True,'recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat()},indent=2)+'\n')
log=Path('wotan/dev-log/T-0776.md');log.write_text(log.read_text()+f'\n## Godkänd styrning bevarad\n\nReview `{review}` och separat ägarbeslut `{decision}` är append-only bevarade i [PROJECT-CONTROL.md](../../PROJECT-CONTROL.md). Tidigare bytes bevarade; inget protokollbyte eller nytt modellmandat. Kvitto: `evaluations/T-0776/project-control-append-receipt.json`.\n')
print(review,decision)
