import json,pathlib,datetime,hashlib
B=pathlib.Path(__file__).resolve().parent;now=datetime.datetime.now(datetime.timezone.utc).isoformat();usage=json.loads((B/'usage-snapshot.json').read_text());(B/'usage-at-report-v1.json').write_bytes((B/'usage-snapshot.json').read_bytes())
start=datetime.datetime.fromisoformat('2026-10-02T06:41:10.017070+00:00');elapsed=(datetime.datetime.fromisoformat(now)-start).total_seconds()
clusters=[{'id':'K1','scope':'C-0038','topic':'Own Jungf. title, unsupported own ogift, and reserved Ökna/609 suffix reading','discovery':'Primary original pass; exact source changes before first C38 candidate.'},{'id':'K2','scope':'C-0083','topic':'Parents residence versus physical delivery location in BIO117','discovery':'Independent final IF1 before initial C83 freeze; primary verified printed header.'},{'id':'K3','scope':'C-0083/current Segerslund support','topic':'Already-read household/date anchors versus false unread/gap descriptions','discovery':'Primary copy follow-through plus independent IF2; IF3 separate outcome omission and final pending P15 participation copy. Existing native support, no fourth image.'},{'id':'K4','scope':'C-0083/current census support','topic':'Unsupported independent baptism confirmation chain','discovery':'Primary additional consequence follow-through after first candidate.'},{'id':'K5','scope':'C-0083','topic':'Unsupported paternal second-son order','discovery':'Primary additional consequence follow-through after first candidate.'},{'id':'K6','scope':'C-0083','topic':'Fadderns surname versus Faderns','discovery':'Primary additional consequence follow-through after first candidate.'},{'id':'K7','scope':'C-0083/current census support','topic':'No registered absence versus physical presence','discovery':'Primary additional consequence follow-through after first candidate.'}]
counts={'accepted_scopes':3,'own_posts':3,'grouped_fields':{'C-0037':10,'C-0038':10,'C-0083':21},'grouped_field_total':41,'grouped_fields_are_not_new_facts':True,'unique_researched_people':4,'bounded_adoptions':5,'Ada_adopted_in_two_posts':True,'C0083_source_people':6,'C0083_existing_context_mentions':3,'metadata_route_people_not_subject_count':8,'new_objects':12,'revised_existing_objects':19,'unique_changed_objects':31,'revision_events':32,'individual_resolutions':6}
measurement={'task':'T-0776','state':'CANONICAL_VERIFIED_END_METER_PENDING','recorded_at_utc':now,'started_at_utc':start.isoformat(),'elapsed_seconds_through_report':elapsed,'baseline_percent':39,'baseline_quality':'Provisional latest owner reading before continuation chat, not exact fresh task-only baseline. Preparation counts.','end_percent':None,'root_model_and_usage':'UNKNOWN; not zero','usage_snapshot':'usage-at-report-v1.json','usage_agents':[{k:a[k] for k in ['agent_path','thread_id','actual_usage_sum']} for a in usage['agents']],'production_scope':'All preparation, primary Astra source decisions, Sol implementation and failed technical apply, independent final Astra findings/rebind/final review and closure count production.','phase_timing':{'task_start':start.isoformat(),'source_start_approx':'2026-10-02T06:55:00+00:00','source_handoff_complete':'2026-10-02T07:36:03.043647+00:00','independent_final_receipt':'2026-10-02T07:49:55.993687+00:00','root_apply_gate':'2026-10-02T07:51:27.102833+00:00','root_actual_confirmation':'2026-10-02T07:54:52.723000+00:00','report':now},'limits':['Phases overlap; their elapsed times must not be summed.','Only exact new T776 turns/response usage, no old T775 cumulative totals.','Cached input separated; reasoning is output subset, not double counted.','Current response/later root closure usage requires appended final metadata snapshot.','Root unknown means logged agent sums are not whole-pilot total.','No matched all-Astra baseline; grouped post sizes differ from T775; no causal halving or quality superiority conclusion.']}
(B/'measurement-report-v1.json').write_text(json.dumps(measurement,ensure_ascii=False,indent=2)+'\n')
report={'task':'T-0776','recorded_at_utc':now,'outcome':'EXACT_THREE_SCOPES_CANONICALLY_ACCEPTED_AFTER_INDEPENDENT_FINAL_PASS','scopes':['C-0037','C-0038','C-0083'],'baseline_journal':248,'canonical_journal':255,'G001_before':30,'G001_after':33,'G001_total':40,'work_counts':counts,'correction_clusters':clusters,'formal_independent_findings':['IF1: parental residence/physical birthplace precision','IF2: false unread current event caveat','IF3: separate pathway outcome left contradictory by primary specification omission; Sol faithfully implemented specified body changes'],'sol_implementation_history':['All source decisions made by Astra; zero unexpected exact replacement matches silently skipped.','One final participation apply rejected stale E-other@1 support before write; independent Astra approved exact bounded1→2 rebind. Failed operation and error preserved; revised operation applied.','Initial C37 explicit structural mention dependency amendment; earlier candidate/check history preserved.','106 stale UNDECIDED scaffold flags cleaned metadata-only where explicit Astra disposition/reason already existed; exact receipt preserved.'],'validation':{'full_object_matches':'31/31 ordered data/payload/metadata/evidence/origin','pending':0,'verify':0,'verify-assets':0,'verify-source':0,'root_independent_all_current_revision_count':44136,'all_current_revisions_equal_reviewed_stage':True,'protected_native_invariants':'PASS;19explicit existing revisions only, person/relation/identity/OWNER/gates unchanged','prior_preservation_hash_bindings':40299,'prior_preservation_mismatches':0,'default_verified_pedigree_P0269_paths':20},'research_limits':['No fourth original; Segerslund/1905/1918 support documentary native reuse.','Current household sources do not prove uninterrupted physical residence, exact travel day, or physical delivery place.','No new identity/person/relationship/sex/OWNER/gate approvals.','T0677 remains unfinished33/40; task completion differs from ancestry/life-picture/source-exhaustion completion.'],'measurement':'measurement-report-v1.json','report_usage':'usage-at-report-v1.json','canonical_receipt':'canonical-apply/canonical-result.json','independent_actual_confirmation':'canonical-apply/root-independent-stage-comparison-v1.json','program_receipts':'program-acceptance-v1.json','freeze':'final-review/candidate-freeze-v1.json','end_meter_pending':True,'later_meter_policy':'Append a versioned budget amendment and supplemental completion manifest; never rewrite this frozen report.'}
(B/'report.json').write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');(B/'work-counts-final-v1.json').write_text(json.dumps(counts,indent=2)+'\n')
(B/'report.md').write_text('''# T-0776 result

Exactly C-0037, C-0038 and C-0083 are accepted in canonical genealogy2 after independent Astra final PASS and root’s separate apply gate. Seven controlled operations advanced j248→255; G001 is 33/40 and remains unfinished.

The three own posts contain 10+10+21=41 grouped fields, not 41 new facts. Five bounded adoptions cover four existing researched people (Ada in two posts). C-0083 also retains three existing contextual mentions. The eight metadata-routed people are not eight source subjects. Canonical work comprises 12 new objects and 19 existing objects revised, 31 unique objects, 32 revision events and six individual resolutions.

The final result passes 31/31 strict ordered full-object matches, pending0 and all three validators. Root independently confirmed all 44,136 current revision records equal the reviewed stage, including affected native data, dependencies and origins. Protected person, relation, identity, OWNER and gate state is unchanged. Current default verified P-0269 pedigree still has 20 paths. All 40,299 recorded prior preservation hash bindings match.

Initial candidates were not error free. Seven correction clusters are listed in report.json. Formal independent IF1/IF2/IF3 and further primary copy corrections are preserved with their discovery timing. IF3 was a missed separate outcome in the primary specification; Sol implemented the specified body change faithfully. A final participation apply rejected stale support before writing; Astra reviewed and authorized the exact rebind. The failed version and accepted amendment remain available.

Production measurement includes preparation, both Astra roles, implementation, corrections and finalization. The 39% baseline is provisional; the owner’s end reading is pending. Exact new-turn usage is recorded per agent, while root model/usage remains unknown rather than zero. Current-response and later closure usage will require an appended snapshot. Post size and grouped-field conventions differ from T-0775, and there is no matched all-Astra comparator: no causal halving or superior-quality claim is supported.

No fourth original, dashboard/archive update, commit, push or PDF. Existing Segerslund/1905/1918 native support was reused documentarily. Bookkeeping anchors do not establish uninterrupted physical residence or exact physical delivery/travel location. Later budget readings must append an amendment rather than rewrite this report.
''')
print('Report, counts and production measurement saved; end meter pending')
