import json,pathlib,hashlib
B=pathlib.Path('evaluations/T-0781');O=B/'independent-review'
def rd(p):return json.loads(pathlib.Path(p).read_text())
def pin(p):return {'path':str(p),'sha256':hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()}
p=B/'implementation/six-future-owner-append-only-administration-plan-v1/six-individual-reviewable-append-only-owner-plan-v1.json';d=rd(p);s=rd(d['source_ledger_pin']['path']); rows=[]
back=rd('wotan/backlog.json'); tasks=back if isinstance(back,list) else back.get('tasks',[]); lookup={t['id']:t for t in tasks}
for i,r in enumerate(d['rows']):
 old=pathlib.Path(r['existing_log_pin']['path']).read_bytes();a=pathlib.Path(r['append_pin']['path']).read_bytes();assert pin(r['existing_log_pin']['path'])==r['existing_log_pin'];assert pin(r['append_pin']['path'])==r['append_pin'];assert a.decode()==r['append_text'];assert hashlib.sha256(old+a).hexdigest()==r['expected_after_full_log_sha256'];assert len(old)==r['existing_prefix_bytes'];assert lookup[r['owner_task_id']]==r['current_backlog_entry'];assert s['rows'][i]['reuse_and_corrected_premise'] in r['append_text'];assert s['rows'][i]['remaining_exact_scope'] in r['append_text']
 rows.append({'owner_task_id':r['owner_task_id'],'whole_existing_log_actually_read':True,'existing_log_pin':r['existing_log_pin'],'whole_append_actually_read':True,'append_pin':r['append_pin'],'own_source_scope_decision':'APPROVE_EXACT_CONDITIONAL_APPEND','reason':'Reuse exact two-source own fields and sufficient older support; preserves residual own-source/time/field tests, no result/identity/path guarantee, no newly scheduled research. Existing whole log prefix, status, after, task ID and AC remain unchanged. Historical older claims are qualified by the explicit latest amendment.','status_after_guard_exact':True,'old_prefix_plus_append_sha256':r['expected_after_full_log_sha256']})
out={'task':'T-0781','scope':'Administrative text source/scope approval only, not Wotan write authority','plan_pin':pin(p),'source_ledger_pin':d['source_ledger_pin'],'rows':rows,'raw_glyph_reservations':'Preserve tested source ambiguities; no new task per glyph and no routine third C67 reading.','execution_preconditions':['actual exact two accepted canonical receipts','root explicit append authorization','fresh exact log-prefix and backlog-entry guards'],'new_tasks':0,'status_AC_changes':0,'actual_acceptance':False,'runtime_or_Wotan_authorized':False};q=O/'six-future-owner-exact-append-source-and-preservation-review-v1.json';q.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(pin(q))
