import{person,core,add,fact,event,relation,reuse,assertion,relationRow,save,origins,exact,units,section,src,cs,record}from'./genealogy2-persons08-combined.mjs';
const p=person('P-0397','Hela akten/profilen genomlästa samt C0473/0474/0475/0651/0800/0806/0774/0945 med sena rättelser. Akten missar brudens redan utvunna Skånela och Klara10okt1888, räknar makens fyra barn som två och överdriver gravfrånvarons innebörd. Dessa gränser registreras; eget ursprung och livsslut förblir öppna, äldre PK-underkännande består. Ingen ny arkivläsning.');const po=[origins(p.person,'person',1,257)];core(p,[section(p,'Identitet')],'Säker familjeidentitet, obelagt ursprung och livsslut.');
const bride=['M-C0474-bride','ID-C0474-bride','O-C0474-bride'].map(id=>reuse(p,id,['A-2253','A-2254']));
const extra=add(p,'O-P-0397-C0474-extra','observation',{record_id:record('C-0474'),mention_id:'M-C0474-bride',property:'bride_additional_fields',value_literal:'Jungfrun; Skånela,Stockholms län; Klara10/10 1888; God; Medborgerlig; Ofta; streck; tidigare-barnfält tomt',value_json:{role_literal:'jungfrun',birth_county:'Stockholms län',smallpox:'streck',widow_field:'streck',estate_field:'streck',guardian_field:'streck',previous_children_field:'',banns:['1888-11-18','1888-11-25','1888-12-02'],marriage:'1888-12-08',officiant:'v.komminister Sch…[?]',certificate_issued:'1888-12-27',priest_signature_name_unresolved:true}},['A-2254',cs('C-0474')],[record('C-0474')],'Egna brudfält och gemensamt vigselavsnitt; tomt tidigare-barnfält bevisar inte barnlöshet.','TRANSCRIBED','recorded');
const birth=event(p,'birth',exact('1866-10-16'),['A-2253'],'Uppgivet i1888års originalakt, ingen egen födelsenotis.');const arrival=event(p,'registered_arrival',exact('1888-10-10'),['A-2254',cs('C-0474')],'Klara till Kungsholm enligt vigselakt; ingen belagd fysisk resdag.');const marriage=event(p,'marriage',exact('1888-12-08'),['A-2254'],'Kungsholm; samma redan införda parhändelse.',null,'CORROBORATED','E-marriage-P-0336-P-0397-1888');
const spouse=relation(p,'P-0336',p.person,'spouse',['A-2254'],'marriage');
const census1900=src(p,'C-0806','','C0806-own','Johanna Charlotta','h.',{year:1900,birth_year:1866,birth_place:'Skånela',marital_status:'gift',family_role:'Mor/fru',home:'Jordgubben N:o11,Kungsholm rote17',family:1,folio:43,children:['Frida Elisabeth1883','Augusta Gerda Charlotta1890','Ester Olivia Johanna1891','Edit Maria Justina1894','Oskar Fredrik1895']},['A-3086'],'Hushållsroll avgör inte moderskap till Frida. Inget eget efternamn utvunnet.');
const census1910=src(p,'C-0774','','C0774-own','Johanna Charlotta','',{date:'1910-12-31',birth_year:1866,birth_place:'Skånela',birth_county:'Stockholms län',marital_status:'gift',family_role:'Mor/fru',home:'Gösen4,15,Klara rote3',family:1,folio:31,children:['Augusta Gärda Charlotta1890','Ester Olivia Johanna1891','Edit Maria Justina1895','Oskar Fredrik1895','Elvira Fredina Gully1902']},['A-2998'],'Ingen separat råroll utvunnen; familjekoden hålls som eget fält.');
const family=reuse(p,'F-P-0336-family_context-nine-known-children',po);
const correction=fact(p,'source_assessment','own-fields-and-family',{birth_parish_already_in_C0474:'Skånela',arrival_already_in_C0474:'1888-10-10 från Klara',bride_home:'37Fleminggatan',own_birth_original_unread:true,parents_unknown:true,husband_first_marriage_children:4,old_two_children_rejected:true,own_known_children:5,lifetime_total_proven:false,occupation_unknown:true,historical_no_military_material_possible_proven:false,prior_children_blank_proves_childless:false,own_Fredberg_surname_attested:false,Jansdotter_is_search_variant:true,own_life_after1910_unread:true,own_move_to_Sollentuna_proven:false,Klara_registration1911_is_own_physical_move_proven:false},po);
const end=fact(p,'marital_history','ending-unresolved',{last_joint_census:'1910-12-31',husband_death:'1925-08-06',husband_category:'Änkling eller frånskild',ending_between_recorded_anchors:true,ending_type:null,own_death_day:null,own_death_before1925_proven:false,own_divorce_proven:false},['A-4285',cs('C-0475')]);
const endBasis=['O-P-0336-C0475-death','F-P-0336-death_assessment-source-boundaries','E-death-P-0336'].map(id=>reuse(p,id,['A-4285']));
const grave=fact(p,'source_assessment','grave-absence-and-birth-gaps',{grave:'Sollentuna0107 012',listed_count:11,Johanna_listed:false,earliest_listed_burial:'1925-08-12',death_or_divorce_from_absence_proven:false,burial_elsewhere_from_absence_proven:false,earliest_listed_burial_proves_grave_never_previously_used:false,own_children_grave_birth_dates:['1890-09-05','1891-12-21','1894-04-13','1895-10-16','1902-11-28'],last_birth_gap:'7år1månad12dagar',earlier_birth_gaps:'cirka15–28månader',missing_children_proven:false,gap_cause:null,grave_birth_dates_primary:false,Edit1894_1895_conflict_resolved:false,independent_family_witnesses:false},['A-7924',cs('C-0945')],'TRANSCRIBED','Bevarad frånvaro och datumjämförelse, ingen ny slutsats om gravens fulla historia eller livsslut.');
const children={};for(const id of ['P-0489','P-0490','P-0491','P-0492','P-0493']){children[id]=relation(p,p.person,id,'parent',po,'recorded_parent',id==='P-0493'?'TRANSCRIBED':'CORROBORATED');relationRow(p,id,[children[id],family,grave],'Riktad barnrelation; senare gravdatum och1894/1895konflikt hålls skilda.');}
relationRow(p,'P-0336',[spouse,...marriage,end,correction],'Samma make och vigsel, inget nytt döds-/skilsmässodatum.');
for(const id of ['P-0395','P-0287']){const f=fact(p,'family_context',`stepchild-${id}`,{person:id,relation:'styvbarn',father:'P-0336',mother:'P-0337',from_marriage:'1888-12-08'},po);relationRow(p,id,[f,family],'Styvförhållande, ingen föräldralänk till Johanna.');}
assertion(p,'A-2253',[...bride,...birth,correction],'Uppgiven exakt födelsedag; Skånela finns också redan i vigselakten.');assertion(p,'A-2254',[...bride,extra,...marriage,...arrival,spouse],'Gemensam originalvigsel och redan utvunna egna brudfält.');assertion(p,'A-2998',[...census1910,...Object.values(children),family],'1910familj med fem egna barn.');assertion(p,'A-3086',[...census1900,family,correction],'1900familj med Frida som styvbarn.');assertion(p,'A-4285',[end,...endBasis],'Makens kategori, inte hennes dödsdatum.');assertion(p,'A-7924',[grave,end],'Elva poster utan Johanna och födelseintervall; bevarade begränsningar.');save(p);
