import{person,core,fact,event,relation,reuse,assertion,relationRow,save,origins,exact,units,section,src,cs,db}from'./genealogy2-persons08-combined.mjs';
const p=person('P-0394','Hela akten/profilen inklusive äldre och sena bedömningar genomlästa; C0469/0470 med samtliga tillägg och C0593/0594:s identitetsgräns genomlästa. Fyra livshändelser, tolv dopvittnen och namnlös dödfödd tvilling återbrukas från föräldrakohorten. Ingen ny arkivläsning, dödsorsak, släktinferens eller PK-uppgradering.');
const po=[origins(p.person,'person',1,Math.max(...units(p.person,'person').map(u=>u.end_line)))];
core(p,[section(p,'Identitet')],'Avgränsad identitet via samma far/hemvist och födelse-/döddatum.');
const birth=src(p,'C-0470','tvillingklamrad','C0470-birth','Märtha Brita','',{birth:'1856-02-20',baptism:'1856-02-23',father:'Henrik Henriksson',father_title:'inhysesmannen',mother:'Margaretha Charlotta Sjölin',mother_age:30,twin_brace:'Tvillingar',following_column:'16/3[?]',column_heading_unresolved:true,officiant_name:null},['A-2234','A-4337'],'Ingen separat råroll utvunnen; okänd kolumnrubrik. Inget hälsotillstånd härlett från avsaknad av nöddopsnot.');
const death=src(p,'C-0470','döda1856','C0470-death','Märtha','dotter',{death:'1856-03-02',burial:'1856-03-09',age:'11 dagar',father:'Henrik Henriksson',father_title:'inhysesmannen',father_home:'Sjöberg',death_cause:''},['A-2234','A-7923'],'Andranamnet saknas; fader/hemvist/datum identifierar henne. Tom dödsorsak är inget diagnosbelägg.');
const home=src(p,'C-0469','','C0469-own','Märtha Brita','',{birth:'1856-02-20',death:'1856-03-02',household_head:'Henrik Henriksson',home:'Sjöberg',folio:116},['A-2234'],'Föräldrarnas senare överföring till54 är inte en flytt för barnet som dog1856.');
const events=[['birth','1856-02-20'],['baptism','1856-02-23'],['death','1856-03-02'],['burial','1856-03-09']].flatMap(([k,d])=>event(p,k,exact(d),['A-2234'],'Samma redan införda barnhändelse; inga föräldrahändelser dupliceras.'));
const twin=['M-C0470-stillborn-boy','O-C0470-stillborn-boy'].map(id=>reuse(p,id,['A-4337']));
const w=db.prepare("select id from object where id like '%C0470-witness-%' or id like 'EP-C0470-%' or id in ('ID-C0470-Jonas','ID-C0470-Cecilia') order by id").all().map(({id})=>reuse(p,id,['A-7923']));
const family=reuse(p,'F-P-0338-family_context-children-and-witnesses',['A-4337','A-7923']);
const age=fact(p,'source_assessment','age-and-identity',{elapsed_days:11,reported_days:11,leap_year:1856,independent_birth_evidence:false,comparison_people:['P-0379','P-0380'],comparison_reported_offset_days:-1,parish_wide_rule_proven:false,comparison_only_within_same_parish_absolute_rule_proven:false,death_name:'Märtha',birth_name:'Märtha Brita',identity_basis:['far','hemvist','datum'],witness_count:12,witness_groups:6,largest_group_claim_scope:'programmets då granskade material'},['A-7923',cs('C-0438'),cs('C-0470')],'CORROBORATED','Observerad aritmetisk skillnad bevaras; en/två poster bevisar inget generellt församlingsbruk. Åldern kan vara räknad ur samma födelseuppgift.');
const residence=fact(p,'residence','infant',{parents_home:'Sjöberg, Ljustorp',birth:'1856-02-20',death:'1856-03-02',exact_birth_building_proven:false,physical_death_site_proven:false,move_documented:false,no_move_ever_proven:false},po);
const limits=fact(p,'source_assessment','infant-limits',{surname_Henriksson_written_on_own_source:false,ordinary_baptism_proves_healthy:false,death_cause_unknown:true,twin_status_proves_death_cause:false,young_age_excludes_legal_economic_personal_family_mentions:false,younger_siblings_co_residence_proven:false,earlier_identity_review_irrevocable:false},po);
const parents=['P-0338','P-0339'].map(id=>relation(p,id,p.person,'parent',po));
const sibs=['P-0253','P-0366'].map(id=>relation(p,id,p.person,'sibling',po));
assertion(p,'A-2234',[...birth,...death,...home,...events,age,residence],'Fyra daterade händelser och råålder, med beroende och platsgräns.');
assertion(p,'A-4337',[...twin,family,...birth],'Namnlös dödfödd tvilling; inga dopdeltaganden, egen person eller diagnos skapas.');
assertion(p,'A-7923',[age,...w,...death,family],'Hela sammansatta sakuppgiften och dess metodgräns.');
for(const[i,id]of ['P-0338','P-0339'].entries())relationRow(p,id,[parents[i],...birth,residence],'Samma redan införda riktade föräldralänk.');
relationRow(p,'gossebarn',[...twin,family],'Namnlös källperson återbrukas; inget nytt P-id.');
for(const[i,id]of ['P-0253','P-0366'].entries())relationRow(p,id,[sibs[i],limits],'Yngre syskon; inget gemensamt boende under hennes elva dagar.');
relationRow(p,'tolv faddrar',[...w,family],'Tolv vittnesroller vid hennes eget dop; tre namnlösa hustrur är tre skilda omnämnanden.');
p.pending.push({origin:section(p,'Hälsa och död'),question:'C0470:s smala kolumn efter dopdagen lyder16/3[?] men rubriken är inte säkert bestämd; ingen kyrktagningshändelse eller annan datering härleds.'});
save(p);
