import json,hashlib,datetime,re
from pathlib import Path
b=Path('evaluations/T-0832'); out=b/'independent'
read=lambda p:json.loads((b/p).read_text())
scan=read('independent/independent-semantic-scan-full-v1.json')
rows=scan['matches']+read('independent/independent-semantic-supplement-v1.json')+read('preparation/actual-version-graph-current-closure-input-v1.json')['objects']
rows += [read('independent/C0660-current-record-v1.json')]
D={x['revision']['object_id']:x for x in rows}
groups=[]
def group(code,ids,fields,decision,authority,disposition='AMEND_NARROWLY'):
 ids=list(dict.fromkeys(ids)); missing=[i for i in ids if i not in D]
 assert not missing,(code,missing)
 groups.append(dict(group=code,disposition=disposition,fields=fields,source_bound_decision=decision,authority=authority,targets=[dict(object_id=i,current_revision=D[i]['revision']['id'],full_current_native=D[i]) for i in ids]))
N='original-first-two-v2 + primary/full-record-extraction-v3'
A='AUDIT-T0110-C-0457@1 full accepted extraction, no image reread'
group('G01_C0456_own_mother', ['R-237a94ab0d124e6adec2a7be','M-C0456-Anna-Stina','O-P-0272-C0456-own','READ-e7a5012e65e014417fc74aad'],['record caveat/provenance','mention.role_literal/caveat','observation.value_json/value_literal','READ caveat'], 'Preserve record arrays and old daughter-row4 accepted extraction. Add exact mother row2 full fields: h.,44 4/12, Indal ditto, marriage ditto63 2/10,v, all own annual and other tested blank fields, no physical-continuity inference. Correct only own-mother unread scope. Existing READ body about non-exhaustive children/dependence stays true. Full new audit/transcription required, with source hash and headers; no new family identities.',N)
group('G02_C0658_full_post', ['R-cb27515d61b6f4077a013394','TR-ac20726383ee749fc39971ea','READ-eaf7343df53b81fe7bcf81d8','M-C0658-Nils-Petter','O-P-0271-C0658-father','ID-P-0349-C0658-birth','O-P-0349-C0658-birth'],['full source record','text/reading_note/body/caveat','name_literal/role_literal','value_json/value_literal religious fields/parent ages'], 'Full post46: male live legitimate, Nov12, Jonas Alfred Conrad8de barnet; father Nils Petter Pehrsson[Persson?],Torpare,Högsjö,bapt.[ist?],46; mother Anna Stina Strandlund,17de året gifta,baptister,reported36,gift mark. Preserve tested blanks incl noble and examined-attendant columns. No own odöpt: preceding post45 only; C0659 own odöpt remains source-specific. Flag religious_notes_in_parents_column_fully_extracted true with tested terminal reservation. Add exact mother mention/observation/identity to existing P0272 if absent, no new person/edge. Preserve complete source chain/SCB dependence. Historical48-post reading not claimed anew; current exact post only.',N)
group('G03_C0457_stale_record_metadata', ['S-0360','R-b3e23944d836bea3dfc27e8a','TR-400ad719c9e54ab7655bafc9','READ-d9566a4c0a7eaf36b4e6d7e1'] if 'READ-d9566a4c0a7eaf36b4e6d7e1' in D else ['S-0360','R-b3e23944d836bea3dfc27e8a','TR-400ad719c9e54ab7655bafc9']+ [i for i in D if i.startswith('READ-d956')],['source.description','record.caveat','transcription.reading_note/caveat','READ body/caveat'], 'Current raw C0457 AnnaStina4Dec1844 and Jonas12Nov1880 already accepted T0110; old7/22 in current source/record/READ/TR metadata must be explicitly superseded, not erased from history. C0254/C0349 actual older7 and C0654 older22 remain. Source title/volume years need no gratuitous normalization. Metadata amendment is accepted reuse, not a new original read.',A)
group('G04_C0457_reused_full_rows',[i for i in D if i.startswith('O-') and 'C0457' in i]+['M-C0457-Nils-Petter','M-C0457-Anna-Stina'],['own source-field JSON/literal','typed extraction flags','raw role and exact own reservation','caveat/rationale'], 'Reuse complete accepted six-person audit individually: P0271 Torpare/raw dates, loose nondate deathmark/G.b.130; P0272 H:u/4Dec/dittos/blankright; P0345 D:r/crossed/Timrå no4 1900-02-10, remaining annotations extracted true; P0346 own frejd/military upps...? Fri...96[?] tested reservation, not unexamined and not certain service; P0349 son/12Nov with own blanks; P0385 son/12/4[?] source reservation while accepted own birth unchanged, other_own_columns tested not unextracted. Each own annual blanks individually, not imported from another row. No side gate/fullcontract upgrade, no C0456 side-row closure.',A)
group('G05_P0272_current_partial_adoption', ['ASSESSMENT-P-0272','RESEARCH-P-0272-9d76f0343410','BIO-P-0272','THEME-P-0272-ID','THEME-P-0272-SAM','P-0272/Q-01','P-0272/Q-02','PATH-P-0272-KP-01','PATH-P-0272-KP-02','CONTRACT-P-0272-PK-04','CONTRACT-P-0272-PK-05'],['body/markdown','outcome where directly affected','caveat/current adoption'], 'Close only own C0456/C0457/C0658 relevant extraction, baptister in1880 source established; specific congregation, duration, motives behind1868oäkta/1888Ejvigda and biological father ofP0274 unresolved. Accept birth/parents/spouse/descent already supported. PK05 remains HELD pending actual C0660 maternal age debt; no provisional PASS. Full legacy contract/life remains unfinished. PK04 full network not automatically closed. Old statements are a single untouched historical suffix; updated current clause names remaining source/field. Q02 and KP01 must also reuse already accepted T0162 C0342 witnesses rather than resurrect that old debt.',N+'; C0660 current explicit debt; accepted T0162')
group('G06_P0272_date_key', ['KEY-P-0272-b040db51cb66'],['body/caveat'], 'Supersede six-sources-three-each claim. Accepted4Dec supported ownbirth/earlyhousehold plus correctedC0457; raw7 only C0254/C0349 remains. No vote counting or invented conflict.',A)
group('G07_P0271_source_notes',[i for i in ['F-P-0271-source_assessment-family-notes','RESEARCH-P-0271-9d76f0343410','BIO-P-0271','KEY-P-0271-87c7ed1a91f0','THEME-P-0271-SAM','P-0271/Q-01','P-0271/Q-02','PATH-P-0271-KP-01','PATH-P-0271-KP-02','CONTRACT-P-0271-PK-04','CONTRACT-P-0271-PK-05'] if i in D],['denomination typed fields','body/markdown/outcome','caveat'], 'C0658 parent notation establishes a source-reported Baptist identification1880, with father bapt.[ist?]/mother pluralbaptister. denomination:null cannot remain unqualified ignorance; add source/time/raw/limits. No namedcongregation, lifelongfaith, causal resolution, exactfive/totalchildren or inferredP0274paternity. C0457 full ownfields acceptedreuse; C0456 father fullrow notnewread. Preserve C0660 father age debt and remaining ownsource scopes; no father gate promotion. C0342 six witnesses already acceptedT0162, not activeunknown.',N+'; '+A+'; accepted T0162')
ids=[i for i,x in D.items() if 'P-0271' in i and 'Ingen religiös tillhörighet fastställs' in (x['revision'].get('caveat') or '')]
group('G08_P0271_shared_caveat',ids,['revision.caveat'], 'Prefix each exact current caveat with source-limited C0658 parent baptister identification1880, tested father terminal reservation, no named congregation/lifelong attribution/causality. Preserve entire old caveat as historical scope, incl acceptedT0162 witness correction. Only this shared now-overbroad negative clause requires change; no other native grade/key expansion.',N)
group('G09_P0349_fullparents_consequence',['KEY-P-0349-bf7e794a698b','THEME-P-0349-SAM','P-0349/Q-01','PATH-P-0349-KP-01','CONTRACT-P-0349-PK-05'],['body/outcome/caveat'], 'Religious parent notes C0658 now fulltested with glyph reservation; exact father/motherages and civil fields preserved. KP01 outcome and body both report bounded positive, not whole1880 reread; C0659 same chain/odöpt separate. PK05 retains EJ STYRKT for ownC0654 rad5 August1901 banns/military and other exact pending scopes, no son gate promotion. Q01 supported and new context not own creed.',N)
group('G10_P0349_late_date_scope',['KEY-P-0349-12a91c3f6e98','RESEARCH-P-0349-9d76f0343410','BIO-P-0349','ID-P-0349-C0457-hh'],['body/markdown/caveat'], 'Current blanket later22 must specify C0654; C0457 accepted raw12, earlier22there transcriptionerror. BIO already says that precisely later: retain correct fullbody where existing qualification sufficient; add only needed parent-C0658 source context. ID-P0349-C0457 caveat laterdeviation cannot mean ownpost; qualify. No normalizedbirth change.',A+'; '+N)
group('G11_Johan_minimal_context',['F-P-0273-household_membership-Hogsjo','KEY-P-0273-16c090b08ab3','P-0273/Q-01','BIO-P-0273'],['source_periods/continuation_after1880_unread and scoped new anchor','body/markdown/caveat'], 'C0456 needed adjacent row3 JohanPetter64 14/8 is minimal source-context anchor1882–91. continuation_after1880_unread false ONLY with explicit minimal anchor/otherownfieldsuntested; retain older18Aug as rawsource key and unresolved actualbirth/biologicalparents. Add this anchor to applicable gap/key/Q/BIO; no continuous residence, new person/parentedge/fullside review. Historical SEARCH-P0273 local18Aug remains untouched. Primary source concurrence received.',N+' primary same-source row3 concurrence')
group('G12_Hok_comparison',['P-0277/Q-01','PATH-P-0277-KP-04'],['Q body comparison','PATH outcome/body scope'], 'Qualify comparison: Indal C0658 explicit parents baptister; exactlyfive odöpta scope not established here, no independent proof or religion transfer to Hök. Hök own affiliation/motives remains open. Shared PATH untouched Hudiksvall missions/newresearch scope and EJ UNDERSÖKT for those sources; distinguish newlyread Indalparentrecord from untouched archiveprogramme.',N)
group('G13_existing_stronger_and_protected_retains',[i for i in D if i.startswith(('REL-parent-P-0272','REL-parent-P-0343-P-0272','REL-parent-P-0344-P-0272','REL-spouse-P-0271-P-0272'))]+['F-P-0272-birth_date_conflict-4-vs7','F-P-0349-birth_assessment-12-not22','IDENTITY-REVIEW-T0812-P0255','TREE-EFFECT-T0812-P0255','O-P-0255-C0456-own','AUDIT-T0812-C0456-full-own-post','TR-T0812-C0456-full-own-post','SEARCH-P-0273-Indal1864-local-date','O-P-0272-C459-mother','O-P-0385-C0457-child'][:-1],['all except exact separately approved source binding if later mandatory'], 'Preserve adultidentities, recorded parent nature/grades and exact OWNER45. Accepted4Dec/12Nov remain; daughterT0812 historical row4scope true. C0459 only accepted mother43/Högsjö/Ejvigda reused; childstatistical/(8)/dop debt remains T0218/T0219, no unobserved motherblank certification or invented specificmaternal debt. Historical negative pass untouched, no new negative. No blanket numericrebind approval.', 'accepted ownbirth/marriage/descent, T0110/T0812/OWNER; primary C0459 scope concurrence','RETAIN')
group('G14_C0660_gate_hold',['R-1b298271e291a92acce34ca7','TR-9c91122a69b02cfbb06b56eb','O-P-0346-C0660-birth','O-P-0272-C660-mother'],['record/transcription age-debt caveat','parent_age_field_fully_extracted','PK05 consequence'], 'Actual explicit parent-age/parentcolumn debt includes AnnaStina ownmaternal age, alreadyreliedon record. Hold PK05 until sufficient acceptedlaterfullpost or separatelyrootauthorized sourceunit. No originalread under fixed2scope. Adultidentity/descent stays accepted, no modelgap/owner demotion. Do not relabel this LIFE solely to pass.', 'full current C0660 objects/primary source decisionv1','HOLD')
files=['independent/original-first-two-v2.json','primary/full-record-extraction-v3.json','primary/source-decisions-v1.json','preparation/current-input-manifest-v1.json','independent/independent-semantic-scan-full-v1.json','independent/independent-semantic-supplement-v1.json','preparation/actual-version-graph-current-closure-input-v1.json']
report=dict(task='T-0832',review='independent source concurrence and current semantic consequence requirements, not package approval',created_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),baseline=dict(journal=507,pending=0,sha256='a77cd5669b32e9cb0225f750b636fd40290b712406d517a1c9435c509463f71f'),authorities=[dict(path=str(b/p),sha256=hashlib.sha256((b/p).read_bytes()).hexdigest()) for p in files],coverage=dict(current_heads_scanned=scan['current_count'],independent_hits=352,supplement=80,actual_mechanical_closure=143,closure_extra=30,originals_newly_read=2,external_fetches=0,third_image_reads=0),source_concurrence='CONCUR exact two fullpost readings and accepted C0457 reuse; mother Baptist notation source/time bounded; father terminal reserved. PK05 HELD actualC0660, PK11 await assetproof; no identity/tree PASS approved.',global_requirements=['Preserve fullold metadata/evidence/origins/assets/media arrayorder.','One current amendment followed by untouched prior wording; do not rewrite accepted datedhistory.','Each requested zero/multiple match or new numericreference goes to Astra before dependentwrites.','Actual final sourceop/pendingresolutionop/fullstage hashreview required; no canonical approval here.'],groups=groups,counts=dict(group_count=len(groups),target_occurrences=sum(len(g['targets']) for g in groups),unique_targets=len({t['object_id'] for g in groups for t in g['targets']})))
p=out/'source-concurrence-and-consequences-v1.json';p.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(p,hashlib.sha256(p.read_bytes()).hexdigest(),report['counts']);print([(g['group'],len(g['targets'])) for g in groups])
