import pathlib,json,hashlib,re,importlib.util,time,copy
R=pathlib.Path.cwd();D=R/'evaluations/T-0819';P=D/'preparation';start=time.monotonic();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.load(open(p))
def save(n,v):
 p=P/n;assert not p.exists();p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');return p
hp=R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py';sp=importlib.util.spec_from_file_location('h',hp);h=importlib.util.module_from_spec(sp);sp.loader.exec_module(h);main=R/'genealogy2/data/research.sqlite';b=load(P/'baseline-v1.json');assert sha(main)==b['main']['sha256'];c=h.conn(main);assert h.state(c)=={'journal_head':488,'pending':0}
# Full literal history/scope snapshots; no source interpretation or scope promotion.
N=P/'exact-task-and-norm-snapshots';N.mkdir();snapshotpaths=[]
for n in ['T-0819','T-0255','T-0237','T-0410','T-0217','T-0228']:
 p=N/(n+'.md');p.write_bytes((R/f'wotan/dev-log/{n}.md').read_bytes());snapshotpaths.append(p)
for n in ['AGENTS.md','wotan/README.md','PROJECT-CONTROL.md','NORTH-STAR.md','docs/research/person-contract.md','genealogy2/docs/working.md']:
 p=N/n.replace('/','__');p.write_bytes((R/n).read_bytes());snapshotpaths.append(p)
backlog=R/'wotan/backlog.json';p=P/'baseline-backlog-v1.json';p.write_bytes(backlog.read_bytes());snapshotpaths.append(p);q=load(p);assert q['next_id']==820;assert next(x for x in q['tasks']if x['id']=='T-0819')['status']=='ONGOING'
transferpath=R/'evaluations/T-0816/settled-fixed160-successor-transfer-v3.json';transfer=load(transferpath);actual_log=(N/'T-0819.md').read_text();blocks=[json.loads(x)for x in re.findall(r'```json\n(.*?)\n```',actual_log,re.S)];actual=next(x for x in blocks if 'fixed160'in x);assert actual==transfer;assert len(actual['fixed160'])==len({x['person']for x in actual['fixed160']})==160;assert len(actual['full_T0791_T0792_planning_appendices'])==4898;assert hashlib.sha256(actual['full_T0791_T0792_planning_appendices'].encode()).hexdigest()==actual['appendices_sha256'];allocation=load(R/'evaluations/T-0816/root-actual-allocation-v1.json');assert allocation['active_full160_and4898appendix_planning_owner']=='T-0819'
union=save('fixed160-lossless-current-owner-proof-v1.json',{'source_transfer_pin':{'path':str(transferpath.relative_to(R)),'sha256':sha(transferpath)},'full_T819_embedded_transfer_exact':True,'persons160_unique':True,'every_full_source_plan_and_historical_owner_retained':True,'full_previous_transfer_exact':'preserved_previous_transfer is preserved verbatim within immutable exact transfer','planning_appendix_characters':4898,'appendices_sha256':actual['appendices_sha256'],'historical_inner_owner_semantics':actual['old_owner_semantics'],'historical_proposed_owner_wording':'T0819 only after allocation is historical transfer wording; actual allocation proof and live ONGOING status establish current owner','current_outer_owner':'T-0819','current_postallocation_atom_ownership':actual['current_postallocation_atom_ownership'],'deeper130_not_newly_audited':True,'next_id_observed_not_reserved':820,'queue_mutation':False})
# Four actual accepted envelopes from completed tasks; historical prefix already accepted, no replay.
delta=[]
for seq in [485,486,487,488]:
 row=dict(c.execute('select *from operation_payload where sequence=?',(seq,)).fetchone());files=list((R/'genealogy2/journal').glob(f'{seq:09d}-*.json'));assert len(files)==1;receipt=load(files[0]);assert receipt['request']==json.loads(row['request_json'])and receipt['sequence']==seq and receipt['policy']==row['policy']and receipt['request']['id']==row['operation_id'];delta.append({'database_payload':row,'receipt':receipt,'pin':{'path':str(files[0].relative_to(R)),'sha256':sha(files[0])},'exact':True})
save('accepted-T0817-T0818-envelope-reconciliation-v1.json',{'state':h.state(c),'all_four_envelopes_exact':True,'accepted_prefix486_reused':'evaluations/T-0818/preparation/accepted-delta485-486-reconciliation-v1.json and root accepted all50 verification','actual488_all50_comparison':'evaluations/T-0818/actual-main-stage-comparison-v1.json','envelopes':delta})
# Whole actual current scopes and original bound bases of OWNER knowledge, without changing scope.
old=load(R/'evaluations/T-0817/preparation/protected-native-review-snapshot-v1.json')['current_OWNER45_fullnative'];owners=[];basis={}
for n in old:
 assert h.current(c,n['object_id'])==n['id'];cur=h.native(c,n['id']);assert cur==n;owners.append(cur)
 for e in cur['evidence']:
  raw=h.native(c,e['basis_revision_id']);basis[raw['id']]=raw
owner=save('current-OWNER45-and-direct-bases-v1.json',{'OWNER45_full_raw_native':owners,'direct_bound_bases':list(basis.values()),'source_PC_exact_decisions_reuse':'evaluations/T-0817/preparation/locked-input-manifest-v2.json; current full PROJECT-CONTROL snapshot included','same_current_OWNER45_exact':True,'scope_extension':False})
# Raw native full focal objects, seven criteria and exact review axes; no new research ranking.
front=[];relations={}
for pid in ['P-0337','P-0042','P-0043','P-0336']:
 pack=load(P/'native'/f'{pid}.json');raw=[h.native(c,n['id'])for n in pack['current']];pk=[n for n in raw if n['object_id']in [f'CONTRACT-{pid}-PK-{j:02d}'for j in [1,2,5,7,9,11,12]]];assert len(pk)==7
 idx=next(x for x in load(P/'current-person-index-v1.json')['persons']if x['person_id']==pid);front.append({'person':pid,'full_current_raw_native':raw,'seven_identity_criteria_fullnative':pk,'current_review_axes':idx['axes'],'full_current_person_file':f'current-full/{pid}.json','direct_current_stronger_support_file':'native-support-versions-v1.json','current_object_count':len(raw)})
 for n in raw:
  if n['kind']=='relation':relations[n['object_id']]=n
f=save('four-current-front-full-native-and-criterion-index-v1.json',{'front':front,'relation_fullnative':list(relations.values()),'routing_not_strategy_or_source_grading':True})
reuse=[transferpath,R/'evaluations/T-0816/root-actual-allocation-v1.json',R/'evaluations/T-0817/root-actual-final-verification-v1.json',R/'evaluations/T-0817/actual-main-stage-comparison-v1.json',R/'evaluations/T-0818/root-actual-final-verification-v1.json',R/'evaluations/T-0818/actual-main-stage-comparison-v1.json',R/'evaluations/T-0818/implementation/stage488-sequence-v1/inventory-full.json',R/'evaluations/T-0818/implementation/stage488-sequence-v1/P-0269-pedigree.json',R/'evaluations/T-0818/implementation/stage488-sequence-v1/P-0270-pedigree.json',R/'evaluations/T-0817/preparation/locked-input-manifest-v2.json',hp,D/'root-start-baseline-v1.json',D/'collect_usage.py']
for task in ['T-0817','T-0818']:
 reuse.extend((R/f'evaluations/{task}').glob('*final*source*gate*.json'))
result=save('input-preparation-result-v1.json',{'state':h.state(c),'main_unchanged_sha256':sha(main),'front_people':4,'seven_criteria_each':True,'relations':len(relations),'OWNER45':45,'OWNER_direct_bases':len(basis),'fixed160_exact':True,'full4898_appendix_exact':True,'current_outer_owner':'T-0819','old_task_records_order_preserved':True,'next_id_observed':820,'originals':0,'native_writes':0,'source_decisions':0,'elapsed_seconds':time.monotonic()-start,'capture_seconds':load(P/'capture-result-v1.json')['elapsed_seconds'],'usage_collector':'UNRUN newT0819floor; priorT818usage not recaptured'})
paths=[p for p in P.rglob('*')if p.is_file()and '__pycache__'not in str(p)]+reuse+[R[x['pin']['path']]for x in delta];assert sha(main)==b['main']['sha256'];pins=[{'path':str(p.relative_to(R)),'sha256':sha(p),'bytes':p.stat().st_size}for p in sorted(set(paths))];m={'task':'T-0819','state':h.state(c),'main_sha256':sha(main),'scope':'Four exact current front persons, lossless fixed160/source_plan/4898appendix and relevant preserved old owner scopes; no130newaudit/30redo/source or queue changes','front_index':str(f.relative_to(R)),'union_proof':str(union.relative_to(R)),'OWNER_scope':str(owner.relative_to(R)),'pins':pins,'source_decisions':0,'canonical_or_queue_writes':0};out=P/'locked-input-manifest-v1.json';assert not out.exists();out.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'manifest_sha256':sha(out),'pins':len(pins),'relations':len(relations),'OWNER_bases':len(basis),'elapsed':time.monotonic()-start}))
