import pathlib,json,hashlib,copy,time
R=pathlib.Path.cwd();E=R/'evaluations/T-0819';D=E/'candidate-v1';D.mkdir(exist_ok=True);start=time.monotonic();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.load(open(p))
def text(n,v):
 p=D/n;assert not p.exists();p.write_text(v);return p
def save(n,v):return text(n,json.dumps(v,ensure_ascii=False,indent=2)+'\n')
inputs={'evaluations/T-0819/settled-source-planning-design-v2.json':'6668fde9c734723450c35f9d27968d95d00076c42a78f29d42f9ab1182829242','evaluations/T-0819/settled-fixed160-successor-transfer-v2.json':'633180dbd8248c826d832cd61cbe770d947368d523a07eeef764bfebb937140f','evaluations/T-0819/independent-settled-source-design-gate-v1.json':'292104734b1ae6a13044cecfc4d96a9516ab339576da06af2493d08d9ba38f60'}
for p,h in inputs.items():assert sha(R/p)==h
spec=read(R/next(iter(inputs)));tr=read(R/list(inputs)[1]);prev=read(R/tr['previous_transfer']['path']);assert sha(R/tr['previous_transfer']['path'])==tr['previous_transfer']['sha256'];assert tr['preserved_previous_transfer']==prev;assert tr['fixed160']==prev['fixed160'];assert len(tr['fixed160'])==len({r['person']for r in tr['fixed160']})==160;appendix=tr['full_T0791_T0792_planning_appendices'];assert appendix==prev['full_T0791_T0792_planning_appendices']and len(appendix)==4898;assert hashlib.sha256(appendix.encode()).hexdigest()==tr['appendices_sha256']
base=read(R/'wotan/backlog.json');assert base['next_id']==820;assert next(t for t in base['tasks']if t['id']=='T-0819')['status']=='ONGOING';(D/'baseline-backlog.json').write_bytes((R/'wotan/backlog.json').read_bytes());new=[];logs=[]
for t in spec['tasks']:
 assert t['status']=='READY'and t['after']==[];n={k:copy.deepcopy(t[k])for k in ['id','status','size','priority','priority_basis','after']};n['summary']=t['title'];n['note']=t['mandate']+' Se wotan/dev-log/'+t['id']+'.md; inget utförandemandat genom allocation.';new.append(n)
 parts=['# '+t['id']+' — '+t['title'],'','- Size: '+t['size'],'- Status: READY','- Phase: —','- Priority: '+t['priority'],'- After: []','','## Omfång och mandat','',t['mandate'],'','T-0819 har originaltak0 och nativeändringar0. Kandidat/allocation medger inget utförande.']
 for key,label in [('source_scope','Exakt källbunden avgränsning'),('scope','Exakt checkpointomfång'),('excluded','Utanför omfånget'),('trigger','Verkligt återstartvillkor'),('transfer','Aktuell transferreferens')]:
  if key in t:
   v=t[key];parts+=['','## '+label,'',v if isinstance(v,str)else json.dumps(v,ensure_ascii=False,indent=2)]
 parts+=['','## Acceptance Criteria','']+[f'{i+1}. {v}'for i,v in enumerate(t['acceptance_criteria'])]
 if t['id']=='T-0820':parts+=['','## Full förlustfri gammal scope/AC och exakt partition','','```json',json.dumps(spec['lossless_partition'],ensure_ascii=False,indent=2),'```']
 if t['id']=='T-0821':parts+=['','## Full förlustfri fast160/source_plan-transfer','','Historiska innerägare och full tidigare transfer bevaras exakt; aktuell ytterägare kräver faktisk rootallocation och anges separat.','','```json',json.dumps(tr,ensure_ascii=False,indent=2),'```','','## Oförkortad historisk T0791/T0792-planeringsappendix','',appendix,'','## Ändligt nära livsbildsbeslut','','```json',json.dumps(spec['life_decision'],ensure_ascii=False,indent=2),'```']
 parts+=['','## Exakt bokstavlig SOURCE-design','','```json',json.dumps(t,ensure_ascii=False,indent=2),'```','','## Hashbundna avgjorda ingångar','']+[f'- {p} SHA256 {h}'for p,h in inputs.items()]
 parts+=['','## Återupptagning — literal kandidat','','2026-10-08: kandidat endast. Separata literal SOURCE-grindar och faktisk rootallocation återstår. READY ger inget utförandemandat. Nästa ej utförda steg är rootverifierad allocation; faktisk aktuell allocation/checkpoint skall appendas av root efter allokering. T0817/T0818/T0819beställningen slutar med T0819; ingen fjärde exekvering.']
 p=text(t['id']+'.md','\n'.join(parts)+'\n');logs.append({'task':t['id'],'path':str(p.relative_to(R)),'sha256':sha(p)})
alloc=copy.deepcopy(base);at=next(i for i,t in enumerate(base['tasks'])if t['id']=='T-0819')+1;assert base['tasks'][at]['id']=='T-0217';alloc['tasks'][at:at]=new;alloc['next_id']=822;save('backlog.json',alloc);assert [t for t in alloc['tasks']if t['id']not in ['T-0820','T-0821']]==base['tasks'];assert len({t['id']for t in alloc['tasks']})==len(alloc['tasks']);assert appendix in(D/'T-0821.md').read_text();assert json.dumps(tr,ensure_ascii=False,indent=2)in(D/'T-0821.md').read_text()
partition=spec['lossless_partition'];oldpath=R/'wotan/dev-log/T-0255.md';old=oldpath.read_bytes();assert sha(oldpath)==partition['full_old_scope_snapshot']['sha256'];assert old.decode()==partition['full_old_scope_text'];(D/'T-0255-preimage.md').write_bytes(old);append=partition['append_only_text'];(D/'T-0255.md').write_bytes(old+append.encode());assert(D/'T-0255.md').read_bytes()[:len(old)]==old;assert(D/'T-0255.md').read_bytes()[len(old):].decode()==append
text('PCR-draft.md',spec['PCR_draft']+'\n');text('allocation-checkpoint-proposals.md','\n\n'.join([f'## {t["id"]}: efter faktisk rootallocation\n\nExakt avgjort paket och båda literal SOURCE-grindar har allokerats av root; se faktisk allocationreceipt. Uppgiften är READY, inte startad. Allocation ger inget utförandemandat. Nästa ej utförda steg: '+('framtida beställd start av enda C0800-atomen med actual current/media/source-lock och separat SOURCE-grind före eventuell originalåtkomst.'if t['id']=='T-0820'else'aktiv full160/source_plan/4898appendix-checkpoint vid första accepterade resultat ELLER konkret hinder från enda T0820, före annan passage/djupval; T0217 först och T0228 sedan prövas enligt exakta avgjorda scope/AC.')for t in spec['tasks']])+'\n')
proof={'passed':True,'old_task_count':len(base['tasks']),'new_task_count':len(alloc['tasks']),'all_old_record_fields_and_relative_order_exact':True,'T0819_ONGOING_fullrecord_preserved':True,'insert_after':'T-0819','insert_before':'T-0217','new_order':['T-0820','T-0821'],'next_id_before':820,'next_id_after':822,'all_new_after_empty':True,'full160_source_plan_exact':True,'full_previous_transfer_exact':True,'full4898appendix_exact':True,'historical_innerowner_and_new_outer_overlay_separate':True,'T0255_old_sha256':sha(oldpath),'T0255_candidate_sha256':sha(D/'T-0255.md'),'T0255_prefix_bytes':len(old),'T0255_source_append_exact':True,'node_links_sha256':sha(R/'wotan/node-links.json'),'main_sha256':sha(R/'genealogy2/data/research.sqlite'),'native_changes':0,'originals_opened':0,'live_queue_writes':0,'elapsed_seconds':time.monotonic()-start};save('preservation-proof.json',proof)
save('individual-consequence-table.json',{'old_records':[{'task':t['id'],'disposition':'RETAIN_FULL_RECORD_AND_RELATIVE_ORDER','before':t,'after':t}for t in base['tasks']],'new_records':[{'task':n['id'],'disposition':'CREATE_BOUNDED_READY_NO_EXECUTION_MANDATE','after':n,'source_design':spec['tasks'][i],'log':logs[i]}for i,n in enumerate(new)],'old_log_append':{'task':'T-0255','full_old_scope':partition['full_old_scope_text'],'exact_append':append,'source_partition':partition,'prefix_sha256':sha(oldpath)},'fixed160_transfer':{'disposition':'FULL_LOSSLESS_TRANSFER_ONLY_AFTER_ROOT_ALLOCATION','source_pin':spec['whole160_transfer'],'whole_previous_transfer_exact':True,'full4898appendix_exact':True,'current_outer_owner_after_allocation':'T-0821'},'native_changes':0,'originals_opened':0});print(json.dumps({'old':len(base['tasks']),'new':len(alloc['tasks']),'elapsed':time.monotonic()-start}))
