import pathlib,json,hashlib
B=pathlib.Path(__file__).resolve().parent;R=B.parents[1];s=json.loads((B/'source-review/C-1060-source-v1.json').read_text());a=json.loads((B/'source-review/C-1060-source-amendment-v2.json').read_text());rid='R-beaee87a400dd929753d190d';tr='TR-T0778-C1060-fullfields';au='AUDIT-T0778-C1060';fields=s['fields']
for f in fields:
 if f['field']=='D3':f.update(raw='\n'.join(a['D3']['raw_lines']),state=a['D3']['state'],note=a['D3']['interpretation']+' '+a['D3']['older_support'])
 if f['field']=='D4':f.update(raw=a['D4']['raw'],state=a['D4']['state'],note=a['D4']['meaning'])
 if f['field']=='B15':f['note']+=' '+a['B15_precision']
assert len(fields)==28
limits='Only Lerbo1884post33, ownheaders/28fields/margins. Raw(1) functionunestablished; fourwitnesslines,no witnessidentity/kinshipinference. D4abs[?]/absl[?] nonblankbutundated, no ritualperformance/dateproved. Stronger acceptedC1063Erikslund retained; no cottageownership/physicaldelivery/homecoming inference. Unnamedfather neitherprovesnorexcludesKarlFredrik. Same recordchain is not independentevidence.'
def ev(o,v,n):return {'object':o,'version':v,'role':'supports','note':n}
bases=[ev('S-0016',2,'Explicit source metadata amendment, pending exact spec; no blanket otherrecordrebind.'),ev(rid,2,'Same ownpost33 with exact nativefullasset preservation amendment, pending exactspec.')];changes=[]
def add(oid,kind,data,es,caveat):changes.append({'id':oid,'kind':kind,'expectedVersion':None,'data':data,'origins':[],'evidence':es,'disposition':'recorded','evidenceStatus':None,'rationale':'T-0778 AC2–4: mechanical implementation of settled fullsource reading/amendment and bounded ownsource adoption.','caveat':caveat})
add(tr,'transcription',{'record_id':rid,'text':json.dumps({'scope':s['scope'],'headers':s['headers'],'numbered_fields':fields,'margin':'No ownoutermargin note;B23/D5blank, D4abbreviation asreserved.'},ensure_ascii=False,indent=2),'reading_note':limits+' Currentfullreading supersedes historicalTR-988baba0bb41dada7834f9fa@1 for fullfield/witness/D4/(1) claims; historical version preserved.'},bases,limits)
add(au,'assessment',{'subject_id':rid,'criteria':'original_revision/1','outcome':'reviewed_with_limits','body':json.dumps({'coverage':a['coverage'],'source_bound_decisions':s['primary_conclusions'],'corrected_witness_extent':a['D3'],'corrected_D4':a['D4'],'stronger_support':s['stronger_support'],'initial_completeness_omission':a['discovery']},ensure_ascii=False,indent=2)},bases+[ev(tr,1,'Full28fields including fourwitnesslines andreservedD4.')],limits)
for pid,own in [('P-0044','Own SvenEdvinSeverus, Oct22birth/Nov2baptism1884; explicitm/oäkta1, raw(1)reserved; fourwitnesslines, nofatheridentified.'),('P-0043','Own Larsd:rCharlottaWilhelmina, dotter Ericsland[?]/Ericslund[?]; mothericke gift1,17; exraw; D4reservedundated. AcceptedErikslund and1884-04-25registration remain fromstrongerC1063, not newphysicalhomecoming.')]:
 es=bases+[ev(tr,1,'Own numberedpost33 fields.'),ev(au,1,'Sourcebound interpretation/limits.')]
 if pid=='P-0043':es +=[ev('O-P-0043-A-3969-corrected_place',1,'Existing acceptedC1063identifiedErikslund; rawbirthplace reserved.'),ev('O-P-0043-A-3972-registered_arrival',1,'Existing registeredarrival1884-04-25, not physicalhomecoming.')]
 add('ADOPT-T0778-C1060-'+pid,'assessment',{'subject_id':pid,'criteria':'bounded_source_adoption/1','outcome':'reviewed_with_limits','body':own},es,limits)
for oid,name,role,caveat in [('M-T0778-C1060-witness3','C.[?] J. Johansson','dr[?]; dopvittne','Raw firstinitial/prefix reserved; no identitylink; VallaSköldingeS:n distributionbetweenadditionalwitnesses notestablished.'),('M-T0778-C1060-witness4','Hilda Lovisa Nilsson','dottr.; dopvittne','Dottr. is rawrole, no namedparentrelation; no identitylink; VallaSköldingeS:n distributionbetweenadditionalwitnesses notestablished.')]:
 add(oid,'mention',{'record_id':rid,'name_literal':name,'role_literal':role},bases+[ev(tr,1,'OwnD3third/fourthwitnesslines.')],caveat)
x={'id':'T-0778/C1060-source-candidate-v1','actor':'Codex Sol mechanical implementation of settled Astra decisions','reason':'T-0778 AC2–4:28fullfields/fourwitnesslines/rawritualreservation/twoboundedadoptions/twounlinkedsource-onlymentions. Await exactsource/recordmetadata revisions and independentreview.','dependencyReviewVersion':2,'changes':changes};(B/'C-1060-source-candidate-operation-v1.json').write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');(B/'C-1060-first-source-candidate-freeze-v1.json').write_text(json.dumps({'task':'T-0778','status':'DRAFT_NOT_TESTED_REQUIRES_EXACT_S2_R2_SPECS','files':[{'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in [B/'source-review/C-1060-source-v1.json',B/'source-review/C-1060-source-amendment-v2.json',B/'C-1060-source-candidate-operation-v1.json']]},indent=2)+'\n');print('6newsourceobjects draft')
