import pathlib,json,sqlite3,hashlib,datetime
B=pathlib.Path(__file__).resolve().parent;R=B.parents[1];names=['C1060-metadata-operation-v1.json','C-1060-source-candidate-operation-v2.json','C1060-consequences-operation-v2.json','group-copy-v4-candidate-operation-v2.json','group-copy-v6-operation-v1.json','raw-place-v7-operation-v2.json','maternal-boundary-v8-operation-v1.json','C1060-final-individual-resolution-operation-v1.json'];ops=[];states=[93,93,156,168,168,168,168,0]
for i,n in enumerate(names,1):
 p=B/n;ops.append({'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'expected_before':{'journal_head':269+i-1,'pending':0 if i==1 else states[i-2]},'expected_after':{'journal_head':269+i,'pending':states[i-1]}})
c=sqlite3.connect('file:'+str(B/'clone/c1060-final-v3.sqlite')+'?mode=ro',uri=True);state={'journal_head':c.execute('select max(sequence) from operation_payload').fetchone()[0],'pending':c.execute('select count(*) from review_request q left join review_resolution r on q.id=r.request_id where r.request_id is null').fetchone()[0]};assert state=={'journal_head':277,'pending':0}
used=['C-1060-source-v1.json','C-1060-source-amendment-v2.json','C-1060-current-revisions-v1.json','C-1060-and-group-copy-amendment-v3.json','C-1060-individual-retains-v1.json','current-semantic-copy-amendment-v4.json','current-copy-pending-amendment-v6.json','raw-place-current-amendment-v7.json','maternal-biography-boundary-amendment-v8.json','BIO-C0035-rebind-amendment-v9.json','pending168-individual-dispositions-final-v2.json','supplemental130-individual-dispositions-v1.json'];files=[B/'source-review'/n for n in used]+[B/n for n in ['root-pre-source-lock-v1.json','C-1060-stage-media-v1.json','originals/C-1060-info.json','C1060-final-pending-release-input-v5.json','C1060-final-full-stage-check-v1.json','C1060-final-protected-invariants-v1.json','C1060-final-verify-v1.json','C1060-final-verify-assets-v1.json','C1060-final-verify-source-v1.json','clone/c1060-final-v3.sqlite','C0035-empty-media-preservation-correction-v3.json','C0035-record-asset-preservation-amendment-v2.json','raw-place-v7-stale-support-attempt-v1.json','C1060-source-artifact-state-cleanup-amendment-v2.json','group-copy-v4-approved-support-amendment-v2.json','C1060-final-all-event-consequence-table-v1.json','C-1060-individual-consequence-table-v3.json','group-copy-v4-consequence-table-v3.json','group-copy-v6-consequence-table-v1.json','maternal-boundary-v8-consequence-table-v1.json']]
asset=json.loads((B/'C-1060-stage-media-v1.json').read_text());files.append(R/asset['storagePath'])
pins=[{'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in files]
x={'task':'T-0778','frozen_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':'C-1060 plus individually settled current G001 semantic copies; C1047 EXCLUDED, full G001 closure NOT APPROVED','status':'PENDING_INDEPENDENT_EXACT_HASH_PASS','baseline_state':{'journal_head':269,'pending':0},'final_state':state,'stage':str((B/'clone/c1060-final-v3.sqlite').relative_to(R)),'operations':ops,'pinned_artifacts':pins,'native_unique_objects':47,'new_objects':6,'existing_objects_revised':41,'change_events':51,'revision_events':45,'bounded_adoptions_new':2,'new_unlinked_witness_mentions':2,'individual_resolutions':168,'unchanged_baseline_current_objects':44133,'coverage':'One fullpost33,28 numberedfields/fourwitnesslines; previously acceptedgroupreading reused, noC1047originalreading','technical_pass_is_not_source_approval':True};(B/'C1060-partial-final-package-freeze-v1.json').write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');print('8ops',len(pins),'pins stage',state)
