import json,sqlite3,pathlib,hashlib,datetime,re
base=pathlib.Path('evaluations/T-0797')
db=sqlite3.connect('genealogy2/data/research.sqlite');db.row_factory=sqlite3.Row
def h(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def digest(x):return hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True).encode()).hexdigest()
def write(n,x):(base/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def ev(r,n='T0797 bounded metadata only',role='supports'):return {'object':r.rsplit('@',1)[0],'version':int(r.rsplit('@',1)[1]),'role':role,'note':n}
def new(i,k,d,e=[]):return {'id':i,'kind':k,'expectedVersion':None,'data':d,'disposition':'recorded','evidenceStatus':None,'rationale':'T-0797 AC1–3 bounded metadata-only routing, no person facts or review-grade change.','caveat':'Metadata existence/coverage/access only; no personal content or whole-source absence.','origins':[],'evidence':e}
heads=[dict(r) for r in db.execute('select * from current_revision order by object_id')]
# Large convenience head copy stays outside Git.
pathlib.Path('/private/tmp/T0797-baseline-heads.json').write_text(json.dumps(heads))
write('baseline-proof.json',{'db_sha256':h('genealogy2/data/research.sqlite'),'head':499,'heads_semantic_sha256':digest(heads),'pending':db.execute('select count(*) from pending_review').fetchone()[0]})
assert db.execute('select max(sequence) from operation_payload').fetchone()[0]==499
owner=[]
for r in heads:
 if r['evidence_status']=='OWNER_CONFIRMED' and any(v in r['object_id'] for v in ['P0004-paternal','paternal-grandparents','P-0005-P-0004']):
  owner.append({'head':r,'data':dict(db.execute('select * from '+r['kind']+' where revision_id=?',(r['id'],)).fetchone())})
write('owner-current.json',owner)
write('reuse-ledger.json',{'accepted':'ownHyltinge13/r16; T0788Flen744; T0789own1945/46; T0676scope20 new own gravecapture reused without rereading originals. Full current person read from /private/tmp/T0797-maj-before.json (root) and /tmp/t0797-p0007.json (Sol).','C0924':{'source_version':'S-0727@1','citation_path':'genealogy/citations/C-0924-katalogprov-yrkeskallor-djup-3-2026-09-06.md','citation_sha256':h('genealogy/citations/C-0924-katalogprov-yrkeskallor-djup-3-2026-09-06.md'),'performed_date':'2026-09-06','exact_time':'UNKNOWN','provider_version':'UNKNOWN','raw_response_copy':'UNKNOWN/not preserved by historical receipt; frozen citation is report, not raw response','reuse':'Scania-Vabis NAD query only; not corporate archive absence. Probate generic Västerbotten statement explicitly not P0007 own2006 jurisdiction/access. No historical receipt rewrite.'},'C0925':'Sättna household record, not a T0797 corporate/name/probate metadata receipt; no new reading of its original.','T0796PRV':'Trademark query belongs to P0003/Sesam, not a name-file search; no repeat of that query and no inference for Maj.'})
r1='T-0797 R1 current bounded metadata outcome: CfN corporate entrypoint and TAM SIF entrypoint tested, two named entrypoints TOTAL. CfN holdings page describes deponent→archive creator ordering, primarily Bromma/Uppsala, archive-owner permission; digital guide says login for open files, permission for corporate files, partial digitisation. Linked134-page holdings PDF URL says ver-2026-04, but extracted header repeatedly says Version:21mar2024; neither is silently chosen as certified current provider revision. Web text find Scania returns AB Scania bilverkstad under OK atpage76 and Margarin AB Scania under Upfield atpage133; these are not certified Scania-Vabis personnel holdings. Vabis textfind returned no match in extracted representation, no positive control for that spelling and no full visual/binary PDF audit; target company/personnel-series existence,1943–1960s coverage and Samzelius linkage remain precise UNKNOWN. This is not absence in CfN or Scanias own archive. TAM official access guide routes to Klara A–Ö/free/advanced catalogue and warns unlisted new/unprocessed material and confidential personfiles requiring owner permission. Linked Klara returned0textlines in web extraction; SIF own series/date/localbranch/Scania coverage UNKNOWN, an access/extraction limit not a search zero. No personnel original read. ca1943–1960s remains pragmatic search frame from known Södertälje registration, not established employment/office years. Reopen only with new readable catalogue/material metadata or separately authorized bounded original/access passage; no account creation/contact/permission request here.'
r2='T-0797 R2 current bounded metadata outcome: RA PRV name-file entrypoint and KB/Libris PoIT collection entrypoint tested, two named entrypoints TOTAL. PRV MCP query Patent registreringsverket namnärenden returned3catalogue units: SE/RA/420209/03/B/B III/B III c Besvärsavdelningens avgöranden i namnärenden1964–1977, under PRV→Besvärsavdelningen→Utgående handlingar; SE/RA/420209/03 Besvärsavdelningen1885–1977; SE/RA/420401/65 Riksbyrån för folkbokföringen1945–1964 under SCB-samlingspost. Institution Riksarkivet Stockholm/Täby; creator PRV1897– for first2,SCB1880– for third. Appealsseries1964–77 does not cover proposed1950s; fonds-wide dates do not prove name-series coverage. Riksbyrån is a candidate alternative agency route, not a read1950s decision. Returned fields give no own familyfile, access decision, complete hierarchy or digital-image certainty. KB/Libris metadata-domain query \"Post- och inrikes tidningar\"1950 returned no results; earlier broader KB discovery exposed general Svenska tidningar coverage/access but no exact1950s PoIT collection certificate. Exact query/index visibility and1950s collection coverage UNKNOWN, no positive control; not newspaper/notice absence. No notice, name decision or personal original read. Year, legal spelling change, persons covered and familyclaim Jansson→Janson remain unresolved. Reopen with exact historical name-series/register or PoIT title/year collection metadata, then separately authorized original passage; no archival identity changes.'
r3='T-0797 R3 current bounded metadata outcome: RA probate metadata and Skatteverket current-custodian metadata tested, two named entrypoints TOTAL. RA MCP Bouppteckningar returned10of10+catalogue units across unrelated jurisdictions; full returned fields preserved, not own2006probate routing or comprehensive coverage. RA official register guide describes incomplete1622–2001coverage, multiple underlying actors/registers and variable quality; no person query was sent. RA official custody guidance says up to30June2001RA and from1July2001Skatteverket (web search extraction preserved; directopen timeout retained). Skatteverket own copy-access page says documents drawn up from1July2001 held there and copy request concerns registered probate/supplement/estate notification. E-mail copy channel described; no request submitted, no e-mail or personnumber entered. Applying that general date rule to alreadyknown Majbirth1920-05-11/death2006-10-04/registeredhomeSödertälje gives Skatteverket as repository/request route if her probate/dödsboanmälan was registered, not proof it exists or was registered. Södertälje is registered-home key, not physical deathplace; no tingsrätt territorialguess needed for2006custody. Actual own material-id/registration/date/content and any document-specific restriction remain UNKNOWN/unread. This corrects prior untested routing gap, never asserts a demonstrated denial or no-online-content. Reopen on new exact registration metadata or explicit authorized finite copy/original task; orders/contact excluded here.'
rest='Remaining exclusive owners: T0378Helgesta; T0786 ownSödertälje15; T0379 historicalpreservation; T0796shared1951/1948–70metadata are retained with full old scopes/status/checkpoints. T0793 retains planning responsibility for Konsumemployment, personalpapers, possible voluntary/service relevance, later ownresidence1970–2006 and undecided finite original follow-up for these three routes; no automatic next execution. T0797 finishes bounded routing only, not life picture, source exhaustion or tree approval. OWNER PCD2026-10-07-001 Arne/Maj→P0005→P0004 stays established; no new proof requirement or fact extrapolation.'
write('route-outcomes.json',{'R1':r1,'R2':r2,'R3':r3,'remaining':rest})
sources=[
 ('R1-CFN','inconclusive','P-0007/Q-02',['web-discovery-receipt.json','web-targeted-receipt.json','web-open1-receipt.json','web-open2-receipt.json','web-open3-receipt.json','web-open4-receipt.json'],r1,'CfN corporate holdings/access metadata including linked134-page PDF text representation'),
 ('R1-TAM','access_problem','P-0007/Q-02',['web-discovery-receipt.json','web-targeted-receipt.json','web-open1-receipt.json','web-open2-receipt.json','web-open3-receipt.json','web-open4-receipt.json'],r1,'TAM access guide and linked Klara catalogue; blank JS text representation'),
 ('R2-PRV','inconclusive','P-0007/Q-03',['R2-PRV-receipt.json'],r2,'RA MCP exact metadata query Patent registreringsverket namnärenden'),
 ('R2-PoIT','inconclusive','P-0007/Q-03',['web-discovery-receipt.json','web-targeted-receipt.json','web-open2-receipt.json'],r2,'KB/Libris web metadata queries, not article or notice search'),
 ('R3-RA','inconclusive','P-0007/Q-03',['R3-RA-receipt.json','web-targeted-receipt.json','web-open1-receipt.json','web-open2-receipt.json'],r3,'RA MCP Bouppteckningar offset0limit10 plus official custody/register guide metadata'),
 ('R3-SKV','positive','P-0007/Q-03',['web-discovery-receipt.json','web-open1-receipt.json','web-open2-receipt.json'],r3,'Skatteverket public custody/copy-access guidance, no personal request')]
changes=[]
for key,outcome,qid,files,reading,identifier in sources:
 sid='S-T0797-'+key
 snaps=[{'reference':str(base/f),'sha256':h(base/f)} for f in files]
 dates=[json.loads((base/f).read_text())['received_at'] for f in files]
 provider={'value':None,'unknown_reason':'No certified provider revision exposed; web crawl date is not provider version. CfN URL ver2026-04 and internal21mar2024 header both preserved without certified reconciliation.'}
 changes.append(new(sid,'source',{'title':'T-0797 '+key+' bounded metadata','archive_reference':identifier,'source_class':'catalogue_metadata','description':reading+'\n\nExact raw tool-received representations/arguments/time preserved at '+json.dumps(snaps,ensure_ascii=False)+'. Hashes identify response copies, never full originals. Binary CfN PDF not captured: sandbox Python urllib DNS failure; only returned web-extracted metadata read.'}))
 scope={'description':identifier,'query':{'receipt_files':files},'bounds':{'named_entrypoint':key,'originals_read':0,'personal_queries':0,'exact_reading':reading},'search_memory':{'format':'search-memory/1','subjects':['P-0007'],'performed_at':max(dates),'method':'Exact metadata-only requests in preserved receipt args; received_at is local receipt time, not provider update. Only relevant metadata excerpts read; discovery snippets not treated as personal evidence.','material':{'identifier':identifier,'source_version':1,'provider_version':provider,'snapshot':{'reference':str(base/files[-1]),'sha256':h(base/files[-1])}},'coverage':{'completed':outcome!='access_problem','limitations':reading+' Each referenced batch receipt identifies separately requested URLs/queries; this copy hash is not separate material hash or full original.'},'reactivation':['New exact readable catalogue/material metadata with changed keys/coverage, separately authorized bounded passage.','Own original/notice/request needs separate finite authorization; no orders/contact here.']}}
 changes.append(new('SEARCH-T0797-'+key,'search',{'question_id':qid,'source_id':sid,'scope_json':scope,'outcome':outcome,'body':reading},[ev(sid+'@1')]))
audit='AUDIT-T0797-metadata-routing'
changes.append(new(audit,'assessment',{'subject_id':'P-0007','criteria':'bounded_metadata_routing/1','outcome':'reviewed_with_limits','body':r1+'\n\n'+r2+'\n\n'+r3+'\n\n'+rest},[ev('SEARCH-T0797-'+k+'@1') for k,*_ in sources]+[ev('S-0727@1'),ev('F-T0804-P0004-paternal-grandparents-owner@1')]))
targets={'P-0007/Q-02':r1,'P-0007/Q-03':r2+'\n\n'+r3,'PATH-P-0007-KP-02':r1,'PATH-P-0007-KP-03':r2,'PATH-P-0007-KP-06':r3,'KEY-P-0007-8b6bca962679':r1,'KEY-P-0007-1a11bf2908b0':r2,'KEY-P-0007-61b77d7b301e':r3,'THEME-P-0007-ARB':r1,'THEME-P-0007-SAM':r1+'\n\n'+r2,'THEME-P-0007-EKO':r3}
con=[]
for oid,text in targets.items():
 head=dict(db.execute('select * from current_revision where object_id=?',(oid,)).fetchone());kind=head['kind']
 data=dict(db.execute('select * from '+kind+' where revision_id=?',(head['id'],)).fetchone());data.pop('revision_id')
 for k,v in data.items():
  if k.endswith('_json') and v is not None:data[k]=json.loads(v)
 oldbody=data['body'];data['body']='T-0797 current bounded metadata amendment; prior dated wording retained below as historical state:\n'+text+'\n\n'+oldbody
 m={'id':oid,'kind':kind,'expectedVersion':head['version'],'data':data,'disposition':head['disposition'],'evidenceStatus':head['evidence_status'],'rationale':'T-0797 AC2–3 metadata scope amendment only; full prior body/caveat/outcome/evidence/origin order retained.','caveat':head['caveat'],'origins':[{'unit':x['unit_id'],'coverage':x['coverage'],'note':x['note']} for x in db.execute('select * from origin where revision_id=? order by rowid',(head['id'],))],'evidence':[ev(x['basis_revision_id'],x['note'],x['role']) for x in db.execute('select * from dependency where revision_id=? order by rowid',(head['id'],))]}
 m['evidence'].append(ev(audit+'@1','Only the new bounded metadata amendment; full prior evidence order unchanged.'));changes.append(m)
 con.append({'object':oid,'old_revision':head['id'],'exact_field':'body prefix only','old_body_sha256':hashlib.sha256(oldbody.encode()).hexdigest(),'old_outcome':data.get('outcome'),'old_caveat':head['caveat'],'disposition':'amend bounded metadata; retain all old wording/history/status/evidence/origins/order'})
write('consequences.json',con)
write('metadata-routing-operation-v1.json',{'id':'T-0797/metadata-routing-v1','actor':'Codex Sol primary; root independent review required','reason':'T-0797 AC1–3: exact three fixed metadata routes,two namedentrypoints total perroute,no personaloriginal/notice/request. Reuse sufficient historical receipts and preserve preciseunknowns, native bounded profile amendments. Root alone canonical apply after independent review.','dependencyReviewVersion':2,'searchMemoryVersion':1,'changes':changes})
semantic=[]
for head in heads:
 data=dict(db.execute('select * from '+head['kind']+' where revision_id=?',(head['id'],)).fetchone())
 raw=json.dumps({'head':head,'data':data},ensure_ascii=False)
 if 'P-0007' in raw and re.search('Scania|SIF|namnärend|bouppteck|dödsbo|Samzelius|C-0924',raw,re.I):
  semantic.append({'object':head['object_id'],'revision':head['id'],'kind':head['kind'],'exact_fields':[k for k,v in data.items() if isinstance(v,str) and re.search('Scania|SIF|namnärend|bouppteck|dödsbo|Samzelius|C-0924',v,re.I)],'data_sha256':digest(data),'disposition':'body metadata amendment retaining complete older fields' if head['object_id'] in targets else 'RETAIN: underlying personal/owner/source/review content or explicitly dated earlier assessment; new metadata-only routing supplies no revised personal fact or grade'})
write('semantic-consequence-dispositions.json',semantic)
calls=[]
for f in sorted(base.glob('*receipt.json')):
 r=json.loads(f.read_text());calls.append({'receipt':str(f),'sha256':h(f),'args':r['args'],'received_at':r['received_at']})
write('call-inventory.json',{'named_entrypoints_by_route':{'R1':['CFN corporate metadata','TAM SIF metadata'],'R2':['RA PRV name-file metadata','KB/Libris PoIT collection metadata'],'R3':['RA probate metadata','Skatteverket custodian access metadata']},'actual_tool_calls':len(calls),'calls':calls,'extra_failed_copy_attempt':'Python urllib exact linked CFN PDF; DNS failure,0bytes; not an additional named entrypoint','personal_originals':0,'orders_contacts_purchases_accounts':0})
print('Prepared',len(changes),'changes;',len(targets),'metadata amendments;',len(semantic),'semantic copies')
