import fs from'node:fs';import{openDB}from'../../lib/store.mjs';import{inspect}from'../../lib/domain.mjs';const dir='genealogy2/verification/T-0675/',db=openDB('genealogy2/data/research.sqlite',{readOnly:true}),first=JSON.parse(fs.readFileSync(dir+'kalmar-census-first-initial.json')),second=JSON.parse(fs.readFileSync(dir+'kalmar-census-second-initial.json')),objects=JSON.parse(fs.readFileSync(dir+'kalmar-current-objects.json')),changes=new Map(),ledger=[];
const record='R-95c83804b130dc9847fe2fdf',tid='TR-T0675-KALMAR-30';
const reason='T-0675 AK1–4 scope30: full egna nio rader i Kalmar1930, låsta FIRST/SECOND, råfält och individuella materiella följder; ingen apply eller ny person.';
const common='FIRST hade tidigare oavsiktlig modellfältsexponering; SECOND hade tidigare korta personkontexter från gravarbete men läste inte Kalmaravskrift eller scope30-modell före lås. Ingen läsning beskrivs som helt personblind. Utdrag och index är samma beroendekedja, två läsningar är inte två vittnen. Samtliga egna kolumner granskade, kvarstående råtecken osäkra: partial audit. Kol14 är sammansatt rubrik, ingen säker samfundstillhörighet eller datering härleds. Kod-/beloppsskalor ej nyverifierade. Ingen ny födelse-/flyttdag, person eller relationskant.';
const note='Hela Carlmanfamiljens åtta rader och Nilssons separata hushållsmarkering bevarade. Råekonomi Johan74[34?]—2, Amelia4—, Inga10—, Nilsson8—; streck är synliga och inte tomma eller fastställda noll. NamnAmelia/Amelie, Johans yrkesförled/ställning, kol14 och Nilssons inflyttningsort fortsatt reserverade.';
const ev=()=>({object:tid,version:1,role:'supports',note:'Full egen rad och källbundna råreserver, ingen separat historisk röst.'});
function add(id,kind,data,evidence,note){changes.set(id,{id,kind,expectedVersion:null,data,disposition:'recorded',rationale:reason,caveat:note,origins:[],evidence});}
function revise(id,edit,evidence,note){if(changes.has(id))throw Error('duplicate '+id);const x=inspect(db,id),r=x.revisions.at(-1),data={...r.data};delete data.revision_id;for(let k of Object.keys(data))if(k.endsWith('_json')&&typeof data[k]==='string')data[k]=JSON.parse(data[k]);edit(data);let c={id,kind:x.kind,expectedVersion:x.currentVersion,data,disposition:r.disposition,evidenceStatus:r.evidence_status,rationale:note,caveat:note+'\n\nÄldre förbehåll bevarade som historisk lydelse; aktuell precisering ovan gäller:\n'+r.caveat,origins:r.origins.map(o=>({unit:o.id,coverage:o.coverage,note:o.note})),evidence:[...r.evidence.map(e=>{let i=e.basis_revision_id.lastIndexOf('@');return{object:e.basis_revision_id.slice(0,i),version:+e.basis_revision_id.slice(i+1),role:e.role,note:e.note};}),...evidence]};if(x.kind==='record'){c.assets=r.assets.map(a=>({path:a.path,region:a.region}));c.media=r.nativeAssets.map(a=>({id:a.id,region:a.region}));}changes.set(id,c);}
const merged=structuredClone(first);delete merged.crops;merged.pass='AFTER_LOCK_COMPARISON';merged.rows[0].name_raw='Carlman Johan Fredrik Villehad[?]';merged.rows[0].main_occupation_raw='Specerimatvaru[?]/Specerivaror[?]; Handlande A.ä.[?]/a.g.[?]';merged.rows[0].column14_raw='10; Sv.Mff.[?]/Sv.Mtb.[?]; blå V; vågrätt streck';merged.rows[0].income_wealth_raw='74[34?]—2';merged.rows[4].school_raw='5[-?]; yx/gx-liknande tecken';merged.rows[5].name_raw='d. Amelia[Amelie?] Karolina';merged.rows[6].communion_raw='n/h/k-likt';merged.rows[8].arrival_from_raw='[oläst, slut -la/-lla?; FIRST prövade Målilla?/D...lla?]; överlagrad kod272';
const text='Aktuell fullpostavskrift av avgränsade nio egna rader, med synliga tomma fält, streck och osäkerheter.\n'+JSON.stringify(merged,null,2)+'\n'+note+'\n'+common;
revise(record,d=>{d.dependence_note+=' '+note+' '+common;},[],note);
add(tid,'transcription',{record_id:record,text,reading_note:note+' '+common},[{object:record,version:2,role:'derived_from',note:'Fullbild och egna rader, inga tillkommande medier.'}],note);
add('AUDIT-T0675-KALMAR-30','assessment',{subject_id:record,criteria:'original_revision/1',outcome:'partial',body:note+' '+common},[ev()],note);
revise('TR-1ebd6d551c472c4815d50f21',d=>{d.text=text+'\n\nÄldre avskrift, historiskt läsläge:\n'+d.text;d.reading_note=note+' '+common+'\nÄldre anteckning:\n'+d.reading_note;},[ev()],note);
revise('READ-cfad7b1dec14fa47ee76256c',d=>{d.body=note+' '+common+'\n\nÄldre läshistorik:\n'+d.body;},[ev()],note);
revise('O-P-0242-C0899-own',d=>{d.value_json={...d.value_json,income_wealth_literal:'74[34?]—2',older_income_wealth_literal:'34-2',school_code:'5-; x',occupation_raw:merged.rows[0].main_occupation_raw,occupation_code_raw:'1-308-20',religious_literal:merged.rows[0].column14_raw,column14_interpretation:'otolkad sammansatt kolumn; inget fastställt samfund',raw_row:merged.rows[0]};d.value_literal=JSON.stringify(d.value_json);},[ev()],'Råekonomi74föredras men34bevaras osäkert; koder och kol14 läses utan expansion. Tidigare absoluta34 ersätts med reserverad läsning.');
revise('O-P-0243-C0899-own',d=>{d.value_json={...d.value_json,religious_literal:'10 〃; blå V; vågrätt streck',religious_context:'dito till Johans osäkra kol14, ej säker egen utskriven samfundsform',raw_row:merged.rows[1]};d.value_literal=JSON.stringify(d.value_json);},[ev()],'Elins kol14 har dito, inte egen fullt utskriven samfundsförkortning; den råa raden bevaras.');
revise('O-P-0531-C0899-own',d=>{d.value_json={...d.value_json,income_literal:'4',income_wealth_raw:'4 —',wealth_cell:'synligt vågrätt streck',wealth_not_numeric_zero:true,raw_row:merged.rows[5]};d.value_literal=JSON.stringify(d.value_json);},[ev()],'Synligt streck i ekonomifältet rättar läst-och-tomt. Ingen säker nolla eller ovillkorligt kronorbelopp.');
revise('F-P-0242-occupation_economy-source-qualified',d=>{d.value_json={...d.value_json,later_image_literal:'74[34?]—2',older_image_literal:'34-2',school:'5-; x',religion:merged.rows[0].column14_raw,limits:'74 föredras i två låsta läsningar,34 kvarstår råalternativ. Index7400/2000 är samma kopiekedja, inte skiljedomare. Beloppsskala/koder ej verifierade här; ingen samfundsbestämning eller antalstolkning.'};},[ev()],'Kvalificerat ekonomifaktum uppdateras till bästa råförslag74med34reserv; behåller äldre indexbelopp uttryckligt härledda.');
revise('F-P-0531-income-1930',d=>{d.value_json={...d.value_json,wealth_cell_state:'visible_horizontal_dash',wealth_literal:'—',wealth_not_numeric_zero:true,father_current_raw:'74[34?]—2',income_wealth_raw:'4 —'};},[ev()],'Amelias synliga ekonomistreck får inte längre kallas blankt; äldre villkorliga400 består som äldre tolkning, inte ny verifierad skala.');
const replaces={
'BIO-P-0242':[['Johan är handlande och redovisas med inkomst 7 400 kronor och förmögenhet 2 000 kronor.','Johan är handlande. Ekonomifältet läses nu 74[34?]—2; äldre indexexpansion 7 400 kronor och 2 000 kronor är samma beroendekedja och beloppsskalan har inte nyverifierats.']],
'BIO-P-0531':[['Hon arbetade som affärsbiträde och hade en egen redovisad inkomst på 400 kronor — mindre än systern Inga Elins 1 000 och hushållerskans 800, men en egen försörjning.','Hon arbetade som affärsbiträde. Hennes ekonomifält har råtecknen 4 —, systern Ingas 10 — och hushållerskans 8 —. Äldre expansioner till 400, 1 000 och 800 kronor är villkorliga; skalan är inte verifierad här och strecket är inte ett tomt fält eller fastställt noll.']],
'THEME-P-0242-EKO':[['Inkomst 7 400 kr och förmögenhet 2 000 kr redovisade 1930','Råekonomi74[34?]—2 år1930; äldre indexexpansion7400/2000kr villkorlig utan nyverifierad skala']],
'THEME-P-0531-ARB':[['med egen inkomst på 400 kronor','med eget ekonomifält4 —, tidigare villkorligt tolkat400kronor']],
'THEME-P-0531-EKO':[['förmögenhetsfältet är tomt','ekonomifältets efterled har synligt streck, inte tomt eller säkert noll']],
'CONTRACT-P-0242-PK-05':[['C-0269:s fadderfält samt C-0899:s egna samfunds-/skol-/barnkolumner är konkret ofullständigt utvunna.','C-0269:s fadderfält är fortfarande en konkret utvinningsrest. C-0899:s nio egna rader och alla kolumner har nu granskats; kol14, vissa yrkestecken och kodsystem förblir råreserverade, inte överhoppade fält.']],
'THEME-P-0243-SAM':[['Samfundsnotisen1930 är konkret men ofullständigt utvunnen.','Kol14år1930 är granskad:10dito,blåV och streck; förkortningen på makens rad är fortsatt osäker. Ingen bestämd samfundstolkning.']]
};
for(const[id,pairs]of Object.entries(replaces))revise(id,d=>{let k='markdown'in d?'markdown':'body';for(const[a,b]of pairs){if(!d[k].includes(a))throw Error('missing '+id+':'+a);d[k]=d[k].replace(a,b);}d[k]+='\n\nT-0675 scope30: '+note+' '+common;},[ev()],'Individuell textföljd: '+pairs.map(p=>p[0]+' → '+p[1]).join(' / '));
const clarifications={
'CONTRACT-P-0531-PK-05':'Full egen rad kvarstår granskad; ekonomins streck skiljs nu från tomt. Kodsystem och osäkra bokstavstecken är tolknings-/läsgränser, ingen ny fullkontraktsgrind.',
'CONTRACT-P-0531-PK-02':'Den villkorliga kronskalan i äldreA4994 består som tidigare tolkning. Råfält4—och far74[34?]—2 är nu uttryckligen bevarade; ingen ovillkorlig pengarprecision.',
'CONTRACT-P-0531-PK-10':'Berättelsens tidigare ovillkorliga400/1000/800är ersatta med råfält och uttryckliga skalgränser. Okäntvuxenliv och sextiosexårsluckan består.'
};for(const[id,n]of Object.entries(clarifications))revise(id,d=>{d.body=n+'\n\nÄldre bedömning, berörda formuleringar preciseras ovan:\n'+d.body;},[ev()],n);
const followNotes={
'KEY-P-0242-2d1bdbf4e79c':'Skolbildningsnyckel1930 är rå5-;x, inte en ensam5. Kodens innebörd, läroanstalt och examen är fortfarande okända.',
'KEY-P-0242-edab87ed1a96':'Kol14 är läst som10;Sv.Mff.[?]/Sv.Mtb.[?];blåV;streck. Förkortningsalternativen är råreserver, inget säkert samfund eller inträdesår.',
'KEY-P-0243-a057073061e3':'Elins egen kol14 har10dito,blåVochstreck; inget eget fullt utskrivetSv.Mff. Skol4består; makens förkortningsalternativ och kodsystem förblir osäkra.',
'AS-P0243-untranscribed-fields':'C0899egna kolumner är nu alla prövade; Elins10dito och skol4bevaras. Kvar finns tecken-/kodtolkning, inte överhoppade kolumner. Övriga källors fadder/dopförrättar/attestfält och gravprovenans avgörs inte av denna passage.',
'P-0243/Q-02':'Frågans C0899del har full råfältspassage: skol4,kol14med10dito/blåV/streck. Kvarvarande förkortnings- och kodtolkning hålls öppen; frågans andra källrester består.',
'PATH-P-0242-KP-01':'Avgränsat utfall för1930Kalmar: alla nio egna rader/kolumner har granskats och bevarats i aktuell fullTR. Partial avser råtecken och kodtolkning. Denna passage löser inte födelsefadderfält, ungdomskällor eller övriga öppnade poster.',
'PATH-P-0243-KP-02':'C0899egna1930fält är nu prövade och fullutvunna med explicita läsreserver. Förkortning/kodnyckel är fortsatt öppen. C0270/C0406/C0407och egen gravpost ingår inte i detta nya originalutfall.',
'THEME-P-0531-SAM':'Hennes egen kol14är blank. Föräldrarnas anteckning är nu prövad men fortsatt råosäker; den ger henne ingen överförd samfundstillhörighet. Senare församlings-/föreningsliv består som lucka.'
};for(const[id,n]of Object.entries(followNotes))revise(id,d=>{d.body='T-0675 aktuell avgränsad precisering: '+n+'\n\nÄldre text, berörda formuleringar ersätts ovan:\n'+d.body;},[ev()],n);
for(const[id,x]of Object.entries(objects)){const d=x.revisions.at(-1).data;if(!(id===record||d.record_id===record||d.subject_id===record||['P-0242','P-0243','P-0531'].includes(d.subject_id)))continue;let decision=changes.has(id)?'revise':'retain',rationale=changes.get(id)?.rationale;if(!rationale){let p=d.property||d.criteria||d.title||x.kind;rationale='Prövat eget sakomfång '+p+': ';if(p.includes('birth'))rationale+='råår och ort består; detta utdrag ger ingen ny exakt födelsedag eller oberoende födelsekälla.';else if(p.includes('name')||p.includes('PK-01')||p.includes('Identitets'))rationale+='Amelia/Amelie och Villehad/Högsby kvarstår källvarianter; ingen ny identitetskonflikt eller persondelning.';else if(p.includes('residence')||p.includes('BO')||p.includes('PK-03'))rationale+='1909Jönköping→Kalmar och1930uppslag4774 består; inga nya mellanled, senare gemensamma flyttar eller motiv.';else if(p.includes('household')||p.includes('family')||p.includes('REL')||p.includes('PK-04'))rationale+='samma åtta familjerader; Nilsson har separat1och yrke hushållerska, inget släktbevis eller nya totalbarnantal.';else if(p.includes('PK-11'))rationale+='lokal fullbild och lokalisering består; denna passage avgör inte andra källors bevarandebrister.';else rationale+='egen oförändrad uppgift/öppen fråga ligger utanför de korrigerade småfälten. Prövat mot aktuell payload som bevaras i ledger; inget automatiskt lyft av övriga utfall.';}ledger.push({object:id,current_version:x.currentVersion,decision,rationale,current_payload:d});}
for(const c of changes.values()){for(const e of c.evidence)if(changes.has(e.object))e.version=(changes.get(e.object).expectedVersion??0)+1;c.evidence=[...new Map(c.evidence.map(e=>[`${e.object}@${e.version}/${e.role}`,e])).values()];}
const ordered=[],done=new Set(),active=new Set();function visit(id){if(done.has(id))return;if(active.has(id))throw Error('cycle '+id);active.add(id);const c=changes.get(id);for(const e of c.evidence)if(changes.has(e.object))visit(e.object);active.delete(id);done.add(id);ordered.push(c);}for(let id of changes.keys())visit(id);
fs.writeFileSync(dir+'kalmar-proposed-operation.json',JSON.stringify({id:'T-0675/Kalmar1930-v1',actor:'codex',reason,changes:ordered},null,2)+'\n');
fs.writeFileSync(dir+'kalmar-comparison-ledger.json',JSON.stringify({task:'T-0675',scope:30,status:'proposed_not_applied',first_blindness:first.blindness,second_independence:second.independence,first_second_comparison:['Överens huvudnamn/år/orter/yrken/civilstånd/1909 och1930inflyttningar, nio rader och hushållsmarkeringar.','SECOND såg blyertskod över Johan men utelämnade den i låst JSON; ingen efterhandsändring av SECOND. Aktuell TR bevarar FIRSTs reserverade2808[?]-01-5[?], ej ett påstående om två oberoende kodläsningar.','Johan yrkesförled A.ä./a.g. och kol14 Mff/Mtb reserverade som alternativ.','74föredras av båda, FIRST34alternativ består. Ingen indexharmonisering.','Rut skol5-streck osäkert; Amelia slutvokal fortsatt a/e.','Nilssons inflyttort oläst; FIRST alternativ Målilla?/D...lla? endast råförslag.'],model_changes:note,individual:ledger,limits:common,impact_routing:'Övriga C0899poster Umeå och andra personers/gravers ämnen är routingsamband, utanför denna sakgranskning. Inga pending requests löses före faktiskt applyutfall.'},null,2)+'\n');console.log({changes:changes.size,ledger:ledger.length});
