import fs from 'node:fs';import{openDB}from '../../lib/store.mjs';import{inspect}from '../../lib/domain.mjs';
const dir='genealogy2/verification/T-0675/', first=JSON.parse(fs.readFileSync(dir+'root-address-first-initial.json')),second=JSON.parse(fs.readFileSync(dir+'address-second-initial.json'));const db=openDB('genealogy2/data/research.sqlite',{readOnly:true});const changes=[];
const reason='T-0675 AK1–3: full granskning av fyra adressposter på tre bevarade fullbilder, separat kontroll och exakt radbindning. Fastighetsnycklar hålls skilda från personboende.';
for(const r of first.records){const s=second.records.find(x=>x.record===r.record||x.number===r.number);if(!s)throw Error('MissingSECOND '+r.number);const tr='TR-T0675-address-'+r.number;const note='Tryckta källvärden återgivna med alla egna kolumner. Dittomärken upplöses inom samma block. År1945 kommer från äldre volymidentifiering, inte dessa tre sidhuvuden. Ingen ny läsning av alfabetiska s46–48 eller målet639; äldre avgränsat noll om Tranbäret räknas inte som nykontrollerat här. Gondolen2=40 och3=42 är samtidiga separata nycklar; ingen gatunummerändring eller ny boendeuppgift.';
changes.push({id:tr,kind:'transcription',expectedVersion:null,data:{record_id:r.record,text:JSON.stringify({first:r,second:s},null,2),reading_note:note},disposition:'recorded',evidenceStatus:'TRANSCRIBED',rationale:reason,caveat:note,origins:[],evidence:[{object:r.record,version:1,role:'derived_from',note:'Samma bevarade tryckta källa; mediehashar i låsta protokoll.'}]});
changes.push({id:'AUDIT-T0675-address-'+r.number,kind:'assessment',expectedVersion:null,data:{subject_id:r.record,criteria:'original_revision/1',outcome:'bounded_fields_examined',body:r.scope+'\n'+note},disposition:'recorded',rationale:reason,caveat:note,origins:[],evidence:[{object:tr,version:1,role:'supports',note:'Hela egna målposten och båda separata läsningarna.'}]});}
const id='O-P-0003-C0885-stg452',x=inspect(db,id),r=x.revisions.at(-1),d={...r.data};delete d.revision_id;d.value_json=JSON.parse(d.value_json);d.value_json.source_row_literal='452+453+454+455';d.value_json.property_is_subset_of_combined_entry=true;
changes.push({id,kind:x.kind,expectedVersion:x.currentVersion,data:d,disposition:r.disposition,evidenceStatus:r.evidence_status,rationale:reason,caveat:r.caveat+' T-0675: Kartreferensen D9 står vid den sammanbundna posten452+453+454+455; tidigare452 är ett urval ur den, inte en separat tryckt rad.452A/Se639 är en annan post.',origins:r.origins.map(o=>({unit:o.id,coverage:o.coverage,note:o.note})),evidence:[...r.evidence.map(e=>{const [object,v]=e.basis_revision_id.split('@');return{object,version:+v,role:e.role,note:e.note}}),{object:'TR-T0675-address-25',version:1,role:'supports',note:'Källradens fulla grupp bevarad.'}]});
fs.writeFileSync(dir+'address-proposed-operation.json',JSON.stringify({id:'T-0675/four-address-blocks-v1',actor:'codex',reason,changes},null,2)+'\n');db.close();console.log(changes.length);
