import fs from'node:fs';import{openDB}from'../../lib/store.mjs';import{inspect}from'../../lib/domain.mjs';const dir='genealogy2/verification/T-0675/',db=openDB('genealogy2/data/research.sqlite',{readOnly:true}),read=n=>JSON.parse(fs.readFileSync(dir+n)),first=read('root-birger-first-initial.json'),second=read('birger-second-initial.json'),all=read('birger-current-objects.json'),rid=second.record,tid='TR-T0675-birger-28',changes=[],ledger=[];
const reason='T-0675 AK1–4 post28: fullbild, två separata låsta pass över hushållsrader12–14s18kolumner och individuell käll-/modelljämförelse.';
const note='T-0675: Birgers egen födelsecell05 31/8 avviker från andra källors1905-08-13; bevara konflikt, ingen automatisk omdatering/ny identitet. Yrkesråform Distr.polis föredras efter riktad jämförelse: storD-slinga följd avistr; FIRSTsVakt.polis? bevaras som avvikande läsning. Äldre normaliseringpoliskonstapel är inte ordagrann egenform. Från G.B.10[1/4]4 år43; tillN.B.315/I? år54, inte äldre51. Hustruns förnamn RensErika?/NinaEricha? fortsatt olösta; Högdahl ochFolkskollär:a stöds. Sonens egen namnformLarsGregor föredras framför äldre[LarsBirger]; födelse38 27?/3 medFIRST21/27reservation. Inga nya familjeidentiteter/kanter. Rad13–14s egna flyttceller tomma fylls inte frånrad12. Äldre avskrifter/origins bevarade append-only; båda läsningar samma historiska källa.';
function clone(id,fn,why){const x=inspect(db,id),r=x.revisions.at(-1),d=structuredClone(r.data);delete d.revision_id;for(const k in d)if(k.endsWith('_json')&&typeof d[k]==='string')d[k]=JSON.parse(d[k]);const c={id,kind:x.kind,expectedVersion:x.currentVersion,data:d,disposition:r.disposition,rationale:reason,caveat:r.caveat,origins:r.origins.map(o=>({unit:o.id,coverage:o.coverage,note:o.note})),evidence:r.evidence.map(e=>{const [object,v]=e.basis_revision_id.split('@');return{object,version:+v,role:e.role,note:e.note}})};if(r.evidence_status)c.evidenceStatus=r.evidence_status;if(x.kind==='record'){c.assets=r.assets.map(a=>({path:a.path,region:a.region}));c.media=r.nativeAssets.map(a=>({id:a.id,region:a.region}));}fn(c);changes.push(c);ledger.push({object:id,version:x.currentVersion,decision:'revise',reason:why,old:r.data,new:c.data,oldCaveat:r.caveat,newCaveat:c.caveat});return c;}
clone(rid,c=>{c.caveat=note;},'Egenpostens utelämnade dagar är nu utvunna; råreservationer ersätter gamla ofullständiga gränser, fullmediet bevaras.');
const raw=structuredClone(second);raw.rows[0].raw['2']='Distr.polis [föredras efter riktad jämförelse; FIRSTVakt.polis? bevaras]' ;raw.rows[0].raw['9']='G.B.10[1/4]4';raw.rows[1].raw['1']='h.[Rens Erika?/Nina Ericha?] f.Högdahl';raw.rows[2].raw['4']='[27?/21?]/3';raw.comparison_note=note;raw.additional_first_field='Blå Egen133? ovanrad12 iFIRST; SECOND missade denna lokala kod. Kod och radbindning reserveras, ej personfakta.';
changes.push({id:tid,kind:'transcription',expectedVersion:null,data:{record_id:rid,text:JSON.stringify({current:raw,locked_FIRST:first,locked_SECOND:second},null,2),reading_note:note},disposition:'recorded',evidenceStatus:'TRANSCRIBED',rationale:reason,caveat:note,origins:[],evidence:[{object:rid,version:2,role:'derived_from',note:'Samma bevarade fullbildsha'+second.image.sha256}]});
clone('TR-1c5945013eadf0605987ef97',c=>{c.data.text='Aktuell källavskrift efterT0675jämförelse; äldre@1 bevarad.\n'+JSON.stringify(raw,null,2);c.data.reading_note=note;c.caveat=note;},'Aktuelltext rättar51→54/LarsBirger→Gregor och visar egen31aug-konflikt/reservationer.');
clone('READ-0a036192b4e2e244d27e8eaf',c=>{c.data.body='Rader12–14,alla18kolumner/rubriker faktiskt prövade iT0675. '+note;c.caveat=note;},'Tidigare text rörde delvis annat hushåll; exakt Birgersomfång nu komplett.');
changes.push({id:'AUDIT-T0675-birger-28',kind:'assessment',expectedVersion:null,data:{subject_id:rid,criteria:'original_revision/1',outcome:'bounded_fields_examined',body:reason+' '+note},disposition:'recorded',rationale:reason,caveat:note,origins:[],evidence:[{object:rid,version:2,role:'derived_from',note:'Egna tre rader.'},{object:tid,version:1,role:'supports',note:'Låsta råpass och aktuell jämförelse.'}]});
clone('M-P-0036-C0889-son',c=>{c.data.name_literal='Lars Gregor';c.caveat+=' T-0675:båda visuella läsningarGregor; äldre[LarsBirger] bevarat@1. Källomnämnande, ingen ny personidentitet.';},'Egen namncellGerGregor, ändra endastmention.');
clone('M-P-0036-C0889-wife',c=>{c.data.name_literal='[Rens Erika?/Nina Ericha?] f. Högdahl';c.caveat+=' T-0675:de skilda låsta förnamnsförslagen är olösta; ingen vald personidentitet.';},'SäkerRens-namnform inte stödd avSECOND; båda alternativ synliga.');
clone('O-P-0036-C0889-son-fields-household_person',c=>{c.data.value_json={...c.data.value_json,name_literal:'Lars Gregor',birth_day_month_literal:'27?/3 [FIRST21/27reservation]',birth_parish_literal:'ditto Burträsk',vaccination_literal:'v',christian_knowledge_literal:'a',communion_literal:'n-liknande',own_transfer_cells:'tomma'};c.data.value_literal=JSON.stringify(c.data.value_json);c.caveat='Hela egenrad14 prövad; namn/datum är källvärden, ingen ny person eller föräldrakant. Äldre hakparentesnamn bevarat i@1.';},'Kompletterar egna nya småfält utan identitetsnormalisering.');
clone('O-P-0036-C0889-wife-fields-household_person',c=>{c.data.value_json={...c.data.value_json,name_literal:'[Rens Erika?/Nina Ericha?] f.Högdahl',birth_day_month_literal:'31/1',marriage_literal:'ditto',own_transfer_cells:'tomma'};c.data.value_literal=JSON.stringify(c.data.value_json);c.caveat=note;},'Egna31jan/ditto ochnamnreservation, inga nya person-/partnerkanter.');
for(const id of ['O-P-0001-C0889-Birger','O-P-0036-C0889-r12-household_and_transfers'])clone(id,c=>{let v=c.data.value_json;for(const k of Object.keys(v))if(typeof v[k]==='string'){v[k]=v[k].replace('1951','1954').replace(' 51',' 54').replace('1014','10[1/4]4');}if(v.occupation)v.occupation='Distr.polis [föredras; FIRSTVakt.polis? reserverat]' ;v.birth_day_month_literal='31/8 [konflikt med äldre13/8]';v.marriage_literal='K.33 26?/12';v.catechism_year_literal='45';v.military_literal='242? 69/25';c.data.value_literal=JSON.stringify(v);c.caveat+=' '+note;},'Aktiva51/yrkesnormalisering/frånfolio ersätts med egen aktuell råpost.');
clone('F-P-0036-occupation-poliskonstapel',c=>{c.data.value_json='Poliskonstapel på äldre avgångsrad; Burträskfol275 har senare förkortningenDistr.polis [föredragen råform; FIRSTVakt.polis? bevaras], exakt titelutveckling reserverad.';c.caveat+=' T-0675:Burträskraden säger inte ordagrantpoliskonstapel och är inte överstruken; äldreUmeårad bedöms separat.';},'Separera äldrepoliskonstapel från dagens egenråförkortning.');
for(const id of ['F-P-0001-household_membership-network-P-0036','F-P-0039-family_neighborhood-Birger-Gammelbyn','F-P-0040-family_neighborhood-Birger-Gammelbyn'])clone(id,c=>{const v=c.data.value_json;for(const k in v)if(typeof v[k]==='string')v[k]=v[k].replace('1943–1951','1943–1954');c.caveat+=' T-0675:54 är Birgers överföringsår, inte bevis för kontinuerligt grannskap till1954. Övriga hushålls egna flyttar och tidigare syskonankare består; Birgers sena31/8konflikt omdaterar inte automatiskt andra källors13/8.';},'Samma källa hade felårs51; förlänger inte andra personers boende bortom deras egna avgångar.');
const researchEdits={
'AS-P-0036-existing-family-conflict':d=>{d.body='Tidigare akt/profil sade att egen familj inte är känd. C0889 fol275 r12–14 är nu fullständigt lästa:T0675 visarhustru ochson i eget familjeblock. Förnamnsreservation hos hustrun, sonLarsGregor; inga nya familjemedlemmars personidentiteter eller släktkanter.';},
'BIO-P-0036':d=>{d.markdown=d.markdown.replace('Där, 1951, slutar allt som är\nbelagt.','Hans egen hushållsrad fördes vidare tillN.B.315/I? år1954; mellanleden och fortsättningen är inte lästa.');d.markdown+='\nT-0675:C0889fol275r12–14 visar hustru ochsonLarsGregor som källomnämnanden. Hustruns förnamn reserveras. Birgers egen05 31/8 är en källkonflikt mot ovan13augusti, inte en ny fastställd födelsedag. Den egna yrkesformenDistr.polis [föredragen råform; FIRSTVakt.polis? bevaras] är reserverad; ingen kontinuerlig tjänst härleds.\n';},
'CONTRACT-P-0036-PK-03':d=>{d.body='| PK-03 | EJ STYRKT | T0675 har nu läst Burträskfol275r12–14 och överföringsår54, inte äldre51. Mellankedjan1933–43 och fortsättningen efter1954/döden är inte fullständigt följda; sekundär1962 fastställer inget slutår. |\n';},
'CONTRACT-P-0036-PK-04':d=>{d.body=d.body.replace('Men ingen egen familj är känd, och frånvaron är oprövad — de lästa källorna slutar när han är tjugoåtta, vilket uttryckligen inte får läsas som att han var ogift.','T0675 visar nuhustru ochson pår13–14; familjens personidentiteter/nätverk är fortfarande ofullständigt prövade.');},
'THEME-P-0036-BO':d=>{d.body='| BO | AVGRÄNSAT | Tidiga ankare bevaras. Egen Burträskradfol275 är nu läst: G.B.10[1/4]4 år43 och N.B.315/I? år54. Dessa är överföringshänvisningar; 1933–43 och fortsättningen efter1954/döden återstår, inte en bevisad obruten1905–1954kedja. | T0675;Q01,KP01 |\n';},
'THEME-P-0036-REL':d=>{d.body=d.body.replace('Ingen egen familj är känd — och frånvaron är oprövad, eftersom hans egen rad efter 1933 inte är läst; den får inte skrivas som att han var ogift.','T0675:r12–14 visar hustru med reserverat förnamn ochsonLarsGregor; exakta familjeidentiteter och övrigt nätverk är inte avgjorda.');},
'THEME-P-0036-HAL':d=>{d.body=d.body.replace('Levde 1951.','Egen rad överförd år54; ingen dödanteckning på denna rad.').replace('Att han fick värnpliktsnummer utan frikallelseanteckning är en indirekt hälsouppgift vid tjugo år.','Värnpliktsnummer och avsaknad av frikallelseanteckning fastställer inte god hälsa.');},
'PATH-P-0036-KP-01':d=>{d.outcome='DELVIS UNDERSÖKT: fol275r12–14 fullständigt lästa T0675; övrig kedja/död ej avgjord.';d.body+='\nAktuell avgränsning T0675:fol275r12–14 är utförd och ska återbrukas. FöregåendeGB10[1/4]4 ochfortsättningNB315/I?54 är källnycklar med reservation; ingen ny sida öppnad. Hustru/son finns redan som källomnämnanden. Tidigare1951slut ocholästegenrad är överspelade.\n';},
'PATH-P-0036-KP-04':d=>{d.body+='\nT0675:C0889egenrad läses05 31/8 mot tidigare13/8 i andra volymer. Det är nu en faktisk källkonflikt att motpröva i födelsebok, ingen majoritetsnormalisering. Den gamla motiveringen lågbrådska därför att alla datum överensstämmer är begränsad till tidigarevolymer.\n';},
'P-0036/Q-04':d=>{d.body=d.body.replace('Ingen hustru och inga\n  barn i någon läst källa, men hans egen rad efter 1933 är oläst.','T0675 har läst hustru/son i Burträskrader13–14; personidentiteterna avgörs inte här.');d.body+='\nT0675:första frågan är fortsattÖPPEN med ny källkonflikt31/8 mot13/8; familjens existens i detta hushåll är nu belagd men dess identiteter/nätverk inte färdiga.\n';},
'RESEARCH-P-0036-9d76f0343410':d=>{d.body+='\nT0675:Burträskfol275r12 ger05 31/8, en konkret konflikt mot andra volymers13/8. Namn,Degerfors,polisyrke ochmilitärnyckel stöder fortsatt tidigare personkoppling men hänvisningenGB10[1/4]4 reserveras; ingen ny identitet eller födelsedagsnormalisering görs. Överföringsåret54 rättar51. Tidigare GODKÄND/EJBÄRANDE höjs inte och födelsebok återstår.\n';}
};
for(const[id,edit]of Object.entries(researchEdits))clone(id,c=>{edit(c.data);c.caveat+=' '+note;},'Individuell aktivtext: egen rad/familj/årgräns/datumkonflikt, bevarat utfall och övrig forskning.');
// Precisely qualify remaining current copies of the changed year/reading in their own field.
for(const id of ['ASSESSMENT-P-0036','CONTRACT-P-0036-PK-01','THEME-P-0036-ID','KEY-P-0036-f93c7470cdbe','KEY-P-0036-0ea2dbb24106','KEY-P-0036-23fc711e06b4','P-0036/Q-01','P-0036/Q-03','THEME-P-0036-ARB','THEME-P-0036-SAM'])clone(id,c=>{c.data.body+='\nAktuell T0675-kvalifikation: '+note+' Egna kol13år45 tillförs som källuppgift utan ny medlemskaps- eller hälsoslutsats.\n';c.caveat=c.caveat.replaceAll('rader 42–45','rader12–14')+' '+note;},'Bevarar gammal saklig forskning men kvalificerar egen kopia av1951/yrke/13aug eller nu kompletterad rad/förhör.');

for(const id of ['CONTRACT-P-0036-PK-06','CONTRACT-P-0036-PK-09','CONTRACT-P-0036-PK-10','THEME-P-0036-SYN'])clone(id,c=>{c.data.body=c.data.body.replace('familjefrågan är oprövad och inte besvarad','hustru ochson är lästa källomnämnanden men deras exakta personidentiteter/nätverk ännu inte avgjorda').replace('frånvaron av en hustru i lästa källor räknas inte som ogift stånd','hustru ochson nu finns i den lästa Burträskposten utan att nya familjeidentiteter/kanter fastställts').replace('lämnar både familjefrågan och döden som luckor','redovisar läst hushåll medhustru/son men kvarstående familjeidentiteter ocholäst död');},'Precisera äldre familjelucka till faktiskt kvarvarande identiteter, bevara kontraktsutfall.');
const bodies={
'P-0036/Q-01':`### Q-01: Var i Burträsk bodde han, och när dog han?

Frågan är fortsatt ÖPPEN. Umeå stads egen avgång1933-11-17 tillKalvträsk är tidigare prövad. T-0675 har nu läst hans eget hushåll på Burträskfol275r12–14 överalla18kolumner. Rad12 hänvisar frånG.B.10[1/4]4 år43 och vidare tillN.B.315/I? år54. Hänvisningarna ger administrativa ankare; de bevisar inte obruten fysisk vistelse eller exakt flyttdag. Mellankedjan1933–43 och fortsättningen efter1954 är inte följda.

Hustrun och sonen finns på egna rader som källomnämnanden; deras slutliga personidentiteter avgörs inte här. Hustruns förnamn RensErika?/NinaEricha? är olöst, sonens namn läsesLarsGregor. Birgers Distr.polis föredras som egen råtitel. Hans05 31/8 avviker från tidigare13/8 och bevaras som källkonflikt.

Fortsatt prövning inomKP01/T0537 gäller de hänvisade egna raderna och eventuell senare avgång/död. Den nu fullständigt lästa fol275 ska återbrukas. Ingen dödcell är ifylld pår12; sekundärträdets1962 är fortfarande obelagt och får inte välja dödsårgång. Inga nya familjepersoner eller släktkanter skapas.
`,
'P-0036/Q-03':`### Q-03: Hur blev ett kontorsbiträde polis?

Frågan är ÖPPEN och gäller ARB/PER/SAM. Kontorsbitr. i folkräkningen1930 och den tidigare Umeåradens överstrukna poliskonstapel hålls källskilda. På Burträskfol275r12 föredras nu Distr.polis; FIRSTsVakt.polis? bevaras som avvikande läsning. Hushållsraden bär hänvisningsåren43 och54, inte en verifierad tjänstgöringsperiod1943–1954.

Ingen utbildnings-, antagnings- eller tjänstehandling är belagd. En anställning utan formell utbildning, genomgången utbildning och en extraordinarie befattning är fortfarande oprövade alternativ. Polisdistriktets eller länsstyrelsens personbundna antagnings- och tjänstehandlingar är den relevanta oberoende vägen enligtKP03/T0537.

Folkräkningsinkomsten1 har inte omtolkats här och bevisar inte fattigdom; det lästa strecket i förmögenhetsdelen är ett eget källfält. Birgers födelsedagskonflikt31/8mot13/8 ska följa söknyckeln utan automatisk omdatering.
`,
'THEME-P-0036-ARB':`| ARB | AVGRÄNSAT | Kontorsbitr.1930, poliskonstapel i den tidigare Umeåraden och föredragen råformDistr.polis påBurträskfol275 är källskilda yrkesuppgifter. De visar inte obruten tjänst eller identisk befattning. Utbildning och antagnings-/tjänstehandlingar är olästa. | C0899,C0916,C0889;Q03,KP03,T0537 |\n`,
'KEY-P-0036-0ea2dbb24106':`| poliskonstapel; Distr.polis | Umeås tidigare avgångsrad och Burträskfol275 med hänvisningsår43/54 | C0916,C0889 | Skilda råtitlar; ingen kontinuerlig1933–1954tjänst fastställd. Personbundna antagnings-/tjänstehandlingar är en oprövad oberoende väg. |\n`,
'KEY-P-0036-23fc711e06b4':`| BirgerZingmark, Burträskfol275r12–14 | Gammelbyn14 | C0889,T0675 | Eget hushåll nu fullständigt läst: G.B.10[1/4]4 år43→N.B.315/I? år54. Tidigare brodersakt var ingång, men är inte längre enda personbundna läsningen. Andra hushålls egna boendeår ändras inte. |\n`,
'P-0036/Q-04':`### Q-04: Vad står i hans egen födelsenotis, och vilka är hans familjemedlemmar?

Frågan är ÖPPEN. Tidigare Degerfors- och Umeåvolymer anger1905 13/8 och hör till samma möjliga kopiekedja. T0675 läser Birgers egen Burträskcell05 31/8. Detta är en bevarad källkonflikt, inte ett beslut att omdatera honom. Degerfors födelsebok1905 ska pröva den ursprungliga dagen och kan ge dopuppgifter; denna exakta passage ingår iT0399/KP04.

Familjeförekomst är nu positivt läst: hustrun pårad13 och sonen pårad14 iC0889. Hustruns RensErika?/NinaEricha? f.Högdahl är namnosäker; sonen läsesLarsGregor. De förblir källomnämnanden utan nya personID eller kanter. Egna flyttceller för dem är tomma och får inte fyllas frånBirgers rad12.

Fortsatt hushållsbunden familjeprövning ingår iT0537/KP01. Separata vigsel-/familjefödelseposter är inte öppnade. Tre tidigare upprepningar av13/8 räknas inte som tre oberoende röster mot31/8.
`,
'PATH-P-0036-KP-01':`### KP-01: Burträsks och Kalvträsks kyrkoböcker från1933

Frågor/teman:Q01,Q04,BO,HAL,REL,SAM. KällklassK04,K03,K05. Burträsk kyrkoarkiv, egen hushålls- och flyttkedja från avgången1933-11-17 tillKalvträsk samt senare dödsväg.

Undersökt omfång: T0675 har fullständigt läst C0889fol275r12–14. Positivt eget hushåll medhustru ochson; Birgers hänvisningarG.B.10[1/4]4 år43 ochN.B.315/I? år54, titelDistr.polis föredragen. Birgers födelsecell05 31/8 är konflikt mot tidigare13/8. Exakt hustrunamn och frånfolio reserveras. Tom egen dödcell fastställer inget dödsår.

Återstående omfång: mellanled1933–43 och fortsättning efter1954 är inte följda. Hänvisningarna är nya begränsade söknycklar, inte redan lästa fortsättningssidor. Tidigare fol275 ska tillgodoräknas. Döden är inte belagd; sekundär1962 får inte välja dödsårgång. Inga nya familjeID.

Leverantör:Riksarkivet. Wotan:T0537 äger hushålls-/flyttpassagen och dess stoppgränser. Inga nya källor öppnade i denna jämförelse.
`,
'PATH-P-0036-KP-03':`### KP-03: Personbundna handlingar om polistjänsten

Q03,ARB,EKO,PER; källklassK19,K21. Tidigare Umeåradens poliskonstapel och Burträskfol275s föredragnaDistr.polis är ingångar. Hänvisningsår43/54 på hushållsraden anger inte tjänstens början eller slut. Exakt polisdistrikt och arkivbildare är fortfarande oidentifierade.

Förväntad information:antagning,utbildning,tjänstgöringsort,lön och egenhand. Inget sådant personbundet dokument är läst. BirgerZingmark och båda källbundna födelsedagsformer13/8 respektive31/8 år1905 ska bevaras i sökningen.

Beroende:katalogrouting; följer hushållsortsprövningenKP01. Åtkomst:EJ KONTROLLERAD. Utfall:EJ UNDERSÖKT. T0537 omfattar vidbehov polisdistriktets/länsstyrelsens antagningshandlingar; ingen allmän polishistorik eller oavgränsad ny undersökning ingår.
`};
for(const[id,body]of Object.entries(bodies)){let c=changes.find(x=>x.id===id);if(!c)c=clone(id,()=>{},'Rättar aktiv äldre yrkesperiod/åtkomstägare enligt faktiskt omfång.');c.data.body=body;if(id==='P-0036/Q-03')c.data.title='Q-03: Hur blev ett kontorsbiträde polis?';if(id==='P-0036/Q-04')c.data.title='Q-04: Vad står i hans egen födelsenotis, och vilka är hans familjemedlemmar?';}
const bio=changes.find(c=>c.id==='BIO-P-0036');bio.data.markdown=bio.data.markdown.replace('Tio år efter det bodde han som poliskonstapel\ngranne med sin bror Oskar Alfred i Burträsk.','På Burträskfol275 står han senare med den föredragna råtitelnDistr.polis i ett eget hushåll på samma fastighetsbeteckning som broderns hushåll. Detta är inte bevis för oförändrad befattning eller kontinuerlig tjänst.');
for(const c of changes){for(const k of ['body','markdown'])if(typeof c.data[k]==='string'){c.data[k]=c.data[k].replaceAll('rader 42–45','rader12–14').replaceAll('1943–1951','1943–1954');}c.caveat=c.caveat.replaceAll('rader 42–45','rader12–14');}
for(const l of ledger){const c=changes.find(c=>c.id===l.object);l.new=c.data;l.newCaveat=c.caveat;}
const versions=new Map(changes.map(c=>[c.id,(c.expectedVersion??0)+1]));for(const c of changes){for(const e of c.evidence){if(versions.has(e.object))e.version=versions.get(e.object);if(e.object===rid)e.note=e.note.replace('1943–1951','1943–1954');}}
const sorted=[],todo=[...changes];while(todo.length){const i=todo.findIndex(c=>c.evidence.every(e=>!todo.some(v=>v.id===e.object)));if(i<0)throw Error('cycle '+todo.map(x=>x.id));sorted.push(...todo.splice(i,1));}
fs.writeFileSync(dir+'birger-proposed-operation.json',JSON.stringify({id:'T-0675/birger-household-full-v1',actor:'codex',reason,changes:sorted},null,2)+'\n');fs.writeFileSync(dir+'birger-comparison-and-impact.json',JSON.stringify({task:'T-0675',scope:28,first:'root-birger-first-initial.json',second:'birger-second-initial.json',comparison:note,ledger},null,2)+'\n');console.log(changes.length);db.close();
