import fs from'node:fs';import{openDB}from'../../lib/store.mjs';import{inspect}from'../../lib/domain.mjs';const db=openDB('genealogy2/data/research.sqlite',{readOnly:true}),dir='genealogy2/verification/T-0675/';const first=JSON.parse(fs.readFileSync(dir+'flen-arrivals-first-initial.json')),objects=JSON.parse(fs.readFileSync(dir+'sodflen-current-objects.json')),changes=new Map(),reviews=[];
const reason='T-0675 AK1–4: fyra hela egna källposter kontrollerade genom låsta FIRST/SECOND; rätta avskrift och kolumnsemantik samt individuellt prövade följder. Ingen ny personprecision eller trädgrind.';
const notes={4:'Post132: 24/11 1943, --- Arne Godvig, poler.[?], liten not husförest.[?] med osäker personbindning; 15 21/2, 2 män/2 kvinnor, från Flen till Mejseln3, uppslag15, av.22 44/35. Ovanfödda 38/40 med v-/pil-liknande sluttecken; ingen namngiven hustru eller barn i denna post. Värnpliktsnumret daterar inte militärtjänst.',22:'Post131: datum23/11 under år1943 och trädg.arb., inte äldre23/12/tvätt.arb. Namn Margit Eleonora Jansson,23 3/12, en kvinna från Botkyrka till Brunnsäng gård/Ö.1, uppslag23,av. Separat post, inte del av nästa hushåll.',15:'860 r20–22: Johansborg [vokalgrafi något reserverad],Storgatan24. Polerare på r20; h.Maj Amalia f.Ekholm med tomt yrke på r21; s.Jan Christer,icke döpt på r22. Gift38 15/5 i gemensamt vertikalt fält. Kol6 Vaccinerad eller haft koppor bär v för vuxna, tomt för sonen. Majs kol11 a/k[?] och kol12 n-/v-liknande är skilda tecken med kvarstående läsreservation. Arnes kol11/12 är streck och kol13 tom. N.B.720, militär22 44/35; utflyttdatum tomt. Svag båge i dödskolumnens område är inget läst dödsdatum.',47:'720 r14–17: Kv.Penseln (östra),N:o4,Johansborg [vokalgrafi något reserverad],Storgat.24. Hushållsnamnen är strukna; barnens icke döpt också struket, följt av Döpt16.11.1941 på sonens rad och dittotecken på dotterns. Majs kol11 b/k[?],kol12 n-liknande; vaccinationens rubrik är fastställd. Kol13 bär överlagrad Fl.[?]43 A/11[?] samt41,42; äldre40 inte säkert separerbart. Noten ligger i Bevistat husförhör år, inte flyttningsbetygets två faktiskt tomma kolumner. Ingen säker attesthändelse/dag härleds. G.B.860 endast utskrivet på r14; r15–17 frånfält tomma. Mejseln3,22 44/35,Södertälje stad[sf.?],1943 24/11 och relevanta dittotecken. Dödkolumn tom; marginaltal olästa.'};
const common='Låsta läsningar: flen-arrivals-first-initial.json och root-sodflen-second-initial.json. Samma original är inte två historiska vittnen. Råa barnfödelsedagar bevaras enbart i låst läsunderlag; aktuell visning fortsätter redaktionell dataminimering och använder inte tomt för utelämnad dag. FIRST och SECOND ändras inte. Ingen ny identitets-, tros-, militärtjänst- eller resförloppsslutsats.';
function ev(n){return{object:`TR-T0675-SF-${n}`,version:1,role:'supports',note:'Full egen post med explicita råreservationer och två låsta läsningar.'};}
function revise(id,edit,es,note){const x=inspect(db,id),r=x.revisions.at(-1);let data={...r.data};delete data.revision_id;for(const k of Object.keys(data))if(k.endsWith('_json')&&typeof data[k]==='string')data[k]=JSON.parse(data[k]);edit(data);let evidence=r.evidence.map(e=>{let i=e.basis_revision_id.lastIndexOf('@');return{object:e.basis_revision_id.slice(0,i),version:+e.basis_revision_id.slice(i+1),role:e.role,note:e.note};});changes.set(id,{id,kind:x.kind,expectedVersion:x.currentVersion,data,disposition:r.disposition,evidenceStatus:r.evidence_status,rationale:note,caveat:note+(r.caveat?'\n\nÄldre förbehåll, historisk lydelse; ovanstående precisering gäller aktuellt:\n'+r.caveat:''),origins:r.origins.map(o=>({unit:o.id,coverage:o.coverage,note:o.note})),evidence:[...evidence,...es]});}
function add(id,kind,data,es,note){changes.set(id,{id,kind,expectedVersion:null,data,disposition:'recorded',rationale:reason,caveat:note,origins:[],evidence:es});}
for(const r of first.records){let n=r.scope_number,id=r.record,x=inspect(db,id),full=structuredClone(r);delete full.uncertainties;
 if(n===15){full.rows[1].cells.Kristendomskunskap='a/k[?], FIRST k[?], SECOND a';full.rows[1].cells['Inom svenska kyrkan begått H. Nattvarden']='n-/v-liknande tecken [osäkert]';full.rows[2].cells['Född dag/månad']='[redaktionellt utelämnad; råtecken i låst FIRST]';full.rows[2].marks='Röd kontrollmarkering; födelsedag redaktionellt minimerad.';}
 if(n===47){for(const row of full.rows.filter(row=>['16','17'].includes(row.row))){row.cells['Född dag/månad']='[redaktionellt utelämnad; råtecken i låst FIRST]';row.marks='Överstruken namnrad och icke döpt; rådag bevarad i låst FIRST, inte tillförd personmodell.';}full.rows[0].cells['Utflyttad/överförd till']='Södertälje stad[sf.?]';full.rows[1].cells.Kristendomskunskap='b/k[?]';full.rows[0].cells['Bevistat husförhör år']='Fl.[?]43 A/11[?];41,42; överlagring, eventuellt äldre40 inte säkert separerbart';}
 let text='Aktuell fullpostavskrift T-0675, med explicit redaktionell minimering och kvarstående råreservationer.\n'+notes[n]+'\n'+JSON.stringify(full,null,2)+'\n'+common;
 add(`TR-T0675-SF-${n}`,'transcription',{record_id:id,text,reading_note:notes[n]+' '+common},[{object:id,version:x.currentVersion+1,role:'derived_from',note:'Fullbildens path och SHA i låst FIRST; tillhör slutlig källpostversion.'}],notes[n]);
 add(`AUDIT-T0675-SF-${n}`,'assessment',{subject_id:id,criteria:'original_revision/1',outcome:'bounded_fields_examined_with_reservations',body:notes[n]+' '+common},[ev(n)],notes[n]);
 revise(id,d=>{},[],notes[n]);changes.get(id).assets=x.current.media.map(m=>({path:m.path,region:m.region}));
 for(const old of Object.values(objects).filter(o=>o.kind==='transcription'&&o.revisions.at(-1).data.record_id===id))revise(old.object,d=>{d.text=text+'\n\nÄldre avskrift, uttryckligen historisk; ersatt i berörda fält av ovanstående:\n'+d.text;d.reading_note=notes[n]+' '+common+'\n\nÄldre läsanteckning:\n'+d.reading_note;},[ev(n)],notes[n]);
 for(const rd of x.current.readings)revise(rd.object_id,d=>{d.body=notes[n]+'\n\nÄldre avgränsningshistorik:\n'+d.body;},[ev(n)],notes[n]);
}
revise('O-P-0003-C0882-arrival-fields',d=>{d.value_literal='poler.[?]; 2 män, 2 kvinnor; uppslag15;22 44/35';d.value_json={...d.value_json,occupation_raw:'poler.[?]',occupation:'polerare [tolkningsform; förkortning reserverad i denna post]',otherTitle:'husförest.[?]',otherTitleSubject:null,pencil_years_raw:'38/40 med v-/pil-liknande osäkra sluttecken'};},[ev(4)],'Ankomstpostens yrkesförkortning och andra titel återges med lokal råreservation även i observationen. Polerare är säkert utskrivet i de separata Flenraderna, men deras klarhet tar inte bort denna posts grafiska reservation. Hushållssummor och obunden andra titel består.');
revise('O-P-0007-marks-860',d=>{d.property='vaccination_and_church_columns';d.value_literal='kol6 v; kol11 a/k[?]; kol12 n-/v-liknande; kol13 tom';d.value_json={row:21,vaccination_or_smallpox_raw:'v',christian_knowledge_raw:'a/k[?]',communion_raw:'n-/v-liknande',examination_year_raw:null,military_column:null};},[ev(15)],'Majs egen rad21: rubrikerna är nu lästa och skilda; v ligger i Vaccinerad eller haft koppor, inte ett tidigare okänt fält. Bokstavstecknen a/k och n/v förblir olösta; ingen trosaktivitet eller vaccindag härleds.');
revise('O-P-0007-marks-720',d=>{d.property='vaccination_and_church_columns';d.value_literal='kol6 v; kol11 b/k[?]; kol12 n-liknande; kol13 ditto till reserverad not på r14';d.value_json={row:15,vaccination_or_smallpox_raw:'v',christian_knowledge_raw:'b/k[?]',communion_raw:'n-liknande',examination_raw:'ditto till r14:s reserverade Fl.[?]43 A/11[?];41,42',military_column:null};},[ev(47)],'Majs egen rad15: v under fastställd rubrik Vaccinerad eller haft koppor; kol11 b/k och kol12 n reserveras var för sig. Kol13 har ditto, inte ett separat säkert daterat deltagande; makens värnpliktsnummer tillhör inte henne.');
revise('O-P-0003-C0895-religious-fields',d=>{d.value_literal='kol13 Fl.[?]43 A/11[?];41,42, överlagrat; flyttningsbetygets datum/nr tomma';d.value_json={column:'13 Bevistat husförhör år',raw:'Fl.[?]43 A/11[?];41,42',prior40:'inte säkert separerbart i överlagringen',certificate_date:null,certificate_number:null,attestation_event_proved:false};},[ev(47)],'Äldre säker serie40–42 och attestdag1943 ersätts av rå reserverad kol13. De separata flyttningsbetygsfälten är tomma. Ingen ny daterad attest eller trosaktivitet sluts.');
revise('O-P-0303-C-0895-flen',d=>{d.value_json={...d.value_json,home:'Kv. Penseln (östra), N:o4, Johansborg [vokalgrafi något reserverad], Storgat.24',birth_day:'redaktionellt utelämnad; råfält bevarat i låst FIRST'};},[ev(47)],'Dotterns hushållshuvud rättas från äldre (Åsta) till bildens (östra), N:o4. Egen namnform, födelseår, dittoanknutet dop och utflyttning består; ingen ny full födelsedag förs.');
const precise={
 'CONTRACT-P-0003-PK-05':['Arnes del om C-0895 preciseras: kol13 är prövad men delvis oläst;41,42 tydliga medan äldre40 och attesttolkning inte säkert kan bekräftas. De separata flyttningsbetygsfälten är tomma. Övriga PK-05-brister och utfall ändras inte.',47],
 'PATH-P-0003-KP-07':['Källvägens C-0895-del preciseras: överlagrad kol13 har Fl.[?]43 A/11[?];41,42 och ingen säker separat40; inte en fastställd attesthändelse. Flyttningsbetygets egna fält är tomma. Den lokalt prövade oläsbarheten skiljs från tidigare utvinningsskuld; övriga namngivna poster kvarstår.',47],
 'CONTRACT-P-0007-PK-05':['Majs kolumnrubriker på860/720 och hela egna rader har nu prövats. v har rubriken Vaccinerad eller haft koppor; kristendom/nattvard är egna kolumner med a/k respektive b/k och n/v-liknande råreservationer. Dessa två blad är inte längre outvunna;932 och övriga namngivna hänvisningar bedöms inte avslutade här. PK-05-utgången ändras inte.',15,47],
 'P-0007/Q-04':['Delutfall för Majs egen rad21 på860 och rad15 på720: samtliga egna fält och rubriker prövade, kvarstående bokstavsreservationer i kol11/12 och ditto i kol13 bevarade. Frågan om932 och1920–1929 är fortfarande öppen; det är inte tre obehandlade Flenrader längre.',15,47],
 'PATH-P-0007-KP-04':['Delutfall:860 r21 och720 r15 fullständigt prövade till läsbarhetsgränsen, rubriker fastställda; råreservationer och tomfält skilda från utvinningsskuld.932 och Helgesta ej behandlade i detta pass. Ofullständig normalisering är inte i sig outvunnen råkälla.',15,47],
 'PATH-P-0007-KP-01':['Den tidigare angivna resten av Majs egna kolumnmärken på860/720 är nu prövad med lästa rubriker och kvarstående råreservationer. Hushåll, boköverföring och1943-11-24 består; ingen ny exakt överföringsdag1940 eller fysisk kontinuitet.',15,47],
 'KEY-P-0007-b6e7a6cfd00e':['Söknycklarna till tre egna rader består. Utvinningsstatus preciseras:860 r21 och720 r15 är fullprövade med råreservationer;932 r2 ligger utanför denna passage.',15,47],
 'P-0007/Q-01':['Hushålls- och bokföringsfrågan består som fastställd. Formuleringen att860 inte lästs och att hennes860/720-märken är outvunna är äldre status; båda egna rader är nu fullprövade med läsreservationer. Den registrerade kedjan avgör inte varje fysisk vistelse.',15,47],
 'THEME-P-0007-HAL':['Majs v på860/720 står under läst rubrik Vaccinerad eller haft koppor. Kolumnmarkeringen är råbelagd, men ingen vaccinationsdag, sjukdomshistoria eller förklaring av v utöver rubriken sluts. Övriga döds-/grav- och hälsofrågor ändras inte.',15,47],
 'THEME-P-0007-SAM':['Majs kristendomskolumn på860/720 är nu prövad: a/k[?] respektive b/k[?], med skild nattvardskolumn och reserverade tecken. Inget exakt betyg eller särskild kyrkohändelse fastställs. SIF och namnärendet är fortsatt oprövade.',15,47],
 'THEME-P-0303-HAL':['Kolumnrubriken för v på720 är nu läst som Vaccinerad eller haft koppor. Detta undanröjer äldre påstående om okänd rubrik; ingen personnormaliserad hälsoobservation, vaccinationsdag eller ny levande persons livsuppgift förs.',47],
 'CONTRACT-P-0303-PK-05':['Rubriken för v på720 är nu känd, men dataminimering av dotterns födelsedag och hälsonormalisering består. Råtecken finns endast i låst läsunderlag. Utfall och identitetsgrind omprövas inte.',47],
 'KEY-P-0303-57f406bd3f70':['Flyttnyckeln1943-11-24 består. Äldre säker benämning flyttningsbetygets anteckning återtas: noten står i kol13 Bevistat husförhör år och är delvis oläst; själva betygsfälten är tomma.',47],
 'THEME-P-0303-SAM':['Dotterns dopnot/ditto och registrerade utflyttning1943 består. Äldre hushållets flyttbetyg1943 är en tolkning som inte kan hämtas ur de tomma betygsfälten; den överlagrade kol13-noten förblir råreservation.',47],
 'RESEARCH-P-0303-9d76f0343410':['Den egna identitetsbedömningen behålls: ankomst132 namnger inte dottern. Blyerts38/40 har v-/pil-liknande osäkra sluttecken, inte säkerställda nedåtpilar. Ingen ny namnbindning, moderskapsart eller full födelsedag sluts.',4]
};
for(const[id,[note,...ns]]of Object.entries(precise))revise(id,d=>{for(const k of ['body','markdown'])if(k in d)d[k]='T-0675 aktuell precisering: '+note+'\n\nÄldre text, bevarad som historiskt forskningsläge; berörda formuleringar ersätts ovan:\n'+d[k];if(id==='PATH-P-0003-KP-07'||id==='PATH-P-0007-KP-04')d.outcome=note;},ns.map(ev),note);
// Individuell sakdisposition. Alla aktuella payloads finns i snapshots; ingen ändring från enbart provenance.
for(const[id,x]of Object.entries(objects)){const r=x.revisions.at(-1),d=r.data;let decision=changes.has(id)?'revise':'retain',note=changes.get(id)?.rationale;
if(!note){const head=d.title||d.property||d.criteria||d.event_type||d.relation_type||d.role||d.name_literal||x.kind;let test='';
if(x.kind==='participation')test=`${d.person_id} står kvar i rollen ${d.role} till ${d.event_id}; datum och hushållsidentifiering är oförändrade, marginal-/betygsrättelserna ändrar inte rollen.`;
else if(x.kind==='event')test=`Händelsen ${d.event_type} med ${d.date_json} stöds fortsatt av egen datumcell eller dokumenterat dopditto; ingen rättelse av det datumet, och betygsnoten skapar ingen extra händelse.`;
else if(x.kind==='relation'||x.kind==='identity'||x.kind==='mention')test='Egen familjeroll/namnankare består; ingen ny biologisk eller rättslig relation, efternamnsutvidgning eller identitetsgrind härleds ur kolumnmärkena.';
else if(id.includes('military')||id.includes('-MIL')||id==='P-0003/Q-04'||id==='KEY-P-0003-d438f0afae4e')test='22 44/35 består på Arnes egna rader; ingen ny tjänstgöring/systemtolkning och ingen överföring av numret till annan familjemedlem.';
else if(id.includes('portrayed')||id==='P-0303/Q-02'||id==='PATH-P-0303-KP-02')test='Jämförelsedagen24/11 består; fotoalternativen kvarstår, eftersom registreringen inte daterar faderns första arbetsresa.';
else if(id.includes('Johansborg860')||id.includes('johansborg1938'))test='Adress, eget hushåll och1938-ingång består.1940 är period-/bokgräns, inte ett nyavläst exakt datum i tomma utflyttningscellen; fullpostens tydliga tomfält bär denna gräns.';
else if(id.includes('birth-P-0303')||id.includes('name_form')||id.includes('children'))test='Barnens årsnoggrannhet, rånamn och antal består. Fulla födelsedagar och personnormaliserad hälsa införs inte.';
else if(id==='P-0007/Q-05')test='Den andra Lyckedalsraden har inte öppnats här;860:s egna sonrad och ditto från932 ger en söknyckel men avgör inte det andra barnets identitet.';
else if(id.startsWith('ASSESSMENT'))test='Övergripande äldre identitets-/kontraktsutfall ändras inte av dessa fyra delposter; andra namngivna brister kvarstår. Detta är ingen ny grindprövning.';
else if(id.startsWith('BIO'))test='Biografins hushåll, yrke, dopår och registreringsdag består; den anger inte den rättade lilla betygsnoten som ny händelse. Tidigare egna reservationsnoter och integritetsgränser består.';
else if(id==='RESEARCH-P-0003-9d76f0343410'||id==='RESEARCH-P-0007-9d76f0343410')test='Forskningsobjektets identitetskedja och andra specifika kunskapsluckor består; inget av de rättade råfälten ändrar dess faderskaps-/namnslutsatser.';
else test='Egen text och sakfält prövade mot denna passages fyra begränsade rättelser. Huvudkedja, egna andra frågor och avgränsningar består; ingen ny slutsats följer av provenance eller textmatch ensam.';
note=`${head}: ${test}`;}
reviews.push({object:id,version:x.currentVersion,kind:x.kind,decision,rationale:note,current_payload:d,registered_evidence:r.evidence});}
for(const c of changes.values()){for(const e of c.evidence){if(changes.has(e.object))e.version=(changes.get(e.object).expectedVersion??0)+1;}c.evidence=[...new Map(c.evidence.map(e=>[`${e.object}@${e.version}/${e.role}`,e])).values()];}
const ordered=[],done=new Set(),active=new Set();function visit(id){if(done.has(id))return;if(active.has(id))throw Error('cycle '+id);active.add(id);let c=changes.get(id);for(const e of c.evidence)if(changes.has(e.object))visit(e.object);active.delete(id);done.add(id);ordered.push(c);}for(const id of changes.keys())visit(id);
fs.writeFileSync(dir+'sodflen-proposed-operation.json',JSON.stringify({id:'T-0675/Sodertalje-Flen-four-v1',actor:'codex',reason,changes:ordered},null,2)+'\n');fs.writeFileSync(dir+'sodflen-comparison-ledger.json',JSON.stringify({task:'T-0675',status:'proposal_not_applied',notes,limits:common,first_sha256:'441bff1aa58387b3629bd4585eef21705e5903e1be6040bf1695036c465bd11b',individual:reviews,after_apply:'Exakta nyutlösta pending ids ska läsas och sakprövas separat; inga påhittade resolve här.'},null,2)+'\n');console.log({changes:changes.size,reviewed:reviews.length});
