import pathlib,json,sqlite3,hashlib,datetime,time,shutil
R=pathlib.Path.cwd();D=R/'evaluations/T-0812/preparation';start=time.monotonic();h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();main=R/'genealogy2/data/research.sqlite';expected=json.load(open(R/'evaluations/T-0812/root-start-baseline-v1.json'));assert h(main)==expected['main_sha256'];c=sqlite3.connect(f'file:{main}?mode=ro',uri=True);c.row_factory=sqlite3.Row;backup=D/'baseline477.sqlite';assert not backup.exists();out=sqlite3.connect(backup);c.backup(out);out.close();(D/'baseline-state-v1.json').write_text(json.dumps({'state':{'journal_head':477,'pending':0},'main':{'path':str(main.relative_to(R)),'sha256':h(main)},'backup':{'path':str(backup.relative_to(R)),'sha256':h(backup)},'main_unchanged':True},indent=2)+'\n');support=json.load(open(D/'exact-support-native-v1.json'))['revisions'];records=[n for n in support if n['kind']=='record'];codes=['0274','0456','1046','0941','0048','0026'];units=[]
for code in codes:
 paths=list((R/'genealogy/citations').glob('C-'+code+'-*'));matched=[]
 for n in records:
  origins=[]
  for o in n['origins']:
   u=c.execute('select *from unit where id=?',(o['unit_id'],)).fetchone()
   if u and ('C-'+code+'-' in u['document_path']or u['legacy_id']in ['C-'+code,'C'+code]):origins.append(dict(u))
  if origins:matched.append({'record_revision':n['id'],'exact_native_record':n,'accepted_origin_units':origins,'assets':n.get('assets',[]),'media':n.get('media',[])})
 units.append({'citation':'C-'+code,'accepted_frozen_citation_fulltexts':[{'path':str(p.relative_to(R)),'sha256':h(p),'full_text':p.read_text()}for p in paths],'matched_accepted_record_versions':matched,'qualification':'Source-ceiling/reuse metadata only, not original promotion or source-person certification; tested limits remain exactly in accepted text.'})
(D/'accepted-source-ceiling-and-reuse-map-v1.json').write_text(json.dumps({'units':units,'images_opened':0,'note':'Accepted T0158/T0196/T0110/T0674 stronger support reused; proposed units not promoted. T0420/T0215 rest owners retained.'},ensure_ascii=False,indent=2)+'\n');scopes=D/'scope-and-norm-snapshots-v1';scopes.mkdir();norms=['AGENTS.md','wotan/README.md','wotan/dev-log/T-0812.md','wotan/dev-log/T-0420.md','wotan/dev-log/T-0215.md','genealogy2/README.md','genealogy2/docs/working.md','docs/research/person-contract.md','docs/research/source-strategy.md']
for p in norms:shutil.copyfile(R/p,scopes/p.replace('/','__'))
reusepaths=['evaluations/T-0811/actual-main-stage-comparison-v1.json','evaluations/T-0811/implementation/stage477-v2/inventory-full.json','evaluations/T-0811/implementation/stage477-v2/P-0269-pedigree.json','evaluations/T-0811/implementation/stage477-v2/P-0270-pedigree.json','evaluations/T-0811/implementation/stage477-v2/qualified-final-result-v1.json'];reuse=[{'path':p,'sha256':h(R/p)}for p in reusepaths];(D/'current-reader-reuse-pins-v1.json').write_text(json.dumps({'current_actual_main_sha256':h(main),'reuse':reuse,'qualification':'T0811 canonical actual all50/order comparison proves immutable stage477 reader data current; both default verified paths38. No duplicate wholeproject views.'},indent=2)+'\n');r=json.load(open(D/'capture-result-v1.json'));rec=json.load(open(D/'actual-accepted-receipt-reconciliation-v1.json'));assert rec['all_exact']and len(rec['entries'])==477;assert h(main)==expected['main_sha256'];files=[{'path':str(p.relative_to(R)),'sha256':h(p)}for p in sorted(D.rglob('*'))if p.is_file()and p.name!='locked-current-input-manifest-v1.json'];files+=reuse;files.append({'path':'PROJECT-CONTROL.md','sha256':h(R/'PROJECT-CONTROL.md')});manifest={'task':'T-0812','scope':['P-0254','P-0255'],'state':{'journal_head':477,'pending':0},'main_sha256':h(main),'current_focal_objects':r['focal_current_count'],'direct_and_current_stronger_support_revisions':r['support_revision_count'],'old467_head_delta':r['old467_head_delta'],'all477_receipts_exact':True,'delta468_477_complete_exact':True,'OWNER_literal_routes':r['owner_literal_count'],'all_current_OWNER_count':45,'OWNER_direct_basis_count':25,'exact_owner_PC_sections':6,'required_write_preflight':'Before any literalstage required/allowed schemas and unique native evidence tuple (basis revision,role) per target; duplicates returned to Astra, no silent dedup','OWNER_qualification':'Literal routing is not a source scope judgement or absence claim; full direct/current evidence and accepted decisions available in source/relevant receipt objects.','source_originals_opened':0,'no_original_promotion':True,'elapsed_capture_seconds':r['elapsed_seconds'],'seal_elapsed_seconds':time.monotonic()-start,'files':files,'file_count':len(files),'canonical_writes':0};p=D/'locked-current-input-manifest-v1.json';assert not p.exists();p.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');print(h(p));print('pins',len(files),'focal',r['focal_current_count'],'support',r['support_revision_count'],'changed',len(r['old467_head_delta']))
