import json,hashlib,importlib.util
from pathlib import Path
R=Path(__file__).resolve().parents[3];D=R/'evaluations/T-0804/implementation';H=R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py';sp=importlib.util.spec_from_file_location('h',H);h=importlib.util.module_from_spec(sp);sp.loader.exec_module(h);c=h.conn(R/'evaluations/T-0804/preparation/baseline464.sqlite');assert h.state(c)=={'journal_head':464,'pending':0}
def native(oid):
 rid=h.current(c,oid);n=h.native(c,rid)
 for key,t in [('origins','origin'),('evidence','dependency')]:n[key]=[dict(z)for z in c.execute('select * from '+t+' where revision_id=? order by rowid',(rid,))]
 return n
statement='Ägaren bekräftar 2026-10-07 att Arne P-0003 och Maj P-0007 är Sverker P-0004:s farföräldrar. Den etablerade kopplingen löper genom Jan-Christer P-0005. Saknad egen Södertäljeuppslag15-utvinning får inte blockera denna bekräftade familjekoppling.'
reason='T-0804 AC1–2: registrera ägarens uttryckliga familjebesked med åtskild ägarproveniens; ingen ny arkivoriginalutvinning.'
source={'id':'S-T0804-owner-family-confirmation-20261007','kind':'source','expectedVersion':None,'data':{'title':'Ägarbekräftelse 2026-10-07: Arne/Maj som Sverkers farföräldrar','archive_reference':'Ägarens besked i projektets arbetsdialog, bevarat i PROJECT-CONTROL.md och T-0804','source_class':'owner_statement','description':statement},'disposition':'accepted','evidenceStatus':None,'rationale':reason,'caveat':'Ägaruppgift, inte arkivhandling eller ny originalbild. Exakt beslutsscope bevaras; ingen allmän källuttömning eller full livsbild.','origins':[],'evidence':[]}
record={'id':'R-T0804-owner-family-confirmation-20261007','kind':'record','expectedVersion':None,'data':{'source_id':source['id'],'record_type':'owner_statement','locator':'Ägarbesked 2026-10-07; T-0804; PROJECT-CONTROL.md','dependence_note':'En och samma ägaruppgift; source/record/observation/fact är administrativa lager, inte oberoende röster.'},'disposition':'accepted','evidenceStatus':None,'rationale':reason,'caveat':source['caveat'],'origins':[],'evidence':[{'object':source['id'],'version':1,'role':'derived_from','note':'Versionsbunden egen ägaruppgift, ingen arkivoriginalproveniens.'}]}
observation={'id':'O-T0804-owner-paternal-grandparents','kind':'observation','expectedVersion':None,'data':{'record_id':record['id'],'mention_id':None,'property':'owner_family_statement','value_literal':statement,'value_json':{'grandchild':'P-0004','father':'P-0005','paternal_grandparents':['P-0003','P-0007']}},'disposition':'accepted','evidenceStatus':'OWNER_CONFIRMED','rationale':reason,'caveat':source['caveat'],'origins':[],'evidence':[{'object':record['id'],'version':1,'role':'supports','note':'Samma explicita ägarbesked.'}]}
fact={'id':'F-T0804-P0004-paternal-grandparents-owner','kind':'fact','expectedVersion':None,'data':{'subject_id':'P-0004','property':'owner_confirmed_paternal_grandparents','value_type':'structured','value_json':{'father':'P-0005','paternal_grandparents':['P-0003','P-0007']}},'disposition':'accepted','evidenceStatus':'OWNER_CONFIRMED','rationale':reason,'caveat':'Fastställd projektinformation inom ägarens exakta familjebesked. Ändrar inte datum, föräldrarelationernas lagrade art, olästa sourcefält eller separat underkänd livsbild.','origins':[],'evidence':[{'object':observation['id'],'version':1,'role':'supports','note':'Ägarbekräftelsen registreras en gång; administrativa lager är inte oberoende röster.'}]}
changes=[source,record,observation,fact];con=[];unsettled=[]
for oid in ['REL-parent-P-0003-P-0005','REL-parent-P-0007-P-0005','REL-parent-P-0005-P-0004']:
 old=native(oid);a=h.api(old);a['expectedVersion']=old['version'];a['evidence'].append({'object':fact['id'],'version':1,'role':'supports','note':'T-0804: explicit bekräftad farföräldrakoppling genom P-0005; tidigare arkivstöd och lagrad relationsart/datering består.'})
 if oid=='REL-parent-P-0005-P-0004':a['evidenceStatus']='OWNER_CONFIRMED'
 changes.append(a);con.append({'object':oid,'old_native':old,'proposed_api':a,'source_direction':'Root/primary settled relationship chain; literal new owner provenance proposed pending exact source approval'})
ids=['ASSESSMENT-T0784-P0003-identity','ASSESSMENT-T0784-P0003-tree','ASSESSMENT-T0784-P0007-identity','ASSESSMENT-T0784-P0007-tree','IDENTITY-REVIEW-T0788-P0007','TREE-EFFECT-T0788-P0007','IDENTITY-REVIEW-T0789-P0007','TREE-EFFECT-T0789-P0007'];retired=set(ids[2:6]);projected={oid:native(oid)['version']+1 for oid in ids};heads=dict(c.execute('select object_id,version from current_revision'));edgeNote='T-0804: aktuell version anger senare rättelser; den pensionerade granskningens ursprungliga bedömningsläge och gamla belägg finns oförändrade i revision1. Inte stöd för att det äldre bristpåståendet fortfarande gäller.'
for oid in ids:
 old=native(oid);a=h.api(old);a['expectedVersion']=old['version']
 if oid in retired:
  a['disposition']='retired';a['caveat']='T-0804: pensionerad historisk granskningsversion. En aktuell uttrycklig ägarbaserad bedömning ersätter konkurrensen; ursprunglig arkivutvinningsbedömning och tidigare belägg kvarstår i revision1. Ingen egen15-post har lästs.\n\nTidigare förbehåll:\n'+old['caveat']
 else:
  axis=a['data']['criteria'];a['data']['outcome']='passed' if axis=='identity_review/1' else 'supporting';a['data']['body']='T-0804: aktuell avgränsad bedömning grundad på ägarens bekräftade farföräldrakoppling genom P-0005 till P-0004. '+('Identitetsutfall passed' if axis=='identity_review/1' else 'Trädverkan supporting')+'. Bekräftad familjekunskap får användas utan att egen15 först öppnas. Detta anger tillräckligt underlag för denna bekräftade familjekoppling, inte fullgjord PK05-arkivutvinning eller godkänd livsbild. Egen15-rest och faktiska åtkomsthinder ligger kvar hos T-0786.\n\nHistorisk arkivutvinningsbedömning, oförändrad:\n'+old['data']['body'];a['caveat']='T-0804: ägarbekräftad familjekoppling bär denna avgränsade aktuella grind. Historisk utvinningsrest bevaras men blockerar inte ägarbeskedet. Ingen full PK05-PASS eller ny originalläsning.\n\nTidigare förbehåll:\n'+old['caveat'];a['evidence'].append({'object':fact['id'],'version':1,'role':'supports','note':'T-0804: exact owner-confirmed paternal-grandparent chain; separate from archive extraction completion.'})
 for e in a['evidence']:
  if e['object']==fact['id']:continue
  target=projected.get(e['object'],heads.get(e['object']))
  if e['version']!=target:
   unsettled.append({'target':oid,'edge':dict(e),'proposedCurrentOrProjectedVersion':target,'requiresFinalIndividualSourceApproval':True});e['version']=target;e['note']=(e['note']+'\n\n' if e['note'] else '')+edgeNote
 changes.append(a);con.append({'object':oid,'old_native':old,'proposed_api':a,'source_direction':'Settled active/retired outcomes, proposed exact body/caveat and projected edges require primary approval; no automatic application'})
op={'id':'T-0804/owner-family-and-bounded-review-correction-PROPOSED-v1','actor':'Codex/Sol-proposed-for-Astra-review','reason':'T-0804 AC1–5 PROPOSED LITERAL PACKAGE ONLY; no clone or canonical authority.','dependencyReviewVersion':2,'changes':changes};p=D/'proposed-owner-native-operation-v1.json';p.write_text(json.dumps(op,ensure_ascii=False,indent=2)+'\n');q=D/'proposed-owner-native-consequences-v1.json';q.write_text(json.dumps({'role':'Noncanonical draft for primary source review; proposed exact wording/metadata/provenance, not a source decision','operation_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'changes':con,'projectedEvidenceAmendmentsAwaitingExactSourceApproval':unsettled,'semanticCopies':'143 literal routes supplied separately; individual decisions pending. Seven current-to-future retired-edge bindings need final projected approvals after semantic operations settle.'},ensure_ascii=False,indent=2)+'\n');print(json.dumps({'draftChanges':len(changes),'reviewedExistingObjects':len(con),'proposedRebinds':len(unsettled),'operationSha':hashlib.sha256(p.read_bytes()).hexdigest()}))
