import json,hashlib,importlib.util,time
from pathlib import Path
R=Path.cwd();I=R/'evaluations/T-0814/implementation';S=I/'stage483-v1';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();sp=importlib.util.spec_from_file_location('h',R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py');h=importlib.util.module_from_spec(sp);sp.loader.exec_module(h);c=h.conn(S/'stage.sqlite');initial=h.conn(I/'stage482-v1/stage.sqlite');assert h.state(c)=={'journal_head':483,'pending':0};op=json.load(open(I/'operation-v1.json'));resolve=json.load(open(I/'42-resolution-operation-v1.json'));ct=json.load(open(I/'consequence-table-v1.json'));rt=json.load(open(I/'42-resolution-consequence-table-v1.json'));rows=[]
for a in op['changes']:
 n=h.native(c,h.current(c,a['id']));assert n==h.native(initial,h.current(initial,a['id']));actual=h.api(n);assert actual==h.expected_defaults(a,actual),a['id'];rows.append({'object':a['id'],'current_full_native':n,'exact_API':a,'full_metadata_order_exact':True})
for t in ct['retains']:assert h.native(c,h.current(c,t['old_native']['object_id']))==t['old_native']
for t in rt['retains']:assert h.native(c,h.current(c,t['old_native']['object_id']))==t['old_native']
stored=[dict(r)for r in c.execute('SELECT * FROM review_resolution WHERE operation_id=? ORDER BY rowid',(resolve['id'],))];assert [{'request':r['request_id'],'rationale':r['rationale']}for r in stored]==resolve['resolve'];actual=[]
for o in [op,resolve]:
 row=dict(c.execute('SELECT * FROM operation_payload WHERE operation_id=?',(o['id'],)).fetchone());assert json.loads(row['request_json'])=={**o,'dependencyReviewVersion':2,'searchMemoryVersion':1};actual.append({'operation':o['id'],'accepted_payload':row,'literal_except_supported_policy_defaults':True})
proof={'state':h.state(c),'full20_native_APIs':rows,'ordered42stored_resolutions':stored,'initial613retains_exact':True,'resolution42stepretains_exact':True,'unique_retains_are_not_655_claim':True,'all_history_and_arrays_proof':'protected-native-prefix-proof.json','accepted_two_operation_payloads':actual,'initial_stage482_unchanged_sha256':sha(I/'stage482-v1/stage.sqlite'),'final_stage483_sha256':sha(S/'stage.sqlite'),'no_new_native_LIFE':not any(a['kind']=='assessment' and a['data']['criteria']=='life_picture_review/1' for a in op['changes']),'no_new_search_or_original':True};p=S/'final-exact-native-package-proof.json';assert not p.exists();p.write_text(json.dumps(proof,ensure_ascii=False,indent=2)+'\n');print('20native/42orderedresolution/613+42stepretainsPASS',sha(p))
