import json,hashlib,copy
from pathlib import Path
D=Path('evaluations/T-0830/implementation');before=json.load(open(D/'stage-v4/actual-pending-full-native-v1.json'));now=json.load(open(D/'stage-v5/actual-pending-full-native-v1.json'));review=json.load(open('evaluations/T-0830/independent/actual-pending203-review-v1.json'));key=lambda r:(r['affected_revision'],r['changed_revision']);approved={key(r):r for r in review['individual_requests']if r['disposition']=='APPROVE_RETAIN_RESOLUTION'};old={(z['request']['affected_revision_id'],z['request']['changed_revision_id']):z for z in before['actual_requests']};rows=[];res=[]
def sem(n):
 x=copy.deepcopy(n);x['revision'].pop('operation_id');return x
assert len(approved)==201==len(now['actual_requests'])
for z in now['actual_requests']:
 q=z['request'];pair=(q['affected_revision_id'],q['changed_revision_id']);r=approved[pair];p=old[pair];assert p['affected_native']==z['affected_native'];assert p['current_head_native']==z['current_head_native'];assert sem(p['changed_basis_native'])==sem(z['changed_basis_native']);rationale='T-0830 individuell granskning: '+pair[0]+' mot '+pair[1]+'. '+r['reason']+' Exact independent retain approval actual-pending203-review-v1 SHA54a36b56107a285bfb7298eef4be037583c7932046c2dcae4b6e316df4286f86. Full current data/caveat/status/evidence/origins and historical basis retained; no latest-version rebinding or new independent voice.';res.append({'request':q['id'],'rationale':rationale});rows.append({'request':q,'original_review_request_id':r['request_id'],'affected_revision':pair[0],'changed_basis':pair[1],'source_disposition':r['reason'],'full_affected_native_equal':True,'full_current_native_equal':True,'changed_basis_equal_except_exact_source_operation_id':True,'affected_native':z['affected_native'],'current_native':z['current_head_native'],'changed_basis_native':z['changed_basis_native'],'resolution_rationale':rationale})
o={'id':'T-0830/individual-dependency-resolutions-v5','actor':'Codex / exact independent Astra actual203 full current review','reason':'201 individual approved retained pairs after136 exact five-read/blocked-sixth changes; one omitted copy caveat corrected in source operation. Historical/stronger/OWNER and original bindings retained.','dependencyReviewVersion':2,'changes':[],'resolve':res};p=D/'operation-resolutions-v5.json';p.write_text(json.dumps(o,ensure_ascii=False,indent=2)+'\n');t=D/'individual-resolution-table-v5.json';t.write_text(json.dumps({'source_operation_sha256':hashlib.sha256((D/'operation-ordered-v5.json').read_bytes()).hexdigest(),'requests':rows,'exact_approved_pairs':201,'unmatched_pairs':0,'mismatched_full_payloads':0,'review_input_sha256':hashlib.sha256(Path('evaluations/T-0830/independent/actual-pending203-review-v1.json').read_bytes()).hexdigest()},ensure_ascii=False,indent=2)+'\n');print({'operation_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'table_sha256':hashlib.sha256(t.read_bytes()).hexdigest(),'requests':len(rows)})
