import sqlite3,json,hashlib
from pathlib import Path
D=Path('evaluations/T-0830/implementation');C=sqlite3.connect('file:genealogy2/data/research.sqlite?mode=ro',uri=True);C.row_factory=sqlite3.Row;op=json.load(open(D/'operation-candidate-v2.json'));rows=[];objects=[]
for cand in op['changes']:
 oid=cand['id'];r=C.execute('SELECT *FROM current_revision WHERE object_id=?',(oid,)).fetchone()
 if r is None:objects.append({'object_id':oid,'old_native':None,'candidate':cand});rows.append({'object_id':oid,'field':'new_object','old_value':None,'new_value':cand,'support':cand['evidence'],'source_disposition':'Exact bounded new extraction/audit/review in settled source-decisions-v3; no new unidentified person or LIFEpass.'});continue
 assert r['version']==cand['expectedVersion'];data=dict(C.execute('SELECT *FROM '+r['kind']+' WHERE revision_id=?',(r['id'],)).fetchone());orig=[dict(e)for e in C.execute('SELECT *FROM origin WHERE revision_id=? ORDER BY rowid',(r['id'],))];ev=[dict(e)for e in C.execute('SELECT *FROM dependency WHERE revision_id=? ORDER BY rowid',(r['id'],))];native={'revision':dict(r),'data':data,'origins':orig,'evidence':ev};api={**{'data.'+k:(json.loads(v)if k.endswith('_json')and v is not None else v)for k,v in data.items()if k!='revision_id'},'disposition':r['disposition'],'evidenceStatus':r['evidence_status'],'rationale':r['rationale'],'caveat':r['caveat'],'origins':[{'unit':e['unit_id'],'coverage':e['coverage'],'note':e['note']}for e in orig],'evidence':[{'object':e['basis_revision_id'].rsplit('@',1)[0],'version':int(e['basis_revision_id'].rsplit('@',1)[1]),'role':e['role'],'note':e['note']}for e in ev]}
 if r['kind']=='record':
  native['assets']=[dict(e)for e in C.execute('SELECT *FROM record_asset WHERE revision_id=? ORDER BY rowid',(r['id'],))];native['media']=[dict(e)for e in C.execute('SELECT *FROM record_media WHERE revision_id=? ORDER BY rowid',(r['id'],))];api['assets']=[{'path':e['asset_path'],'region':e['region']}for e in native['assets']];api['media']=[{'id':e['asset_id'],'region':e['region']}for e in native['media']]
 objects.append({'object_id':oid,'old_native':native,'candidate':cand,'retains':[]})
 for f,old in api.items():
  val=cand['data'][f[5:]]if f.startswith('data.')else cand[f]
  if val==old:objects[-1]['retains'].append({'field':f,'old_and_new_equal':True});continue
  rows.append({'object_id':oid,'old_revision_id':r['id'],'version':r['version'],'field':f,'old_value':old,'new_value':val,'support':cand['evidence'],'source_disposition':'Settled five-read/blocked-sixth source-decisions-v3 and independent exact13group current-field consequence; candidate only, rebind disposition pending. Old revisions/origins and protected facts retained; see candidate fullbody/caveat for exact subject/source/time/field scope.'})
x={'schema':'individual-consequence-table/1','task':'T-0830','baseline_journal':505,'pending':0,'operation':{'path':str(D/'operation-candidate-v2.json'),'sha256':hashlib.sha256((D/'operation-candidate-v2.json').read_bytes()).hexdigest()},'source_authorities':[{'path':str(q),'sha256':hashlib.sha256(q.read_bytes()).hexdigest()}for q in [Path('evaluations/T-0830')/n for n in ['primary/source-decisions-v3.json','primary/full-relevant-extraction-v2.json','independent/source-concurrence-and-waiting-candidate-v1.json','independent/consolidated-consequence-requirements-v2.json']]],'fields':rows,'objects':objects,'prior_candidate_transform_history':'individual-transform-consequences-v2.json','history_note':'Candidatev1 table uses exact livebaseline505→candidate, not intermediate transform values; source/consequence approval and numeric rebind decisions pending.'};p=D/'individual-consequence-table-candidate-v2.json';p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'field_rows':len(rows),'objects':len(objects)}))
