import pathlib,json,hashlib,shutil
R=pathlib.Path.cwd();D=R/'evaluations/T-0811';I=D/'implementation';S=I/'stage477-v2';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();axes=json.load(open(S/'final-axis-differences-and-relation-proof.json'));assert axes['persons']==536 and [x['person']for x in axes['all_person_axis_differences']]==['P-0016'];assert axes['all_relation_native_exact']and len(axes['relations'])==8;result=json.load(open(S/'initial-result.json'));assert result['state']=={'journal_head':477,'pending':0};assert json.load(open(S/'actual-pending-full.json'))==[]and json.load(open(S/'actual-pending-contexts-initial.json'))==[];inv=json.load(open(S/'inventory-full.json'));p=next(x for x in inv['people']if x['id']=='P-0016');assert p['identityReview']['outcome']=='passed'and p['identityReview']['usable'];assert p['treeEffect']['outcome']=='supporting'and p['treeEffect']['usable'];assert p['lifePictureReview']['outcome']=='failed'and p['lifePictureReview']['usable'];controls=[]
for pid in ['P-0269','P-0270']:
 b=json.load(open(R/'evaluations/T-0810/implementation/stage476-v1'/(pid+'-pedigree.json')));a=json.load(open(S/(pid+'-pedigree.json')));key=lambda x:json.dumps(x,sort_keys=True);bs={key(x)for x in b['paths']};assert bs<={key(x)for x in a['paths']};added=[x for x in a['paths']if key(x)not in bs];assert len(b['paths'])==37 and {x['person']for x in added}=={'P-0016'};controls.append({'root':pid,'baseline':37,'final':len(a['paths']),'all_old_paths_exact':True,'added_paths':added})
for name in ['verify.json','verify-assets.json']:
 v=json.load(open(S/name));assert v['ok']and not v['errors']
baseline=json.load(open(D/'preparation/baseline-state-v1.json'));assert sha(R/'genealogy2/data/research.sqlite')==baseline['main']['sha256'];qualified={'task':'T-0811','state':result['state'],'literal12_full_native_exact':True,'full216_retains_exact':True,'actual_pending_empty':True,'individual_dependency_resolutions':0,'no_synthetic_resolutions':True,'old44nonderived_rows_order_preserved':True,'persons':536,'nonfocal535_full_axes_exact':True,'relations8_full_native_exact':True,'focal_identity':p['identityReview'],'focal_tree':p['treeEffect'],'focal_legacy_full_contract':p['lifePictureReview'],'legacy_backing_revision':'ASSESSMENT-P0016@1→@2 exact source-approved qualifications; failed/fullcontract scope unchanged,no native LIFE created','pedigree_controls':controls,'verify_assets_pass':True,'new_originals':0,'new_media':0,'main476_unchanged':True,'attempts_preserved':['V1 dependency UNIQUE rejection, all50/order exactrollback andemptyjournal','V2 onlytwo namednewappends removed, fresh476→477 acceptedpending0'],'elapsed_seconds':{'rejected_initial':json.load(open(I/'stage477-v1/failure-preserved.json'))['elapsed_seconds'],'accepted_initial':result['elapsed_seconds'],'final_readers':json.load(open(S/'reader-capture-result.json'))['elapsed_seconds']},'model_usage':'unknown; root captures after allfinalresponses','canonical_apply':'Root only, worker no canonicalwrites'};q=S/'qualified-final-result-v1.json';assert not q.exists();q.write_text(json.dumps(qualified,ensure_ascii=False,indent=2)+'\n');N=D/'preparation/normative-snapshots-final-v1';assert not N.exists();N.mkdir()
for name in ['AGENTS.md','wotan/README.md','wotan/dev-log/T-0811.md','wotan/dev-log/T-0237.md','wotan/dev-log/T-0241.md','genealogy2/docs/working.md','docs/research/person-contract.md']:
 shutil.copyfile(R/name,N/name.replace('/','__'))
paths=[x for x in D.rglob('*')if x.is_file()and '__pycache__'not in x.parts and x.suffix!='.pyc'and 'final-source-gate'not in x.name and x.name!='final-manifest-v1.json'];paths +=[R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py']
for pin in json.load(open(D/'preparation/locked-current-input-manifest-v1.json'))['files']:paths.append(R/pin['path'])
paths.append(R/'PROJECT-CONTROL.md');files=[{'path':str(x.relative_to(R)),'sha256':sha(x)}for x in sorted(set(paths))];pin=lambda x:{'path':str(x.relative_to(R)),'sha256':sha(x)};manifest={'task':'T-0811','baseline_state':{'journal_head':476,'pending':0},'baseline_main_sha256':baseline['main']['sha256'],'final_state':result['state'],'stage_database':pin(S/'stage.sqlite'),'operations':[pin(I/'operation-v2.json')],'consequence_tables':[pin(I/'consequence-table-v2.json')],'qualified_result':pin(q),'file_count':len(files),'files':files,'canonicalApproval':False};f=D/'final-manifest-v1.json';assert not f.exists();f.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');print('manifest',sha(f),'pins',len(files),'DB',sha(S/'stage.sqlite'))
