import json,pathlib,hashlib,datetime
B=pathlib.Path('evaluations/T-0781');O=B/'independent-review';S=B/'exact16-fresh-stage-v1'
def rd(p):return json.loads(pathlib.Path(p).read_text())
def pin(p):return {'path':str(p),'sha256':hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()}
h=rd(S/'complete-stage-result-and-Astra-handoff.json');p=S/'all-actual-individual-request-and-complete-dependency-context-routing.json';d=rd(p);np=S/'complete-actual-target-request-history-upstream-native-payloads.json';n=rd(np)['objects']
reasons=[
'Anna Albertinas namn/radperson består. M@2 har den egna uttryckliga D:r-rollen, korrigerad caveat och R49@2/fullTR-stöd. Begäran gäller historisk M@1 och är sakligt omprövad genom denna redan införda efterföljare; inga ytterligare ändringar behövs.',
'ID53@1 binder samma namngivna Anna Albertina-rad till samma P53. Recordrättelsen ändrar egenortscellen, inte radkorrelationen. ID innehåller ingen egen födelseort; ursprunglig M53@1-grund, accepted/CORROBORATED och avgränsad identitet behålls. E53s separata ort-null och O53@2 återställer inte den gamla dittohärledningen.',
'Catharina Johannas namn/radperson består. M@2 redovisar D:r på egenrad och explicit R49@2/fullTR. Historisk M@1 är ersatt; ingen ny person eller egen födelseort härleds.',
'O52@2 har redan ersatt falskt födelseortsditto med null/egenblankhet, kvar datum1865-05-11 och samma person. R49@2/M52@2/fullTR exakta stöd. E52s Bygdeå från separat C46 rapport gäller inte C49s tomma cell. Historisk O@1 återtas inte.',
'M53@2 tillför D:r och källgräns men ändrar inte Anna Albertinas namn eller mention/person-ID. Därför behålls hela ID53@1 och dess exakta gamla M53@1-stöd; inget nytt identitetsgodkännande eller automatisk rebind.',
'ID52@1 binder samma Catharina Johanna-rad/person. R49@2s falsktditto-korrigering påverkar inte denna avgränsade identitetslänk. ID saknar egen födelseortsutsaga; accepted/CORROBORATED och M52@1-stöd bevaras. Separata C46-stödet för rapporterad födelseförsamling hålls separat.',
'O48@2 har rättat systernamnskopian till Magdalena Euphrosyne med R49@2/fullTR. Befintliga familjeband och äldre sonAnders1862 består; varken uttömt barnantal eller kontinuerlig fysisk hemvist påstås genom upplösningen. Historisk O@1 ersatt.',
'Faderns eget Anders Andersson är oförändrat i R49@2; dotternamn, ditto och årsfält ändrar inte O50s name_report. Hela currentO50@1 med R49@1-stöd och historisk två-längds-caveat behålls, ingen ny oberoende namnröst eller rebind.',
'ID57@3 har redan rättat Magdalena-namnet och explicit M57@2/fullTR, samma P57/accepted/TRANSCRIBED. Äldre ID@1CORROBORATED är historisk och ska inte återadopteras; ID@2 ersatt. Familjekontinuitet ger inget andra eget personbelägg eller ny identitetsgrad.',
'READ@2 redovisar nu full avgränsad sexradsprövning och exakta läsreservationer med R49@2/fullTR. Historiska READ@1s olästa-kolumn/ditto-premiss har uttryckligen ersatts. Detta är källtäckning, inte personkontraktsgodkännande eller generell källuttömning.',
'TR@2 har redan korrekt Magdalena29/5/B:å, yngre tre egna ortblankheter och tydligt nyoriginal-rationale; hela utvinningen hänvisas till fullTR. Record@2/fullTR-stöd är uttryckliga. Historisk feltext@1 behålls som historik, ingen tredje läsning behövs.',
'F50s bonde/f.d. hemmansägare står kvar: B:n på egen C49rad är oförändrat och senare C44/C569 ger separat tidsbunden titel. Osäkra mantalsmarginalen ger ingen ny markäganderätt, förvärvsdag eller liv1913. Hela F@1 och tre ordnade gamla stöd R49@1/R44@1/R569@1 behålls utan automatisk rebind.',
'EP52@1 är enbart samma persons principal-deltagande i samma födelsehändelse. E52@2 behåller datum/place/eventtyp/status; caveat klargör C49blankhet och rapporterad Bygdeå från C46. EPs egenföddpost-oläst-caveat är fortsatt riktig. Hela EP@1 och E52@1-grund kvar, ingen starkare födelse- eller identitetsgrad.',
'O53@2 har redan tagit bort falsktditto-normalisering, null i eget reported_birth_place, samma Anna/date1871-09-28, R49@2/M53@2/fullTR. Separat E53place-null är inte geografiskt motbevis. Historisk O@1 är ersatt och återadopteras inte.',
'M57@2 har redan rättat samma dotterrads namn till Magdalena Euphrosyne och D:r; R49@2/fullTR ger samma historiska post, inte ny självständig person. Historisk Margareta@1 ersatt, statusTRANSCRIBED oförändrad.',
'M52@2 tillför egen D:r och förtydligad caveat men Catharina Johannas namn/radperson är oförändrad. Därför behålls ID52@1 med M52@1-grund och samma accepted/CORROBORATED; ingen ny identitetsprövning eller blanketversionsuppdatering.',
'O57@2 har redan rättat namn och dag till Magdalena Euphrosyne1863-05-29 och egen B:å, sameperson/familj, uttryckliga R49@2/M57@2/fullTR. Egen födelsenotis är fortsatt oläst; äldre24maj/ditto@1 får inte återadopteras.'
]
assert len(reasons)==len(d['requests'])==17
rows=[]
for i,(r,reason) in enumerate(zip(d['requests'],reasons)):
 a=n[r['affected_exact_revision_id']];cur=n[r['affected_current_revision_id']];changed=n[r['changed_exact_revision_id']];old=n[r['changed_previous_revision_id']]
 rows.append({'request_id':r['actual_request']['id'],'actual_request':r['actual_request'],'actual_request_pointer':f'/requests/{i}','affected_exact_revision_id':a['id'],'retained_current_revision_id':cur['id'],'changed_exact_revision_id':changed['id'],'changed_previous_revision_id':old['id'],'full_histories':r['full_histories'],'own_decision':'RESOLVE_AS_ALREADY_EXPLICITLY_SUPERSEDED' if a['id']!=cur['id'] else 'RESOLVE_RETAIN_ENTIRE_CURRENT_WITH_EXACT_OLD_BASES','own_rationale':reason,'current_ordered_evidence':cur['evidence'],'new_native_revisions_needed':False,'new_rebind_needed':False,'full_current_payload_pointer':'/objects/'+cur['id'],'full_affected_history_pointer':'/objects/'+a['id'],'changed_full_payload_pointer':'/objects/'+changed['id'],'old_changed_payload_pointer':'/objects/'+old['id'],'primary_runtime_grade_or_resolution_candidate_seen_before_freeze':False})
ids=sorted({rid for r in d['requests'] for arr in r['full_histories'].values() for rid in arr})
out={'task':'T-0781','status':'INDEPENDENT_ACTUAL17_ASSESSMENT_FREEZE_BEFORE_PRIMARY_RUNTIME_GRADES','saved_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'stage_handoff_pin':pin(S/'complete-stage-result-and-Astra-handoff.json'),'stage_DB_pin':h['stage_DB_pin'],'request_pin':pin(p),'native_context_pin':pin(np),'own_pre_stage_gate':pin(O/'two-source-complete-exact174-pre-stage-source-consequence-gate-v1.json'),'actual17_own_freeze_complete':True,'rows':rows,'counts':{'requests':17,'historical_affected_already_superseded':10,'retained_current_requests':7,'new_native_revisions':0,'new_rebinds':0},'own_reading_scope':{'whole_actual_request_objects_read':17,'whole_affected_changed_current_histories_native_read_ids':ids,'additional_whole_direct_support_native_read_ids':['R-f81045d395fcb687a2417ed6@1','R-709a6f58d922fa1df3bb75c1@1','R-23a0a3adc573124b3fb1c938@1','S-0042@1'],'whole398_or208origin_unit_reading_claim':False,'prior_source_and174_API_judgments_reused':True,'truncation_repair':'Initial combined30native display truncated middle; all missing M53new/M57/O48/O50/O52 and bothR49 reprinted in bounded complete second output. No credit from truncated text.','new_originals':0},'remaining':'Independently verify actual174 API/native and old/protected exact result binding, then compare primary actual17 instructions and built resolution bytes. Freeze itself is no runtime or finalcanonical approval.','runtime_authorized':False,'final_global_PASS':False}
p=O/'actual17-independent-own-source-consequence-freeze-v1.json';assert not p.exists();p.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(pin(p))
