import json,pathlib,hashlib
B=pathlib.Path('evaluations/T-0781');O=B/'independent-review';S=B/'source-review'
def rd(p):return json.loads(pathlib.Path(p).read_text())
def pin(p):return {'path':str(p),'sha256':hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()}
f=O/'actual17-independent-own-source-consequence-freeze-v1.json';own=rd(f);pp=S/'actual17-individual-primary-source-consequence-decisions-v1.json';p=rd(pp);gp=S/'actual17-complete-primary-pre-resolution-source-gate-v1.json';g=rd(gp);n=rd(own['native_context_pin']['path'])['objects'];rows=[]
assert g['all_actual_requests_source_approved'] and not g['source_questions_open'];assert pin(g['stage_DB_pin']['path'])==g['stage_DB_pin']==own['stage_DB_pin'];assert len(p['rows'])==len(own['rows'])==17
for i,(a,b) in enumerate(zip(own['rows'],p['rows'])):
 assert a['request_id']==b['request_id'] and a['actual_request']==b['actual_request'];assert a['retained_current_revision_id']==b['retained_current_revision_id'];assert a['current_ordered_evidence']==b['current_ordered_evidence_retained']==n[b['retained_current_revision_id']]['evidence'];assert b['source_approved'];assert b['native_changes_required']==b['evidence_rebinds_required']==[];assert b['resolution_instruction']['request']==a['request_id']
 path=b['exact_historical_dependency_path']; assert path[0]['revision_id']==a['affected_exact_revision_id'];assert path[-1]['basis_revision_id']==a['changed_previous_revision_id']
 for j,e in enumerate(path):
  assert e in n[e['revision_id']]['evidence'];
  if j:assert path[j-1]['basis_revision_id']==e['revision_id']
 assert (a['own_decision']=='RESOLVE_AS_ALREADY_EXPLICITLY_SUPERSEDED')==(b['disposition']=='already_superseded_by_source_approved_current_revision')
 rows.append({'request_id':a['request_id'],'actual_request':a['actual_request'],'retained_current_revision_id':a['retained_current_revision_id'],'own_frozen_scope_pointer':'/rows/'+str(i)+'/own_rationale','primary_scope_pointer':'/rows/'+str(i)+'/individual_source_scope','primary_instruction_pointer':'/rows/'+str(i)+'/resolution_instruction','own_frozen_decision':a['own_decision'],'own_frozen_rationale':a['own_rationale'],'primary_source_scope':b['individual_source_scope'],'own_semantic_comparison':'AGREE: exact affected/current/source-version/path and retained basis conclusions match own pre-comparison freeze. Primary literal instruction read in full, including corrected scope boundaries.','exact_historical_path_verified_against_actual_native':path,'approved_resolution_instruction':b['resolution_instruction'],'no_new_native_or_rebind':True})
assert g['approved_request_ids']==[r['request_id'] for r in rows];assert g['approved_individual_resolution_instructions']==[r['approved_resolution_instruction'] for r in rows]
out={'task':'T-0781','status':'INDEPENDENT_ALL17_ACTUAL_REQUEST_MEANING_AND_LITERAL_INSTRUCTIONS_PASS','all_actual_requests_independently_approved':True,'own_precomparison_freeze':pin(f),'primary_decisions':pin(pp),'primary_gate':pin(gp),'actual174_result_review':pin(O/'actual174-native-protected-history-and-complete-result-binding-v1.json'),'stage_DB_pin':own['stage_DB_pin'],'stage_journal':441,'stage_pending':17,'rows':rows,'approved_request_ids':[r['request_id'] for r in rows],'counts':own['counts'],'findings_open':[],'reading_limit':'Each17 literal resolution text and source/current scope read, matched to own earlier freeze. Initial combined display truncated part ofrow7; whole row7 reprinted before approval. Histories/oldbasis checks are per actual request, no blanket count approval. No new original reading.','resolution_operation_bytes_reviewed':False,'final_complete_package_PASS':False,'runtime_authorized':False,'canonical_apply_authorized':False}
q=O/'actual17-complete-independent-pre-resolution-meaning-and-instruction-gate-v1.json';assert not q.exists();q.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(pin(q))
