import json,sqlite3,hashlib,datetime
from pathlib import Path
b=Path('evaluations/T-0780');out=b/'preparation/C0060-additive-presentations-v1';c=sqlite3.connect('file:'+str(b/'preparation/baseline-j281.sqlite')+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;known={o['id']:o for o in json.load(open(b/'preparation/selected/complete-current-impact-and-support-package-v1.json'))['objects']}
for p in [b/'implementation/dependency-preparation-v1/current-full-native-objects-v1.json',b/'implementation/dependency-preparation-v1/additional-context-full-native-objects-v2.json']:
 for o in json.load(open(p))['objects'].values():known[o['id']]=o
v1p=out/'full-current-person-and-exact-support-dictionary-v1.json';v1raw=v1p.read_bytes();x=json.loads(v1raw);outside=[];checks=[];order=[]
def rowset(z):return sorted(json.dumps(r,ensure_ascii=False,sort_keys=True,separators=(',',':')) for r in z)
for o in x['objects']:
 rid=o['id'];actual=[dict(z) for z in c.execute('SELECT * FROM dependency WHERE revision_id=? ORDER BY basis_revision_id,role',(rid,))];assert rowset(actual)==rowset(o['evidence'])
 if rid in known:
  k=known[rid];assert rowset(k['evidence'])==rowset(actual);o['evidence']=k['evidence'];basecols=['revision_id','unit_id','coverage','note'];assert rowset([{f:z[f] for f in basecols} for z in k['origins']])==rowset(o['origins']);assert k['data']==o['data'];checks.append({'revision_id':rid,'exact_origin_rows':'PASS','whole_data_including_embedded_JSON_array_order':'PASS','exact_evidence_row_multiset':'PASS','evidence_array_order':'prior frozen preserved'})
 else:
  if o['evidence']!=actual:order.append({'revision_id':rid,'old_query_order':o['evidence'],'canonical_cli_order':actual})
  o['evidence']=actual;outside.append(o)
x['evidence_order_policy']='Already covered objects keep prior frozen array order after exact evidence-row multiset equality. Outside objects use canonical readCurrent SELECT WHERE revision_id ORDER BY basis_revision_id,role (domain.mjs:243); embedded data JSON arrays never sorted or normalized.';p=out/'full-current-person-and-exact-support-dictionary-v2.json';p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');q=out/'objects-outside-prior-frozen-dictionaries-v2.json';q.write_text(json.dumps({'baseline_journal':281,'count':len(outside),'metadata_only_existing_knowledge_not_new_claims':True,'evidence_order_policy':x['evidence_order_policy'],'objects':outside,'exact_versions':[o['id'] for o in outside]},ensure_ascii=False,indent=2)+'\n');cp=out/'full-origin-and-embedded-array-comparison-v2.json';cp.write_text(json.dumps({'covered_count':len(checks),'checks':checks,'outside_evidence_query_order_amendments':order,'v1_preserved':hashlib.sha256(v1raw).hexdigest(),'order_changes_are_top_level_SQL_relational_presentation_only':True},ensure_ascii=False,indent=2)+'\n');assert v1p.read_bytes()==v1raw;prior=json.load(open(out/'additive-presentation-and-native-input-freeze-v1.json'));assert all(hashlib.sha256(Path(pin['path']).read_bytes()).hexdigest()==pin['sha256'] for pin in prior['pins']);pins=[{'path':str(z),'sha256':hashlib.sha256(z.read_bytes()).hexdigest(),'bytes':z.stat().st_size} for z in [p,q,cp,out/'additive-presentation-and-native-input-freeze-v1.json']];f={'task':'T-0780','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline_journal':281,'presentation_full_count':9,'presentation_overview_count':9,'prior_freeze_allpins_unchanged':True,'preferred_fullnative_dictionary':str(p),'preferred_outside_dictionary':str(q),'covered_objects':len(checks),'outside_objects':len(outside),'outside_current':sum(o['current'] for o in outside),'outside_older':sum(not o['current'] for o in outside),'covered_origin_meta_data_array_checks':'PASS','new_original_reads':0,'stage_or_canonical_applies':0,'source_decisions_need_root_additive_lock':True,'pins':pins};(out/'additive-input-order-origin-amendment-freeze-v2.json').write_text(json.dumps(f,ensure_ascii=False,indent=2)+'\n');print({'covered_origin_full_data_PASS':len(checks),'outside':len(outside),'canonical_outside_order_amendments':len(order)})
