import json,hashlib,pathlib,datetime
out=pathlib.Path('evaluations/T-0773/sol-primary')
cases=json.loads(pathlib.Path('evaluations/T-0773/source-input/cases.json').read_text())
def f(raw='',state=None,q=''):
 return dict(raw=raw,state=state or ('read' if raw else 'empty'),qualifier=q)
def row(id,**kw):return dict(row_id=id,fields={k:(v if isinstance(v,dict) else f(v)) for k,v in kw.items()})
def save(c,scope,headers,rows,notes,unc):
 image=next(x for x in cases if x['case']==c)
 actual=hashlib.sha256(pathlib.Path(image['image']).read_bytes()).hexdigest()
 assert actual==image['sha256']
 data=dict(case=c,image_sha256=actual,scope=scope,headers=headers,row_ids=[r['row_id'] for r in rows],rows=rows,boundary_notes=notes,uncertainties=unc)
 (out/(c+'-raw.json')).write_text(json.dumps(data,ensure_ascii=False,indent=2)+'\n')
 (out/(c+'-summary.md')).write_text('# '+c+' — självständig råutvinning\n\n'+scope+'\n\n'+ '\n\n'.join(notes)+'\n\nReservationer: '+ '; '.join(unc)+'\n')
save('A','SCB Hyltinge målpost 15; hela målposten, månadsankare rad12 och vidareföring rad13–14. Årtal saknas på målpost/rad12 i synligt utsnitt.',
 {'1':'Inskrifningens löpande årsnummer','2':'Född år och månad','3':'dag','4-7':'Räknad till församlingen: lefv.född m/k; dödfödd m/k','8':'Dopnamn (förnamn)','9':'Föräldrar: namn, yrke, nationalitet/religionsbekännelse om främmande, bostad, tid för äktenskaps ingående','10':'Födda år, dag och månad','11-14':'Modern: Gift; Enka eller frånskild; Trolofvad; Ogift','21':'Särskilda anteckningar'},
 [row('12-anchor',entry_number='12',birth_month='maj',birth_year=f('',q='Ej angivet på denna synliga rad'),birth_day='2'),row('13-anchor',entry_number='13',birth_month=f('〃',q='ditto rad12 maj'),birth_day=f('〃',q='ditto rad12 2')),row('14-anchor',entry_number='14',birth_month=f('〃',q='ditto rad12 via rad13: maj'),birth_day='20'),
 row('15-child',entry_number='15',birth_year=f('',q='1919 på rad16 får inte uppföras som målpostens år'),birth_month=f('〃',q='maj från rad12 genom rad13–14'),birth_day='11',alive_m='',alive_k='1',stillborn_m='',stillborn_k='',forenames='Maj Amalia',legitimacy_note=f('u. ä.',q='handskrivet under namnet; inget påstående om faderskapets säkerhet')),
 row('15-father',role='Fader:',surname='Eriksson',forenames='Axel Edvard',occupation=f('järnv. arb.',q='förkortning läst; exakt expansion inte införd'),residence=f('[kann/kvarn?]…70','uncertain','Bostadstext och 70 synliga; ordet före70 är inte säkert'),nationality='',religion='',birth_year='81',birth_day='20',birth_month=f('3?','uncertain','datum överkorsat/omramat; nämnaren inte säkert'),date_marks=f('omramning/diagonal och horisontell överstrykning','read','bevaras; inte automatiskt avskrivet som ogiltigt'),marriage_date=''),
 row('15-mother',role='Moder:',surname=f('Ekholm','uncertain','läst förslag; bokstäver mitten kräver reservation'),forenames='Hulda Amalia',maiden_name=f('f. Ålund','uncertain','prefixet och Ålund är läsförslag'),additional_name_note=f('änka','uncertain','ordet efter födelsenamnet liknar änka, inte säkert sammanfogad efternamnsform'),birth_year='77',birth_day='25',birth_month='9',gift='',enka_franskild=f('1 (inringad)',q='kol12'),trolovad='',ogift=f('v',q='kol14; båda markeringarna bevaras'),nationality='',religion='',separate_birthplace='',special_notes=f('',q='målpostens anmärkningsfält tomt; klammer vid vänster fältgräns finns'))],
 ['Post15 består av barnraden och två föräldrarader. Rad16 börjar med eget 1919 och juli23, samt egen Anna-Lisa; det året/datumet är inte målpost15:s datum.','Enka/frånskild-kolumnen har inringad1 och Ogift har v på målposten. Ingen vald ensam normaliserad civilstatus.','Långt datum-/gränsbläck kring faderns födelsedatum och vänster klammer i anmärkningsfältet är bevarade. G.15/10 hör till rad14 ovanför, inte till15.'],
 ['Målpostens födelseår är inte säkert från bilden.','Faderns bostadsord och födelsedatumets månad osäkra.','Moderns efternamn, födelsenamnsprefix och tillägg änka behöver reserveras.','Tryckt Dopnamn innehåller förnamn; ingen separat dopdagkolumn i denna tabell.'])
# B enumerate every logical column, including blank fields.
BH={'page':'43; utdrag för municipalsamhället i Flens församling, Villåttinge kontrakt, Södermanlands län,31/12 1930','left':'Församlingsbokuppslag; hushåll; By/lägenhet, namn och familjeställning','2':'Huvudyrke; ställning i yrket','2(1)':'Biyrke','3':'Icke döpt/icke av sv.kyrkan döpt; stam; lyte','5':'Födelseår och ort','m':'Moderns kyrkobokföringsort om annan än barnets födelseort','7-8':'Ogift m/kv; Gift m/kv; Änkling; Änka; Frånskild m/kv; Vigselår','9-10':'År för församlingsboksuppslaget; Sista gången inflyttad till bostadskommunen, från plats, år','12':'Dopen sv.kyrkan begått','14':'Trosbekännelse, nationalitet, frånvarande, uttagit flyttningsbetyg','right':'Skolbildning; barn levande men ej boende i föräldrahemmet; redan döda; inkomst och förmögenhet'}
def br(id,name,role,year,place,occ='',status='',mar='',book='',inplace='',inyear='',school='',**extra):
 d=dict(name=name,role=role,birth_year=year,birthplace=place,main_occupation=occ,occupation_statistics='',secondary_occupation='',baptism_stam_lyte='',mother_registration_place='',ogift_m='',ogift_kv='',gift_m='',gift_kv='',ankling='',anka='',franskild_m='',franskild_kv='',marriage_year=mar,book_year=book,last_move_from=inplace,last_move_year=inyear,baptism_sv_kyrkan='n',religion='',nationality='',absent='',move_certificate='',school_code=school,children_outside_parental_home='',children_deceased='',income_wealth='')
 if status:d[status]='/'
 d.update(extra)
 return row(id,**d)
save('B','Hela fysiska blocket på uppslag563 mellan Björkhem h:1 och Björkhem h:2: sju namnrader. Separata hushållsklamrar urskiljs; familjeroller läses av skrivna prefix, inte enbart eftergemensamt uppslag.',BH,
 [br('563-1','Anna Fredrika Pettersson [Törin?]','', '62','Åsmo, Sthmsl.','2-606-00','anka',book='23',inplace='232 Floda',inyear='20',school='3',occupation_statistics=f('2-606-00; läg. äg.','uncertain','pennkod och förkortning; ingen full expansion säker'),children_outside_parental_home=f('og / inget yrke','uncertain','noteringens nedre räckvidd mot rad2 osäker')),
 br('563-2',f('Karl Ludvik Godvik','uncertain','Ludvik läses tydligare än locatorns Gustaf; efternamnets slut ej helt säkert'),'','61','d:o Mellösa,Söd.l.','Maskinarb.','gift_m','86','',f('242 Skederi','uncertain','ortens bokstäver reserveras'),'00','3',occupation_statistics='2-623+00',children_outside_parental_home=f('222-5 / fabr.arb. / 04-0-1-0-00','uncertain','pennstatistik; återger råkod utan utvidgad tolkning')),
 br('563-3','Charlotta Wilhelmina Larsson','h.','67',f('d:o [Söd.l.]',q='ditto ort till Karl: Mellösa; län ditto'),'3','gift_kv',f('〃',q='86 från Karl'),'',f('—〃—',q='Skederi-förslag från Karl'),'00','3',religion='Baptist',move_certificate=f('23 / blå V','uncertain','placering nära tros-/flyttningsfält; håll tecken och år åtskilda')),
 br('563-4',f('Arne Godvig Ingvar','uncertain','mellannamn Godvig läsförslag'),f('[f.?]d.s.','uncertain','möjligt inledande f. före d.s., inte säkert löst'),'15','Flen','Polerare','ogift_m',inplace='',inyear='',school='3',baptism_sv_kyrkan='—',occupation_statistics='222-51',income_wealth=f('9 —',q='kolumnen inkomst och förmögenhet; ingen valuta angiven')),
 br('563-5',f('Astrid Charlotta [Karlsson?]','uncertain','Astrid och Charlotta läsförslag; efternamnet överlagrat av kod och gränsbläck'),'','97','Skedvi, Vstl.',f('—〃—',q='ditto Polerare från föregående rad'),'franskild_kv','25','',f('510 Sundbyberg',q='råplats och kod'),'26','3',occupation_statistics='2-222-51',children_outside_parental_home='yk',income_wealth='4 —',name_marks=f('kraftig horisontell linje över/utmed namnradens övre kant',q='kan vara hushålls-/gränsmarkering; inte säker namnstrykning')),
 br('563-6','Emmy Solveig Charlotta','d.','14','Flen','5','ogift_kv',inplace=f('—〃—',q='Sundbyberg från Astrid'),inyear='26',school='4'),
 br('563-7','Karl Ingvar','s.','21',f('Östermalm,Sthm → Flens','uncertain','Östermalm,Sthm överstruket; röd korrigering Flens-läsförslag'),'4','ogift_m',inplace=f('—〃—',q='Sundbyberg från Astrid'),inyear='26',school='4',mother_registration_place='500')],
 ['Björkhem h:1 är understruket före Anna. Björkhem h:2 börjar efter Karl Ingvar och före uppslag564; inte en person i blocket.','Anna har egen hushållsmarkering1. Nästa klammer omfattar Karl, h.Charlotta och d.s.Arne och stängs vid linjen ovan Astrid. Ett nytt1 och en klammer omfattar Astrid,d.Emmy,s.Karl Ingvar.','Prefix på Arne liknar [f.?]d.s.; d.s. kan vara dotterson men ett möjligt f-prefix är inte säkert tolkat. Familjeblockets anknytning fastställer inte Arnes ej namngivna mor här.','Över-/gränsbläck och redigerad födelseort bevaras. Koder och skolbildningsnummer får inte självständiga ospecificerade innebörder.'],
 ['Locator Karl Gustaf harmoniseras inte in i bildens Karl Ludvik-läsförslag.','Namnens svåraste slut, inflyttningsort Skederi och en del pennkoder är osäkra.','Barnstatistikens radanknytning särskilt Anna/Karl är inte helt säker.','Arnes baptismkolumn visar streck; inte evidens för ej döpt.','Uppslag563 och sju namnrader är inte ett enda släkt-/administrativt hushåll.'])
save('C','SCB födelseutdrag Värsås annex1886, nr14 Bernhard Natanael; hela målpostens barn-/föräldra-/status-/anmärkningsfält. Rad11 används som aprilankare och rad13/15 som gränskontroll.',
 {'page':'1886, Värsås annex församling i Frökinds prosteri, Skara stift, Skaraborgs län,3 blad','1-5':'Nummer; födelseår/månad/dag; kön m/q','6':'De lefvande födda barnens dop- eller förnamn','7-10':'Äkta m/q; Oäkta m/q','11-14':'Dödfödda: Äkta m/q; Oäkta m/q','15':'Föräldrars namn, embete, yrke, stånd, hemvist, nationalitet/religion om främmande; födelseplats om ej hemorten','16':'Barnet aflidit','17-21':'Modern: gift; enka/frånskild; trolofvad; ejgift; sistfyllda åldersår','22':'Förlossningsbiträdet examineradt','23':'Särskilda anteckningar'},
 [row('11-anchor',birth_year='1886',birth_month='April',birth_day='14'),row('14-child',entry_number=f('14','uncertain','numret delvis täckt på originalet; målpost lokaliserad mellan13 och15'),birth_year=f('1886',q='år i sidhuvud och rad11'),birth_month=f('〃',q='april från rad11 via12–13'),birth_day='19',sex_m='1',sex_q='',forenames='Bernhard Natanael',inline_date=f('1:[?]','uncertain','handskrivet i namnkolumnens högra del; datumliknande, ej separat tryckt dopdagrubrik'),legitimate_m='1',legitimate_q='',illegitimate_m='',illegitimate_q='',stillborn_legitimate_m='',stillborn_legitimate_q='',stillborn_illegitimate_m='',stillborn_illegitimate_q='',child_deceased='',special_notes=f('',q='målpostens fält tomt innanför klammer; rad13 daterad19April1886 ej målpost14')),
 row('14-father',role='Fader:',surname='Eliasson',forenames='Per Wilhelm',occupation=f('heg.','uncertain','förkortning liknar heg./hemäg., inte full ordform'),residence=f('i Djursätra Mellang.','uncertain','plats/hemvist läsförslag; förkortning inte säkert utvidgad'),nationality='',religion='',number_in_age_column=f('36','uncertain','överstruket/avgränsat nummer på fadersrad, inte moderns22 eller en säker åldersuppgift för fadern')),
 row('14-mother',role='Moder:',surname=f('Johansson','uncertain','slutets bokstäver mindre tydliga, råförslag'),forenames='Augusta Viktoria',parenthetical='(1 år)',parenthetical_meaning=f('',q='ingen exakt vigseldag eller säker numerisk kontraktsbetydelse infererad'),gift='1',enka_franskild='',trolovad='',ejgift='',completed_age='22',examined_birth_assistant=f('Ex.',q='markerar examinerat biträde enligt rubrik; identifierar ingen person'),birthplace_if_not_home='',nationality='',religion='')],
 ['Barnnamnet och föräldrarna hör till samma dubbelhöga post. Rader13 och15 har egna anmärkningar; deras datum kopieras inte.','Gränsklammer i kol23 omsluter målposten men inga målpostord. Tal på fadersrader i ålderskolumnen genomstrukna med gränsbläck bevaras separat från moderns sistfylldaålder.','Kön och äkta-status stöds av de tryckta m-kolumnerna; inte av namnet ensamt.'],
 ['Inline1:[?] får inte säkert bli ett dopdatum.','Faderns yrkesförkortning och hemvistförkortning hålls reserverade.','Överstruket tal på fadersrad är36-läsförslag med osäker innebörd.','(1år) är råparentes utan härledd exakt vigseldag.'])
DH={'page':'Värsås, Frökinds prosteri, Skaraborgs län,31/12 1890; sida23 /7ark','1':'Hushållens nummer','2':'By/lägenhet, namn, familjeställning h=hustru,s=son,d=dotter','3':'Yrke, embete,tjänst,näringsfång','4':'Lyte, främmande nationalitet/religionsbekännelse,frånvarande','5-6':'Födelseår och ort','7-14':'Ogift m/q; Gift m/q; Enkling; Enka; Frånskild m/q'}
def cr(id,name,role,year,place,occ='',status='',**extra):
 d=dict(name=name,role=role,birth_year=year,birthplace=place,occupation=occ,ogift_m='',ogift_q='',gift_m='',gift_q='',enkling='',enka='',franskild_m='',franskild_q='')
 if status:d[status]='/'
 d.update(extra)
 return row(id,**d)
save('D','1890 Värsås, sista fyraradiga familje-/hushållsblock på sidan: Per Wilhelm Eliasson,h.Augusta Viktoria Johansson,s.Bernhard Natanael,d.Agnes Maria.',DH,
 [cr('D-1','Per Wilhelm Eliasson','','1830','förs.', 'Hemmansegare','gift_m',lyte='',nationality='',religion='',absent=''),cr('D-2','Augusta Viktoria Johansson','h.','1863','Hogstena Skarab.','', 'gift_q',lyte='',nationality='',religion='',absent=''),cr('D-3','Bernhard Natanael','s.','1886',f('d:o',q='Hogstena Skarab. från Augusta'),'','ogift_m',lyte='',nationality='',religion='',absent=f('mörkt mindre tecken vid kol4:s högra gräns','uncertain','ingen läsbar betydelse')),
 cr('D-4','Agnes Maria','d.','1889',f('d:o',q='Hogstena Skarab. från Augusta via Bernhard'),'','ogift_q',lyte='',nationality='',religion='',absent=f('mörkt mindre tecken vid kol4:s högra gräns','uncertain','ingen läsbar betydelse'))],
 ['Egen klammer och marginell hushållssiffra2?/3? börjar vid Per Wilhelm och omsluter fyra rader; föregående Gustaf Rikard Karlsson hör till föregående block.','Gemensam platsrubrik ovanför flera hushåll läses Djursätra Mellangården; ingen ny platsrad mellan rubriken och målgruppen.','Födelseort på Per är förs. och på Augusta egen Hogstena Skarab.; barnens d:o ankras till Augusta, inte Per.','Transporttal vid sidfoten är sidstatistik, inte en ålder eller hushållsmedlem.'],
 ['Hushållssiffra i vänstermarginalen är osäker och inte år/antal familjemedlemmar.','Djursätra Mellangården och Hogstena-läsning har smärre ortografisk reservation.','Kol4:s små gränstecken på barnraderna ges ingen lyte-/religions-/frånvarobetydelse.'])
EH={'page':'24; Värsås annex, Frökinds kontrakt,Skaraborgs län,31/12 1900','1':'Hushållens nummer, by/lägenhet,namn,familjeställning;titel;icke döpt','2':'Yrke; stam(främmande);lyte','3-5':'Födelseår och ort','7-8':'Ogift m/q; Gift m/q; Enkling; Enka; Frånskild','10':'Trosbekännelse,utträde ur svenska kyrkan,nationalitet,frånvarande'}
def er(id,name,role,year,place,occ='',status=''):
 r=cr(id,name,role,year,place,occ,status,stam='',lyte='',not_baptized='',title='',religion='',left_sv_church='',nationality='',absent='')
 r['fields'].pop('franskild_m');r['fields'].pop('franskild_q');r['fields']['franskild']=f()
 return r
save('E','1900 Värsås: hela tiogradiga administrativa hushållsklammern från Per Wilhelm till sista pigan, före Gustaf...Thors eget hushåll.',EH,
 [er('E-1','Per Wilhelm Eliasson','','30','förs.','Hemmansegare','gift_m'),er('E-2','Augusta Viktoria Johansson','h.','63','Hogstena,Skarab.l.','','gift_q'),er('E-3','Bernhard Natanael','s.','86','förs.','','ogift_m'),er('E-4','Agnes Maria','d.','89',f('d:o',q='förs. från Bernhard'),'','ogift_q'),er('E-5',f('Johan [Alarik?] Gabriel','uncertain','mellannamnets bokstäver osäkra'),'s.','91',f('d:o',q='förs. från Bernhard'),'','ogift_m'),er('E-6','Ragnar Wilhelm','s.','93',f('d:o',q='förs. från Bernhard'),'','ogift_m'),er('E-7',f('Ruth Ingegerd Margareta','uncertain','första namnformen liten/otydlig, Ingegerd läsförslag'),'d.','95',f('d:o',q='förs. från Bernhard'),'','ogift_q'),er('E-8',f('Ester Maria Öbom','uncertain','efternamnsläsning osäker'),'','81',f('Huddinge,Sthmsl.','uncertain','ortens bokstavsform reserverad'),'Piga','ogift_q'),er('E-9',f('Brita [J?] [Herma?] Fride','uncertain','mellannamnsfält svårläst; inte säkert normaliserat'),'','78',f('Frötuna, d:o','uncertain','ortläsning; län ditto Sthmsl. från Ester'),'Dräng','ogift_m'),er('E-10',f('Sofia [Afia?] [Cas... ]','uncertain','sista tjänsteradens namn inte säkert bokstavsläst'),'','77',f('Carls... ,d:o','uncertain','födelseorten ofullständigt läst; län ditto från Ester'),'piga','ogift_q')],
 ['En vänsterklammer med1 omfattar sju familjerader plus tre tjänsterader. Egen klammer börjar först på nästa Gustaf...Thor. Familjen och administrativa hushållet har därför olika antal.','Barnens födelseortankare är Bernhards eget förs.; moderns Hogstena följs inte som ankare över Bernhards egna förs.','Dräng på Brita-namnraden är bevarat och ogiftm-markeringen ger manligt kolumnvärde; namnet får inte ensamt sätta kön.','Ingen egen bebyggelserubrik står i målblockets synliga närhet; ort/fastighet inte uppfylld från en annan målbild.'],
 ['Tjänsternas fullständiga namn och två orter är osäkra; delvis lästa råförslag bevaras.','Johan andra namn och Ruth första namn reserveras.','Födelseårens århundraden är inte nytryckta på varje rad; 30,63,86... återges som råtal.','Blank trosbekännelse/lyte/stamfält bevisar ingen positiv tillhörighet eller hälsostatus.'])
print('saved five raw matrices')
