import json,pathlib,hashlib,datetime,copy
R=pathlib.Path.cwd();D=R/'evaluations/T-0813/candidate-v1';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();read=lambda p:json.loads((R/p).read_text());save=lambda n,v:(D/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
inputs={'evaluations/T-0813/settled-source-design-v1.json':'34140804cffe540c92449ecc2a5c95874102e3a23e017357fdc318afcdb6ae26','evaluations/T-0813/settled-fixed160-successor-transfer-v1.json':'5d56b741b0761dc443ea86f39ea439acc0bc1a5f2c643e207a6cb7a14d40ca1c','evaluations/T-0813/independent-settled-source-design-gate-v1.json':'b9ac50b83a8f46122115a244046f2e5eb1424bcab7cfcecc78de935d1ccc6869'}
for p,h in inputs.items():assert sha(R/p)==h,p
spec=read(next(iter(inputs)));transfer=read(spec['transfer']['path']);base=read('wotan/backlog.json');assert base['next_id']==814
old=read('evaluations/T-0793/fixed160-successor-transfer-v1.json');assert transfer['fixed160']==old['fixed160'];assert transfer['preserved_previous_transfer']==old
appendix=transfer['full_T0791_T0792_planning_appendices'];assert appendix==old['full_T0791_T0792_planning_appendices'] and len(appendix)==4898
(D/'baseline-backlog.json').write_bytes((R/'wotan/backlog.json').read_bytes());new=[];logs=[]
for t in spec['tasks']:
 entry={k:copy.deepcopy(t[k]) for k in ['id','status','size','after','priority','priority_basis']};entry['summary']=t['title'];entry['note']=t.get('mandate',t.get('activation'))+' Se wotan/dev-log/'+t['id']+'.md; originaltak0.';new.append(entry)
 parts=['# '+t['id']+' — '+t['title'],'','- Size: '+t['size'],'- Status: READY','- Phase: —','- Priority: '+t['priority'],'- After: []','','## Omfång och mandat','',t.get('mandate',t.get('activation','')),t.get('question',t.get('scope','')),'','Originaltak: 0. Ingen ny källåtkomst eller nytt utförandemandat.','']
 for key,label in [('persons','Personer'),('side','Sida'),('child_relation_question','Exakt barn-/relationsfråga'),('accepted_reuse','Accepterat återbruk'),('old_owner_boundary','Bevarade äldre ägare'),('procedure','Arbetsgång'),('trigger','Verkligt återstartvillkor'),('life_obligation','Nära livsbildsbeslut')]:
  if key in t:parts+=['## '+label,'',json.dumps(t[key],ensure_ascii=False) if isinstance(t[key],list) else t[key],'']
 if 'exclusions' in t:parts+=['## Utanför omfånget','']+['- '+v for v in t['exclusions']]+['']
 if 'life_caps' in t:parts+=['## Fastställda livsbildstak och prioriteringsgräns','']+[k+': '+v for k,v in t['life_caps'].items()]+['']
 parts+=['## Acceptance Criteria','']+[f'{i+1}. {v}' for i,v in enumerate(t['acceptance'])]+['','## Återupptagning','','Uppdaterat: 2026-10-08. Kandidat endast; root allocation och exakta SOURCE-grindar återstår. Inget av uppdragen har startats.','','## Exakta avgjorda ingångar','']+[f'- {p} SHA256 {h}' for p,h in inputs.items()]+['','## Bokstavlig source-design för denna uppgift','','```json',json.dumps(t,ensure_ascii=False,indent=2),'```','']
 if t['id']=='T-0816':parts+=['## Förlustfritt planeringsägarskap','','Aktuell ytterägare är T-0816 vid faktisk root allocation. Historiska planning_owner/source_plan-fält och gamla sourceägare bevaras; dessa är inte nytt utförandemandat.','',transfer['owner_semantics'],'','Hela fasta160/source_plan och separata aktuella30-dispositioner: '+spec['transfer']['path']+' SHA256 '+spec['transfer']['sha256'], '','## Oförkortad historisk T0791/T0792-planeringsappendix','',appendix]
 text='\n'.join(parts)+'\n';p=D/(t['id']+'.md');p.write_text(text);logs.append({'task':t['id'],'path':str(p.relative_to(R)),'sha256':sha(p)})
allocated=copy.deepcopy(base);at=next(i for i,t in enumerate(base['tasks']) if t['id']=='T-0813')+1;allocated['tasks'][at:at]=new;allocated['next_id']=817;save('backlog.json',allocated)
assert [t for t in allocated['tasks'] if t['id'] not in {n['id'] for n in new}]==base['tasks'];assert len({t['id'] for t in allocated['tasks']})==len(allocated['tasks']);assert next(t for t in allocated['tasks'] if t['id']=='T-0813')==next(t for t in base['tasks'] if t['id']=='T-0813');assert appendix in (D/'T-0816.md').read_text()
node=R/'wotan/node-links.json';main=R/'genealogy2/data/research.sqlite';oldlogs={t['id']:sha(R/'wotan/dev-log'/ (t['id']+'.md')) for t in base['tasks'] if t.get('priority')=='CORE_LIFE' and (R/'wotan/dev-log'/(t['id']+'.md')).exists()}
proof={'passed':True,'old_task_count':len(base['tasks']),'new_task_count':len(allocated['tasks']),'all_old_records_values_exact':True,'all_old_relative_order_exact':True,'T0813_ONGOING_preserved':True,'insert_after':'T-0813','insert_before':'T-0217','new_order':[n['id'] for n in new],'next_id_before':814,'next_id_after':817,'all_new_after_empty':all(n['after']==[] for n in new),'fixed160_fullrows_exact':True,'whole_previous_transfer_exact':True,'appendix_characters':4898,'appendix_fulltext_exact':True,'historical_owner_fields_unchanged':True,'CORE_LIFE_log_preimages':oldlogs,'node_links_sha256':sha(node),'main_sha256':sha(main),'no_live_writes':True}
save('preservation-proof.json',proof);save('individual-consequence-table.json',{'old_records':[{'task':t['id'],'disposition':'RETAIN_ALL_FIELDS_ORDER_STATUS_AFTER_SCOPE','before':t,'after':t} for t in base['tasks']],'new_records':[{'task':n['id'],'disposition':'CREATE_PLANNED_BOUNDED_TASK_NO_EXECUTION_MANDATE','after':n,'source_design':spec['tasks'][i],'log':logs[i]} for i,n in enumerate(new)],'fixed160_transfer':{'disposition':'FULL_LOSSLESS_TRANSFER_WITH_SEPARATE_CURRENT_OUTER_OWNER','pin':spec['transfer'],'original160_equal':True,'appendix_equal':True},'native_change_count':0})
files=[{'path':str(p.relative_to(R)),'sha256':sha(p)} for p in sorted(D.iterdir()) if p.is_file()];save('manifest.json',{'task':'T-0813','candidate_only':True,'canonicalApproval':False,'liveQueueApproval':False,'source_inputs':[{'path':p,'sha256':h} for p,h in inputs.items()],'files':files,'logs':logs,'backlog_preimage_sha256':sha(R/'wotan/backlog.json'),'backlog_candidate_sha256':sha(D/'backlog.json'),'main_sha256':sha(main),'node_links_sha256':sha(node),'generated_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()});print(json.dumps({'manifest':str((D/'manifest.json').relative_to(R)),'sha256':sha(D/'manifest.json'),'backlog':sha(D/'backlog.json'),'old_count':len(base['tasks']),'new_count':len(allocated['tasks'])}))
