import pathlib,json,sqlite3,hashlib
B=pathlib.Path(__file__).resolve().parent;R=B.parents[1]
src=B/'source-review/C-0084-source-v1.md';text=src.read_text();raw=text.split('## Full field reading\n\n',1)[1].split('## Settled evidence decisions',1)[0].strip();decision=text.split('## Settled evidence decisions\n\n',1)[1].split('## Implementation requirements',1)[0].strip();rid='R-84ff945992bb67c98161922b';changes=[]
def ev(o,v,n):return {'object':o,'version':v,'role':'supports','note':n}
bases=[ev(rid,1,'Födelsebok1902nr34 med fulla rubriker, egna celler och marginaler.'),ev('S-0008',1,'Versionsbunden volymmetadata.')]
limits='Samma originalpost och bokföringskedja; inget nytt oberoende historiskt vittne. Svagt räknespår är inte certifierad1/manlig cell; moderns civilståndsceller tomma, ingen explicit oäkta kategori. Ingen fysisk födelseort/attestankomst, biologisk far eller säker fadderidentitet följer.'
def add(oid,kind,data,evidence,caveat):changes.append({'id':oid,'kind':kind,'expectedVersion':None,'data':data,'origins':[],'evidence':evidence,'disposition':'recorded','evidenceStatus':None,'rationale':'T-0777 AC2–4: avgjord fullfältstabell och source-bound adoption; tidigare läsningar bevaras som historik.','caveat':caveat})
tr='TR-T0777-C0084-fullfields';audit='AUDIT-T0777-C0084'
add(tr,'transcription',{'record_id':rid,'text':raw,'reading_note':limits+' Denna aktuella läsning ersätter TR-947c0c8fae6d908aa48b973b@1:s äldre räkne1/classificering för aktuell användning; äldre transkription bevaras.'},bases,limits)
add(audit,'assessment',{'subject_id':rid,'criteria':'original_revision/1','outcome':'reviewed_with_limits','body':decision},bases+[ev(tr,1,'Samtliga tryckta kolumner inklusive blankheter och osäkert spår.')],limits)
own=[('P-0117','Moder: Charlotta Cecilia Elisabeth Gustafsson; piga vid Mälby i Helgesta;83 14/1; civilståndsceller tomma; attest till Helgesta.','Bokföringsort är inte fysisk nedkomstort; inget uttryckligt ogift från denna post.'),('P-0118','Erik Axel;1902 Juni22; nr34; faderokänd; Juli6 dop; ingen säker räkne1; ingen explicit legitimitetsklass.','Könman kvarstår genom äldre explicit1910 Ogiftm, inte denna källas räknecell; föräldra-/identitetsgrindar ändras inte.'),('P-0133','Torparen Erik Karlsson i Brosätter, fadderrollen.','Befintlig kandidatlänk inte säker morfar; ingen ny föräldralänk.'),('P-0135','Erik Karlssons ej namngivna hustru i Brosätter, fadderrollen.','Befintlig kandidatidentifiering behåller osäkerhet; ingen säker mormor eller eget utskrivet namn.')]
for pid,fields,specific in own:add('ADOPT-T0777-C0084-'+pid,'assessment',{'subject_id':pid,'criteria':'bounded_source_adoption/1','outcome':'reviewed_with_limits','body':json.dumps({'person':pid,'own_source_fields':fields,'scope':'Flen1902nr34','limitation':specific},ensure_ascii=False,indent=2)},bases+[ev(tr,1,'Egen post/rad med kontext.'),ev(audit,1,'Avgjord källräckvidd och kandidatgränser.')],limits+' '+specific)
op={'id':'T-0777/C0084-source-candidate-v1','actor':'Codex Sol mechanical implementation of settled Astra decisions','reason':'T-0777 AC2–4: full birth1902nr34 field extraction, corrected source classification limits and four bounded source adoptions; canonical-ready operation subject to independent final review.','dependencyReviewVersion':2,'changes':changes};p=B/'C-0084-source-candidate-operation-v1.json';p.write_text(json.dumps(op,ensure_ascii=False,indent=2)+'\n');(B/'C-0084-first-source-candidate-freeze-v1.json').write_text(json.dumps({'task':'T-0777','scope':'C-0084','baseline_head':255,'status':'first source candidate before testing','files':[{'path':str(x.relative_to(R)),'sha256':hashlib.sha256(x.read_bytes()).hexdigest()} for x in [src,p]]},ensure_ascii=False,indent=2)+'\n');print('6 new source objects')
