import pathlib,json,hashlib
B=pathlib.Path(__file__).resolve().parent;R=B.parents[1]
src=B/'source-review/C-0896-source-v1.md';text=src.read_text();changes=[]
def ev(o,v,n):return {'object':o,'version':v,'role':'supports','note':n}
def add(oid,kind,data,evidence,limit,assets=None):
 x={'id':oid,'kind':kind,'expectedVersion':None,'data':data,'origins':[],'evidence':evidence,'disposition':'recorded','evidenceStatus':None,'rationale':'T-0777 AC2–4: avgjord full utvinning av avgränsade trepersonersposter med egen källtyp; inga nya identiteter eller relationer.','caveat':limit}
 if assets:x['assets']=assets
 changes.append(x)
pr='R-9ae4232a74448543e820b85f';imagepr='R-01d7f3c0b9efbd24ee39cf7c';cr='R-T0777-C0896-Astrid-SCB1930'
parish=text.split('## Parish page 563\n\n',1)[1].split('## SCB census page43',1)[0].strip();census=text.split('## SCB census page43, additional own household rows\n\n',1)[1].split('## Reused accepted economic region',1)[0].strip()
# Remove production instruction while preserve explicit source descriptor.
census=census.replace('Add a SEPARATE S-0007 record for Astrid + two children\'s three own rows immediately below ArneValfrid: record_type census_household_entry, locator ','Separate three-row household immediately below ArneValfrid, locator ')
limit='Samma bokförings-/utdragskedja, ingen oberoende födelse-/skilsmässobekräftelse. Årsankare1930/1926/1932 är registreringsuppgifter, inte obruten fysisk vistelse eller exakt resdag. Tomma celler är lokala blankheter. Inkomst4— är rått fält utan enhetsnyckel; inga nollförmögenhets- eller400kr-fakta.'
add(cr,'record',{'source_id':'S-0007','record_type':'census_household_entry','locator':'Folkräkning1930 Flen municipalsamhälle, utdrag s43, församlingsbok563 Björkhem nr1, Astrid Charlotta Lundkvist med Gunvor Solveig Charlotta och Karl Yngve, B0001059_00329','dependence_note':'Egen separat familj1 med Astrid och två barn på samma SCB-utdrag som tidigare Jaenssonfamilj; församlingsboksberoende, inte ett oberoende födelsevittne.'},[ev('S-0007',1,'Versionsbunden SCB1930metadata.')],limit,[{'path':'genealogy/media/C-0896-riksarkivet-B0001059_00329.jpg','region':'Astrid Charlotta Lundkvist och egna två barnrader direkt nedanför Arne; egen familj1'}])
pb=[ev(pr,1,'Egna parishrader12–14.'),ev(imagepr,1,'Samma originalbild563; överlappande källpost, inte oberoende evidens.'),ev('S-0706',1,'Befintlig församlingsboksmetadata och reproduktionskontroller.')];cb=[ev(cr,1,'Den nya separata avgränsade SCBfamiljen.'),ev('S-0007',1,'Versionsbunden utdragsmetadata.')]
for tag,rid,raw,bases in [('parish',pr,parish,pb),('SCB1930',cr,census,cb)]:
 tr=f'TR-T0777-C0896-{tag}-fullfields';audit=f'AUDIT-T0777-C0896-{tag}'
 add(tr,'transcription',{'record_id':rid,'text':raw,'reading_note':limit+' Parishoriginalruta bevaras som C0030asset med hash73185d0a21457e2dfc4b1a3d81fce70b3cefb93d3a6cc1cf436a8e8c6f8f6960; ingen recordmetadata ändras.'},bases,limit)
 add(audit,'assessment',{'subject_id':rid,'criteria':'original_revision/1','outcome':'reviewed_with_limits','body':json.dumps({'scope':tag,'source_reading':raw,'limits':limit,'economic_reuse':text.split('## Reused accepted economic region\n\n',1)[1].split('## Page-label search controls',1)[0].strip(),'label_controls':text.split('## Page-label search controls\n\n',1)[1].split('## Implementation and adoption',1)[0].strip()},ensure_ascii=False,indent=2)},bases+[ev(tr,1,'Alla egna fält inklusive ditton/blankheter.')],limit)
add('ADOPT-T0777-C0896-P-0047','assessment',{'subject_id':'P-0047','criteria':'bounded_source_adoption/1','outcome':'reviewed_with_limits','body':json.dumps({'person':'P-0047','parish_scope':'563r12, relevanta barnrader13–14','SCB_scope':'Astrid och egen Gunvor/KarlYngvefamilj per1930','dated_anchors':'egen sista inflyttning Sundbyberg1926 i SCB, intern638→563år1930,949år1932','occupation':'polererska i parish + eget Polerareditto i SCB, ingen belagd ändringsordning','child_identity_limit':'Befintliga egna M-P0047-daughter/son bevaras utan P-identiteter; P0019/P0017 är andra personer och adopteras inte.'},ensure_ascii=False,indent=2)},pb+cb+[ev('AUDIT-T0777-C0896-parish',1,'Parishutvinning.'),ev('AUDIT-T0777-C0896-SCB1930',1,'Egen SCBfamilj.')],limit)
op={'id':'T-0777/C0896-source-candidate-v1','actor':'Codex Sol mechanical settled source implementation','reason':'T-0777 AC2–4: full own parish563r12–14 extraction and separate1930SCBfamily source with preserved1926anchor; P0047bounded adoption only, no new child identities; canonical-ready after independent review.','dependencyReviewVersion':2,'changes':changes};out=B/'C-0896-source-candidate-operation-v1.json';out.write_text(json.dumps(op,ensure_ascii=False,indent=2)+'\n');(B/'C-0896-first-source-freeze-v1.json').write_text(json.dumps({'task':'T-0777','files':[{'path':str(x.relative_to(R)),'sha256':hashlib.sha256(x.read_bytes()).hexdigest()} for x in [src,out]],'child_identity_check':'C-0896-current-child-identity-check-v1.json','existing_records_not_revised':True},ensure_ascii=False,indent=2)+'\n');print(len(changes),'new source objects; original records preserved')
