import pathlib,json,hashlib,sqlite3,datetime
B=pathlib.Path(__file__).resolve().parent;R=B.parents[1]
receipts=[json.loads((B/f'final-sequence-v1-step-{i:02d}.json').read_text()) for i in range(1,4)]+[json.loads((B/f'final-sequence-v2-step-{i:02d}.json').read_text()) for i in range(4,10)]+[json.loads((B/f'final-sequence-v3-step-{i:02d}.json').read_text()) for i in range(10,13)]
ops=[{'path':x['path'],'sha256':x['sha256'],'expected_before':x['expected_before'],'expected_after':x['actual_after']} for x in receipts]
for n,b,a in [('C-0911-caveat-copies-candidate-operation-v1.json',{'journal_head':267,'pending':33},{'journal_head':268,'pending':33}),('final-individual-resolution-operation-v1.json',{'journal_head':268,'pending':33},{'journal_head':269,'pending':0})]:
 p=B/n;ops.append({'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'expected_before':b,'expected_after':a})
files=[B/'root-pre-source-lock-v1.json',B/'final-full-stage-check-v2.json',B/'final-protected-invariants-v1.json',B/'final-native-measurements-v1.json',B/'final-pending-disposition-input-v1.json',B/'source-review/final-pending-dispositions-v1.json',B/'clone/final-candidate-v3.sqlite']+list(B.glob('C-*-final-consequence-table-v3.json'))+list((B/'source-review').glob('*'))+[B/'final-verify-v1.txt',B/'final-assets-v1.txt',B/'final-source-v1.txt']
files=[p for p in files if p.is_file()];pins=[{'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in files]
for o in ops:assert hashlib.sha256((R/o['path']).read_bytes()).hexdigest()==o['sha256']
c=sqlite3.connect(B/'clone/final-candidate-v3.sqlite');state={'journal_head':c.execute('select max(sequence) from operation_payload').fetchone()[0],'pending':c.execute('select count(*) from review_request q left join review_resolution r on q.id=r.request_id where r.request_id is null').fetchone()[0]};assert state=={'journal_head':269,'pending':0}
x={'task':'T-0777','frozen_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'source_approval':'PENDING_INDEPENDENT_EXACT_HASH_PASS','baseline_state':{'journal_head':255,'pending':0},'final_state':state,'stage':str((B/'clone/final-candidate-v3.sqlite').relative_to(R)),'operations':ops,'pinned_artifacts':pins,'native_objects':128,'new':38,'revised':90,'adoptions':19,'individual_resolutions':33,'technical_pass_not_source_approval':True};(B/'final-package-freeze-v1.json').write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');print('frozen14operations',len(pins),'pins')
