"""Read-only closure preparation. Never applies canonical or changes Wotan."""
import pathlib,json,hashlib,sqlite3,datetime
B=pathlib.Path(__file__).resolve().parent;R=B.parents[1]
f=json.loads((B/'final-package-freeze-v1.json').read_text());pins=f['pinned_artifacts']+[{k:o[k] for k in ['path','sha256']} for o in f['operations']]
checks=[{'path':p['path'],'expected_sha256':p['sha256'],'actual_sha256':hashlib.sha256((R/p['path']).read_bytes()).hexdigest(),'pass':hashlib.sha256((R/p['path']).read_bytes()).hexdigest()==p['sha256']} for p in pins];assert all(x['pass'] for x in checks)
historical=[p for p in B.rglob('*') if p.is_file() and ('candidate-operation-v1' in p.name or 'first-' in p.name or 'final-sequence-v1' in p.name or 'final-sequence-v2' in p.name or 'amendment' in p.name)]
c=sqlite3.connect('file:'+str(B/'clone/final-candidate-v3.sqlite')+'?mode=ro',uri=True);state={'journal_head':c.execute('select max(sequence) from operation_payload').fetchone()[0],'pending':c.execute('select count(*) from review_request q left join review_resolution r on q.id=r.request_id where r.request_id is null').fetchone()[0]};assert state=={'journal_head':269,'pending':0}
x={'task':'T-0777','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'package_hash':hashlib.sha256((B/'final-package-freeze-v1.json').read_bytes()).hexdigest(),'frozen_pin_checks':checks,'retained_history_artifacts':[{'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in sorted(historical)],'stage_final_state':state,'canonical_application_status':'ROOT_RECEIPT_REQUIRED','wotan_status':'ROOT_CHECKPOINT_REQUIRED','usage_status':'ROOT_COLLECT_AFTER_ALL_WORKER_FINAL_RESPONSES','measurements':{'scoped_rows':28,'coverage_comparability':'heterogeneous rows; not comparable unit cost','prior_C0021_cells_reused':81,'prior_gaplabel_controls':5,'native_objects':128,'new':38,'revised':90,'adoptions':19,'individual_resolutions':33,'operations':14},'limitations':['Fresh budget start/end unknown.','Root preparation before firstworker and root tokenusage unknown.','Usage sum of loggedworkerturns is not totalprojectproduction.']}
(B/'closure-preparation-manifest-v1.json').write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');print('pinsPASS',len(checks),'preservedhistory',len(historical),'stage',state)
