import pathlib,json,sqlite3,subprocess,hashlib,datetime
B=pathlib.Path(__file__).resolve().parent;R=B.parents[1];db=B/'clone/final-candidate-v3.sqlite';assert not db.exists(),'Preserve first attempt; choose new version'
src=sqlite3.connect('file:'+str(B/'clone/final-candidate-v2.sqlite')+'?mode=ro',uri=True);dest=sqlite3.connect(db);src.backup(dest);dest.close();src.close();j=B/'clone/final-candidate-v3-journal';j.mkdir()
names=['C-0084-source-candidate-operation-v2.json','C-0084-consequence-candidate-operation-v2.json','C-0402-source-candidate-operation-v2.json','C-0402-role-metadata-candidate-operation-v2.json','C-0573-source-candidate-operation-v1.json','C-0573-consequence-candidate-operation-v1.json','C-0896-source-candidate-operation-v3.json','C-0896-consequence-candidate-operation-v2.json','C-0911-record-metadata-candidate-operation-v1.json','C-0911-source-candidate-operation-v3.json','C-0911-role-metadata-candidate-operation-v1.json','C-0911-consequence-candidate-operation-v2.json']
def state():
 c=sqlite3.connect('file:'+str(db)+'?mode=ro',uri=True);x={'journal_head':c.execute('select max(sequence) from operation_payload').fetchone()[0],'pending':c.execute('select count(*) from review_request q left join review_resolution r on q.id=r.request_id where r.request_id is null').fetchone()[0]};c.close();return x
steps=[]
for i,name in enumerate(names[9:],10):
 p=B/name;before=state();start=datetime.datetime.now(datetime.timezone.utc).isoformat();r=subprocess.run(['node','genealogy2/cli.mjs','apply',str(p),'--db',str(db),'--journal',str(j)],cwd=R,capture_output=True,text=True);after=state();receipt={'index':i,'at_utc':start,'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'expected_before':before,'actual_after':after,'exit_code':r.returncode,'stdout':r.stdout,'stderr':r.stderr};(B/f'final-sequence-v3-step-{i:02d}.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');steps.append(receipt);(B/'final-sequence-v3-progress.json').write_text(json.dumps({'task':'T-0777','db':str(db.relative_to(R)),'steps':steps,'complete_all_12':False},ensure_ascii=False,indent=2)+'\n');print(i,name,r.returncode,after,flush=True);assert r.returncode==0,receipt
c=sqlite3.connect('file:'+str(db)+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;pending=[dict(x) for x in c.execute('select q.* from review_request q left join review_resolution r on q.id=r.request_id where r.request_id is null')];details=[]
for request in pending:
 oid=request['object_id'] if 'object_id' in request else request.get('dependent_object_id')
 details.append({'request':request,'object_id':oid})
(B/'final-sequence-v3-pending-requests.json').write_text(json.dumps(details,ensure_ascii=False,indent=2)+'\n');(B/'final-sequence-v3-progress.json').write_text(json.dumps({'task':'T-0777','db':str(db.relative_to(R)),'steps':steps,'complete_all_12':True,'pending':len(pending),'source_approval_still_required':True},ensure_ascii=False,indent=2)+'\n');print('12steps complete, pending',len(pending),flush=True)
