import json,re,hashlib
from pathlib import Path
B=Path('evaluations/T-0830');O=B/'independent'
all={a['revision']['object_id']:a for a in json.loads((B/'preparation/current-relevant-native-v1.json').read_text())}
for name in ['five-source-existing-record-closures-v1','hypothetical-source-head-closures-v1']:
 for root in json.loads((B/f'preparation/{name}.json').read_text()):
  for a in root['current_affected']:all[a['native']['revision']['object_id']]=a['native']
for a in json.loads((O/'independent-current-semantic-scan-v1.json').read_text())['matches']:all[a['revision']['object_id']]=a
G=[]
def group(n,ids,fields,decision):
 ids=list(dict.fromkeys(ids));missing=[i for i in ids if i not in all]
 if missing:raise ValueError(missing)
 rows=[]
 for i in ids:
  a=all[i];rows.append({'revision':a['revision']['id'],'fields':fields,'full_current_native':a})
 G.append({'group':n,'decision':decision,'targets':rows})
def ids(rx):return [i for i in all if re.search(rx,i)]
own134=[i for i,a in all.items() if (a['data'].get('subject_id')=='P-0134' or i=='P-0134') and 'kopierest' in a['revision'].get('caveat','')]
group('G01_P134_current_copy_caveats',own134,['revision.caveat'],'Amend only current two-copy debt: C5 image13 and C4 image14 now preserved/tested; historical old text remains. Preserve all other source reservations and criteria outcomes except separately authorized native identity/tree and PK11/12. No full LIFE approval.')
own316=[i for i,a in all.items() if a['data'].get('subject_id')=='P-0316' and re.search(r'C0512/AI12.*C0436/C0437.*egna fält kvarstår',a['revision'].get('caveat',''))]
group('G02_P316_current_T0812_remainder',own316,['revision.caveat','data.body where current debt repeated'],'Only own C0436/C0437/C0512 rows are now fully tested with raw reservations. T0812 C0274 was already closed. Preserve broader T0420 other-person ownfields and full LIFE scope. Current metadata must distinguish new reading from old no-new-reading rationale.')
group('G03_P134_own_semantic_bodies',['AS-P-0134-birth-correction','ASSESSMENT-P-0134','BIO-P-0134','CONTRACT-P-0134-PK-11','CONTRACT-P-0134-PK-12','P-0134','P-0134/Q-01','PATH-P-0134-KP-02','RESEARCH-P-0134-9d76f0343410'],['revision.caveat','revision.rationale','data.body/text','data.outcome where applicable'],'Source-specific current copy closure and exact1853control boundary. PK11 STYRKT after media; native seven-criteria passed/supporting conditional corrected staged package. Keep legacy full contract UNDERKÄND and PK03/08. Birth21Mar/directparentpair unaffected; deathage35y7m3d retained; not independent C4/C5 votes.')
group('G04_P316_own_semantic_bodies',['ASSESSMENT-P-0316','BIO-P-0316','CONTRACT-P-0316-PK-04','CONTRACT-P-0316-PK-05','CONTRACT-P-0316-PK-11','CONTRACT-P-0316-PK-12','P-0316','P-0316/Q-03','PATH-P-0316-KP-05','RESEARCH-P-0316-9d76f0343410','THEME-P-0316-ARB','THEME-P-0316-SAM','THEME-P-0316-SYN','THEME-P-0316-ID'],['revision.caveat','revision.rationale','data.body/text','data.outcome where applicable'],'PK04 sole C0274 witness debt closed by accepted T0812: STYRKT. PK05 own three-row debt closed: STYRKT. PK11 old STYRKT incorrect because actual C0984 image32 absent; EJ STYRKT until unit6. Native identity failed/tree waiting on exact preservation debt, not unidentified woman. Q03/KP05 close exact old extraction scope; other life paths remain. P0316 display Cajsa Märta Dahlsten/Dalsten; Andersdotter is rejected old transcription, preserve history. Current own annual anchors reach relevant life summaries without physical-continuity inference.')
group('G05_P316_typed_source_flags',['F-P-0316-source_assessment-own-fields-and-limits','O-P-0316-C0436-childhood','O-P-0316-C0437-childhood','O-P-0316-C0512-household'],['data.value_json','data.value_literal','revision.caveat','revision.rationale'],'Exact own_AI12_columns/own_childhood_columns fully tested with explicit raw reservation maps; own_AI8_columns full accepted T0136/T0110 reuse, not partial. O own_knowledge_communion_notes_extracted and own_remaining_columns_extracted true for respective own rows only. death_source_copy_missing:true and old_all_positive_copies_statement_incorrect:true remain pending sixth. Preserve full_contract_upgraded:false, actual blanks and missing-column distinctions.')
group('G06_P316_raw_mentions_identity',['M-P-0316-C0436-childhood','M-P-0316-C0437-childhood','M-P-0316-C0512-household','ID-P-0316-C0436-childhood','ID-P-0316-C0437-childhood','ID-P-0316-C0512-household'],['data.name_literal','data.role_literal','revision.caveat','revision.rationale'],'C0512 own raw Dalsten, Kajsa Märta / Hu.; other source name forms unchanged. C436/C437 D:r raw role may replace normalized dotter, no stronger relation inference. Amend actual unread claims only, identity accepted unchanged.')
group('G07_Marriage_precision',['KEY-P-0316-72cd29ac2063','RESEARCH-P-0316-9d76f0343410'],['data.body','revision.caveat','revision.rationale'],'1858-02-21 is C0511 banns and C0512 registered marriage ditto. C0510 current accepted58/59[?]26/3 is distinct. No certain actual wedding date, no two-independent-HH agreement. Preserve F-P0315-marriage_assessment@2 and E-banns as-is.')
# Exact shared original-bound metadata. Full current payload supplied for individual field identification.
rs=['R-2c30f50bb85f191a282e6867','R-ab67d38b58e92a0c9b0329d2','R-f9c30454d2afaad13941d205','R-45b297a69f523f7abcb7fdf5','R-dd31c2714bc0d4606128259b','R-2feea08ce24e0d5e40d9734d']
related=[i for i,a in all.items() if a['revision']['kind'] in ['transcription','assessment'] and a['data'].get('record_id') in rs]
# READ assessment subjects are record IDs.
related += [i for i,a in all.items() if i.startswith('READ-') and a['data'].get('subject_id') in rs]
group('G08_exact_six_record_representations',rs+related,['record media/asset registration','data.text/reading_note/body','revision.caveat','revision.rationale'],'Add full own extractions and exact hashes/provenance to selected six records across five images; C4 controls separate. Preserve old transcript verbatim as historical. Own P316 full-field closure must not become full household closure. C437 older April-certain/April-v-August context is superseded by accepted reserved month, not a new claim of August. C0512 Nils65 28/11 and Katarina25/8[?] context retain current1865/1877-08-25; no side full-field review.')
boundary=json.loads((B/'implementation/1853-boundary-current-semantic-copy-candidates-v1.json').read_text())['objects']
group('G09_boundary_and_copy_metadata',[a['revision_id'].rsplit('@',1)[0] for a in boundary if not a['revision_id'].startswith('SEARCH-')]+['R-d6ef52c986e2385ad3234a8b','RESEARCH-P-0214-9d76f0343410'],['data.body/description/text/reading_note','revision.caveat','revision.rationale'],'Exact current1853 coverage=21 rows born17Jan–12Nov,lastbapt20Nov. Not whole year. C4/C5 copied forms share registration chain. Newly preserved copies do not change image13 C4 or image12 C5 original receipt. For unaffected original representations, add only scoped current correction to actual missing-copy/whole-year statements; do not claim original reread. Historical transcript quoted claims remain clearly historical. Source head amendments must be narrow and full actual closure reviewed.')
group('G10_C5_own_fields',['O-P-0134-C1041-C5-birth','O-P-0134-C1041-copy-boundary','O-P-0134-C1041-Anna-Christina1853','O-P-0134-C1041-Kallvik-control'],['data.value_json','data.value_literal','revision.caveat'],'C5 reference29 removed/null: no ownfolio/post29. Age33;18/4 recorded, prior churching interpretation explicitly qualified. C4 otherAnna born9May/bapt15May1853, differentmother, legitimate-column distinction; KallvikAugustaMathilda9/16Oct withJohanErsson/EvaLottaAndersdotter, no relation. Exact record fields, no global source-family inference.')
w=ids(r'^(M-C1041-witness-|O-P-0134-C1041-witness-|EP-.*C1041|E-.*P-0215.*1852)')
# Additional churching/witness participants selected by full data references.
w += [i for i,a in all.items() if a['revision']['kind'] in ['event','participation'] and ('C1041-witness' in json.dumps(a,ensure_ascii=False) or ('churching' in i and 'P-0215' in i))]
group('G11_witness_and_churching_raw',w,['data.name_literal/role_literal/value_json/value_literal','revision.caveat','revision.rationale'],'Own source witness reservations hu A.[S/L?]G[ill/uit?]man;dr A.[J/F?].Nilson/Nilsson;Pig[A/C?].Br.Jonsdotter;alla iMåna[d?]. No person IDs/initial expansions. And.Nilson/Nilsson separate strongest raw.18/4 prior churching interpretation retained qualified; no independently printed function. Preserve older rawliteral as history not active certainty; object IDs need not rename.')
group('G12_retained_knowledge',['REL-parent-P-0134-P-0015','REL-parent-P-0316-P-0254','F-P-0315-marriage_assessment-banns-not-wedding','F-P-0315-documentation_conflict-extraction','F-P-0316-name_assessment-current-readings','SEARCH-P-0134-Ardala1851-1853'],['all'], 'RETAIN semantic payload. Descendant relations accepted CORROBORATED recorded_parent. P0315 own AI12/AIIa1 debt remains; C0274 already superseded. Current name assessment already correct. Historical negative receipt unchanged: add separate exact current C4 search memory, not rewrite old metadata/provider unknowns.')
group('G13_two_current_mentions_copy_status',['M-C1041-Anna-Christina-C5','M-C1041-Anna-Christina1853'],['revision.caveat','revision.rationale'],'Replace exact missing-copy/not-newly-reviewed claim with new preserved full image and own tested record; raw empty role is retained because sex marker is separately recorded, not an explicit role string. No identity status change.')
out={'task':'T-0830','status':'CONSOLIDATED_SOURCE_CONSEQUENCE_REQUIREMENTS_NOT_FINAL_PACKAGE_APPROVAL','baseline':505,'independent_scan':{'path':str(O/'independent-current-semantic-scan-v1.json'),'sha256':hashlib.sha256((O/'independent-current-semantic-scan-v1.json').read_bytes()).hexdigest(),'current_heads':44604,'matched':975,'note':'103 own current objects and 233 mechanical closure full semantics read; broad975 name hits are screening, not claimed all full reviewed. Relevant additional targets full read. Sol boundary17 compared after independent search.'},'source_comparison':{'path':str(O/'source-comparison-five-v2.json'),'sha256':'cf43c76b576a7f6fcbf8aa5009b0610e89b5c3fc9b3379ef2b4d4240ac85c680'},'groups':G,'constraints':['All45 OWNER scopes read, preserve exact native facts/support/review states and no demotion for archive gaps.','No changes to side full-extraction flags from context-only readings. Existing protected parent/sibling relations unchanged.','No whole-contract or nativeLIFE pass. Current P316PK11 remains true source-copy debt until actual unit6;401 is accessblock,notnoll.','If exact field absent or multiple unexpected matches, return to Astra; no silent alias or substitute.','Each required numeric evidence rebind needs individual exact old/current basis review; four existing older references not blanket approved.','Final ordered operation/candidate fullfield table/actual pending dispositions/stage hashes still required.']}
f=O/'consolidated-consequence-requirements-v2.json';f.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(f,hashlib.sha256(f.read_bytes()).hexdigest());print([(g['group'],len(g['targets'])) for g in G]);print('unique',len({x['revision'] for g in G for x in g['targets']}))
