import json,hashlib,datetime,re
from pathlib import Path
p=Path('evaluations/T-0830');inp=p/'implementation/stage-v4/actual-pending-full-native-v1.json';x=json.loads(inp.read_text());pri=p/'primary/actual-pending-copy-caveat-decision-v1.json';decision=json.loads(pri.read_text());out=p/'independent'
def sha(f):return hashlib.sha256(f.read_bytes()).hexdigest()
def jsha(v):return hashlib.sha256(json.dumps(v,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()
obj={r['current_head_native']['revision']['id']:r['current_head_native'] for r in x['actual_requests']};correction='READ-aff688277ca14239677e115c@1';assert len(obj)==123
objects=[]
for id,n in sorted(obj.items()):
 k=n['revision']['kind'];d=n['data'];pid=d.get('subject_id',d.get('person_id',d.get('from_person','')))
 if id==correction:reason='Current caveat explicitly says own positive C5 image13 missing. Newly preserved/tested exact unit1 disproves this present copy state. True C4 own1852/C5 image12 boundary body retained; narrow correction required.'
 elif id in ['E-birth-P-0134@1','EP-E-birth-P-0134-P-0134-principal@1']:reason='Accepted21March1852 event/participation and parental-home versus physical-place boundary unchanged. Kopierester ger ingen ny personosäkerhet states a true bounded principle, not an active assertion that those two copies still lack preservation; retain exact wording and grade.'
 elif id=='F-P-0316-family_context-parents-and-siblings@2':reason='Seven known children, distinct Anders Olof brothers, raw age/date conflicts and stronger accepted T0134 month reservation remain. New Cajsa ownrow extraction does not resolve sibling household month or prove lifetime total.'
 elif id=='O-P-0409-C0512-own@1':reason='Retain already accepted1877 25/8 literal and crossed-row context. New samepage contextual reading25/8[?] does not disprove accepted August value or authorize February; its tested glyph reservation remains in new source audit. No stronger confidence or other own-column completeness is inferred.'
 elif id=='O-P-0407-C0512-own@1':reason='Existing1865 28/11/Sättna and crossed row agree settled source comparison; initial60 alternative was withdrawn. No side-person own annual/notes extraction upgrade.'
 elif 'P-0315' in id:reason='Husband Lars Petter same C0512 row/identity and registered1858-02-21 field retained. Registered date is not actual wedding; own extraction-conflict scope remains because Cajsa fullrow is a distinct row.'
 elif re.search(r'P-03(?:7[5-9]|8[0-2])',id):
  if k=='relation':reason=f'Exact recorded_parent endpoint {d["from_person"]}→{d["to_person"]}, CORROBORATED grade and unknown relation dates retained. New source amendment is Cajsa ownrow and preservation metadata, not a replacement or downgrade of this previously accepted family relation.'
  elif k in ['identity','mention']:reason='Same separate Dahlsten-household person/mention retained with its exact recorded name/role, accepted identity and source-specific caveat. Cajsa ownrow full extraction does not fill this other person’s own fields or upgrade its contract.'
  elif k in ['event','participation']:reason='Retain this distinct family member’s later-reported birth event/participation with exact date precision and caveat. Existing uncertainty, separate ownbirth requirements and age arithmetic limits are untouched by Cajsa ownrow.'
  else:reason=f'Retain exact {d.get("property",k)} fields for {pid}. Full current structured source limits distinguish known adult/family or child identity, accepted stronger ownposts, reported household dates, conditional age hypotheses and genuinely unread separate own fields. The changed Cajsa row introduces no contrary claim for these fields; no side completeness/parentage/date upgrade.'
 elif k=='identity':reason='Same C4/C5 person linkage retained. Distinct1853 Anna remains rejected for P0134 because different mother/year; own1852 child and named parents retain accepted identification independent of any unresolved parental origins.'
 elif k=='mention':reason='Retain exact same C4/C5 source mention/name/role. Empty separate role_literal is not denial of explicit parental relationship; relational fields already express it. No witness/parent identity expansion from copied source names.'
 elif k in ['event','participation']:reason='Retain exact own1852 birth/baptism date or existing source-named parent participation. C4/C5 agreement remains dependent parallel registration, no new biological nature or independent vote.'
 else:reason=f'Retain exact {d.get("property",k)} for {pid}: own1852 parent/home/name support remains accepted; dated residence/occupation/affinal/half-sibling and birth-conflict boundaries stay source-specific. Preservation of C5 and narrow1853 control adds no continuous residence, new origin, life extension or family-total inference.'
 objects.append({'object_revision':id,'decision':'CORRECT_CURRENT_COPY_CAVEAT' if id==correction else 'RETAIN_EXACT_CURRENT','reason':reason,'full_current_native_sha256':jsha(n),'full_current_native':n,'field_dispositions':{**{'data.'+k:'RETAIN_EXACT' for k in d if k!='revision_id'},'revision.rationale':'AMEND_CURRENT_METHOD_KEEP_OLD' if id==correction else 'RETAIN_EXACT','revision.caveat':'PRIMARY_EXACT_PREFIX_THEN_UNTOUCHED_OLD' if id==correction else 'RETAIN_EXACT','revision.disposition':'RETAIN_EXACT','revision.evidence_status':'RETAIN_EXACT','origins':'RETAIN_ALL_IN_ORDER','evidence':'EXACT_PRIMARY_ONE_REBIND_AND_ONE_AUDIT_ADD' if id==correction else 'RETAIN_ALL_EXACT_PRIOR_BINDINGS_NO_REBIND','assets/media':'RETAIN_ALL_IN_ORDER'}})
om={a['object_revision']:a for a in objects};rows=[]
for n,r in enumerate(x['actual_requests']):
 assert r['affected_native']==r['current_head_native'];rq=r['request'];a=rq['affected_revision_id'];basis=rq['changed_revision_id'];o=om[a]
 rows.append({'index':n,'request_id':rq['id'],'affected_revision':a,'changed_revision':basis,'disposition':'CORRECT_BEFORE_RESOLUTION' if a==correction else 'APPROVE_RETAIN_RESOLUTION','reason':o['reason'],'source_basis_scope':r['changed_basis_native']['data'],'affected_full_native_sha256':jsha(r['affected_native']),'current_full_native_sha256':jsha(r['current_head_native']),'changed_basis_full_native_sha256':jsha(r['changed_basis_native']),'implementation':'For retain, resolve this exact actual request without changing payload, grade, old basis versions or origins. If source rebuild changes request IDs, compare exact affected/basis/fullpayload against this row; no general latest-binding authorization.'})
assert sum(r['disposition']=='APPROVE_RETAIN_RESOLUTION' for r in rows)==201
report={'task':'T-0830','date':datetime.datetime.now(datetime.timezone.utc).isoformat(),'decision':'201_EXACT_RETAINS_APPROVED_TWO_REQUESTS_ON_ONE_OBJECT_REQUIRE_CORRECTION','inputs':{str(inp):sha(inp),str(pri):sha(pri),str(p/'implementation/operation-ordered-v4.json'):sha(p/'implementation/operation-ordered-v4.json')},'coverage':{'actual_requests':203,'distinct_current_objects':123,'affected_equals_current_all':True,'retains':201,'retained_current_objects':122,'corrected_requests':2,'corrected_current_objects':1,'new_original_reads':0,'new_external_calls':0,'main_writes':0,'method':'Read complete current semantic data/body/caveats/status/rationale for all123 unique heads, each203 actual affected/basis pair, exact evidence and origin context (deduplicated repeated metadata notes); same settled changed-basis payloads reused. Full snapshots/hash preserved; independent original-first five and accepted stronger support remain authority.'},'individual_objects':objects,'individual_requests':rows,'exact_correction':decision,'additional_rebind_approval':'Only READ-aff688277ca14239677e115c R-d6ef@1→@2 same role/note, plus AUDIT-T0830-unit-1@1 supports per primary exact decision; preserve body/data/grade/origins and historical caveat. Source-only scope, no extra original.','protected_boundaries':['All OWNER_CONFIRMED/current prior protected review states remain exact.','P0134 native passed/supporting candidate depends on exact source preservation/final package approval; fullcontract/LIFE remain distinct.','P0316 remains failed/waiting on actual unread C0984 copy; adult/mother and accepted descendant unchanged.','Side-person dates/parents/owncolumn debt are not upgraded because their record container changed; tested contextual reservations retained in source audits.','Old negative receipts remain immutable, new21row search has exact bounded scope.'],'next':'Sol batch the one current caveat correction into exact source package, show finite payload/evidence delta; stage and compare actual remaining request pairs to201 approved retains, create exact resolution operation. Final stable stage/media/validators/full history/protected proof and hash approval still required; no canonical approval yet.'}
f=out/'actual-pending203-review-v1.json';f.write_text(json.dumps(report,ensure_ascii=False,indent=2)+'\n');print(f,sha(f))
