from pathlib import Path
import json,hashlib,sqlite3,datetime
R=Path.cwd();D=R/'evaluations/T-0814/preparation';sha=lambda p:hashlib.sha256(Path(p).read_bytes()).hexdigest();read=lambda p:json.loads(Path(p).read_text());save=lambda n,v:(D/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');base=read(D/'baseline-v1.json');assert sha(base['main']['path'])==base['main']['sha256'];c=sqlite3.connect('file:genealogy2/data/research.sqlite?mode=ro',uri=True);c.row_factory=sqlite3.Row
state={'journal_head':c.execute('SELECT max(sequence) FROM operation_payload').fetchone()[0],'pending':c.execute('SELECT count(*) FROM review_request q LEFT JOIN review_resolution r ON r.request_id=q.id WHERE r.request_id IS NULL').fetchone()[0]};assert state==base['state']
prior=read('evaluations/T-0813/preparation/locked-input-manifest-v1.json');assert prior['main']==base['main'];reconciliation=read('evaluations/T-0813/preparation/actual-accepted-reconciliation-v1.json');assert reconciliation['all_exact'] and reconciliation['count']==481
journalpins=[{'path':e['journal_path'],'sha256':sha(e['journal_path']),'accepted_request_hash':e['request_hash'],'sequence':e['sequence']} for e in reconciliation['entries']];save('unchanged481-receipt-reuse-proof-v1.json',{'same_MAIN_sha256':True,'accepted_DB_payloads_and_reconciliation_reused':True,'prior_reconciliation':'evaluations/T-0813/preparation/actual-accepted-reconciliation-v1.json','journal_file_pins':journalpins,'qualification':'No new receipt interpretation; identical full canonical DB and prior exact canonical reconciliation reused.'})
revisions=read(D/'native-support-versions-v1.json')['revisions'];ops=[]
for oid in sorted({r['operation_id'] for r in revisions}):
 row=c.execute('SELECT p.sequence,p.policy,o.request_hash FROM operation_payload p JOIN operation o ON o.id=p.operation_id WHERE p.operation_id=?',(oid,)).fetchone()
 if row:ops.append({'operation_id':oid,**dict(row),'receipt':next(j['path'] for j in journalpins if j['sequence']==row['sequence'])})
 else:ops.append({'operation_id':oid,'qualification':'Accepted historical import predates journal; native revision metadata retained.'})
save('accepted-direct-support-operation-index-v1.json',{'operations':ops,'note':'Reuse exact canonical envelopes, not duplicate aggregate receipt JSON.'})
child=read('evaluations/T-0813/preparation/native/P-0287.json');assert all(c.execute('SELECT id FROM current_revision WHERE object_id=?',(r['object_id'],)).fetchone()[0]==r['id'] for r in child['current']);edges=[r for r in child['current'] if r['kind']=='relation' and r['data']['relation_type']=='parent' and r['data']['to_person']=='P-0287' and r['data']['from_person'] in ['P-0336','P-0337']];assert len(edges)==2;save('exact-two-parent-to-Johannes-links-v1.json',{'fullnative_edges':edges,'child_full_current':'evaluations/T-0813/preparation/current-full/P-0287.json','child_native_current':'evaluations/T-0813/preparation/native/P-0287.json','child_current_heads_all_exact':True,'no_new_child_or_ancestor_review':True})
owner=read('evaluations/T-0813/preparation/all-current-OWNER-scope-v1.json');assert len(owner['OWNER_full_native'])==45;assert all(c.execute('SELECT id FROM current_revision WHERE object_id=?',(r['object_id'],)).fetchone()[0]==r['id'] for r in owner['OWNER_full_native']);save('OWNER-scope-reuse-v1.json',{'full_current_OWNER45':'evaluations/T-0813/preparation/all-current-OWNER-scope-v1.json','full25bases_and_exact6PCDs_in_same_packet':True,'current45_heads_exact':True,'unchanged_entire_canonical_DB':True,'structural_proof':'evaluations/T-0813/preparation/OWNER-reuse-comparison-v1.json','qualification':'Scope/provenance requires Astra reading; no implied focal OWNER fact or absence inference.'})
PC=Path('PROJECT-CONTROL.md').read_text();newpc=PC[PC.index('## PCD-2026-10-08-002'):];(D/'PCD-2026-10-08-002-snapshot.md').write_text(newpc)
for p in ['AGENTS.md','wotan/README.md','wotan/dev-log/T-0814.md','genealogy2/AGENTS.md','genealogy2/docs/working.md','docs/research/person-contract.md','docs/research/source-strategy.md']:
 q=D/'normative-snapshots'/p;q.parent.mkdir(parents=True,exist_ok=True);q.write_bytes(Path(p).read_bytes())
# No opening originals: preserve DB media locators/hash metadata only.
record_ids=[r['id'] for r in revisions if r['kind']=='record'];media=[]
for rid in record_ids:
 for row in c.execute('SELECT rm.*,m.* FROM record_media rm JOIN media m ON m.id=rm.media_id WHERE rm.revision_id=? ORDER BY rm.rowid',(rid,)).fetchall():media.append(dict(row))
save('existing-record-media-metadata-v1.json',{'record_media':media,'qualification':'Existing canonical hash/locator metadata only; originals neither opened nor interpreted in original-ceiling0 task.'})
# All current focal full semantic fields are included, independent of citation regex.
save('current-semantic-field-routing-v1.json',{'persons':[{'person':p,'fullnative_file':'evaluations/T-0814/preparation/native/'+p+'.json','covered_fields':['all native data fields including structured flags/status/outcomes','complete body/caveat/rationale','ordered evidence/origins','direct bound and current stronger versions'],'routing_only':True} for p in ['P-0336','P-0337']],'note':'Complete mechanical focal scope; no automatic correction, PASS, source promotion or regex certification.'})
backup=D/'baseline481.sqlite';out=sqlite3.connect(backup);c.backup(out);out.close();c.close();assert sha(base['main']['path'])==base['main']['sha256']
reuse=['evaluations/T-0813/preparation/actual-accepted-reconciliation-v1.json','evaluations/T-0813/preparation/accepted-delta468-481-v1.json','evaluations/T-0813/preparation/all-current-OWNER-scope-v1.json','evaluations/T-0813/preparation/OWNER-reuse-comparison-v1.json','evaluations/T-0813/preparation/current-full/P-0287.json','evaluations/T-0813/preparation/native/P-0287.json','evaluations/T-0812/implementation/stage481-v1/inventory-full.json','evaluations/T-0812/actual-main-stage-comparison-v1.json','evaluations/T-0814/root-start-baseline-v1.json','evaluations/T-0814/collect_usage.py']
for p in Path('evaluations/T-0814').glob('root-baseline-pedigree*.json'):reuse.append(str(p))
result={'state':state,'MAIN_unchanged':True,'focal_persons':2,'protected_child':'P-0287','parent_to_child_edges':len(edges),'current_OWNER':45,'baseline_backup':str(backup.relative_to(R)),'baseline_backup_sha256':sha(backup),'no_original_or_source_access':True,'no_native_or_queue_writes':True,'usage_collector':'UNRUN; root collects actual task turns after all final responses','completed_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()};save('preparation-result-v1.json',result)
files=[{'path':str(p.relative_to(R)),'sha256':sha(p)} for p in sorted(D.rglob('*')) if p.is_file()]+[{'path':p,'sha256':sha(p),'reuse':True} for p in reuse];save('locked-input-manifest-v1.json',{'task':'T-0814','main':base['main'],'state':state,'focal':['P-0336','P-0337'],'protected_child':'P-0287','original_ceiling':0,'files':files,'fullperson_index':'evaluations/T-0814/preparation/current-person-index-v1.json','native_support':'evaluations/T-0814/preparation/native-support-versions-v1.json','notes':['Metadata routing is not a SOURCE judgment.','Reuse sufficient accepted material and search memory exactly; no new original or ancestor/LIFE assessment.','45 current OWNER objects/25bases/six source-decision sections + new PCD002 locked together.']});print(json.dumps({'manifest_sha256':sha(D/'locked-input-manifest-v1.json'),'pins':len(files),'result':result}))
