from pathlib import Path
import sqlite3,json,importlib.util
R=Path(__file__).resolve().parents[3];O=Path(__file__).resolve().parent;s=importlib.util.spec_from_file_location('h',R/'evaluations/T-0784/implementation/stage_root_authorized_exact_nine_v2.py');h=importlib.util.module_from_spec(s);s.loader.exec_module(h);M=R/'genealogy2/data/research.sqlite';main=h.pin(M);c=h.conn(M);assert h.state(c)=={'journal_head':446,'pending':0};before=h.all50(c)
base=O/'baseline-j446.sqlite';assert not base.exists();d=sqlite3.connect(base);c.backup(d);d.close();b=h.conn(base);assert h.state(b)==h.state(c) and h.all50(b)==before
outputs=[]
for label,args,reference in [('inventory',['inventory'],'evaluations/T-0788/root-controlled-two-access-notes-v1/check-4.json'),('Adam-default-verified',['pedigree','P-0269'],'evaluations/T-0788/root-controlled-two-access-notes-v1/check-5.json'),('Axel-default-verified',['pedigree','P-0270'],'evaluations/T-0788/root-controlled-two-access-notes-v1/check-6.json')]:
 p=O/(label+'-current446.json');value=h.run_cli(args+['--db',str(base)],p);old=json.loads((R/reference).read_text());assert value==old;outputs.append({'fresh_pin':h.pin(p),'accepted446_reference_pin':h.pin(R/reference),'wholeJSON_equal':True})
assert h.pin(M)==main and h.all50(c)==before and h.state(c)=={'journal_head':446,'pending':0}
pp=R/'evaluations/T-0787/postlogin-originals/root-full3011-download-provenance-v1.json';p=json.loads(pp.read_text());original=R/p['path'];assert h.sha(original)==p['sha256']=='bded3192fc353a3be6114e0c12ff4de05e4feed99f669053e7dc69dd0659db96' and original.stat().st_size==p['bytes']==1313110
provenance=json.dumps(p,ensure_ascii=False,separators=(',',':'))
plan=h.write(O/'actual3011-full-original-hash-and-exact-stage-media-plan-UNRUN-v2.json',{'task':'T-0787','prior_route_plan_pin':h.pin(O/'exact3011-existing-download-route-and-documented-media-staging-plan-UNRUN-v1.json'),'root_actual_original_provenance_pin':h.pin(pp),'actual_original_pin':h.pin(original),'actual_original_bytes':p['bytes'],'root_verified_dimensions':[p['width'],p['height']],'expected_stage_media_result':{'id':'M-'+p['sha256'],'storagePath':'genealogy2/media/objects/'+p['sha256'],'sha256':p['sha256'],'bytes':p['bytes'],'originalName':original.name,'provenance':provenance},'exact_documented_stage_media_argv_UNRUN':['node','genealogy2/cli.mjs','stage-media',p['path'],'--provenance',provenance],'execution_status':'Prepared exactcommand; no media-file/nativeDB writes by Sol. Root execution authorization required.','no_source_reading_or_new_API_constructed':True})
out=h.write(O/'fresh446-physical-baseline-all50-inventory-and-both-default-verified-additive-proof-v1.json',{'main_pin':main,'baseline_pin':h.pin(base),'actual_state':h.state(c),'all50_main_equals_fresh_backup_and_remains_unchanged':True,'all50':before,'fresh_inventory_and_default_verified_reuse_proofs':outputs,'earlier_existing_head_and_protected42_reconciliation_pin':h.pin(O/'bounded-current446-existing-heads-fullnative-view-reuse-and-three-access-notes-reconciliation-v1.json'),'actual3011_media_preparation_pin':plan,'no_original_interpretation_build_apply_or_Wotan_write':True,'usage':'UNKNOWN pending root collector'});print(json.dumps({'proof_pin':out,'actual_state':h.state(c),'media_plan_pin':plan}));c.close();b.close()
