import json,pathlib,hashlib,copy,time
R=pathlib.Path.cwd();E=R/'evaluations/T-0816';D=E/'candidate-v1';start=time.monotonic()
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def read(p):return json.load(open(p))
def save(n,v):(D/n).write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
inputs={'evaluations/T-0816/settled-source-design-v3.json':'cf9fc039fc6ad42e2606674f2f1f841fce7429361b69868c729491528faedc2a','evaluations/T-0816/settled-fixed160-successor-transfer-v3.json':'dc8d0450d785112150daf9dc973cdfbe810c899544b38c9b3ca25a2d644cd3c0','evaluations/T-0816/independent-settled-source-design-gate-v1.json':'684a61f640dadafc5c8de741e2d1795511ae11c72b01f458b44954a3325025bd'}
for p,h in inputs.items():assert sha(R/p)==h
spec=read(R/next(iter(inputs)));gate=read(R/list(inputs)[2]);assert gate['approved_for_literal_materialization'];tr=read(R/spec['transfer']['path']);prev=read(R/'evaluations/T-0813/settled-fixed160-successor-transfer-v1.json');assert tr['preserved_previous_transfer']==prev;assert tr['fixed160']==prev['fixed160'];assert len(tr['fixed160'])==160;appendix=tr['full_T0791_T0792_planning_appendices'];assert appendix==prev['full_T0791_T0792_planning_appendices']and len(appendix)==4898;assert hashlib.sha256(appendix.encode()).hexdigest()==tr['appendices_sha256']
base=read(R/'wotan/backlog.json');assert base['next_id']==818;assert next(t for t in base['tasks']if t['id']=='T-0816')['status']=='ONGOING';(D/'baseline-backlog.json').write_bytes((R/'wotan/backlog.json').read_bytes());new=[];logs=[]
for t in spec['tasks']:
 assert t['status']=='READY'and t['after']==[]
 n={k:copy.deepcopy(t[k])for k in ['id','status','size','priority','priority_basis','after']};n['summary']=t['title'];n['note']=t['mandate']+' Se wotan/dev-log/'+t['id']+'.md; inget utförandemandat genom allocation.';new.append(n)
 parts=['# '+t['id']+' — '+t['title'],'','- Size: '+t['size'],'- Status: READY','- Phase: —','- Priority: '+t['priority'],'- After: []','','## Omfång och mandat','',t['mandate'],'','T-0816:s aktuella originaltak är0; ingen källa öppnas eller nativeändring görs genom detta planeringspaket.']
 for key,label in [('scope','Exakt fastställd avgränsning'),('active_owner','Aktivt planeringsägarskap vid faktisk allocation'),('accepted_reuse','Accepterat återbruk'),('access','Åtkomst och faktisk kopiekontroll'),('exclusions','Utanför omfånget'),('trigger','Verkligt återstartvillkor'),('life_decision','Ändligt nära livsbildsbeslut'),('lossless_partition','Förlustfri exakt atompartition')]:
  if key in t:
   v=t[key];text=v if isinstance(v,str)else json.dumps(v,ensure_ascii=False,indent=2);parts+=['','## '+label,'',text]
 parts+=['','## Acceptance Criteria','']+[f'{i+1}. {x}'for i,x in enumerate(t['acceptance'])]
 if t['id']=='T-0819':
  parts+=['','## Full förlustfri fast160/source_plan-transfer','','Historiska innerägare/source_plan bevaras exakt. Aktuell ytterägare och exklusiva atomägare redovisas separat enligt följande hela avgjorda transfer; faktisk rootallocation återstår.','','```json',json.dumps(tr,ensure_ascii=False,indent=2),'```','','## Oförkortad historisk T0791/T0792-planeringsappendix','',appendix]
 parts+=['','## Exakt bokstavlig SOURCE-design','','```json',json.dumps(t,ensure_ascii=False,indent=2),'```','','## Hashbundna avgjorda ingångar','']+[f'- {p} SHA256 {h}'for p,h in inputs.items()]
 parts+=['','## Återupptagning — literal kandidat','','2026-10-08: endast kandidat. Fulla SOURCE-designgrindar godkänner materialisering; separat bokstavlig paketgrind och faktisk rootallocation återstår. READY är inte ONGOING eller utförandemandat. Nästa ej utförda steg är rootverifierad allocation efter exakta dubbla literalgrindar. Därefter kan uppgiften endast startas inom ett nytt faktiskt mandat; T0814–T0816beställningen avslutas medT0816.']
 p=D/(t['id']+'.md');p.write_text('\n'.join(parts)+'\n');logs.append({'task':t['id'],'path':str(p.relative_to(R)),'sha256':sha(p)})
alloc=copy.deepcopy(base);at=next(i for i,t in enumerate(base['tasks'])if t['id']=='T-0817')+1;assert base['tasks'][at]['id']=='T-0217';alloc['tasks'][at:at]=new;alloc['next_id']=820;save('backlog.json',alloc)
assert [t for t in alloc['tasks']if t['id']not in ['T-0818','T-0819']]==base['tasks'];assert len({t['id']for t in alloc['tasks']})==len(alloc['tasks']);assert appendix in (D/'T-0819.md').read_text();assert json.dumps(tr,ensure_ascii=False,indent=2)in (D/'T-0819.md').read_text()
appendproof=[]
for tid,append in spec['existing_task_appends'].items():
 p=R/'wotan/dev-log'/(tid+'.md');old=p.read_bytes();candidate=old+append.encode();(D/(tid+'-preimage.md')).write_bytes(old);q=D/(tid+'.md');q.write_bytes(candidate);assert q.read_bytes()[:len(old)]==old;assert q.read_bytes()[len(old):].decode()==append;appendproof.append({'task':tid,'old_sha256':sha(p),'candidate_sha256':sha(q),'old_prefix_bytes':len(old),'source_append_exact':True,'source_append':append})
assert spec['native_changes']==spec['originals_opened']==0
proof={'passed':True,'old_task_count':len(base['tasks']),'new_task_count':len(alloc['tasks']),'all817old_record_values_and_relative_order_exact':True,'T0816_ONGOING_fullrecord_preserved':True,'insert_after':'T-0817','insert_before':'T-0217','new_order':['T-0818','T-0819'],'next_id_before':818,'next_id_after':820,'all_new_after_empty':True,'full160rows_source_plan_exact':True,'full_previous_transfer_exact':True,'full4898appendix_exact':True,'current_owner_overlay_exact':tr['current_postallocation_atom_ownership'],'old_log_appendices':appendproof,'other_old_logs_not_written':True,'node_links_sha256':sha(R/'wotan/node-links.json'),'main_sha256':sha(R/'genealogy2/data/research.sqlite'),'native_changes':0,'originals_opened':0,'live_queue_writes':0,'elapsed_seconds':time.monotonic()-start};save('preservation-proof.json',proof)
save('individual-consequence-table.json',{'old_records':[{'task':t['id'],'disposition':'RETAIN_FULL_RECORD_AND_RELATIVE_ORDER','before':t,'after':t}for t in base['tasks']],'new_records':[{'task':n['id'],'disposition':'CREATE_BOUNDED_READY_NO_EXECUTION_MANDATE','after':n,'source_design':spec['tasks'][i],'log':logs[i]}for i,n in enumerate(new)],'old_log_appends':appendproof,'fixed160_transfer':{'disposition':'FULL_LOSSLESS_TRANSFER_ONLY_AFTER_ACTUAL_ROOT_ALLOCATION','path':spec['transfer']['path'],'sha256':spec['transfer']['sha256'],'whole_previous_transfer_exact':True,'current_owner_overlay':tr['current_postallocation_atom_ownership']},'native_changes':0,'originals_opened':0})
print('Candidate built:',len(base['tasks']),'old/',len(alloc['tasks']),'total, full160/appendix/2prefixes PASS')
