import json,pathlib,hashlib
b=pathlib.Path('evaluations/T-0790');p=b/'source-review/primary-own-90-dispositions-and-exact-changes-v1.json';own=b/'independent-review/own-freeze-v1.json';d=json.loads(p.read_text());o=json.loads(own.read_text());lookup={(r['person'],('PK-'+r['code'] if r['kind']=='PK' else r['code'])):r for r in o['individual_rows']}
rows=[]
for r in d['individual_table']:
 key=(r['person'],r['item']);reason='Compatible in substance; subject to exact v2 wording, support and final stage review.'
 if key==('P-0212','PK-06'):reason='Amend both initial failed judgments: literal current PK06 requires individually assessed ten themes with scope/support/gaps/possible routes, not all routes completed. Agreed STYRKT after current complete assessment. Native life remains failed through03/04/08.'
 if key==('P-0006','MIL'):reason='Accept primary change to INTEGRITETSMINIMERAT; clearer than independent conditional retention of EJ RELEVANT as narrow source priority. No negative service/sailing fact.'
 if key in [('P-0212','MIL'),('P-0212','EKO')]:reason='Agree ÖPPET; dated local catalogue limit remains explicit, universal exhaustion removed. Independent freeze allowed narrowly AVGRÄNSAT for MIL but open accurately exposes untested alternatives.'
 if key==('P-0005','REL'):reason='Accept two younger named sisters on native1940/1945 versus1938; must also correct PK04 older-sister copy and preserve stronger CORROBORATED maternal relation.'
 if key==('P-0005','PK-04'):reason='Retain STYRKT, revise stale older-sisters wording and add stronger current maternal support; v1 literal retain insufficient.'
 if key in [('P-0211','PK-03'),('P-0211','PK-10'),('P-0211','SYN')]:reason='Agree outcome after consolidation; include already accepted daughter1964 anchor with1962/2017, not just birth/marriage/widowhood.'
 if key==('P-0212','PK-10'):reason='STYRKT after exact BIO corrections including Stockholmstrakten and undated training/meeting chronology, not merely catalogue paragraph.'
 rows.append({'person':key[0],'item':key[1],'primary_v1_outcome':r['new_outcome'],'primary_v1_disposition':r['disposition'],'independent_frozen_judgment':lookup[key]['independent_disposition'],'comparison_decision':reason})
obj={'schema':'T0790-independent-comparison/1','primary_v1_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'independent_own_freeze_sha256':hashlib.sha256(own.read_bytes()).hexdigest(),'individual_comparisons':rows,'v1_exact_changes_review':'25 reviewed conceptually and exact new texts read; NOT approved as complete. Independent ten finding groups, stale PK04 sibling copy, Q02 largely nondigital claim, LIBRIS query count and Evy1964 anchor must resolve in v2.','six_native_review_agreement':{'P-0004':'failed','P-0210':'failed','P-0005':'failed','P-0006':'failed','P-0211':'passed after justified current consolidation','P-0212':'failed'},'bounded_T0795_assessment':{'necessity':'C0906 did not support universal exhausted online routes; targeted six unit routing can distinguish actual access boundaries and known missing keys for deceased Gunnar. It does not require whole-source rereview.','permitted_design':'Six units: military routing circa1953; Floby/Fredriksberg school archives1967–2017; teacher/school-leader lists1950–1980; possible Floby property1960s; possible estate2017; cultural committee/Liberal/FN pre2017 including2008. Up to2metadata entries per unit/max12.','constraints':'Metadata/routing only, no personal original, image, health data, order, contact, free namesearch or living-relative collection. No assumed military service/property/estate existence. Existing T0359/T0362 are separate owners, not fabricated dependencies. Missing key needs exact acquisition path and source/time/field scope. Scope cap result may be partial; no guaranteed access/source exhaustion.','execution_authorized_here':False},'exact_v2_approval':False,'final_stage_approval':False}
assert len(rows)==90
out=b/'independent-review/comparison-decisions-v1.json';out.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n');print(hashlib.sha256(out.read_bytes()).hexdigest())
