import json,pathlib,hashlib
b=pathlib.Path('evaluations/T-0790');p=b/'preparation/reviewed-stage-v1/actual-requests-full-context.json';d=json.loads(p.read_text());o=d['objects'];a=json.loads(o['O-P-0212-C0903-child@2']['data']['value_json']);z=json.loads(o['O-P-0212-C0903-child@3']['data']['value_json']);delta=[k for k in set(a)|set(z) if a.get(k)!=z.get(k)];assert delta==['column9']
reasons={
'EP-E-birth-P-0212-P-0212-principal@1':('Födelsens principalroll','Gunnar är samma principal i E-birth-P0212. C0902daterade barnpost, familjedatum C0268 och C0903namn/datum samverkar inom accepterad kedja. Kolumn9prövningsstatus tillför inget konkurrerande barn. Registrerad Engelbrekt/förlossningsadressokänd behålls.','O-P-0212-C0902-child@1,O-P-0212-C0268-own@1,E-birth-P-0212@1'),
'F-P-0212-name_form-source_comparison@2':('Dokumentär namnordning','C0903literal Ivar Gunnar Emanuel ändras inte i@3. CONFLICT/order_conflict_unresolved gäller dokumentärt ursprung/administrativt beroende enligt hela aktuella caveaten, inte identitet eller ägarbeslut. OWNER Gunnar Ivar Emanuel står fast; kolumn9tolkning kan inte avgöra ordningsfrågan.','F-P-0212-name-owner-confirmed@1,O-P-0212-C0236-own@1,O-P-0212-C0904-own@1'),
'F-P-0212-source_reference-Lidingo1951@2':('Egen1719/51 och kolumn9metastatus','Nuvarande@2 har redan own_column9_unread:false och prövad men olöst FIRST/SECOND-reserv. O@3 återställer just överensstämmelsen och förändrar inte1719,1951,tal105 eller nästa bok oläst. Ingen ny ort/handling följer. Behåll@2 utan onödig cirkulär ombindning till O@3, som själv stöds av detta tidigare sakbeslut.','F-P-0240-household_membership-Lidingo-family@1,AUDIT-T0675-HOOK-4@1'),
'E-birth-P-0212@1':('Födelsehändelse1933-03-26','Datumfältet1933-03-26 i O@1/@2/@3 är identiskt; det stöds även av C0902 och C0268. Kolumn9är en senare hushållsnot med olöst innehåll, inte ett ändrat födelsedatum eller fysisk förlossningsplats. Accepterad CORROBORATED händelse och registreringsroll behålls.','O-P-0212-C0902-child@1,O-P-0212-C0268-own@1'),
'EP-E-registered_arrival-Hook-family-Lidingo1946-P-0212-principal@1':('Deltagande i1946registrering','Gunnars egen hushållsrad/mention och familjemedlemskap är oförändrade. Familjens registrerade inflyttning1946-09-13 står i eget event och familjekontext; O@3tolkar inte kolumn9som annan flytt. Ingen exakt ankomstadress eller fysisk reskedja införs.','F-P-0240-household_membership-Lidingo-family@1,E-registered_arrival-Hook-family-Lidingo1946@1'),
'F-P-0212-event_place-birth@1':('Registrerad födelseförsamling/stad','O@3 behåller Engelbrekt St. och C0902har samma registreringskontext. Nuvarande structured register_parishEngelbrekt/cityStockholm och physical_birth_address:null med caveat ger inget förlossningshus. Den olösta kolumn9notisen kan inte ersätta dessa ortgränser eller säkra fysisk hemresa.','O-P-0212-C0902-child@1,AS-P-0240-registration-limits@1'),
'F-P-0212-rejected_claim-foreign_birth@1':('Avvisat äldre utlandsantagande','Indirekt beroende via födelseplatsfaktum: gamla sannoliktutomlands-antagandet förblir tillbakadraget. Faderns utreseregistrering1931avgör inte barnets fysiska födelseplats. Accepterad Engelbrektregistrering kvar; avgränsade söknoll bevisar inte utlänsk födelse. Kolumn9status har ingen sådan bevisverkan.','F-P-0212-event_place-birth@1,SEARCH-Hook-C0887-birth-marriage1933@1,E-registered_departure-P-0239@1'),
'F-P-0212-church_note-1933-1946@1':('Daterade dopnoter och lifetimegräns','Odöptgossebarn1933och icke döpt av sv.kyrkan1946–51 är orörda i C0902/C0903. lifetime_baptism_excluded:false är redan rätt avgränsning; olöst kolumn9 blir ingen dopnot eller senare trosuppgift. Behåll TRANSCRIBED utan ny faktaversion.','O-P-0212-C0902-child@1'),
'F-P-0212-rejected_claim-A1479@2':('Avvisat sammansatt sekundärpåstående','Indirekt via födelseplats/namnjämförelse. Hela gamla Lidingöförlagda påståendet avvisas, medan datumet accepteras och raw Ivar Gunnar Emanuel bevaras. Aktuell@2caveat skiljer dokumentär namnfråga från OWNER; kolumn9metadata förändrar ingen av dessa sakdelar. Ingen återupplivad personosäkerhet eller nytt namnbyte.','F-P-0212-event_place-birth@1,F-P-0212-name_form-source_comparison@2,F-P-0212-name-owner-confirmed@1,O-P-0212-C0236-own@1')}
rows=[]
for r in d['requests']:
 k=r['affected_revision_id'];field,reason,support=reasons[k];rows.append({**r,'own_disposition':'retain_current_conclusion','requires_new_affected_revision':False,'requires_evidence_rebind':False,'exact_field_scope':field,'rationale':reason,'stronger_or_unchanged_support':support.split(','),'preservation':'Keep complete current body/data/caveat/disposition/evidenceStatus/origins/evidence exactly; resolve only this actual request with individual reason. No new independent source voice.'})
out={'schema':'T0790-independent-actual-nine-freeze/1','primary_dependency_proposals_seen':False,'input_sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'actual_state':d['actual_state'],'changed_revision':'O-P-0212-C0903-child@3','actual_value_delta':delta,'source_limit':'Accepted current/native and selected complete relevant upstream/history read; no originals/images/catalog/network/runtime/canonical.55available is not55readcredit. Full nine current affected bodies+caveats/evidence, changedO@1/@2/@3, relevant stronger named sources and historic qualified revisions considered.','individual_decisions':rows,'blanket_retain_rule':False,'final_stage_source_approval':False};f=b/'independent-review/actual-nine-own-freeze-v1.json';f.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(hashlib.sha256(f.read_bytes()).hexdigest())
