import sqlite3,json,pathlib,hashlib
b=pathlib.Path('evaluations/T-0790');db=b/'preparation/reviewed-stage-v1/stage.sqlite';c=sqlite3.connect('file:'+str(db)+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;errs=[];checked=[]
paths=[b/'preparation/materialized-source-v3-literal-v1/operation-literal.json',b/'preparation/final-three-literal-draft-v1/operation-final-three-literal.json']
def norm(d):return {k:json.loads(v) if k.endswith('_json') and isinstance(v,str) else v for k,v in d.items() if k!='revision_id'}
def ck(x,y):
 if not x:errs.append(y)
for p in paths:
 for api in json.load(open(p))['changes']:
  r=dict(c.execute('select * from revision where object_id=? order by version desc limit 1',(api['id'],)).fetchone());d=dict(c.execute('select * from "'+api['kind']+'" where revision_id=?',(r['id'],)).fetchone());ck(r['version']==(api['expectedVersion'] or 0)+1,['version',api['id']]);ck(norm(d)==api['data'],['data',api['id']]);
  for x,y in [('disposition','disposition'),('evidence_status','evidenceStatus'),('rationale','rationale'),('caveat','caveat')]:ck(r[x]==api[y],[x,api['id']])
  origins=[{'unit':x['unit_id'],'coverage':x['coverage'],'note':x['note']} for x in c.execute('select * from origin where revision_id=?',(r['id'],))];edges=[{'object':x['basis_revision_id'].rsplit('@',1)[0],'version':int(x['basis_revision_id'].rsplit('@',1)[1]),'role':x['role'],'note':x['note']} for x in c.execute('select * from dependency where revision_id=?',(r['id'],))];sort=lambda z:sorted(z,key=lambda x:json.dumps(x,sort_keys=True));ck(sort(origins)==sort(api['origins']),['origins',api['id']]);ck(sort(edges)==sort(api['evidence']),['edges',api['id']]);checked.append(r['id'])
pending=c.execute('select count(*) from review_request q left join review_resolution z on z.request_id=q.id where z.request_id is null').fetchone()[0];ck(pending==0,'pending')
reviews=[dict(r) for r in c.execute("select a.subject_id,a.criteria,a.outcome,r.evidence_status from assessment a join revision r on a.revision_id=r.id where r.operation_id='T0790-existing-material-life-six-v1' and a.criteria='life_picture_review/1'")];ck(len(reviews)==6,'6reviews');ck({r['subject_id']:r['outcome'] for r in reviews}=={'P-0004':'failed','P-0210':'failed','P-0005':'failed','P-0006':'failed','P-0211':'passed','P-0212':'failed'},'outcomes');ck(all(r['evidence_status'] is None for r in reviews),'nullstatus')
res={'stage_sha256':hashlib.sha256(db.read_bytes()).hexdigest(),'full_API_current_revisions_checked':checked,'errors':errs,'pending':pending,'six_life_reviews':reviews,'source_semantic_result':'Stage457current targeted pattern search preserves legitimate historical wrappers/reservations; three held sourcecopy findings now explicit correctedcurrent qualifiers; twoOeditorial omissionlabels remain individually justified. No current asserted global source exhaustion, unsupported Stockholmresidence, lifelong nodop or maternal downgrade in reviewed scope.','limits':'479current semantic candidates scanned,114patternhits triaged using prior complete readings and changed bodies/caveats. This is not479newsource/full-record reads. Arrayorder native preservation uses pinned full50proof; content of all43APIs independently checked directly in readonlystage.'};f=b/'independent-review/final457-direct-source-verification-v1.json';f.write_text(json.dumps(res,ensure_ascii=False,indent=2)+'\n');print(errs,hashlib.sha256(f.read_bytes()).hexdigest())
