import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';import {execFileSync} from 'node:child_process';
import {openDB} from '../../../genealogy2/lib/store.mjs';import {personView,inspect} from '../../../genealogy2/lib/domain.mjs';
const start=new Date().toISOString(),db=openDB('genealogy2/data/research.sqlite',{readOnly:true});const hash=x=>crypto.createHash('sha256').update(x).digest('hex');const write=(p,x)=>fs.writeFileSync(p,typeof x==='string'?x:JSON.stringify(x,null,2)+'\n',{flag:'wx'});
const seq=db.prepare('SELECT * FROM operation_payload ORDER BY sequence').all();const journal=fs.readdirSync('genealogy2/journal').filter(f=>f.endsWith('.json')).sort();const reconciliation={sequence:seq.length,lastSequence:seq.at(-1)?.sequence,journalFiles:journal.length,pendingReviews:db.prepare('SELECT count(*) n FROM review_request r LEFT JOIN review_resolution s ON s.request_id=r.id WHERE s.request_id IS NULL').get().n,accepted:seq.map(o=>{const f=journal.find(f=>f.startsWith(String(o.sequence).padStart(9,'0')+'-'));return {...o,request_json:undefined,request_sha256:hash(o.request_json),journalFile:f??null,journalHash:f?hash(fs.readFileSync('genealogy2/journal/'+f)):null};})};
for(const [task,people] of [['T-0791',['P-0003','P-0007','P-0001','P-0002']],['T-0792',['P-0241','P-0246','P-0239','P-0240']]]){const dir=`evaluations/${task}/preparation`;write(`${dir}/reconciliation.json`,reconciliation);write(`${dir}/git-status-baseline.txt`,execFileSync('git',['status','--short'],{encoding:'utf8',maxBuffer:20e6}));const all=new Set(),cites=new Set();
for(const p of people){const view=personView(db,p);write(`${dir}/${p}-full.json`,view);function walk(v){if(!v||typeof v!=='object')return;if(v.object_id)all.add(v.object_id);if(v.revision_id)all.add(v.revision_id.split('@')[0]);for(const a of Object.values(v)){if(typeof a==='string')for(const c of a.matchAll(/\bC-\d{4}\b/g))cites.add(c[0]);else if(typeof a==='object')walk(a);}}walk(view);const legacy=db.prepare('SELECT d.* FROM legacy_entity e JOIN document d ON d.path=e.document_path WHERE e.id=? ORDER BY e.kind').all(p);write(`${dir}/${p}-frozen-context.json`,legacy);}
const queue=[...all];for(let i=0;i<queue.length;i++){const id=queue[i];const o=inspect(db,id);write(`${dir}/object-${id.replaceAll('/','_')}.json`,o);const r=o.current;if(!r)continue;for(const e of r.evidence??[]){const basis=e.basis_revision_id.split('@')[0];if(!all.has(basis)){all.add(basis);queue.push(basis);}}for(const k of ['record_id','source_id','mention_id'])if(r[k]&&!all.has(r[k])){all.add(r[k]);queue.push(r[k]);}for(const c of JSON.stringify(o).matchAll(/\bC-\d{4}\b/g))cites.add(c[0]);}
write(`${dir}/accepted-object-operations.json`,db.prepare('SELECT * FROM operation ORDER BY recorded_at,id').all().filter(o=>db.prepare('SELECT object_id FROM revision WHERE operation_id=?').all(o.id).some(r=>all.has(r.object_id))).map(o=>({...o,payload:seq.find(s=>s.operation_id===o.id)})));
const citations=[...cites].sort().map(c=>({id:c,inspection:inspect(db,c),frozen:db.prepare('SELECT d.* FROM legacy_entity e JOIN document d ON d.path=e.document_path WHERE e.id=?').all(c)}));write(`${dir}/accepted-citation-context.json`,citations);
write(`${dir}/source-owner-routing.json`,{note:'Mechanical text candidates only; owners and evidence adequacy require Astra judgement. No original or external sources opened.',tasks:JSON.parse(fs.readFileSync('wotan/backlog.json')).tasks.filter(t=>people.some(p=>JSON.stringify(t).includes(p))||[task,'T-0677','T-0793'].includes(t.id)),citedIds:[...cites].sort(),operations:db.prepare('SELECT * FROM operation ORDER BY recorded_at,id').all().filter(o=>people.some(p=>o.reason.includes(p)))});
for(const [name,args] of [['inventory',['inventory']],['pedigree-P-0269',['pedigree','P-0269']],['pedigree-P-0270',['pedigree','P-0270']],['priority',['scripts/wotan-priority.mjs']]])write(`${dir}/${name}.json`,execFileSync('node',name==='priority'?args:['genealogy2/cli.mjs',...args],{encoding:'utf8',maxBuffer:40e6}));
const manifest=fs.readdirSync(dir).filter(f=>f!=='prepare-inputs.mjs').sort().map(f=>({path:dir+'/'+f,bytes:fs.statSync(dir+'/'+f).size,sha256:hash(fs.readFileSync(dir+'/'+f))}));write(`${dir}/input-manifest.json`,{task,people,scope:'Existing accepted material only; no originals/catalog/external searching. Life PK03/04/06/08/10 and ten themes. Mechanical preparation has no candidate claims or evidence judgements.',baseline:{lastSequence:seq.at(-1)?.sequence,pendingReviews:reconciliation.pendingReviews},started:start,finished:new Date().toISOString(),files:manifest,objectIds:[...all].sort(),citedIds:[...cites].sort()});write(`${dir}/INPUT-INDEX.md`,`# ${task} locked inputs\n\nFull person JSON contains complete research, caveats, facts, identities, relations, narratives, OWNER support and review state. Each object-* file has current complete object and all historical versions/evidence/origins. Evidence and source closure is recursive. Accepted-object-operations identifies actual canonical accepted requests. accepted-citation-context preserves full frozen citation text and current representations; it is accepted reuse, not new original reading. Frozen person/profile context is retained as history, never current execution. source-owner-routing contains mechanical candidates, not certified ownership or source adequacy.\n\nScope: ${people.join(', ')}. Baseline journal ${seq.at(-1)?.sequence}, pending ${reconciliation.pendingReviews}. T-0792 preparation is read-only; reconcile again after T-0791 canonical apply.\n\nPrimary Astra must judge each PK and theme individually, preserve all reservations/OWNER and exact scope, and provide exact dispositions including retains. Independent Astra first records its independent existing-material assessment before viewing candidates; final approval must bind staged package hashes. No new original/catalog/search is authorized. Unread fields need exact bounded source owner before DONE.\n\nFiles/hashes: input-manifest.json. No canonical changes performed.\n`);
}
db.close();console.log(JSON.stringify({start,end:new Date().toISOString(),sequence:seq.length,pending:reconciliation.pendingReviews}));
