import pathlib,json,hashlib,shutil,time
R=pathlib.Path.cwd();D=R/'evaluations/T-0812';I=D/'implementation';S=I/'stage480-v1';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();axes=json.load(open(S/'final-axis-differences-and-relation-proof.json'));assert axes['persons']==536 and [x['person']for x in axes['all_person_axis_differences']]==['P-0254','P-0255'];assert axes['all_relation_native_exact']and len(axes['relations'])==20;result=json.load(open(S/'result.json'));assert result['state']=={'journal_head':480,'pending':0};inv=json.load(open(S/'inventory-full.json'));people={x['id']:x for x in inv['people']};focal=[]
for pid in ['P-0255','P-0254']:
 p=people[pid];assert p['identityReview']['outcome']=='passed'and p['identityReview']['usable'];assert p['treeEffect']['outcome']=='supporting'and p['treeEffect']['usable'];life=p['lifePictureReview'];assert life['outcome']=='failed'and life['usable'];focal.append({'person':pid,'identityReview':p['identityReview'],'treeEffect':p['treeEffect'],'legacyFullContract':life})
controls=[]
for pid in ['P-0269','P-0270']:
 b=json.load(open(R/'evaluations/T-0811/implementation/stage477-v2'/(pid+'-pedigree.json')));a=json.load(open(S/(pid+'-pedigree.json')));key=lambda x:json.dumps(x,sort_keys=True);bs={key(x)for x in b['paths']};assert bs<={key(x)for x in a['paths']};added=[x for x in a['paths']if key(x)not in bs];assert len(b['paths'])==38 and len(a['paths'])==41 and {x['person']for x in added}=={'P-0254','P-0255','P-0315'};controls.append({'root':pid,'baseline':38,'final':41,'all_old_paths_exact':True,'added_paths':added})
for name in ['verify.json','verify-assets.json','verify-source.json']:
 v=json.load(open(S/name));assert v['ok']and not v['errors']
proof=json.load(open(S/'final-native-142-and-136-resolution-proof.json'));assert len(proof['full_final_native_changes'])==142 and len(proof['individual136_stored_resolutions'])==136 and len(proof['all_old_retain_native_versions_preserved'])==469
baseline=json.load(open(D/'preparation/baseline-state-v1.json'));assert sha(R/'genealogy2/data/research.sqlite')==baseline['main']['sha256'];qualified={'task':'T-0812','state':result['state'],'changes142_full_native_exact':True,'individual136_resolutions_order_rationales_exact':True,'step_retains':[378,89,2],'step_retain_rows_total':469,'unique_retained_objects_not_claimed':True,'field_scope_retains':5,'new_media':0,'originals_read':2,'existing_originals_reused':2,'old44nonderived_rows_order_preserved':True,'persons':536,'nonfocal534_full_axes_exact':True,'relations20_full_native_exact':True,'focal_reviews':focal,'focal_legacy_backing_revision':'ASSESSMENT-P0254/P0255@1→@2 source-approved copy qualification; fullcontract failed scope unchanged, no native LIFE created','pedigree_controls':controls,'verify_assets_pass':True,'main477_unchanged':True,'attempts_preserved':['initial478 actual134','repairtableV1 sourceextras correctedONLYtableV2','fresh477→478→479 actual2','immutable479→480 exacttworesolve','builderconsole inherited six/five label onlystdout, actualJSONtwo/two exact'],'actual_dependency_exposure':'Both own134 and own2 assessments sealed ROOT ONLY before comparison release.','P0315_path_qualification':'Third addedpath is P0315 with preexisting passed/supporting gate EXACT baseline; no new P0315identity decision. All534nonfocal fullreview structures unchanged.','elapsed_seconds':{'initial':json.load(open(I/'stage478-v1/initial-result.json'))['elapsed_seconds'],'two_op_sequence':json.load(open(I/'stage479-sequence-v1/result.json'))['elapsed_seconds'],'third':result['elapsed_seconds'],'final_readers':json.load(open(S/'reader-capture-result.json'))['elapsed_seconds']},'model_usage':'unknown; root captures role usage after final responses','canonical_apply':'Root only; worker did not apply'};q=S/'qualified-final-result-v1.json';assert not q.exists();q.write_text(json.dumps(qualified,ensure_ascii=False,indent=2)+'\n')
N=D/'preparation/normative-snapshots-final-v1';assert not N.exists();N.mkdir();snap=[]
for name in ['AGENTS.md','wotan/README.md','wotan/dev-log/T-0812.md','wotan/dev-log/T-0420.md','wotan/dev-log/T-0215.md','genealogy2/docs/working.md','docs/research/person-contract.md','docs/research/riksarkivet-access.md']:
 dst=N/name.replace('/','__');shutil.copyfile(R/name,dst);snap.append({'source':name,'snapshot':str(dst.relative_to(R)),'sha256':sha(dst),'qualification':'Immutable precompletion scope/norm snapshot; root Wotan closure may later change live status.'})
(N/'snapshot-index.json').write_text(json.dumps(snap,ensure_ascii=False,indent=2)+'\n');paths=[p for p in D.rglob('*')if p.is_file()and '__pycache__'not in p.parts and p.suffix!='.pyc'and 'final-source-gate'not in p.name and p.name!='final-manifest-v1.json'];paths+=[R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py'];
for fn in ['locked-current-input-manifest-v1.json']:
 m=json.load(open(D/'preparation'/fn));paths += [R/x['path']for x in m['files']]
for pin in json.load(open(D/'preparation/current-reader-reuse-pins-v1.json'))['reuse']:paths.append(R/pin['path'])
for unit in json.load(open(D/'preparation/proposed-two-unit-media-metadata-v1.json'))['units']:
 for record in unit['records']:
  for entry in record['local_original_metadata']:
   asset=entry['asset'];path=R/asset['path'];assert sha(path)==asset['actual_sha256'];paths.append(path)
files=[{'path':str(p.relative_to(R)),'sha256':sha(p)}for p in sorted(set(paths))];ops=['operation-v1.json','repair-operation-v1.json','two-resolution-operation-v1.json'];tables=['consequence-table-v1.json','repair-consequence-table-v2.json','two-resolution-consequence-table-v1.json'];pin=lambda p:{'path':str(p.relative_to(R)),'sha256':sha(p)};manifest={'task':'T-0812','baseline_state':{'journal_head':477,'pending':0},'baseline_main_sha256':baseline['main']['sha256'],'final_state':result['state'],'stage_database':pin(S/'stage.sqlite'),'operations':[pin(I/x)for x in ops],'consequence_tables':[pin(I/x)for x in tables],'qualified_result':pin(q),'file_count':len(files),'files':files,'canonicalApproval':False};p=D/'final-manifest-v1.json';assert not p.exists();p.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');print('manifest',sha(p),'pins',len(files),'db',sha(S/'stage.sqlite'))
