import pathlib,json,hashlib,shutil,subprocess,time,importlib.util,traceback
R=pathlib.Path.cwd();D=R/'evaluations/T-0812';I=D/'implementation';MAIN=R/'genealogy2/data/research.sqlite';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();s=importlib.util.spec_from_file_location('h',R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py');h=importlib.util.module_from_spec(s);s.loader.exec_module(h)
def save(p,v):assert not p.exists();p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
def main():
 start=time.monotonic();b=json.load(open(D/'preparation/baseline-state-v1.json'));assert sha(MAIN)==b['main']['sha256'];pin=json.load(open(I/'third-stage-preimage-pin-v1.json'));source=R/pin['path'];assert sha(source)==pin['sha256'];old=h.conn(source);assert h.state(old)=={'journal_head':479,'pending':2};opath=I/'two-resolution-operation-v1.json';tpath=I/'two-resolution-consequence-table-v1.json';assert sha(opath)=='fe6ac43d9de5bf9d57ce104d81321ffe76f775b0129efd37c015f3e3f10bf8fd';assert sha(tpath)=='592eccdf5b17f17de4e1cab6b329a86bac90ff2eefbecd43bbd8f982d6b07605';op=json.load(open(opath));table=json.load(open(tpath));assert op['changes']==[]
 for t in table['retains']:assert h.native(old,h.current(old,t['old_native']['object_id']))==t['old_native']
 S=I/'stage480-v1';assert not S.exists();S.mkdir();db=S/'stage.sqlite';shutil.copyfile(source,db);journal=S/'journal';journal.mkdir()
 try:
  args=['node','genealogy2/cli.mjs','apply',str(opath),'--db',str(db),'--journal',str(journal)];r=subprocess.run(args,capture_output=True,text=True);(S/'apply.json').write_text(r.stdout);save(S/'apply.process.json',{'args':args,'exit':r.returncode,'stderr':r.stderr});assert r.returncode==0,r.stderr;c=h.conn(db);assert h.state(c)['journal_head']==480;accepted=dict(c.execute('select *from operation_payload where operation_id=?',(op['id'],)).fetchone());assert json.loads(accepted['request_json'])=={**op,'dependencyReviewVersion':2,'searchMemoryVersion':1};save(S/'accepted-request-normalization-proof.json',{'raw_operation':op,'actual_accepted':accepted,'only_supported_metadata_defaults':True});pending=[dict(x)for x in c.execute('select q.*from review_request q left join review_resolution r on r.request_id=q.id where r.request_id is null order by q.rowid')];save(S/'actual-pending-full.json',pending)
  for t in table['retains']:assert h.native(c,h.current(c,t['old_native']['object_id']))==t['old_native']
  actual=[dict(x)for x in c.execute('select *from review_resolution where operation_id=? order by rowid',(op['id'],))];assert [{'request':x['request_id'],'rationale':x['rationale']}for x in actual]==op['resolve'];save(S/'two-native-resolution-and-retains-proof.json',{'ordered_resolutions':actual,'full_retains':table['retains'],'changes_empty':True});assert sha(source)==pin['sha256']and sha(MAIN)==b['main']['sha256'];save(S/'actual-all50.json',h.all50(c));save(S/'result.json',{'state':h.state(c),'source479_unchanged':True,'main477_unchanged':True,'tworetains_exact':True,'tworesolution_order_exact':True,'elapsed_seconds':time.monotonic()-start});print(json.dumps(h.state(c)))
 except Exception as e:save(S/'failure-preserved.json',{'error':str(e),'traceback':traceback.format_exc(),'elapsed_seconds':time.monotonic()-start});raise
if __name__=='__main__':main()
