import pathlib,json,hashlib,sqlite3,datetime
P=pathlib.Path(__file__).resolve().parent;B=P.parent;R=P.parents[2];ops=['C1047-metadata-operation-v1.json','C1047-native-source-operation-v2.json','C1047-current-consequences-operation-v2.json','C1047-individual-resolutions-operation-v1.json'];c=sqlite3.connect(P/'clone/c1047-final-v3.sqlite');c.row_factory=sqlite3.Row;ordered=[]
for i,n in enumerate(ops,278):
 p=P/n;actual=json.loads(c.execute('select request_json from operation_payload where sequence=?',(i,)).fetchone()[0]);expected=json.loads(p.read_text());assert actual==expected,(n,'journal payload');ordered.append({'sequence':i,'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'expected_before':{'journal_head':i-1,'pending':[0,8,8,48][i-278]},'expected_after':{'journal_head':i,'pending':[8,8,48,0][i-278]}})
files=[P/n for n in ops]+[P/'clone/c1047-final-v3.sqlite',P/'clone/research-pre.sqlite',P/'C1047-final-v3-all-native-consequence-table-v2.json',P/'C1047-initial49-complete-consequence-table-v2.json',P/'C1047-settled-individual-retain-table-v1.json',P/'C1047-final-v3-full-stage-check-v1.json',P/'C1047-final-v3-protected-invariants-v1.json',P/'C1047-final-v3-resolution-check-v1.json',P/'C1047-final-v3-pending48-full-release-input-v1.json',P/'C1047-mechanical-attempt-history-v1.json',B/'root-C1047-pre-source-lock-v1.json',B/'root-C1047-union-scope-lock-amendment-v2.json']
files += [P/f'C1047-final-v3-sequence-step-{i:02d}.json' for i in range(1,5)]+[P/f'C1047-final-v3-{cmd}-receipt-v2.json' for cmd in ['verify','verify-assets','verify-source']]
files += [B/'source-review'/n for n in ['C-1047-own-reading-v1.json','C-1047-source-amendment-v2.json','C-1047-union-own-reading-v3.json','C-1047-current-source-decisions-v1.json','C-1047-Astrid-current-decisions-v1.json','C-1047-media-extraction-current-decisions-v1.json','C-1047-current-copy-amendment-v4.json','C-1047-native-source-spec-v1.json','C-1047-native-source-wording-amendment-v2.json','C-1047-pending48-individual-dispositions-final-v2.json','C-1047-remaining19-individual-dispositions-v2.json','C-1047-initial49-final-retains-v2.json','G001-closure-current277-and-C1047-union-v4.json']]
for p in files:assert p.is_file(),p
out={'task':'T-0778','state':'TECHNICALLY_VERIFIED_IMMUTABLE_PACKAGE_AWAITING_INDEPENDENT_SOURCE_PASS_AND_ROOT_CANONICAL_GATE','frozen_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'baseline':{'journal_head':277,'pending':0},'reviewed_stage':{'database':str((P/'clone/c1047-final-v3.sqlite').relative_to(R)),'journal_head':281,'pending':0},'ordered_operations':ordered,'files':[{'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()} for p in files],'metrics':{'native_objects':36,'new_objects':14,'revised_existing_objects':22,'version_events':36,'bounded_adoptions':4,'new_records':1,'new_transcriptions':3,'new_source_audits':3,'new_unlinked_mentions':3,'individual_dependency_resolutions':48,'initial49_dispositions':{'revise':15,'retain':34},'source_rows':7,'enumerated_units':126,'initial_units_preserved':72,'additional_units':54,'full_payload_matches':36,'untouched_current_revisions':44158,'owner_confirmed_retained':42},'scope':'C1047 three separate own groups plus approved current semantic consequences; no new identity/person/gate decisions. G001 closure assessment separate, root alone declares task acceptance.','canonical_not_written':True};f=P/'C1047-final-package-freeze-v1.json';assert not f.exists();f.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print('freeze',hashlib.sha256(f.read_bytes()).hexdigest(),len(files),'bindings')
