import pathlib,json,sqlite3,hashlib,subprocess,datetime,time,shutil
R=pathlib.Path.cwd();D=R/'evaluations/T-0810/preparation';start=time.monotonic();h=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();c=sqlite3.connect('file:genealogy2/data/research.sqlite?mode=ro',uri=True);c.row_factory=sqlite3.Row;allfiles=subprocess.run(['rg','--files','-uuu'],capture_output=True,text=True,check=True).stdout.splitlines();items=[('C-0543','A0005181_00270','P-0253','AI10 p265 r13'),('C-0542','00205390_00090','P-0253','AIIa2 p388 r16'),('C-0939','00198500_00116','P-0253','Holm AIIa1 p211 r21 cols11/13/Värn, proposed root amendment only'),('C-0677','00205394_00087','P-0247','AIIa6 p389 Gertrud own row'),('C-0677','00205396_00087','P-0247','AIIa8 p388 Gertrud own row'),('C-0677','00205400_00019',None,'name register locator/provenance only, not new own-person reading')];out=[]
for citation,image,pid,scope in items:
 records=[dict(x)for x in c.execute('select r.* from record r join current_revision cr on cr.id=r.revision_id') if image in x['locator']];links=[];paths=set(p for p in allfiles if image in p and pathlib.Path(p).suffix.lower()in ['.jpg','.jpeg','.png','.tif','.tiff']);manifest=[]
 for rr in records:
  aset=[dict(x)for x in c.execute('select ra.*,a.sha256,a.bytes from record_asset ra left join asset a on a.path=ra.asset_path where revision_id=?order by ra.rowid',(rr['revision_id'],))];med=[dict(x)for x in c.execute('select rm.*,a.storage_path,a.sha256,a.bytes,a.original_name,a.provenance from record_media rm left join native_asset a on a.id=rm.asset_id where revision_id=?order by rm.rowid',(rr['revision_id'],))];links.append({'record':rr,'record_asset':aset,'record_media':med});paths.update(x['asset_path']for x in aset if pathlib.Path(x['asset_path']).suffix.lower() in ['.jpg','.jpeg','.png','.tif','.tiff']);paths.update(x['storage_path']for x in med)
 for a in c.execute('select *from native_asset'):
  if image in json.dumps(dict(a)):paths.add(a['storage_path'])
 for p in (R/'genealogy/media').glob('*'+image.split('_')[0]+'*manifest*.json'):
  try:m=json.load(open(p));canvases=m.get('items',[])or (m.get('sequences',[{}])[0].get('canvases',[]) if m.get('sequences') else []);matches=[x for x in canvases if image in json.dumps(x)];manifest.append({'path':str(p.relative_to(R)),'sha256':h(p),'exact_matching_canvas_metadata':matches})
  except (ValueError,KeyError):pass
 originals=[]
 for p in sorted(paths):
  f=R/p
  if not f.is_file():continue
  r=subprocess.run(['sips','-g','pixelWidth','-g','pixelHeight',str(f)],capture_output=True,text=True);originals.append({'path':p,'sha256':h(f),'bytes':f.stat().st_size,'dimension_metadata':r.stdout,'dimension_exit':r.returncode,'content_viewed':False})
 out.append({'citation':citation,'image_id':image,'person':pid,'proposed_reading_scope':scope,'current_record_asset_mapping':links,'local_original_metadata':originals,'existing_manifest_header_metadata':manifest,'local_copy_result':'local exact file metadata available' if originals else 'Ej återfunnet i kontrollerat omfång: repository filenames including ignored files, exact current record-asset links and registered native_asset locators. Not archival/person absence.','provider_version':'unknown','scope_authorization':'Proposed only; no images viewed/acquired, root adoption and dual exact scope gate pending.'})
p=D/'five-proposed-own-row-and-register-metadata-map-v1.json';p.write_text(json.dumps({'units':out,'images_opened':0,'new_acquisition':0,'elapsed_seconds':time.monotonic()-start,'metadata_only':True},ensure_ascii=False,indent=2)+'\n');prefix=D/'T-0231-before-source-adoption-full-prefix-v1.md';assert not prefix.exists();shutil.copyfile(R/'wotan/dev-log/T-0231.md',prefix);pp=D/'T-0231-prefix-preservation-pin-v1.json';pp.write_text(json.dumps({'source':'wotan/dev-log/T-0231.md','prefix_path':str(prefix.relative_to(R)),'sha256':h(prefix),'bytes':prefix.stat().st_size,'full_scope_AC_checkpoints_accepted_units_preserved':True,'no_adoption_performed':True,'T-0214_sole_executor_unchanged':True},indent=2)+'\n');print(h(p));print([(x['image_id'],len(x['local_original_metadata']))for x in out]);print('prefix',h(prefix))
