import pathlib,json,hashlib,subprocess,importlib.util,time
R=pathlib.Path.cwd();D=R/'evaluations/T-0810';P=D/'preparation';O=D/'originals';start=time.monotonic();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();main=R/'genealogy2/data/research.sqlite';before=sha(main);expected=json.load(open(D/'root-start-baseline-v1.json'));assert before==expected['main_sha256'];planfile=D/'primary-five-unit-source-necessity-plan-v1.json';plan=json.load(open(planfile));browserfile=O/'root-browser-exact-two-download-receipt-v1.json';browser={u['image_id']:u for u in json.load(open(browserfile))};metadata=json.load(open(P/'five-proposed-own-row-and-register-metadata-map-v1.json'));sp=importlib.util.spec_from_file_location('h',R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py');h=importlib.util.module_from_spec(sp);sp.loader.exec_module(h);c=h.conn(main);assert h.state(c)=={'journal_head':473,'pending':0};units=[];pins=[]
for u in plan['units']:
 image=u['image_id'];n=h.native(c,u['record_revision']);assert h.current(c,n['object_id'])==u['record_revision'];old=next(x for x in metadata['units']if x['image_id']==image);entry={**u,'full_current_basis_native':n,'provider_version':'unknown','image_content_read_by_Sol':False}
 if image in browser:
  receipt=browser[image];p=R/receipt['path'];assert sha(p)==receipt['sha256']and p.stat().st_size==receipt['bytes'];dims=receipt['expected_dimensions'];provenance=f"T-0810 {image}; {receipt['volume_visible']}, page {receipt['selected_page_visible']}; {receipt['download_ui_label']}; observed {receipt['downloaded_at_observed_utc']}; {receipt['method']} Provider version unknown; direct IIIF and own Referer 401 preserved. Exact browser receipt originals/root-browser-exact-two-download-receipt-v1.json. No source interpretation by mechanical staging."
  r=subprocess.run(['node','genealogy2/cli.mjs','stage-media',str(p),'--provenance',provenance],capture_output=True,text=True,check=True);stage=json.loads(r.stdout);assert stage['sha256']==receipt['sha256'];sf=O/(image+'-stage-media-receipt-v1.json');assert not sf.exists();sf.write_text(r.stdout);entry['root_browser_receipt']=receipt;entry['staging_receipt']=stage;pins.extend([sf,R/stage['storagePath']])
 else:
  asset=u['media_metadata'][0]['asset'];p=R/asset['path'];assert sha(p)==asset['sha256']and p.stat().st_size==asset['bytes'];m=next(x for x in old['local_original_metadata']if x['path']==asset['path']);dims=[int(z.split(':')[1])for z in m['dimension_metadata'].splitlines()if 'pixelWidth:'in z or'pixelHeight:'in z];entry['existing_registered_frozen_asset']=asset;entry['staging_receipt']=None
 r=subprocess.run(['sips','-g','pixelWidth','-g','pixelHeight',str(p)],capture_output=True,text=True,check=True);actual=[int(z.split(':')[1])for z in r.stdout.splitlines()if 'pixelWidth:'in z or'pixelHeight:'in z];assert actual==dims;entry.update({'original_path':str(p.relative_to(R)),'sha256':sha(p),'bytes':p.stat().st_size,'dimensions':actual,'dimension_metadata':r.stdout});units.append(entry);pins.append(p)
assert sha(main)==before;pinpaths=[planfile,D/'independent-five-unit-source-scope-gate-v1.json',D/'T0231-exact-atom-partition-v1.json',D/'T0231-before-adoption-v1.md',browserfile,P/'locked-current-input-manifest-v1.json',P/'five-proposed-own-row-and-register-metadata-map-v1.json',P/'baseline-state-v1.json',*pins];pinpaths+=[p for p in O.iterdir()if p.is_file()];files=[{'path':str(p.relative_to(R)),'sha256':sha(p)}for p in sorted(set(pinpaths))];lock={'task':'T-0810','state':h.state(c),'main_sha256_unchanged':before,'plan_pin':{'path':str(planfile.relative_to(R)),'sha256':sha(planfile)},'units':units,'files':files,'file_count':len(files),'source_images_read_by_Sol':0,'new_native_registrations':0,'new_staged_media_files':2,'native_DB_apply':False,'elapsed_seconds':time.monotonic()-start,'qualification':'Actual full copies locked before both own source readings. Three existing Erik legacy assets reused unchanged; exactly two Gertrud contentfiles staged, native registration deferred to source-approved operation. Register19 and other images excluded.'};out=P/'actual-five-media-input-lock-v1.json';assert not out.exists();out.write_text(json.dumps(lock,ensure_ascii=False,indent=2)+'\n');print(sha(out));print('pins',len(files),'main unchanged',sha(main))
