import pathlib,json,importlib.util,hashlib
R=pathlib.Path.cwd();P=R/'evaluations/T-0810/preparation';s=importlib.util.spec_from_file_location('h',R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py');h=importlib.util.module_from_spec(s);s.loader.exec_module(h);c=h.conn(R/'genealogy2/data/research.sqlite');lock=json.load(open(P/'actual-five-media-input-lock-v1.json'));spec=json.load(open(R/'evaluations/T-0810/primary-source-adoption-spec-v1.json'));templates=[]
for u in lock['units']:
 if not u['staging_receipt']:continue
 n=u['full_current_basis_native'];a=h.api(n);a['expectedVersion']=n['version'];a['media'].append({'id':u['staging_receipt']['id'],'region':'helbild'});templates.append({'unit':u['unit_id']if 'unit_id'in u else u.get('id'),'full_old_native':n,'template_existing_record_with_media_only':a,'top_level_operation_media_receipt':u['staging_receipt'],'qualification':'Template only; caveat and any other change await exact source spec. Existing arrays untouched, new media appended.'})
checks=[]
for o in spec['newObjects']:
 cols=[dict(x)for x in c.execute('pragma table_info('+o['kind']+')')];allowed=[x['name']for x in cols if x['name']!='revision_id'];required=[x['name']for x in cols if x['name']!='revision_id'and x['notnull']and x['dflt_value']is None];meta={'id','kind','disposition','rationale','caveat','origins','evidenceStatus','evidence','expectedVersion'};data={k:v for k,v in o.items()if k not in meta};missing=[k for k in required if data.get(k)is None];unexpected=[k for k in data if k not in allowed];checks.append({'id':o['id'],'kind':o['kind'],'schema_columns':cols,'required':required,'allowed':allowed,'missing':missing,'unexpected':unexpected,'api_template':{**{k:v for k,v in o.items()if k in meta},'data':data}})
assert all(not x['missing']and not x['unexpected']for x in checks)
out={'task':'T-0810','state':h.state(c),'record_templates':templates,'new_source_objects_schema_preflight':checks,'pass':True,'native_writes':0,'qualification':'Required/allowed data-field preflight and full metadata templates only; no operation materialization or source/evidence rebind decision.'};f=P/'source-api-templates-and-schema-preflight-v1.json';assert not f.exists();f.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(hashlib.sha256(f.read_bytes()).hexdigest())
