"""Immutable exact all-member draft package/order/consequence index; never apply."""
import json,copy,hashlib,sqlite3,datetime,ast
from pathlib import Path
B=Path('evaluations/T-0781');W=B/'implementation/complete-two-source-settled-draft-package-v2';assert not W.exists();W.mkdir()
def load(p):return json.loads(Path(p).read_text())
def pin(p):return {'path':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()}
def save(n,v):
 p=W/n;assert not p.exists();p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');return pin(p)
core=B/'implementation/C0049-core-and-C0067-P0098-drafts-v1';c67=B/'implementation/C0067-fullTR-audit-READ-draft-v1';big=B/'implementation/C0049-small14-copy104-C0067-clause22-drafts-v1';final=B/'implementation/final-five-and-thirteen-adoption-drafts-v1';birth=B/'implementation/birth52-53-settled-three-drafts-v1';src=B/'source-review'
core_spec=src/'two-settled-fullsource-TR-audit-and-four-wrapper-specifications-v1.json'
order=[(core/'01-C0049-record-own-full-source-scope-draft-operation-v1.json',core_spec),(core/'02-C0049-fullTR-draft-operation-v1.json',core_spec),(core/'03-C0049-full-audit-draft-operation-v2.json',core_spec),(core/'04-C0049-READ-source-scope-draft-operation-v1.json',core_spec),(core/'05-C0049-old-TR-source-scope-draft-operation-v2.json',core_spec),(c67/'01-C0067-new-TR-draft-operation-v1.json',core_spec),(c67/'02-C0067-new-audit-draft-operation-v2.json',core_spec),(c67/'03-C0067-READ-exact-prior-full-scope-draft-operation-v1.json',core_spec),(big/'01-C0049-small14-draft-operation-v1.json',src/'C0049-fourteen-small-native-field-consequence-specifications-v1.json'),(big/'02-C0049-current-copy104-draft-operation-v1.json',src/'C0049-finite-current-narrative-contract-path-key-theme-caveat-specifications-v1.json'),(B/'implementation/C0067-four-clause-draft-v1/C0067-four-exact-source-approved-clause-revisions-draft-operation-v1.json',src/'C0067-four-current-source-scope-clause-decisions-v1.json'),(core/'06-C0067-P0098-other-year-source-route-draft-operation-v1.json',src/'C0067-P0098-unread-other-year-source-route-clause-decision-v1.json'),(big/'03-C0067-current-witness-clause22-draft-operation-v1.json',src/'C0067-twentytwo-finite-witness-current-clause-decisions-v1.json'),(final/'01-two-source-final-direct-copy5-draft-operation-v1.json',src/'two-source-five-final-direct-semantic-copy-clause-decisions-v1.json'),(birth/'01-P0052-P0053-structured-birth-place-three-revisions-draft-operation-v1.json',src/'P0052-P0053-structured-birth-place-three-revision-and-one-retain-decisions-v1.json'),(final/'02-two-source-thirteen-bounded-adoptions-draft-operation-v1.json',src/'two-source-thirteen-individual-bounded-adoption-specifications-v1.json')]
scope={};prep=B/'prepare_bounded_consequence_inputs_v1.py';exec(compile(prep.read_text().split('assert not W.exists();')[0],str(prep),'exec'),scope);c=scope['conn'](scope['BASE']);native=scope['native'];defs=(B/'build_settled_core_and_PATH98_drafts_v2.py').read_text().split('assert W.exists();')[0];d={};exec(compile(defs,'definitions','exec'),d)
protected={x['object_id'] for x in load(B/'mechanical-current425-preparation-v1/complete-current-OWNER-identity-tree-life-protected-native-payloads-v1.json')['objects'].values()};members=[];tables=[];seen=set();versions={x['id'] for x in c.execute('select id from revision')};operationids=set();new=0
for no,(p,sp) in enumerate(order,1):
 op=load(p);s=load(sp);assert op['dependencyReviewVersion']==2 and 'resolve' not in op and op['id'] not in operationids;operationids.add(op['id']);targets=[]
 specs=[]
 for key in ['objects','revisions','new_objects']:
  for i,x in enumerate(s.get(key,[])):specs.append((x,'/'+key+'/'+str(i)))
 for i,a in enumerate(op['changes']):
  oid=a['id'];assert oid not in seen and oid not in protected;seen.add(oid);hits=[(x,ptr) for x,ptr in specs if x['object_id']==oid];assert len(hits)==1;decision,ptr=hits[0];expected=a['expectedVersion'];now=c.execute('select max(version) from revision where object_id=?',(oid,)).fetchone()[0];assert now==expected
  resulting=oid+'@'+str(1 if expected is None else expected+1);baseline=native(c,oid+'@'+str(expected)) if expected is not None else None
  if expected is None:
   new+=1;expected_source_API=copy.deepcopy(decision['new_entire_API'])
   if oid in ['AUDIT-T0781-C0049-fullpost','AUDIT-T0781-C0067-fullpost']:
    am=load(src/'two-full-audit-final-status-rationale-metadata-amendments-v1.json');ar=[x for x in am['objects'] if x['object_id']==oid];assert len(ar)==1 and expected_source_API==ar[0]['entire_prior_candidate_API'] and expected_source_API['rationale']==ar[0]['old'];expected_source_API['rationale']=ar[0]['new']
   assert a==expected_source_API;oldAPI=None
  else:oldAPI=d['api'](baseline)
  dependency_rows=[]
  for e in a['evidence']:
   basis=e['object']+'@'+str(e['version']);assert basis in versions,('Producer missing/order',oid,basis);dependency_rows.append({'exact_API_edge':e,'basis_revision_id':basis,'available_before_target':True,'prior_baseline_or_earlier_producer':True})
  versions.add(resulting);payloadsha=hashlib.sha256(json.dumps(a,ensure_ascii=False,separators=(',',':')).encode()).hexdigest();target={'object_id':oid,'kind':a['kind'],'expectedVersion':expected,'resulting_revision_id':resulting,'change_index':i,'payload_sha256':payloadsha,'source_spec_pin':pin(sp),'source_decision_pointer':ptr,'ordered_evidence_availability':dependency_rows}
  if oid=='TR-bf8e09efe7e3e3c20156c785':target['explicit_same_version_metadata_amendment_pin']=pin(src/'C0049-old-TR-rationale-exact-metadata-amendment-v1.json')
  targets.append(target);tables.append({**target,'operation_index':no,'operation_pin':pin(p),'full_before_native':baseline,'full_before_API':oldAPI,'entire_exact_after_API':a,'exact_source_decision':decision,'source_metadata_amendment':load(src/'C0049-old-TR-rationale-exact-metadata-amendment-v1.json') if oid=='TR-bf8e09efe7e3e3c20156c785' else None})
 members.append({'index':no,**pin(p),'operation_id':op['id'],'changes':len(op['changes']),'targets':targets})
assert len(members)==16 and len(tables)==len(seen)==174 and new==17
membership=save('complete16-operation174-target-ordered-membership-v1.json',{'task':'T-0781','operations':members,'counts':{'operations':16,'targets':174,'new':17,'revisions':157},'superseded_candidates':[{'pin':pin(core/'05-C0049-old-TR-source-scope-draft-operation-v1.json'),'reason':'Same-version exact metadata amendment only; v2 selected once.'}],'protected42_intersection':[],'per_target_expected_current_version_and_evidence_producer_order':True,'stage':'UNRUN','canonical_apply':'UNRUN'})
table=save('complete174-individual-full-API-consequence-and-source-disposition-table-v1.json',{'rows':tables,'membership_pin':membership,'all_metadata_origins_assets_media_array_order_preserved_except_explicit_source_fields_edges':True,'mechanical_source_locator_not_newgrade':True})
sourcefiles=[src/n for n in ['C0049-primary-settled-source-extraction-v3.json','C0067-primary-settled-full-prior-reuse-source-scope-v1.json','C0049-eleven-record-and-one-birth-event-incoming-source-dispositions-v1.json','C0049-seven-mention-and-one-event-incoming-exact-source-dispositions-v1.json','C0049-finite-individual-semantic-amend-and-retain-index-v1.json','C0067-finite-individual-semantic-amend-and-retain-index-v1.json']]
proposal=save('complete-two-source-draft-package-proposal-v1.json',{'task':'T-0781','membership_pin':membership,'full_individual_consequence_table_pin':table,'operations':members,'counts':{'operations':16,'targets':174,'new':17,'revisions':157},'source_scope_and_incoming_retains_indexes':[pin(p) for p in sourcefiles],'main425_pin':pin(scope['MAIN']),'baseline_pin':pin(scope['BASE']),'protected42_pin':pin(B/'mechanical-current425-preparation-v1/complete-current-OWNER-identity-tree-life-protected-native-payloads-v1.json'),'initial_oldTR_candidate_preserved_and_excluded':True,'read_only_preparation_complete':True,'two_audit_exact_metadata_amendment_pin':pin(src/'two-full-audit-final-status-rationale-metadata-amendments-v1.json'),'prior_package_preserved_pin':pin(B/'implementation/complete-two-source-settled-draft-package-v1/complete-two-source-draft-package-proposal-v1.json'),'global_primary_exact_package_gate':'PENDING','global_independent_exact_pre_stage_gate':'PENDING','root_stage_authorization':'NOT_GIVEN','stage':'UNRUN','canonical_apply':'UNRUN'})
assert pin(scope['MAIN'])['sha256']=='efea4dfa8feec3f2f5bff8167792b01513ebb5689d9d2ec5278983a23ca208b3';c.close();print(json.dumps({'proposal_pin':proposal,'membership_pin':membership,'consequence_table_pin':table,'counts':{'operations':16,'targets':174,'new':17,'revisions':157}},indent=2))
