"""Exact source-approved17 draft only; no CLI/subprocess/runtime write code path."""
import json,copy,hashlib,sqlite3
from pathlib import Path
B=Path('evaluations/T-0781');W=B/'implementation/exact17-resolution-and-final17-member-draft-v1';assert not W.exists();W.mkdir()
def load(p):return json.loads(Path(p).read_text())
def pin(p):return {'path':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()}
def readpin(p):assert pin(Path(p['path']))=={'path':p['path'],'sha256':p['sha256']};return load(p['path'])
def save(n,v):p=W/n;assert not p.exists();p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');return pin(p)
def ptr(x,p):
 for k in p.strip('/').split('/') if p else []:k=k.replace('~1','/').replace('~0','~');x=x[int(k)] if isinstance(x,list) else x[k]
 return x
sp=B/'source-review/actual17-individual-primary-source-consequence-decisions-v1.json';assert pin(sp)['sha256']=='0905d65364b6b80fed7f012f969a6a2b904184231dfabc4c38cc6f7cc6e026e5';s=load(sp);gp=B/'source-review/actual17-complete-primary-pre-resolution-source-gate-v1.json';assert pin(gp)['sha256']=='47729b431c584b996b5920c1c094fa1d5b0bbec9947c305b2a8a4a222df82ecc';g=load(gp);assert g['all_actual_requests_source_approved'] is True and not g['source_questions_open'];assert g['individual_decisions_pin']==pin(sp)
assert s['runtime_resolution_apply_authorized'] is False and s['canonical_apply_authorized'] is False
stage=Path(s['stage_DB_pin']['path']);assert pin(stage)==s['stage_DB_pin'];c=sqlite3.connect(stage.resolve().as_uri()+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;actual=[dict(r) for r in c.execute('select * from pending_review order by id')];assert len(actual)==17 and c.execute('select max(sequence) from operation_payload').fetchone()[0]==441
input=readpin(s['actual_request_input_pin']);native=readpin(s['full_native_context_pin'])['objects'];ownp=B/'independent-review/actual17-independent-own-source-consequence-freeze-v1.json';own=load(ownp);ownrows={r['request_id']:r for r in own['rows']};rows=[];instructions=[];cache={}
for i,r in enumerate(s['rows']):
 q=r['actual_request'];assert q==actual[i]==input['requests'][i]['actual_request'];assert r['source_approved'] is True;instruction=r['resolution_instruction'];assert set(instruction)=={'request','rationale'} and instruction['request']==r['request_id']==q['id'] and instruction['rationale'].strip();assert instruction==g['approved_individual_resolution_instructions'][i]['resolution_instruction'];assert ownrows[q['id']]['actual_request']==q and ownrows[q['id']]['retained_current_revision_id']==r['retained_current_revision_id']
 cur=c.execute('select id from revision where object_id=? order by version desc limit 1',(native[r['retained_current_revision_id']]['object_id'],)).fetchone()[0];assert cur==r['retained_current_revision_id'];assert native[cur]['evidence']==r['current_ordered_evidence_retained']
 for k,pointer in r['full_native_context_pointers'].items():assert ptr({'objects':native},pointer)['id'] in native
 for e in r['exact_historical_dependency_path']:assert e in native[e['revision_id']]['evidence']
 for pp in r['support_review_pins']:
  key=(pp['path'],pp['sha256'])
  if key not in cache:cache[key]=readpin(pp)
 instructions.append(copy.deepcopy(instruction));rows.append({'request_id':q['id'],'actual_request':q,'source_decision_pin':pin(sp),'source_row_pointer':'/rows/'+str(i),'source_instruction_pointer':'/rows/'+str(i)+'/resolution_instruction','resolution_API_pointer':'/resolve/'+str(i),'resolution_instruction':instruction,'retained_current_revision_id':cur,'individual_source_scope':r['individual_source_scope'],'exact_historical_dependency_path':r['exact_historical_dependency_path'],'current_ordered_evidence_retained':r['current_ordered_evidence_retained'],'full_native_context_pointers':r['full_native_context_pointers'],'native_input_pin':s['full_native_context_pin'],'entire_source_decision':r,'independent_original_freeze_pin':pin(ownp),'independent_original_row_pointer':'/rows/'+str(next(j for j,x in enumerate(own['rows']) if x['request_id']==q['id'])),'independent_resolution_actual_API_approval':'PENDING','new_native_revision_or_rebind':False})
assert len(instructions)==len({x['request'] for x in instructions})==17 and [x['request'] for x in instructions]==g['approved_request_ids'];op={'id':'T-0781/actual17-individual-source-approved-resolutions-v1','actor':'codex','reason':'T-0781 AC3: sjutton individuellt källprövade faktiska beroendeomprövningar enligt '+str(sp)+' SHA'+pin(sp)['sha256']+'. Varje request/rationale följer exakt sitt avgjorda käll-, fält- och versionsomfång; inga nativefält eller evidenslänkar ändras.','dependencyReviewVersion':2,'changes':[],'resolve':instructions};op_pin=save('one-exact17-individual-resolution-only-draft-operation-v1.json',op)
priorp=B/'implementation/complete-two-source-settled-draft-package-v3/complete-two-source-draft-package-proposal-v1.json';prior=load(priorp);membership=readpin(prior['membership_pin']);members=copy.deepcopy(membership['operations'])
for m in members:assert pin(Path(m['path']))['sha256']==m['sha256']
member={'index':17,**op_pin,'operation_id':op['id'],'changes':0,'targets':[],'resolutions':17,'ordered_request_ids':[x['request'] for x in instructions]};members.append(member);newmembership={'task':'T-0781','operations':members,'counts':{'operations':17,'native_targets':174,'native_operations':16,'new_native_objects':17,'native_revisions':157,'resolution_only_operations':1,'individually_source_approved_resolutions':17},'first16_entire_ordered_members_equal_reviewed_prefix':members[:16]==membership['operations'],'prefix16_proposal_pin':pin(priorp),'prefix16_membership_pin':prior['membership_pin'],'source17_gate_pin':pin(gp),'stage_resolution_apply':'UNRUN','canonical_apply':'UNRUN'};mp=save('complete17-operation174-native17-individual-resolution-ordered-membership-v1.json',newmembership);tp=save('all17-individual-actual-request-source-instruction-current-scope-and-full-context-consequence-table-v1.json',{'membership_pin':mp,'resolution_operation_pin':op_pin,'source17_decisions_pin':pin(sp),'source17_gate_pin':pin(gp),'reviewed_native174_consequence_table_pin':prior['full_individual_consequence_table_pin'],'rows':rows,'no_blanketretains_or_rebinds':True,'exact17actualpendingcoverage':True});proposal=save('final17-operation-two-source174-plus-individual17-resolution-draft-proposal-v1.json',{'task':'T-0781','operations':members,'membership_pin':mp,'native174_consequence_table_pin':prior['full_individual_consequence_table_pin'],'individual17_resolution_consequence_table_pin':tp,'resolution_operation_pin':op_pin,'source17_gate_pin':pin(gp),'stage_before_pin':s['stage_DB_pin'],'actual_stage_before':{'journal_head':441,'pending':17},'expected_stage_after_resolution':{'journal_head':442,'pending':0},'independent_exact_resolution_API_and_fullpackage_gate':'PENDING','primary_exact_final17_package_gate':'PENDING','same_stage_resolution_apply_authorized':False,'canonical_apply_authorized':False,'no_changes_to_prior174_candidate_bytes':True});assert pin(stage)==s['stage_DB_pin'];c.close();print(json.dumps({'resolution_operation_pin':op_pin,'membership_pin':mp,'request_consequence_table_pin':tp,'proposal_pin':proposal},indent=2))
