import json,copy,hashlib
from pathlib import Path
D=Path(__file__).parent
v=json.loads((D/'primary-own-90-dispositions-and-exact-changes-v1.json').read_text())
n=json.loads((D.parent/'preparation/complete-current-history-support-native.json').read_text())['objects']
cs={c['target_revision']:c for c in v['exact_changes']}
def text(r,f='body'):
 return next((x['new'] for x in cs.get(r,{}).get('field_changes',[]) if x['field']==f),n[r]['data'].get(f))
def setv(r,f,s,sup,why):
 if r not in cs: cs[r]=dict(target_revision=r,expectedVersion=n[r]['version'],kind=n[r]['kind'],field_changes=[],supporting_versions=[],reason=why)
 c=cs[r];c['field_changes']=[x for x in c['field_changes'] if x['field']!=f]+[dict(field=f,old=n[r]['data'].get(f),new=s)]
 c['supporting_versions']=list(dict.fromkeys(c['supporting_versions']+sup));c['reason']+=' '+why if why not in c['reason'] else ''
def sub(r,a,b,sup,why,f='body'):
 s=text(r,f);assert s.count(a)==1,(r,a);setv(r,f,s.replace(a,b),sup,why)
# Stronger maternal and explicit age support.
sibs=['O-P-0005-sibling-P-0303@1','O-P-0005-sibling-P-0304@1']
cs['THEME-P-0005-REL@1']['supporting_versions']+=sibs+['REL-parent-P-0007-P-0005@1']
sub('THEME-P-0005-REL@1','Registerroller hålls skilda','Moderns redan CORROBORATED relation stöds av senare accepterat Flenunderlag; h.f. ensam visar inte moderskap. Registerroller hålls skilda',['REL-parent-P-0007-P-0005@1'],'Starkare befintligt moderskapsstöd återbrukas.')
setv('CONTRACT-P-0005-PK-04@1','body','PK-04 STYRKT inom personbundet integritetsminimerat omfång. Tolv bevarade relationsankare med belägg, tid och P-id återbrukas. Fadern och modern har redan CORROBORATED relationer; moderns starkare Flenunderlag väger utöver Södertäljeregistrets h.f.-roll, som ensam inte fastställer moderskap. De två namngivna systrarna P-0303 (1940, Flen) och P-0304 (1945, Södertälje) är yngre än Jan-Christer (1938); krönikans tre barn inkluderar honom. Detta gör ingen ny helsyskoninferens eller uttömmande utsaga om alla möjliga syskon. Halvfaster- och farföräldraleden behåller sin tidigare källkontext. Inga nya relationskanter eller privata nätverk tillförs.',sibs+['REL-parent-P-0007-P-0005@1','R-31ddf6090af32ffa30920ac9@1'],'Aktuellt starkare moderskapsstöd konsolideras; gammal kropp sade två systrar, inte äldre.')
a='Moderskapet är däremot\nen hushållsslutsats — Maj Amalia står som `h.f.`, inte som barnets uppgivna\nmor — och A-0238 står därför kvar som `TRANSCRIBED` med registret som\nstödjande, inte höjande, belägg.'
sub('RESEARCH-P-0005-9d76f0343410@2',a,'Maj Amalias `h.f.` i Södertäljeregistret visar ensam inte moderskap. Den senare accepterade Flenkontrollen i T-0150 ger dock starkare stöd, och den aktuella relationen REL-parent-P-0007-P-0005@1 är redan CORROBORATED. Den äldre uppgiften att A-0238 fortfarande är TRANSCRIBED är därmed överspelad; ingen relation uppgraderas i T-0790.',['REL-parent-P-0007-P-0005@1'],'Starkare befintlig relation ersätter gammal statusetikett, h.f.-reservationen består.')
# Evy: accepted daughter anchor belongs in minimal synthesis.
es=['E-birth-P-0210@1','REL-parent-P-0211-P-0210@1']
for r,f in [('BIO-P-0211@2','markdown'),('CONTRACT-P-0211-PK-03@2','body'),('CONTRACT-P-0211-PK-04@2','body'),('CONTRACT-P-0211-PK-10@2','body')]:
 setv(r,f,text(r,f)+'\n\nDottern Kristinas födelse 1964 återbrukas tillsammans med den accepterade mor–dotterrelationen. Ingen födelseort, bostad för modern eller senare levandestatus härleds ur detta ankare.',es,'Redan accepterat dotterankare1964 konsolideras utan ny privat detaljinsamling.')
setv('THEME-P-0211-SYN@1','body','Den integritetsminimerade berättelsen sammanhåller födelsen 1938 med åtskillnad mellan nedkomstort och föräldrahem, accepterat vigselår1962, dotterns födelse1964 samt efterlevande maka i barnens minnesord2017. Relationsbryggan och respektive källled bevaras. Luckorna fylls inte med bostad, yrke eller trosliv, och efterlevandeställningen2017 fastställer ingen nutida levandestatus.',es+['O-P-0211-C0901-spouse@1','AUDIT-T0674-C0240@2'],'Minimal sammanfattning omfattar alla redan relevanta accepterade tidsankare.')
# Gunnar chronology, residence, dated baptism and bounded source routing.
sub('BIO-P-0212@5','Om åren mellan 1951 och 1962 vet projektet ingenting belagt. Därefter tecknar minnesorden en sammanhängande linje: han utbildade sig till lärare, mötte sin blivande hustru Evy på Ibra radio i Stockholm och gifte sig 1962. Dottern Kristina föddes medan familjen ännu bodde i Stockholmstrakten, och omkring mitten av 1960-talet — enligt minnesorden 1967 — flyttade de till Floby,','För perioden1951–1962 saknas en daterad boende- och utbildningskedja. Barnens minnesord berättar att han utbildade sig till lärare och mötte sin blivande hustru Evy på Ibra radio i Stockholm; årtal för utbildningen och mötet saknas, och dessa händelser placeras inte efter1962. Vigselåret är enligt samma minnesord1962. Ägaren placerar Flobyflytten i mitten av1960-talet efter dottern Kristinas födelse1964; minnesorden anger1967. Uppgifterna har olika precision och harmoniseras inte till en ny exakt dag eller en bevisad tidigare bostad. Familjens ursprungsort vid flytten och dotterns födelseort är inte angivna. De flyttade till Floby,',['F-P-0212-event_place-Floby@1','O-P-0212-C0905-family-move@1','O-P-0212-C0901-own@2','E-birth-P-0210@1'],'Tar bort ogrundad Stockholmstraktsbostad och felplacerad kronologi; mötesort blir inte bostad.',f='markdown')
sub('PATH-P-0212-KP-01@1','ger rapporterande församling och därmed familjens svenska hemvist 1933.','ger rapporterande församling; svensk hemvist eller fysisk hemresa1933 följer inte därav.',['AS-P-0240-registration-limits@1'],'Registrering hålls skild från fysisk hemvist.')
sub('PATH-P-0212-KP-01@1','avslutad. Engelbrekts egen födelse- och dopbok kan läsas som dublett, men eftersom barnet aldrig döptes i svenska kyrkan tillför den sannolikt inget namn; återaktiveras om Q-03 kräver ett fjärde namnled.','Den prövade SCB-passagen är avslutad inom sitt dokumenterade omfång. Födelsepostens odöpt och den senare hushållsbokens icke döpt av svenska kyrkan är daterade noter, inte belägg för att dop aldrig skett. Engelbrekts egen bok och en eventuell senare dopnotis är inte lästa här; deras innehåll eller oberoende namnbevis kan inte förutsättas. Återaktivering kräver en konkret avgränsad dokumentär fråga under Q-03 och separat utförandemandat.',['F-P-0212-church_note-1933-1946@1'],'Daterad kyrkonot ersätter livslångt negativt dopantagande.')
sub('P-0212/Q-02@1','Uppgifter om en person som levde till 2017 finns i övrigt främst i icke-digitala myndighetsarkiv och hos familjen.','C0906:s katalogprov2026-09-06 avgränsar endast de faktiskt prövade serierna och sökningarna. Det fastställer inte att övriga livsuppgifter främst ligger i icke-digitala arkiv. T-0795 äger sex specificerade metadatafrågor för kvarstående routing, högsttvå ingångar perenhet och tolv totalt.',['F-P-0212-source_access-C0906@1'],'Avlägsnar även omgivande universell analogslutsats.')
sub('P-0212/Q-02@1','minnesordens 1967 mot ägarens `mitten av 60-talet` är en precisionsskillnad, inte en konflikt, eftersom intervallet rymmer årtalet.','minnesordens1967 och ägarens mitten av60-talet bevaras som olika precisa uppgifter; ett entydigt kalenderintervall konstrueras inte.',['F-P-0212-event_place-Floby@1'],'Harmoniserar inte vardaglig ungefärlig tidsuppgift.')
s=text('PATH-P-0212-KP-03@1'); start=s.index('- Bedömning och återaktivering:')
setv('PATH-P-0212-KP-03@1','body',s[:start]+'- Bedömning och återaktivering: befintliga familjeuppgifter återbrukas. T-0362 äger en avgränsad frågelista om Gunnars1951–1967, däribland vistelse, utbildning och vigselförsamling. Inga svar är mottagna genom denna korrigering, och inget obegränsat kontakt- eller privatarkivuppdrag följer. T-0034 gäller sina namngivna levande personer enligt senare PCD2026-09-09-029; det är inte ägare till Gunnars livsfråga.\n- Wotan: [T-0362](../../wotan/dev-log/T-0362.md); endast dess befintliga scope, ingen exekvering i T-0790.\n',['O-P-0212-C0905-family-move@1','O-P-0212-C0901-own@2'],'Exakt redan befintlig ägare ersätter EJ BESLUTAT och historiskt IDEA-läge.')
sub('PATH-P-0212-KP-04@1','redan fullutvunnen med reserverad kolumn9','redan accepterat granskad i hela det relevanta postomfånget med prövad men fortsatt olöst kolumn9',[],'Fullpostomfång innebär inte att alla tecken är lösta.')
sub('PATH-P-0212-KP-05@1','tre LIBRIS-sökningar','de angivna LIBRIS-sökningarna',[],'Ingen osäker sökräkning införs.')
sub('PATH-P-0212-KP-05@1','En separat ändlig metadata-/åtkomstprövning behöver faktisk Wotanägare före utförande; T0790 öppnar inga nya källor.','[T-0795](../../wotan/dev-log/T-0795.md) äger de sex uttryckliga metadatafrågorna U1–U6, högst två ingångar perenhet och tolv totalt; U6 har högst två totalt över sina tre organisationer. Ingen personpostläsning ingår. Uppdraget är registrerat för senare beslut, inte utfört; T-0790 öppnar inga nya källor.',[],'Registrerad exakt begränsad restägare T0795.')
setv('CONTRACT-P-0212-PK-06@1','outcome','STYRKT',[],'PK06 kräver individuell temabedömning, inte att samtliga källvägar redan utförts.')
setv('CONTRACT-P-0212-PK-06@1','body','PK-06 STYRKT: alla tio teman är individuellt prövade med personbundet underlag, kunskapsluckor och möjliga avgränsade källvägar. ID är GENOMGÅNGET; ARB, BO, EKO, HAL, MIL, PER, REL, SAM och SYN är ÖPPET. Nio öppna teman är inte i sig ett PK06-fel. EKO/MIL återöppnas därför att C0906 endast bär sitt daterade lokala prov. Bedömd tematäckning är inte utfört framtida källarbete eller godkänd full livsbild: PK03, PK04 och PK08 förblir EJ STYRKT. T0359/T0362/T0795 äger sina exakta återstående omfång.',[],'Amendment efter normativ avstämning med oberoende granskare; v1bevarad.')
# Structured source-reading status only, no glyph resolution.
r='O-P-0212-C0903-child@2'; raw=json.loads(n[r]['data']['value_json']);raw['column9']='Visuellt prövad i accepterad T0675-fullpostgranskning men fortsatt olöst: FIRST föreslog Obs! B.; SECOND Olof B. Ingen säker ordform eller händelse fastställs.'
setv(r,'value_json',json.dumps(raw,ensure_ascii=False,separators=(',',':')),['AUDIT-T0675-HOOK-4@1','F-P-0212-source_reference-Lidingo1951@2'],'Endast kolumn9:s prövningsstatus rättas från oläst till prövad men olöst; övriga råfält bevaras.')
for p in ['P-0004','P-0210','P-0212']:
 r='ASSESSMENT-'+p+'@1';setv(r,'outcome','`UNDERKÄND`',[],'Metadataamendment: legacy Kontraktsgranskning har ursprungligt helkontraktsomfång och UNDERKÄND i kroppen. Befintlig identitetsgrind/trädverkan ändras inte; detta är ingen ny native livsgranskning.')
# Literal amended caveats retain historical content and explicitly supersede stale status.
for c in cs.values():
 c['mechanical_rule']='Settled field decisions. Preserve every unspecified field, original rationale, disposition, evidence status, origins and existing evidence. Append exact amendment_caveat. Materialize full literal API and individually review evidence rebindings before approval; no runtime inference.'
 c['amendment_caveat']='T-0790 2026-10-06: '+c['reason']+' Endast accepterat återbruk; ingen ny original-, katalog- eller nätläsning. Äldre motsägande formulering inom exakt rättat fält är överspelad, men råreservationer och historiska granskningsomfång består.'
# exact planned new heads, no implicit runtime binding.
heads={c['target_revision'].rsplit('@',1)[0]:c['expectedVersion']+1 for c in cs.values()}
def final(r):
 o,ver=r.rsplit('@',1);return o+'@'+str(heads.get(o,int(ver)))
for row in v['individual_table']:
 old=row['object_id']+'@'+str(row['old_version']);c=cs.get(old)
 row['disposition']='revise' if c else 'retain';row['final_revision']=final(old)
 row['new_outcome']=next((f['new'] for f in c['field_changes'] if f['field']=='outcome'),row['old_outcome']) if c else row['old_outcome']
 if c:row['individual_rationale']+=' '+c['reason']
 if row['person']=='P-0212' and row['item']=='PK-06':row['individual_rationale']='Alla tio teman har individuellt bedömda belägg, luckor och möjliga vägar; STYRKT enligt PK06-definitionen. Öppna teman innebär inte automatiskt PK06-fel. V1:s motsatta slutsats återtas uttryckligen; PK03/04/08 håller livsbilden failed.'
 if row['person']=='P-0211' and row['item'] in ['SYN','PK-03','PK-04','PK-10']:row['individual_rationale']+=' Även dotterns accepterade födelse1964 konsolideras utan födelseort eller bostadsinferens.'
 row['supporting_versions']=list(dict.fromkeys(row['supporting_versions']+(c['supporting_versions'] if c else [])))
 row['final_supporting_versions']=list(dict.fromkeys(map(final,row['supporting_versions'])))
for rv in v['six_life_reviews']:
 p=rv['data']['subject_id']; rows=[r for r in v['individual_table'] if r['person']==p]
 rv['expectedVersion']=None; rv['data']['body']='T-0790 individuell livsbildsgranskning 2026-10-06; endast accepterat befintligt underlag.\n\n'+ '\n'.join(r['item']+' — '+r['new_outcome']+'. '+r['individual_rationale'] for r in rows)+'\n\nSlututfall: '+rv['data']['outcome']+'. '
 rv['data']['body']+=('PCD2026-09-09-029:s exakta obligatoriska K09-passage för denna person återstår hos T-0034; dataminimering gör den inte utförd.' if p in ['P-0004','P-0210','P-0005','P-0006'] else 'Individuellt minimerat omfång är sakligt fullgjort med accepterade1938/1962/1964/2017-ankare; Evy ingår inte i PCD029:s obligatoriska sjupersonspassage. Prövade råreservationer kvarstår, och ingen nutida levandestatus fastställs.' if p=='P-0211' else 'PK03/04/08 förblir underkända för de specificerade materiella livs-, relations- och åtkomstluckorna. T-0359, T-0362 och T-0795 äger exakt sina befintliga begränsade frågor; inga nya källor har öppnats.')
 rv['data']['body']+=' Återöppna berörda bedömningar vid relevant ny accepterad evidens, verifierad specifik åtkomstgräns eller uttrycklig ändring av personomfånget. Identitet, trädverkan, OWNER_CONFIRMED och accepterade relationer består. Legacy helkontraktsgranskning behåller historiskt omfång; task DONE är inte personpass.'
 rv['caveat']='Ingen ny original-, katalog- eller nätläsning. Personbundna tids-/plats-/fältgränser, gemensamma uppgiftsled och prövade råreservationer består. Denna granskning gäller endast livsbildsnivån.'
 rv['evidence_versions']=list(dict.fromkeys(final(x) for x in rv['evidence_versions']+sum((r['supporting_versions'] for r in rows),[])))
 rv['evidence']=[dict(object=x.rsplit('@',1)[0],version=int(x.rsplit('@',1)[1]),role='supports',note='T0790 individuell livsbildsprövning; exakt aktuell accepterad eller i detta paket beslutad revision, ingen ny oberoende källröst.') for x in rv.pop('evidence_versions')]
 rv['evidenceStatus']=rv.pop('evidence_status');rv['origins']=[]
v['exact_changes']=list(cs.values());v['freeze']='Settled comparative amendment v2; v1 independently frozen and preserved.'
v['bounded_followup']['proposed_owner']='T-0795 registered metadata-only owner, not executed'
v['implementation_gate']='Settled literal field decisions and six full new-review candidates. Sol materializes complete existing-object APIs preserving metadata/evidence/origins; primary and independent must approve exact resulting API/table hashes before stage/apply.'
v['comparison']={'independent_findings_sha256':'785abecce3ab92c0de34ef4a3fc6022b530ac8bfb22f4eef8003bceda9ac5b8c','all_ten_findings':'accepted with bounded amendments','PK06_amendment':'Both source reviewers agree assessed thematic coverage, not completion of every path, governs PK06. P0212 STYRKT; life failed remains.','legacy_scope':'Only outcome metadata reflects original full-contract UNDERKÄND; native identity/tree remain protected.'}
assert len(v['individual_table'])==90
assert all(s in n for c in cs.values() for s in c['supporting_versions'])
p=D/'settled-90-dispositions-and-literal-field-decisions-v2.json';p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');print(len(cs),hashlib.sha256(p.read_bytes()).hexdigest())
