import json,hashlib
from pathlib import Path
D=Path(__file__).parent;p=D.parent/'preparation/reviewed-stage-v1/actual-requests-full-context.json';b=p.read_bytes();assert hashlib.sha256(b).hexdigest()=='98a8337c74663e0b8b5acb95ef6bb0210ba3d91628fcc4c8d0a636f239b7ff37';x=json.loads(b);n=x['objects']
judgments={
'EP-E-birth-P-0212-P-0212-principal@1':('P0212:s roll principal i E-birth-P0212 består. Namnlösa SCB-postens datum1933-03-26 och namngivna föräldrar, hushållsradens samma datum samt C0268:s familjeidentifiering bär den redan accepterade person–händelsekopplingen. Ny kolumn9-status ändrar inget identifieringsfält. Registrerad Engelbrektförsamling får fortsatt inte bli förlossningsadress; CORROBORATED och de historiska evidencekanterna behålls.', ['O-P-0212-C0902-child@1','O-P-0212-C0268-own@1','E-birth-P-0212@1']),
'F-P-0212-name_form-source_comparison@2':('Namnjämförelsens CONFLICT gäller dokumentär ordningsavvikelse, inte identiteten eller OWNER-namnet Gunnar Ivar Emanuel Höök. C0903:s raw Ivar Gunnar Emanuel och index-/gravformerna förändras inte i@3. Kolumn9 saknar fortfarande säker ordform och är inget nytt namnbevis; inga majoritets- eller oberoendeslutsatser tillkommer. preferred_display/owner, order_conflict_unresolved och church_grave_independence_established=false består liksom hela@2-caveat.', ['F-P-0212-name-owner-confirmed@1','O-P-0212-C0268-own@1','O-P-0212-C0236-own@1','O-P-0212-C0904-own@1']),
'F-P-0212-source_reference-Lidingo1951@2':('Detta faktum anger redan visuellt prövad men olöst kolumn9, own_column9_unread=false, FIRST Obs!B./SECOND OlofB. och ingen säker ort/handling. Observation@3 bringar den lägre strukturkopian i överensstämmelse med denna redan accepterade kvalificering. Egen hänvisning1719/1951, from_folio1341, number105_meaning=null och next_book_read=false ändras inte. Behåll hela@2 och historiska evidencekanter; ingen cirkulär ny ombindning till observation@3 behövs.', ['AUDIT-T0675-HOOK-4@1','F-P-0240-household_membership-Lidingo-family@1']),
'E-birth-P-0212@1':('Händelsens exakta datum1933-03-26 är bevarat i C0902:s födelsepost, C0903:s egen rad och C0268:s familjeuppgift. Endast kolumn9:s lässtatus ändras; födelsedatumet och event_type birth förblir identiska. place_id=null och place_role recorded_birth_parish förhindrar påhittad adress. CORROBORATED händelse behålls utan ny källa, omdatering eller ombindning.', ['O-P-0212-C0902-child@1','O-P-0212-C0268-own@1']),
'EP-E-registered_arrival-Hook-family-Lidingo1946-P-0212-principal@1':('Gunnars principal-roll i familjens registrerade inflyttning1946-09-13 stöds av egen namngiven barnrad och F-P0240-household_membership som inkluderar honom bland fyra barn. Moderns registrerade ankomsthändelse och barnets mention_id är oförändrade. En fortsatt olöst kolumn9 tillför ingen ny flytt eller adress, och Kyrkovägen10 förblir odaterad. TRANSCRIBED participation och samtliga strukturreferenser/kanter behålls.', ['F-P-0240-household_membership-Lidingo-family@1','E-registered_arrival-Hook-family-Lidingo1946@1','M-P-0212-C0903-child@1']),
'F-P-0212-event_place-birth@1':('Den accepterade uppgiften är register_parish Engelbrekt och stadsuppgift Stockholm, med physical_birth_address=null. C0902:s registreringskontext och C0903:s oförändrade Engelbrekt St. bär just denna nivå. Kolumn9:s osäkerhet löser inte och motsäger inte en förlossningsort; varken Lidingö, utlandet, Allmänna BB eller fysisk hemresa tillförs. CORROBORATED faktum och dess uttryckliga caveat består.', ['O-P-0212-C0902-child@1','E-birth-P-0212@1']),
'F-P-0212-rejected_claim-foreign_birth@1':('Avvisandet av äldre sannolik utlandsfödelse består. Faderns1931registrerade utresa är ingen fysisk resegaranti för modern/barnet1933; C0887:s nio uttryckliga sökomfång är lokala noll och följs av positiv Engelbrektregistrering. Oavgjord kolumn9 på1946–1951-raden ger inget nytt utlandsfödelsebelägg. withdrawn=true, negative_searches_remain_bounded=true och REJECTED behålls; ingen fysisk födelseadress fastställs.', ['SEARCH-Hook-C0887-birth-marriage1933@1','E-registered_departure-P-0239@1','F-P-0212-event_place-birth@1']),
'F-P-0212-church_note-1933-1946@1':('Faktumet skiljer redan 1933postens Odöpt gossebarn från1946–1951-bokens icke döpt av sv. kyrkan och har lifetime_baptism_excluded=false. Dessa kyrkofält förändras inte i observation@3; den visuellt prövade men olösta kolumn9 kan inte certifiera en dophandling eller livslång dopfrånvaro. TRANSCRIBED, de daterade begränsningarna och historiska stödversionerna behålls.', ['O-P-0212-C0902-child@1']),
'F-P-0212-rejected_claim-A1479@2':('Avvisandet gäller den gamla sammansatta utsagan med Lidingö som födelseort. Birth_date_accepted=true för1933-03-26 består, medan whole_claim_rejected=true och den dokumentära namnordningsfrågan hålls skilda från OWNER_CONFIRMED Gunnar Ivar Emanuel Höök. C0236:s Lidingö fs B är en olöst källhänvisning; den kvarolösta kolumn9 kan inte göra den till accepterad födelseförsamling. Varken REJECTED, rånamnet, aktuellt ägarnamn eller caveat ändras.', ['F-P-0212-event_place-birth@1','F-P-0212-name_form-source_comparison@2','F-P-0212-name-owner-confirmed@1','O-P-0212-C0236-own@1'])}
rows=[]
for r in x['requests']:
 a=r['affected_revision_id'];why,sup=judgments[a];assert all(z in n for z in sup)
 rows.append(dict(request_id=r['id'],affected_revision=a,changed_revision=r['changed_revision_id'],disposition='retain exact current native; resolve request only',rationale=why,evidence_reviewed=['O-P-0212-C0903-child@1','O-P-0212-C0903-child@2','O-P-0212-C0903-child@3']+sup,mutation_required=False,evidence_rebinding='none; existing historical bindings remain exactly as stored',literal_resolution=dict(request=r['id'],rationale='T-0790 individuell faktisk beroendegranskning: '+why)))
a=json.loads(n['O-P-0212-C0903-child@2']['data']['value_json']);b=json.loads(n['O-P-0212-C0903-child@3']['data']['value_json']);assert [k for k in a if a[k]!=b[k]]==['column9']
out=dict(task='T-0790',role='primary source/evidence',freeze='Own individual nine-request judgment before seeing independent dependency dispositions',independent_dependency_decisions_seen=False,input_sha256=hashlib.sha256(p.read_bytes()).hexdigest(),actual_state=x['actual_state'],changed_data_scope='Only value_json.column9 differs from observation@2 to@3; raw literal/birth/church/name/folio fields unchanged. Audit and caveat retain partial/unresolved meaning.',individual_decisions=rows,literal_resolutions=[r['literal_resolution'] for r in rows],new_native_mutations=[],canonical_or_stage_actions=False,source_access=0,gate='Own source disposition only; compare separately frozen independent decisions, then approve exact resolution operation and final stage hashes.')
f=D/'actual-nine-dependencies-own-freeze-v1.json';f.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(hashlib.sha256(f.read_bytes()).hexdigest())
