import json, hashlib
from pathlib import Path

root=Path(__file__).parent
prep=root.parent/'preparation'
native=json.loads((prep/'complete-current-history-support-native.json').read_text())['objects']
pids=['P-0004','P-0210','P-0005','P-0006','P-0211','P-0212']
people={p:json.loads((prep/(p+'-person.json')).read_text()) for p in pids}
changes=[]

def change(rev, fields, support, reason):
    old=native[rev]
    changes.append(dict(target_revision=rev,expectedVersion=old['version'],kind=old['kind'],field_changes=[dict(field=f,old=old['data'].get(f),new=v) for f,v in fields.items()],supporting_versions=support,reason=reason,mechanical_rule='Preserve every unmentioned native data field, disposition, evidence_status, origins, existing evidence and caveat. Append the source rationale as a dated T0790 caveat; add listed support version bindings. A zero/multiple replacement or stale version returns to Astra.'))

def replace(rev, field, old, new, support, reason):
    s=native[rev]['data'][field]
    assert s.count(old)==1,(rev,old,s.count(old))
    change(rev,{field:s.replace(old,new)},support,reason)

change('THEME-P-0005-REL@1',{'body':'Föräldrarna, två yngre systrar (P-0303 och P-0304), farföräldrar, två fastrar, hustru och tre söner är bevarade med källkontext. C-0266 namnger familjens tre barn inklusive Jan-Christer; han har därmed två namngivna systrar, inte tre syskon. Registerroller hålls skilda från relationernas biologiska/rättsliga art. Egna vänner, kolleger och nutida hushåll samlas inte inom den personbundna dataminimeringen. Ingen relationskant ändras.'},['R-31ddf6090af32ffa30920ac9@1','REL-sibling-P-0005-P-0303@1','REL-sibling-P-0005-P-0304@1'],'Rättar faktiskt felräknade och felåldersordnade syskon i aktuell tematext; två yngre systrar följer redan accepterat familjeunderlag.')
change('THEME-P-0005-SAM@1',{'body':'Den äldre anteckningen icke döpt på Flen folio 860 följs på folio 720 rad 16 av dopnoteringen 16 november 1941. E-baptism-P-0005@1 bevarar detta redan accepterade datum; fysisk dopplats och senare trosutövning sluts inte. Hushållsbokföring och den egna uppgiften om nationsinskrivning i Uppsala januari 1960 återbrukas. Nutida föreningsliv, myndighetskontakter och rättsliga förhållanden samlas inte. Det är personbunden dataminimering, inte ett negativt källfynd.'},['E-baptism-P-0005@1','TR-717e9c73524962d14b10314c@2','TR-bd156a2627a87db06628621f@2','F-P-0005-education-uppsala1960@1'],'Starkare redan accepterad dopnot saknas bakom temats felaktiga endast-formulering.')
replace('BIO-P-0005@2','markdown','Familjen flyttade till Södertälje den 24 november 1943,','Flens församlingsbok folio 720 rad 16 antecknar hans dop den 16 november 1941 (C-0895; E-baptism-P-0005@1). Den äldre noteringen icke döpt är där överstruken; dopets fysiska plats och senare trosutövning anges inte.\n\nFamiljen flyttade till Södertälje den 24 november 1943,',['E-baptism-P-0005@1','TR-717e9c73524962d14b10314c@2'],'Konsoliderar redan native dopankare i livsberättelsen utan ny råavläsning eller privat precisionsökning.')
change('CONTRACT-P-0005-PK-03@1',{'body':'PK-03 STYRKT inom personbundet integritetsminimerat omfång. Den befintliga livslinjen innehåller födelseår/församling 1938 Flen, dopnot 1941-11-16 i Flen folio 720, hushållets registrering i Södertälje 1943-11-24 och bokföringskedjan Mejseln–Gondolen–Tranbäret till 1947. Familjeminnena om skolstart 1945, studentexamen 1958, värnplikt, Falsterbo 1959, Uppsala januari 1960 och krönikans utbildnings-/yrkesår 1973/2006 är daterade uppgiftslämnarled. Inga kontinuerliga fysiska vistelser eller nutida adresser fylls i. 42/40-frågan och registerteckenreservationerna består; PK08:s oprövade öppeninformationpassage kvarstår separat.'},['E-baptism-P-0005@1','BIO-P-0005@2','R-2989c302482c679b7fa007d7@1','R-31ddf6090af32ffa30920ac9@1'],'Kompletterar konsoliderad kronologi med redan accepterat dopankare; bevarar sakligt STYRKT inom dataminimerat livslinjeomfång, inte full livsbildspass.')
change('THEME-P-0006-MIL@1',{'outcome':'INTEGRITETSMINIMERAT','body':'Ingen egen militär- eller sjöfartsuppgift om Hillevi finns i det accepterade underlaget. Burträskuppslagets nummer 174 hör till faderns rad och tillför inte dottern militärtjänst. För den sannolikt levande personen görs ingen vidare privat breddinsamling inom denna personbundna avgränsning. Den tidigare årskullsargumentationen visar inte i sig att all militär- eller sjöfartsanknytning är irrelevant; inget sådant negativt sakfynd registreras.'},['AUDIT-T0675-38@1','AUDIT-T0675-45@1','ASSESSMENT-P-0006@2'],'Byter osakligt bred irrelevansgrund till den redan gällande personbundna dataminimeringen; inga nya fakta.')
change('CONTRACT-P-0006-PK-06@1',{'body':'PK-06 STYRKT inom personbundet integritetsminimerat omfång. Alla tio teman är individuellt prövade mot barndomens egna rader i Burträsk, familjeuppgifterna och den daterade utbildningsprofilen 2011. MIL är INTEGRITETSMINIMERAT: faderns nummer är inte hennes tjänst, och någon allmän frånvaro av militär-/sjöfartsanknytning påstås inte. Temabedömningarna innebär inte att den separata, ännu oprövade K09-vägen enligt PK08 är genomförd.'},['AUDIT-T0675-38@1','AUDIT-T0675-45@1','R-31ddf6090af32ffa30920ac9@1'],'Följer ändrad MIL-motivering utan automatisk fullnivåhöjning.')
change('KEY-P-0006-e60e57df3b5f@1',{'body':'Gammelbyn folio 1006 och folio 275, Gammelbyn 14, Burträsk: egna barndomsrader 1938–1950. Accepterad T0675-fullpostgranskning skiljer boköverföring från fysisk flytt. Faint margin/property superscripts och röda årtal på folio 1006 är reserverade; understrukna treställiga tal på folio 275 är råa tal utan fastställd personaktsnummerfunktion. Ingen sådan funktion eller ännu oläst helrad hävdas. Burträsk som födelseförsamling kommer från folio 275:s egen rad/dittos, inte den tomma ortskolumnen på folio 1006.'},['AUDIT-T0675-38@1','AUDIT-T0675-45@1'],'Senare accepterad tecken-/funktionsreserv överordnas äldre säker personaktsnummeretikett. Ingen ny källpassage.')

evy_support=['AUDIT-T0674-C0240@2','AUDIT-T0675-SATTNA388-44@1','ASSESSMENT-T0784-P0211-identity@1','O-P-0211-C0901-spouse@1','O-P-0212-C0901-own@2']
replace('BIO-P-0211@2','markdown','En vidare livsberättelse om Evy samlas inte in.','En vidare privat livsberättelse samlas inte in. Redan accepterade relationsankare återbrukas: enligt barnens minnesord om Gunnar gifte paret sig 1962 och Evy var efterlevande maka vid textens publicering 2017-10-10 (C-0901; O-P-0211-C0901-spouse@1). Mötet på Ibra radio i Stockholm ger varken vigselort, arbetsgivare eller bostad. Detta visar inte hennes levandestatus efter 2017.',evy_support,'Konsoliderar redan accepterade maka-/vigselankare; ingen ny privat insamling.')
change('CONTRACT-P-0211-PK-03@2',{'body':'PK-03 STYRKT inom det individuellt motiverade integritetsminimerade omfånget. Födelseankaret 1938-01-12 skiljer SCB:s nedkomstort Sundsvalls lasaretts B.B. från föräldrahemmet Storbränna i Sättna. Därtill återbrukas accepterat vigselår 1962 och efterlevande maka i barnens minnesord 2017-10-10. Luckorna mellan dessa ankare fylls inte till kontinuerligt boende, och 2017-uppgiften blir ingen nutida levandestatus. Inga nya privata tidslinjeuppgifter krävs inom den här personbundna minimeringen.'},evy_support,'Konsoliderar samtliga befintliga relevanta tidsankare, inte bara födelsen.')
change('CONTRACT-P-0211-PK-04@2',{'body':'PK-04 STYRKT inom personbundet integritetsminimerat omfång. Föräldrarna, dottern Kristina, familjens fem syskon och makan–make-relationen till Gunnar är bevarade i accepterade relationer och underlag. Vigselåret 1962 och efterlevande maka 2017 kommer från samma familjeminnesled, inte två oberoende vittnesmål. Inga fler privata hushåll eller nätverk behöver kartläggas för denna begränsade relationsbild; social närhet ges ingen ny släktskapsart.'},evy_support+['REL-spouse-P-0211-P-0212@1','REL-parent-P-0211-P-0210@1'],'Tillgodoräknar redan accepterat makestöd utöver äldre föräldra-/dotterformulering.')
change('CONTRACT-P-0211-PK-08@2',{'outcome':'STYRKT','body':'PK-08 STYRKT inom personbundet integritetsminimerat omfång, prövat 2026-10-06. C0240:s tidigare medie-/fullradslucka är slutligt hanterad i T0674 och C0935 folio388 r6–13 i T0675. Kvarstående egna tecken är prövade läsreservationer, inte olästa kolumner; tillräckligt accepterat underlag återbrukas enligt T0784. T0214:s andra familjeposter är inte nödvändiga nya Evy-passager. De befintliga familje- och makaankarna bevaras, men ingen bred kartläggning av en möjligt levande persons senare boende, ekonomi, hälsa eller privatarkiv motiveras här. PCD2026-09-09-029 tillåter öppen information men dess obligatoriska sjupersonspassage namnger inte Evy; inget generellt nätförbud eller påstådd källuttömning används som skäl. Återöppna vid konkret relevant motbelägg, nytt frivilligt familjeunderlag eller uttrycklig ändring av hennes personbundna integritetsomfång.'},evy_support,'Ny individuell PK08-bedömning efter accepterad fullpostutvinning och integritetsprövning; inte automatisk PASS från tidigare identitetsgrind.')
change('CONTRACT-P-0211-PK-10@2',{'body':'PK-10 STYRKT inom personbundet integritetsminimerat omfång. Den konsoliderade berättelsen skiljer födelse-/hemort, registreringsförsamling och reserverat ägarförtydligande, bevarar föräldra-/dotterbryggan samt det redan kända vigselåret 1962 och efterlevandeställningen 2017. Barnens minnesord anges som familjeunderlag. Varken levandestatus efter 2017, kontinuerligt boende, yrke eller privat trosuppfattning konstrueras.'},evy_support,'Avstämmer kompletterad minimal berättelse mot befintliga accepterade ankare.')

gcat=['F-P-0212-source_access-C0906@1']
change('THEME-P-0212-EKO@1',{'outcome':'ÖPPET','body':'Ingen egen egendom, inkomst eller skuld är belagd i granskat underlag. C0906:s prov 2026-09-06 gäller Riksarkivets lagfartsböcker 1875–1933, som inte täcker ett möjligt Flobyförvärv på 1960-talet. Det bevisar inte att samtliga nutida alternativa nätvägar är uttömda. Lantmäteriets möjliga fastighetsväg och eventuell bouppteckning efter döden 2017 är ännu inte personprövade; inget fastighetsägande eller ens befintlig bouppteckning antas. Källåtkomst och rätt ingång måste avgränsas innan handling öppnas eller beställs.'},gcat,'Lokalt daterat katalogprov bär inte en full prövad onlinegräns för ekonomitemat.')
change('THEME-P-0212-MIL@1',{'outcome':'ÖPPET','body':'Ingen militärtjänst är belagd för Gunnar. År omkring 1953 är en möjlig planeringsingång från födelseåret 1933, inte belagd inskrivning. C0906:s katalogprov 2026-09-06 fann Värnpliktsverkets 1968–1995-serier och äldre länsvisa inskrivningsböcker utan digital bild i det prövade omfånget. Detta är inget personnoll och bevisar inte att alla relevanta alternativa åtkomstvägar är prövade. Rätt inskrivningsområde och personlig post är okända; eventuell framtida passage begränsas först till routing/åtkomst och får inte tillskriva honom tjänst eller hälsodata.'},gcat,'Separat nödvändighets- och åtkomstprövning saknas för total AVGRÄNSAT; ingen inskrivningshändelse får härledas ur årskull.')
replace('THEME-P-0212-ARB@1','body','de kommunala skolarkiven ligger utanför NAD.','C0906:s fyra angivna NAD-sökningar gav ingen relevant skolarkivserie; faktisk åtkomst hos kommunen och möjliga matrikelalternativ är inte därmed uttömda.',gcat,'Preciserar lokalt söknoll utan generell frånvaro av skolarkiv.')
change('THEME-P-0212-REL@1',{'body':'Föräldrar och tre syskon är bevarade genom födelsepost, hushåll och uttrycklig familjeuppgift; helsyskonarten kommer inte enbart ur hushållsgemenskap. Maka, vigselår 1962 och dotter har minnesords-/familjekontext; två andra efterlevande barn är legitimt minimerade. Exakt vigselförsamling, vigselpost och vidare materiellt nätverk återstår. Födelsepostens Odöpt gossebarn och Lidingöbokens icke döpt av sv. kyrkan är daterade noter; de bevisar inte att en dopnotis eller dopvittnen aldrig funnits senare eller i annat samfund. Ingen sådan handling öppnas här.'},['F-P-0212-church_note-1933-1946@1','O-P-0212-C0901-own@2','O-P-0212-C0268-full-siblings@1'],'Rättar obegränsad dopfrånvaro och skiljer bevarat helsyskonstöd från enbart hushåll.')
change('CONTRACT-P-0212-PK-04@1',{'body':'PK-04 EJ STYRKT på livsbildsnivån. Föräldrar och tre syskon, maka och dotter är bevarade med rätt källkontext; helsyskonarten stöds av familjeuppgift. De två andra barnens dataminimering är sakligt motiverad och är inte ett kravfel. Den återstående bristen gäller den ännu okända vigselförsamlingen/olästa vigselposten 1962 och oprövat relevant nätverk, inom den avlidne Gunnars eget liv. T0359 kan ge avgränsade hushålls-/utflyttningsnycklar; T0362 äger frågelistan om1951–1967. Identitetsnivåns befintliga relationer ändras inte.'},['O-P-0212-C0901-own@2','O-P-0212-C0268-full-siblings@1'],'Bevarar underkänt sakutfall men slutar behandla legitim minimering av levande barn som brist.')
change('CONTRACT-P-0212-PK-06@1',{'body':'PK-06 EJ STYRKT för full livsbild. Alla tio teman är individuellt redovisade; ID är GENOMGÅNGET med OWNER-namnet och den dokumentära avvikelsen skilda åt. ARB, BO, EKO, HAL, MIL, PER, REL, SAM och SYN är ÖPPET. EKO/MIL ändras från otillräckligt motiverad AVGRÄNSAT till ÖPPET eftersom C0906:s lokala katalogprov inte styrker full onlinegräns. Exakta kunskapsluckor och möjliga ingångar är synliga, men denna befintligmaterialpassage utför inte deras källarbete.'},gcat+['F-P-0212-name-owner-confirmed@1'],'Rättar tidigare sex-räkning och två övervida källgränser utan att framtvinga tematäckning.')
change('CONTRACT-P-0212-PK-08@1',{'body':'PK-08 EJ STYRKT. Egen födelsepost och gravpost återbrukas med accepterade råreservationer och bevarande; dödsannonsdelen är inte utförd. Den egna fortsättningen efter1951, folio1719, är oläst och ägs av T0359 inom två hushållsuppslag plus register. T0362 äger en avgränsad ägarfrågelista om1951–1967. C0906:s daterade prov är inte heltäckande kontroll av yrkes-, ekonomi-, militär- och föreningsvägarnas åtkomst. Tillgång, alternativ och kunskapsvärde återstår att sakligt avgränsa, utan påstådd nätåtkomstgaranti eller krav på omedelbar beställning. Ingen väg utförs i T0790.'},gcat+['F-P-0212-source_reference-Lidingo1951@2','PATH-P-0212-KP-02@2'],'Slutar räkna hela KP02 som utförd och hela KP05 som konstaterat hinder; bevarar faktiskt PK08-underkännande.')
replace('BIO-P-0212@5','markdown','De källfamiljer som normalt skulle belysa ett yrkesliv från 1950-talet framåt — värnpliktshandlingar, kommunala skolarkiv, lärarmatriklar och lagfart — är analoga, förvarade utanför Riksarkivets katalog eller avslutade före hans tid, vilket är ett dokumenterat åtkomstläge och inget personnoll.','Det daterade katalogprovet 2026-09-06 prövade vissa värnpliktsserier, NAD-sökningar efter skolarkiv, LIBRIS-sökningar efter matriklar och Riksarkivets lagfartsserie1875–1933. Resultaten gäller dessa ingångar och år, inte alla relevanta alternativa nätvägar. Ingen personsökning efter Gunnars tjänst, inskrivning eller fastighet gjordes i dessa serier. Faktisk åtkomst och relevanta alternativ är fortsatt oprövade i de preciserade återstående delarna.',gcat,'Aktuell berättelse generaliserar C0906 till uttömmande analog åtkomst; ersätt med faktiskt prövat omfång.')
replace('P-0212/Q-02@1','body','Den enda nätåtkomliga oöppnade passagen är Lidingös församlingsbok uppslag 1718–1719.','Den konkret identifierade hushållsfortsättningen är1951 års uppslag1718–1719, med Gunnars egen rad på1719, och ägs av T0359. Den fortsatta bokens digitala åtkomst är inte kontrollerad här. C0906 visar inte att denna är den enda möjliga nätvägen; exakt leverantörs-/källomfång måste prövas separat.',['F-P-0212-source_reference-Lidingo1951@2',*gcat],'Ingen nätåtkomstgaranti eller exklusiv källväg följer av befintligt prov.')
replace('P-0212/Q-03@2','body','Att barnet var odöpt gör att ingen samtida dopnotis kan skilja alternativen.','Födelseposten är namnlös och betecknar barnet odöpt, medan1946-bokens not gäller dop inom svenska kyrkan. Ingen dopnotis som kan skilja alternativen är läst; de daterade noterna bevisar inte att sådan handling aldrig funnits.',['F-P-0212-church_note-1933-1946@1'],'Rättar slutsats från frånvarande/daterad dopuppgift till absolut frånvaro; OWNER-namnet och dokumentär konflikt behålls.')
change('PATH-P-0212-KP-04@1',{'outcome':'EJ UNDERSÖKT: egen fortsättning från1951, folio1719; digital åtkomst ej kontrollerad.','body':'KP-04: Lidingö kyrkoarkiv SE/SSA/1529, nästa bok efter AIIa/29 från1951. Gunnars egen hänvisning1719/51 är accepterat läst; modern och två syskon har1718. T0359 äger den enda samordnade passagen för hela det angivna hushållet: högst1718 och1719 plus ett register, full egen rad och egen utflyttningshänvisning inom nästa bokperiod. Ingen läsosäkerhet fabriceras för det nu klarlagda1719, och ingen garanti om digital tillgänglighet ges. Nuvarande personnycklar, båda namnordningarna och födelsedatumet kan återbrukas; Kyrkovägen10 är odaterad i den äldre boken. Förväntat värde: boende/utbildnings-/utflyttningsankare i luckan1951–1962 och eventuell dokumentär namnordning; en ny kyrkobok är inte automatiskt oberoende namnbevis. Vigselförsamlingen1962 och senare böcker ingår bara om den står i den egna begränsade posten, annars utanför ägarens scope. Tidigare egen rad1341 är redan fullutvunnen med reserverad kolumn9; den ska inte läsas om för denna passage.'},['F-P-0212-source_reference-Lidingo1951@2','AUDIT-T0675-HOOK-4@1'],'Inför faktisk exakt passageägare och säkert klarlagd egen hänvisning utan att utöka T0359.')
change('PATH-P-0212-KP-05@1',{'outcome':'Delvis lokalt katalogprov2026-09-06; övrig åtkomst/alternativ EJ KONTROLLERAD, inga personnoll.','body':'KP-05, Gunnar1950–2017: C0906 prövade Riksarkivets Värnpliktsverket/SE/KrA/0495 Stamkort-ingångar, länsvisa inskrivningsböcker i katalogen utan digital bild, tre LIBRIS-sökningar med träffar1857/1889 men ingen modern träff, fyra angivna NAD-frågor om Floby/Fredriksberg/Falköpings skolarkiv samt lagfartsböcker1875–1933. Proven visar inte frånvaro av moderna matriklar eller alla nätåtkomliga alternativ. Ingen inskrivning, fastighet eller personpost är därmed belagd. Möjliga kompletterande ingångar: rätt inskrivningsområde omkring1953; kommunens egna skolarkiv för tjänsterna efter Flobyflytten1967; lärar-/skolledarmatriklar1950–1980; fastighetsrouting för eventuellt Flobyboende på1960-talet; eventuell bouppteckning2017; Liberalernas/FN-föreningens eller kulturnämndens uppdragsunderlag före2017. Deras konkreta åtkomst och diskriminerande värde är ej styrkta här. Ingen beställning, kontakt, personmedicinsk insamling eller sourceöppning följer av denna korrigering. T0359 och T0362 kan tillföra nycklar men görs inte till fabricerade tekniska beroenden. En separat ändlig metadata-/åtkomstprövning behöver faktisk Wotanägare före utförande; T0790 öppnar inga nya källor.'},gcat+['O-P-0212-C0901-own@2'],'Bevarar det utförda katalogprovet och återstående frågor, avlägsnar universell analogspärr. Root registrerar exakt bounded efterföljare före DONE.')
replace('KEY-P-0212-0767ee81003f@1','body','arkiven finns inte i NAD','C0906:s fyra angivna NAD-sökningar gav ingen relevant skolarkivserie; kommunens faktiska åtkomst är inte prövad',gcat,'Samma övervida skolarkivslutsats får inte ligga kvar i strukturerad söknyckel.')

# Individual dispositions. Each key is a genuinely considered person/theme or PK,
# not a score inferred from count or a copied legacy review outcome.
scope={
'P-0004':'1963 födelseankare, familjefoto1975 och daterad yrkes-/utbildningsprofil2011; födelseort okänd, Kista arbetsplats inte bostad; relationer ur egna familjeuppgifter.',
'P-0210':'1964 födelseankare och kärnfamiljerelationer; födelseort, vigseldag och namnbytesdag okända, inga föräldraorter övertas.',
'P-0005':'1938–1947 Flen/Södertälje egna barndomsrader,1941 dop, egna minnen1945–1960 och krönika2011 med1973/2006; senare privata perioder minimerade.',
'P-0006':'1938–1950 Gammelbyn/Burträsk, utflyttningsregistrering1950-09-02 till Umeå, makens2011uppgifter om odaterade examina; Umeå mottagande oläst.',
'P-0211':'1938-01-12 SCB Sättna/Storbränna/Sundsvalls BB, C0935 egenrad13, familjerelationer, accepterat vigselår1962 och efterlevande maka2017; nutida status okänd.',
'P-0212':'1933 registrerad födelse Engelbrekt; barnens Indienberättelse, Lidingö1946–1951, lucka1951–1962, vigsel1962, Floby1967, odaterade tjänster/uppdrag, utmärkelse2008, död2017/grav2018.'}
reasons={
'P-0004':{
'ID':'Egen identifiering och OWNER-födelsedag bär det minimerade ankaret; ingen källa till födelseort antas.',
'REL':'Föräldrar, två bröder, hustru och två söner återbrukas med sin verkliga familjeprovenans; ingen biologisk/rättslig art läggs till.',
'BO':'Inget säkert eget bostadsankare i den daterade yrkesprofilen; Kista är arbetsplats. Privat bostad samlas inte, inte ett söknoll.',
'ARB':'Faderns2011profil bär doktor/avdelningschef vid just den tiden, inte nutida titel eller examensdag.',
'EKO':'Inget eget ekonomiskt sakstöd; personbunden privat minimering räcker för temat, inte påstådd källa uttömd.',
'MIL':'Ingen egen tjänstuppgift i accepterat familjeunderlag; privat minimering utan negativ tjänstslutsats.',
'SAM':'Inget sakstöd för egna institutionella kontakter; personbunden privat minimering, ingen slutsats om frånvaro.',
'HAL':'Ingen hälso-/dödsuppgift behöver tillföras för självidentifierad levande projektägare; ingen död fabriceras.',
'PER':'Bevarad bildtext1975 och familjekrönika2011 återbrukas som familjematerial, ingen ny bildidentifiering.',
'SYN':'Minimal befintlig berättelse binder1963/1975/2011 och relationer, utan kontinuerlig privat livslinje; PK08 består öppet.',
'PK-03':'Befintliga tidsankare är samlade och privata luckor individuellt minimerade; arbetstitel blir inte bostad.',
'PK-04':'Relationerna är källbundna utan extra nätverksinsamling; inga nya kanter behövs.',
'PK-06':'Tio individuellt motiverade minimeringar är bedömda; det separata PK08-felet göms inte.',
'PK-08':'PCD029 namnger personen och den oprövade K09-vägen ägs av T0034; inga mottagna receipts visar utfört resultat.',
'PK-10':'BIO@1 är tillräcklig källförankrad minimerad sammanfattning; ingen omskrivning bara för ny review.'},
'P-0210':{
'ID':'Makens identifikation och OWNER-födelsedatum återbrukas; namnbytesdag och födelseort förblir okända.',
'REL':'Make, föräldrar, söner och angivna äldre släktankare bär den minimerade relationsbilden; tre meddelanden är en informant.',
'BO':'Ingen egen bostadsort belagd; föräldrarnas Sundsvall/Lidingö får inte överföras till henne.',
'ARB':'Inga egna yrkes-/utbildningsuppgifter i bevarat underlag; privat minimering, inget källnoll.',
'EKO':'Ingen ekonomisk insamling behövs inom personbundet minimerat omfång; inget känt ekonomiskt faktum förnekas.',
'MIL':'Ingen egen militär/sjöfartsuppgift; minimering är skäl, inte påstådd irrelevans av alla möjliga källor.',
'SAM':'Rättsliga/kyrkliga/sociala privata kontakter samlas inte; ingen avsaknad bevisas.',
'HAL':'Sannolikt levande enligt underlag; ingen aktuell döds-/hälsoforskning eller ny levandestatus.',
'PER':'Inga egna personliga medieobjekt i accepterad täckning; det är lokal materialgräns och privat minimering.',
'SYN':'Minimal berättelse återbrukas med current caveat som uttryckligen upphäver gamla totalförbud; ingen falsk fullgranskning.',
'PK-03':'1964/familjeankare sammanhållna; övriga privata livsperioder minimerade utan gissade orter.',
'PK-04':'Åtta äldre relationsankare tillgodoräknas, inte ny nätverksutvidgning.',
'PK-06':'Varje temas minimering bedömd mot den egna begränsade källbilden; inga tomma temarubriker.',
'PK-08':'PCD029 namnger personen; T0034:s K09-korroborering är fortfarande oprövad. Äldre inga-vägar-prosa är uttryckligen överspelad.',
'PK-10':'BIO@1:s faktadel är giltig och redan kvalificerad av current caveat; korthet är inte i sig fel, full life ändå failed.'},
'P-0005':{
'ID':'År/Flen och föräldra-/familjekedja återbrukas; exakta privata födelsedagen återförs inte. Råmånad2/7 i Tranbäret harmoniseras inte.',
'REL':'Rättar tre syskon och äldre systrar till två yngre systrar enligt krönika och native relationer; övriga bevarade anhöriga består.',
'BO':'Flen/Södertälje1938–1947 återbrukas med42/40 och sigelreservationer.1948–1970 är oläst, inte noll; bokföring är inte obruten fysisk vistelse.',
'ARB':'Egna minnen och2011krönika ger daterad skol-/yrkessekvens; institutionella primärkällor är inte lästa.',
'EKO':'Faderns oavgjorda blyertsord affär/delägare får inte tillskrivas sonen. Current@2 reservation är redan korrekt.',
'MIL':'Egna15månadersminnet vid I1/T4 bevaras som minne; inga exakta in-/utdatum eller yrkesmilitärstatus.',
'SAM':'Konsoliderar redan accepterad dopnot1941-11-16; tidigare endast-hushåll/nation är för snävt. Ingen nutida tro sluts.',
'HAL':'Ingen egen hälsoinformation; faderns dödsorsaksbedömning gäller fadern. Privat minimering består.',
'PER':'Krönika, brev och två barnbilder återbrukas; Flen1943bildens begränsade datering och gemensam informant består.',
'SYN':'BIO kompletteras med redan accepterat dopankare. Övrig daterad minnessekvens återbrukas utan kontinuerligt vuxenboende.',
'PK-03':'Befintlig kronologi är tillräcklig inom minimeringen efter dopankarets konsolidering; PK08 separat underkänd.',
'PK-04':'Tolv äldre relationsankare återbrukas, med två yngre systrar och korrekt hushållsroll; ingen ny person skapas.',
'PK-06':'Tio personbundna bedömningar återbrukas med REL/SAM-korrigering; ingen fullnivå från antal.',
'PK-08':'Current@2 EJ STYRKT genom uttryckligtPCD029 är gällande; T0034:s äldre fem-undantag är inte norm.',
'PK-10':'Källkritisk BIO@2 bär berättelsen; dopankare läggs till utan nya sakfakta,42/40 och råreservationer består.'},
'P-0006':{
'ID':'Anna Hillevi och födelseåret återbrukas; Burträsk kommer från fol275, inte tomma fol1006. OWNER-föräldrar/syskon demoteras inte.',
'REL':'Föräldrar/bröder OWNER samt make/söner familjeuppgifter bevaras; farbroderns grannskap blir inte hushåll.',
'BO':'Bokföring1938–1950 och utflyttning1950 återbrukas; Umeåmottagande oläst. Ingen kontinuerlig senare fysisk bosättning sluts.',
'ARB':'Makens2011profil ger två examina från Uppsala, inga examensår eller yrkesutövning; föräldrarnas läraryrken överförs inte.',
'EKO':'Barnraderna ger inget eget ekonomiskt underlag; personbunden privat minimering, inget globalt ekonomiskt noll.',
'MIL':'Ändras till INTEGRITETSMINIMERAT: inget eget spår, faderns nummer inte hennes. Årskull ensam bär inte generell irrelevans.',
'SAM':'Historisk hushållsbokföring återbrukas; senare institutions-/trosliv minimeras. Lästa tomma småfält blir inga livslånga negativa.',
'HAL':'Tom egen dödskolumn gäller bara boken; ingen nutida hälsa eller levandestatus härleds.',
'PER':'Elva bildtexter namnger inte henne inom granskat material; detta är lokal materialtäckning, inte total personarkivfrånvaro.',
'SYN':'BIO@1 sammanhåller1938–1950 och2011uppgiften; current caveat rättar födelseortens folio och PK08@2 gäller.',
'PK-03':'1938–1950/2011 är tydliga avgränsade ankare utan fabricerade mellanår eller examens-/vigseldag.',
'PK-04':'Nio relationsankare återbrukas med OWNER och familjekällor, grannskap hålls isär.',
'PK-06':'STYRKT inom minimerat omfång efter reviderad MIL-motivering; ingen uppgradering av PK08.',
'PK-08':'Current@2 EJ STYRKT enligtPCD029 består; T0034 prövar grunduppgifterna senare, inget nytt sökresultat nu.',
'PK-10':'BIO@1 är källkritisk, minimerad och läsbar med sin specificerade current caveat; ingen ny text behövs.'},
'P-0211':{
'ID':'T0784 current identity passed återbrukas; C0240 namn/datum och ägarkontext bär, C0935 råalternativ är inte ny exakt bekräftelse.',
'REL':'Föräldrar, dotter/fem syskon och redan accepterad make/vigsel1962/efterlevandeställning2017 sammanhålls utan privat utvidgning.',
'BO':'Storbränna föräldrahem skiljs från Sundsvalls BB nedkomstort; inga senare privata bostäder tillförs.',
'ARB':'Ingen egen yrkesfråga behövs för den minimerade historiska relationsbilden; faderns chaufförsyrke överförs inte.',
'EKO':'Egen ekonomi är personbundet minimerad för möjligt levande person; källuttömning påstås inte.',
'MIL':'Faderns nummer hålls på P0241, inget eget militärt privatliv samlas.',
'SAM':'Egen historisk icke-döpt-not bevaras tidsbundet; inget nuvarande samfund eller övertygelse sluts.',
'HAL':'Efterlevande maka2017 är redan känt, inte levandestatus2026; senare hälsa/död är privat minimerad, inte söknoll.',
'PER':'Familjeuppgifter och befintligt minnesordsled återbrukas; inga nya bilder, kontaktuppgifter eller privatarkiv behövs.',
'SYN':'Minimal BIO kompletteras med accepterade1962/2017ankare; ingen luckfyllnad eller ny privatinsamling.',
'PK-03':'Samtliga nödvändiga redan kända tidsankare1938/1962/2017 konsolideras med ort-/statusgränser.',
'PK-04':'Föräldra-/dotter/syskon- och makaankare tillräckliga inom personbunden minimering; familjenätverk dupliceras inte.',
'PK-06':'Alla tio teman individuellt sakprövade; minimeringen grundas på hennes person/syfte, inte automatiskt på ålder.',
'PK-08':'STYRKT inom individuellt minimerat omfång: exakt fullutvinning färdig, kvartecken prövade; T0214 andra poster krävs inte. PCD029s obligatoriska lista inkluderar inte Evy.',
'PK-10':'Minimal berättelse blir konsoliderad även för accepterat vigsel-/efterlevandeled; inga egna bostads-/yrkesfakta konstrueras.'},
'P-0212':{
'ID':'OWNER-namnet står fast; källornas andra namnordning och administrativa beroende är dokumentär fråga, inte personosäkerhet.',
'REL':'ÖPPET består för vigselförsamling1962/nätverk, inte för legitim barnminimering. Absolut dopfrånvaro rättas till daterade noter.',
'BO':'Registrerade ankare och familjeminnen bevaras;1951–1962 materiell lucka.1719 är egen hänvisning, Kyrkovägen10 odaterad.',
'ARB':'Yrkesordningen från minnesord stöds, tjänste-/examensår saknas; NAD-noll får endast sitt sökomfång.',
'EKO':'ÖPPET ersätter övervid AVGRÄNSAT;1933slut på prövad lagfartsserie avgör inte alla alternativ eller boupp2017.',
'MIL':'ÖPPET ersätter övervid AVGRÄNSAT; omkring1953 är planeringshypotes, ingen belagd inskrivning; känt katalogläge är lokalt.',
'SAM':'Uppdrag/2008medalj familjeminnesbelagda, mandatperiod/lokalavdelning/protokoll oprövade; kyrkonoten tidsbunden.',
'HAL':'Död2017/grav2018 återbrukas. HemortFalköping är inte dödsplats och gravsättning inte ceremoni/urnsättning. Övrig hälso-/dödsorsak okänd.',
'PER':'Fullt accepterade barnens minnesord återbrukas; värdeomdömen attribution, IFKidrott är kandidat och familjebilder inte undersökta.',
'SYN':'Sammanhängande källkritisk berättelse kan återbrukas med korrekt källåtkomstgräns; luckan1951–1962 består.',
'PK-03':'EJ STYRKT består: egen fortsättning1951 oläst och materiell tidslucka, T0359 exakt framtida ägare.',
'PK-04':'EJ STYRKT för vigsel-/nätverksfråga, inte minimerade levande barn; grundrelationer bevaras.',
'PK-06':'EJ STYRKT; alla teman bedömda men nio öppna efter korrigering av två otillräckliga gränser.',
'PK-08':'EJ STYRKT; T0359/T0362 utförs inte här, C0906 är lokalt och dödsannons oläst. Ny bounded källåtkomstprövning föreslås.',
'PK-10':'STYRKT efter snäv rättelse av BIO:s övervida källåtkomstpåstående; god prosa betyder inte fylld livslucka.'}}

supports={
'P-0004':['R-C0252-family@1','R-3f2d691a05a9abe1b45f0274@1','R-31ddf6090af32ffa30920ac9@1','BIO-P-0004@1','CONTRACT-P-0004-PK-08@1'],
'P-0210':['R-C0252-family@1','O-P-0210-C0140-own@1','BIO-P-0210@1','CONTRACT-P-0210-PK-08@1'],
'P-0005':['R-31ddf6090af32ffa30920ac9@1','R-2989c302482c679b7fa007d7@1','AUDIT-T0675-sodertalje-tranbaret@1','AUDIT-T0675-sodertalje-gondolen@1','TR-717e9c73524962d14b10314c@2','BIO-P-0005@2','CONTRACT-P-0005-PK-08@2'],
'P-0006':['R-31ddf6090af32ffa30920ac9@1','AUDIT-T0675-38@1','AUDIT-T0675-45@1','BIO-P-0006@1','CONTRACT-P-0006-PK-08@2'],
'P-0211':evy_support+['BIO-P-0211@2'],
'P-0212':['O-P-0212-C0901-own@2','AUDIT-T0675-HOOK-3@1','AUDIT-T0675-HOOK-4@1','F-P-0212-source_access-C0906@1','F-P-0212-name-owner-confirmed@1','F-P-0212-church_note-1933-1946@1','BIO-P-0212@5']}
byrev={c['target_revision']:c for c in changes}
rows=[]
for p in pids:
 for group in ['themes','requirements']:
  for x in people[p]['research'][group]:
   key=x['object_id'].split('-')[-1] if group=='themes' else x['criteria'].split('/')[-1]
   if group=='requirements' and key not in ['PK-03','PK-04','PK-06','PK-08','PK-10']:continue
   rev=x['revision_id'];c=byrev.get(rev)
   new_outcome=next((f['new'] for f in c['field_changes'] if f['field']=='outcome'),x['outcome']) if c else x['outcome']
   rows.append(dict(person=p,item=key,object_id=x['object_id'],old_version=x['version'],field_scope='data.outcome; data.body; caveat and existing evidence',old_outcome=x['outcome'],old_body=x['body'],old_caveat=x['caveat'],disposition='revise' if c else 'retain',new_outcome=new_outcome,individual_rationale=reasons[p][key],person_period_place_scope=scope[p],supporting_versions=list(dict.fromkeys([rev]+supports[p]+(c['supporting_versions'] if c else []))),source_reuse='Accepted source extraction/current model only; no original or external read. Shared family texts and registration chains are not new independent evidence.'))
assert len(rows)==90
assert sum(r['item'].startswith('PK') for r in rows)==30
assert all(v in native for r in rows for v in r['supporting_versions'])

reviews=[]
for p in pids:
 outcome='passed' if p=='P-0211' else 'failed'
 selected=[r for r in rows if r['person']==p]
 body='T-0790, individuell livsbildsgranskning 2026-10-06; endast befintligt accepterat material.\n\n'
 body+='Omfång: '+scope[p]+'\n\n'
 body+='\n'.join(f"{r['item']} — {r['new_outcome']}. {r['individual_rationale']}" for r in selected)
 body+='\n\nSlututfall: '+outcome+'. '
 if p in ['P-0004','P-0210','P-0005','P-0006']:
  body+='T0034 äger den ännu oprövade öppna K09-grunduppgiftspassagen enligtPCD2026-09-09-029; current PK08 EJ STYRKT kvarstår. Personbunden dataminimering betyder inte att denna materiella passage är utförd. Återöppna livsbildsutfallet när exakt personutfall med provenans faktiskt finns, eller ägaren uttryckligen ändrar personens omfång.'
 elif p=='P-0211':
  body+='Denna persons integritetsminimering är individuellt prövad mot1938posterna, familjebryggan och redan accepterade1962/2017ankare. Kvartecken är prövade råreservationer; ingen nödvändig oläst Evypost återstår i det minimerade omfånget. Öppeninformationtillåtelsen är inget generellt krav på privat breddinsamling och Evy ingår inte iPCD029:s beställda sjupersonspassage. Återöppna vid relevant motbelägg, nytt frivilligt familjeunderlag eller ändrad uttrycklig personavgränsning. Detta är inte intyg om full dokumentation av hennes privata liv eller nutida levandestatus.'
 else:
  body+='Livsluckan1951–1962, vigsel-/nätverks- och källåtkomstfrågorna är materiella. T0359 äger exakt nästa Lidingöuppslag1718–1719 plus register; T0362 äger frågelistan1951–1967. KatalogprovetC0906 bär endast sitt utförda omfång; dess kvarvarande routing behöver den separat bounded Wotanägare som anges i operationspaketet. Återöppna endast berörda teman/krav efter faktisk ny evidens eller verifierad specifik åtkomstgräns. Ägarnamnet och dokumentära avvikelsen står kvar.'
 body+=' Identitets-/trädnivå, accepterade relationer, OWNER_CONFIRMED och tidigare helkontraktsgranskningars historiska innebörd ändras inte. Task-DONE och detta personutfall är skilda saker.'
 reviews.append(dict(id='ASSESSMENT-T0790-'+p.replace('-','')+'-life',expectedVersion=0,kind='assessment',disposition='recorded',evidence_status=None,data=dict(subject_id=p,criteria='life_picture_review/1',outcome=outcome,body=body),rationale='T0790 AC1–4: egen individuell prövning av fem PK och tio teman med accepterat återbruk, aktuella källgränser och personbunden dataminimering.',caveat='Ingen ny original-, katalog- eller nätläsning. Bevarade source-reservationer och oberoendegränser består. Versionbindings must be settled to the final staged current revisions after approved corrections; zero/multiple targets return to Astra.',evidence_versions=list(dict.fromkeys(supports[p]+[r['object_id']+'@'+str(r['old_version']) for r in selected]))))

followup=dict(proposed_owner='Root to allocate exact bounded Wotan task; no current execution',person='P-0212',purpose='Pröva C0906:s kvarvarande övervida åtkomstslutsatser genom avgränsad metadata/routing, inte ny livsrekonstruktion.',existing_owners=[dict(id='T-0359',scope='Hela angivna Höökhushållets nästa1951bok,1718/1719 plus ett register; Gunnars egen1719, inga senare böcker.'),dict(id='T-0362',scope='Ägarfrågelista om Gunnar1951–1967; inget svar antas, ingen extern kontakt.')],units=[dict(id='U1',period='omkring1953',provider='Riksarkivet',field='rätt inskrivningsmyndighet/område och prövad digital metadataåtkomst för född1933; ingen personlig tjänst antas'),dict(id='U2',period='1967–2017',provider='Falköpings kommunarkiv',field='arkivrouting/digital tillgång för Flobyskolan och Fredriksbergskolan; inga anställningsakter'),dict(id='U3',period='1950–1980',provider='LIBRIS',field='relevant lärar-/skolledarmatrikelutgåva och nätåtkomst; äldre C0906noll återbrukas, ingen personnoll'),dict(id='U4',period='1960-talet',provider='Lantmäteriet',field='möjlig tillåten nätingång till historisk fastighetsidentifiering/lagfart för Floby; inget ägande eller fastighets-ID antas'),dict(id='U5',period='2017',provider='Skatteverket',field='möjlig tillåten metadata-/åtkomstväg för eventuell bouppteckning efter Gunnar; handlingens existens inte antagen'),dict(id='U6',period='före döden2017, inklusive2008',provider='Västra Götalandsregionens kulturnämnd/Liberalerna/FN-föreningsarkiv',field='högst två relevanta öppna katalog-/registeringångar om kända uppdrag/medalj, exakt lokalavdelning och mandatperiod fortfarande okända')],stop='Högst två relevanta metadataingångar per U1–U6, totalt tolv. Ingen originalpersonhandling, bild, brev, hälsodata, beställning, kontakt eller fri namnsökning; ingen ny nutidsinsamling om levande anhöriga. Fastställ tillgång/okänd uppgift/lokalt noll med exakt datum och omfattning; ingen fysisk källa beställs. Vid saknad nyckel namnge nyckeln och anskaffningsväg, inte automatiskt BLOCKED. Därefter nytt beslut före någon faktisk personpost.',exclusions='T0359/T0362 utförs inte; inga andra personer, nya generationer, generell40källfamiljsinventering eller fri livsbildsforskning.',why_needed='Nödvändig begränsad följd av felaktigt avslutade EKO/MIL och universell analogspärr i current KP05. Angivna övriga livsfrågor förblir kunskapsluckor; detta begränsade uppdrag löser inte hela1950–2017.')

out=dict(task='T-0790',role='primary source/evidence',freeze='Own first judgment before independent proposals, 2026-10-06',root_release_sha256='1f9ceabb88996d2506422ece47e27fe84f701a675d019e2c6d4a59abaae4e0d4',source_access='0 new originals/catalog/web; accepted extraction reused, native809 availability is not809 reading credit',scope=pids,individual_table=rows,exact_changes=changes,six_life_reviews=reviews,bounded_followup=followup,implementation_gate='This is source-approved candidate wording, not canonical approval. Sol must mechanically preserve metadata, resolve every evidence version individually and stage exact operations. Independent comparison and exact-package source/consequence final gate remain.',read_coverage='Six full current person/research views including body/caveat, facts/events/relations/narratives; relevant accepted source-bound audits for C0240/C0935/C0884/C0889/C0894/C0895/C0901/C0902/C0903, C0266/C0267 accepted extraction, C0906 full preserved catalog-report; exact T0034/T0359/T0362/T0214 and current PK08@2/OWNER/privacy decisions. No source images or original documents opened.')
(root/'primary-own-90-dispositions-and-exact-changes-v1.json').write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n')
digest=hashlib.sha256((root/'primary-own-90-dispositions-and-exact-changes-v1.json').read_bytes()).hexdigest()
(root/'primary-own-freeze-v1.json').write_text(json.dumps(dict(task='T-0790',artifact='primary-own-90-dispositions-and-exact-changes-v1.json',sha256=digest,rows=len(rows),themes=60,PK=30,literal_changes=len(changes),native_life=6,passed=['P-0211'],failed=[p for p in pids if p!='P-0211'],independent_proposals_seen=False),indent=2)+'\n')
print(digest,len(rows),len(changes))
