import json,pathlib,hashlib,datetime
R=pathlib.Path.cwd();D=R/'evaluations/T-0815';I=D/'implementation';S=I/'stage484-v1'
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
def load(p):return json.load(open(p))
assert sha(R/'genealogy2/data/research.sqlite')=='579621e34a890be16ee55eb9c5baaef29a945b30bf3f2595a08794f5738be76d';assert load(S/'actual-pending-full.json')==load(S/'actual-pending-contexts-initial.json')==[]
for name in ['verify','verify-assets']:
 x=load(S/f'{name}.json');assert x['ok']and not x['errors']
x=load(S/'verify-source.json');assert x['ok']and not x['problems']
log=(S/'targeted-review-pedigree-tests.log').read_text();assert 'pass 18'in log and 'fail 0'in log
axes=load(S/'final-axis-relations-OWNER-proof-v1.json');assert axes['nonfocal_axes_exact']==534;assert axes['protected_child_axes_full_exact'];assert axes['focal_legacy_LIFE_full_exact'];assert len(axes['relations_full_native_exact'])==26
result={'task':'T-0815','stage_state':{'journal_head':484,'pending':0},'main_baseline_state':{'journal_head':483,'pending':0},'main_unchanged_sha256':sha(R/'genealogy2/data/research.sqlite'),'stage_sha256':sha(S/'stage.sqlite'),'exact_native_changes':8,'existing_corrections':4,'new_native_identity_tree_reviews':4,'full_native_retains':662,'actual_dependency_requests':0,'resolution_operations':0,'persons':536,'nonfocal_axes_exact':534,'focal_axes':'Both identity failed usable and tree waiting usable; source-bound insufficient own fields remain scoped','focal_LIFE':'Entire existing legacy full-contract view unchanged; no new native LIFE review','protected_child':'P-0009 full identity/tree/LIFE axes unchanged','relation_fullnative_retains':26,'OWNER45':'Full current heads/native metadata/evidence/origins/order exact baseline','default_pedigree_paths_each':41,'default_full_paths_exact':True,'all44_nonderived_old_rows_and_order_protected':True,'validators':'verify/verify-assets/verify-source PASS','tests':'18/18 review/pedigree PASS, unchanged model code; prior wider accepted code tests reused','production':{'literal_materialization_seconds':load(I/'preflight-v1.json')['elapsed_seconds'],'clone_seconds':load(S/'initial-result.json')['elapsed_seconds'],'reader_capture_seconds':load(S/'reader-capture-result.json')['elapsed_seconds'],'read_only_protection_seconds':axes['elapsed_seconds'],'attempts':'One exact materialization, one authorized clone; no schema/tuple/stale issues or rejected applies. Initial oversized source display truncated; no claim of full source reading from that display; literal comparisons performed programmatically.','model_usage':'Root collects actual T0815 turn usage after all final responses; unobservable usage unknown, not zero'},'canonical_apply':'ROOT ONLY after both final SOURCE hashgates; exact one operation through supportedCLI; never replace database','canonical_comparison':'Readonly UNRUN all50 comparator permits only recorded_at difference of T-0815/accepted-material-identity-and-current-copy-v1; no data/order normalization','remaining_scope':'T0816 active planning; no T0817 execution, new originals, LIFE or ancestor mandate'}
p=S/'final-qualified-result-v1.json';assert not p.exists();p.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
paths={p for p in I.rglob('*')if p.is_file()and '__pycache__'not in str(p)and not p.name.startswith('final-manifest')}
paths.update([D/'primary-complete-source-design-v3.json',D/'independent-complete-source-design-gate-v1.json',D/'primary-literal-clone-source-gate-v1.json',D/'independent-literal-clone-source-gate-v1.json',D/'root-initial-clone-release-v1.json',D/'root-imported-helper-pin-supplement-v1.json',D/'root-actual-zero-requests-proof-v1.json',D/'primary-own-fourteen-criteria-v1.json',D/'independent-own-fourteen-criteria-v1.json',D/'root-both-own14-comparison-release-v1.json',D/'materialize-literal-v1.py',D/'preparation/locked-input-manifest-v2.json',R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py'])
for pin in load(D/'preparation/locked-input-manifest-v2.json')['files']:paths.add(R/pin['path']);assert sha(R/pin['path'])==pin['sha256']
pins=[{'path':str(p.relative_to(R))if p.is_absolute()else str(p),'sha256':sha(p),'bytes':p.stat().st_size}for p in sorted(paths,key=str)]
out=I/'final-manifest-v1.json';assert not out.exists();out.write_text(json.dumps({'task':'T-0815','stage_state':result['stage_state'],'stage_database':str(S/'stage.sqlite'),'stage_sha256':sha(S/'stage.sqlite'),'main_preimage_sha256':result['main_unchanged_sha256'],'operation':str(I/'operation-v1.json'),'operation_sha256':sha(I/'operation-v1.json'),'consequence_table':str(I/'consequence-table-v1.json'),'consequence_sha256':sha(I/'consequence-table-v1.json'),'qualified_result':str(p),'actual_requests':0,'canonicalApproval':False,'canonical_apply_root_only':True,'pins':pins},ensure_ascii=False,indent=2)+'\n');print(json.dumps({'manifest_sha256':sha(out),'pins':len(pins),'stage_sha256':sha(S/'stage.sqlite'),'result_sha256':sha(p)}))
