import {assessPartACore} from './part-a-core-assessment.mjs';
import{person,core,fact,event,relation,reuse,assertion,relationRow,save,origins,units,section,cs,record,add}from'./genealogy2-persons09-combined.mjs';
const p=person('P-0402','Hela akt/profil samt C0506/C0108 med sena rättelser lästa. Tre barnrader, fem hushållsrader; äldre formulering fyra barn på sidan motsägs av exakt avskrift. Johannes finns i separat1824post men inte hushållet, P0058 fortsatt kandidat. Bergvall hemvist är inte utläst födelseort. Avvecklad verklig person, ingen ny forskning.');
const full=[origins(p.person,'person',1,Math.max(...units(p.person,'person').map(u=>u.end_line)))];p.researchState={disposition:'retired',origins:[section(p,'Arbetsläge')],rationale:'PCD-2026-09-11-034; verklig separat person, avvecklad forskning.'};core(p,[section(p,'Identitet')],'Samtida födelse och hushåll binder Brita Greta. Pehrsdotter är projektets normalisering, ingen källform.');reuse(p,'IMPORT-P-0402',full);
const birth=['E-birth-P-0402','EP-E-birth-P-0402-P-0402-child','O-P-0146-C0506-Brita-Greta-birth','M-C0506-Brita-Greta-birth1821','ID-M-C0506-Brita-Greta-birth1821'].map(x=>reuse(p,x,['A-2303','A-2304','A-2305','A-7831']));
const household=['O-P-0146-C0506-child-Brita-Greta','M-C0506-Brita-Greta-household','ID-M-C0506-Brita-Greta-household','F-P-0146-household_membership-Bergvall-family','F-P-0146-residence-Bergvall','O-P-0146-C0506-child-Eric','O-P-0146-C0506-child-Anders','F-P-0146-church_participation-1824'].map(x=>reuse(p,x,['A-7833']));
const parents=['P-0146','P-0147'].map(x=>relation(p,x,p.person,'parent',['A-2305']));const mother=reuse(p,'O-P-0147-C0506-mother_age37',['A-2305']);
const names=fact(p,'name_form','source-versus-project',{source:'Brita Greta',household_prefix:'dott.',project_patronymic:'Pehrsdotter',patronymic_source_attested:false,search_only_variants:['Brita Margareta','Brita Margreta']},['A-2303']);
const bp=event(p,'baptism',{precision:'year',value:'1821',literal:'döpt1821; separat dag oläst'},['A-7832'],'Ingen säker dopdag eller fysisk dopplats. Prästvittne visar inte sakristia/prästgård.');
const raw=reuse(p,'O-P-0146-C0506-Brita-Greta-witnesses',['A-7832']);const witnesses=[];
for(const[k,name,role]of[['pastor','Sa[h]lin[?]','Pastor'],['second','Jo[.] Sa[h]lman[?]',''],['johan','Johan Jonsson','Bond:'],['wife-johan','Lisb[eta?]','Hu-stru[?]'],['olof','Ol[of] Jonsson','Bond:'],['wife-olof','','Hustru'],['stina','[.] Stina d:o','Pig:'],['joh','Joh: Jonsson','dr[än]g[?]']]){const m=add(p,`M-P-0402-C0506-witness-${k}`,'mention',{record_id:record('C-0506','födda1821'.replace('födda1821','födda 1821')),name_literal:name,role_literal:role},['A-7832',cs('C-0506')],[raw],'Ingen personidentitet eller släktskap. Namnlös hustru är egen källaomnämning; tom roll saknar separat råroll.','TRANSCRIBED','recorded');witnesses.push(m,add(p,`EP-E-baptism-P-0402-${k}-witness`,'participation',{event_id:bp[0],person_id:null,mention_id:m,role:'witness'},['A-7832'],[raw],'Läsreservationerna kvarstår; inga personkärnor.'));}
const limits=fact(p,'source_assessment','own-life-limits',{birth_date:'1821-04-21',birth_place_cell_unresolved:true,older_Bergvall_birth_cell_rejected:true,home:'Bergvall,Kyrko-Rotan',home_from_household_and_index:true,household_rows:5,household_children:3,older_four_child_rows_claim:false,own_household_day_blank:true,own_knowledge_examination_communion_blank:true,parents_communion_oct1824_not_own_life_anchor:true,own_survival_oct1824_not_independently_dated:true,whole_household_crossed:true,crossing_proves_move_or_death:false,annotations_column_unused_entire_spread:true,own_destination_unknown:true,own_death_unknown:true,Johannes_death_search_is_own_negative:false,own_occupation_finances_military_material_impossible_proven:false},full);
const candidate=fact(p,'kinship_hypothesis','P0058',{possible_brother:'P-0058',accepted_sibling:false,parentage_and_9versus19_March_unresolved:true,Johannes1824_belongs_to_separate_birth_record:true},full,'LEAD');p.changes.at(-1).disposition='candidate';
for(const[i,id]of['P-0146','P-0147'].entries())relationRow(p,id,[parents[i],mother,...household],'Föräldrars riktning och moderns uppgivna ålder.');relationRow(p,'son Eric',[household[5],household[3],limits],'Oregistrerad bror; ingen ny personkärna.');relationRow(p,'son Anders',[household[6],household[3],limits],'Oregistrerad bror; ingen ny personkärna.');relationRow(p,'P-0058',[candidate],'Kandidat, ingen syskonkant.');relationRow(p,'dopvittnena',[raw,...bp,...witnesses],'Åtta omnämnanden inom minst fyra vittnesparter, inga släktskap.');
assertion(p,'A-2303',[names,...birth,...household],'Namn i två poster, efternamn endast normalisering.');assertion(p,'A-2304',[...birth,limits,...household],'Datum står kvar; hemvistbelägg ger ingen säker faktisk födelseplats.');assertion(p,'A-2305',[...parents,mother,...birth],'Föräldrapar, stånd och ålder.');assertion(p,'A-7831',[birth[2],limits],'Ortcellen olöst, inga gissade alternativ.');assertion(p,'A-7832',[raw,...bp,...witnesses],'Hela vittnesblockets personer/roller och reservationer.');assertion(p,'A-7833',[...household,limits],'Rå rad och tomma fält; korrigerar avskriftens tre barn mot aktens fyra.');
p.pending.push({origin:'A-7833',question:'C0506s fullständiga tabell har fem rader, två vuxna och tre barn Eric/Anders/Brita Greta, medan akt/profil säger fyra barn på sidan. Den fjärde Johannes finns bara i separat1824post; äldre formulering bevaras och sakbedömningen räknar tre.'});assessPartACore(p);save(p);
