import json,hashlib,datetime,pathlib
base=pathlib.Path('evaluations/T-0826')
m=json.load(open(base/'primary/blind-source-manifest-v2.json'))
notes=[
'''Full spread examined with headings and neighbouring entries 9–11, enlarged. Entry 10: Augusta Viktoria, born Juni 24, baptized Juni 28, female mark; father Ersson Johannes, Hem. Egare, Bjerg; mother Jonsdotter Maja Greta; residence fol18; mother age39. Witnesses Sjö[n?] Anders, korporal vid [Sventå?], following woman Svensdotter Britta Maja [Stina?] från [T...]; precise witness suffixes uncertain. Special notes, church-taking and absolution blank on own row. IMPORTANT row alignment: Rotte Eric, Soldat i Attby and Svensdotter Cajsa Lisa belong to next child Johan (12 July), not Augusta. The initial reduced image could mislead by vertically offset parent lines; enlarged full row corrects that before candidate exposure.''',
'''Full fol134 headers and household rows1–9 inspected. Djursätra Vesterg. Head Per Wilhelm Eliasson, Hemmansegare, 1850 3/8 Värsås; wife Augusta Viktoria Johansson 1863 24/6 Kyrkefalla; shared marriage brace 1885 29/6. Son Bernhard Natanael1886 19/4 Värsås, daughter Agnes Maria1889 14/6, son Johan Martin Gabriel1891 1/3, son Ragnar Wilhelm1893 2/4, daughter Rut Ingegärd Margareta1896 6/12, son Ivar Alvar Elias1901 23/6, daughter Alva Viktoria1904 12/9. Later children's birthplaces ditto Värsås. Family's own inbound columns blank. Outbound for couple reads Vapptorp? 1916 22/4, repeated for wife; exact place must be checked against sharper crop before canonical use. Bernhard has military339[1906], and absence annotation dated1/4 not securely transcribed here. Religious marks and crossing-out present, not negative identity evidence; no own parents stated for wife.''',
'''Full SCB1886 Värsås annex birth extract headers read; row14 enlarged. Bernhard Natanael born April19, male legitimate marks; father Eliasson, Per Wilhelm, [hem.eg.] i Djursätra Vesterg.; mother Johansson, Augusta Viktoria (1år), age22; baptism date1/5 with notation in name area. Mother's married-status mark present. Own special-notes area blank; adjacent row13 attestation must not attach to14. This is a copy/extract, not independent of parish registration.''',
'''Full census1890 page23 header and bottom household inspected. Per Wilhelm Eliasson1850, Hemmansegare, birth-place ditto from Värsås above; h. Augusta Viktoria Johansson1863 Kyrkefalla Skarab.; s. Bernhard Natanael1886 and d.Agnes Maria1889, birthplace ditto Värsås. Household brace groups these four. Married/sex marks in own columns; no parents for Augusta. Census-derived repetition is not independent evidence from household chain.''',
'''Full Bygdeå1913 death/burial spread and row39. Died Maj23; Barbro Kristina Olofsdotter, änka e.f.Hem.Eg.Anders Andersson, Jomark. Born1830 14/2; female/widow marks. Congregation-book page1130. Cause ålderdomssvaghet (linewrap ålderdoms / svaghet); buried Juni8. Different death locality blank. Special note interpreted [Widén?] officiant, unsure spelling. No own parents named. Age/date/name/spouse/place form adult continuity anchor, not birth-original proof.''',
'''Full Bygdeå marriage1860 spread, June19 /5/7 row enlarged (the first numeric19 is June day in left date column, not safely an entry number). Bondesonen A.Andersson ifrån [N...?] af Rickattnet, born1835; Hemmansegarinnan B.C.Olofsdr i Jomark, born1830. Consent: B[n?] Pehr Isaksson i Jomark & skriftligt medgifvande af [farbrodern?] B[n?] C.E.Lundberg i [L...]; Föräldrarne döda. Betyg om hinderslöshet m.m.af kyrkoherden Nordenstam. Officiant Löfling. Larger exact relationship word before C.E.Lundberg appears farbrodern, but first interpretation carries uncertainty; no Olaus name in this record. Bride initials do not state full forenames. Parents unnamed/dead claim must not identify parents by itself.''',
'''Full Kungsholm1888 act172 including header, both parties and bottom prior-children table. Stationskarlsförmannen Olaus Fredriksson Fredberg and Jungfrun Johanna Charlotta Jansson. Declaration Stockholm16Nov1888, witnesses Aug.Sandin stationskarl and A.F.Bondell? stationskarl. Olaus: Lundby, Elfsborgs län;1852 4/9; incoming Alnö1876 14/6; Kungsholm; kristendom försvarlig, frejd medborgerlig, nattvardsgång [förut]; koppor mark; previously married Brita Stina Svensdotter; widower11/8 86; Stockholm RR probate13/11 88; address37 Fleminggatan. Johanna: Skånela Stockholms län,1866 [18?]/10; from Clara1888 10/10; unmarried, frejd medborgerlig, communion [förut], other applicable former-marriage blanks/dashes. Banns18,25Nov and2Dec; marriage9/12 88 by v.comm.Sch...; certificate27/12 88. Widower's children from former marriage explicitly: son Robert Nicolaus born Kungsholm7/6 78 baptized8/7; son Johannes Ivar24/4 80 baptized20/7; daughter Freda Elisabeth29/1 83 baptized26/2; daughter Ruth Fredrika7/2 85 baptized10/4; all Kungsholm. Baptism numerals need precision check before native dates. No Olaus parents stated despite Fredriksson name.''',
'''Available1880 census image is a crop without its header, upper/lower page edges clipped. Named household Olaus Fredberg stationskarl1852 Lundby Elfsb.; h.Brita Stina1853 Alnö; s.Robert Niklas1878 ditto Stockholm from register layout; s.Johannes Ivar1880 same. Own sex/marriage column marks visible but labels unavailable in crop, so do not infer exact numbered column meanings from crop alone. Household relationship prefixes explicit. Page-wide title/locator comes from manifest, not visible internal heading.''',
'''Full Ljustorp1854 marriage page17 headers, row8 and right continuation enlarged. Banns Juni25 and Juli9; married Juli16. Drängen Henrik Henriksson i Lagfors, age23; Pigan Margaretha Charlotta Sjölin ibm, age28; prior marriages blank/dash. Bride consent Förmyndaren Lars Olofsson i Löfberg, lemn.munt.bifall. No father named; guardian is not a biological father. Amount12, officiant [E...] Bergman. Own remarks blank. Both spouse places specifically Lagfors.''',
'''Full Ljustorp C3 1860 spread viewed; target is second Erik Jonas, distinct from preceding Erik Jonas son of Carl Olof. Own row born23 January; adjacent left date29? (uncertain raw digit); in narrow gutter baptism24/2 appears, precise header unavailable on this spread. Name Erik Jonas; Torp.Henr.Henriksson i Lagfors, H[ustru] Marg.Charl.Sjölin, mother34. Witnesses Torp.Joh.[Alb.?] Berg, h[ustru] Margaretha Berg at Lagfors Bruk; [skogs...] Anders Berg; pigan Joh.Elina Henriksdotter ibm; båtsman A.Wiklund i Sanna; pigan Erika Henriksdotter i [Gå?]åker. Witness suffixes and raw date readings remain uncertain, not relation evidence. Father and mother link clear.''',
'''Full Lagfors AI9 fol222, top household, right-page continuation and lower ErikJonas row read. Torp.Henrik Henriksson1829 10/8 Lagfors; wife Margretha Charlotta Sjölin1825 12/8 Stockholm; shared marriage54 16/7; son NilsAndreas Henriksson1867 21/2 Ljustorp, military annotation Inskr.88 Icke... uncertain lastword. Henrik crossed out; death84 15/3 at right edge of leftpage. No own parents in this household. Lower Arb.Erik Jonas Henriksson1860 23/1 Ljustorp, incoming from221 [87?]10/11, note7[...]87; physical separation means relationship not made from row placement alone. Adult identity contextual corroboration, not own-birth proof.''',
'''Full AI4 Löfberg86 original plus Familia index. Original Barnh.flickan Margreta Charl.Schölin1825 13/8 (initial whole-image numeral uncertain, magnification reads13); married/coppor/inbound/outbound largely blank; reading marks, yearly entries1832–40 and communion1839/40. NilsLarsson1776 and MärthaOlofsdr1785 upper household; placement alone cannot assign biological parents. Familia index agrees1825-08-13, row008, entry1831/end1841; index is a reading of this original, not independent. No Stockholm birthplace in original own row.''',
'''Full pre-existing one-page barnhusrulla PDF rendered read-only to PNG, plus search-result screenshot. No2532, Margreta Charlotta Schölin; f.d.13Aug1825, ympad. Admitted1831 Juni21? (day uncertain:21 with15 beneath, preserve raw rather than choose). Årligt underhåll20. Hr90? Fadren FabriksArbetaren Jonas Scholin/Schölin (surname letter uncertain). Uppfostras af förre Bonden NilsLarsson i Löfberg Ljustorps socken, Westernorrlands län.1839 Aug [1?] upph.—f[ör?] ålder? last note uncertain. Afmönstrade quarterly columns blank. This gives named father for barnhus child, but adult-spouse continuity still requires linking evidence. Search screenshot shows1831 Schölin MargretaCharlotta2532; not independent of roll.''',
'''Full AI10 Lagfors264 r13–15, headings and right continuation enlarged. Crossing-out HenrikHenriksson heading; row14 MargretaCharlottaSjölin, inh.hjon,1825 12/8 Stockholm, marriage54 16/7, widow84; death01 19/4; fromGB222. Own frejd remarks blank; communion marks present. Row15 NilsAndreasHenriksson1867 21/2 [Ljustorp ditto], arb., outHolm95 13/12. Source explicitly19April1901, not replacement of conflicting death record until both read. Row13 is reference to deceased husband, not another live person.''',
'''Mofalla AI4(1862–76) fol18 1Roten Bjerg full page and first household. Head (egare/kyrkovärden) Eriksson Johannes1820 22/12 Kyrkefalla; wife replacement Eriksdotter KarinElisabeth1833 29/1, marriage1870 1/12; crossed-out firstwife Jonsdotter MajaGreta1824 28/9? (day/month uncertain), ibm, died1868 27/8. Children CarlJohan1850 19/7, EmmaCharlotta1854 27/11, AnnaSofia1857 9/6, HildaAugusta1861 19/[?] died1862 28/7, AugustaViktoria1863 24/6. Explicit brace 'mannens barn i1sta äktenskapet' includes Augusta; her birthplace ibm traceable to Kyrkefalla. MariaOlivia1872 20/2, VictorAlbin1874 23/11 Kyrkefalla. Children vaccine marks. Augusta own incoming/outgoing/remarks blank on this page. Relation context identifies Johannes as father; first-wife maternity supported context, but birth record directly names MajaGreta. Religious/year columns not continuous physical-presence proof.''',
'''Mofalla AI5(1876–90) fol18 Bjerg full page. Hemm.eg.Nämndem.ErikssonJohannes1820 22/12 Kyrkefalla and wife EriksdotterKarinElisabeth1833 29/1 ibm, marriage1870 1/12. Crossed-out children CarlJohan1850 19/7 (Kyrkefalla1879), EmmaCharlotta1854 27/11(Hjo1877), AnnaSofia1857 9/6(pag72,1881), AugustaViktoria1863 24/6 ibm. Brace 'mannens barn i1sta äktenskapet' includes Augusta. Her own frejd 'lysning'; outgoing Värsås24/9 83, certificate11; communion first date10/8 79? uncertain. MariaOlivia1872 20/2; VictorAlbin1874 23/11; ErnstJohan1877 1/3. No independent new own-parent pair for Augusta; continuation strongly connects source child to movement toward adult parish.''',
'''Lövånger AI7 Bodan fol68 full spread. Upper Olof Nilsson1786 and Catharina[... ]1781, daughter AnnaGreta1803 with 'attest fr Bygdeå1827', crossed out and 'till fol66'. Wife BritaChristina Johansdotter1791 1/7, marriage1828 22/6?; daughter BarbroCatharina1830 29/1 (day29, not14/2). Brita row1834 has 'död'; last margin smittk[oppor?]. Child own 1834/35 marks weak/ditto and no clear continuous-presence inference. Below independent households FredrikWidman/Margreta and NilsHög... etc; do not merge. This source does not say BarbroChristina and cannot alone connect1830 child to Jomark adult.''',
'''Lövånger AI7 Bodan handwritten fol66 verified, full spread. Lower target family LarsAndersson Lund...1801 6/7 fromfol64, wife AnnaMargretaNilsd[otter]1803 fromfol68, child AnnaStina1828 20/12? (date uncertain). Marriage1828 22/6?; brace 'flyttat till Umeå1829'. Surname of husband enlarged still not fully certain here. Reference pair and matching1803 permits AnnaGreta route to this married woman, no evidence from this row that she is parent of Barbro1830. Row occurs lower half, separate from upper AndersAndersson/Cajsa household. Read wholepage inclupper continuation to avoid stale location assumption.''',
'''Ljustorp BI1 incoming1850 full spread headers and entry12, own dittos and anchor11. Entry11 bruks... JonasBerg, from LagforsBruk to Lagforsby. Entry12 Drängen HenrikHenriksson; own origin do, destination do, male1/femaleblank. Date via current section Nov1 fromentry8, later entries until12 marked dash in datecol; entry13 Nov14 supplies next boundary. Thus incoming1850 Nov1 LagforsBruk→Lagforsby, origin inherited from row11, NOT Lögdö from prior unrelatedrow5. No birthdate or parents in this row, so identitylink to1829 adult depends contextual chain.'''
]
rows=[]
for r,n in zip(m['records'],notes[:14]):
 rr={k:r[k] for k in ['record_revision','source','locator']}; rr['media']=r['media'];rr['own_reading']=n;rr['status']='original read before primary candidate claims';rows.append(rr)
for r,n in zip(m['new_originals'],notes[14:]):
 rr=dict(r);rr.pop('reading',None);rr['own_reading']=n;rr['status']='original read before primary candidate claims';rows.append(rr)
for r in rows:
 for x in r.get('media',[r]):
  p=pathlib.Path(x['path']);actual=hashlib.sha256(p.read_bytes()).hexdigest();assert actual==x['sha256'],p
obj={'task':'T-0826','role':'independent original-first review','recorded_at':datetime.datetime.now(datetime.timezone.utc).isoformat(),'blindness':'Read only source-only manifests v1/v2, originals, task/normative instructions. No primary candidate decision files/current person claims/settled implementation opened. Task wording disclosed questions, not candidate reading. Manifest includes a Familia derivative and search-result locator, both treated as derivative evidence.','source_count':19,'legacy_records':14,'new_original_pages':5,'pending':'Two Rotman rawposts not yet provided/read; final candidates and semantic consequence search not yet assessed. This is no final approval.','method':'Full supplied images first, relevant rows/headers/dittos/blanks/margins plus magnification as needed. Unreadable details preserved as uncertainties, not invented. PDF skill used solely to render existing source for read-only inspection.','records':rows}
p=base/'independent/original-first-v1.json';p.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n');print(p,hashlib.sha256(p.read_bytes()).hexdigest())
