import json,pathlib,hashlib,importlib.util,time
R=pathlib.Path.cwd();D=R/'evaluations/T-0817';I=D/'implementation';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();start=time.monotonic()
def save(p,v):
 assert not p.exists();p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n')
sf=D/'primary-settled-seven-resolution-spec-v1.json';spec=json.load(open(sf));gate=D/'independent-settled-seven-resolution-design-gate-v1.json';assert sha(gate)=='7f83a14c3e6fd4bf1733cd86a35e48ddc229d1c36ae45629a4c818177cc0cd0e'
hp=R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py';s=importlib.util.spec_from_file_location('h',hp);h=importlib.util.module_from_spec(s);s.loader.exec_module(h);db=I/'stage485-v1/stage.sqlite';c=h.conn(db);assert h.state(c)=={'journal_head':485,'pending':7}
pending=[dict(x)for x in c.execute('select q.*from review_request q left join review_resolution r on r.request_id=q.id where r.request_id is null order by q.rowid')];assert [x['id']for x in pending]==[x['request']for x in spec['resolve']];assert spec['changes']==[]
contexts=json.load(open(I/'stage485-v1/actual-pending-contexts-initial.json'));rows=[];retains=[]
for q,rr,context,disp in zip(pending,spec['resolve'],contexts,spec['individual_source_dispositions']):
 assert context['request']==q;assert set(rr)=={'request','rationale'}and rr['rationale'];assert disp['request_id']==q['id']and disp['rationale']==rr['rationale'];old=h.native(c,q['affected_revision_id']);cur=h.native(c,h.current(c,old['object_id']));assert cur==old
 rows.append({'actual_full_context':context,'exact_native_resolution':rr,'current_native_retained':cur,'source_disposition':disp});retains.append({'request_id':q['id'],'revision_id':cur['id'],'old_native':cur,'source_disposition':'RETAIN_EXACT','rationale':rr['rationale']})
assert len(set(x['revision_id']for x in retains))==4
op={'id':'T-0817/seven-individual-dependency-retains-v1','actor':'Codex / settled Astra decisions','reason':'T-0817 AC3: seven individually source-reviewed dependency retains; no native fields or evidence bindings change. Controlled canonical apply remains root-only after exact SOURCE approval.','dependencyReviewVersion':2,'changes':[],'resolve':spec['resolve']};p=I/'seven-resolution-operation-v1.json';save(p,op)
table={'operation_sha256':sha(p),'source_spec':{'path':str(sf.relative_to(R)),'sha256':sha(sf)},'changes':[],'individual_request_consequences':rows,'retains':retains,'unique_retained_targets':4,'schema_preflight':{'changes_empty':True,'all_resolution_keys_exact':True,'ordered_actual_request_match':True,'all_full_native_targets_current_exact':True,'no_evidence_or_origin_changes':True},'elapsed_seconds':time.monotonic()-start};t=I/'seven-resolution-consequence-table-v1.json';save(t,table);save(I/'resolution-stage-preimage-pin-v1.json',{'path':str(db.relative_to(R)),'sha256':sha(db),'state':h.state(c)});print(json.dumps({'op':sha(p),'table':sha(t),'spec':sha(sf),'elapsed':time.monotonic()-start}))
