import json,pathlib,hashlib,time
R=pathlib.Path.cwd();D=R/'evaluations/T-0817';I=D/'implementation';S=I/'stage486-v1';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();load=lambda p:json.load(open(p))
assert sha(R/'genealogy2/data/research.sqlite')=='f73c9599c70b2938b581593c1250995122d79bfa4451e72be1e040cc6c339d0e';assert load(S/'actual-pending-full.json')==[]
for n in ['verify','verify-assets']:x=load(S/(n+'.json'));assert x['ok']and x['errors']==[]
x=load(S/'verify-source.json');assert x['ok']and x['problems']==[]
assert 'pass 18'in (S/'targeted-review-pedigree-tests.log').read_text()and 'fail 0'in(S/'targeted-review-pedigree-tests.log').read_text()
axes=load(S/'final-axis-OWNER-child-relation-proof-v1.json');assert axes['nonfocal_axes_full_exact']==535
peds={}
for pid in ['P-0269','P-0270']:
 x=load(S/(pid+'-pedigree.json'));assert not x['truncated'];peds[pid]={'paths':len(x['paths']),'truncated':x['truncated']}
result={'task':'T-0817','state':{'journal_head':486,'pending':0},'main_unchanged_sha256':sha(R/'genealogy2/data/research.sqlite'),'stage_sha256':sha(S/'stage.sqlite'),'literal_native_changes':47,'existing_revisions':45,'new_source_objects':2,'initial_full_native_retains':483,'dependency_resolution_requests':7,'dependency_unique_full_native_targets':4,'step_retains_not_unique_cumulative':490,'persons':536,'nonfocal_full_axes_exact':535,'only_focal_axis_differences':'See exact full differences in final-axis-OWNER-child-relation-proof-v1.json; SOURCE must qualify actual Brita backing revisions and identity/tree change, legacy fullcontract is not native LIFE.','OWNER45_fullnative_exact':True,'Johannes185_fullnative_exact':True,'relations22_fullnative_exact':True,'history44_and_order_exact':True,'default_pedigrees':peds,'validators':'verify/verify-assets/verify-source PASS','targeted_tests':'18/18 PASS','production':{'final_readers_seconds':load(S/'reader-capture-result.json')['elapsed_seconds'],'resolution_clone_seconds':load(S/'result.json')['elapsed_seconds'],'initial_clone_seconds':load(I/'stage485-v1/initial-result.json')['elapsed_seconds'],'preserved_mechanical_attempts':['final-native-package V1 filename pointed to nonexistent resolution V2; V2 corrects path without native mutation','axis protection V1 convenience decoded JSON mismatch; V2 compares both raw full native canonical databases exactly','initial native proof labels482/483 corrected solely to485/486 in proofV2 with explicit amendment'],'model_usage':'Root collects actual turn usage after all worker FINAL responses; unobservable usage unknown'},'canonicalApproval':False,'canonical_apply':'Root only, two exact supportedCLI operations; no database replacement','actual_comparator':'UNRUN; all50 and ordered arrays exact with ONLY two named operation.recorded_at timestamps normalized'}
p=S/'final-qualified-result-v1.json';assert not p.exists();p.write_text(json.dumps(result,ensure_ascii=False,indent=2)+'\n')
paths={f for f in I.rglob('*')if f.is_file()and '__pycache__'not in str(f)and not f.name.startswith('final-manifest')};paths.update([D/'preparation/locked-input-manifest-v2.json',D/'preparation/consequence-input-supplement-manifest-v1.json',D/'preparation/protected-native-review-snapshot-v1.json',D/'preparation/baseline484.sqlite',R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py'])
for f in D.glob('*gate*.json'):paths.add(f)
for f in D.glob('*release*.json'):paths.add(f)
paths.add(D/'primary-complete-source-design-v2.json');paths.add(D/'primary-settled-seven-resolution-spec-v1.json')
m={'task':'T-0817','stage_state':result['state'],'stage_database':str((S/'stage.sqlite').relative_to(R)),'stage_sha256':result['stage_sha256'],'main_preimage_sha256':result['main_unchanged_sha256'],'operations':[{'path':str((I/n).relative_to(R)),'sha256':sha(I/n)}for n in ['operation-v2.json','seven-resolution-operation-v1.json']],'qualified_result':str(p.relative_to(R)),'canonicalApproval':False,'pins':[{'path':str(f.relative_to(R)),'sha256':sha(f),'bytes':f.stat().st_size}for f in sorted(paths)]};out=I/'final-manifest-v1.json';assert not out.exists();out.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'manifest_sha256':sha(out),'stage_sha256':result['stage_sha256'],'pins':len(paths),'peds':peds}))
