import json,pathlib,hashlib,datetime
r=pathlib.Path('evaluations/T-0795/source-review');now=datetime.datetime.now(datetime.timezone.utc).isoformat()
x=json.loads((r/'primary-own-six-frozen-v1.json').read_text());x['utc']=now;x['independent_claims_seen']=True;x['amends']='primary-own-six-frozen-v1.json preserved; independent own-six-reading-v1.md read only after both freezes'
x['units'][3]['unopened_leads']=[{'title':'Ekonomiska kartan1935–1978','url':'https://geotorget.lantmateriet.se/dokument/projects/ekonomiska-kartan/released/2025.04/','source':'U4-1 search response','status':'UNOPENED DISCOVERY; no full service/original/map read; potential historical-designation alternative after dated place key and new decision'}]
x['units'][5]['unopened_leads']=[{'title':'Kulturnämnden protocol2016-12-08','url':'https://mellanarkiv-offentlig.vgregion.se/alfresco/s/archive/stream/public/v1/source/available/sofia/kun6111-136948837-125/surrogate','source':'U6-1 search response','status':'UNOPENED DISCOVERY; PDF snippet only; no original/personal record opened'},{'title':'Regionstyrelseprotokoll snippet mentions kulturnämnden2003-02-07 §18','url':'https://mellanarkiv-offentlig.vgregion.se/alfresco/s/archive/stream/public/v1/source/available/sofia/rs3878-551954431-5309/surrogate','source':'U6-1 search response','status':'UNOPENED DISCOVERY; search snippet, not independently checked date/role/person'}]
x['units'][5]['read']=x['units'][5]['read'].replace('bl.a.2016.','bl.a.2016-12-08 samt en2003ärendehänvisning.');x['units'][5]['conclusion']+=' Sökbara historiska uppslag2016 och2003 finns i söksvaret, men underliggande protokoll är olästa; resultatet får inte beskrivas som enbart nutid eller inga historiska uppslag.'
(r/'primary-own-six-amended-v2.json').write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
f=json.loads((r/'primary-literal-field-plan-v1.json').read_text());f['utc']=now;f['amendment']='v1 preserved; explicit unopened map/protocol leads retained after independent comparison.'
for row in f['rows']:
 if row['disposition']=='revise' and row['field']=='data.body' and row['object_id']=='THEME-P-0212-EKO':row['new']+=' U4:s söksvar visar också Ekonomiska kartan1935–1978 som oläst historisk kartingång; tjänsten och ingen Flobykarta har öppnats.'
 if row['disposition']=='revise' and row['field']=='data.body' and row['object_id']=='THEME-P-0212-SAM':row['new']+=' Sökningen visade olästa protokolluppslag2016-12-08 och en2003ärendehänvisning; de bevaras som uppslag, inte personbelägg eller full katalogläsning.'
 if row['disposition']=='revise' and row['field']=='data.body' and row['object_id']=='PATH-P-0212-KP-05':row['new']+=' Olästa uppslag bevaras också: U4 Ekonomiska kartan1935–1978 och U6 protokoll2016-12-08/2003ärendehänvisning; inga nya original har öppnats.'
(r/'primary-literal-field-plan-v2.json').write_text(json.dumps(f,ensure_ascii=False,indent=2)+'\n')
# Source-bound full native specification, awaiting mechanical media staging and operation integration.
entries=json.loads((r/'entry-ledger-v2-reserved12.json').read_text())['entries'];changes=[];media=[]
providers={'U1':'Riksarkivet — katalogmetadata om Stockholms inskrivningsområde','U2':'Falköpings kommun — Kommunens arkiv','U3':'LIBRIS — bibliografiska metadatafrågor','U4':'Lantmäteriet — Ta del av allmän handling','U5':'Skatteverket — Bouppteckning och kopieringsrouting','U6':'Västra Götalandsregionen — metadatafråga och prövad institutionsadress'}
old=json.load(open('evaluations/T-0795/preparation/complete-current-history-support-native.json'))['objects']
def b(k,role='supports'):
 oid,version=k.rsplit('@',1);return {'object':oid,'version':int(version),'role':role,'note':'Exakt versionsbundet underlag; metadata är inte personlig händelse eller ny oberoende röst.'}
def c(id,kind,data,evidence=[],caveat='',bindings=None):
 z={'id':id,'kind':kind,'expectedVersion':None,'disposition':'recorded','evidenceStatus':None,'rationale':'T-0795 AC2–4: bevarar exakt bounded metadata-/åtkomstprov2026-10-06, två ingångar för denna enhet; inga personoriginal.','caveat':caveat,'data':data,'origins':[],'evidence':evidence}
 if bindings:z['bindings']=bindings
 return z
for u in x['units']:
 unit=u['unit']; sid='S-T0795-'+unit;rid='R-T0795-'+unit+'-metadata';qid='SEARCH-T0795-'+unit;pid='PATH-P-0212-T0795-'+unit
 es=[e for e in entries if e['unit']==unit]
 bundle={'task':'T-0795','unit':unit,'source_time_field':u['source_time_field'],'entries':es,'captured_inputs':{p:json.loads((r/p).read_text()) if p.endswith('.json') else (r/p).read_text() for p in u['evidence']},'scope_note':'RAW source/tool data only. Search-return PDF snippets were never opened as original records. Full selected HTML text may differ from indexed search copy. Transport attempts are same reserved URL.'}
 path=r/(unit+'-raw-source-bundle-v1.json');path.write_text(json.dumps(bundle,ensure_ascii=False,indent=2)+'\n');sha=hashlib.sha256(path.read_bytes()).hexdigest()
 media.append({'record_id':rid,'path':str(path),'sha256':sha,'provenance':f'T-0795 {unit}; exakt två reserverade generiska metadataingångar2026-10-06, verktygsfrågor/fullrelevantåtergivning/transportfel med UTC. Ej personlig originalhandling; raw manifest4b0898d3 och entryledger kontrolleras.','region':unit+' två metadataingångar, hela bevarade svar och uttryckliga läsgränser'})
 changes.append(c(sid,'source',{'title':providers[unit],'archive_reference':'SE/KrA/0473/B/01' if unit=='U1' else None,'source_class':'metadata','description':u['source_time_field']+'. Daterad metadataingång2026-10-06. Verktygen återger katalog/guide/sökrespons; leverantören och namngivna arkiv/post är källor. Ingen personoriginalkälla.'},caveat=u['limits']))
 changes.append(c(rid,'record',{'source_id':sid,'record_type':'bounded_metadata_access_probe','locator':json.dumps({'unit':unit,'date':'2026-10-06','entries':es,'raw_bundle_sha256':sha},ensure_ascii=False),'dependence_note':u['read']+'\nLäsgräns: '+u['limits']+'\nWebbsökningens indexerade text och samma sidas fulltext är inte oberoende källor. Verktygsfel skiljs från faktisk HTTPstatus; hämtat är inte läst personoriginal.'},[b(sid+'@1')],u['limits'],{sid:1}))
 outcome={'U1':'inconclusive','U2':'positive','U3':'inconclusive','U4':'positive','U5':'positive','U6':'inconclusive'}[unit]
 scope={'description':u['source_time_field'],'query':[e['args'] for e in es],'bounds':{'entry_count':2,'total_task_count':12,'unit6_all_organizations_total':2 if unit=='U6' else None,'date':'2026-10-06','person_query':False,'personal_original_read':False,'queries_not_exhaustive':True},'raw_bundle_sha256':sha,'unopened_leads':u.get('unopened_leads',[])}
 changes.append(c(qid,'search',{'question_id':'P-0212/Q-02','source_id':sid,'scope_json':scope,'outcome':outcome,'body':u['read']+'\n'+u['outcome']+'\n'+u['limits']},[b(rid+'@1')],u['limits']))
 body='T-0795 '+unit+', metadataåtkomst2026-10-06. '+u['source_time_field']+'\n\nLäst/prövat: '+u['read']+'\n\nBedömning: '+u['conclusion']+'\n\nSaknad nyckel: '+u['missing_key']+'\nAnskaffningsväg/ägare: '+u['acquisition']+'\n\nGräns: '+u['limits']+'\nUppdragets två ingångar är använda. Fortsatt utförande utöver nämnda redan beslutade T0359/T0362-scope är EJ BESLUTAT UTFÖRANDE och kräver nytt avgränsat beslut. T0767 behåller separat sina exakt två äldre åtkomstmål. Task-DONE är inte person-/källslut.'
 if u.get('unopened_leads'):body+='\n\nOlästa uppslag, inte sakbelägg:\n'+json.dumps(u['unopened_leads'],ensure_ascii=False,indent=2)
 ev=[b(rid+'@1'),b(qid+'@1')]+[b(z,'context') for z in u['retains']]
 changes.append(c(pid,'assessment',{'subject_id':'P-0212','criteria':'source_path/1','outcome':u['outcome'],'body':body},ev,u['limits']))
output={'task':'T-0795','utc':now,'status':'source-approved specification pending independent package review; NOT apply-ready until media staged','changes':changes,'media_to_stage':media,'rules':['Sol uses stage-media for exactly six raw bundles; bind resulting mediaIDs to corresponding record. No source refetch.','Record dependence_note preserves full relevant metadata reading; raw bundles preserve entire tool response. No personal mention/observation/event/fact created.','Original C0906fact remains unchanged. Six new paths reference stronger older person support as context only.','Rebind any evidence whose referenced head changes in same operation only after returning exact version pair for Astra decision.']}
(r/'native-six-spec-v2.json').write_text(json.dumps(output,ensure_ascii=False,indent=2)+'\n')
for name in ['primary-own-six-amended-v2.json','primary-literal-field-plan-v2.json','native-six-spec-v2.json']:print(name,hashlib.sha256((r/name).read_bytes()).hexdigest())
