import json,pathlib,datetime,hashlib
r=pathlib.Path('evaluations/T-0795/source-review');p=json.load(open('evaluations/T-0795/preparation/complete-current-history-support-native.json'))['objects']; units=json.loads((r/'primary-own-six-frozen-v1.json').read_text())['units']
rows=[]
def change(key,field,new,why,basis):
 x=p[key]; old=x['data'][field] if field!='caveat' else x[field]
 assert old!=new
 rows.append({'object_id':x['object_id'],'version':x['version'],'revision':key,'field':('data.'+field if field!='caveat' else field),'disposition':'revise','old':old,'new':new,'rationale':why,'evidence':basis})
def append(key,field,s,why,basis):change(key,field,p[key]['data'][field]+s,why,basis)
def replace(key,field,oldfrag,newfrag,why,basis):
 old=p[key]['data'][field];assert old.count(oldfrag)==1,(key,old.count(oldfrag));change(key,field,old.replace(oldfrag,newfrag),why,basis)
def refs(*ns):return [f'PATH-P-0212-T0795-U{n}@1' for n in ns]
summary='T-0795:s metadataresultat2026-10-06: U1 kandidatarkiv Stockholms inskrivningsområde1902–1969, men full katalog CAPTCHA och Gunnars rätta område okänt; U2 kommunarkivets institutionella skolrouting verifierad, exakta skolserier/år/digitalåtkomst okända; U3 två avgränsade bibliografiska prov utan relevant utgåva, inget generellt matrikelnoll; U4 full fastighetsbeteckning behövs och inskrivningshandlingar före2008-06-01 hänvisas till Riksarkivet; U5 Skatteverket för eventuell bouppteckning2017, tjänsteformulär/personlig handling ej prövade; U6 ingen relevant före2017katalog fastställd inom två ingångar, Liberalerna/FN separat oprövade.'
base=p['PATH-P-0212-KP-05@2']['data']['body'];prefix=base[:base.index('Möjliga kompletterande ingångar:')]
new=prefix+'\n\n'+summary+' Se PATH-P-0212-T0795-U1–U6 för exakt källa, datum, fält, sökfråga, åtkomstfel och anskaffningsväg. Två ingångar per enhet, tolv totalt; inga personposter lästa. C0906:s daterade fakta består.\n\nKvarvarande nycklar: U1 hemvist/inskrivningsnummer och jurisdiktion omkring1953; U2 skolarkivbildare/serie/år och tjänsteår; U3 verifierad relevant utgåvetitel/utgivare1950–1980; U4 daterad adress/plats, historisk fastighetsbeteckning och aktreferens; U5 aktuell tjänsteingång/identifieringskrav; U6 riktig katalogingång, mandatperiod/lokalavdelning och medaljens eventuella registerägare2008. T0359 äger endast nästa Lidingöbok1718–1719 plus högstettregister, T0362 endast sin befintliga ägarfrågelista1951–1967; möjliga nycklar därifrån antas inte redan finnas. T0767:s två äldre åtkomstpassager består. Övrigt fortsatt metadata-/personutförande är EJ BESLUTAT UTFÖRANDE och kräver nytt avgränsat beslut; beställning/kontakt har separat mandatgräns. Taskresultatet är metadata, inte personlig källuttömning.'
change('PATH-P-0212-KP-05@2','body',new,'Ersätter registrerat framtida T0795 med utförd boundedmetadata och precis kvarvarande nycklar utan personpåståenden.',refs(1,2,3,4,5,6))
change('PATH-P-0212-KP-05@2','outcome','Daterade metadata-/åtkomstprov2026-09-06 och2026-10-06; partiell institutionsrouting, specificerade olösta nycklar/åtkomstfel; inga personnoll.','Uppdaterar åtkomstläge men förklarar ingen källväg uttömd.',refs(1,2,3,4,5,6))
replace('P-0212/Q-02@2','body','T-0795 äger sex specificerade metadatafrågor för kvarstående routing, högsttvå ingångar perenhet och tolv totalt.',summary+' De sex separata PATH-P-0212-T0795-U1–U6 bevarar exakt prövat omfång och återstående nycklar. Ingen personlig livslucka har därigenom fyllts.','Frågans STÖDD består; utförda metadata syns utan nya personfakta.',refs(1,2,3,4,5,6))
change('THEME-P-0212-ARB@2','body','ARB ÖPPET. Yrkesbanan från barnens minnesord består: lärarutbildning, studierektor på Flobyskolan och senare rektor på Fredriksbergskolan. Lärosäte, examensår och tjänstedatum saknas fortfarande. C0906:s fyra daterade NAD-frågor gav ingen relevant skolarkivserie. T0795 U2 verifierar kommunarkivets generella ansvar för nuvarande kommun sedan1974 och införlivade kommuner från1863, med skolhandlingar men utan de två skolornas exakta seriesignum eller digitala tjänsteakter. U3 identifierade ingen relevant matrikel1950–1980 i sina två specificerade prov; API-nollet saknar positivkontroll och bevisar inte matrikelfrånvaro. Se PATH-P-0212-T0795-U2/U3 för exakta nycklar och åtkomst. Ingen anställnings-/utbildningspost läst.','För in generisk skolrouting och begränsat bibliografiskt resultat utan ändrat yrkesfaktum eller temautfall.',refs(2,3))
change('THEME-P-0212-EKO@2','body','EKO ÖPPET. Ingen egen egendom, inkomst eller skuld är belagd i granskat underlag. C0906:s lagfartsprov1875–1933 täcker inte ett möjligt Flobyförvärv på1960-talet. T0795 U4 verifierar Lantmäteriets guide: full fastighetsbeteckning behövs, Min karta anges som beteckningsingång och inskrivningshandlingar registrerade före2008-06-01 hänvisas till Riksarkivet. Daterad adress/plats och historisk beteckning/aktreferens saknas. U5 verifierar Skatteverkets ansvar för bouppteckningar från2001-07-01; eventuell2017handling är varken sökt, beställd eller belagd. Den länkade tjänstens inbäddade komponent var inte läsbar som aktuellt formulär. Exakta resultat/anskaffningsvägar i PATH-P-0212-T0795-U4/U5. Ingen fastighet eller bouppteckning antas finnas för Gunnar och ingen universell analogspärr eller fri digital originalåtkomst fastställs.','Byter otestad institutionsrouting mot läst guide; personfrågorna kvarstår.',refs(4,5))
change('THEME-P-0212-MIL@2','body','MIL ÖPPET. Ingen militärtjänst är belagd. Omkring1953 är en planeringshypotes från födelseår1933, inte en inskrivningshändelse. C0906:s daterade katalogprov består i sitt omfång. T0795 U1 gav MCP-katalogträff Stockholms inskrivningsområde SE/KrA/0473/B/01,1902–1969, hos Riksarkivet i Täby/Krigsarkivet. Full detaljkatalog ledde till CAPTCHA och blev inte läst. Lidingöankaret1951 fastställer inte Gunnars hemvist/inskrivningsområde1953. Exakt hemvist/nummer/jurisdiktion och serie-/volymtäckning återstår; se PATH-P-0212-T0795-U1. T0359:s egna nästa hushållspassage eller T0362:s redan avgränsade adressfråga kan tillföra nyckel men inga resultat antas. Ingen personlig post, tjänst eller hälsouppgift har undersökts.','Kandidatarkiv och åtkomstfel hålls skilda från rätt personlig jurisdiktion.',refs(1))
append('THEME-P-0212-SAM@1','body','\nT0795 U6 prövade2026-10-06 två metadataingångar totalt: generisk VGR-sökning och en institutions-URL som gav HTTP404. Ingen relevant full katalog-/guidepost för före2017 lästes. Nämndens mandatperiod, föreningarnas lokala avdelning/period och eventuell medaljregisterägare2008 är fortsatt okända; Liberalerna/FN fick inga separata nya prov. Felet gäller endast vald URL, inte arkivens existens. Se PATH-P-0212-T0795-U6.','Bevarar personunderlag och fulla okända uppdragsfält; tillför bara utfört metadataomfång.',refs(6))
replace('BIO-P-0212@6','markdown','Faktisk åtkomst och relevanta alternativ är fortsatt oprövade i de preciserade återstående delarna.','T0795:s tolv metadataingångar2026-10-06 preciserar institutionell routing till kommunarkivet, Riksarkivet för äldre inskrivningshandlingar och Skatteverket för eventuell bouppteckning2017; de löser inga personliga livsfrågor. Rätt inskrivningsområde, exakt skolserie, relevant matrikelutgåva, fastighetsbeteckning och uppdragens katalog-/lokalnycklar är fortsatt olösta inom angivna prov. De sex aktuella resultaten PATH-P-0212-T0795-U1–U6 bevarar åtkomstfel och nästa saknade nyckel.','Syntesen får aktuell metadataåtkomst utan biografisk utfyllnad.',refs(1,2,3,4,5,6))
replace('KEY-P-0212-0767ee81003f@2','body','kommunens faktiska åtkomst är inte prövad','kommunarkivets generella institutionsrouting är verifierad i T0795 U2 men exakt skolserie/år och digital tjänsteaktåtkomst är fortfarande inte fastställda','Arbetsgivarnycklarna består; skiljer utförd guide från oläst skolserie.',refs(2))
replace('CONTRACT-P-0212-PK-06@2','body','T0359/T0362/T0795 äger sina exakta återstående omfång.','T0359/T0362 behåller sina exakta omfång. T0795:s sex metadataresultat tillför partiell routing och precisa olösta nycklar; inga tema- eller PK-utfall uppgraderas av dessa prov.','STYRKT betyder utförd individuell temabedömning, inte uttömd källtillgång.',refs(1,2,3,4,5,6))
replace('CONTRACT-P-0212-PK-08@2','body','Tillgång, alternativ och kunskapsvärde återstår att sakligt avgränsa, utan påstådd nätåtkomstgaranti eller krav på omedelbar beställning. Ingen väg utförs i T0790.','T0790 öppnade inga nya källor. T0795:s sex senare metadataresultat ger verifierad partiell institutionsrouting men lämnar exakt personområde/skolserie/matrikel/fastighet/tjänsteingång/föreningsnyckel olösta i angivet omfång. Se PATH-P-0212-T0795-U1–U6 för lästa guider och precisa hinder/anskaffningsvägar. Ingen personlig post är läst; nätåtkomst garanteras inte och beställning/kontakt följer inte automatiskt. PK08 förblir EJ STYRKT.','Synliggör begränsad förbättring medan substantiella personluckor och separata uppdrag består.',refs(1,2,3,4,5,6))
append('CONTRACT-P-0212-PK-12@1','body','\nT0795-metadataamendment2026-10-06: ovanstående2026-09-08bedömning är historiskt daterad. Den gamla KP05-beställningsformuleringen är inte ensam nuvarande återaktiveringsväg: sex metadataresultat med exakta nycklar/åtkomstfel finns i PATH-P-0212-T0795-U1–U6. Fortsatt avgränsad metadata- eller originalpassage kräver nytt beslut; beställning/kontakt kräver sitt särskilda mandat. STYRKT, identitetsgrind och ursprungligt granskningsomfång ändras inte.','Bevarar historisk bedömning men hindrar att gamla beställningsvillkoret blir exklusivt aktuellt hinder.',refs(1,2,3,4,5,6))
# Each changed object's complete caveat retained with explicit metadata amendment.
changed=list(dict.fromkeys(x['revision'] for x in rows))
for key in changed:
 x=p[key];why='T-0795 2026-10-06: Endast avgränsad metadata-/åtkomstamendment. Äldre daterade T0790-/C0906-läsgränser förblir historiska; denna revision tillför enbart här specificerade metadataresultat. Ingen ny personlig originalpost eller ändrad identitet, OWNER-uppgift, relation, tema-/PK-/livsbildsgrind följer. Fulla råsvar, fel och ingångstak finns i T0795:s källposter.'
 change(key,'caveat',x['caveat']+'\n\n'+why,'Explicit amendment skiljer nya metadata från äldre daterat inget-nytt-original-förbehåll.',[])
retains={
'F-P-0212-source_access-C0906@1':'Daterat2026-09-06prov med uttrycklig begränsningscaveat bevaras; nya prover får egna record/path, inte omdaterad historik.',
'ASSESSMENT-T0790-P0212-life@1':'Uttryckligt daterad befintligmaterialgranskningT0790; failed och ursprungliga kriterier består. U1–U6 löser inte PK03/04/08. Uppdragshänvisningarna läses i sitt historiska granskningsomfång.',
'ASSESSMENT-P-0212@2':'Legacy helkontrakt UNDERKÄND samt explicit godkänd identitet/BÄRANDE oförändrade; inga nya personbelägg.',
'F-P-0212-occupation-school-career@1':'Minnesordens yrkessekvens har starkare personbundet stöd än generisk kommunarkivguide; inga tjänstedatum tillkom.',
'F-P-0212-education-teacher@1':'Ingen relevant matrikelutgåva eller utbildningspost lästes; tidigare utbildningsuppgift och datumreservation består.',
'F-P-0212-award-Karl-Staaff2008@1':'Medalj2008 enligt minnesord bevaras; U6 säger inget nytt om utdelare eller individuell utmärkelse.',
'F-P-0212-civic_role-obituary@1':'Personligt uppdragsstöd från minnesord består; lokalavdelning och mandatperiod fylls inte genom routing.',
'O-P-0212-C0901-own@2':'Fullt accepterade minnesord återbrukas som samma barnens röst; metadata är ingen korrigering eller ny oberoende personröst.',
'F-P-0212-name-owner-confirmed@1':'Ägarens namnordning har explicitOWNER_CONFIRMED och relevantPCD; ingen metadata kan ändra den.',
'F-P-0212-name_form-source_comparison@2':'Dokumentär namnordningskonflikt berörs inte av generiska namnlösa metadatafrågor.',
'F-P-0212-source_reference-Lidingo1951@2':'Gunnars egen1719hänvisning består som exakt framtidaT0359nyckel; katalogträffen visar inget1953boende.',
'F-P-0212-event_place-Floby@1':'Minnesord1967/ägarens mitten av1960-talet bevaras; karta eller äganderätt har inte verifierats.',
'E-death-P-0212@1':'Befintligt dödsdatum används endast som årsrouting; SKVguide ger ingen ny döds- eller bouppteckningshändelse.',
'CONTRACT-P-0212-PK-03@1':'1951–1962boende-/utbildningskedja fortsatt oläst; metadata fyller ingen livslucka.',
'CONTRACT-P-0212-PK-04@2':'Vigselförsamling/nätverk fortfarande olösta; dataminimering och relationer består.',
'CONTRACT-P-0212-PK-10@1':'Sakligt korrekt källkritisk biografi kan förbli STYRKT med rent metadataamendment; inget personinnehåll ändras.'}
for key,why in retains.items():
 x=p[key];rows.append({'object_id':x['object_id'],'version':x['version'],'revision':key,'field':'data + disposition + evidence_status + rationale + caveat + evidence + origins','disposition':'retain','old':x,'new':x,'rationale':why,'evidence':['primary-own-six-frozen-v1.json']})
# Changed object scalar outcomes are explicitly retained individually apart from the source-path access outcome.
for key in changed:
 if key=='PATH-P-0212-KP-05@2':continue
 x=p[key]
 if 'outcome' in x['data']:
  val=x['data']['outcome'];rows.append({'object_id':x['object_id'],'version':x['version'],'revision':key,'field':'data.outcome','disposition':'retain','old':val,'new':val,'rationale':'Metadata ändrar inte detta objekts personbundna sak-/kontraktsutfall; se dess individuella bodydisposition och fortfarande olösta nycklar.','evidence':[z for row in rows if row['revision']==key for z in row.get('evidence',[]) if str(z).startswith('PATH-')]})
out={'task':'T-0795','utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'primary_frozen_sha256':'c128f8b5a4c9d99b8b5557b96b161c28b25c5e80f5c47a34f67ca8f08b881687','status':'Primary source disposition proposal; independent comparison and exact native implementation pending','rows':rows,'implementation_rules':['Use exact full old/new field values; unexpected match/version returns to Astra.','All unrelated object data, disposition/evidence_status, prior evidence/origins and order preserved. Existing evidence remains; add only specified supporting result paths after record bindings.','No revision of historical C0906 evidence or generic personal facts.','Do not regrade complete90T0790scope. Sol should report additional current semantic matches beyond this focused source list for Astra disposition.','Dependent review requests require exact individual retains/revisions on staged operations; no invented request IDs.','Stable proposed six result IDs PATH-P-0212-T0795-U1 through U6. S/R/search schema mechanics belong to Sol; source claims exactly frozen units.']}
f=r/'primary-literal-field-plan-v1.json';f.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');print(len(rows),len(changed),hashlib.sha256(f.read_bytes()).hexdigest())
