import json,pathlib,sqlite3,hashlib,datetime,copy
r=pathlib.Path('evaluations/T-0795');s=r/'source-review';stage=r/'preparation/reviewed-stage-v1'
def read(p):return json.loads(p.read_text())
def pin(p):return {'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
op=read(stage/'operation-media-bound.json');db=sqlite3.connect('file:'+str(stage/'stage.sqlite')+'?mode=ro',uri=True);db.row_factory=sqlite3.Row;checks=[]
for req in op['changes']:
 oid=req['id'];n=dict(db.execute('select * from current_revision where object_id=?',(oid,)).fetchone());data=dict(db.execute('select * from '+n['kind']+' where revision_id=?',(n['id'],)).fetchone());data.pop('revision_id');data={k:json.loads(v) if k.endswith('_json') and isinstance(v,str) else v for k,v in data.items()}
 actual={'id':oid,'kind':n['kind'],'expectedVersion':n['version']-1 or None,'data':data,'disposition':n['disposition'],'evidenceStatus':n['evidence_status'],'rationale':n['rationale'],'caveat':n['caveat'],'origins':[{'unit':x['unit_id'],'coverage':x['coverage'],'note':x['note']} for x in db.execute('select * from origin where revision_id=? order by rowid',(n['id'],))],'evidence':[{'object':x['basis_revision_id'].rsplit('@',1)[0],'version':int(x['basis_revision_id'].rsplit('@',1)[1]),'role':x['role'],'note':x['note']} for x in db.execute('select * from dependency where revision_id=? order by rowid',(n['id'],))]}
 expected=copy.deepcopy(req);bindings=expected.pop('bindings',{})
 for k,v in [('origins',[]),('evidence',[]),('evidenceStatus',None),('caveat','')]:expected.setdefault(k,v)
 for k in data:expected['data'].setdefault(k,None)
 if n['kind']=='record':
  actual['assets']=[{'path':x['asset_path'],'region':x['region']} for x in db.execute('select * from record_asset where revision_id=? order by rowid',(n['id'],))];actual['media']=[{'id':x['asset_id'],'region':x['region']} for x in db.execute('select * from record_media where revision_id=? order by rowid',(n['id'],))];expected.setdefault('assets',[]);expected.setdefault('media',[])
 assert expected==actual,oid
 for b,v in bindings.items():assert data['source_id']==b and any(e['object']==b and e['version']==v for e in actual['evidence']),(oid,b,v)
 checks.append({'id':oid,'native_projection_exact':True,'request_bindings':bindings,'typed_source_version_dependency_verified':bool(bindings) if n['kind']=='record' else None})
requests=read(stage/'actual-pending-full-after-stopped-stage.json');assert len(requests)==7
rationales={
'THEME-P-0212-ARB@3':'U2 verifies only institution-level school archive routing and U3 gives no relevant edition; neither supplies education/service dates or personnel records. Dated T0790 ARB open and life failed remain correct; new current ARB@3 carries actual2026-10-06metadata, while life review retains historical ARB@2 evidence.',
'THEME-P-0212-EKO@3':'U4 supplies pre2008RA routing/property-key requirement and U5 custody after2001, not property, probate existence, wealth or income. Old EKO@2 open and failed review remain valid for its dated scope; new EKO@3 supplies current limitedmetadata and unselected map lead.',
'THEME-P-0212-MIL@3':'U1 candidate Stockholms area/captcha establishes no personal area, enrolment or service. Old MIL@2 open remains substantive correct, with actual access attempt in MIL@3; life review retains its older dated source binding.',
'THEME-P-0212-SAM@2':'U6 generic result and exact URL404 supply no mandate/localbranch/medal record; unselected2016/2003leads do not fill personalfields. Dated SAM@1 open and failed life remain correct; current SAM@2 adds only boundedmetadata.',
'BIO-P-0212@7':'BIO@7 changes only final access synopsis, not biographical facts or missing1951–1962chain. Dated T0790 PK10-STYRKT based on BIO@6 and failed overall remain defensible; retain old binding as historicalreview rather than silently redate it.',
'CONTRACT-P-0212-PK-06@3':'PK06@3 keeps STYRKT for individually assessedten themes; only updates T0795 ownership/probe result, not personalcoverage. Dated life review PK06 conclusion and oldPK06@2 binding retained.',
'CONTRACT-P-0212-PK-08@3':'PK08@3 keeps EJ STYRKT: precise metadata routing improved but personal/access keys and T0359/T0362 needs persist. Dated life failed from PK03/04/08 remains warranted, retaining oldPK08@2 binding. No original passage or reviewgradechange.'}
res=[]
for q in requests:
 assert q['affected_revision_id']=='ASSESSMENT-T0790-P0212-life@1';why=rationales[q['changed_revision_id']];res.append({'request':q['id'],'decision':'retain','rationale':'T-0795 individuell SOURCE-prövning: '+why,'affected_revision':q['affected_revision_id'],'changed_revision':q['changed_revision_id']})
x={'task':'T-0795','utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'gate':'PRIMARY SOURCE APPROVES REQUEST-ONLY BINDINGS PROJECTION AND SEVEN INDIVIDUAL RETAINS; NOT FINAL CANONICAL GATE','pins':[pin(stage/'operation-media-bound.json'),pin(stage/'literal-default-discrepancy-diagnostic-v1.json'),pin(stage/'actual-pending-full-after-stopped-stage.json')],'approved_comparison_semantics':'bindings is an input-only version constraint consumed by apply; native payload has no bindings column. For precisely six R-T0795-U1–U6-metadata request projections only, omit request bindings from reconstructed-native equality AFTER checking actual record.source_id and exact source@1 dependency. Keep original request and journal unchanged. All35 other fields/metadata/origins/evidence order/media compare exactly after existing null/empty defaults; independently SQLchecked.','checks':checks,'resolutions':res,'continuation':'Continue readonly stage checks and separately controlled seven-retain operation on existing458clone after independent concurrence/rootrelease. No secondapply of35changes, no requestrewrite and no mainwrite.','remaining_possibilities':'No concrete new execution decided. Final T0795 checkpoint may retain six exact EJ BESLUTAT UTFÖRANDE possibilities with owner/root subsequent bounded decision. T0359 twohushåll+maxoneregister, T0362 original1951–1967ownerquestions, T0767 originaltwoURLs unchanged; none expands to absorb remaininggenericroutes.'}
p=s/'primary-stage-projection-seven-retains-v1.json';p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n');print(pin(p))
