import json, hashlib
from pathlib import Path

B = Path('evaluations/T-0784')
P = B / 'mechanical-current442-preparation-v2'
def read(p): return json.loads(Path(p).read_text())
def pin(p): return {'path':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()}
inputs = read(P/'all21-current-PK-full-native-and-three-assessment-relation-inputs-v1.json')
native = read(P/'complete-three-current-history-upstream-native-dictionary-v1.json')['objects']

reasons = {
'P-0211': {
'01': ('passed', 'Datum, namngivna föräldrar, Storbränna och den ägarförankrade familjekopplingen till Kristina bär samma Evy. C0240 och familjeunderlaget används inom sin egen räckvidd. C0935 rad13 har reserverade namn- och dagtecken och används inte som en självständig exakt bekräftelse av 12 januari. Ingen konkurrerande person har framkommit i det befintliga relevanta underlaget.'),
'02': ('passed', 'Egen person och föräldra-/barnrelationer är åtskilda från observationer och den äldre granskningsstatusen. Storbränna är föräldrarnas boställe; C0240:s nedkomstortsnot och reserverad C0239-byuppgift likställs inte med detta. Ingen ny privat familjeuppgift tillförs.'),
'05': ('passed', 'C0240 första posten nr1 är fullutvunnen med rubriker, egna småfält och marginalnot genom T0674. C0935 fol388 rader6–13 är fullgranskade genom T0675 till uttryckliga teckengränser. Råreservationerna är prövade läsosäkerheter, inte kvarvarande olästa kolumner. Övriga familjeposter i T0214 är inte därigenom lästa eller automatiskt nödvändiga för Evys identitetsnivå. För denna privata person tillämpas den redan motiverade integritetsminimeringen; vidare bred familjeinsamling krävs inte.'),
'07': ('passed', 'Evy Åsa Kristina, födelsedatumet, föräldranamn, Storbränna och familjenamnet Höök bevaras som tids- och källbundna söknycklar. Höök ger inget nytt juridiskt namnbytesdatum; C0935:s råalternativ fylls inte från C0240.'),
'09': ('passed', 'Familjeuppgift, SCB-post och församlingsbok korreleras med beroenden redovisade. SCB och kyrkobok räknas inte utan vidare som två oberoende röster. Ägarens C0239-precisering reserverar fysisk bytolkning; de begränsade C0141-söknollen görs inte till fullständig frånvaro. Ingen relevant olöst identitetskonflikt döljs av ortnormalisering.'),
'11': ('passed', 'T0674 har bevarat C0240:s fulloriginal med SHA256 d94106481afe0db77a02e0e43ae600955b0ee5d2c7d2f4c65fa7f3e7085dfbd9, exakt avskrift och rättelsekedja. T0675:s C0935-audit binder de fulla fälten och reservationerna. Den äldre frånvaron av full C0240-bild är historiskt åtgärdad; den får inte räknas som aktuell proveniensbrist.'),
'12': ('passed', 'Denna daterade individuella omprövning skiljer sju identitetskrav från livsbild och privata teman. Äldre UNDERKÄND/AVVAKTAR och dess skäl bevaras historiskt men ersätts för den aktuella identitets-/trädaxeln. Återöppning krävs vid konkret motstridig person-/föräldrauppgift eller belagd felbindning i de namngivna källorna, inte genom rutinmässig omläsning av tillräckligt underlag.')},
'P-0003': {
'01': ('passed', 'Arne Godvig Jansson binds från egen födelse1915-02-21 och modern Ada via morföräldrahushåll, vigseln1938-05-15 och den senare namngivna familjen. Ottilia-alternativet förblir avvisat. Bernhard är separat OWNER_CONFIRMED far och behöver inget nytt arkivbevis; den tomma faderscellen varken upphäver eller är nytt stöd för ägaruppgiften.'),
'02': ('passed', 'Källobservation, nuvarande personkorrelation och äldre kontraktsutfall hålls åtskilda. Arnes sonrelation stöds av de namngivna familjeuppgifterna och senare egna rader, inte av C0005 som ny fadersuppgift. Bärande accepterade relationer och deras bevisstatus behålls.'),
'05': ('failed', 'C0008 nr10, C0034 nr16, C1047 familjerader12/13/15 och C0910 fol914 är redan fullständigt hanterade till sina prövade teckengränser genom T0677, T0778, T0676 och tidigare T0129. Dessa gamla brister återöppnas inte. En annan exakt rest kvarstår: den egna C0882-posten132 i Södertälje B I/11 s279,24/11 1943 hänvisar till församlingsbokens uppslag15. Den hänvisade familjeradens egna namn-/familjeställnings-, in-/överförings- och fortsättningsfält är ännu inte lästa; den direkta hänvisningen hör till den redan använda registreringskedjan. S0689 visar en äldre kataloggräns för analog AIIa1936–61, inte att rätt volym/personrad eller alla rimliga åtkomstalternativ har prövats. Resterande handling får därför inte deklareras uttömd. Gemensam åtgärd med Maj via befintligt T0379; Arnes T0227 får återbruks-/konsekvenshänvisning. Ingen ny1951källa eller barndomslucka1923–30 tas in som ytterligare identitetskrav.'),
'07': ('passed', 'Fullständigt namn, födelsedatum, Ada/morföräldrar, vigsel, maka och senare adresser är konkreta personnycklar. Värnpliktsnummer ger inte tjänstgöringsdatum, adress inte ägande och ett katalogiserat uppslag inte läst innehåll. Den analoga uppslag15-restens åtkomstgräns redovisas uttryckligt i den nya prövningen.'),
'09': ('passed', 'Administrativa led och sonens olika texter räknas inte som oberoende röster av bara antal. Registrering hos Ada/morföräldrar daterar inte faktisk omsorg; 638/30 löser inte1923–30. Hertig Karls väg42 i minnet mot40 i register kvarstår som livsuppgiftsavvikelse, inte en styrkt omnumrering eller konkurrerande person. Ägarbekräftad Bernhard-relation och arkivbelagd Ada-relation bevaras var för sig.'),
'11': ('passed', 'Befintliga T0677- och T0778-audits binder fulla C0008/C0034/C1047-underlag. T0676:s aktuella C0910-protokoll och C19-gravkortsaudit återbrukas med rätt läsdatum och bilder/HTML-hashar. Den saknade äldre gravkopian är inte den aktuella bevarade Sept20-kopian. Ingen ny bildläsning eller självständig evidensröst påstås; den olästa uppslag15-passagen har egen angiven gräns och är inte ett förlorat redan läst original.'),
'12': ('passed', 'Sju krav bedöms individuellt nu. Identiteten är sakligt etablerad, men den kvarvarande direkta uppslag15-hänvisningen lämnar PK05 underkänd och trädverkan avvaktande. Återaktivering kräver antingen full relevant egen familjerad eller dokumenterad verklig åtkomstgräns med prövade relevanta alternativ och förnyad sakbedömning. Inte hela T0227/T0228 eller en full livsbild behöver slutföras för en ny identitetsprövning.')},
'P-0007': {
'01': ('passed', 'Maj/May Amalia Eriksson/Ekholm/Jansson/Ekholm-Jansson korreleras genom1920-05-11Hyltinge, Hulda Ålund, bokförd far Axel Edvard, hushållskedja och vigsel/familj. C0019 innehåller endast födelseår och är inte en sjunde exakt datumröst. Flera fadersnoteringar kan vara samma administrativa kedja. Ingen konkurrerande person eller nytt fadersalternativ förs in.'),
'02': ('passed', 'Egen källroll, atomära påståenden och aktuella bärande relationer hålls isär från legacygrind. Senare barnrelationer har redan CORROBORATED stöd genom namngivna familjerader; h.f. ensam görs inte till biologisk moder. Ett tomt eller reserverat kolumntecken fylls inte från närstående.'),
'05': ('failed', 'C0028/C0034 samt Flen860/720/932 är redan fullständigt hanterade till dokumenterade gränser; C0932:s v/k/n och andra osäkra tecken är inte automatiskt olästa. Egna Södertäljeuppslag15 och egna mantalsrader1945–46 återstår däremot i den uttryckligt utpekade befintliga registreringskedjan. Uppslag15 delas med Arnes C0882-hänvisning; Maj namnges inte i själva inflyttningspost132, varför korrelationen vilar på den övriga egna familjekedjan. C0883:s1945s96/1946s104 gäller Arne, inte verifierade sidor för Maj. T0379 äger den gemensamma uppslagspassagen en gång och Majs egna registerrader; ingen garanti om innehåll eller inloggning räcker för analog AIIa.'),
'07': ('passed', 'Befintliga namnformer, födelse, föräldrar, giftermål och ort-/registernycklar är användbara inom sina egna tider. KEY:s utsaga att exakta datumet upprepas i sju poster ska rättas till sju korrelerade poster där C0019 bara anger år. PATH-KP05 ska skilja kända manssidor från ännu olokaliserade egna1945–46-rader och analog AIIa från digitala AIIc-serier. Dessa två exakta följdrättelser ingår i bedömningens förutsättning; ingen ny originaltolkning behövs.'),
'09': ('passed', 'Barnets ursprungliga post, senare hushåll och egna vuxenrader ger samstämmig korrelation med beroenden synliga. Fadersanteckningar räknas inte automatiskt som tre oberoende vittnen. Gravkortets hemort/gravegenskaper är inte dödsplats, och fol16-rutten är uttryckligt historiskt ersatt av rad16 på uppslag13. Familjeidentiteten är inte underkänd bara för att fullutvinnings-/provenienskrav återstår.'),
'11': ('failed', 'Den aktuella egna gravkortskopian är bevarad genom AUDIT-T0676-20 och ska återbrukas; äldre saknad gravkopia är historisk. C0973:s originalkedja har däremot kvar en konkret relevant bevarandebrist: Helgesta fol744 rad10 används för Hulda Margaretas gemensamma föräldrar och därmed Majs syster-/familjesamband men bildkopian har inte bevarats enligt nuvarande PK11. T0237 äger bevarandet; den avgränsade relevanta744-passagen är nödvändig här, inte ett automatiskt krav att först göra all forskning på moderns fyra folier. Inga bilder återhämtas i T0784.'),
'12': ('passed', 'Daterad prövning redovisar etablerad identitet men underkända PK05/11 och waiting för antavlan. Återöppning av grinden kräver den avgränsade T0379-passagen eller sakligt prövad källgräns samt relevant C0973/744-proveniens hos T0237. Helgestas övriga livslinje, systerns ännu olästa egen födelsepost och hela moderns bredare uppdrag är inte automatiska villkor. Äldre granskning och livsbild bevaras; två aktuella nyckel-/åtkomstfel rättas i det avgränsade paketet.')}
}

supports = {
'P-0211':['RESEARCH-P-0211-9d76f0343410@3','TR-614bc4a80513645992b9beda@2','AUDIT-T0675-SATTNA388-44@1','TR-T0674-owner-clarification-20260918@1','REL-parent-P0241-P0211@2','REL-parent-P0246-P0211@2','REL-parent-P0211-P0210@1'],
'P-0003':['RESEARCH-P-0003-9d76f0343410@1','AUDIT-T0677-C0008@1','TR-T0677-C0034-consolidated-control@1','AUDIT-T0778-C1047-family@1','AUDIT-T0676-FLEN914-UPPER-45@1','READ-02e7b9de11767690e1314c91@1','AUDIT-T0676-19@1','R-18122baf2db2f6c17eda5082@2','S-0689@1','REL-parent-P0010-P0003@1','REL-parent-P0009-P0003@1','REL-parent-P0003-P0005@1'],
'P-0007':['RESEARCH-P-0007-9d76f0343410@3','TR-T0677-C0034-consolidated-control@1','AUDIT-T0677-C0033-row2@1','AUDIT-T0676-20@1','R-ab847c1960d02f28801419b3@1','R-18122baf2db2f6c17eda5082@2','S-0689@1','R-3c84f3b9ebdf5ce77e63fe20@1','R-51c053d56cc1a32d26231525@1','REL-parent-P0015-P0007@1','REL-parent-P0016-P0007@1','REL-parent-P0007-P0005@1']}

rows=[]
for person,decisions in reasons.items():
    for pk,(grade,why) in decisions.items():
        inp=inputs[person]['seven_PK_full_current']['PK-'+pk]
        rows.append({'person':person,'requirement':'PK-'+pk,'current_revision_id':inp['revision_id'],'whole_current_native':inp['native_payload'],'current_and_previous_full_person_equal':True,'grade':grade,'source_bound_reason':why,'support_revision_ids':supports[person],'native_disposition':'Retain this dated legacy requirement exactly; new identity_review/1 carries this explicit current individual judgment. No automatic conversion of legacy outcome.','independent_T0784_exposure_before_freeze':False})
for rs in supports.values():
    for r in rs: assert r in native,r
obj={'task':'T-0784','phase':'primary_source_meaning_frozen_before_independent_comparison_not_package_approval','scope_person_ids':list(reasons),'new_originals_read':0,'new_external_sources_fetched':0,'independent_T0784_judgments_seen':False,'MAIN_pin':{'path':'genealogy2/data/research.sqlite','sha256':'42321e363573c243597aded458e6a10d2d6cd8e4be47da02a227b149bbaed45f'},'input_pins':[pin(P/'all21-current-PK-full-native-and-three-assessment-relation-inputs-v1.json'),pin(P/'complete-three-current-history-upstream-native-dictionary-v1.json')],'reading_scope':'All21 whole current PK bodies/caveats/rationale/evidence plus three current identity arguments and bearing relations; exact prior wholePerson views equal fresh442. Necessary source audits/transcriptions/retained source texts reused. Not a full1214-native reread; no new original reading.','individual_21':rows,'person_outcomes':{'P-0211':{'identity_review':'passed','tree_effect':'supporting','failed_requirements':[]},'P-0003':{'identity_review':'failed','tree_effect':'waiting','failed_requirements':['PK-05']},'P-0007':{'identity_review':'failed','tree_effect':'waiting','failed_requirements':['PK-05','PK-11']}},'required_current_copy_corrections':['KEY-P-0007-bf37119ff18f@1 data.body exactdate-count','PATH-P-0007-KP-05@1 data.body own-page/access scope'],'preservation':'All existing person/relationship acceptance/evidence states, OWNER_CONFIRMED Bernhard, rejected Ottilia, old legacy reviews, complete life-picture states and lower-priority task scopes remain. New native reviews override only current identity/tree criterion.','next_unperformed_step':'Bind root AC1 release and exact immutable six review API specifications plus two current-copy fields. Independent comparison only after own freeze; no candidate or runtime approval in this document.'}
out=B/'source-review/primary-current-21-individual-requirement-and-three-outcome-freeze-v1.json'
assert not out.exists()
out.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n')
print(json.dumps(pin(out)))
