"""One exact root-authorized same-stage resolution command; never canonical/newstage."""
import json,hashlib,shutil,sqlite3,datetime,subprocess,importlib.util,traceback
from pathlib import Path
ROOT=Path(__file__).resolve().parents[3];B=ROOT/'evaluations/T-0781';S=B/'exact16-fresh-stage-v1';W=S/'actual17-resolution-apply-v1';AUTH=B/'root-one-exact17-same-stage-resolution-authorization-v1.json'
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def pin(p):return {'path':str(Path(p).relative_to(ROOT)),'sha256':sha(p)}
def load(p):return json.loads(Path(p).read_text())
def check(p):path=ROOT/p['path'];assert pin(path)==p;return path
assert sha(AUTH)=='adcf363aca2c7b7d3bcb650443aac3b7efae913980359ae665461108162ba6b7';a=load(AUTH);assert a['authorization']=='ONE_EXACT_SAME_STAGE_RESOLUTION_APPLY_ONLY' and a['root_authorized'] is True and a['canonical_apply_authorized'] is False and a['snapshot_authorized'] is True and a['retry_or_second_stage_authorized'] is False
for k,v in a.items():
 if k.endswith('_pin') and isinstance(v,dict) and set(v)=={'path','sha256'}:check(v)
helper=B/'implementation/stage_exact_two_settled_package_v2.py';assert sha(helper)=='ce9c424a2f1f36748880e15c83b44e4aa8aa407ab627ee723bf7c90b6b709ce2';spec=importlib.util.spec_from_file_location('readonly_native_stage_functions',helper);h=importlib.util.module_from_spec(spec);spec.loader.exec_module(h)
db=check(a['stage_DB_pin_before']);main=check(a['main_pin']);op_path=check(a['resolution_operation_pin']);op=load(op_path);assert op['dependencyReviewVersion']==2 and op['changes']==[] and set(op)=={'id','actor','reason','dependencyReviewVersion','changes','resolve'};assert len(op['resolve'])==len({r['request'] for r in op['resolve']})==17
assert db.resolve()==(S/'stage.sqlite').resolve() and db.resolve()!=main.resolve();assert (ROOT/a['journal_path']).resolve()==(S/'journal').resolve();command=['node','genealogy2/cli.mjs','apply',a['resolution_operation_pin']['path'],'--db',a['stage_DB_pin_before']['path'],'--journal',a['journal_path']];assert command==a['CLI_command_template'];assert not W.exists();W.mkdir()
c=h.conn(db);live=h.conn(main);before=h.state(c);assert before==a['expected_actual_before']=={'journal_head':441,'pending':17};assert h.state(live)=={'journal_head':425,'pending':0};pending=[dict(r) for r in c.execute('select * from pending_review order by id')];assert [r['id'] for r in pending]==[r['request'] for r in op['resolve']];assert c.execute('select count(*) from operation where id=?',(op['id'],)).fetchone()[0]==0
all_before=h.all50(c);live_before=h.all50(live);current_before=[dict(r) for r in c.execute('select * from current_revision order by object_id')];protected=load(S/'protected42-before.json');assert len(protected)==42
for rid,n in protected.items():assert h.current(c,n['object_id'])==rid and h.native(c,rid)==n
c.close();snapshot=(ROOT/a['immutable_original_stage_before_byte_snapshot_path']).resolve();assert snapshot.parent==S.resolve() and not snapshot.exists() and snapshot!=db.resolve() and snapshot!=main.resolve();shutil.copyfile(db,snapshot);assert sha(snapshot)==a['stage_DB_pin_before']['sha256'];assert pin(db)==a['stage_DB_pin_before']
def save(n,x):return h.write(W/n,x)
save('authorized-original-stage-byte-preservation-and-actual-before-proof-v1.json',{'authorization_pin':pin(AUTH),'original_stage_pin':pin(db),'preservation_snapshot_pin':pin(snapshot),'byte_equality':True,'preservation_only_not_newstage':True,'actual_before':before,'CLI_calls':0});save('all50-stage-before-v1.json',all_before);save('all50-main-before-v1.json',live_before);save('all17-actual-pending-before-v1.json',pending)
receipt={'authorization_pin':pin(AUTH),'operation_pin':pin(op_path),'argv':command,'before':before,'CLI_invocations':0,'started_at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat()}
try:
 assert sha(AUTH)=='adcf363aca2c7b7d3bcb650443aac3b7efae913980359ae665461108162ba6b7' and pin(db)==a['stage_DB_pin_before'] and pin(main)==a['main_pin'];receipt['CLI_invocations']=1
 try:
  process=subprocess.run(command,cwd=ROOT,capture_output=True,text=True);(W/'one-exact-apply.stdout.json').write_text(process.stdout);(W/'one-exact-apply.stderr.txt').write_text(process.stderr);receipt['exit_code']=process.returncode
 finally:
  c=h.conn(db);receipt['after']=h.state(c);c.close();receipt['actual_DB_pin_after']=pin(db);save('one-actual-before-after-CLI-apply-receipt-v1.json',receipt)
 assert process.returncode==0,('One apply failed',process.stderr);out=load(W/'one-exact-apply.stdout.json');assert out['operation']==op['id'] and out['unchanged'] is False and out['changes']==0;assert receipt['after']==a['expected_after']=={'journal_head':442,'pending':0}
 c=h.conn(db);after=h.all50(c);assert after['schema']==all_before['schema'];changed={t for t in after['tables'] if after['tables'][t]!=all_before['tables'][t]};assert changed=={'operation','operation_payload','review_resolution'};assert after['ordered_native_arrays']==all_before['ordered_native_arrays'];assert [dict(r) for r in c.execute('select * from current_revision order by object_id')]==current_before
 for rid,n in protected.items():assert h.current(c,n['object_id'])==rid and h.native(c,rid)==n
 stored=[dict(r) for r in c.execute('select rowid as native_rowid,* from review_resolution where operation_id=? order by rowid',(op['id'],))];assert [(r['request_id'],r['rationale']) for r in stored]==[(r['request'],r['rationale']) for r in op['resolve']];assert len(stored)==17
 journal=dict(c.execute('select * from operation_payload where operation_id=?',(op['id'],)).fetchone());assert json.loads(journal['request_json'])==op and journal['sequence']==442
 old=h.conn(snapshot)
 for table in ['operation','operation_payload','review_resolution']:
  limit=old.execute('select max(rowid) from '+table).fetchone()[0];assert h.rows(c,table,True,limit)==h.rows(old,table,True)
 old.close();pool=load(S/'complete-actual-target-request-history-upstream-native-payloads.json');assert len(pool['objects'])==398
 for rid,n in pool['objects'].items():assert h.native(c,rid)==n
 target=load(S/'all174-actual-full-native-targets-and-exact-API-bindings.json');assert len(target['objects'])==174
 for rid,n in target['objects'].items():assert h.native(c,rid)==n
 c.close();save('all50-stage-after-v1.json',after);respin=save('all17-stored-exact-individual-resolution-rows-in-rowid-order-v1.json',stored);proofpin=save('only-three-review-journal-tables-appended-and-all47-native-current-history-metadata-order-exact-v1.json',{'before_pin':pin(W/'all50-stage-before-v1.json'),'after_pin':pin(W/'all50-stage-after-v1.json'),'actual_changed_tables':sorted(changed),'all_three_existing_rows_and_rowid_prefixes_exact':True,'all47_other_entire_tables_exact_includingderivedsearch':True,'all_current_revision_records_exact':True,'ordered_evidence_origins_assets_media_exact':True,'protected42_full_current_native_exact':True,'all398_full_current_history_upstream_native_payloads_equal_prior_stage':True,'all174_actual_native_API_targets_equal_prior_stage':True,'all17_stored_resolution_literals_order_exact':True,'stored_resolution_pin':respin,'entire_stored_request_json':journal,'submitted_API_exact_no_defaultaddition':True})
 validators=[]
 for name,args in [('verify',['verify']),('verify-assets',['verify-assets']),('verify-source',['verify-source']),('inventory',['inventory']),('pedigree-verified-P0269',['pedigree','P-0269'])]:
  output=W/(name+'.json');result=h.run_cli(args+['--db',str(db)]+(['--journal',str(S/'journal')] if name!='pedigree-verified-P0269' else []),output)
  if name.startswith('verify'):assert result['ok'] is True
  validators.append(pin(output))
 assert h.all50(live)==live_before and h.state(live)=={'journal_head':425,'pending':0} and pin(main)==a['main_pin'];assert sha(snapshot)==a['stage_DB_pin_before']['sha256'];original_auth=load(B/'root-exact16-fresh-sequential-clone-stage-authorization-v1.json')
 for p in original_auth['media_pins']:check(p)
 for k,v in a.items():
  if k.endswith('_pin') and k!='stage_DB_pin_before' and isinstance(v,dict) and set(v)=={'path','sha256'}:check(v)
 c=h.conn(db);final=h.state(c);c.close();assert final==receipt['after'];mp=check(a['final17_membership_pin']);membership=load(mp);assert len(membership['operations'])==17;assert membership['operations'][-1]['sha256']==a['resolution_operation_pin']['sha256'];steps=[{'operation_id':load(S/f'step-{i:02}-actual-before-after.json')['operation_id'],'expected_before':load(S/f'step-{i:02}-actual-before-after.json')['before'],'expected_after':load(S/f'step-{i:02}-actual-before-after.json')['after'],'actual_step_receipt_pin':pin(S/f'step-{i:02}-actual-before-after.json')} for i in range(1,17)];steps.append({'operation_id':op['id'],'expected_before':before,'expected_after':final,'actual_step_receipt_pin':pin(W/'one-actual-before-after-CLI-apply-receipt-v1.json')});steppin=save('all17-final-package-actual-ordered-step-before-after-state-index-v1.json',{'final17_membership_pin':pin(mp),'steps':steps,'actual_final_state':final,'no_state_counts_inferred':True});resultpin=save('complete-final442-zero-pending-exact17-resolution-stage-handoff-v1.json',{'task':'T-0781','authorization_pin':pin(AUTH),'actual_state':final,'final_stage_DB_pin':pin(db),'original_stage441_snapshot_pin':pin(snapshot),'final17_proposal_pin':a['final17_proposal_pin'],'final17_membership_pin':a['final17_membership_pin'],'actual_all17_step_state_index_pin':steppin,'resolution_operation_pin':pin(op_path),'one_actual_CLI_receipt_pin':pin(W/'one-actual-before-after-CLI-apply-receipt-v1.json'),'stored17_resolution_pin':respin,'all50_exact_preservation_and_request_json_proof_pin':proofpin,'all398_native_context_pin':pin(S/'complete-actual-target-request-history-upstream-native-payloads.json'),'all174_native_API_pin':pin(S/'all174-actual-full-native-targets-and-exact-API-bindings.json'),'protected42_pin':original_auth['protected42_pin'],'validator_pins':validators,'main_all50_unchanged_pin':pin(W/'all50-main-before-v1.json'),'main_pin':pin(main),'actualCLIcount':1,'newnativechanges':0,'evidencerebinds':0,'canonical_apply':False,'programacceptance':False,'final_source_and_independent_exact_resolvedstage_gates':'PENDING','actual_worker_usage':'Rootcollects afterworkerfinal, unavailablehere notzero.'});print(json.dumps({'final_handoff_pin':resultpin,'actual_state':final,'final_stage_DB_pin':pin(db),'exact_all50_review_resolution_proof_pin':proofpin,'actual17_step_state_index_pin':steppin},indent=2))
except BaseException as e:
 c=h.conn(db);actual=h.state(c);c.close();save('failure-stop-actual-state-no-retry-v1.json',{'error_type':type(e).__name__,'error':str(e),'traceback':traceback.format_exc(),'actual_state':actual,'stage_DB_pin':pin(db),'CLIinvocations':receipt['CLI_invocations'],'no_retry_no_newstage_no_canonical':True});raise
finally:live.close()
