from pathlib import Path
import json,statistics,datetime,re
b=Path(__file__).resolve().parent;s=json.loads((b/'summary.json').read_text());rs=json.loads((b/'results.json').read_text());aux=json.loads((b/'auxiliary-measurements.json').read_text());root=json.loads((b/'orchestration-usage.json').read_text());models=['gpt-6-astra','gpt-5.6-sol','gpt-5.6-terra','gpt-5.6-luna'];labels=dict(zip(models,['Astra','Sol','Terra','Luna']));lookup={(r['task'],r['model']):r for r in s}
text='''# Modelltest i slaktforsk – T-0769\n\nGenomfört 2026-09-19: **60 försök**, fem nya subagentkontexter per\nX/Y/Z × Astra/Sol/Terra/Luna. Alla använde `medium`, identiska frysta\nuppgiftspaket per uppgift och samma verktyg. Inga omförsök eller\nrättningsrundor. Ordinarie forskning förblev pausad.\n\n## Rekommenderad arbetsfördelning\n\n- **Astra för svår originaltolkning.** Den enda modellen som klarade hela\n  bildpaketet. Sol var inte ett tillförlitligt billigare alternativ här.\n  Bevara riktad andra läsning och kontroll av rad-/kolumngränser även med Astra.\n- **Astra för slutlig följdprövning där bevarande av befintlig kunskap är\n  avgörande.** Y visar en skillnad i helhetsbevarande, men modellrankningen\n  drivs starkt av ett enda fall. Använd inte detta som allmän bevisning för\n  att billigare modeller saknar genealogisk analysförmåga.\n- **Sol för genomförande av fastställda ändringsbeslut med automatisk\n  införselkontroll.** Samma godkända andel som Astra i Z, cirka34%lägre\n  beräknad kandidatkostnad. Det är den tydligaste omedelbara besparingen\n  utan sänkt godkänd andel i detta test.\n- **Terra är en kandidat för mekaniska paket med exakt specificerade\n  strängar och automatisk validering.** Alla fem Z-paket var sakligt rätt\n  bortsett från en extra titelpunkt. Inför inte en generell normalisering\n  av källtitlar; nästa specifikation bör citera det exakta värdet.\n- **Luna för utkast och välkontrollerade rutinmoment.** Mycket billig, men\n  två av fem Z-paket motiverade en följdprövning för fel objekt. Låt inte\n  Luna ensam stänga evidensberoenden eller tolka svåra tabellbilder.\n\nDetta är rekommendationer för uppmätta moment; ingen modellkonfiguration\neller permanent arbetsregel har ändrats. En kedja där en billig modell\ngör utkast och Astra granskar är inte testad som sammanhängande arbetsflöde.\n\n## Godkända hela svar\n\n| Uppgift | Astra | Sol | Terra | Luna |\n|---|---:|---:|---:|---:|\n'''
for task,title in [('x','X: originalutvinning'),('y','Y: följdprövning'),('z','Z: ändringspaket, strikt')]:text+='| '+title+' | '+' | '.join(str(lookup[(task,m)]['passed'])+'/5' for m in models)+' |\n'
text+='''\nEtt underkänt svar kan innehålla många riktiga uppgifter. Genomsnittlig\npoäng var X:100/88/78/81% och Y:100/94/93/94% i modellordningen ovan.\nHöga medelvärden dolde fel som kunde knyta uppgifter till fel person eller\ntappa befintlig kunskap. Därför används också hela-svaret-grindar.\n\n**X:** Två verkliga bevarade källbilder, 25fält: Robertsfors fol658\nrader2–3 och Degerfors fol1064 rader8–12. Klara datum/tomma celler samt\növerstrykningar, svag blyerts och radplacering. Alla15underkända svar\nplacerade husförhörstal på fel rad. Vissa hade dessutom säkra felläsningar\nav namn eller datum. Rimliga Nicolaus/Nikolaus/Nickolaus- och12/13-varianter\ngodtogs; de avgjorde inte underkännandet. Gate≥68/75och inga kritiska fel.\n\n**Y:** Syntetiserat mikrofall från verkliga projekttyper:16objekt,9requests,\ntydlig datumrättelse, osäkert datum, källberoende, historik/namne,\nägaruppgift, hälsotomfält och hemort/dödsort. Alla15underkända svar\ntappade den tidigare uppgiften om familjens boende i F5. Ett svar hade\nrequestfel och ett var otydligt om vilket kanoniskt datum som skulle\nbehållas. Ingen modell etablerade en ny säker föräldrarelation.\n\n**Z:** Två stipulerade fall i ett paket: enkel titelrättelse och\ndatumrättelse med fyra objekt, gammalt+nytt medium, versionsbindningar och\ntvå individuella resolve. Alla20paket kunde införas i en engångsdatabas.\nFem Terra-paket hade en extra punkt i titeln. Två Luna-paket hade\notillräckligt individuellt sakskäl för F-B-prövningen trots rätt data.\n\n## Känslighetsanalyser och brister i testet\n\nBedömningsgränsfallen avgjordes och låstes **före modellnyckeln öppnades**.\nFrysta instruktioner, råsvar och automatresultat är oförändrade.\n\n| Alternativ avgränsning | Astra | Sol | Terra | Luna |\n|---|---:|---:|---:|---:|\n'''
text+='| Y utan enbart F5:s bevarandekrav | '+' | '.join(str(lookup[('y',m)]['without_F5_passed'])+'/5' for m in models)+' |\n'
text+='| Z om enbart titelns slutpunkt tolereras | '+' | '.join(str(lookup[('z',m)]['material_passed'])+'/5' for m in models)+' |\n'
text+='''\nY:s F5 har inget separat bifogat boendebelägg; enda explicita support är\ngravkortet. Huvudbedömningen kräver att den opåverkade bostadsuppgiften\nbevaras, men ett annat synsätt på detta begränsade underlag påverkar\nrankningen kraftigt. Y ger därför svagt stöd för generell rangordning.\nAutomatikens krav på exakt `retain` för P2 och tom persons-lista var också\nför snäva: en datumbevarande konfliktannotering är sakligt giltig enligt\nden offentliga policyn. Den blinda sakbedömningen godtog sådana svar.\n\nZ:s titel stod i en löpande mening utan citattecken kring värdet. Att\nkopiera meningspunkten är en formateringsavvikelse, inte ett genealogiskt\nsakfel. Det strikta resultatet behålls men ska inte ensamt styra modellval.\n\n18försök avvek från paketavgränsningen:16läste/försökte läsa allmänna\ninstruktioner (två även README/NORTH-STAR; ett även gitstatus), två skrev\negna bildderivat i tillfällig katalog. Ingen läsning av facit eller andra\nsvar observerades. Följande är huvudgodkännanden efter att dessa18uteslutits:\n\n| Uppgift | Astra | Sol | Terra | Luna |\n|---|---:|---:|---:|---:|\n'''
for task in 'xyz':text+='| '+task.upper()+' | '+' | '.join(f"{lookup[(task,m)]['clean_passed']}/{lookup[(task,m)]['clean_n']}" for m in models)+' |\n'
text+='''\nIsoleringen var nya kontexter och instruktioner i gemensamt filsystem,\ninte separata OS-sandboxar. Modellnamn fanns i körkatalogen, men de blinda\ngranskarna fick slump-ID. Exakta modellalias/medium verifierades i\nkörloggarna; modellvikterna kunde inte låsas till daterad snapshot.\n\n## Tid och kostnad\n\nUSD-värdena nedan är **beräknad standard-API-kostnad**, inte faktisk\nCodex-debitering eller abonnemangskvot. De använder uppmätt input, cached\ninput och output; reasoning är del av output och dubbelräknas inte.\nPrisunderlag kontrollerat2026-09-19: [Astra/Sol/Terra](https://developers.openai.com/api/docs/models/compare)\noch [Luna](https://developers.openai.com/api/docs/models/gpt-5.6-luna).\nPriser per miljon tokens, input/cache/output:10/1/50,4/0,4/20,\n2/0,2/12 och0,2/0,02/1,2. Ingen request passerade272ktokens.\n\n| Uppgift/modell | Median sekunder | Medelkostnad per försök | Kandidatkostnad per strikt godkänt svar |\n|---|---:|---:|---:|\n'''
for row in s:
 cost=row['proxy_per_accepted_usd'];text+=f"| {row['task'].upper()} / {labels[row['model']]} | {row['median_seconds']:.0f} | ${row['mean_standard_proxy_usd']:.4f} | "+(f'${cost:.4f}' if cost is not None else '— inget godkänt')+' |\n'
trial_total=sum(r['api_standard_proxy_usd'] for r in rs);judges=sum(r['standard_api_proxy_usd'] for r in aux if 'judge' in r['agent']);builders=sum(r['standard_api_proxy_usd'] for r in aux if 'builder' in r['agent'])
text+=f'''\nDe60kandidatsvaren kostade tillsammans cirka${trial_total:.2f} enligt denna\nprisproxy. Separata granskaragenter cirka${judges:.2f}, paketbyggande\nagenter cirka${builders:.2f}. Huvudagentens uppmätta delsumma för planering,\norkestrering, kontroll och rapportarbete var ${root['standard_api_proxy_usd']:.2f}\nvid uttaget (slutrapportens sista steg tillkommer). Detta är engångskostnad\nför studien och ska inte döljas eller fördelas som om det vore normal\nproduktionskostnad per paket.\n\n'''
grade_z=next(r['standard_api_proxy_usd'] for r in aux if r['agent'].endswith('z_judge'))/20
text+='Med lika fördelning av Z-granskarens faktiska studiearbete över20svar blir\nkostnaden per strikt godkänt Z-svar ungefär '+', '.join(f"{labels[m]} ${(lookup[('z',m)]['mean_standard_proxy_usd']+grade_z)*5/lookup[('z',m)]['passed']:.3f}" for m in models if lookup[('z',m)]['passed'])+'.\n'
text+='''Det är en transparent fördelningsmodell, inte uppmätt produktionskostnad\nför varje modells efterarbete. Ingen rättningsrunda genomfördes och\nframtida mänsklig granskning/reparation är inte prissatt. Luna kan därför\nvara ekonomisk som granskat utkast, men dess lägre kandidatpris bevisar\ninte lägst total kostnad för självständig leverans.\n\nAstra var snabbare än Sol i dessa medianer; billigare tokenpris betydde\ninte kortare väntetid. Cacheandelen är hög. `results.json` redovisar även\nen beräkning utan cachebesparing; den ändrar inte vilka svar som är\ngodkända. Avgränsade agentuppdrag och kort överlämnad kontext är därför\nviktiga även när modellen väljs rätt. Orkestrering av60små uppdrag i en\nlång huvudtråd var en betydande del av just denna studies kostnad.\n\n## Vad slutsatserna håller för\n\nDetta är fem isolerade upprepningar på samma lilla material, inte fem\noberoende genealogiska problem per modell. 5/5är ingen felfrihetsgaranti\n(en beskrivande95%Wilsonintervall är ungefär57–100%); 0/5bevisar inte\natt modellen aldrig kan klara momentet. Mellanfall, andra dokumenttyper,\nandra resonemangsnivåer och stora akter har inte testats.\n\nSakgranskningen utfördes av separata modellblinda Astra-kontexter med\nrootens efterprövning, inte en oberoende mänsklig granskare. Det kan ge\nmodellfamiljsbias. Observerbara rad-/databevarandefel och faktisk native\ninförsel ger starkare stöd än en allmän AI-poängsättning, men eliminerar\ninte begränsningen.\n\n## Bevarande och verifiering\n\nAlla60svar, indata, kontrollsummor, modellval, tider, tokenposter,\nverktygsanrop, blindbedömningar och individuella fel finns bevarade.\nSe [README](README.md), [protokoll](PROTOCOL.md), [resultat per försök](results.csv),\n[sammanställning](summary.json), [rootens adjudikation](ROOT-ADJUDICATION.md)\noch [slutverifiering](verification.json).\n\nReferenspaketet klarar15/15 och testaren upptäcker åtta injicerade fel.\nSamtliga60inputkopior och blindkopior verifierade;188skyddade\ndatabas-/journal-/mediefiler samt filuppsättningen oförändrade.\nArkiv-/Wotanvalidator:5130assertions,3035Markdown,5065media, godkänd.\nDen upptäckte först fleraONGOING eftersom äldre pauser stod som aktiva.\nT-0675/T-0676 står nu BLOCKED av ägarens paus med sparad fas och exakt\nåterstartpunkt; inget forskningsarbete återupptogs. Ingen arkivsnapshot\nuppdaterades för att få kontrollen att passera.\n\nInget commit/push, ingen dashboarduppdatering och ingen live-apply.\n'''
text=re.sub(r'([a-zåäö])(\d)',r'\1 \2',text)
text=re.sub(r'(\d)([A-Za-zÅÄÖåäö])',r'\1 \2',text).replace('272 ktokens','272 000 tokens')
(b/'report.md').write_text(text)
print('report written',len(text),'characters')
