import pathlib,json,hashlib,shutil,time
R=pathlib.Path.cwd();D=R/'evaluations/T-0810';I=D/'implementation';S=I/'stage476-v1';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();axes=json.load(open(S/'final-axis-differences-and-relation-proof.json'));assert axes['persons']==536 and [x['person']for x in axes['all_person_axis_differences']]==['P-0247','P-0253'];assert axes['all_relation_native_exact']and len(axes['relations'])==19;result=json.load(open(S/'result.json'));assert result['state']=={'journal_head':476,'pending':0};inv=json.load(open(S/'inventory-full.json'));people={x['id']:x for x in inv['people']};focal=[]
for pid in ['P-0247','P-0253']:
 p=people[pid];assert p['identityReview']['outcome']=='passed'and p['identityReview']['usable'];assert p['treeEffect']['outcome']=='supporting'and p['treeEffect']['usable'];life=p['lifePictureReview'];assert life['outcome']=='failed'and life['usable'];focal.append({'person':pid,'identityReview':p['identityReview'],'treeEffect':p['treeEffect'],'legacyFullContract':life})
assert people['P-0241']['lifePictureReview']['outcome']=='failed'and people['P-0241']['lifePictureReview']['usable'];controls=[]
for pid in ['P-0269','P-0270']:
 b=json.load(open(R/'evaluations/T-0809/implementation/stage473-sequence-v1'/(pid+'-pedigree.json')));a=json.load(open(S/(pid+'-pedigree.json')));key=lambda x:json.dumps(x,sort_keys=True);bs={key(x)for x in b['paths']};assert bs<={key(x)for x in a['paths']};added=[x for x in a['paths']if key(x)not in bs];assert len(b['paths'])==35 and len(a['paths'])==37 and {x['person']for x in added}=={'P-0247','P-0253'};controls.append({'root':pid,'baseline':35,'final':37,'all_old_paths_exact':True,'added_paths':added})
for name in ['verify.json','verify-assets.json']:
 v=json.load(open(S/name));assert v['ok']and not v['errors']
proof=json.load(open(S/'final-native-135-and-65-resolution-proof.json'));assert len(proof['full_final_native_changes'])==135 and len(proof['individual65_stored_resolutions'])==65 and len(proof['all_old_retain_native_versions_preserved'])==304
baseline=json.load(open(D/'preparation/baseline-state-v1.json'));assert sha(R/'genealogy2/data/research.sqlite')==baseline['main']['sha256'];qualified={'task':'T-0810','state':result['state'],'changes135_full_native_exact':True,'individual65_resolutions_order_rationales_exact':True,'step_retains':[246,52,6],'step_retain_rows_total':304,'unique_retained_objects_not_claimed':True,'field_scope_retains':3,'media2_exact':True,'old44nonderived_rows_order_preserved':True,'persons':536,'nonfocal534_full_axes_exact':True,'P0241_LIFE_failed_usable_full_baseline_exact':True,'relations19_full_native_exact':True,'focal_reviews':focal,'focal_legacy_backing_revision':'ASSESSMENT-P0247/P0253@1→@2 source-approved copy qualification; fullcontract failed scope unchanged, no native LIFE created','pedigree_controls':controls,'verify_assets_pass':True,'main473_unchanged':True,'attempts_preserved':['literal metadata-name adapter assertion no write','initial474 actual59','fresh473→474→475 actual6','immutable475→476 exact6resolve'],'actual59_exposure_qualification':'Independent received unsolicited primary52/7target summary before own59seal, did not open candidatefiles; ownoriginal reading blind. Actual59 review not claimed blind. Six ownassessments sealed before comparison.','elapsed_seconds':{'initial':json.load(open(I/'stage474-v1/initial-result.json'))['elapsed_seconds'],'two_op_sequence':json.load(open(I/'stage475-sequence-v1/result.json'))['elapsed_seconds'],'third':result['elapsed_seconds'],'final_readers':json.load(open(S/'reader-capture-result.json'))['elapsed_seconds']},'model_usage':'unknown; root captures role usage after final responses','canonical_apply':'Root only; worker did not apply'};q=S/'qualified-final-result-v1.json';assert not q.exists();q.write_text(json.dumps(qualified,ensure_ascii=False,indent=2)+'\n')
N=D/'preparation/normative-snapshots-final-v1';assert not N.exists();N.mkdir();snap=[]
for name in ['AGENTS.md','wotan/README.md','wotan/dev-log/T-0810.md','wotan/dev-log/T-0231.md','genealogy2/docs/working.md','docs/research/person-contract.md','docs/research/riksarkivet-access.md']:
 dst=N/name.replace('/','__');shutil.copyfile(R/name,dst);snap.append({'source':name,'snapshot':str(dst.relative_to(R)),'sha256':sha(dst),'qualification':'Immutable precompletion scope/norm snapshot; root Wotan closure may later change live status.'})
(N/'snapshot-index.json').write_text(json.dumps(snap,ensure_ascii=False,indent=2)+'\n');paths=[p for p in D.rglob('*')if p.is_file()and '__pycache__'not in p.parts and p.suffix!='.pyc'and 'final-source-gate'not in p.name and p.name!='final-manifest-v1.json'];paths+=[R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py'];
for fn in ['locked-current-input-manifest-v1.json','actual-five-media-input-lock-v1.json']:
 m=json.load(open(D/'preparation'/fn));paths += [R/x['path']for x in m['files']]
for pin in json.load(open(D/'preparation/current-reader-reuse-pins-v1.json'))['reuse']:paths.append(R/pin['path'])
files=[{'path':str(p.relative_to(R)),'sha256':sha(p)}for p in sorted(set(paths))];ops=['operation-v3.json','repair-operation-v1.json','six-resolution-operation-v1.json'];tables=['consequence-table-v3.json','repair-consequence-table-v1.json','six-resolution-consequence-table-v1.json'];pin=lambda p:{'path':str(p.relative_to(R)),'sha256':sha(p)};manifest={'task':'T-0810','baseline_state':{'journal_head':473,'pending':0},'baseline_main_sha256':baseline['main']['sha256'],'final_state':result['state'],'stage_database':pin(S/'stage.sqlite'),'operations':[pin(I/x)for x in ops],'consequence_tables':[pin(I/x)for x in tables],'qualified_result':pin(q),'file_count':len(files),'files':files,'canonicalApproval':False};p=D/'final-manifest-v1.json';assert not p.exists();p.write_text(json.dumps(manifest,ensure_ascii=False,indent=2)+'\n');print('manifest',sha(p),'pins',len(files),'db',sha(S/'stage.sqlite'))
