import pathlib,json,hashlib,shutil,subprocess,importlib.util,time
R=pathlib.Path.cwd();I=R/'evaluations/T-0820/implementation';sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();MAIN=R/'genealogy2/data/research.sqlite';assert sha(MAIN)=='c0bfefbfe1a734cf216514d478c1f74c77a4f05237ae78a04e00b45517295c76';SOURCE=I/'stage490-sequence-v1';assert sha(SOURCE/'stage.sqlite')=='e313bd94ea6a45931705bd2790f70ba05870593c3ce061c4a4989f7fbbbe32f7';hp=R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py';assert sha(hp)=='ce9c424a2f1f36748880e15c83b44e4aa8aa407ab627ee723bf7c90b6b709ce2';sp=importlib.util.spec_from_file_location('h',hp);h=importlib.util.module_from_spec(sp);sp.loader.exec_module(h)
def save(p,x):assert not p.exists();p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
p=I/'third-flag-operation-v1.json';assert sha(p)=='6aa8165c923a2fb3798cc50629178108c39e5597af9cc3a9982215aba46613cc';op=json.load(open(p));S=I/'stage491-continuation-v1';assert not S.exists();S.mkdir();db=S/'stage.sqlite';shutil.copyfile(SOURCE/'stage.sqlite',db);shutil.copytree(SOURCE/'journal',S/'journal');c=h.conn(db);assert h.state(c)=={'journal_head':490,'pending':0};save(S/'baseline490-all50.json',h.all50(c));c.close();t=time.monotonic()
try:
 r=subprocess.run(['node','genealogy2/cli.mjs','apply',str(p),'--db',str(db),'--journal',str(S/'journal')],capture_output=True,text=True);(S/'apply.json').write_text(r.stdout);save(S/'apply-process.json',{'exit':r.returncode,'stderr':r.stderr});assert r.returncode==0,r.stderr;c=h.conn(db);pending=[dict(x)for x in c.execute('select q.*from review_request q left join review_resolution r on r.request_id=q.id where r.request_id is null order by q.rowid')];save(S/'actual-pending-full.json',pending);ctx=[]
 for q in pending:
  n=h.native(c,q['affected_revision_id']);ctx.append({'request':q,'old_target_native':n,'current_target_native':h.native(c,h.current(c,n['object_id'])),'changed_basis_native':h.native(c,q['changed_revision_id']),'all_old_basis_current_stronger':[{'edge':e,'old_basis':h.native(c,e['basis_revision_id']),'current_stronger':h.native(c,h.current(c,h.native(c,e['basis_revision_id'])['object_id']))}for e in n['evidence']]})
 save(S/'actual-pending-contexts.json',ctx);accepted=json.loads(c.execute('select request_json from operation_payload where operation_id=?',(op['id'],)).fetchone()[0]);assert accepted=={**op,'dependencyReviewVersion':2,'searchMemoryVersion':1};a=op['changes'][0];n=h.native(c,h.current(c,a['id']));actual=h.api(n);assert actual==h.expected_defaults(a,actual);save(S/'literal-single-native-proof.json',n);save(S/'actual-all50.json',h.all50(c));assert sha(SOURCE/'stage.sqlite')=='e313bd94ea6a45931705bd2790f70ba05870593c3ce061c4a4989f7fbbbe32f7';assert sha(MAIN)=='c0bfefbfe1a734cf216514d478c1f74c77a4f05237ae78a04e00b45517295c76';save(S/'result.json',{'state':h.state(c),'single_API_exact':True,'source490_MAIN488_unchanged':True,'elapsed_seconds':time.monotonic()-t,'new_pending_requires_SOURCE':bool(pending)});print(json.dumps(h.state(c)))
except Exception as e:save(S/'failure-preserved.json',{'error':str(e),'elapsed_seconds':time.monotonic()-t});raise
