import json,hashlib
from pathlib import Path
p='evaluations/T-0781/proposed-two-current425-metadata-and-prior-reuse-inputs-v1.json';d=json.load(open(p));o=d['objects']; pin=lambda p:{'path':str(p),'sha256':hashlib.sha256(Path(p).read_bytes()).hexdigest()}
entries=[]
def add(oid,subs,reason):
 cur=o[oid];old=cur['data']['body'];new=old
 for a,b in subs:
  assert new.count(a)==1,(oid,a,new.count(a));new=new.replace(a,b)
 entries.append({'object_id':oid,'current':cur,'decision':'revise_exact_data_body_clauses_only','edits':[{'field':'data.body','old':old,'new':new}],'reason':reason,'retains':'Complete caveat/rationale/disposition/evidence_status/outcome/title/criteria and existing ordered evidence/origins unchanged; no historical basis rebind. Whole body+caveat read.','evidence_addition':{'basis':'TR-T0781-C0067-fullpost@1','role':'supports','note':'T-0781 återbruk av T-0131:s fullständiga egenpost och prövade vittnesgränser; samma historiska källa, ingen ny oberoende röst.'},'incoming_gate':'Exact current/all-history incoming and overlap must be zero or returned for specific source disposition before dependent production; prepare draft only.'})
add('BIO-P-0049',[
 ('som fjärde barnet i bonden Jakob Anderssons och Maria Christina Hansdotters hushåll och döptes tre dagar senare med fyra vittnen ur byn.','i bonden Jakob Anderssons och Maria Christina Hansdotters hushåll och döptes tre dagar senare. Postens råtal (4) bevaras utan att här fastställa födelseordning eller familjens totala barnantal. Tre av de fyra vittnesleden anger Ultervattnet; det fjärde anger Anna Nilsd:r[?] i Ytteråträsk[?].')],
 'Full egen T0131post och current BIO har lästs. Alla fyra ur byn är fel eftersom fjärde orten är separat reserverad. Rå(4) kan inte ensam göras till faktiskt fjärde födda barnet. Resterande biografi och befintliga gränser består; personidentitet/föräldrar/datum ändras inte.')
add('BIO-P-0105',[
 ('**Byn är hennes enda framkomliga led — och den är läst.** Ultervattnets\nhusförhörsuppslag omkring 1872 skulle ge både hennes och mannens namn, och den\npassagen är därmed billigare än för något av projektets övriga\noidentifierade vittnen.',
 '**Byn och den angivna hustrurelationen ger möjliga sökingångar.** De redan\nlästa familjesidorna i Ultervattnet identifierar inte säkert henne eller\nmannen och täcker inte byns samtliga hushåll. En fortsatt prövning i relevant\nhushållsmaterial kan vara möjlig, men tillgänglig passage, personkorrelation\noch innehåll måste först fastställas. Källan utlovar inte bådas namn, lägre\narbetsinsats eller att andra källvägar är uteslutna.')],
 'Den egna postens namnlösa hustru och ort är giltiga nycklar, inte en säker ensam/billig identitetslösning. Hela current caveat kvalificerar redan äldre myndighetsinferens; den görs inte till nytt originalfynd. Ingen ny vittnesidentitet eller kontraktsstatus.')
add('RESEARCH-P-0105-9d76f0343410',[
 ('**Orten är hennes enda framkomliga led, och den är ovanligt stark.**\n`Ultervattnet` är inte en grannby utan dopbarnets hemvist, och byn är redan\nläst i två volymer — `A I/14b` sida 567 och `A II a/2b` sida 824. Hon är\nnåbar i material projektet redan har hämtat, vilket gör hennes passage\nbilligare än för något av programmets övriga oidentifierade vittnen.',
 '**Orten och den angivna hustrurelationen ger möjliga sökingångar.**\n`Ultervattnet` är dopbarnets hemvist. De lästa familjesidorna `A I/14b`\nsida 567 och `A II a/2b` sida 824 ger avgränsat sammanhang men identifierar\ninte säkert henne eller mannen och täcker inte byns samtliga hushåll.\nRelevant fortsatt passage, åtkomst, personkorrelation och innehåll är\noprövade; varken en säker namnträff, lägre arbetsinsats eller en enda möjlig\nkällväg följer av orten.')],
 'Hela currentbody/caveat lästa. Egen källort är möjlig nyckel, inte bevis att vittnet är nåbart i just hämtade familjerader eller billigare än andra personer. Namnlöshet, separata personankaret, OLÖST/EJ BÄRANDE och övriga frågor består.')
add('BIO-P-0104',[
 ('**Men orten är stark på ett sätt de andra vittnenas inte är.**','**Orten är en gemensam sökingång för honom, den namnlösa hustrun och C. Jacobsd:r.**')],
 'Independent bounded finding accepted after own wholeBIO read: tre av fyra vittnesled delar Ultervattnet. Jämförelse som påstår exklusiv ortstyrka inom gruppen rättas. Redan kvalificerade senare sökvägar och farbrorshypotes bevaras. RESEARCH104:s uttryckliga jämförelse mot Degerforsvittnen är annan scope och får inte tyst ändras.')
f=Path('evaluations/T-0781/source-review/C0067-four-current-source-scope-clause-decisions-v1.json');assert not f.exists();v={'task':'T-0781','scope':'Four entire current objects; exact C0067 source-field consequences, no new original or personcontract upgrade.','source_decision_pin':pin('evaluations/T-0781/source-review/C0067-primary-settled-full-prior-reuse-source-scope-v1.json'),'input_pin':pin(p),'objects':entries,'implementation':'Prepare exact four draft native revisions with one explicitly specified TR support addition each after exact current and incoming guards. New TR is settled same-source reuse, requires explicit fullpost API spec before operation assembly. No automatic rebinding, no runtime authorization.'};f.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');print(pin(f))
