import json, sqlite3, hashlib, pathlib, datetime

base=pathlib.Path('evaluations/T-0796')
db=sqlite3.connect('genealogy2/data/research.sqlite'); db.row_factory=sqlite3.Row
def h(p): return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def write(n,x): (base/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def evidence(r,n='T-0796 bounded metadata result',role='supports'): return {'object':r.rsplit('@',1)[0],'version':int(r.rsplit('@',1)[1]),'role':role,'note':n}
def new(id,kind,data,ev=[]): return {'id':id,'kind':kind,'expectedVersion':None,'data':data,'disposition':'recorded','evidenceStatus':None,'rationale':'T-0796 AC1–3: exact metadata-only routing; no person content or review upgrade.','caveat':'Metadata/candidate routing only; no employment, ownership, identity or parent conclusion.','origins':[],'evidence':ev}
heads=[dict(r) for r in db.execute('SELECT * FROM current_revision ORDER BY object_id')]
write('baseline-heads.json',heads)
write('baseline-proof.json',{'db_sha256':h('genealogy2/data/research.sqlite'),'max_sequence':db.execute('SELECT MAX(sequence) FROM operation_payload').fetchone()[0],'pending':db.execute('SELECT count(*) FROM pending_review').fetchone()[0] if db.execute("SELECT 1 FROM sqlite_master WHERE name='pending_review'").fetchone() else None,'heads_sha256':h(base/'baseline-heads.json')})
reuse=[]
for p in ['genealogy/media/S-0688-kMzeNZ6kuYJ7MDrjZlNKI2.json','genealogy/media/S-0688-Rfbn3tQXcKwIDm040Bi1c0.json','genealogy/media/S-0688-vol9-katalog.txt','genealogy/media/S-0688-vol10-katalog.txt','genealogy/media/S-0689-records-1572-AIIc.json','genealogy/media/S-0690-records-handelsregister-sodertalje.json']:
 reuse.append({'path':p,'sha256':h(p),'access_date':'2026-09-05','exact_time':'UNKNOWN: not documented by old receipt','provider_version':'UNKNOWN: not exposed by old receipt'})
write('reuse-copies.json',reuse)
changes=[]
for name,key,outcome,qid in [('e22a-attempt1-tool-response.json','E22A-attempt1','inconclusive','P-0003/Q-05'),('e22a-attempt2-tool-response.json','E22A-attempt2','positive','P-0003/Q-05'),('prv-tool-response.json','PRV','inconclusive','P-0003/Q-05')]:
 receipt=json.loads((base/name).read_text());sid='S-T0796-'+key
 raw=receipt['response']['structuredContent']['result']
 source=new(sid,'source',{'title':'T-0796 '+key+' metadata tool response','archive_reference':receipt['args']['keyword'],'source_class':'catalogue_metadata','description':'Exact query parameters and full received tool response preserved at '+str(base/name)+' SHA256 '+h(base/name)+'\n\n'+raw})
 changes.append(source)
 limitation='Only returned catalogue query representation, offset0 limit10. No person originals or trademark records read; no full archive or1950–1993 coverage. Provider version UNKNOWN. Received_at is local response-observation time, not server event/version.'
 if key=='E22A-attempt1': limitation+=' The queried path had an unverified extra E22 segment; its zero is query visibility only and is superseded for routing by corrected E22A-attempt2, not personal absence.'
 if key=='PRV': limitation+=' All-term/wildcard keyword matching and no positive control; zero cannot distinguish query normalization, catalogue coverage or absence. PRV historical collection and specific1950s Sesam route remain unresolved.'
 scope={'description':'Fixed '+key+' metadata entrypoint attempt','query':receipt['args'],'bounds':{'offset':0,'limit':10,'only_digitised':False,'originals_read':0},'search_memory':{'format':'search-memory/1','subjects':['P-0003'],'performed_at':receipt['received_at'],'method':'Riksarkivet MCP search_metadata. Local received_at marks actual response receipt; no invented server timestamp.','material':{'identifier':'Riksarkivet MCP metadata catalogue: exact query '+receipt['args']['keyword'],'source_version':1,'provider_version':{'value':None,'unknown_reason':'Not exposed by tool response; model@1 is not provider version.'},'snapshot':{'reference':str(base/name),'sha256':h(base/name)}},'coverage':{'completed':True,'limitations':limitation},'reactivation':['Changed catalogue/material or corrected query supported by new metadata, within separately authorized bounded passage; do not repeat sufficient receipts.','Original/person/trademark content requires separately authorized task; no orders or contacts authorized.']}}
 changes.append(new('SEARCH-T0796-'+key,'search',{'question_id':qid,'source_id':sid,'scope_json':scope,'outcome':outcome,'body':raw+'\n\nInterpretation: '+limitation},[evidence(sid+'@1')]))
r1='T-0796 R1: sufficient dated metadata reused, no new external call. S0688@1 exact F I aa/9 kMzeNZ6kuYJ7MDrjZlNKI2 and /10 Rfbn3tQXcKwIDm040Bi1c0,1951 districts1–4/5–8; preserved article texts show Kronokamreraren i Södertälje, Stockholms stadsarkiv, Läsesal on2026-09-05. This remains a candidate jurisdiction for the C0876 reported household, not proof that2828/bild620/sida260 belongs to these volumes. S0689@1 exact returned item O88tCNBZPaozjCscDcC063: SE/SSA/1572/A II c/99,1948–1970, note Tranbäret–Tunet, Stockholms stadsarkiv, onlyDigitisedMaterials:false and no image link in this returned representation. Full item including hierarchy/provenance/links preserved in reused byte copy; no new current-access or terminal digitalization claim. Tranbärets1951district and household/person content after1947 remain unknown/unread; addresses do not prove continuous physical residence or property ownership. Reopen on new district/catalogue metadata or separately authorized exact original passage; no order/contact here.'
r2='T-0796 R2: two named metadata entrypoints tested, three calls including one corrected E22A attempt. Initial unverified extra-segment reference gave query zero only. Corrected SE/SSA/1451/01/E/E22A reported10+matching volumes with only1–10displayed (full returned fields in SEARCH-T0796-E22A-attempt2@1), including /110 dated1949 and /107 dated1948, SSA/Länsstyrelsen i Stockholms län äldre/Landskansliet/INKOMNA HANDLINGAR. A positive reference route exists; these returned volumes lack titles and do not newly certify the E22A series meaning (handelsregister remains olderS0690 candidate routing); no complete1950–1993coverage or person-bound firm route established. S0690@1 previously names E22A1888–1958/D1B/E22G1964–1970, but its preserved15/487APIitems do not themselves contain E22A; retain dated summary without inventing its missing rawE22A support. PRV query Patent registreringsverket varumärk* gave no results: precise query/coverage unknown, not noSesam/noArne/no trademark archive. Own firm dates/name/address/registration and Sesam registration/owner/milestones remain open; C0266/C0267 are one attributed family-information chain, not independent business evidence. No ownership/employment inference. Reopen with new exact historical PRV catalogue/index metadata or firmanamn/year/register locator in separately authorized bounded work.'
rest='Exclusive remaining owners retained: T0228 childhood1923–1930; T0786 ownSödertälje15 names/family/in-transfer/continuations and access; T0229 military22-44-35/probate1993; T0227 remaining accepted-source control. T0793 retains planning responsibility for later life and Orrestaö/Båven property/PK03; this planning is not original execution authority. R1district/ownrow and R2ownfirm/trademark original questions remain undecided execution, not DONE, source exhaustion or personPASS.'
audit=new('AUDIT-T0796-metadata-routing','assessment',{'subject_id':'P-0003','criteria':'bounded_metadata_routing/1','outcome':'reviewed_with_limits','body':r1+'\n\n'+r2+'\n\n'+rest+'\n\nProtected: PCD2026-08-20-001 Bernhard parentage and PCD2026-10-07-001 Arne/Maj→P0005→P0004 OWNER_CONFIRMED, stronger accepted1930–1947 sources and all identity/tree/life grades unchanged. Metadata alters routing only.'},[evidence('S-0688@1'),evidence('S-0689@1'),evidence('S-0690@1'),evidence('SEARCH-T0796-E22A-attempt1@1'),evidence('SEARCH-T0796-E22A-attempt2@1'),evidence('SEARCH-T0796-PRV@1')]);changes.append(audit)
targets=['P-0003/Q-01','P-0003/Q-05','PATH-P-0003-KP-01','PATH-P-0003-KP-05','KEY-P-0003-0fbf93cb4e0f','KEY-P-0003-c4df7c772e8f','KEY-P-0003-df61854d250b']
p=json.loads((base/'person-before.json').read_text())
targets += [x['object_id'] for x in p['research']['themes'] if any(s in x['object_id'] for s in ['-BO','-ARB','-EKO'])]
consequences=[]
for oid in targets:
 head=dict(db.execute('SELECT * FROM current_revision WHERE object_id=?',(oid,)).fetchone());kind=head['kind'];data=dict(db.execute('SELECT * FROM '+kind+' WHERE revision_id=?',(head['id'],)).fetchone());data.pop('revision_id')
 for k,v in data.items():
  if k.endswith('_json') and v is not None:data[k]=json.loads(v)
 text=r2 if any(s in oid for s in ['Q-05','KP-05','df61854d250b','-EKO']) else r1
 if '-ARB' in oid:text=r1+'\n\n'+r2
 # Preserve complete older body/caveat/outcome; current amendment precedes historical wording.
 oldbody=data['body'];data['body']='T-0796 current bounded metadata amendment (earlier dated wording below retained as history):\n'+text+'\n\n'+oldbody
 m={'id':oid,'kind':kind,'expectedVersion':head['version'],'data':data,'disposition':head['disposition'],'evidenceStatus':head['evidence_status'],'rationale':'T-0796 AC1–3: current bounded metadata routing appended with full prior body/caveat/outcome preserved; no grade or person conclusion.','caveat':head['caveat'],'origins':[{'unit':x['unit_id'],'coverage':x['coverage'],'note':x['note']} for x in db.execute('SELECT * FROM origin WHERE revision_id=? ORDER BY rowid',(head['id'],))],'evidence':[evidence(x['basis_revision_id'],x['note'],x['role']) for x in db.execute('SELECT * FROM dependency WHERE revision_id=? ORDER BY rowid',(head['id'],))]}
 m['evidence'].append(evidence('AUDIT-T0796-metadata-routing@1','Only the new bounded routing amendment; prior evidence order retained.'));changes.append(m)
 consequences.append({'object':oid,'old_revision':head['id'],'field':'body prefix only','old_body_sha256':hashlib.sha256(oldbody.encode()).hexdigest(),'old_caveat':head['caveat'],'old_outcome':data.get('outcome'),'disposition':'metadata amendment; retained complete old body/caveat/outcome and evidence/origin order'})
write('consequences.json',consequences)
write('metadata-routing-operation-v1.json',{'id':'T-0796/metadata-routing-v1','actor':'Codex Sol primary; root review required','reason':'T-0796 AC1–3: exactly P0003R1/R2metadata; reuse sufficient prior receipts, preserve3actualtoolresponses and precise unknowns, native bounded profile amendments.0personoriginal. Root alone canonical apply after independent exact-package review.','dependencyReviewVersion':2,'searchMemoryVersion':1,'changes':changes})
print('Prepared',len(changes),'changes; current amendments',len(targets))
