import pathlib,json,hashlib,copy,sqlite3,time
start=time.time();b=pathlib.Path('evaluations/T-0780');w=b/'implementation/C0563-duplicated-caveat-amendment-v3';w.mkdir(exist_ok=True);load=lambda p:json.load(open(p));sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def save(n,d):
 p=w/n;assert not p.exists();p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');return {'path':str(p),'sha256':sha(p)}
sp=b/'source-review/C-0563-fullTR-duplicated-caveat-amendment-v1.json';assert sha(sp)=='daac2329fa6b55ccbe663638d3ebc82db102ee40771afbb10578a2dba36462a2';s=load(sp);assert sha(s['current_candidate']['path'])==s['current_candidate']['sha256'];old=load(s['current_candidate']['path']);new=copy.deepcopy(old);ch=next(x for x in new['changes'] if x['id']==s['target']);assert ch['expectedVersion'] is None and s['native_version']==1 and len(s['edits'])==1;e=s['edits'][0];assert e['field']=='caveat' and ch['caveat']==e['old'];ch['caveat']=e['new'];assert ch['caveat']==ch['data']['text'];restore=copy.deepcopy(new);next(x for x in restore['changes'] if x['id']==s['target'])['caveat']=e['old'];assert restore==old;new['id']=old['id']+'-duplicated-caveat-amended-v3';new['reason']='T-0780 exact source duplicated caveat amendment '+sha(sp)+'; caveat matches correctedtext, NEWnull1 unchanged, diagnostic oldpayload immutable, fresh full source review/stage pending.';np=save('C0563-fullTR-caveat-operation-v3.json',new);priorp=b/'implementation/C0563-fullTR-compilation-amendment-v2/concrete-current113-C0563-fullTR-amended-sequence-proposal-v2.json';prior=load(priorp);seq=copy.deepcopy(prior['sequence']);oldpin=next(p for p in seq if p['path']==s['current_candidate']['path']);count=0
for i,p in enumerate(seq):
 if p['path']==oldpin['path']:seq[i]=np;count+=1
assert count==1
for i,p in enumerate(seq):
 o=load(p['path']);p['index']=i+1;p['operation_id']=o['id'];p['targets']=[{'id':x['id'],'expectedVersion':x['expectedVersion'],'payload_sha256':hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()} for x in o['changes']]
def reid(x):
 if isinstance(x,dict):return {k:reid(v) for k,v in x.items()}
 if isinstance(x,list):return [reid(v) for v in x]
 return new['id'] if x==old['id'] else x
cross=[{'dependent':x['id'],'basis':e,'full_candidate_payload':x,'member_pin':p,'individual_primary_disposition':None} for p in seq for x in load(p['path'])['changes'] for e in x['evidence'] if e['object']==s['target']];c=sqlite3.connect('file:'+str(b/'preparation/baseline-j281.sqlite')+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;fan=[dict(t) for t in c.execute('select * from dependency where basis_revision_id in(select id from revision where object_id=?)',(s['target'],))];assert not fan
inp=save('whole-payload-caveat-only-proof-and-incoming-input-v3.json',{'source_pin':{'path':str(sp),'sha256':sha(sp)},'old_member_pin':oldpin,'new_member_pin':np,'old_full_changed_payload':next(x for x in old['changes'] if x['id']==s['target']),'new_full_changed_payload':ch,'exact_field':e,'all_other_fields_arrays_metadata_origins_evidence_unchanged':True,'new_caveat_exact_equal_corrected_data_text':True,'same_NEWnull1':True,'native_incoming':fan,'full_candidate_incoming':cross,'diagnostic_old_vs_final_new_payloads_not_equivalent':True,'diagnostic97_actual328_immutable_untouched':True})
m=save('current113-C0563-caveat-amended-membership-inventory-v3.json',{'candidate_members':seq,'members':113,'unique_targets':777,'explicit_member_supersession':{'old':oldpin,'new':np},'duplicate_targets':0,'global_source_approval':False});q=save('concrete-current113-C0563-caveat-amended-sequence-proposal-v3.json',{'sequence':seq,'members':113,'unique_targets':777,'constraints':reid(prior['constraints']),'static_head_order_violations':prior['static_head_order_violations'],'membership_pin':m,'basis_IDS_versions_array_order_unchanged':True,'fresh_source_and_independent_hash_binding_and_full10_stage_required':True,'no_native_PASS_stage_or_request_resolution':True});f=save('bounded-two-module-wide1059-and-caveat-production-v3.json',{'wide1059_receipt_pin':{'path':str(b/'implementation/C0069-wide1059-source-input-match-v1/bounded-wide1059-match-input-output-receipt-v1.json'),'sha256':sha(b/'implementation/C0069-wide1059-source-input-match-v1/bounded-wide1059-match-input-output-receipt-v1.json')},'input_pin':inp,'membership_pin':m,'proposal_pin':q,'changed_native_NEW_payloads':1,'changed_fields':1,'failed_mechanical_attempts':[],'source_duplication_propagation_failure':s['failure'],'elapsed_seconds':time.time()-start,'model_usage_root_collect_after_final':True,'closed_two_module_scope_complete':True,'no_stage_probe_apply_actual328_modification':True});print({'input':inp,'membership':m,'proposal':q,'receipt':f,'incoming':len(cross)})
