import json,copy,sqlite3,hashlib,time,datetime
from pathlib import Path
b=Path('evaluations/T-0780');w=b/'implementation';start=time.time();ap=b/'source-review/C-0062-current-person-and-C-0106-dependency-metadata-amendment-v1.json';assert hashlib.sha256(ap.read_bytes()).hexdigest()=='b91f758e3b183b43553bb689da63fdc6f96f4a184469cfdce640cca031c8776a';a=json.load(open(ap));c=sqlite3.connect('file:genealogy2/data/research.sqlite?mode=ro',uri=True);c.row_factory=sqlite3.Row;assert c.execute('select max(sequence) from operation_payload').fetchone()[0]==281;pold=a['current_person_disposition']['full_current'];head=dict(c.execute('select r.*,o.kind from revision r join object o on o.id=r.object_id where r.object_id=? order by r.version desc limit 1',('P-0089',)).fetchone());assert all(head[k]==pold[k] for k in head);assert head['version']==2 and head['disposition']=='accepted';assert dict(c.execute('select * from person where revision_id=?',('P-0089@2',)).fetchone())==pold['data'];assert pold['data']['sex'] is None;assert [dict(r) for r in c.execute('select * from origin where revision_id=?',('P-0089@2',))]==pold['origins'];assert [dict(r) for r in c.execute('select * from dependency where revision_id=?',('P-0089@2',))]==pold['evidence'];out=[];tables=[]
for am in a['candidate_amendments']:
 src=Path(am['candidate']);original=src.read_bytes();assert hashlib.sha256(original).hexdigest()==am['sha256'];op=json.loads(original);before=copy.deepcopy(op);assert len(am['edits'])==(45 if 'C-0062' in src.name else 1);entries=[]
 for edit in am['edits']:
  found=[x for x in op['changes'] if x['id']==edit['change_id']];assert len(found)==1;ch=found[0];keys=edit['field'].split('.');loc=ch
  for key in keys[:-1]:loc=loc[key]
  key=keys[-1];assert loc[key]==edit['old'],'Unexpected exact old candidate field: return Astra';loc[key]=edit['new'];entries.append({'change_id':edit['change_id'],'field':edit['field'],'old_wording':edit['old'],'new_wording':edit['new'],'Astra_reason':edit['reason'],'existing_expectedVersion_unchanged':ch['expectedVersion']})
 op['id']=am['new_operation_id'];assert len(op['changes'])==len(before['changes']);assert [(x['id'],x['expectedVersion']) for x in op['changes']]==[(x['id'],x['expectedVersion']) for x in before['changes']];back=copy.deepcopy(op);back['id']=before['id']
 for edit in reversed(am['edits']):
  ch=next(x for x in back['changes'] if x['id']==edit['change_id']);keys=edit['field'].split('.');loc=ch
  for key in keys[:-1]:loc=loc[key]
  loc[keys[-1]]=edit['old']
 assert back==before,'Unenumerated mutation';dest=src.with_name(src.name.replace('-v1.json','-v2.json'));assert not dest.exists();dest.write_text(json.dumps(op,ensure_ascii=False,indent=2)+'\n');assert src.read_bytes()==original;table=dest.with_name(dest.name.replace('-operation-v2.json','-candidate-amendment-field-table-v2.json'));table.write_text(json.dumps({'candidate_before':str(src),'candidate_after':str(dest),'approved_exact_edits':len(entries),'entries':entries,'all_other_fields_arrays_meta_evidence_origins_status_unchanged':True},ensure_ascii=False,indent=2)+'\n');out.append({'scope':'C-0062 Forsberg' if 'C-0062' in src.name else 'C-0106','source_candidate':str(src),'source_candidate_sha256':am['sha256'],'new_candidate':str(dest),'new_candidate_sha256':hashlib.sha256(dest.read_bytes()).hexdigest(),'exact_field_edits':len(entries),'change_count':len(op['changes']),'existing_revisions':sum(x['expectedVersion'] is not None for x in op['changes']),'new_objects':sum(x['expectedVersion'] is None for x in op['changes']),'field_table':str(table),'field_table_sha256':hashlib.sha256(table.read_bytes()).hexdigest()})
receipt={'task':'T-0780','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'builder_elapsed_seconds':time.time()-start,'source_amendment_path':str(ap),'source_amendment_sha256':hashlib.sha256(ap.read_bytes()).hexdigest(),'current_P0089_exact2accepted_sexnull_retained':True,'person_revision_changes':0,'prior_candidate_and_history_preserved':True,'all46_exactcandidate_field_matches_PASS':True,'unlisted_fields_arrays_metadata_origins_protectedstatus_unchanged':True,'stage_or_canonical_applies':0,'new_original_reads':0,'outputs':out,'failure_history':[{'event':'Initial C0062 new audit/adoption hardcoded retained person@1 instead of actual accepted current@2','impact':'Draft metadata/evidence only; no apply; exact source-authorized amendment preserves bounded person acceptance and unresolved external identification.'}],'still_pending':'Expanded semantic and independent exactpackage approval; C0106 EPoperation stays separate after amended source operation.'};(w/'C-0062-C-0106-explicit-metadata-amendment-receipt-v2.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(out)
