import json,hashlib,sqlite3,datetime
from pathlib import Path
b=Path('evaluations/T-0780');s=b/'source-review';sem=s/'C-0043-semantic-dispositions-v1.json';dec=s/'C-0043-primary-decisions-v1.json';si=json.load(open(sem));d=json.load(open(dec));c=sqlite3.connect('file:genealogy2/data/research.sqlite?mode=ro',uri=True);c.row_factory=sqlite3.Row;entries=[]
for item in si['items']:
 rid=item['revision_id'];r=c.execute('select * from revision where id=?',(rid,)).fetchone();assert r and c.execute('select max(version) from revision where object_id=?',(item['object_id'],)).fetchone()[0]==r['version'];assert item['Astra_disposition'] and item['Astra_rationale']
 for hit in item['matches']:entries.append({'object_id':item['object_id'],'revision_id':rid,'exact_field':'data.'+hit['field'] if hit['field'] not in ['caveat','rationale','disposition','evidence_status'] else hit['field'],'old_wording':hit['old_wording'],'routing_terms':hit['terms'],'registered_support':item['evidence'],'source_support':'R-884d16c907cc272d30bd2cc8@1; locked original94cb5416ff0ede6643a9a925a9ef4c770c55f2581d9d616bb1e7ea5cb1d0495c; primary raw/decision hashes receipt-bound','Astra_disposition':item['Astra_disposition'],'Astra_rationale':item['Astra_rationale'],'required_change':False,'review_scope':si['scope']})
for item in d['items']:
 rid=item['object_id']+'@'+str(item['version']);assert c.execute('select max(version) from revision where object_id=?',(item['object_id'],)).fetchone()[0]==item['version']
 for field,old in [('data.'+k,v) for k,v in item['old_data'].items() if k!='revision_id']+[('caveat',item['old_caveat'])]:entries.append({'object_id':item['object_id'],'revision_id':rid,'exact_field':field,'old_wording':old,'registered_support':[dict(x) for x in c.execute('select * from dependency where revision_id=?',(rid,))],'source_support':item['support'],'Astra_disposition':item['disposition'],'Astra_rationale':item['rationale'],'required_change':False,'review_scope':'46 exact source-relevant wholecurrentcontext objects primary reviewed'})
p=b/'implementation/C-0043-complete-consequence-table-v1.json';p.write_text(json.dumps({'task':'T-0780','citation':'C-0043','semantic_objects':si['candidate_count'],'exact_context_objects':len(d['items']),'individual_fields':len(entries),'entries':entries,'independent_review_pending':True},ensure_ascii=False,indent=2)+'\n')
def pin(p):return {'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
receipt={'task':'T-0780','stage':'settled_primary_source_and_bounded_semantic_consequence_input; draft unchanged; no apply','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'bound_files':[pin(x) for x in [sem,dec,s/'C-0043-primary-raw-v1.json',p,b/'implementation/C-0043-candidate-operation-v1.json',b/'implementation/C-0043-mechanical-draft-receipt-v1.json']],'semantic_objects':257,'individual_fields':len(entries),'zero_existing_revisions':True,'protectedstate_changes':False,'outstanding':'Independent source/consequence exactpackage review; draftaudit semantic_consequences_remaining was historical creation status and requires explicit metadata amendment before final package.'};(b/'implementation/C-0043-settled-consequence-binding-v1.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print({'fields':len(entries),'semantic_objects':257})
