import json,sqlite3,copy,hashlib,datetime
from pathlib import Path
b=Path('evaluations/T-0780');dp=b/'source-review/C-0044-primary-decisions-v1.json';d=json.load(open(dp));rp=b/d['original_raw'];ap=b/d['comparative_amendment'];raw=json.load(open(rp));am=json.load(open(ap));r='R-f81045d395fcb687a2417ed6';c=sqlite3.connect('file:genealogy2/data/research.sqlite?mode=ro',uri=True);c.row_factory=sqlite3.Row
ro=next(x for x in d['objects'] if x['current']['object_id']==r);old=ro['current'];data={k:v for k,v in old['data'].items() if k!='revision_id'}
def ev(o,v,role='supports',note='T-0780 C0044 avgränsad familjepost; samma historiska källa.'):
 return {'object':o,'version':v,'role':role,'note':note}
evidence=[ev(x['basis_revision_id'].rsplit('@',1)[0],int(x['basis_revision_id'].rsplit('@',1)[1]),x['role'],x['note']) for x in old['evidence']];origins=[{'unit':x['unit_id'],'coverage':x['coverage'],'note':x['note']} for x in c.execute('select * from origin where revision_id=?',(old['revision_id'],))];rmeta={'id':r,'kind':'record','expectedVersion':1,'data':data,'origins':origins,'evidence':evidence,'disposition':old['disposition'],'evidenceStatus':old['evidence_status'],'rationale':old['rationale'],'caveat':old['caveat']}
for e in ro['edits']:assert e['field']=='caveat' and rmeta['caveat']==e['old'];rmeta['caveat']=e['new']
assets=[{'path':x['asset_path'],'region':x['region']} for x in c.execute('select * from record_asset where revision_id=?',(old['revision_id'],))];media=[{'id':x['asset_id'],'region':x['region']} for x in c.execute('select * from record_media where revision_id=?',(old['revision_id'],))]
# Runtime operation API record arrays are named assets/media; original query order retained.
if assets:rmeta['assets']=assets
if media:rmeta['media']=media
currentraw=copy.deepcopy(raw);row=[x for x in currentraw['rows'] if x[0]=='4'];assert len(row)==1 and row[0][16]=='145[?] 175/1890';row[0][16]='45 175/1890';currentraw['status']='primary settled full relevant familypost; expanded semantic and independent package review pending';tid='TR-T0780-C0044-fullpost';aid='AUDIT-T0780-C0044';caveat='Bleka årsnoteringar och Ebbaradens komprimerade vaccinations-/betygs-/nattvardsfält behåller råreservationer; inga säkra datum eller kyrkliga händelser därav. Barnens och Anna Fredrikas födelseortsceller tomma upphäver inte starkare egna födelsebelägg. N.b.1130 i Barbro Christinas radområde bevisar ingen helfamiljs fysisk flytt. 45 175/1890 identifierar ännu inget förband eller faktisk tjänstgöring. Ingen ny person-/grind-/livsbildsgranskning.'
def ch(oid,kind,data,evidence):return {'id':oid,'kind':kind,'expectedVersion':None,'data':data,'origins':[],'evidence':evidence,'disposition':'recorded','evidenceStatus':'TRANSCRIBED' if kind=='transcription' else None,'rationale':'T-0780 AC2–3: mekanisk implementation av Astras avgjorda C0044 fullpost-/fältbeslut.','caveat':caveat}
changes=[rmeta,ch(tid,'transcription',{'record_id':r,'text':json.dumps({'header':currentraw['header'],'scope':currentraw['scope'],'printed_columns':currentraw['columns'],'all_rows_current':currentraw['rows'],'margins':currentraw['margin'],'explicit_primary_comparative_amendment':am},ensure_ascii=False,indent=2),'reading_note':raw['exposure']+' Initial råavläsning bevarad separat i '+str(rp)+'. Endast militärfältets första tal avgjort genom explicit jämförelse; övriga råvärden/reservationer bevarade.'},[ev(r,2)]),ch(aid,'assessment',{'subject_id':r,'criteria':'source_reread/1','outcome':'reviewed_with_reservations','body':json.dumps({'task':'T-0780','scope':'C-0044','record_version':r+'@2','source_sha256':raw['sha256'],'primary_raw_path':str(rp),'comparative_amendment_path':str(ap),'primary_decisions_path':str(dp),'exposure':raw['exposure'],'full_current_post':currentraw,'individual_context_objects':93,'individual_revision_objects':14,'individual_retains':79,'expanded_semantic_and_dependency_dispositions':'pending, no blanket approval; individualR1fanout22 returnedAstra','independent_review_and_hashapproval':'pending'},ensure_ascii=False,indent=2)},[ev(r,2),ev(tid,1)])]
for n in d['new_objects']:
 if n['id'] in [tid,aid]:continue
 pid=n['subject_id'];pv=c.execute('select max(version) from revision where object_id=?',(pid,)).fetchone()[0];changes.append(ch(n['id'],'assessment',{'subject_id':pid,'criteria':'bounded_source_adoption/1','outcome':'reviewed_with_limits','body':n['content']},[ev(pid,pv),ev(r,2),ev(tid,1),ev(aid,1)]))
assert len(changes)==10
op={'id':'T-0780/C0044-source-candidate-v1','actor':'Codex Sol mechanical settled Astra implementation','reason':'T-0780 AC2–3 C0044 fullpost/Rqualification/audit/7boundedadoptions; draft only pending individualdependency+expandedsemantic+independentpackageapproval.','dependencyReviewVersion':2,'changes':changes};p=b/'implementation/C-0044-source-candidate-operation-v1.json';assert not p.exists();p.write_text(json.dumps(op,ensure_ascii=False,indent=2)+'\n');receipt={'draft_only_no_apply':True,'source_record_revision':1,'new_objects':9,'other13existing_revision_objects_held':'Need individualR1basisdispositions beforedependentoperations','pins':[{'path':str(x),'sha256':hashlib.sha256(x.read_bytes()).hexdigest()} for x in [p,dp,rp,ap,b/'implementation/C-0044-exact-context-consequence-plan-v1.json',b/'implementation/C-0044-R1-dependency-fanout-input-v1.json']]};(b/'implementation/C-0044-source-draft-receipt-v1.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(hashlib.sha256(p.read_bytes()).hexdigest())
