import json,sqlite3,pathlib,hashlib,time,datetime
s=time.time();b=pathlib.Path('evaluations/T-0780');w=b/'implementation';p=b/'source-review/C-0062-family-four-adoption-decisions-v1.json';sha='bd3374c1a0869a87adbb96bf01c71181e677ae29b85837aba7c2639cc3688fe7';assert hashlib.sha256(p.read_bytes()).hexdigest()==sha;d=json.load(open(p));c=sqlite3.connect('file:'+str(b/'preparation/baseline-j281.sqlite')+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;entries=[]
for i in d['objects']:
 o=i['current'];h=dict(c.execute('select r.*,ob.kind from revision r join object ob on ob.id=r.object_id where r.id=?',(o['id'],)).fetchone());assert all(h[k]==o[k] for k in h);assert not c.execute('select 1 from revision where object_id=? and version>?',(h['object_id'],h['version'])).fetchone();data=dict(c.execute('select * from '+h['kind']+' where revision_id=?',(o['id'],)).fetchone());assert data==o['data'];orig=[dict(z) for z in c.execute('select * from origin where revision_id=?',(o['id'],))];assert len(orig)==len(o['origins']) and all(all(z[k]==q[k] for k in z) for z,q in zip(orig,o['origins']));ev=[dict(z) for z in c.execute('select * from dependency where revision_id=?',(o['id'],))];assert sorted(ev,key=lambda z:json.dumps(z,sort_keys=True))==sorted(o['evidence'],key=lambda z:json.dumps(z,sort_keys=True))
 for k,v in data.items():entries.append({'revision':o['id'],'field':'data.'+k,'old':v,'new':v,'disposition':'retain_exact_field','rationale':i['rationale']})
 for k in ['disposition','evidence_status','rationale','caveat']:entries.append({'revision':o['id'],'field':k,'old':h[k],'new':h[k],'disposition':'retain_exact_field','rationale':i['rationale']})
assert len(d['new_objects'])==4;changes=[];allbases=[]
for n in d['new_objects']:
 assert not c.execute('select 1 from object where id=?',(n['id'],)).fetchone();assert len(n['evidence'])==3
 for e in n['evidence']:assert c.execute('select 1 from revision where id=?',(e['basis_revision_id'],)).fetchone()
 prior=[]
 for f in w.glob('*operation-v*.json'):
  a=json.load(open(f));assert all(ch['id']!=n['id'] for ch in a.get('changes',[]));prior.append({'path':str(f),'sha256':hashlib.sha256(f.read_bytes()).hexdigest()})
 ch={'id':n['id'],'kind':'assessment','expectedVersion':None,'data':{'subject_id':n['subject_id'],'criteria':n['criteria'],'outcome':n['outcome'],'body':n['content']},'origins':[],'evidence':[{'basis':e['basis_revision_id'],'role':e['role'],'note':e['note']} for e in n['evidence']],'disposition':'recorded','evidenceStatus':None,'rationale':'T-0780: explicit source-bound administrative research adoption under settled Astra decision; no new identity judgment.','caveat':n['content']}
 for k,v in ch.items():entries.append({'object':n['id'],'field':k,'old':None,'new':v,'disposition':'create_settled_bounded_adoption','source_decision_sha256':sha})
 changes.append(ch);allbases.extend(n["evidence"])
op={'id':'T-0780/C0062-family-four-administrative-adoption-v1','actor':'Codex Sol mechanical implementation of settled Astra decision','reason':d['scope'],'dependencyReviewVersion':2,'changes':changes};files=[]
for name,obj in [('C-0062-family-four-administrative-adoption-operation-v1.json',op),('C-0062-family-four-administrative-adoption-field-table-v1.json',{'entries':entries,'retained_objects':4,'new_objects':4,'criteria_and_outcome_preserved_exactly':True})]:
 f=w/name;assert not f.exists();f.write_text(json.dumps(obj,ensure_ascii=False,indent=2)+'\n');files.append(f)
r={'task':'T-0780','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'builder_elapsed_seconds':time.time()-s,'source_decision_sha256':sha,'full_current_metadata_data_origins_evidence_matches':'PASS','existing_revisions':0,'new_objects':4,'basis_versions_exact':allbases,'criteria_and_outcome_preserved_exactly':True,'accepted_identity_and_administrative_split_unchanged':True,'stage_or_canonical_applies':0,'failed_attempts':0,'prior_pins':prior,'pins':[{'path':str(f),'sha256':hashlib.sha256(f.read_bytes()).hexdigest()} for f in files]};(w/'C-0062-family-four-administrative-adoption-receipt-v1.json').write_text(json.dumps(r,ensure_ascii=False,indent=2)+'\n');print(json.dumps(r['pins']))
