import json,pathlib,copy,hashlib,sqlite3,collections
b=pathlib.Path('evaluations/T-0780');w=b/'implementation/C0062-C0060-RESEARCH29-amendment-v2';w.mkdir(exist_ok=True);load=lambda p:json.load(open(p));sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest();p=b/'source-review/C-0062-C0060-remaining56-source-attribution-decisions-v2.json';d=load(p);assert sha(p)=='bcbbd793e421d7ff28162cd1daedf84df342d1b8e7542582081b60397363460a';am=d['explicit_cross_scope_amendment'];oldp=pathlib.Path(am['superseded_spec']);assert sha(oldp)==am['sha256'];old=load(oldp);newobj={o['current']['object_id']:o for o in d['objects']};oldobj={o['current']['object_id']:o for o in old['objects']};assert newobj.keys()==oldobj.keys();target=am['object'].rsplit('@',1)[0];assert all(newobj[k]==oldobj[k] for k in oldobj if k!=target);assert newobj[target]['current']==oldobj[target]['current'];prior=load(b/'implementation/C0060-next-six-BIO-queue-v1/current88-candidate-membership-inventory-v1.json');matches=[(ch,pin) for pin in prior['candidate_members'] for ch in load(pin['path'])['changes'] if ch['id']==target];assert len(matches)==1;oldch,oldpin=matches[0];op=load(oldpin['path']);assert sha(oldpin['path'])==oldpin['sha256'];out=copy.deepcopy(op);out['id']+='-explicit-C0060-research29-amendment-v2';out['reason']+=' Source-approved exact candidate amendment '+sha(p)+'; same baseline2→candidate3, all other native payloads unchanged.';newch=next(z for z in out['changes'] if z['id']==target);oldbody=newch['data']['body'];assert oldbody.count(am['old_candidate_clause'])==1;newbody=oldbody.replace(am['old_candidate_clause'],am['new_candidate_clause']);item=newobj[target];edit=[e for e in item['edits'] if e['field']=='data.body'];assert len(edit)==1 and newbody==edit[0]['new'];assert edit[0]['old']==item['current']['data']['body'];newch['data']['body']=newbody;extra=item['additional_required_support'];obj,version=extra['basis_revision_id'].rsplit('@',1);assert version.isdigit();edge={'object':obj,'version':int(version),'role':extra['role'],'note':extra['note']};assert newch['evidence'][-1]['object']=='AUDIT-T0110-C-0062';newch['evidence'].append(edge);assert newch['expectedVersion']==2
c=sqlite3.connect('file:'+str(b/'preparation/baseline-j281.sqlite')+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;cur=item['current'];h=dict(c.execute('select r.*,ob.kind from revision r join object ob on ob.id=r.object_id where r.id=?',(cur['id'],)).fetchone());assert all(cur[k]==v for k,v in h.items());assert cur['data']==dict(c.execute('select * from assessment where revision_id=?',(cur['id'],)).fetchone());assert int(c.execute('select max(version) from revision where object_id=?',(target,)).fetchone()[0])==2;bas=extra['basis_revision_id'];basis=dict(c.execute('select r.*,ob.kind from revision r join object ob on ob.id=r.object_id where r.id=?',(bas,)).fetchone());assert c.execute('select max(version) from revision where object_id=?',(obj,)).fetchone()[0]==int(version);basis['data']=dict(c.execute('select * from '+basis['kind']+' where revision_id=?',(bas,)).fetchone());basis['origins']=[dict(z) for z in c.execute('select * from origin where revision_id=?',(bas,))];basis['evidence']=[dict(z) for z in c.execute('select * from dependency where revision_id=? order by basis_revision_id,role',(bas,))]
for z in out['changes']:
 oldz=next(v for v in op['changes'] if v['id']==z['id'])
 if z['id']!=target:assert z==oldz
 else:
  restored=copy.deepcopy(z);restored['data']['body']=oldz['data']['body'];assert restored['evidence'].pop()==edge;assert restored==oldz
q=w/'remaining56-seven-revision-operation-v2.json';assert not q.exists();q.write_text(json.dumps(out,ensure_ascii=False,indent=2)+'\n');pin={'path':str(q),'sha256':sha(q)};q=w/'exact-candidate-source-oldmatch-and-support-order-receipt-v2.json';q.write_text(json.dumps({'new_source_pin':{'path':str(p),'sha256':sha(p)},'superseded_source_pin':{'path':str(oldp),'sha256':sha(oldp)},'superseded_member':oldpin,'new_member':pin,'all_other55_source_objects_and_six_target_payloads_exact_unchanged':True,'one_exact_previous_candidate_clause_replaced':True,'one_new_ordered_edge_after_existing_AUDIT':edge,'full_new_basis':basis,'same7native_revision_targets_not_extra_RESEARCH29_revision':True,'same_expectedVersion2_newcandidate3':True,'resolves_deferred_source_disposition_only_not_native_review_requests':True,'failed_attempts':0,'no_stage_apply_or_actual328_changes':True},ensure_ascii=False,indent=2)+'\n');print(pin);print('receipt',sha(q))
