import json,sqlite3,hashlib,datetime
from pathlib import Path
b=Path('evaluations/T-0780');dp=b/'source-review/C-0062-primary-Forsberg-decisions-v1.json';assert hashlib.sha256(dp.read_bytes()).hexdigest()=='572b263944074f3199daa9b57ce931d329b2a1eba67d4750f452a4b4a8bb039b';d=json.load(open(dp));c=sqlite3.connect('file:genealogy2/data/research.sqlite?mode=ro',uri=True);c.row_factory=sqlite3.Row;changes=[];entries=[];audit='AUDIT-T0110-C-0062';rid='R-9a4e7b22ce37e515b3f9e559';audithead=c.execute('select * from revision where object_id=? order by version desc limit1'.replace('limit1','limit 1'),(audit,)).fetchone();assert audithead['version']==1;prior=d['reuse']['full_prior_audit'];assert dict(c.execute('select * from assessment where revision_id=?',(audit+'@1',)).fetchone())==prior['data']
for h in d['reuse']['hashes']:assert hashlib.sha256(Path(h['path']).read_bytes()).hexdigest()==h['sha256']==h['actual_sha256']
def evidence(es):return [{'object':e['basis_revision_id'].rsplit('@',1)[0],'version':int(e['basis_revision_id'].rsplit('@',1)[1]),'role':e['role'],'note':e['note']} for e in es]
def ev(o,v,note):return {'object':o,'version':v,'role':'supports','note':note}
for item in d['objects']:
 old=item['current'];oid=old['object_id'];rev=old['id'];head=dict(c.execute('select r.*,o.kind from revision r join object o on o.id=r.object_id where r.object_id=? order by r.version desc limit 1',(oid,)).fetchone());assert all(head[k]==old[k] for k in head);data=dict(c.execute('select * from '+old['kind']+' where revision_id=?',(rev,)).fetchone());assert data==old['data'];orig=[dict(r) for r in c.execute('select * from origin where revision_id=?',(rev,))];es=[dict(r) for r in c.execute('select * from dependency where revision_id=?',(rev,))];assert orig==old['origins'];assert es==old['evidence'];edits={e['field']:e for e in item['edits']}
 for field,val in [('data.'+k,v) for k,v in data.items() if k!='revision_id']+[(k,old[k]) for k in ['caveat','rationale','disposition','evidence_status']]:
  e=edits.get(field)
  if e:assert val==e['old']
  entries.append({'object_id':oid,'revision_id':rev,'field':field,'old_wording':val,'new_wording':e['new'] if e else val,'Astra_disposition':item['disposition'],'Astra_rationale':e.get('reason',item.get('rationale')) if e else item.get('rationale'),'exact_prior_support':es,'settled_reuse_support':audit+'@1','field_edit':bool(e)})
 if not item['edits']:continue
 change={'id':oid,'kind':old['kind'],'expectedVersion':old['version'],'data':{k:v for k,v in data.items() if k!='revision_id'},'origins':[{'unit':o['unit_id'],'coverage':o['coverage'],'note':o['note']} for o in orig],'evidence':evidence(es),'disposition':old['disposition'],'evidenceStatus':old['evidence_status'],'rationale':old['rationale'],'caveat':old['caveat']}
 for e in item['edits']:
  loc=change['data'] if e['field'].startswith('data.') else change;field=e['field'].removeprefix('data.');assert loc[field]==e['old'];loc[field]=e['new']
 assert not any(e['object']==audit and e['version']==1 for e in change['evidence']);change['evidence'].append(ev(audit,1,'T-0780 exakt återbruk av full post139/två skanningar inklusive Forsbergs eget led och synliga rubrikgränser; ingen ny originalavläsning eller oberoende källa.'))
 assert not list(c.execute('select * from dependency where basis_revision_id=?',(rev,))),'Unexpected dependency: return to Astra before dependent operation'
 for field,v in change['data'].items():
  if field.endswith('_json') and isinstance(v,str):change['data'][field]=json.loads(v)
 changes.append(change)
newaid='AUDIT-T0780-C0062-reuse';adopt='ADOPT-T0780-C0062-P-0089';caveat='Enbart exakt återbruk av AUDIT-T0110-C-0062@1, samma handlinjerade post139 och båda skanningarna. Inga nya original har lästs; Forsbergs identitet, fullnamn, kön, ålder, civilstånd och släktskap olösta. Bläckskymt ord och kort olöst ort bevaras. Ingen synlig tryckt kolumnrubrik belagd; osynlig rubrik är inte ett avläst tomt fält. Övriga209källkontexter/semantiska kopior och oberoende slutgranskning ännu ej godkända.'
def new(oid,subject,criteria,outcome,body,es):return {'id':oid,'kind':'assessment','expectedVersion':None,'data':{'subject_id':subject,'criteria':criteria,'outcome':outcome,'body':body},'origins':[],'evidence':es,'disposition':'recorded','evidenceStatus':None,'rationale':'T-0780 AC2–3: exakt tillräckligt återbruk och avgjorda Forsbergskonsekvenser, inte ny originalläsning eller persongodkännande.','caveat':caveat}
changes.append(new(newaid,rid,'original_revision/1','reviewed_with_reservations',json.dumps({'task':'T-0780','scope':'C-0062 exact prior full post139 reuse + currentForsbergsubset','reuse':{k:v for k,v in d['reuse'].items() if k!='full_prior_audit'},'prior_full_extraction':json.loads(prior['data']['body']),'current_context_objects':32,'existing_revisions':31,'person_core_retained':'P-0089@1','broader_context_semantic_and_independent_approval':'pending, no completecitationacceptance'},ensure_ascii=False,indent=2),[ev(rid,1,'Samma avgränsade post139, inga Rrevisioner.'),ev(audit,1,'Exakt tidigare audit bevarad utan omtolkning.')]))
n=next(x for x in d['new_objects'] if x['id']==adopt);changes.append(new(adopt,'P-0089','bounded_source_adoption/1','reviewed_with_limits',n['content'],[ev('P-0089',1,'Personkärna behålls olöst.'),ev(rid,1,'Samma avgränsade post139.'),ev(audit,1,'Exakt tillräcklig tidigare fullbildsprövning.'),ev(newaid,1,'Explicit avgränsad adoption.')]))
assert len(changes)==33 and len(d['objects'])==32
for ch in changes[-2:]:assert c.execute('select count(*) from object where id=?',(ch['id'],)).fetchone()[0]==0
op={'id':'T-0780/C0062-Forsberg-candidate-v1','actor':'Codex Sol mechanical settled Astra implementation','reason':'T-0780 AC2–3 exaktC0062priorauditreuse/Forsbergsubset31currentrevisions+2newobjects; broader209context/semantic/independentpackageapproval pending.','dependencyReviewVersion':2,'changes':changes};p=b/'implementation/C-0062-Forsberg-candidate-operation-v1.json';assert not p.exists();p.write_text(json.dumps(op,ensure_ascii=False,indent=2)+'\n');tp=b/'implementation/C-0062-Forsberg-individual-consequence-table-v1.json';tp.write_text(json.dumps({'task':'T-0780','scope':'C-0062 Forsberg subset only','objects':32,'edited_objects':31,'retained_person':1,'entries':entries,'matched_all_actual_currentmeta_data_evidence_origins':True,'changedobject_incoming_dependency_count':0},ensure_ascii=False,indent=2)+'\n');rp=b/'implementation/C-0062-Forsberg-mechanical-receipt-v1.json';rp.write_text(json.dumps({'stage':'candidateonly_no_apply','source_subset_sha256':hashlib.sha256(dp.read_bytes()).hexdigest(),'pins':[{'path':str(z),'sha256':hashlib.sha256(z.read_bytes()).hexdigest()} for z in [dp,p,tp]],'existing_revisions':31,'new_objects':2,'original_reads':0,'record_prior_audit_and_personcore_unchanged':True,'incoming_dependencies_on31changedobjects':0,'broader209context_semantic_and_independentreview':'pending'},ensure_ascii=False,indent=2)+'\n');print({'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'fields':len(entries),'changes':33})
