import json,sqlite3,hashlib,copy,datetime
from pathlib import Path
b=Path('evaluations/T-0780');src=b/'implementation/C-0044-source-candidate-operation-v1.json';dp=b/'source-review/C-0044-primary-decisions-v1.json';bp=b/'source-review/C-0044-R1-dependency-dispositions-v1.json';d=json.load(open(dp));basis=json.load(open(bp));assert hashlib.sha256(bp.read_bytes()).hexdigest()=='d66262d823c3d34700c77e9c9c373a855b219e03d2082c62abde8858c5e34081';assert hashlib.sha256((b/'implementation/C-0044-R1-dependency-fanout-input-v1.json').read_bytes()).hexdigest()==basis['input_sha256'];op=json.load(open(src));initial=copy.deepcopy(op);c=sqlite3.connect('file:genealogy2/data/research.sqlite?mode=ro',uri=True);c.row_factory=sqlite3.Row;bd={x['object_id']:x for x in basis['decisions']};logs=[]
for o in d['objects']:
 if not o['edits'] or o['current']['kind']=='record':continue
 old=o['current'];oid=old['object_id'];rid=old['revision_id'];payload={'id':oid,'kind':old['kind'],'expectedVersion':int(rid.rsplit('@',1)[1]),'data':{k:v for k,v in old['data'].items() if k!='revision_id'},'origins':[{'unit':r['unit_id'],'coverage':r['coverage'],'note':r['note']} for r in c.execute('select * from origin where revision_id=?',(rid,))],'evidence':[{'object':e['basis_revision_id'].rsplit('@',1)[0],'version':int(e['basis_revision_id'].rsplit('@',1)[1]),'role':e['role'],'note':e['note']} for e in old['evidence']],'disposition':old['disposition'],'evidenceStatus':old['evidence_status'],'rationale':old['rationale'],'caveat':old['caveat']}
 for e in o['edits']:
  loc=payload['data'] if e['field'].startswith('data.') else payload;field=e['field'].removeprefix('data.');assert loc[field]==e['old'];loc[field]=e['new']
 for br in bd.get(oid,{}).get('basis_replacements',[]):
  matches=[e for e in payload['evidence'] if e['object']+'@'+str(e['version'])==br['old'] and e['role']==br['role'] and e['note']==br['old_note']];assert len(matches)==1;matches[0]['object'],v=br['new'].rsplit('@',1);matches[0]['version']=int(v);matches[0]['note']=br['new_note'];logs.append({'object_id':oid,'exact_basis_replacement':br,'Astra_rationale':bd[oid]['rationale']})
 for field,v in payload['data'].items():
  if field.endswith('_json') and isinstance(v,str):payload['data'][field]=json.loads(v)
 op['changes'].append(payload)
assert len(op['changes'])==23;assert op['changes'][:10]==initial['changes'];op['id']='T-0780/C0044-context-candidate-v1';op['reason']='T-0780 AC2–3 C0044 fullpost,14exactcontextrevisions,9newobjects and22individualdependencydispositions; expandedsemantic/independentfinalapproval pending. No staged/canonicalapply.';p=b/'implementation/C-0044-context-candidate-operation-v1.json';assert not p.exists();p.write_text(json.dumps(op,ensure_ascii=False,indent=2)+'\n');receipt={'stage':'draft_only_no_apply','existing_revisions':14,'new_objects':9,'explicit_basis_rebinds':logs,'individual_retains':[{k:x[k] for k in ['object_id','current_revision','disposition','rationale','dependency_resolution']} for x in basis['decisions'] if not x['basis_replacements']],'fullmetadata_evidence_origins_arrayorder_preserved':True,'source_first_draft_changes_prefix_unchanged':True,'remaining':'ExpandedsemanticfullconsequenceAstra+independentreview+exactpackagegate; audit metadata pending22 string historical creationstatus needs explicitsettledamendment','pins':[{'path':str(x),'sha256':hashlib.sha256(x.read_bytes()).hexdigest()} for x in [src,dp,bp,p,b/'implementation/C-0044-exact-context-consequence-plan-v1.json']]};(b/'implementation/C-0044-context-candidate-receipt-v1.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(hashlib.sha256(p.read_bytes()).hexdigest())
