import json,sqlite3,hashlib,time,datetime
from pathlib import Path
b=Path('evaluations/T-0780');w=b/'implementation';start=time.time();dp=b/'source-review/C-0106-event-dependency-dispositions-v1.json';assert hashlib.sha256(dp.read_bytes()).hexdigest()=='06012ba8312c3b153c3a00b33668b3537d82a7b39b31a12382a6e23e1f2db405';d=json.load(open(dp));sp=w/'C-0106-candidate-operation-v1.json';assert hashlib.sha256(sp.read_bytes()).hexdigest()=='448fbcefec2415419852ae26d8639b5b829ba562503083007cfd05ec848e6807';source=json.load(open(sp));event='E-marriage-P-0065-P-0066-1867';e=[x for x in source['changes'] if x['id']==event];assert len(e)==1 and e[0]['expectedVersion']==1;c=sqlite3.connect('file:genealogy2/data/research.sqlite?mode=ro',uri=True);c.row_factory=sqlite3.Row;assert c.execute('select max(sequence) from operation_payload').fetchone()[0]==281;changes=[];entries=[];fan=[];target={i['current']['object_id'] for i in d['objects']};oldpins=[]
for p in sorted(w.glob('*operation-v*.json')):
 x=json.load(open(p));assert not target&{z['id'] for z in x['changes']},'Unexpected candidate overlap: return Astra';oldpins.append({'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
for i in d['objects']:
 old=i['current'];oid=old['object_id'];rid=old['id'];head=dict(c.execute('select r.*,o.kind from revision r join object o on o.id=r.object_id where r.object_id=? order by r.version desc limit 1',(oid,)).fetchone());assert all(head[k]==old[k] for k in head);assert head['version']==1;data=dict(c.execute('select * from participation where revision_id=?',(rid,)).fetchone());assert data==old['data'];orig=[dict(x) for x in c.execute('select * from origin where revision_id=?',(rid,))];es=[dict(x) for x in c.execute('select * from dependency where revision_id=?',(rid,))];assert orig==old['origins'];assert es==old['evidence'];ch={'id':oid,'kind':'participation','expectedVersion':1,'data':{k:v for k,v in data.items() if k!='revision_id'},'origins':[{'unit':z['unit_id'],'coverage':z['coverage'],'note':z['note']} for z in orig],'evidence':[{'object':z['basis_revision_id'].rsplit('@',1)[0],'version':int(z['basis_revision_id'].rsplit('@',1)[1]),'role':z['role'],'note':z['note']} for z in es],'disposition':head['disposition'],'evidenceStatus':head['evidence_status'],'rationale':head['rationale'],'caveat':head['caveat']};assert len(i['edits'])==1 and i['edits'][0]['field']=='caveat';edit=i['edits'][0];assert ch['caveat']==edit['old'];ch['caveat']=edit['new'];assert ch['caveat']==e[0]['caveat']
 for f,v in [('data.'+k,v) for k,v in data.items() if k!='revision_id']+[(k,head[k]) for k in ['caveat','rationale','disposition','evidence_status']]:entries.append({'object_id':oid,'revision_id':rid,'field':f,'old_wording':v,'new_wording':edit['new'] if f=='caveat' else v,'disposition':'revise_exact_caveat' if f=='caveat' else 'retain_exact_field','Astra_rationale':edit['reason'] if f=='caveat' else i['rationale'],'old_support':es})
 for br in i['basis_replacements']:
  matches=[z for z in ch['evidence'] if z['object']+'@'+str(z['version'])==br['old'] and z['role']==br['role'] and z['note']==br['note']];assert len(matches)==1;matches[0]['object'],version=br['new'].rsplit('@',1);assert matches[0]['object']==event and int(version)==2;matches[0]['version']=int(version);entries.append({'object_id':oid,'revision_id':rid,'field':'evidence exact supports edge','old_wording':br['old'],'new_wording':br['new'],'role':br['role'],'note_unchanged':br['note'],'disposition':'explicit_individual_rebind','Astra_rationale':i['rationale']})
 incoming=[dict(z) for z in c.execute('select * from dependency where basis_revision_id=?',(rid,))];fan.append({'source_revision':rid,'incoming':incoming,'Astra_disposition':None if incoming else 'no_incoming_dependencies'});assert not incoming,'Unexpected participant fanout: return Astra before dependent operations'
 changes.append(ch)
assert len(changes)==2;op={'id':'T-0780/C0106-event-dependencies-v1','actor':'Codex Sol mechanical implementation of individual Astra event dependencies','reason':'T-0780 AC3: two exact marriage-participant caveat revisions and individually approved E@1→E@2 bindings after C0106 event operation; draft pending expanded semantic and independent exactpackage approval.','dependencyReviewVersion':2,'changes':changes};p=w/'C-0106-event-dependency-operation-v1.json';assert not p.exists();p.write_text(json.dumps(op,ensure_ascii=False,indent=2)+'\n');tp=w/'C-0106-event-dependency-consequence-table-v1.json';tp.write_text(json.dumps({'objects':2,'caveat_changes':2,'exact_rebinds':2,'entries':entries},ensure_ascii=False,indent=2)+'\n');fp=w/'C-0106-participant-incoming-dependency-check-v1.json';fp.write_text(json.dumps({'baseline':281,'participant_revisions':fan,'incoming_count':0,'no_further_rebind_or_resolution':True},ensure_ascii=False,indent=2)+'\n');for_check=all(hashlib.sha256(Path(z['path']).read_bytes()).hexdigest()==z['sha256'] for z in oldpins);assert for_check;receipt={'task':'T-0780','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'builder_elapsed_seconds':time.time()-start,'stage_or_canonical_applies':0,'source_original_reads':0,'all_currentmeta_data_evidence_origins_exactoldmatches':'PASS','previous_candidate_overlaps':0,'first_candidate_preserved':True,'source_event_operation_must_precede':str(sp),'objects':2,'field_entries':len(entries),'individual_rebinds':2,'new_objects':0,'incoming_dependencies':0,'pending_metadata_amendment':'First sourceaudit outside33eventparticipant_dependency_dispositions field records historical awaiting status; requires explicit Astra metadata amendment before final packaging. No silent rewrite.','previous_candidate_pins':oldpins,'pins':[{'path':str(z),'sha256':hashlib.sha256(z.read_bytes()).hexdigest()} for z in [dp,sp,p,tp,fp]],'failures':[]};(w/'C-0106-event-dependency-receipt-v1.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print({'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'fields':len(entries),'incoming':0})
