import json,hashlib,sqlite3
from pathlib import Path
b=Path('evaluations/T-0780');rawp=b/'source-review/C-0043-primary-raw-v1.json';dp=b/'source-review/C-0043-primary-decisions-v1.json';raw=json.load(open(rawp));dec=json.load(open(dp));rid='R-884d16c907cc272d30bd2cc8';tid='TR-T0780-C0043-fullpost';aid='AUDIT-T0780-C0043';fields=[]
for header,value in raw['fields']:
 if header=='18 by':value='J.A. [efternamn oläst]'
 fields.append({'printed_group':header,'raw':None if value=='blank' else value,'state':'blank' if value=='blank' else 'uncertain' if '[?' in value or 'unresolved' in value or 'oläst' in value or 'not conclusively' in value or 'kept uncertain' in value else 'read'})
text=raw['header']+'\nMålpost135; hela relevanta posten, båda uppslagssidorna.\n'+'\n'.join(x['printed_group']+': '+(x['raw'] if x['raw'] is not None else '[tomt]') for x in fields)+'\nMarginaler: '+raw['margins']
caveat='Dopförrättarens efternamn är oläst. E.G. J[onsson?] läsreserverat; båda vittneshustrurna namnlösa. Ultervattnets tillämpning på båda vittnesparen är inte slutligt avgjord. Inga vittnessläktskap eller nya personidentiteter följer. Könstally bevaras som källfält utan ny personkönsbedömning. Äldre rättelser och råavskrifter bevaras.'
def ev(o,v,role='supports',note='T-0780 avgränsad post135, ingen ny oberoende historisk källa.'):
 return {'object':o,'version':v,'role':role,'note':note}
def change(oid,kind,data,evidence):return {'id':oid,'kind':kind,'expectedVersion':None,'data':data,'origins':[],'evidence':evidence,'disposition':'recorded','evidenceStatus':'TRANSCRIBED' if kind=='transcription' else None,'rationale':'T-0780 AC2–3: mekanisk implementation av Astras avgjorda C0043beslut; full relevant post och bounded native adoption.','caveat':caveat}
changes=[change(tid,'transcription',{'record_id':rid,'text':text,'reading_note':'21 tryckta kolumngrupper med föräldracellerna separerade och sammanslagna tomgrupper uttryckliga. '+raw['exposure']},[ev(rid,1)]),change(aid,'assessment',{'subject_id':rid,'criteria':'source_reread/1','outcome':'confirmed_with_uncertainties','body':json.dumps({'task':'T-0780','citation':'C-0043','record_version':rid+'@1','source_sha256':raw['source_sha256'],'header':raw['header'],'fields':fields,'margins':raw['margins'],'exposure':raw['exposure'],'method':raw['method'],'source_decision':dec['source_decision'],'read_at_utc':raw['time'],'primary_raw_file':str(rawp),'primary_decision_file':str(dp),'prior_current_objects_dispositions_count':len(dec['items']),'semantic_consequences_remaining':'Primary46objects settled individually; global semantic candidate coverage and independentreview pending.'},ensure_ascii=False,indent=2)},[ev(rid,1),ev(tid,1)])]
for pid in ['P-0002','P-0048','P-0049']:
 changes.append(change('ADOPT-T0780-C0043-'+pid,'assessment',{'subject_id':pid,'criteria':'bounded_source_adoption/1','outcome':'reviewed_with_limits','body':'C-0043 post135: full21trycktafältgrupper dokumenteras i '+tid+' och '+aid+'. Bounded adoption av redan prövad barn-/föräldrarad för '+pid+'. Befintlig research och person-/grindutfall behålls enligt Astras individuella primärbeslut. Inget helperson-, PK-, träd- eller livsbildsgodkännande; övriga källor och öppna frågor ligger kvar. '+caveat},[ev(pid,1),ev(rid,1),ev(tid,1),ev(aid,1)]))
# Bind actual current person versions rather than assuming1.
c=sqlite3.connect('file:genealogy2/data/research.sqlite?mode=ro',uri=True)
for ch in changes:
 for e in ch['evidence']:
  if e['object'].startswith('P-'):e['version']=c.execute('select max(version) from revision where object_id=?',(e['object'],)).fetchone()[0]
 fornew=c.execute('select count(*) from object where id=?',(ch['id'],)).fetchone()[0];assert fornew==0
op={'id':'T-0780/C0043-candidate-v1','actor':'Codex Sol mechanical implementation of settled Astra decisions','reason':'T-0780 AC2–3 C0043 fullpost extraction/sourceaudit/boundedresearchadoption; draft only pending full semantic and independent review.','dependencyReviewVersion':2,'changes':changes};out=b/'implementation/C-0043-candidate-operation-v1.json';out.write_text(json.dumps(op,ensure_ascii=False,indent=2)+'\n')
receipt={'stage':'draft_only_no_apply','operation_path':str(out),'operation_sha256':hashlib.sha256(out.read_bytes()).hexdigest(),'decision_sha256':hashlib.sha256(dp.read_bytes()).hexdigest(),'raw_sha256':hashlib.sha256(rawp.read_bytes()).hexdigest(),'new_objects':5,'existing_object_revisions':0,'retained_current_objects':dec['items'],'outstanding':'Primary semanticcandidate screening and independent exactpackage review; no canonical/stageapply performed.'};(b/'implementation/C-0043-mechanical-draft-receipt-v1.json').write_text(json.dumps(receipt,ensure_ascii=False,indent=2)+'\n');print(receipt['operation_sha256'])
