import json,sqlite3,hashlib,time,datetime
from pathlib import Path
b=Path('evaluations/T-0780');work=b/'implementation';start=time.time();dp=b/'source-review/C-0106-primary-decisions-v1.json';rp=b/'source-review/C-0106-primary-raw-v1.json';ap=b/'fresh-independent-review/C-0106-comparative-amendment-v1.json';expected={dp:'83ca4e6960c183b46df20757d37082786742373988124b1986f836146d6640c8',rp:'161dbfc1a2eeafa62440cdeb416a9dc419376de401ded01c2194134153a0d81e',ap:'b601d23cf9eed50681c0e9bb6d622e6386200cdc6d40409704715dd8805f6f21'}
for p,h in expected.items():assert hashlib.sha256(p.read_bytes()).hexdigest()==h
d=json.load(open(dp));raw=json.load(open(rp));am=json.load(open(ap));assert len(raw['header_groups'])==18;c=sqlite3.connect('file:genealogy2/data/research.sqlite?mode=ro',uri=True);c.row_factory=sqlite3.Row;assert c.execute('select max(sequence) from operation_payload').fetchone()[0]==281;assert hashlib.sha256(Path(raw['original']['path']).read_bytes()).hexdigest()==raw['original']['sha256'];cur={r['object_id']:dict(r) for r in c.execute('select r.*,o.kind from revision r join object o on o.id=r.object_id where not exists(select 1 from revision n where n.object_id=r.object_id and n.version>r.version)')};changes=[];fields=[];fan=[];oldpins=[];edited={x['current']['object_id'] for x in d['objects'] if x['edits']}
for p in sorted(work.glob('*operation-v*.json')):
 x=json.load(open(p));assert not edited&{ch['id'] for ch in x['changes']},'Unexpected overlap: return for explicit merge';oldpins.append({'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()})
def full(oid):
 r=cur[oid].copy();rid=r['id'];r['data']=dict(c.execute('select * from '+r['kind']+' where revision_id=?',(rid,)).fetchone());r['evidence']=[dict(x) for x in c.execute('select * from dependency where revision_id=?',(rid,))];r['origins']=[dict(x) for x in c.execute('select * from origin where revision_id=?',(rid,))];return r
for i in d['objects']:
 old=i['current'];oid=old['object_id'];r=full(oid);assert r['id']==old['revision_id'];assert r['data']==old['data'];assert r['evidence']==old['evidence'];assert all(r[k]==old[k] for k in ['kind','disposition','evidence_status','rationale','caveat']);edits={e['field']:e for e in i['edits']}
 for f,v in [('data.'+k,v) for k,v in r['data'].items() if k!='revision_id']+[(k,r[k]) for k in ['caveat','rationale','disposition','evidence_status']]:
  e=edits.get(f)
  if e:assert e['old']==v
  fields.append({'object_id':oid,'revision_id':r['id'],'field':f,'old_wording':v,'new_wording':e['new'] if e else v,'Astra_disposition':i['disposition'],'Astra_rationale':e['reason'] if e else i['rationale'],'registered_support':r['evidence'],'source_basis':[str(rp),str(ap)],'field_edit':bool(e)})
 if not i['edits']:continue
 ch={'id':oid,'kind':r['kind'],'expectedVersion':r['version'],'data':{k:v for k,v in r['data'].items() if k!='revision_id'},'origins':[{'unit':z['unit_id'],'coverage':z['coverage'],'note':z['note']} for z in r['origins']],'evidence':[{'object':z['basis_revision_id'].rsplit('@',1)[0],'version':int(z['basis_revision_id'].rsplit('@',1)[1]),'role':z['role'],'note':z['note']} for z in r['evidence']],'disposition':r['disposition'],'evidenceStatus':r['evidence_status'],'rationale':r['rationale'],'caveat':r['caveat']}
 for e in i['edits']:
  loc=ch['data'] if e['field'].startswith('data.') else ch;f=e['field'].removeprefix('data.');assert loc[f]==e['old'];loc[f]=e['new']
 for f,v in ch['data'].items():
  if f.endswith('_json') and isinstance(v,str):ch['data'][f]=json.loads(v)
 changes.append(ch)
 incoming=[]
 for z in c.execute('select * from dependency where basis_revision_id=?',(r['id'],)):
  z=dict(z);did=z['revision_id'].rsplit('@',1)[0];incoming.append({'edge':z,'current_full_native':full(did),'dependent_current':cur[did]['id']==z['revision_id'],'Astra_disposition':None,'Astra_rationale':None,'basis_replacements':None})
 fan.append({'changed_revision':r['id'],'proposed_version':r['version']+1,'incoming':incoming})
assert len(changes)==3
record='R-3a1e056cc4652ec4b1a2b719';assert cur[record]['version']==1;tid='TR-T0780-C0106-fullpost';aid='AUDIT-T0780-C0106';caveat=raw['source_limits']+' '+raw['current_stronger_support']
def ev(o,v,note='T-0780 C0106 samma avgränsade post nr1, ingen extra oberoende evidensröst.'):return {'object':o,'version':v,'role':'supports','note':note}
def new(oid,kind,data,es):return {'id':oid,'kind':kind,'expectedVersion':None,'data':data,'origins':[],'evidence':es,'disposition':'recorded','evidenceStatus':'TRANSCRIBED' if kind=='transcription' else None,'rationale':'T-0780 AC2–3: full C0106post och avgränsad adoption enligt Astras individuella avgöranden, ingen persongrindsuppgradering.','caveat':caveat}
changes.append(new(tid,'transcription',{'record_id':record,'text':json.dumps({'bounds':raw['bounds'],'printed_header_groups':raw['header_groups'],'all_own_raw_fields':raw['raw'],'digit_reasoning_and_source_reservations':raw['digit_reasoning'],'source_limits':raw['source_limits']},ensure_ascii=False,indent=2),'reading_note':raw['method']+' Reviewer additive comparison preserved at '+str(ap)+'. Both own rows, giftoman note, all18printed subfields and blanks included.'},[ev(record,1)]))
changes.append(new(aid,'assessment',{'subject_id':record,'criteria':'source_reread/1','outcome':'reviewed_with_reservations','body':json.dumps({'task':'T-0780','scope':'C-0106 nr1 full couple/giftoman post','original':raw['original'],'primary_raw_path':str(rp),'primary_raw_sha256':expected[rp],'primary_method_exposure':raw['method'],'full_raw_source_fields':{'bounds':raw['bounds'],'header_groups':raw['header_groups'],'raw':raw['raw'],'digit_reasoning':raw['digit_reasoning'],'source_limits':raw['source_limits']},'comparative_amendment_path':str(ap),'comparative_amendment_sha256':expected[ap],'current_selected_context_decisions_path':str(dp),'current_selected_context_decisions_sha256':expected[dp],'current_selected_context_objects':33,'existing_revision_objects':3,'record_version_retained':record+'@1','expanded_semantic_status':'pending','outside33eventparticipant_dependency_dispositions':'Two currenteventparticipant dependencies returned Astra; awaiting individual dispositions','independent_exactpackage_review':'pending'},ensure_ascii=False,indent=2)},[ev(record,1),ev(tid,1)]))
for n in d['new_objects']:
 if n['id'] in [tid,aid]:continue
 pid=n['subject_id'];changes.append(new(n['id'],'assessment',{'subject_id':pid,'criteria':'bounded_source_adoption/1','outcome':'reviewed_with_limits','body':n['content']},[ev(pid,cur[pid]['version']),ev(record,1),ev(tid,1),ev(aid,1)]))
assert len(changes)==8
for ch in changes[3:]:assert ch['id'] not in cur
op={'id':'T-0780/C0106-candidate-v1','actor':'Codex Sol mechanical settled Astra implementation','reason':'T-0780 AC2–3 C0106 fullpost/33individualcontexts/3exactrevisions/5newobjects; expandedsemantic/dependency/independentapproval pending; draft only.','dependencyReviewVersion':2,'changes':changes};p=work/'C-0106-candidate-operation-v1.json';assert not p.exists();p.write_text(json.dumps(op,ensure_ascii=False,indent=2)+'\n');tp=work/'C-0106-selected-context-consequence-table-v1.json';tp.write_text(json.dumps({'objects':33,'edited_objects':3,'retained_objects':30,'entries':fields,'expanded_semantics_pending':True},ensure_ascii=False,indent=2)+'\n');fp=work/'C-0106-three-revision-incoming-dependency-input-v1.json';fp.write_text(json.dumps({'metadata_only_no_rebind':True,'baseline':281,'changes':fan,'incoming_count':sum(len(z['incoming']) for z in fan),'outside_selected33':True},ensure_ascii=False,indent=2)+'\n');receipt=work/'C-0106-mechanical-candidate-receipt-v1.json';receipt.write_text(json.dumps({'at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'builder_elapsed_seconds':time.time()-start,'stage_or_canonical_applies':0,'new_original_reads':0,'current_versions_full_data_meta_evidence_origins_and_oldmatches':'PASS','prior_candidate_overlap':0,'objects':33,'fields':len(fields),'existing_revisions':3,'new_objects':5,'incoming_dependent_objects':2,'dependent_dispositions':'pending; no automatic rebind or resolves','prior_candidates_preserved':oldpins,'pins':[{'path':str(z),'sha256':hashlib.sha256(z.read_bytes()).hexdigest()} for z in [dp,rp,ap,p,tp,fp]],'failures':[{'action':'Locate reviewer amendment','event':'Initial source-review guessed filename absent','resolution':'rg located actual fresh-independent-review/C-0106-comparative-amendment-v1.json, exacthash verified, no mutation'}]},ensure_ascii=False,indent=2)+'\n');assert all(hashlib.sha256(Path(z['path']).read_bytes()).hexdigest()==z['sha256'] for z in oldpins);print({'sha256':hashlib.sha256(p.read_bytes()).hexdigest(),'fields':len(fields),'incoming':2})
