import json,pathlib,hashlib,sqlite3,copy,time
b=pathlib.Path('evaluations/T-0780');w=b/'implementation/C0069-eight-observation-queue-v1';load=lambda p:json.load(open(p));sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def save(n,d):
 p=w/n;assert not p.exists();p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');return {'path':str(p),'sha256':sha(p)}
c=sqlite3.connect('file:'+str(b/'preparation/baseline-j281.sqlite')+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;r=load(w/'settled-module-receipt-v1.json');pin=next(p for p in r['candidate_modules'] if 'operation-' in p['path']);priorp=b/'implementation/C0069-corrected-full13-queue-v1/concrete-current98-partial-sequence-and-constraint-proposal-v1.json';prior=load(priorp);seq=copy.deepcopy(prior['sequence']);seq.insert(len(seq)-1,pin);heads={z['object_id']:z['version'] for z in c.execute('select object_id,max(version) version from revision group by object_id')};updates={x['id']:{'index':i+1,'expectedVersion':x['expectedVersion'],'newVersion':(x['expectedVersion'] or 0)+1} for i,p in enumerate(seq) for x in load(p['path'])['changes']};targets={};viol=[];constraints=[]
for i,p in enumerate(seq):
 op=load(p['path']);assert sha(p['path'])==p['sha256'];p['index']=i+1;p['operation_id']=op['id'];p['targets']=[]
 for x in op['changes']:
  assert x['id'] not in targets,('overlap',x['id']);assert heads.get(x['id'])==x['expectedVersion'];targets[x['id']]=(x,p);p['targets'].append({'id':x['id'],'expectedVersion':x['expectedVersion'],'payload_sha256':hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()})
  for e in x['evidence']:
   assert set(e)=={'object','version','role','note'} and type(e['version']) is int and e['version']>0
   if e['object'] in updates:constraints.append({'target':x['id'],'operation':op['id'],'index':i+1,'edge':e,'basis_update':updates[e['object']]})
   if heads.get(e['object'])!=e['version'] and not any(t['id']==e['object'] and (t['expectedVersion'] or 0)+1==e['version'] for t in op['changes']):viol.append({'target':x['id'],'edge':e,'proposed_current_head':heads.get(e['object'])})
 for x in op['changes']:heads[x['id']]=(x['expectedVersion'] or 0)+1
assert len(seq)==99 and len(targets)==721;assert viol==prior['static_head_order_violations'];fan=[];native={}
for ch in load(pin['path'])['changes']:
 for row in c.execute('select d.*,r.object_id,r.version,not exists(select 1 from revision n where n.object_id=r.object_id and n.version>r.version) is_current from dependency d join revision r on r.id=d.revision_id where d.basis_revision_id in(select id from revision where object_id=?)',(ch['id'],)):
  row=dict(row);fan.append({'changed_target':ch['id'],'edge':row,'primary_individual_disposition':None,'current_candidate_if_revised':targets.get(row['object_id'])});rid=row['revision_id']
  if rid not in native:
   o=dict(c.execute('select r.*,ob.kind from revision r join object ob on ob.id=r.object_id where r.id=?',(rid,)).fetchone());o['data']=dict(c.execute('select * from '+o['kind']+' where revision_id=?',(rid,)).fetchone());o['origins']=[dict(t) for t in c.execute('select * from origin where revision_id=?',(rid,))];o['evidence']=[dict(t) for t in c.execute('select * from dependency where revision_id=?',(rid,))];native[rid]=o
inp=save('all-history-observation-incoming-full-native-input-v1.json',{'fanouts':fan,'full_native_objects':native,'prior_C425_deferred_not_retain_or_duplicate':True,'current_ready_target_overlap_count':0,'individual_dispositions_pending':True,'prior_seven_API_questions_unchanged':viol})
m=save('current99-candidate-membership-inventory-v1.json',{'prior_proposal_pin':{'path':str(priorp),'sha256':sha(priorp)},'candidate_members':seq,'unique_targets':721,'member_count':99,'new_targets_this_TR_observation_phase':8,'duplicate_targets':0,'global_source_approval':False})
q=save('concrete-current99-partial-sequence-and-constraint-proposal-v1.json',{'sequence':seq,'members':99,'unique_targets':721,'constraints':constraints,'static_head_order_violations':viol,'membership_pin':m,'fresh_primary_hash_binding_required':True,'no_native_PASS_or_stage':True})
f=save('bounded-TR-plus-observation-handoff-and-production-v1.json',{'TR_phase_receipt_pin':{'path':str(b/'implementation/C0069-corrected-full13-queue-v1/bounded-corrected13-TR-handoff-and-production-v1.json'),'sha256':sha(b/'implementation/C0069-corrected-full13-queue-v1/bounded-corrected13-TR-handoff-and-production-v1.json')},'source_pins':r['source_pins'],'input_pin':inp,'membership_pin':m,'proposal_pin':q,'new_TR_objects':1,'observation_revisions':7,'observation_retains':1,'full_field_entries':72,'all_history_incoming_edges':len(fan),'current_incoming_edges':sum(x['edge']['is_current'] for x in fan),'full_native_referencers':len(native),'failed_mechanical_attempts':[{'script':'finalize_C0069_TR_observation_phase_v1.py','reason':'Initial observation placement preceded C425 E-birth96 retaining O96@1. Preserved failed proposal; moved payload-identical seven-observation module after existing consumers and before final source operation, requiring primary hash approval. No evidence rebind or field change.'}],'observed_seconds_since_TR_candidate':time.time()-(b/'implementation/C0069-corrected-full13-queue-v1/full-transcription-operation-v1.json').stat().st_mtime,'prebuild_reads_excluded':True,'source_coverage_failure_and_nonblind_repair_not_zero_production_preserved_in_source_and_TR_receipts':True,'model_usage_root_collect_after_final':True,'no_stage_probe_apply_actual328_modification':True});print(json.dumps({'input':inp,'membership':m,'proposal':q,'handoff':f,'fanout':len(fan),'native':len(native),'current':sum(x['edge']['is_current'] for x in fan),'constraints':len(constraints)}))
