import json,pathlib,sqlite3,hashlib,time
start=time.time();b=pathlib.Path('evaluations/T-0780');w=b/'implementation/C0060-next-six-BIO-queue-v1';folders=[w,b/'implementation/C0060-principal-BIO-queue-v1',b/'implementation/C0060-P0030-six-research-queue-v1'];load=lambda p:json.load(open(p));c=sqlite3.connect('file:'+str(b/'preparation/baseline-j281.sqlite')+'?mode=ro',uri=True);c.row_factory=sqlite3.Row

def sha(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def save(n,d):p=w/n;assert not p.exists();p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');return {'path':str(p),'sha256':sha(p)}
receipts=[load(f/'settled-module-receipt-v1.json') for f in folders];pins=[p for r in receipts for p in r['candidate_modules'] if 'operation-' in p['path']];sources=[p for r in receipts for p in r['source_pins']];assert len(pins)==4;priorp=b/'implementation/C0060-first-settled-queue-v1/concrete-current84-partial-sequence-and-constraint-proposal-v1.json';old=load(priorp);seq=old['sequence'][:-1]+pins+old['sequence'][-1:];assert 'two-records-last' in seq[-1]['path'];heads={z['object_id']:z['version'] for z in c.execute('select object_id,max(version) version from revision group by object_id')};targets={};updates={ch['id']:{'operation_id':load(p['path'])['id'],'index':i+1,'expectedVersion':ch['expectedVersion'],'newVersion':(ch['expectedVersion'] or 0)+1} for i,p in enumerate(seq) for ch in load(p['path'])['changes']};constraints=[];schema=[];viol=[];support=0
for i,p in enumerate(seq):
 op=load(p['path']);assert sha(p['path'])==p['sha256'];p['index']=i+1;p['operation_id']=op['id'];p['targets']=[]
 for ch in op['changes']:
  assert ch['id'] not in targets;targets[ch['id']]=(ch,p);assert heads.get(ch['id'])==ch['expectedVersion'];p['targets'].append({'id':ch['id'],'expectedVersion':ch['expectedVersion'],'payload_sha256':hashlib.sha256(json.dumps(ch,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()})
  for e in ch['evidence']:
   support+=1
   if set(e)!={'object','version','role','note'} or type(e['version']) is not int or e['version']<1:schema.append({'target':ch['id'],'edge':e})
   if e['object'] in updates:constraints.append({'dependent':ch['id'],'dependent_operation':op['id'],'index':i+1,'edge':e,'basis_update':updates[e['object']],'primary_hash_binding_required':True})
   if heads.get(e['object'])!=e['version'] and not any(z['id']==e['object'] and (z['expectedVersion'] or 0)+1==e['version'] for z in op['changes']):viol.append({'dependent':ch['id'],'edge':e,'actual_proposed_head':heads.get(e['object'])})
 for ch in op['changes']:heads[ch['id']]=(ch['expectedVersion'] or 0)+1
assert len(targets)==665 and len(seq)==88 and not schema and not viol
fan=[];native={};checks=[];special=[];retains=[];reuse=[]
for sp in sources:
 for i,item in enumerate(load(sp['path'])['objects']):
  o=item['current']
  if not item['edits']:
   (reuse if item['disposition']=='reuse_exact_previously_settled_revision' else retains).append({'object':o['id'],'disposition':item['disposition'],'source_pin':sp,'pointer':'/objects/'+str(i)});continue
  ch=targets[o['object_id']][0];assert ch['disposition']==o['disposition'] and ch['evidenceStatus']==o['evidence_status'];prefix=[{'object':e['basis_revision_id'].rsplit('@',1)[0],'version':int(e['basis_revision_id'].rsplit('@',1)[1]),'role':e['role'],'note':e['note']} for e in o['evidence']];assert ch['evidence'][:len(prefix)]==prefix
  if 'outcome' in o['data']:assert ch['data']['outcome']==o['data']['outcome']
  added=[]
  for e in ([item['evidence_addition']] if item.get('evidence_addition') else [])+([item['additional_required_support']] if item.get('additional_required_support') else [])+item.get('additional_required_supports',[]):
   rid=e['basis_revision_id'];obj,version=rid.rsplit('@',1);assert version.isdigit() and int(version)>0;added.append({'object':obj,'version':int(version),'role':e['role'],'note':e['note']})
  assert ch['evidence'][len(prefix):]==added
  if o['object_id']=='BIO-P-0069':assert [e['object'] for e in added]==['TR-T0780-C0060-index-group1-fullpost','O-P-0069-s241-own-fields','O-P-0070-s241-own-fields'];special.append({'target':o['id'],'exact_ordered_added_evidence':added})
  if o['object_id']=='BIO-P-0073':assert added[-1]['object']=='O-P-0073-s241-birth-day-comparison' and added[-1]['version']==1;special.append({'target':o['id'],'exact_ordered_added_evidence':added})
  checks.append({'object':o['id'],'source_pin':sp,'status_and_outcome_if_present_preserved':True,'whole_older_ordered_evidence_prefix_preserved':True,'exact_added_evidence_array_order':added})
  for e in c.execute('select d.*,r.object_id,r.version,not exists(select 1 from revision n where n.object_id=r.object_id and n.version>r.version) is_current from dependency d join revision r on r.id=d.revision_id where d.basis_revision_id in(select id from revision where object_id=?)',(o['object_id'],)):
   e=dict(e);fan.append({'changed_target':o['object_id'],'edge':e,'primary_individual_disposition':None});rid=e['revision_id']
   if rid not in native:
    z=dict(c.execute('select r.*,ob.kind from revision r join object ob on ob.id=r.object_id where r.id=?',(rid,)).fetchone());z['data']=dict(c.execute('select * from '+z['kind']+' where revision_id=?',(rid,)).fetchone());z['origins']=[dict(q) for q in c.execute('select * from origin where revision_id=?',(rid,))];z['evidence']=[dict(q) for q in c.execute('select * from dependency where revision_id=? order by basis_revision_id,role',(rid,))];native[rid]=z
assert len(checks)==11 and len(retains)==4 and len(reuse)==1
p=save('all-history-incoming-exact-support-order-and-reuse-input-v1.json',{'incoming_edges':fan,'full_native_objects':native,'individual_metadata_and_support_checks':checks,'special_BIO69_two_ordered_OBIO73_comparison':special,'retains':retains,'prior_settled_reuse':reuse,'reuse_binding_pin':{'path':str(w/'exact-BIO29-prior-candidate-reuse-binding-v1.json'),'sha256':sha(w/'exact-BIO29-prior-candidate-reuse-binding-v1.json')},'no_new_BIO29_change_or_serial_version':True});m=save('current88-candidate-membership-inventory-v1.json',{'previous_current84_pin':{'path':str(priorp),'sha256':sha(priorp)},'candidate_members':seq,'unique_targets':665,'member_count':88,'new_targets':11,'duplicate_targets':0,'schema_errors':schema,'source_flags_preserved_as_data':True,'incomplete_scopes':['C0060remaining','C0069','whole10finalreview','actual328individualrequests'],'global_source_approval':False});q=save('concrete-current88-partial-sequence-and-constraint-proposal-v1.json',{'sequence':seq,'unique_targets':665,'members':88,'evidence_entries_checked':support,'constraints':constraints,'static_head_order_violations':viol,'all_newBIO_research_modules_before_C0060_R2':True,'primary_fresh_global_hash_binding_required':True,'membership_pin':m,'full_individual_input_pin':p,'native_PASS_or_stage_authority':False});first=min(f.stat().st_mtime for f in w.glob('*operation-v1.json'));final=save('bounded-four-module-BIO-research-handoff-and-production-v1.json',{'source_pins':sources,'input_pin':p,'membership_pin':m,'proposal_pin':q,'revisions':11,'retains':4,'previous_exact_revision_reuse':1,'full_individual_field_rows':118,'all_current_history_incoming_edges':len(fan),'whole_native_incoming_objects':len(native),'no_new_person_cores_or_protected_review_changes':True,'failed_attempts':[{'reason':'Initial whole CLI enriched vs SQL current equality assertion failed on derived current and joined origin enrichment. Native persisted headers/data/evidence and exact ordered origin columns match baseline; prior enriched source preserved.'},{'reason':'Follow-up shell attempted builder filename before creation after first assertion failure; no script ran/no candidate changed.'}],'observed_elapsed_from_first_BIO_candidate_seconds':time.time()-first,'elapsed_excludes_initial_prebuild_reads':True,'elapsed_finalize_seconds':time.time()-start,'model_usage_unknown_root_collect_after_final':True,'stage_probe_apply_resolution_actual328_modification_count':0,'completed_exact_four_modules_no_more_queue_taken':True});print({'input':p,'membership':m,'proposal':q,'final':final,'incoming':len(fan),'constraints':len(constraints),'elapsed':time.time()-first})
