import json,pathlib,hashlib,sqlite3,time,copy
b=pathlib.Path('evaluations/T-0780');w=b/'implementation/C0069-corrected-full13-queue-v1';load=lambda p:json.load(open(p));sha=lambda p:hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def save(n,d):
 p=w/n;assert not p.exists();p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');return {'path':str(p),'sha256':sha(p)}
c=sqlite3.connect('file:'+str(b/'preparation/baseline-j281.sqlite')+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;receipt=load(w/'settled-module-receipt-v1.json');pin=next(p for p in receipt['candidate_modules'] if 'operation-' in p['path']);op=load(pin['path']);ch=op['changes'][0];spec=load(receipt['source_pins'][0]['path']);n=spec['new_objects'][0];assert ch['data']['text']==n['content'] and ch['expectedVersion'] is None;assert sha(spec['supersedes_candidate_only']['path'])==spec['supersedes_candidate_only']['sha256'];assert not c.execute('select 1 from object where id=?',(ch['id'],)).fetchone();rawsha='626b3bc381d81b8ba0ccf9969e61c2baa3d9a84325e5a9137c7ffb04b6469648';raw=[p for p in (b/'source-review').rglob('*.json') if sha(p)==rawsha];assert len(raw)==1
priorp=b/'implementation/C0060-final-two-key-source-queue-v1/concrete-current97-partial-sequence-and-constraint-proposal-v1.json';prior=load(priorp);seq=[pin]+copy.deepcopy(prior['sequence']);heads={r['object_id']:r['version'] for r in c.execute('select object_id,max(version) version from revision group by object_id')};updates={x['id']:{'index':i+1,'expectedVersion':x['expectedVersion'],'newVersion':(x['expectedVersion'] or 0)+1} for i,p in enumerate(seq) for x in load(p['path'])['changes']};targets={};viol=[];constraints=[]
for i,p in enumerate(seq):
 o=load(p['path']);assert sha(p['path'])==p['sha256'];p['index']=i+1;p['operation_id']=o['id'];p['targets']=[]
 for x in o['changes']:
  assert x['id'] not in targets;assert heads.get(x['id'])==x['expectedVersion'];targets[x['id']]=(x,p);p['targets'].append({'id':x['id'],'expectedVersion':x['expectedVersion'],'payload_sha256':hashlib.sha256(json.dumps(x,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()})
  for e in x['evidence']:
   assert set(e)=={'object','version','role','note'} and type(e['version']) is int and e['version']>0
   if e['object'] in updates:constraints.append({'target':x['id'],'operation':o['id'],'index':i+1,'edge':e,'basis_update':updates[e['object']]})
   if heads.get(e['object'])!=e['version'] and not any(t['id']==e['object'] and (t['expectedVersion'] or 0)+1==e['version'] for t in o['changes']):viol.append({'target':x['id'],'edge':e,'proposed_current_head':heads.get(e['object'])})
 for x in o['changes']:heads[x['id']]=(x['expectedVersion'] or 0)+1
assert len(seq)==98 and len(targets)==714 and viol==prior['static_head_order_violations'];rid=n['evidence'][0]['basis_revision_id'];full=dict(c.execute('select r.*,ob.kind from revision r join object ob on ob.id=r.object_id where r.id=?',(rid,)).fetchone());full['data']=dict(c.execute('select * from record where revision_id=?',(rid,)).fetchone());full['origins']=[dict(t) for t in c.execute('select * from origin where revision_id=?',(rid,))];full['evidence']=[dict(t) for t in c.execute('select * from dependency where revision_id=?',(rid,))];full['assets']=[dict(t) for t in c.execute('select * from record_asset where revision_id=?',(rid,))];full['media']=[dict(t) for t in c.execute('select * from record_media where revision_id=?',(rid,))];incoming=[dict(t) for t in c.execute('select * from dependency where basis_revision_id in(select id from revision where object_id=?)',(ch['id'],))];assert not incoming
inp=save('corrected-source-content-and-full-record-basis-input-v1.json',{'corrected_source_pin':receipt['source_pins'][0],'corrected_lower_five_raw_pin':{'path':str(raw[0]),'sha256':rawsha},'unimplemented_first_eight_spec_pin':spec['supersedes_candidate_only'],'full_current_original_record_basis':full,'new_TR_expectedVersion':None,'new_native_version':1,'full13_content_exact_source_equal':True,'method_and_source_scope_exact':spec['implementation'],'no_metadata_sourceperson_or_adoption_inference':True,'incoming_new_target_edges':incoming,'future_R2_must_follow_newTR_oldR1_basis':True,'prior_seven_API_questions_unchanged':viol})
m=save('current98-candidate-membership-inventory-v1.json',{'prior_proposal_pin':{'path':str(priorp),'sha256':sha(priorp)},'candidate_members':seq,'unique_targets':714,'member_count':98,'new_targets':1,'duplicate_targets':0,'source_first8_spec_unimplemented_not_candidate_member':True,'global_source_approval':False})
q=save('concrete-current98-partial-sequence-and-constraint-proposal-v1.json',{'sequence':seq,'members':98,'unique_targets':714,'constraints':constraints,'static_head_order_violations':viol,'membership_pin':m,'fresh_primary_source_hash_binding_required':True,'no_nativePASS_stage_or_request_resolution':True})
f=save('bounded-corrected13-TR-handoff-and-production-v1.json',{'source_pins':receipt['source_pins'],'raw_pin':{'path':str(raw[0]),'sha256':rawsha},'input_pin':inp,'membership_pin':m,'proposal_pin':q,'new_transcriptions':1,'new_existing_revisions':0,'full13_scope':'eight family plus five lower context rows, paired annual F/N cells','initial_eight_row_coverage_gap_and_nonblind_repair_preserved':True,'failed_mechanical_attempts':[],'elapsed_since_candidate_seconds':time.time()-pathlib.Path(pin['path']).stat().st_mtime,'initial_reads_excluded':True,'model_usage_root_collect_after_final':True,'prior_seven_API_questions_and_RESEARCH30_dispositions_pending':True,'no_stage_probe_apply_actual328_modification':True});print(json.dumps({'input':inp,'membership':m,'proposal':q,'handoff':f,'constraints':len(constraints)}))
