import json,pathlib,sqlite3,hashlib,time
start=time.time();b=pathlib.Path('evaluations/T-0780');w=b/'implementation/C0060-first-settled-queue-v1';bio=b/'implementation/C0060-three-biography-queue-v1';c=sqlite3.connect('file:'+str(b/'preparation/baseline-j281.sqlite')+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;load=lambda p:json.load(open(p))
def sha(p):return hashlib.sha256(pathlib.Path(p).read_bytes()).hexdigest()
def save(n,d):p=w/n;assert not p.exists();p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');return {'path':str(p),'sha256':sha(p)}
p=w/'concrete-current83-partial-sequence-and-constraint-proposal-v1.json';prior=load(p);r=load(bio/'settled-module-receipt-v1.json');new=[z for z in r['candidate_modules'] if 'operation-' in z['path']];seq=prior['sequence'][:-1]+new+prior['sequence'][-1:];assert 'two-records-last' in seq[-1]['path'];targets={};heads={z['object_id']:z['version'] for z in c.execute('select object_id,max(version) version from revision group by object_id')};updates={ch['id']:{'index':i+1,'operation_id':load(pin['path'])['id'],'expectedVersion':ch['expectedVersion'],'newVersion':(ch['expectedVersion'] or 0)+1} for i,pin in enumerate(seq) for ch in load(pin['path'])['changes']};schema=[];viol=[];constraints=[];support=0
for i,pin in enumerate(seq):
 op=load(pin['path']);assert sha(pin['path'])==pin['sha256'];pin['index']=i+1;pin['operation_id']=op['id'];pin['targets']=[]
 for ch in op['changes']:
  assert ch['id'] not in targets;targets[ch['id']]=ch;assert heads.get(ch['id'])==ch['expectedVersion'];pin['targets'].append({'id':ch['id'],'expectedVersion':ch['expectedVersion'],'payload_sha256':hashlib.sha256(json.dumps(ch,ensure_ascii=False,sort_keys=True,separators=(',',':')).encode()).hexdigest()})
  for e in ch['evidence']:
   support+=1
   if set(e)!={'object','version','role','note'} or type(e['version']) is not int or e['version']<1:schema.append({'target':ch['id'],'edge':e})
   if e['object'] in updates:constraints.append({'dependent':ch['id'],'dependent_operation':op['id'],'index':i+1,'edge':e,'basis_update':updates[e['object']],'primary_source_order_grade_required':True})
   if heads.get(e['object'])!=e['version'] and not any(z['id']==e['object'] and (z['expectedVersion'] or 0)+1==e['version'] for z in op['changes']):viol.append({'dependent':ch['id'],'basis':e,'current_proposed_head':heads.get(e['object'])})
 for ch in op['changes']:heads[ch['id']]=(ch['expectedVersion'] or 0)+1
assert len(targets)==654 and len(seq)==84 and not schema and not viol
protected=[]
for pin in r['source_pins']:
 for o in load(pin['path'])['objects']:
  old=o['current'];ch=targets[old['object_id']];prefix=[{'object':e['basis_revision_id'].rsplit('@',1)[0],'version':int(e['basis_revision_id'].rsplit('@',1)[1]),'role':e['role'],'note':e['note']} for e in old['evidence']];assert ch['evidence'][:len(prefix)]==prefix;assert old['disposition']==ch['disposition'] and old['evidence_status']==ch['evidenceStatus'];protected.append({'object':old['id'],'source_pin':pin,'all_older_evidence_array_prefix_unchanged':True,'status_unchanged':True,'stronger_T0675_T0677_exact_support_versions_retained':True})
p1=save('threeBIO-individual-stronger-evidence-prefix-and-order-check-v1.json',{'checks':protected,'actual_all_history_incoming_edges':0,'prior651_target_overlaps':0,'no_serial_version_bump':True,'source_context_caveat_retained_except_exact_settled_fields':True});m=save('current84-candidate-membership-inventory-v1.json',{'prior_membership':{'path':str(w/'current83-candidate-membership-inventory-v1.json'),'sha256':sha(w/'current83-candidate-membership-inventory-v1.json')},'candidate_members':seq,'unique_targets':654,'member_count':84,'schema_errors':schema,'duplicate_targets':0,'new_C0060_targets':30,'source_flags_retained_as_data':True,'incomplete_scopes':['C0060remaining','C0069','whole10finalreview','actual328individualrequests'],'global_sequence_or_source_APPROVAL':False});q=save('concrete-current84-partial-sequence-and-constraint-proposal-v1.json',{'sequence':seq,'members':84,'unique_targets':654,'evidence_entries_checked':support,'constraints':constraints,'static_head_order_violations':viol,'C0060_NEW_TR_first_oldREAD_TR_O_before_M_R2_last':True,'newTR_expectednull_version1':True,'membership_pin':m,'primary_fresh_global_hash_binding_required':True,'no_native_PASS_or_stage_authority':True,'applies':0});other=load(w/'bounded-C0060-first-plus-adoption-handoff-and-production-v1.json');first=min(z.stat().st_mtime for z in w.glob('*operation-v1.json'));p2=save('bounded-C0060-five-module-final-handoff-and-production-v1.json',{'scope':'Only2TR,6wrappers,12structured/core,13adoptions,3BIO; no larger BIO29 merge','source_pins':other['source_pins']+r['source_pins'],'previous_handoff':{'path':str(w/'bounded-C0060-first-plus-adoption-handoff-and-production-v1.json'),'sha256':sha(w/'bounded-C0060-first-plus-adoption-handoff-and-production-v1.json')},'BIO_protected_pin':p1,'membership_pin':m,'sequence_pin':q,'revisions':15,'newTR':2,'newADOPT':13,'structured_retains':6,'adoption_core_retains':13,'individual_fullfield_rows':255,'incoming_current_history_edges':15,'full_incoming_native_objects':14,'BIO_extra_incoming_edges':0,'prior624_and_incremental_target_overlap':0,'all_original_grouped_candidates_and_splits_preserved':True,'failed_attempts':0,'elapsed_from_first_candidate_persist_seconds':time.time()-first,'elapsed_measured_finalize_seconds':time.time()-start,'elapsed_excludes_initial_prebuild_input_reads':True,'model_usage_unknown_root_collect_after_final':True,'pending_individual_incoming_and_fresh_global_source_binding':True,'stage_probe_apply_resolution_and_actual328_modification_count':0});print({'membership':m,'proposal':q,'handoff':p2,'constraints':len(constraints),'supports':support,'elapsed':time.time()-first})
