"""Append-only review candidates from settled Astra ledger. Does not write Wotan."""
import json,hashlib,datetime
from pathlib import Path
B=Path('evaluations/T-0780');W=B/'implementation/resumed-future-owner-Wotan-append-only-plan-v1'
def load(p):return json.loads(Path(p).read_text())
def sha(p):return hashlib.sha256(Path(p).read_bytes()).hexdigest()
def pin(p):return {'path':str(p),'sha256':sha(p)}
L=B/'source-review/resumed-all10-finite-future-owner-ledger-v2.json';assert sha(L)=='a074b0f1c71b85a9561a2d6edf219930387ac1c81a81d0279d2b3b0bf5321b67';ledger=load(L);owners={x['owner']:x for x in ledger['existing_owners']};assert len(owners)==45
texts={
'T-0268':'Återbruka T-0780:s aktuella C-0425-datum och rollgränser. Marginalformerna 19/128 och 3/16[?] är fortfarande råa söknycklar, inte belägg för ägande eller fastighetsnummer. De befintliga två jurisdiktionskontrollerna, registren för egna dödsår och följande år samt mantalsprovet år1900 i Vol48 står kvar; ingen utvidgad markkedja eller beställning tillkommer.',
'T-0402':'T-0402 och T-0566 överlappar i föräldrahushållets mellanliggande böcker. Genomför en gemensam framtida passage och återbruka varje persons egna rad i båda uppgifterna. T-0780:s fulla C-0069/C-0425-läsningar och daterade ankare tillgodoräknas. Kända ändfolier fastställer inte mellanliggande åtkomst, innehåll eller oavbrutet fysiskt boende.',
'T-0416':'Lotta Sofias egen födelse 30 mars1843 är redan accepterad. De tre senare oktoberformerna är källvarianter, inte fyra olösta alternativ för hennes verkliga födelse. Maria Johanna-kandidaten förblir separat och obevisad. Rödå-/pigaradspassagen behåller sitt befintliga omfång; T-0559:s egna kolumner och T-0560:s kandidatsamband ska dela tillräckligt tidigare material.',
'T-0452':'Underlaget avser tre registrerade Nordamerikaepisoder1892/1904/1907 för sex personer; det bevisar inte fyra faktiska resor, faktisk ankomst eller gemensam destination. Emanuels egna attestblank är lokal. T-0616:s Degerfors1904-register överlappar denna uppgift och ska läsas en gång med återbruk i båda. T-0616:s amerikanska uteslutning består; ingen ny bred amerikansk livsutredning tillkommer.',
'T-0453':'De fyra egna födelseposterna1858/1871/1872/1874 är skilda från T-0780:s hushållsrader. De tre senare födslarna behöver en volym efter C/3:s slut1869; ett äldre löfte om en enda katalog-/volympassage får inte garantera åtkomst eller vidga omfånget. Root stämmer av den befintliga volymgränsen vid start. Födelseposterna1871/1872/1874 överlappar T-0616 och ska återbrukas efter en gemensam läsning.',
'T-0455':'Bevara de boklokala yrkesuppgifterna var för sig: C-0563 hem.ä[?], C-0561/C-0552/C-0554 Bonde, C-0685 egen yrkesblank och C-0584 Såg.arb. Blankfältet upphäver inte daterade titlar och bevisar ingen yrkesövergång. 3/128 förblir en onormaliserad rånyckel. Det befintliga mandatet gäller fortfarande en fastighetsserie och en volym för P-0422.',
'T-0464':'Återbruka T-0259:s redan identifierade kopia och faktisk tillräcklig läsning av A I/3 s262 och A I/7b s400. Ingen duplicerad hämtning eller omläsning följer av detta tillägg. Två öppnade bilder godkänner inte automatiskt sex kontrakt; varje berörd granskning prövas individuellt.',
'T-0493':'De sju namngivna födelsefönstren1814–1825, Holmströmhushållen och den befintliga vigselvägen1810–1814 står kvar. Sju upprepade modersåldrar är inte sju oberoende ursprungsröster. Ett vittnes efternamn fastställer inte identitet. T-0492:s far582/födelse1785/död1870 och T-0495:s Anna Johanna ingår inte här.',
'T-0543':'Uppgiftens senaste mandat gäller sju personer: P-0065 och P-0068–P-0073. Faderns död21oktober1909 och A II a/3 s1088 r1 är redan lästa och ska återbrukas tillsammans med de exakta fader-/registersöknycklarna i T-0780:s fem C-0060-PATH-rättelser. Syskonens egna fortsättnings-, död- och vigselpassager är fortfarande oprövade. Ingen militärkolumn, flyttning, gemensam sjupersonsrad eller billig enda passage är garanterad.',
'T-0546':'De tre brödernas militära råuppgifter ska hållas personbundna, inklusive 305173/1895, Frik och blank. Härledda1897/1901 är inte lästa inskrivningsdatum. Årsklass, volymordning, åtkomst, innehåll och personkorrelation måste prövas; den militära vägen garanterar ingen namnsäker identifiering eller frikallelsegrund. Återbruka tillräckliga glyfkontroller och bevara P-0071:s beroende av egen fortsättning i T-0543.',
'T-0550':'Återbruka den senaste loggens C/4/C/5-nycklar och den fulla P-0073-kontrollen1885. Ties1873 egna födelsepost är redan läst. Tvillingarnas kända Död-celler1874/1875 hör inte till en dödbok efter1895. De sju återstående egna födelsefrågorna behåller sitt befintliga omfång; T-0558:s orsaks-/begravnings-/åldersfrågor dupliceras inte.',
'T-0551':'Återbruka första sidan, den tidigare helaktsavskriften och T-0780:s aktuella C-0060-åldersrättelser. Åldrar sent i augusti skiljer sig från ålder vid död i maj; äldre påståenden om två minderåriga barn eller Carl17/Hanna15 får inte styra före de faktiska datumen. Mandatet gäller de sex namngivna barnens avgränsade andels-/förmyndarfrågor. T-0258 äger de tjugo saknade fortsättningskopiorna och full boeträkning; P-0073:s befintliga nativekontext innebär inget nytt barnmandat här.',
'T-0558':'De redan kända Död-cellerna31december1874 och7maj1875 avslutar inte denna uppgift. Återstående egna dödboksposter, dödsorsak, begravning, ålder och avgränsad omgivning står kvar enligt mandatet. Ett fyramånadersintervall utesluter inte alla gemensamma orsaker och bevisar ingen epidemi. Födelseposter och hushållsråfält återbrukas från T-0550 respektive T-0259.',
'T-0560':'C/4:s period1851–1869 kan inte täcka Maria Johannas födelseår1849. Bevara den tidigare hänvisningen som ett dokumenterat volymfel och välj genom katalogen den volym som faktiskt täcker1849 inom den befintliga egna födelsefrågan2augusti1849. Ingen bredare sökning tillkommer. En födelsepost med samma namn/datum garanterar inte systeridentitet; T-0559:s övriga pigkolumner återbrukas.',
'T-0561':'T-0110:s fulla post139 och tvåscansläsning omfattar redan Forsbergs bläckord och platsgräns; detta återbruk är bekräftat i T-0780:s C-0062-prövning. Uppgiften ska inte repetera ett alternativ som äldre text kallade oläst. Nästa ej utförda steg är roots administrativa avstämning av ursprungliga acceptanskriterier mot faktisk tidigare granskning och accepterade native-rättelser. Ingen automatisk DONE, tredje originalpassage eller identitetsuppgradering följer här; bläckordsreservation, oexpanderad plats och avsaknad av barnsläktskap bevaras.',
'T-0563':'T-0780:s C-0425-rad ger de egna1905-datum- och1899-boknycklarna. Målet Bygdeå A II a/2b folio820 för Christina Louisa och Anna Albertina Öberg[?] är fortfarande oläst. Gemensamt folio fastställer inte hushåll eller släktskap, och bokdag är inte fysisk flyttdag. Ingen utvidgning till1098, egen C/5 eller vigsel1899 tillkommer.',
'T-0565':'Bevara nästa volym och folio1098 som egen oprövad nyckel för Nilsfamiljen, samt Ultervattnets Jakob på egen rad. nb är ingen fysisk flytt; årsmärken09/10 fastställer inte oavbruten närvaro och blank16–18 fastställer inte frånvaro av flytt/död i livet. Iris/Enis-reservationen följer den senaste källbedömningen. Fel volym och person ej funnen hålls skilda. Ingen utvidgning till1096/1097,820 eller egen C/5.',
'T-0566':'Återbruka en gemensam passage med T-0402 för Maria Mathildas egen rad i föräldrahushållets mellanliggande böcker1873–1895. C-0069:s lokala blankfält och C-0425:s frånvaro bevisar varken död, kontinuerlig fysisk närvaro eller att tre förklaringar uttömmer alternativen. Matilda/Mathilda-formerna består utan nytt patronymikon. Den egna födelseposten i T-0564 är separat; ingen automatisk utvidgning till1880-talets dödböcker.',
'T-0569':'Den senaste uppgiften gäller tre vittnen: P-0104/P-0105 samt P-0106. T-0780:s bredare C-0069-post med tretton rader och folkräkningsunderlaget ska återbrukas. En son på ett folio bevisar inte enda son eller frånvaro av äldre barn; piga utesluter inte barn-/släktrelation. Initialerna A och C expanderas inte. P-0107:s Ytteråträsk i T-0578 ligger utanför; samma tidiga föräldrafolio ska delas med T-0267 vid exakt överlapp.',
'T-0616':'T-0616 äger inte en ny separat jämförelse av fem strukna rader; en tidigare association får inte utöka mandatet. T-0673:s hela Skön1874-post är redan läst: föräldrakolumnen saknas, den är inte blank. Tvillingarnas dop14april1864 tillgodoräknas. Andra äktenskapets egna födslar1871/1872/1874/1876/1878/1887 samt befintliga Stöde-/Sättnapassager består. Överlapp med T-0453:s födelseposter och T-0452:s1904-utflyttningsregister ska läsas en gång och återbrukas. Amerikanska källor ligger fortfarande utanför; P-0412 är avslutad utan ny åtgärd. Ingen garanti om frikallelsegrund eller enda svenska källväg införs.'
}
for item in ledger['exact_part1_admin_amendments']:
 if item['owner'] in ['T-0492','T-0621']:
  texts[item['owner']]='\n\n'.join(item[k] for k in ['new','second_new','source_fields','next_unperformed','source_limit','no_extra_scope'] if k in item)
assert len(texts)==22 and set(texts)<=set(owners)
assert not W.exists();W.mkdir();(W/'append-texts').mkdir();(W/'full-proposed-tasklogs').mkdir();(W/'current-before-tasklogs').mkdir()
BP=Path('wotan/backlog.json');bb=BP.read_bytes();backlog=load(BP);tasks={x['id']:x for x in backlog['tasks']};assert backlog['next_id']==782;assert tasks['T-0781']['status']=='BLOCKED'
(W/'current-before-backlog.json').write_bytes(bb)
rows=[]
for owner,text in sorted(texts.items()):
 x=owners[owner];log=Path('wotan/dev-log')/(owner+'.md');before=log.read_bytes();assert sha(log)==x['full_log_pin']['sha256'],'Unexpected current tasklog change; return root before append candidate'
 ap='\n\n## Återupptagning — T-0780: källbunden precisering\n\nFörberett2026-10-04. Tillämpligt efter roots verifierade faktiska acceptans av T-0780:s tio källor och separat godkännande av denna administrativa avstämning.\n\n'+text+'\n\nDe återstående passagerna i uppgiften startas inte genom denna administrativa avstämning. Befintlig status och historik bevaras; aktuella Genealogy2-objekt och tillräckliga accepterade läsningar stäms av vid nästa steg inom befintlig stoppgräns.\n'
 appendp=W/'append-texts'/(owner+'-append-v1.md');appendp.write_text(ap);newp=W/'full-proposed-tasklogs'/(owner+'.md');newp.write_bytes(before+ap.encode());oldp=W/'current-before-tasklogs'/(owner+'.md');oldp.write_bytes(before);assert newp.read_bytes()[:len(before)]==before
 rows.append({'owner':owner,'source_ledger_pin':pin(L),'source_individual_disposition_pointer':'/existing_owners/'+str(x['index']),'literal_settled_source_disposition':x['disposition'],'literal_source_bound_judgment':x['source_bound_owner_judgment'],'literal_duplicate_or_exclusion_judgment':x['duplicate_or_exclusion_judgment'],'exact_part1_pointer':next(('/exact_part1_admin_amendments/'+str(i) for i,a in enumerate(ledger['exact_part1_admin_amendments']) if a['owner']==owner),None),'actual_tasklog_pin':pin(log),'preserved_current_before_pin':pin(oldp),'current_backlog_status':tasks[owner]['status'],'current_backlog_after':tasks[owner].get('after',[]),'append_text_pin':pin(appendp),'complete_proposed_tasklog_pin':pin(newp),'exact_existing_byte_prefix_preserved':True,'backlog_mutation_proposed':False,'status_mutation_proposed':False,'source_assignment_or_research_execution_proposed':False,'root_individual_review_and_post_actual10_approval_required':True})
assert BP.read_bytes()==bb
p=W/'finite-individual-Wotan-append-only-administrative-review-plan-v1.json';p.write_text(json.dumps({'task':'T-0780','at_utc':datetime.datetime.now(datetime.timezone.utc).isoformat(),'status':'PREPARED_UNAPPLIED_ROOT_REVIEW_REQUIRED_AFTER_ACTUAL10','source_ledger_pin':pin(L),'current_backlog_pin':pin(BP),'preserved_current_backlog_pin':pin(W/'current-before-backlog.json'),'existing_owner_route_count':45,'selected_individual_append_candidates':rows,'selected_count':22,'unamended_retain_owner_ids':sorted(set(owners)-set(texts)),'unamended_retain_count':23,'new_Carl_owner_proposal_deferred_no_ID_reserved':ledger['new_bounded_owner_proposals'],'next_two_existing_owner':tasks['T-0781'],'next_id_observed_not_reserved':782,'all_original_tasklog_prefixes_preserved':True,'no_Wotan_canonical_dashboard_or_archive_writes':True,'actual10_acceptance_receipt_binding':'ROOT_MUST_BIND_ACTUAL_ACCEPTED_CANONICAL_RESULT_BEFORE_APPLY','approval':'UNREQUESTED_UNGRANTED_BY_SOL','scope_limits':ledger['limits'],'source_reading_credit':'Astra read45wholelogs+T0110. Sol uses exact settled individual dispositions; no root/all45 whole-reading credit inferred.'},ensure_ascii=False,indent=2)+'\n')
print(json.dumps({'result_pin':pin(p),'append_candidates':len(rows),'retains_not_copied':23,'next_id_unreserved':782,'actual_Wotan_writes':0},indent=2))
