import json,pathlib,sqlite3,hashlib,subprocess,time,datetime
ROOT=pathlib.Path.cwd();b=ROOT/'evaluations/T-0780';out=b/'diagnostic-C0685-C0563-28ops-v1';assert not out.exists(),'Preserve single probe; never overwrite prior attempt';out.mkdir();start=time.time();manifest=b/'implementation/C0685-C0563-split-proposal-v2/concrete-sequence-and-preservation-receipt-v2.json';assert hashlib.sha256(manifest.read_bytes()).hexdigest()=='c8172343aed932c9e7f61743d48537ce017d47877c61bac8f9522789d4b094f6';m=json.load(open(manifest));assert len(m['sequence'])==28 and m['unique_native_changes']==151
bindings=[]
for name,sha in [('C0685-C0563-exact-sequence-v2-primary-binding-v1.json','a334e8bf31e85eebfbaa21b93eced9492e68c817d3283eede0e6f31fda574f6f'),('C0685-C0563-exact-sequence-v2-primary-binding-v2.json','ecf72b247fd22cb961b704417d13dd4c8ca8f69491dd083c8748933040de4355')]:
 p=b/'source-review'/name;assert hashlib.sha256(p.read_bytes()).hexdigest()==sha;bindings.append({'path':str(p.relative_to(ROOT)),'sha256':sha})
def save(p,x):p.write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def ro(p):c=sqlite3.connect('file:'+str(p)+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;return c
def state(c):
 result={}
 for z in c.execute("select name from sqlite_master where type='table' order by name"):
  n=z[0];rows=[]
  for r in c.execute('select * from "'+n+'"'):
   rows.append(json.dumps({k:({'bytes_hex':v.hex()} if isinstance(v,bytes) else v) for k,v in dict(r).items()},ensure_ascii=False,sort_keys=True,separators=(',',':')))
  rows.sort();result[n]={'rows':len(rows),'sha256':hashlib.sha256(('['+','.join(rows)+']').encode()).hexdigest()}
 return result
def protection(c):return [dict(r) for r in c.execute("select r.*,a.criteria,a.outcome,a.body from revision r left join assessment a on a.revision_id=r.id where not exists(select 1 from revision n where n.object_id=r.object_id and n.version>r.version) and (r.evidence_status='OWNER_CONFIRMED' or a.criteria in ('identity_review/1','tree_effect/1','life_picture_review/1')) order by r.object_id")]
live=ro(ROOT/'genealogy2/data/research.sqlite');baseline=state(live);assert len(baseline)==50;assert live.execute('select max(sequence) from operation_payload').fetchone()[0]==281;assert live.execute('select count(*) from pending_review').fetchone()[0]==0;frozen=ro(b/'preparation/baseline-j281.sqlite');assert state(frozen)==baseline;frozen.close();protected=protection(live);save(out/'baseline-all50-table-equality-v1.json',{'live':baseline,'frozen_clone_equal':True});db=out/'probe.sqlite';dest=sqlite3.connect(db);live.backup(dest);dest.close();cc=ro(db);assert state(cc)==baseline;cc.close();save(out/'protected-before-v1.json',protected)
gate={'status':'diagnostic_partial_clone_only','canonical_authorized':False,'baseline_journal':281,'baseline_pending':0,'source_manifest':str(manifest.relative_to(ROOT)),'source_manifest_sha256':hashlib.sha256(manifest.read_bytes()).hexdigest(),'primary_bindings':bindings,'root_authority':'Explicit root finite probe amendment 2026-10-03 in active T-0780; no full10 credit or final stage acceptance','operations':m['sequence'],'pending_allowed':True,'no_resolves':True,'final_fresh_whole10_stage_required':True};save(out/'probe-gate-v1.json',gate);journal=out/'journal';journal.mkdir();(out/'steps').mkdir();actual={};steps=[];knownrequests=set();failure=[]
def native(c,rid):
 if rid in actual:return
 r=c.execute('select r.*,o.kind from revision r join object o on o.id=r.object_id where r.id=?',(rid,)).fetchone();assert r;r=dict(r);r['data']=dict(c.execute('select * from '+r['kind']+' where revision_id=?',(rid,)).fetchone());r['origins']=[dict(z) for z in c.execute('select * from origin where revision_id=?',(rid,))];r['evidence']=[dict(z) for z in c.execute('select * from dependency where revision_id=? order by basis_revision_id,role',(rid,))]
 if r['kind']=='record':r['assets']=[dict(z) for z in c.execute('select * from record_asset where revision_id=?',(rid,))];r['media']=[dict(z) for z in c.execute('select * from record_media where revision_id=?',(rid,))]
 actual[rid]=r
for i,pin in enumerate(m['sequence'],1):
 p=ROOT/pin['path'];assert hashlib.sha256(p.read_bytes()).hexdigest()==pin['sha256'];op=json.load(open(p));t=time.time();proc=subprocess.run(['node','genealogy2/cli.mjs','apply',str(p),'--db',str(db),'--journal',str(journal)],cwd=ROOT,capture_output=True,text=True);(out/'steps'/f'{i:02}-stdout.json').write_text(proc.stdout);(out/'steps'/f'{i:02}-stderr.txt').write_text(proc.stderr);step={'index':i,'operation_id':op['id'],'operation_sha256':pin['sha256'],'exit_code':proc.returncode,'elapsed_seconds':time.time()-t}
 cc=ro(db);requests=[dict(r) for r in cc.execute('select * from review_request order by id')];new=[r for r in requests if r['id'] not in knownrequests];knownrequests|={r['id'] for r in requests};step['new_review_requests']=new;step['pending_total']=cc.execute('select count(*) from pending_review').fetchone()[0];step['actual_journal_head']=cc.execute('select max(sequence) from operation_payload').fetchone()[0]
 for r in new:
  native(cc,r['referencer_revision_id']);native(cc,r['changed_basis_revision_id'])
 if proc.returncode==0:
  stored=json.loads(cc.execute('select request_json from operation_payload where operation_id=?',(op['id'],)).fetchone()[0]);assert stored==op,'Exact payload/array order mismatch'
  for ch in op['changes']:
   rid=ch['id']+'@'+str((ch['expectedVersion'] or 0)+1);native(cc,rid);obj=actual[rid];assert all(obj['data'][k]==(json.dumps(v,ensure_ascii=False,separators=(',',':'),sort_keys=True) if k.endswith('_json') and v is not None else v) for k,v in ch['data'].items()),rid;assert obj['disposition']==ch['disposition'] and obj['evidence_status']==ch['evidenceStatus'] and obj['caveat']==ch['caveat'] and obj['rationale']==ch['rationale'];expected=[{'revision_id':rid,'basis_revision_id':e['object']+'@'+str(e['version']),'role':e['role'],'note':e['note']} for e in ch['evidence']];assert sorted(expected,key=lambda z:json.dumps(z,sort_keys=True))==sorted(obj['evidence'],key=lambda z:json.dumps(z,sort_keys=True));assert obj['origins']==[{'revision_id':rid,'unit_id':o['unit'],'coverage':o['coverage'],'note':o['note']} for o in ch['origins']]
 assert protection(cc)==protected;cc.close();steps.append(step);save(out/'steps'/f'{i:02}-actual-receipt.json',step);save(out/'progress-v1.json',{'completed_steps':len(steps),'last_step':step,'elapsed_seconds':time.time()-start});print(json.dumps({'step':i,'exit':proc.returncode,'new_reviews':len(new),'pending':step['pending_total']}),flush=True)
 if proc.returncode:failure.append(step);break
save(out/'actual-review-request-full-native-dictionary-v1.json',{'objects':actual,'read_only_capture_no_interpretation':True});save(out/'all-step-actual-review-requests-v1.json',{'steps':steps,'no_resolution_operations':True});checks=[]
if not failure:
 for cmd in ['verify','verify-assets','verify-source','inventory']:
  proc=subprocess.run(['node','genealogy2/cli.mjs',cmd,'--db',str(db),'--journal',str(journal)],cwd=ROOT,capture_output=True,text=True);(out/(cmd+'-stdout.json')).write_text(proc.stdout);(out/(cmd+'-stderr.txt')).write_text(proc.stderr);checks.append({'command':cmd,'exit_code':proc.returncode,'output_path':str((out/(cmd+'-stdout.json')).relative_to(ROOT))})
cc=ro(db);save(out/'protected-after-v1.json',protection(cc));pending=[dict(r) for r in cc.execute('select * from pending_review')];save(out/'actual-pending-review-requests-v1.json',pending);assert protection(cc)==protected;cc.close();assert state(live)==baseline;live.close();result={'task':'T-0780','diagnostic_only':True,'baseline_journal':281,'steps_completed':len(steps),'failed_steps':failure,'checks':checks,'pending_count':len(pending),'protected_unchanged':True,'live_all50_tables_unchanged':True,'stage_or_canonical_acceptance':False,'canonical_applies':0,'generic_resolves':0,'elapsed_seconds':time.time()-start,'source_gate_sha256':hashlib.sha256((out/'probe-gate-v1.json').read_bytes()).hexdigest(),'primary_individual_request_dispositions_required':True,'final_fresh_whole10_reviewed_stage_required':True};save(out/'probe-final-receipt-v1.json',result);print(json.dumps(result),flush=True)
