import json,pathlib,hashlib,sqlite3,copy
b=pathlib.Path('evaluations/T-0780');w=b/'implementation/C0425-expanded-research-structured-queue-v1';p=w/'concrete-current76-partial-sequence-and-constraint-return-v1.json';old=json.load(open(p));seq=copy.deepcopy(old['sequence']);move=next(z for z in seq if z['operation_id']=='T-0780/C0425-expanded69-structured-v1');seq.remove(move);position=next(i for i,z in enumerate(seq) if z['operation_id']=='T-0780/C0425-five-full-transcription-v1');seq.insert(position+1,move);c=sqlite3.connect('file:'+str(b/'preparation/baseline-j281.sqlite')+'?mode=ro',uri=True);c.row_factory=sqlite3.Row;vers={z['object_id']:z['version'] for z in c.execute('select object_id,max(version) version from revision group by object_id')};viol=[]
for i,s in enumerate(seq):
 s['index']=i+1;op=json.load(open(s['path']));assert hashlib.sha256(pathlib.Path(s['path']).read_bytes()).hexdigest()==s['sha256']
 for ch in op['changes']:
  assert vers.get(ch['id'])==ch['expectedVersion']
  for e in ch['evidence']:
   if vers.get(e['object'])!=e['version'] and not any(z['id']==e['object'] and (z['expectedVersion'] or 0)+1==e['version'] for z in op['changes']):viol.append({'dependent':ch['id'],'basis':e,'proposed_head':vers.get(e['object'])})
 for ch in op['changes']:vers[ch['id']]=(ch['expectedVersion'] or 0)+1
oldidx={s['operation_id']:s['index'] for s in old['sequence']};newidx={s['operation_id']:s['index'] for s in seq};d={'scope':'Mechanical proposal only, explicit source hash binding required','prior_proposal_preserved':{'path':str(p),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()},'initial_two_head_conflicts':old['static_head_order_violations'],'sequence':seq,'unique_targets':old['unique_targets'],'members':old['members'],'repositioned_whole_operation':{'operation_id':move['operation_id'],'old_index':oldidx[move['operation_id']],'new_index':newidx[move['operation_id']],'reason':'E-birth-P0096 keeps exact two O@1 bases. Place five source-approved structured revisions after their fullTR prerequisites and before selected27O@2; no payload/basis/version changed.'},'all_payloads_and_member_hashes_unchanged':True,'prior74_members_relative_order_unchanged':True,'static_head_order_violations':viol,'all_other_constraints_need_primary_global_bind':True,'source_approval_pending':True,'applies':0};assert not viol;p2=w/'concrete-current76-partial-sequence-reposition-proposal-v2.json';assert not p2.exists();p2.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n');print(hashlib.sha256(p2.read_bytes()).hexdigest(),newidx[move['operation_id']])
