// Initial preparation scaffold. Final reviewed JSON packages include later root-requested literal/temporal repairs and exact three dependency retains; do not regenerate them from this draft.
import fs from 'node:fs';import path from 'node:path';import crypto from 'node:crypto';
import {openDB} from '../../genealogy2/lib/store.mjs';import {readCurrent} from '../../genealogy2/lib/domain.mjs';import {stageMedia} from '../../genealogy2/lib/recovery.mjs';
const root=process.cwd(), dir='evaluations/T-0217',db=openDB('genealogy2/data/research.sqlite'),originals={},consequences=[];
const hash=x=>crypto.createHash('sha256').update(x).digest('hex');
const B=(object,version=1,role='supports',note='T-0217 exact bounded catalogue metadata; no personal original reading.')=>({object,version,role,note});
const news=(id,kind,data,extra={})=>({id,kind,expectedVersion:null,data,disposition:'recorded',rationale:'T-0217 AC1–4: bounded source routing and preserved reading limits.',caveat:'Catalogue metadata/discovery only; own person record unread. No identity, parent, OWNER or tree-gate amendment.',...extra});
function revise(id,fn,basis=[]){const x=readCurrent(db,id);if(!x)throw Error('Missing '+id);originals[id]=x;const columns=db.prepare(`PRAGMA table_info(${x.kind})`).all().map(c=>c.name).filter(c=>c!=='revision_id'),data=Object.fromEntries(columns.map(k=>[k,x[k]]));for(const k of Object.keys(data))if(k.endsWith('_json')&&typeof data[k]==='string')data[k]=JSON.parse(data[k]);fn(data,x);const change={id,kind:x.kind,expectedVersion:x.version,data,disposition:x.disposition,evidenceStatus:x.evidence_status,rationale:'T-0217 bounded catalogue routing; exact current source-path amendment, all other source/identity limits retained.',caveat:x.caveat,origins:x.origins.map(o=>({unit:o.unit_id,coverage:o.coverage,note:o.note})),evidence:[...x.evidence.map(e=>{const at=e.basis_revision_id.lastIndexOf('@');return B(e.basis_revision_id.slice(0,at),Number(e.basis_revision_id.slice(at+1)),e.role,e.note)}),...basis]};consequences.push({object:id,expectedVersion:x.version,fields:columns.filter(k=>JSON.stringify(data[k])!==JSON.stringify(k.endsWith('_json')&&typeof x[k]==='string'?JSON.parse(x[k]):x[k])),before:x,decision:'amend only bounded source routing; other fields retained'});return change;}
function replace(data,old,next){if(!data.body.includes(old))throw Error('Zero match '+old);if(data.body.split(old).length!==2)throw Error('Multiple '+old);data.body=data.body.replace(old,next);}
const specs=[['emma','emma1963-catalogue-extract-v1.txt','Medelpads västra domsagas häradsrätt FIIa65/CIIc1 catalogue2026-10-08','SE/HLA/1040237/F/F II/F II a/65; SE/HLA/1040237/C/C II/C II c/1'],['axel','axel1983-catalogue-extract-v1.txt','Sundsvalls tingsrätt FII/DIVd1 catalogue2026-10-08','SE/HLA/1040239/F/F II; SE/HLA/1040239/D/D IV/D IV d/1'],['mil','military-catalogue-extract-v1.txt','Ro65 linked military cataloguelists2026-10-08','SE/KrA/0473/B/05/005:Ö; SE/KrA/0473/B/21/002:Ö; SE/KrA/0473/B/21/002:H']];
const packs={};for(const [key,file,title,ref] of specs){const txt=fs.readFileSync(`${dir}/sources/${file}`,'utf8'),m=await stageMedia(root,path.resolve(dir,'sources',file),'T-0217 authenticated NAD visible relevant fields; whitespace-normalized multi-record extraction, not full DOM/page facsimile or person original. Exact records/dates separately stated in content.');const S='S-T0217-'+key,R='R-T0217-'+key;packs[key]={id:'T-0217/'+key+'-routing-v1',actor:'gpt-6.1-sol T-0217',reason:'T-0217 AC1–4: '+title+'; bounded routing only; no full probate/order/contact/private-life expansion. Original provider/image availability is not inferred from missing links.',media:[m],changes:[news(S,'source',{title,archive_reference:ref,source_class:key==='mil'?'K-27':'K-14',description:txt}),news(R,'record',{source_id:S,record_type:'catalogue_routing',locator:ref,dependence_note:'Visible catalogue descriptions, not independently corroborating person evidence; preserved extract hash identifies only this representation.'},{evidence:[B(S)],media:[{id:m.id,region:'All relevant extracted catalogue fields; unit boundaries explicit in text.'}]})]};}
const e='Emma: FIIa65(1963) exact SE/HLA/1040237/F/F II/F II a/65; alphabetical CIIc1(1930–1964, A–Ö häften), both Härnösand and Läsesal/no reproduction link in volume details. Own Emma register row/actnr unread; no digitisation-exhaustion conclusion.';
const a='Axel: Sundsvalls tingsrätt FII catalogue lists1983 volumes90–99 (96a/b,98a/b); alphabetical DIVd1(1972–1985) in Härnösand, Läsesal/no reproduction link. Own Axel entry/actnr and jurisdiction unverified;1983volume details untested. Older blanket Skatteverket conclusion was already qualified in T0119; new catalogue disproves the general exclusion, not the custody of a located Axel act.';
const mil='Axel28965/21: catalogue Ro65=Sundsvalls västra is a candidate route only; no numberingguide/personrow confirms placement. Io5D2 lists1927–1941; Io21D3 lacks1919–1922 among listed1902–1926 volumes, Io21D2 ends1918; H/F1898–1915. No1921unit identified/read; no inferred regiment or no-service claim. Further exact1921placement requires a new identified unit/numberingguide, owner T0822 planning without execution here.';
function question(pack,id,p,title,body){pack.changes.push(news(id,'question',{subject_id:p,title,outcome:'OLÖST',body}));}
function search(pack,id,Q,S,outcome,body,scope){pack.changes.push(news(id,'search',{question_id:Q,source_id:S,scope_json:scope,outcome,body},{evidence:[B(S)]}));}
question(packs.emma,'Q-T0217-Emma1963','P-0246','Exact own probate index/act for Emma1963?',e+' Physical own register remains unread; no order/contact mandate. Reopen with accessible CIIc1 Henriksson/Larsson entry matching1963-05-22.');
search(packs.emma,'SEARCH-T0217-Emma1963-register','Q-T0217-Emma1963','S-T0217-emma','access_problem',e,{description:'Person routing blocked at own alphabetical record; catalogue read succeeds.',query:'Emma Petronella Eugenia Henriksson/Larsson,1963-05-22',bounds:{catalogue:'FIIa65 and CIIc1 details;2catalogueunits+1register metadata incl register-series guidance',original_read:'none'},provider_catalogue_versions:{'SE/HLA/1040237/F/F II/F II a/65':'Senast ändrad2007-01-10 00:00:00','SE/HLA/1040237/C/C II/C II c/1':'Senast ändrad2026-01-29 16:40:40'},image_provider_version:'unknown; no image opened',reactivation:'CIIc1 actual alphabetical entry becomes accessible or owner separately authorizes retrieval.'});
packs.emma.changes.push(revise('F-P-0246-source_route-probate1963',d=>{d.value_json.archive='SE/HLA/1040237/F/F II/F II a/65(1963); SE/HLA/1040237/C/C II/C II c/1(1930–1964)';d.value_json.result=e;},[B('R-T0217-emma')]));
packs.emma.changes.push(revise('THEME-P-0246-EKO',d=>{d.body='| EKO | ÖPPET | '+e+' Own economy remains unread. | T-0217 |\n';},[B('R-T0217-emma')]));
packs.emma.changes.push(revise('PATH-P-0246-KP-03',d=>{replace(d,'C-0936/S-0733 fann ingen bild på F II a/65 eller C II c:s bouppteckningsregister. Detta avgränsar det prövade katalogläget, inte alla möjliga kopior.',e);replace(d,'katalogprov utfört, men ingen egen bouppteckning läst.','T-0217 explicit volume/register metadata read completed; own alphabetical entry and probate unread.');replace(d,'T-0217 preciserar Emmas ekonomiska routing, T-0216 hennes dödspost.','T-0217 has bounded catalogue result above; own CIIc1 entry/act retrieval remains unresolved, further planning T0822; T-0216 owns deathpost.');},[B('R-T0217-emma')]));
question(packs.axel,'Q-T0217-Axel1983','P-0241','Exact own probate index/act and jurisdiction for Axel1983?',a+' Reopen when DIVd1 own Henriksson entry matching1983-04-20 is accessible or precise death-domicile supplies jurisdiction.');
search(packs.axel,'SEARCH-T0217-Axel1983-register','Q-T0217-Axel1983','S-T0217-axel','access_problem',a,{description:'Own index row unread; exact catalogue lists and register details read.',query:'Axel Edvin Henriksson,1983-04-20',bounds:{catalogue:'FIIseries1983rows90–99;DIVdseries;DIVd1detail,2catalogueunits+1register',original_read:'none'},provider_catalogue_versions:{'SE/HLA/1040239/D/D IV/D IV d/1':'Senast ändrad2014-07-01 14:34:09','SE/HLA/1040239/F/F II':'unknown; catalogue lastmodified not inspected'},image_provider_version:'unknown; no original read',reactivation:'Actual DIVd1 entry accessible or exact jurisdiction/death-domicile newly established.'});
packs.axel.changes.push(revise('THEME-P-0241-EKO',d=>{d.body='| EKO | ÖPPET | Torpartitel does not prove ownership absence. '+a+' | T-0217 |\n';},[B('R-T0217-axel')]));
packs.axel.changes.push(revise('PATH-P-0241-KP-03',d=>{replace(d,'C-0936/S-0733 fann ingen bild på 1963 volymen eller dess register. Förvaring 1983 och exakt inskrivningshandling är inte kontrollerade; jämförelse med annan person ger inget åtkomstslut.',e+'\n'+a+' Military exact1921unit remains unresolved; comparison with other persons proves no access endpoint.');replace(d,'T-0217 får pröva exakta routingfrågor.','T-0217 probate catalogue passage has the bounded outcome above; unresolved own rows/jurisdiction remain for T0822 planning.');},[B('R-T0217-emma'),B('R-T0217-axel')]));
packs.axel.changes.push(revise('F-P-0241-research_gaps-source-provenance',d=>{const old='Personriktig katalog-/boxreferens för bouppteckningen1983 och värnpliktsväg ej verifierad';if(d.value_json.unresolved.filter(x=>x===old).length!==1)throw Error('gapmatch');d.value_json.unresolved=d.value_json.unresolved.map(x=>x===old?a+' Exact1921militaryunit remains unverified.':x);d.value_json.scope+=' T-0217 has now read bounded probate catalogue metadata; no personal originals.';},[B('R-T0217-axel')]));
question(packs.mil,'Q-T0217-Axel1921','P-0241','Which exact1921militaryunit contains Axel28965/21?',mil);
search(packs.mil,'SEARCH-T0217-Axel1921-routing','Q-T0217-Axel1921','S-T0217-mil','inconclusive',mil,{description:'Finite linked catalogue discovery;0 identified1921units opened; yearfilter MCP gives out-of-range candidates and is not a yearbound certification.',query:'28965/21; Ro65; linked Io5/Io21 lists',bounds:{lists:'Io5Ro65D2;Io21Ro65D3/D2;Io21Ro65H/F; no district sweep',original_read:'none'},provider_catalogue_versions:{'SE/KrA/0473/B/05/005:Ö':'2026-07-23 09:42:00','SE/KrA/0473/B/21/002:Ö':'2020-12-01 11:03:00','SE/KrA/0473/B/21/002:H':'2020-08-31 16:30:52','series_lists':'unknown; no own series modification inspected'},reactivation:'Independent numberingguide or identified1921volume; new bounded approval required outside T0217.'});
packs.mil.changes.push(revise('THEME-P-0241-MIL',d=>{d.body='| MIL | ÖPPET | '+mil+' | T-0217 |\n';},[B('R-T0217-mil')]));
// Second KP03 revision builds explicitly on the preceding reviewed Axel probate revision.
const pathChange=packs.axel.changes.find(x=>x.id==='PATH-P-0241-KP-03');const nextPath=structuredClone(pathChange);nextPath.expectedVersion++;nextPath.data.body+='\nT-0217 military disposition: '+mil+'\n';nextPath.evidence.push(B('R-T0217-mil'));packs.mil.changes.push(nextPath);
const gapChange=packs.axel.changes.find(x=>x.id==='F-P-0241-research_gaps-source-provenance');const nextGap=structuredClone(gapChange);nextGap.expectedVersion++;nextGap.data.value_json.unresolved=nextGap.data.value_json.unresolved.map(x=>x.includes('Exact1921militaryunit remains unverified.')?x.replace('Exact1921militaryunit remains unverified.',mil):x);nextGap.evidence.push(B('R-T0217-mil'));packs.mil.changes.push(nextGap);
const probe='mil-initial-query-v1.json',probeText=fs.readFileSync(`${dir}/sources/${probe}`),ps='S-T0217-MCP-militaryquery';packs.mil.changes.push(news(ps,'source',{title:'Riksarkivet search_metadata exact query response,2026-10-08',archive_reference:'Riksarkivet MCP search_metadata',source_class:'K-27',description:probeText.toString()}));
search(packs.mil,'SEARCH-T0217-MCP-inskrivnings65','Q-T0217-Axel1921',ps,'negative','Exact initial metadata query inskrivningsområde65 returned no results. Subsequent Ro65 query returned positive catalogue routes. Initial zero is question visibility only, not absence of source/person/service.',{description:'Initial MCP metadata query result, not a person-source search.',query:'inskrivningsområde 65',bounds:{dataset:'Riksarkivet search_metadata;only_digitised=false;offset0;limit10',question_scope:'catalogue phrase only; no person originals'},search_memory:{format:'search-memory/1',subjects:['P-0241'],performed_at:fs.statSync(`${dir}/sources/${probe}`).mtime.toISOString(),method:'MCP search_metadata exact phrase/fields; positive control/reformulation rullföringsområde65 produced6metadata routes. Timestamp is preservation of returned reply in this session, not exact request-start time.',material:{identifier:'Riksarkivet MCP search_metadata query=inskrivningsområde65,offset0,limit10,only_digitised=false',source_version:1,provider_version:{value:null,unknown_reason:'MCP reply exposes no catalogue/index revision.'},snapshot:{sha256:hash(probeText),reference:`${dir}/sources/${probe}`}},coverage:{completed:true,limitations:'Only one exact metadata phrase query; subsequent Ro65 reformulation positive; no original search or independent archival absence evidence.'},reactivation:['New catalogue/index visibility or a specifically changed query; use already positive Ro65 routes before repeating this phrase.']}});
const unknown=readCurrent(db,'LIFE-T0792-P0241');for(const p of ['P0241','P0246'])consequences.push({object:'LIFE-T0792-'+p,decision:'retain failed life review; datedT0792 baseline retained, catalogue routing now separately amended; no own source economics/service newly read, no level upgrade'});
for(const group of ['identity_review/1','tree_effect/1'])for(const p of ['P0241','P0246'])consequences.push({object:(group==='identity_review/1'?'IDENTITY-REVIEW-T0787-':'TREE-EFFECT-T0787-')+p,decision:'retain unchanged; no identity, relation or pedigree-affecting source finding.'});
for(const key of Object.keys(packs)){fs.writeFileSync(`${dir}/${key}-routing-v1.json`,JSON.stringify(packs[key],null,2)+'\n');}
fs.writeFileSync(`${dir}/consequence-table-v1.json`,JSON.stringify(consequences,null,2)+'\n');
console.log(JSON.stringify(Object.entries(packs).map(([k,v])=>({passage:k,changes:v.changes.length,media:v.media.length,sha256:hash(fs.readFileSync(`${dir}/${k}-routing-v1.json`))}))));db.close();
