import pathlib,sqlite3,json,hashlib,datetime,subprocess,shutil
B=pathlib.Path(__file__).resolve().parent; ROOT=B.parents[1]; DB=ROOT/'genealogy2/data/research.sqlite'
def save(n,x): (B/n).write_text(json.dumps(x,ensure_ascii=False,indent=2)+'\n')
def sha(p):return hashlib.sha256(p.read_bytes()).hexdigest()
c=sqlite3.connect('file:'+str(DB)+'?mode=ro',uri=True);c.row_factory=sqlite3.Row
connection=c
exec((ROOT/'evaluations/T-0778/native_payload.py').read_text())
assert sha(DB)=='3a6f2c4ff32af5f620455cffa0c8baf983666b5815bb166624526506b5b9af20'
assert c.execute('select max(sequence) from operation_payload').fetchone()[0]==495
(B/'clone').mkdir(exist_ok=True)
base=B/'clone/baseline.sqlite';stage=B/'clone/stage.sqlite'
if not base.exists():
 z=sqlite3.connect(base);c.backup(z);z.close();shutil.copyfile(base,stage)
now=datetime.datetime.now(datetime.timezone.utc).isoformat()
subjects=['P-0003','P-0042','P-0043'];sourcec='S-T0228-Flen5c';changes=[];media=[]
images=json.loads((B/'source-access-and-originals-v1.json').read_text())['images']
for im in images:
 p=ROOT/im['path']; key=p.stem
 r=subprocess.run(['node','genealogy2/cli.mjs','stage-media',str(p),'--provenance',f'T-0228; Flens kyrkoarkiv A II a/5 b eller 5 c, bild {key}; 2026-10-08 official Chrome Hela bilden. Fulloriginal, ingen cookie-/credentialextraktion.'],cwd=ROOT,capture_output=True,text=True,check=True)
 asset=json.loads(r.stdout);media.append(asset);im['media']=asset
save('staged-media-v1.json',images)
def new(oid,kind,data,evidence=(),**extra):
 x={'id':oid,'kind':kind,'expectedVersion':None,'data':data,'disposition':'recorded','rationale':'T-0228 AC: exakt avgränsad routing/läsning, inte full persons- eller källslutsats.','evidence':list(evidence),**extra};changes.append(x);return x
def ev(oid,v=1,role='supports'):return {'object':oid,'version':v,'role':role}
new(sourcec,'source',{'title':'Flens kyrkoarkiv, A II a/5 c (1923–1930)','archive_reference':'SE/ULA/10257/A II a/5 c','source_class':'K-01','description':'Riksarkivet i Uppsala. MCP search_metadata keyword="Flen A II a 5 c", offset0 gav exaktvolym och reproduktion00153997. Rätt IIIF-manifest https://lbiiif.riksarkivet.se/arkis!00153997/manifest bevarat evaluations/T-0228/manifest-00153997.json. Katalog https://sok.riksarkivet.se/arkiv/yMBzRBOITKHfkq00aG21xB. Manifestmetadata är routing, inte personbelägg. Digital leverantörsversion okänd; bild1 visar reproduktionsdatum2016-09-16, ingen innehållsversion härleds därav.'})
readings={
'00153997_00001':('reproduction_cover','Reproduktionsskylt','Skylt: SE/ULA/10257/A II a/5 c; 00153997;04Flens kyrkoarkiv A II a/5 c1923–1930; Församlingsbok; Riksarkivet MKCFränsta;2016-09-16. Metadata, inga personrader.'),
'00153997_00002':('volume_binding','Bandets pärmar/rygg','Bandrygg och pärm: AII5c,1923–1930; Församlingsbok för FlenIII municipalsamhället. Metadata, ingen adress-/personpost. Svag undertext till sidomfång ej nytolkad.'),
'00153997_00003':('place_index','Blankt register och titelblad','Tryckta registerrubriker: Byar och särskilt benämnda Fastigheter; Fol. Två kolumnpar på vänstersidan har ingen handskriven ort/folio. Hela registerytan kontrollerad. Högersida: Församlingsbok för Flens församling i Villåttinge kontrakt av Strängnäs stift, åren1923–1930; boken innehåller400uppslag. Inget Ljungbacka/Turegatan8, Eriksro/Drottninggatan3 eller återbrukad råvariant Sjönsöbacka[?]/Furugatan8 kan lokaliseras genom detta blankregister. Inget personindex där.'),
'00153996_00005':('place_index','Register/Municipalsamhället, första bilden','Hela registerytan på höger sida och instruktionernas avgränsning på vänster kontrollerade. Registerrubriker: Byar och särskilt benämnda Fastigheter; Fol. Inledande handskrift Fol.401–500: gårdar å Nybble och Lätta mark[?]. Bland orterna står Eriksberg n:o1 och n:o2; detta läses inte Eriksro och ger inte målpersonerna. Inga exakt sökta Ljungbacka/Turegatan8, Eriksro/Drottninggatan3 eller äldre råvarianter Sjönsöbacka[?]/Furugatan8 lokaliserade i bildens register. Tryckta instruktioner är tabell-/bokföringsnorm, inte målpersonfakta. Alla positiva övriga orter är orelaterad indexkontext och adopteras inte.'),
'00153996_00006':('place_index','Registerfortsättning, båda sidor','Tryckta rubriker: Byar och särskilt benämnda Fastigheter; Fol. Vänstersidans första par fortsätter ortlistan; andra paret har Från fol.575: gårdar å [osäker mark-/ägningstext]. Övriga ort-/folioreferenser är indexkontext, inte målpersonspår. Högersidans båda par är tomma. Hela bilden kontrollerad för Ljungbacka/Turegatan8 och Eriksro/Drottninggatan3 samt bevarade råvarianter; ingen säker målfoliorouting. Osäker instruktionsort används inte som nyckel.'),
'00153997_00101':('household_page','Sida914, Nydala/Fredsgatan8','Båda sidnummer914; rubrik Nydala och Fredsgatan8. Hela uppslagets25rader, namn-/roll-/ortytor och marginaler kontrollerade för målpersonerna Karl Fredrik Jansson, Charlotta Wilhelmina Larsson och Arne Godvig/Jansson (starkare redan accepterade Arne Georg ändras inte). Inga målpersoner. Endast andra personrader1,2,6 är inskrivna; övriga rader är tomma. Inga målpersonbundna fortsättningsnycklar. Ingen full biografisk utvinning/adoption av dessa orelaterade personer. Alla18kolumnrubriker i tabellens struktur kontrollerade som sökytans avgränsning, men orelaterade personers övriga data inte avskrivna eller behandlade som tomma. Det osäkra gamla914-testet är därmed negativt just på detta folio; detta bevisar inte att familjen saknas i volymen.')}
recordids={}
for im in images:
 key=pathlib.Path(im['path']).stem;s=sourcec if key.startswith('00153997') else 'S-0706';rt,loc,txt=readings[key];rid='R-T0228-'+key;recordids[key]=rid
 new(rid,'record',{'source_id':s,'record_type':rt,'locator':f'{key}; {loc}; official viewer https://sok.riksarkivet.se/bildvisning/{key}','dependence_note':'En originalbild; metadata, index och original ger skilda beläggsomfång.'},[ev(s,1,'context')],media=[{'id':im['media']['id'],'region':'hela bilden'}])
 new('TR-T0228-'+key,'transcription',{'record_id':rid,'text':txt,'reading_note':'Sol; visuellt läst bevarat fulloriginal2026-10-08. Exakt avgränsad relevant routing-/sökläsning. Orelaterade index- och personuppgifter är inte målpersonfakta.'},[ev(rid)])
searches=[]
react=['Ny personbunden sidhänvisning eller säkert adress-/personregister för1923–1930 som kan lokaliseras inom nytt beslutat bounded omfång.','Ändrat material eller identifierat läsfel motiverar nytt exakt pass; upprepa inte oförändrat tillräckligt omfång.']
for key in ('00153997_00003','00153996_00005','00153996_00006','00153997_00101'):
 im=next(x for x in images if pathlib.Path(x['path']).stem==key);s=sourcec if key.startswith('00153997') else 'S-0706';oid='SEARCH-T0228-'+key
 body=readings[key][2];scope={'description':readings[key][1], 'query':'Ljungbacka/Turegatan8; Eriksro/Drottninggatan3; bevarad äldre råvariant Sjönsöbacka[?]/Furugatan8; Karl Fredrik/Charlotta Wilhelmina/Arne Godvig(Jansson)','bounds':{'year_period':'1923–1930','archive':'SE/ULA/10257','image':key,'coverage':'hela bildens registeryta' if key!='00153997_00101' else 'sida914 båda sidor/rader1–25 med marginaler'},'search_memory':{'format':'search-memory/1','subjects':subjects,'performed_at':now,'method':'Slutlig visuell sök-/omfångskontroll av bevarat fulloriginal; performed_at anger denna slutkontroll, tidigare nedladdnings-/lokaliseringsförsök bevarade separat.','material':{'identifier':key,'source_version':1,'provider_version':{'value':None,'unknown_reason':'Ingen leverantörsversion exponerad; modell@1 är inte en leverantörsversion.'},'snapshot':{'sha256':im['sha256'],'reference':im['path']}},'coverage':{'completed':True,'limitations':'Endast exakt deklarerad sökyta. Indexroutingnoll är inte negativ personevidens. Inga andra folios eller hela volymer genomlästa.'},'reactivation':react}}
 new(oid,'search',{'question_id':'P-0003/Q-03','source_id':s,'scope_json':scope,'outcome':'negative','body':body},[ev(s,1,'context'),ev(recordids[key])],evidenceStatus='NEGATIVE');searches.append(oid)
for key in ('00153997_00004','00153996_00005','00153996_00006'):
 s=sourcec if key.startswith('00153997') else 'S-0706';reused=json.loads((B/'direct-5b-register-access-v1.json').read_text());receipt=next((x for x in reused if x['key']==key),None)
 at=receipt['at'] if receipt else now
 new('SEARCH-T0228-DIRECT-'+key,'search',{'question_id':'P-0003/Q-03','source_id':s,'outcome':'access_problem','body':'DirektIIIF med egen visare som Referer gav401. Inte ett person-/källnoll. Chromevisaren fungerade; aktuella relevanta registerbilder bevarades genom official Hela bilden. Bild5c801 lästes aldrig.','scope_json':{'description':'Exakt direktbildprov','query':'GET https://lbiiif.riksarkivet.se/arkis!'+key+'/full/max/0/default.jpg','bounds':{'image':key,'http_status':401},'search_memory':{'format':'search-memory/1','subjects':subjects,'performed_at':at,'method':'DirektIIIF GET med bildens egen Referer. För5c00004 är performed_at dokumentationstid; försöksdatum2026-10-08 bevarat, exakt försökstid saknas.','material':{'identifier':key,'source_version':1,'provider_version':{'value':None,'unknown_reason':'Inte exponerad'},'snapshot':{'sha256':None,'unavailable_reason':'Rå401body inte bevarad; exakta URL/status i source-access-and-originals-v1.json eller direct-5b-register-access-v1.json. Inga credentials.'}},'coverage':{'completed':False,'limitations':'Åtkomstprov; ingen originalpersonläsning genom detta anrop.'},'reactivation':['Återuppta exaktbild via fungerande officialvisare vid sakbehov; ingen påstådd digitaliseringsgräns.']}}},[ev(s,1,'context')])
summary='T-0228,2026-10-08: OLÖST INOM PRÖVAT OMFÅNG för hushållsbryggan1923–1930. Två mellanvolymdelar5b/5c prövade.5cbild3 är blankt register;5bbild5–6 ger ingen säker målfoliorouting. Ett uttryckligt osäkert återbrukstest av äldre914 gav5cfol914/Nydala,Fredsgatan8 utan målpersoner i hela25radsuppslaget. Detta är endast lokal index-/foliorouting, inte frånvaro av familjen i Flen eller volymen. C0910 och T0778/C1047:s accepterade familjerader återbrukas; C0910:s exakt återbrukade Charlottarad2 och Arnerad7 har egna ut16/17 blankt; C1047:s tre egna rader12/13/15 har in9/10 blankt. Dessa exakt lästa fält ger ingen säker5periodnyckel; Karls äldre utkolumner generaliseras inte som hushållsblank.563/30 och638/30 tillhör6b:s interna1930kedja, ingen5b638väg. Äldre bevarad C0910råheader Sjönsöbacka[?]/Furugatan8(TR-T0676-FLEN914-UPPER-45@1) kvarstår jämte äldre profilnyckel Ljungbacka/Turegatan8; ingen ny originaltolkning eller identitetsrättelse. Ingen tredje volymdel eller ytterligare gissningsfolio öppnas. Tvådelstaket är slut,1avhögst3personfolios läst. Framtida konkret person-/gaturegisterrouting kräver separat beslutad passage hos Wotan/Project Control; dagens källor är inte uttömda. Registrering belägger inte första eller kontinuerlig faktisk omsorg. Övriga frågor och båda granskningsnivåernas grader består.'
bases=[ev(x) for x in searches]+[ev('R-e67bb6868b81121b2d3f0732',1,'context'),ev('TR-T0676-FLEN914-UPPER-45',1,'context'),ev('R-33b612f0da2f3aa6fc2addc7',2,'context'),ev('TR-T0778-C1047-family-fullfields',1,'context')]
for p in subjects:new('RESULT-T0228-'+p,'assessment',{'subject_id':p,'criteria':'bounded_research_result/T-0228','outcome':'unresolved_within_scope','body':summary},bases,caveat='Livsbildskomplettering. Ingen ny identitets-/föräldragrind eller full life_picture_review. OWNER_CONFIRMED och starkare stöd oförändrade.')
revised=['P-0003/Q-03','P-0042/Q-01','PATH-P-0003-KP-03','PATH-P-0042-KP-02','PATH-P-0043-KP-02','KEY-P-0003-e24f76fd20a2','KEY-P-0043-db82c256ce8e']
consequences=[]
for oid in revised:
 row=c.execute('select * from current_revision where object_id=?',(oid,)).fetchone();x=existing(oid,row['version']);old=json.loads(json.dumps(x));x['data']['body']+='\n\n'+summary
 if oid=='PATH-P-0003-KP-03':x['data']['outcome']+=' T-0228: lokala register-/foliotest negativa; hushållsbryggan OLÖST INOM PRÖVAT OMFÅNG.'
 x['rationale']+=' T-0228 AC: append-only aktualisering med avgränsat sökminne, fulla äldre sakdata/grader/stöd bevarade.'
 for b in bases:
  if b not in x['evidence']:x['evidence'].append(b)
 changes.append(x);consequences.append({'id':oid,'version':row['version'],'field':'data.body (och endast PATH-P0003 outcome)','old':old,'new':x,'decision':'append bounded negative/inconclusive result; preserve prior content and outcome except qualified path'} )
for p in ('P0003','P0042','P0043'):
 d=json.loads((B/('baseline-'+p+'.json')).read_text())
 for g in ('themes','requirements','reviews'):
  for o in d['research'][g]:consequences.append({'id':o['object_id'],'version':o['version'],'field':'all','decision':'retain','reason':'Ingen ny målpersonpost eller personfaktum. Befintligt individuellt utfall och eget granskningsscope består; nollrouting fyller inte PK-livsluckan eller uppgraderar något tema/grind.'})
save('operation-v1.json',{'id':'T-0228/bounded-Flen-1923-1930-v1','actor':'Codex gpt-6.1-sol','reason':'T-0228 AC: exakt återbruk och OLÖST INOM PRÖVAT OMFÅNG förP0003/P0042/P0043 hushållsbrygga; beständigt sökminne och full relevant routingutvinning;2volymdelar/1personfolio avhögst3. Ingen identitets-/relations-/OWNER-/grindändring.','media':media,'changes':changes})
save('individual-consequences-v1.json',consequences)
save('baseline-lock-v1.json',{'db_file_sha256':sha(DB),'clone_sha256':sha(base),'journal':495,'pending':c.execute("select count(*) from review_request q where not exists(select 1 from review_resolution s where s.request_id=q.id)").fetchone()[0],'operation_sha256':sha(B/'operation-v1.json'),'created_at':now,'stage':str(stage.relative_to(ROOT)),'changes':len(changes),'revised':revised,'new':len(changes)-len(revised),'caps':{'parts':2,'person_folios':1},'source_original_hashes':[{k:im[k] for k in ('path','sha256','bytes')} for im in images]})
print('package',len(changes),'changes;',len(media),'media;',sha(B/'operation-v1.json'))
