"""Manifest-only repair. Reuse completed read-only outputs; never rerun CLI."""
from pathlib import Path
import hashlib,json,sqlite3,time
R=Path(__file__).resolve().parents[3];O=R/'evaluations/T-0790/preparation';S=O/'reviewed-stage-v1';D=O/'final-stage456-readonly-capture-v1';start=time.monotonic()
def pin(p):return {'path':str(p.relative_to(R)),'sha256':hashlib.sha256(p.read_bytes()).hexdigest()}
def load(p):return json.loads(p.read_text())
assert not (D/'final-stage-package-manifest-v1.json').exists()
(D/'initial-manifest-path-failure-preserved-v1.json').write_text(json.dumps({'failed_helper_pin':pin(O/'capture_final_reviewed_stage_readonly_v1.py'),'failed_action':'final manifest root result pin read, after all10readonly CLI outputs completed','wrong_path':'evaluations/T-0790/preparation/nine-resolution-actual-v2/result.json','correct_path':'evaluations/T-0790/preparation/reviewed-stage-v1/nine-resolution-actual-v2/result.json','runtime_db_mutation':False,'retry_or_capture_rerun':False,'initial_monotonic_duration':'unobserved because helper stopped before receipt; no inferred zero'},indent=2)+'\n')
labels=['P-0004-person','P-0210-person','P-0005-person','P-0006-person','P-0211-person','P-0212-person','verify','inventory','Adam-verified','Axel-verified']
for label in labels:assert load(D/(label+'.process.json'))['returncode']==0;load(D/(label+'.json'))
assert load(D/'verify.json')['ok'] is True
rootresult=load(S/'nine-resolution-actual-v2/result.json');assert rootresult['actual_state']=={'journal_head':456,'pending':0};db=R/rootresult['stage_db_pin']['path'];assert pin(db)==rootresult['stage_db_pin'];proof=load(D/'final456-only-three-appendtables-and-full-native-preservation.json');assert proof['only_changed_table_names']==['operation','operation_payload','review_resolution'];assert proof['full40current_and9context_exact'] is True
bs=load(O/'baseline-state.json');assert pin(R/'genealogy2/data/research.sqlite')==bs['main']
operations=[pin(O/'materialized-source-v3-literal-v1/operation-literal.json'),pin(O/'exact-nine-request-only-resolution-draft-v1/resolve-literal.json')]
reused={}
for label in ['verify-assets','verify-source']:
 assert load(S/(label+'.json'))['ok'] is True;reused[label]={'pin':pin(S/(label+'.json')),'reuse_basis':pin(D/'final456-only-three-appendtables-and-full-native-preservation.json'),'reason':'All50 comparison proves only operation/payload/resolution appended; native/source/media/assets and their ordered arrays exact successful455 state.'}
validators={label:(pin(D/(label+'.json')) if label in ['verify','inventory','Adam-verified','Axel-verified'] else reused[label]['pin']) for label in ['verify','verify-assets','verify-source','inventory','Adam-verified','Axel-verified']}
m={'task':'T-0790','actual_final_state':rootresult['actual_state'],'reviewed_stage_DB_pin':pin(db),'ordered_operations':operations,'consequence_table_pin':pin(O/'materialized-source-v3-literal-v1/individual-consequence-table.json'),'resolution_table_pin':pin(O/'exact-nine-request-only-resolution-draft-v1/nine-individual-resolution-table.json'),'source_spec_pin':pin(R/'evaluations/T-0790/source-review/settled-90-dispositions-and-literal-field-decisions-v3.json'),'preservation_proof_pin':pin(D/'final456-only-three-appendtables-and-full-native-preservation.json'),'full_native_current_context_pin':pin(D/'final-stage-full40-current-targets-and-nine-context-native.json'),'six_final_person_views':{p:pin(D/(p+'-person.json')) for p in ['P-0004','P-0210','P-0005','P-0006','P-0211','P-0212']},'six_final_validator_pins':validators,'reused_checks':reused,'first455_result_pin':pin(S/'result.json'),'root_same_stage_resolution_result_pin':pin(S/'nine-resolution-actual-v2/result.json'),'input_source_gates':[pin(R/p) for p in ['evaluations/T-0790/source-review/materialized-v1-prestage-source-gate.json','evaluations/T-0790/independent-review/prestage-source-gate-v1.json','evaluations/T-0790/source-review/exact-nine-resolution-prestage-gate-v1.json','evaluations/T-0790/independent-review/exact-nine-same-stage-resolution-gate-v1.json']],'manifest_only_amendment_no_reread':True,'source_final_approval':False,'canonical_apply':False,'amendment_elapsed_monotonic_seconds':time.monotonic()-start}
p=D/'final-stage-package-manifest-v2.json';assert not p.exists();p.write_text(json.dumps(m,ensure_ascii=False,indent=2)+'\n');print(json.dumps({'manifest':pin(p),'elapsed':time.monotonic()-start}))
