import json,pathlib,hashlib,importlib.util,time,copy
R=pathlib.Path.cwd();D=R/'evaluations/T-0818';I=D/'implementation';start=time.monotonic();sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();sf=D/'primary-settled-actual57-resolution-source-spec-v3.json';assert sha(sf)=='38c98a06ac4e92165b58fba0224c85430537e3e53353a343db9b391ac42775c3';spec=json.load(open(sf));gate=D/'independent-actual57-settlement-source-gate-v1.json';assert sha(gate)=='3e76c6e029c62ab4455213165172f8a0da883a6ebe8dc8305ce968f4c280c104';hp=R/'evaluations/T-0781/implementation/stage_exact_two_settled_package_v2.py';s=importlib.util.spec_from_file_location('h',hp);h=importlib.util.module_from_spec(s);s.loader.exec_module(h);db=I/'stage487-v1/stage.sqlite';c=h.conn(db);assert h.state(c)=={'journal_head':487,'pending':57}
def save(n,v):
 p=I/n;assert not p.exists();p.write_text(json.dumps(v,ensure_ascii=False,indent=2)+'\n');return p
def decoded(n):
 n=copy.deepcopy(n)
 for k,v in n['data'].items():
  if k.endswith('_json')and isinstance(v,str):n['data'][k]=json.loads(v)
 return n
pending=[dict(x)for x in c.execute('select q.*from review_request q left join review_resolution r on r.request_id=q.id where r.request_id is null order by q.rowid')];assert [x['id']for x in pending]==[x['request']for x in spec['resolutions']];assert spec['native_changes']==[];contexts=json.load(open(I/'stage487-v1/actual-pending-contexts-initial.json'));rows=[];retains=[]
for entry in spec['native_retains']:
 n=h.native(c,entry['revision_id']);assert n==entry['native']or decoded(n)==entry['native'];assert h.current(c,n['object_id'])==n['id'];retains.append({'revision_id':n['id'],'old_native':n,'source_disposition':'RETAIN_EXACT','source_retention_entry':entry})
assert len(retains)==len({x['revision_id']for x in retains})==41
for q,disp,context in zip(pending,spec['resolutions'],contexts):
 assert q==context['request'];assert q['affected_revision_id']==disp['affected_revision_id']and q['changed_revision_id']==disp['changed_revision_id'];assert disp['required_changes']==[]and disp['evidence_rebinds']==[];rr={'request':disp['request'],'rationale':disp['rationale']};assert rr['rationale'];rows.append({'actual_full_context':context,'exact_native_resolution':rr,'source_disposition':disp,'full_current_target_retained':h.native(c,q['affected_revision_id'])})
op={'id':'T-0818/57-individual-dependency-retains-v1','actor':'Codex / settled Astra decisions','reason':'T-0818 AC1–6, dependency preservation: 57 individually source-reviewed resolutions retain41 exact native targets without fields or evidence rebinds. Controlled canonical apply remains root-only after exact SOURCE approval and verified baseline.','dependencyReviewVersion':2,'changes':[],'resolve':[x['exact_native_resolution']for x in rows]};p=save('57-resolution-operation-v1.json',op);table={'operation_sha256':sha(p),'source_spec':{'path':str(sf.relative_to(R)),'sha256':sha(sf)},'changes':[],'individual_request_consequences':rows,'retains':retains,'unique_retained_targets':41,'schema_preflight':{'changes_empty':True,'all_resolution_keys_exact':all(set(x)=={'request','rationale'}for x in op['resolve']),'ordered_actual57_request_bijection':True,'all41_current_native_exact':True,'no_evidence_or_origin_changes':True},'elapsed_seconds':time.monotonic()-start};t=save('57-resolution-consequence-table-v1.json',table);print(json.dumps({'operation':sha(p),'table':sha(t),'elapsed':time.monotonic()-start}))
